### ISSUE TITLE
Gnome-disk-utility does not show model of NVME drive

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#10]
_From @brs17 on October 17, 2017 21:0_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.
```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
gnome-disk-utility 3.26

**Issue/Bug Description**
Model for NVME drives are not displayed in the gnome-disk-utility. `cat /sys/class/block/nvme0n1/device/model` shows the model number that should be displayed.

_Copied from original issue: pop-os/iso#170_

**Comment by isantop** [comment]
_From @jackpot51 on October 17, 2017 21:11_

Reported on launchpad: https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1724370

**Comment by brs17** [comment]
This issue seems to have been resolved. 

![disks](https://user-images.githubusercontent.com/7460774/68316609-f84a9600-0076-11ea-9a7d-9e6770d25932.png)
