### ISSUE TITLE
20.04 unresponsive when coming back from suspend/lock

### ISSUE THREAD

**Issue by mbbroberg** [pop-os/pop#1006]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**

Every time I close the laptop or walk away and come back later, Pop!_OS is unresponsive or crashed. I unboxed this Lemur Pro on Thursday and it's happened frequently since then. I'll try to be as specific as possible about when it happens. To note: I have run all updates Pop Shop, `apt update` and `apt upgrade`, and updates through flatpak. 

- I most often use `Super + Esc` to lock the screen. When I come back, the login prompt is there, I enter my password and get to the OS. Within a few seconds of using an application, it becomes unresponsive to keyboard inputs. I can move the cursor but no input is accepted. I hard reboot using the power button. 
- Other times (3-4 so far), I close the lid. Sometimes it responds like described above, others I open and the display is black, CPU fan is running loudly, and no input is accepted. I hard reboot again. 

**Steps to reproduce (if you know):**

- Close lid or lock the computer.
- Wait some time (I haven't tested this part systematically)
- Unlock from the GNOME prompt
- Locked up / freezing occurs

**Expected behavior:**

- Not that :sweat_smile: 

**Other Notes:**

- I tend to have terminal open and firefox with a small number of tabs open. I use Firefox profiles and add-ons, but nothing that's been performing poorly during normal usage. 
- I've added a handful of GNOME extensions that if you can give me a command to do so I'm happy to list out.

**Comment by maxaubry** [comment]
Hello. I have some trouble when my laptop try to come back from suspend too. The laptop is unresponsive as the screen stays black and the front led shows that it's on sleep mode. I tried to add some options via the `kernelstub` command : 
```
Kernel Boot Options:.button.lid_init_state=open intel_idle.max_cstate=4 intel_iommu=on quiet splash mem_sleep_default=deep rcutree.rcu_idle_gp_delay=1
```

but the problem still occurs.
Today I tried to disable the HiDPI daemon and it's working as expected. So in my case it seems to be related with this HiDPI daemon. Could you try this workaround ?

**Comment by mbbroberg** [comment]
Thanks @maxaubry - I'm happy to try it out. What's the workaround exactly?

**Comment by maxaubry** [comment]
You can disable the HiDPI daemon in the settings panel, under the `display` menu.

**Comment by jacks84** [comment]
Same issue, thanks for the insight on the HiDPI disabling. Works

**Comment by mbbroberg** [comment]
FWIW this is no longer happening. I had memory errors in the kernel logs, removed the memory and reinstalled the OS (different problem / longer story), and that's it.
