### ISSUE TITLE
virtualbox 6.1 installation issue

### ISSUE THREAD

**Issue by flare04** [pop-os/pop#1010]
**Distribution (run `cat /etc/os-release`):**
 POP OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Installer

**Issue/Bug Description:**
The virtual box hard drive doesn't seem to be recognised as a valid location to install into. 
I tried someone elses tip of creating the partitions but no joy.
![VirtualBox_Pop_Os_11_05_2020_14_54_49](https://user-images.githubusercontent.com/1712083/81525611-9d348b80-9398-11ea-8adc-661c4189a5eb.png)
![VirtualBox_Pop_Os_11_05_2020_14_55_37](https://user-images.githubusercontent.com/1712083/81525617-a6bdf380-9398-11ea-9e7e-a28452f78844.png)

**Steps to reproduce (if you know):**
Create a virtualbox vm using Ubuntu 64 as template - following instructions from POP OS website

**Expected behavior:**
for disk to be recognised

**Other Notes:**

**Comment by flare04** [comment]
OK so I found out that the OS needs a min of 20G, increased size to 27G.  
Still no joy

**Comment by leviport** [comment]
Have you installed updates on the live environment before running the installer? A fix for a similar-sounding issue was merged on Monday: https://github.com/pop-os/distinst/pull/220

**Comment by jackpot51** [comment]
This will be fixed in the next ISO version

**Comment by jacobgkau** [comment]
Pop!_OS is able to be installed in VirtualBox as of now.
