### ISSUE TITLE
Acer Aspire ES1-533 Laptops - efibootmgr freezes install

### ISSUE THREAD

**Issue by jason-oliveira** [pop-os/pop#102]
**Reporter info**
I'm 38, male, and I enjoy long walks on the beach, and classical music/fine wines. But enough about me.

```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian

apt policy $PACKAGE NAME
efibootmgr:
   Installed: 15-1
   Candidate 15-1
   Version table:
 *** 15-1 500
          500 http://archive.ubuntu.com/ubuntu artful/main amd64 Packages
          100 /var/lib/dpkg/status
```

**Issue/Bug Description**
Acer Aspire ES1-533 Laptops hate efibootmgr writing to NVRAM the way that vegans hate a denver omelet. 

**Steps to reproduce (if you know)**
1) Have a good friend buy one of these god-forsaken laptops.
2) Download Pop!_OS and begin install, marvelling at how everything Just Works.
3) Wait for the part of the install where efibootmgr tries to write to NVRAM.
4) Enjoy as the busy mouse cursor freezes in its tracks, along with the rest of the install.

**Expected behavior**
Grub Installs to NVRAM, and writes the new entry to UEFI.

**Other Notes**
Ubuntu knows all about this bug:
https://bugs.launchpad.net/ubuntu/+source/grub-installer/+bug/1652090
They also suggest workarounds, that don't seem to be relevant to Pop!_OS:
https://askubuntu.com/questions/862946/unable-to-install-ubuntu-on-acer-aspire-es1-533
Similarly, Acer has a support thread on this same issue:
https://community.acer.com/en/discussion/471754/acer-aspire-es-15-es1-533-c3uw-legacy-bios-missing

**Comment by jason-oliveira** [comment]
Got Pop!_OS to install by giving ubiquity the -b flag. Now to get efibootmgr to love me again.

**Comment by jason-oliveira** [comment]
Was able to get Pop!_OS to boot by following the steps below:

sudo mount /dev/sda2 /mnt #sda2 is the root partition
sudo mkdir /mnt/boot/efi
sudo mount /dev/sda1 /mnt/boot/efi #sda1 is the efi partition

for i in /dev /dev/pts /proc /sys; do sudo mount -B $i /mnt$i; done
modprobe efivars # make sure this is loaded

-- notice the bootx64 file
efibootmgr --verbose

-- We will reinstall grub-install for a 64bit version
apt-get install --reinstall grub-efi-amd64
grub-install —no-nvram —root-directory=/mnt

chroot /mnt
update-grub
cd /boot/efi/EFI
cp -R ubuntu BOOT
cd BOOT cp grubx64.efi bootx64.efi

**Comment by brs17** [comment]
@jason-oliveira Thank you so much for your detailed issue report...and your humor! It definitely seems like work-around/fix has been found to get you back up and running Pop!_OS. 

Seeing that this is an issue with a specific piece of hardware (that is not a System76 machine), you're welcome to attempt to make the fix upstream with Ubuntu, or perhaps by having grub-install handle such an exception, but it is unlikely we'll be able to put time into the fix.

Thanks again for giving Pop!_OS a try and submitting bugs as you find them!
