### ISSUE TITLE
Lag/stutter in video while changing brightness

### ISSUE THREAD

**Issue by vneogi199** [pop-os/pop#103]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```) Pop!_OS  17.10 (Artful Aardvark)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
While playing videos on youtube or VLC if I try to change brightness, there is a certain lag in the video for that particular moment.

**Steps to reproduce (if you know)**
Changing brightness while playing videos.

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
@vneogi199, Thank you for filling this issue with Pop!_OS!

I had a few follow up questions for you that will hopefully help me recreate the issue.

First off, what hardware are you running Pop!_OS on? 

Does this machine have NVIDIA graphics hardware?

**Comment by vneogi199** [comment]
I'm running Pop OS on my Dell Vostro 3446 laptop which has NVIDIA GeForce GT 820M Graphics. Please find the detailed hardware info attached in the file below.
[hw.txt](https://github.com/pop-os/pop/files/1588606/hw.txt)

Do let me know if you need any more information.

**Comment by brs17** [comment]
Thank you @vneogi199, we have a few 8xxM series laptops, I hope to look into this shortly.

**Comment by brs17** [comment]
@vneogi199 So I tried to recreate your problem with a machine with an NVIDIA 860M card. I pulled up a video on youtube as well as tried that same video in vlc, and the video continued smooth playback when I would change the brightness of the laptop screen.

And this happens with every video you attempt to play?

**Comment by vneogi199** [comment]
Yes it happens to every video. Both online or offline, could you check by adjusting brightness via the keyboard controls.

**Comment by brs17** [comment]
That is exactly what I've been doing, playing a video and adjusting the screen brightness via the keyboard function controls

**Comment by sramkrishna** [comment]
Given that we can't seem to recreate this issue and we're not able to get someone else to say they are seeing the same thing - I"ll close it for now, if someone else sees this they can re-open and we can look at it a little more in-depth.

**Comment by ChaoticGamingINC** [comment]
Even i am having that same issue i have no idea why i am having this issue.
Specs:
i5-9300HF
GTX 1650
8gb gddr4 2667 mhz
