### ISSUE TITLE
Panel icons and widgets disappear after sleep/closing lid

### ISSUE THREAD

**Issue by vneogi199** [pop-os/pop#104]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```) Pop!_OS  17.10 (Artful Aardvark)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
When I put my laptop to sleep and then after waking it up and logging in, I observe that the icons on the top right and top center like volume, wifi and calendar widget have disappeared. Also the panel becomes transparent, which is not the case by default.
Normal: https://imgur.com/a/PbEkU
After logging back after opening lid: https://imgur.com/a/INdcp
Another thing to note is that this happens only after waking up from sleep and not while logging in normally after a reboot. Also, I'm able to get back the icons and widgets after restarting GNOME or restarting the laptop. My laptop has NVIDIA graphics and I have tried uninstalling and reinstalling the drivers as well as using open source drivers.

**Steps to reproduce (if you know)**
Closing the laptop's lid and then reopening it.

**Expected behavior**
Restore normal desktop with all icons and widgets present.

**Other Notes**
Please refer to the hardware configuration of my laptop in the attachment.
[hw.txt](https://github.com/pop-os/pop/files/1588623/hw.txt)

**Comment by sramkrishna** [comment]
That is very bizarre.  What machine are you using?  One thing you can do is use looking glass, type in <alt>-F2, and then type in 'lg' and press return.  You can also look at logs with:
journalctl /usr/bin/gnome-shell

See if there are any errors from gnome-shell that might give a clue on what is happening.

**Comment by vneogi199** [comment]
Please find attached the logs of journalctl command.
[logs.txt](https://github.com/pop-os/pop/files/1599847/logs.txt)

**Comment by sramkrishna** [comment]
Thanks!  Sorry for the late response.  You have a problem with one of your extensions.  Please remove all extensions and then see if you see the same problem.  Then one by one, turn on an extension and observe whether the problem exists.
