### ISSUE TITLE
Can't report bugs, and graphics broken

### ISSUE THREAD

**Issue by programmin1** [pop-os/pop#105]
**Reporter info**

```
 * Distribution - POP!_OS 17.10
```

**Issue/Bug Description**
I have tested Pop!OS and it was working... for a day or two. Now it has just an underscore and black screen after the P! startup screen.

Worse yet, apparently ubuntu-bug command is broken as it always says "This is not an official Pop!_OS package." This breaks all of user testing and reporting bugs to Ubuntu!

**Steps to reproduce (if you know)**
Install it on a Radeon HD6530D machine. Run updates.

**Expected behavior**
It should either work, or work after you try reinstalling graphics packages... or work after you dpkg-reconfigure xserver-xorg... Nothing has worked so far.

**Comment by brs17** [comment]
@programmin1 Thank you for trying out Pop!_OS and filing this bug!

Unfortunately I can not help in recreating or troubleshooting the graphics issue you have with the HD6530D as I do not have that card in the lab (or much if any AMD hardware at all, at this time). I will share this issue on our Mattermost chat and see if anyone in the community can help out.

**Comment by Aceler** [comment]
On my AMD machine, I need to press ALT+F2 after boot to switch to another console to see the desktop. This can be the case you have.

**Comment by sramkrishna** [comment]
@programmin1 can you see if this fix works for you?  @Aceler thank you for weighing in!

**Comment by programmin1** [comment]
Don't you mean Ctrl+Alt+F2?

**Comment by Aceler** [comment]
No, I mean ALT+F2, but actually, CTRL+ALT+F2 will do. For some reason, graphical environment starts on VT2, while initial boot process runs on VT1, so you need to switch to VT2. Both ways will work.

**Comment by brs17** [comment]
Not really sure what we can do regarding the AMD hardware issue. I may recommend that you ask around in the Pop!_Chat: [chat.pop-os.org](https://chat.pop-os.org) and see if anyone else has had a similar issue.

The ubuntu-bug issue has been opened as it's own issue [here](https://github.com/pop-os/pop/issues/113). I know there was a short offline discussion regarding solving the issue, going to follow up and get it out in writing.
