### ISSUE TITLE
May 21st Update broke the wifi adapter immediately

### ISSUE THREAD

**Issue by ramyk** [pop-os/pop#1052]
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Related package: Latest update

Issue description: Just had a notification about new existing updates today that I installed, it asked me then to restart the pc and as soon as I did so, the wifi settings disappeared and under the settings tab it says that there's no Wifi adapter found to be used.

Just to clarify, here's my network controller (output from _lspci_):
Network controller: Intel Corporation Wi-Fi 6 AX200 (rev 1a)

**Comment by jackpot51** [comment]
Try the following:

```
sudo apt-get purge backport-iwlwifi-dkms
```

**Comment by ramyk** [comment]
I know this would sound weird, but that's exactly what I've done after a bit of research and even after a reboot, it didn't solve the issue. Though after around 4 to 5 hours I rebooted again without doing anything as I didn't notice anything weird with the output of `dmesg` (just removed the old kernel and installed the new one with the build-essentials and some other normal stuff), and voilà it just worked again.

**Comment by jackpot51** [comment]
Whatever fixed it, I am glad it is working again

**Comment by ramyk** [comment]
Yeah, thanks for the quick response though
