### ISSUE TITLE
"Does not have a release file"

### ISSUE THREAD

**Issue by jiechenmc** [pop-os/pop#1054]
chenj7728@pop-os:~$ sudo apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [107 kB]    
Hit:3 http://dl.google.com/linux/chrome/deb stable InRelease                   
Hit:4 http://packages.microsoft.com/repos/vscode stable InRelease              
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease              
Hit:6 http://apt.pop-os.org/proprietary focal InRelease
Get:7 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Ign:8 http://ppa.launchpad.net/pypa/ppa/ubuntu focal InRelease
Hit:9 http://ppa.launchpad.net/system76/pop/ubuntu focal InRelease
Err:10 http://ppa.launchpad.net/pypa/ppa/ubuntu focal Release
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/pypa/ppa/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by mmstick** [comment]
That PPA doesn't support Focal

**Comment by jiechenmc** [comment]
How would I fix this issue?
