### ISSUE TITLE
GNOME Calendar app notifications

### ISSUE THREAD

**Issue by bradh21** [pop-os/pop#106]
**Reporter info**
bradh21
```
 * Distribution - Pop!_OS 17.10
 * Related Application and/or Package Version - 
GNOME Calendar app (default calendar) 3.26.2
```

**Issue/Bug Description**
Notifications (including audio notifications) in calendar app do not work. 

**Steps to reproduce (if you know)**
Set up an event in the calendar app, set to notify 10 minutes beforehand, enable audio. No notification (text or audio) will appear.

**Expected behavior**

Events in calendar should send notifications (text and audio, if audio is enabled).

**Other Notes**

**Comment by AtomicCons** [comment]
This seems to be a gnome problem affecting multiple OS's.

**Comment by sramkrishna** [comment]
I have let the upstream maintainer know about the bug.

**Comment by brs17** [comment]
@sramkrishna Is there an upstream bug regarding this issue? Did you get an update from the maintainer?

**Comment by leviport** [comment]
Since it's over 4 years old, I'm going to bet that it's no longer an issue and this just didn't get closed. If I'm mistaken, I can reopen it.
