### ISSUE TITLE
Can't use Bluetooth devices and 2.4 GHz WiFi at the same time on Galago Pro

### ISSUE THREAD

**Issue by dido** [pop-os/pop#107]
**Reporter info**
* Distribution:

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 * Related Application and/or Package Version:
Bluetooth and WiFi

**Issue/Bug Description**

I have a System76 Galago Pro and have installed Pop!_OS 17.10 on it after using the Ubuntu 16.04.2 it came installed with for some time. I regularly use a Bluetooth mouse (detected as Logitech M336/337/M535) and a Philips AS351 Bluetooth speaker and have had no issues with them under Ubuntu 16.04.2. However, I noticed that under Pop!_OS 17.10 it suddenly doesn't seem to be possible to use Bluetooth and 2.4 GHz wireless networks at the same time. I can use 5 GHz Wi-Fi just fine though, it has no effect on Bluetooth, which is even stranger. If I attempt to connect to a 2.4 GHz Wi-Fi network my Bluetooth devices immediately stop working, although the interface still shows them as connected. My mouse stops working, sound cuts out from my speakers, and the indicator light on my speakers showing an active Bluetooth connection blinks, indicating a lost connection. If I disconnect from the 2.4 GHz network, it seems that my Bluetooth devices will eventually reconnect.

**Steps to reproduce (if you know)**

1. Connect Bluetooth devices to system.
2. Connect to a 2.4 GHz Wi-Fi network
3. All Bluetooth devices will stop working, although the system still shows them as being connected.

**Expected behavior**

2.4 GHz Wi-Fi and Bluetooth should be usable at the same time as they were in Ubuntu 16.04.2.

**Other Notes**

I'll try to see if the same thing happens under Ubuntu 17.10 as well if I have the time to do this to confirm if this is an upstream hardware issue that affects the Galago Pro.

The Galago Pro I bought has the 'WiFi up to 867 Mbps + Bluetooth' option.

**Comment by dido** [comment]
Just tried a live boot session for Ubuntu 17.10 and the same issue occurs. I tried to connect my Bluetooth mouse and then to a 2.4 GHz Wi-Fi and the Bluetooth mouse became unresponsive as well. It seems to be an upstream issue. Who do I talk to to get this fixed?

**Comment by stiggy456** [comment]
I have the same issue on a Lenovo Edge-2 1580

**Comment by dido** [comment]
@sramkrishna Should I make such a bug on Launchpad?

**Comment by dido** [comment]
Hmm, it appears the issue is already known upstream:

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1721271

**Comment by sramkrishna** [comment]
It seems in the bug that it will be fixed in the next kernel release.  So 18.04 should resolve the issue.  Going to close it since a fix has been verified.  You can re-open after 18.04 if the problem persists.

**Comment by r-ush** [comment]
if anyone is still facing this issue. This might help https://askubuntu.com/questions/645009/wi-fi-and-bluetooth-not-working-simultaneously
