### ISSUE TITLE
Firmware update breaks UEFI boot entry on ThinkPad X1 Extreme Gen 1 - pop OS 20.04

### ISSUE THREAD

**Issue by yamato-gun** [pop-os/pop#1079]
Hi,

I just tried to update the firmware from PopOS 20.04 on my Thinkpad X1 Extreme Gen 1.

The update seemed to run as expected. After the update, no more entry is shown. 

I have a dual boot Windows 10 pro with encrypted disk + Pop Os 20.04. Each OS is on a separate disk : 

NVMe SSD 256gb for Pop OS (LUCKS encrypted LVME)
m2 512gb SSD for Windows (Bitlocker encrypted)

I can still boot in Windows 10 now

Unfortunately, I can't enter PopOS after the update. I'll try the "boot repair" procedure on pop docs.

Please indicate me what would be the next steps to produce logs and/or repair.

Best regards

**Comment by yamato-gun** [comment]
Sooo... 

I ran the commands that are included in Pop Os Docs : https://support.system76.com/articles/bootloader/

I ran the commands included in sections :
"systemd-boot"
"Encrypted Disk"

Meaning :

> Encrypted Disk
> To get access to an encrypted disk, these additional commands need run to unlock the disk. Please use the lsblk command described above to determine the correct drive and partition.
> 
> For NVMe Drives:
> ```
> sudo cryptsetup luksOpen /dev/nvme0n1p3 cryptdata
> sudo lvscan
> sudo vgchange -ay
> ```
> systemd-boot
> EFI Boot
> Most computers sold after 2014 use UEFI mode. If boot, esp is listed under flags, the system is installed in UEFI mode. You can also use this command to see if the OS is installed in UEFI mode:
> 
> `[ -d /sys/firmware/efi ] && echo "Installed in UEFI mode" || echo "Installed in Legacy mode"
> `
> Run these commands based on what type of disk you have:
> 
> For NVMe Drives:
> ```
> sudo mount /dev/nvme0n1p3 /mnt
> sudo mount /dev/nvme0n1p1 /mnt/boot/efi
> for i in /dev /dev/pts /proc /sys /run; do sudo mount -B $i /mnt$i; done
> sudo cp /etc/resolv.conf /mnt/etc/
> sudo chroot /mnt
> apt install --reinstall linux-generic linux-headers-generic
> update-initramfs -c -k all
> exit
> sudo bootctl --path=/mnt/boot/efi install
> 
> ```
> 


It worked! So I write from Pop OS now on my X1 Extreme Gen 1.

I don't think I'll do any other Firmware Updates from Pop OS / Linux from now on, since it can break the boot sequence...

Here are more logs for info

~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os


Hopefully, that kind of bugs can be repaired in the future. I expect it could also help anyone with similar problems in the future.

Keep up the good work. Pop!_OS is simply marvellous combined with CrossOver and VMWare! I can run all I want without bothering with Windows 10 and having lot of freedom.

**Comment by aryehweiss** [comment]
I had the same problem and also am no longer updating firmware.

**Comment by isamu1024** [comment]
same problem on a P52s, no longer updating firmware too.

**Comment by aryehweiss** [comment]
Do the System76 people see this discussion?

**Comment by leviport** [comment]
> Do the System76 people see this discussion?

We see it, but we don't have any Thinkpad X1 Extreme machines to investigate with. My first thought is that it's a problem with fwupd since firmware updates for non-System76 machines come from fwupd. Just be careful if you investigate further, as playing around with firmware can have nasty unintended side effects.

**Comment by sky-and-sand** [comment]
> > Do the System76 people see this discussion?
> 
> We see it, but we don't have any Thinkpad X1 Extreme machines to investigate with. My first thought is that it's a problem with fwupd since firmware updates for non-System76 machines come from fwupd. Just be careful if you investigate further, as playing around with firmware can have nasty unintended side effects.

Not sure how helpful this will be but I burned a 20.04 PopOS DVD to install on a ThinkPad x240 with the latest BIOS update. 

It boots the DVD but fails with an error 'failed to load ldlinux.c32'.

I tried the non-NVIDIA .iso but I can see if the Intel .iso works. The laptop is a few years old. It doesn't boot at all with UEFI enabled. I have disabled secure boot and enabled Legacy BIOS only for now to try again later.

This is the changelog for the BIOS https://download.lenovo.com/pccbbs/mobiles/giuj36uc.txt

**Comment by sky-and-sand** [comment]
No.  I haven't tried in awhile. I think the partition I set aside for updating the OS ran out of space. You can close the issue because I will likely have to format and try when Rust comes out.

Thanks
________________________________
