### ISSUE TITLE
Gnome terminal wrong icon size

### ISSUE THREAD

**Issue by eeeple** [pop-os/pop#108]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**
eeeple
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```
```
gnome-terminal:
  Installed: 3.24.2-0ubuntu4
  Candidate: 3.24.2-0ubuntu4
  Version table:
 *** 3.24.2-0ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description**
Top left icon of Gnome terminal is wrong with _pop_ icon theme and various others

**Steps to reproduce (if you know)**
Apply _Pop_ Icons theme through Gnome Tweak Tool
Launch Gnome Terminal

**Expected behavior**
Top left icon of Gnome Terminal should be the right size and not look overblown

**Other Notes**
See attached screenshots :
Right :
![right](https://user-images.githubusercontent.com/2037523/34447911-c475b8bc-ece8-11e7-901b-698813e94357.png)
Wrong :
![wrong](https://user-images.githubusercontent.com/2037523/34447914-c8fad944-ece8-11e7-89cd-4948c9967712.png)

**Comment by sramkrishna** [comment]
Thanks for bringing this up.  I'll see if @isantop might be interesting in covering that usecase.  In general the default doesn't use the icons in the windows.  Can you tell me why you liked having them there?

**Comment by eeeple** [comment]
Ok, thanks for clarifying 👍  If you need anything else, do not hesitate !

**Comment by sramkrishna** [comment]
I'm going to close this out since the question has been answered.  This is something that upstream needs to fix, as well, it isn't the primary way we show things on windows.
