### ISSUE TITLE
How to install nvidia-340 officially/correctly??

### ISSUE THREAD

**Issue by eatobin** [pop-os/pop#1093]
I have a fresh install of 20.04 on a very old Sony which needs the nvidia-340 legacy driver for it's gpu. The pop shop nicely tells me I need this driver and offers to install it but the install fails with this error:

`Error while installing package: trying to overwrite '/lib/udev/rules.d/71-nvidia.rules', which is also in package nvidia-kernel-common-440 440.82-1pop1ubuntu1~1588025390~20.04~bf29882`

I have read and followed `https://github.com/pop-os/shop/issues/121` on the same topic but the reboot left me in an unusable video state. The expert advice implied this was not the correct solution anyway.

If I start from scratch - with a fresh install - what is the official/correct way of installing nvidia-340 so I can use the both the integrated and nvidia graphics (including nvidia x server settings) successfully?

Thank you for your help.

**Comment by mmstick** [comment]
If you installed with the NVIDIA ISO, you first need to purge all NVIDIA packages from the system before installing a different driver.

```
sudo apt purge '*nvidia*'
sudo apt install nvidia-340
```

**Comment by eatobin** [comment]
```
eric@pop-os:~$ sudo apt purge '*nvidia*'
[sudo] password for eric: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package *nvidia*
eric@pop-os:~$
```

**Comment by mmstick** [comment]
Try with `sudo apt-get purge '*nvidia*'`

**Comment by eatobin** [comment]
Sorry, but the nvidia-340 driver just simply does not work. Thoroughly
purged Nvidia and added back 340 driver. Wether installed from the client
or pop shop, a reboot opens me into a bad dpi (bad resolution) login
screen. When I choose to reboot into integrated graphics to set dpi = 96
the restart lands me into a dead place without access to a terminal to fix
the situation and reboot.

You may want to check this. But then, how many people are still using
Nvidia 340...
