### ISSUE TITLE
Pop Shell extension: Launcher shortcut issue

### ISSUE THREAD

**Issue by starchivoree** [pop-os/pop#1095]
**Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 20.04 LTS

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Application switcher and launcher Pop OS tiling extension.

**Issue/Bug Description:**

The launcher shortcut works randomly in an Spanish international layout:

Sometimes it works.
Sometimes it opens the 7th application in the application bar.
Most of the time it does not work.

**Steps to reproduce (if you know):**

Set the keyboard layout to Spanish international and try pressing Super + /

![image](https://user-images.githubusercontent.com/60193301/84867878-1ef49480-b07c-11ea-8782-07178da8a62e.png)

**Expected behavior:**

Open the application switcher and launcher.

**Other Notes:**

Fixing this issue would be fantastic for all non English speakers. Thank you for your awesome work!

**Comment by starchivoree** [comment]
I almost forgot. Although the documentation shows the shortcut can be change, I haven't found the option.
![image](https://user-images.githubusercontent.com/60193301/84883040-5f5e0d80-b090-11ea-8af0-5fd311233f6f.png)

**Comment by oauk** [comment]
its a bug, that its some time dont show, after installing popos. if you resintall popos it might show up, or not.

**Comment by WatchMkr** [comment]
Thanks for your bug report. We're tracking the issue here: https://github.com/pop-os/shell/issues/196

And the second issue here: https://github.com/pop-os/gnome-control-center/issues/93
