### ISSUE TITLE
Resume from suspend on battery power causes reboot and loss of state

### ISSUE THREAD

**Issue by jamedwarnton** [pop-os/pop#1098]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
 
**Issue/Bug Description:**
Dell Latitude E5470 Laptop will not resume system from suspend on battery power. Suspending from lid closing or from power menu puts the laptop into suspend mode correctly. On battery, when resuming either opening lid or pressing power/mouse, the laptop immediately reboots losing all state saved in suspend. 

If battery is plugged in and charging, suspend and resume works perfectly as expected.

I have tried the following commands:

sudo kernelstub -o "loglevel=0 splash systemd.show_status=false quiet mem_sleep_default=deep"

kernelstub -a rcutree.rcu_idle_gp_delay=1

**Expected behavior:**
Laptop should resume from suspend on both battery power and whilst charging.

**Comment by finzzz** [comment]
I'm using thinkpad with mx250, same thing happened

**Comment by MEJacoby529** [comment]
I'm using a Dell Precision 7530, 20.04, having the same issue.

**Comment by hirusi** [comment]
Facing the same issue on XPS 15 9560 on 20.04.

**Comment by mmstick** [comment]
You could contact Dell about this. This is something they have to fix in their firmware.
