### ISSUE TITLE
Improper default program for decompressing formats

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#11]
_From @brs17 on October 17, 2017 16:12_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS (20171016) build

**Issue/Bug Description**
Compression formats .7z and .tar.xz, and .iso default to open in "Files" not the "Archive Manager" and thus results in the compressed file being decompressed by default. 

**Steps to reproduce (if you know)**
In "Files" select on a *.7z, *.tar.xz, or *.iso file. 

**Expected behaviour**
The compressed file should open up in the "Archive Manager" displaying the contents of the compressed file.

**Other Notes**
.7z, .iso, .tar.xz should have the same default program as .zip or .tar.gz

_Copied from original issue: pop-os/iso#167_

**Comment by isantop** [comment]
I've noticed that nautilus 3.26 seems to be able to load these files anyway, so this may be intended behavior.

**Comment by WatchMkr** [comment]
@brs17 open an iso on my machine is extracting it in Archive Manager. Is this still occurring?

**Comment by isantop** [comment]
I believe we updated the default program for archive type files prior to release. @jackpot51 Can probably confirm.

**Comment by jackpot51** [comment]
We need to verify this behavior, and then close

**Comment by brs17** [comment]
I realized I left out a big part of this bug :( 

I had this issue when trying to access these compressed formats from an external drive.

**Comment by jackpot51** [comment]
According to @brs17 

.7z and .tar.xz are not correct

**Comment by jackpot51** [comment]
.iso is also not correct

**Comment by WatchMkr** [comment]
@brs17 How does this operate differently between launching archives from a USB drive and launching local files?

**Comment by jackpot51** [comment]
@brs17 retested on a fresh install and will update this bug. .tar.xz and .iso worked correctly, but not .7z

**Comment by brs17** [comment]
So turns out my machine is being funky and weird...seems like .tar.xz and .iso do work. When Archive manager attempts to open .7z, it says:
![7_zip](https://user-images.githubusercontent.com/7460774/34305711-a0ee3258-e6fc-11e7-8293-57e03b473ee0.png)

It seems as though Archive Manager only supports ([link](https://help.gnome.org/users/file-roller/3.26/supported-formats.html.en)):

    Archive only
        AIX Small Indexed Archive (.ar)
        ISO-9660 CD Disc Image [Read-only mode] (.iso)
        Tape Archive File (.tar)
    Archive and compression
        Java Archive (.jar)
        WinRAR Compressed Archive (.rar)
        Tape Archive File compressed with:
            gzip (.tar.gz, .tgz)
            bzip (.tar.bz, .tbz)
            bzip2 (.tar.bz2, .tbz2)
            lzop (.tar.lzo, .tzo)
            7zip (.tar.7z)
            xz (.tar.xz)
        Cabinet File (.cab)
        ZIP Archived Comic Book (.cbz)
        ZIP Archive (.zip)
        ZOO Compressed Archive File (.zoo)

**Comment by WatchMkr** [comment]
What happens when you click Search Command?

If you run "sudo apt install unrar" do .7z files open in Nautilus?

**Comment by brs17** [comment]
Selecting "Search Command" does show you the package that needs to be installed for this to work @jackpot51 is thinking we can install it by default

**Comment by bflanagin** [comment]
Doing a quick check on the latest release all the extensions mentioned here are now opening with the proper application. 

Closing issue.
