### ISSUE TITLE
Flatpak netbeans, bracket no access to /var/www/html folder

### ISSUE THREAD

**Issue by avdzm** [pop-os/pop#1106]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
flatpak info org.apache.netbeans 

NetBeans - NetBeans - Apache Java IDE. Fits the Pieces Together

          ID: org.apache.netbeans
         Ref: app/org.apache.netbeans/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 12.0
     License: Apache-2.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 1.3 GB
     Runtime: org.freedesktop.Sdk/x86_64/19.08
         Sdk: org.freedesktop.Sdk/x86_64/19.08

      Commit: b1ad25485668ef1944f505f14a97460bff4392eba67e3eac2ffe5599cbf2e4f1
      Parent: e89de096ccfef1a48ec6662601c534f0e09cc8a70f83dfa04581103e64346f32
     Subject: Update to 12.0, add new screenshots (b960a6f9)
        Date: 2020-06-18 17:24:31 +0000

**Issue/Bug Description:**
I have installed Apache Netbeans v12 and Adobe Brackets from the flatpak repository.
They both do not have access to /var/www/html.

Note: I've noticed that some folders are not shown in the view when trying to save a file.
I've attached a screenshot.
![Screenshot from 2020-06-23 13-35-35](https://user-images.githubusercontent.com/64041008/85399105-8e73f380-b556-11ea-9fe1-7c9720d48a9a.png)

I cannot save any documents using both apps to that directory.
I do have ownership and permission writes to folder.

**Steps to reproduce (if you know):**
Check if you have permission and ownership of folder and sub directories to /var/www/html.

1) Download Apache Netbeans or Adobe Brackets (via flatpak repository).
2) Create a new document and try to save to path /var/www/html.
 

**Expected behavior:**
To be able to save files to /var/www/html.

**Other Notes:**
I do realize this might be a flatpak or flathub issue.
I have attached screen shots that i do have permission and netbeans has full access to the system.
I have also attached screen shots that netbeans sees less folders then what is there.

![applications netbeans](https://user-images.githubusercontent.com/64041008/85399719-8bc5ce00-b557-11ea-8df3-4c018e74a17d.png)
 ![Screenshot from 2020-06-23 13-44-24]
(https://user-images.githubusercontent.com/64041008/85399810-b6b02200-b557-11ea-836b-30f65926ae2e.png)

![folders in var](https://user-images.githubusercontent.com/64041008/85400484-c1b78200-b558-11ea-912e-6fbba6ad8e31.png)

**Comment by designtechti** [comment]
I have this issue too! I use Linux Mint 20.1 and also doesn't work exactly like you saying! It's a problem with the Flatpak/Flathub!

**Comment by jacobgkau** [comment]
It might be worth reporting this to the Flathub packagers for these packages:

- https://github.com/flathub/org.apache.netbeans 
- https://github.com/flathub/io.brackets.Brackets 

Although they may find it more appropriate to simply override on your own system: https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

**Comment by mmstick** [comment]
Use Flatseal to add permissions for a flatpak

**Comment by ids1024** [comment]
Closing, because if this is an issue (rather than a reasonable default in the Flatpak) it's not an issue in anything packaged by Pop!_OS.

**Comment by arvodia** [comment]
Hi,
il vous suffit d'ajouter des autorisations de lecture/écriture sur le dossier www avec cette commande
```
sudo flatpak override --filesystem=/var/www:rw org.apache.netbeans
```

**Comment by arvodia** [comment]
Hi,
you just need to add read/write permissions on the www folder with this command
```
sudo flatpak override --filesystem=/var/www:rw org.apache.netbeans
```
