### ISSUE TITLE
small tiles render blurry

### ISSUE THREAD

**Issue by hypergig** [pop-os/pop#1108]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
The tiling gnome shell extension 

**Issue/Bug Description:**
Small tiles render blurry

**Steps to reproduce (if you know):**
Simply create enough tiles to get one of them small enough to cause the bug

**Expected behavior:**
Should not be blurry

**Other Notes:**
I notice if I go into adjustment mode and then back out, the issue resolves itself, but only temporary as eventually it will turn blurry again. Seems to happen with any type of window.

![blurry](https://user-images.githubusercontent.com/8643560/85568897-17933500-b600-11ea-8953-7962b9f916cf.png)

**Comment by WatchMkr** [comment]
Thanks for your bug report. This is a duplicate that we're tracking here: https://github.com/pop-os/shell/issues/192
