### ISSUE TITLE
Display Settings Portrait mode not functioning

### ISSUE THREAD

**Issue by justinsilber** [pop-os/pop#1110]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-control-center:
  Installed: 1:3.36.2-0ubuntu1pop1~1593108892~20.04~d255b0f
  Candidate: 1:3.36.2-0ubuntu1pop1~1593108892~20.04~d255b0f
  Version table:
 *** 1:3.36.2-0ubuntu1pop1~1593108892~20.04~d255b0f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.36.2-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     1:3.36.1-1ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages

**Issue/Bug Description:**
I have a dual-monitor configuration; left monitor is in a portrait orientation with a resolution of 1080x1920, right monitor is primary display in landscape with a resolution of 1920x1200. Left monitor defaults to landscape and when setting it to portrait and clicking, 'Apply', one of two things will happen: 

    1. Control center will disable it, putting me in single monitor mode with only my primary monitor active.
    2. Monitors will blank briefly as settings are seemingly applied and ask me to revert or retain. The left monitor will remain enabled and show as 'joined' but will remain in landscape mode. Layout of displays will have been modified with the left display overlapping the right by about 40%.

**Steps to reproduce (if you know):**

1. Open gnome-control-center either using the GUI or in terminal via `gnome-control-center display`
2. Ensure that Display Mode is set to, 'Join Displays'
3. Select the display I wish to set to Portrait orientation
4. Under 'Orientation' use the drop-down menu to select either 'Portrait (Left)' or 'Portrait (Right)'
5. Click 'Apply'

**Expected behavior:**
The display will be set to portrait orientation and be able to have its relative position adjusted.

**Other Notes:**
Display can be configured correctly through the NVIDIA X Server Settings application, but settings do not persist between reboots even after saving changes to X configuration

**Comment by leviport** [comment]
Thank you for the report! We are tracking this bug here: https://github.com/pop-os/pop/issues/1009
