### ISSUE TITLE
Can't pair my Airpods Pro with the latest Pop OS

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1115]
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 
 
**Issue/Bug Description:**

After putting my airpods pro into pairing mode, and after I click on them in bluetooth devices list, nothing happens
I was able to connect to my Bose QC 35, for instance. 

Thanks

**Comment by dodalovic** [comment]
found some workaround

**Comment by the-vampiire** [comment]
@dodalovic what did you do to get it working?

**Comment by dodalovic** [comment]
Don't remember. Maybe had to reset them. Really not idea. Although - the mic is still not working. :shrug:
