### ISSUE TITLE
Apps/documents do not fade away when searching in activities/show applications menu

### ISSUE THREAD

**Issue by zubair0803** [pop-os/pop#1119]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
Issue is unclear. Could you please explain in more detail, perhaps with screenshots?
