### ISSUE TITLE
On Screen Keyboard Prints Wrong Characters 

### ISSUE THREAD

**Issue by jeremyminnick** [pop-os/pop#112]
**Reporter info:**
Jeremy Minnick
jeremyeminnick@gmail.com
Twitter: @jeremyminnick82 

**OS:** POP!_os Latest Version 
 
**Related Application:** On-screen keyboard (for touch screens).

**Issue/Bug Description:**
When using the on-screen keyboard, if you go into the [123] /Shift Mode When you type "@" you get "2" instead, The "&" symbols get you "7" instead. 

**Steps to reproduce (if you know)**
On a touch Screen (I am using an x360 HP Convertable Laptop) Swipe up from the bottom of the touch screen to produce the on-screen keyboard. Then press the "[123]" button then push the @ and & symbols to produce the incorrect characters "2" and "7". 

**Expected behavior**

The expected behavior is to produce "@" and  "&".

**Other Notes**

**Comment by dido** [comment]
I confirm that I see this same behaviour for the on screen keyboard, and worse. Additionally the double quote key produces single quotes, the curly brace key produces square brackets, etc. Just about every key in {#* mode is wrong or non-functional. The # key produces 3. % produces 5. ^ produces 6, * produces 8. + produces =. _ produces - | produces \.  ~ produces `.  > produces . $ produces 4. " produces '. The € and £ keys do not produce any output at all. ? produces /. ! produces 1. Using the shift key does not produce capital letters. The whole thing seems completely broken.

**Comment by brs17** [comment]
I can confirm this is an issue in both 17.10 as well as in early builds of 18.04. Going to create an issue upstream once I find where exactly that should go!

**Comment by brs17** [comment]
Looks like Ubuntu 17.10 fixes this issue but the issue exists in Pop!_OS and upstream Gnome. This would be a good starting point to find the fix (that Ubuntu has implemented).

**Comment by brs17** [comment]
This issue does not exist in Ubuntu 17.10 but exists in both Pop!_OS(17.10 and early builds of 18.04) and upstream Gnome. I'm thinking Ubuntu 17.10 does not use the same keyboard. Finding where this keyboard is implemented (going to look in clutter, which is packaged in mutter), I will then see if an upstream bug has been filed or file one myself.
