### ISSUE TITLE
Pop!_Shop requires constant reauthentication with failed uninstalls

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#1132]
**Distribution (run `cat /etc/os-release`):**
 
20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Shop

**Issue/Bug Description:**

If you go to the "Installed" tab and try to uninstall an app, you get asked for your password even if you just logged in to the lock screen. Maybe this is hard to prevent because the time of most recent authentication is unknown to the shop, but then if the app fails to uninstall, it will ask you again for your password next time you try to uninstall a different app. (It may or may not also happen if your uninstall succeeds.) This is a real nuisance when trying to uninstall as many apps as possible.

**Steps to reproduce (if you know):**

Explained above

**Expected behavior:**

Have whatever timeout you want for requiring reauthentication. (The screen lock timeout would be a logical default.) But then abide by it rather than asking for the password repeatedly over shorter durations.

**Other Notes:**

**Comment by leviport** [comment]
Logging into the machine and elevating privileges to uninstall an application are two distinctly different actions. For example, a user without elevated permissions has to be able to log in to/unlock the machine, but will not be permitted to uninstall applications. If that user unlocked the screen and was granted sudo privileges, it would be quite a problem.

**Comment by KloudKoder** [comment]
I get that, but my point was that a user who has successfully authenticated and does have uninstall privileges is being asked for his password over and over again within a short timespan in this particular context. That doesn't happen in the terminal, for instance. Why should it happen in the shop?
