### ISSUE TITLE
Block Caribou extension no longer blocks on-screen keyboard 

### ISSUE THREAD

**Issue by 7f043** [pop-os/pop#1140]
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 

Block Caribou no longer prevents caribou from popping up when keyboard commands are used.

Open firefox, use command ALT+D or open terminal, or open any program that has a cursor by default.

Caribou should not ever appear.

This happened after the update and hasn't been fixed yet. If the extension no longer works, I will also accept another way of getting caribou to go away.

**Comment by jacobgkau** [comment]
Hello. What hardware are you using? From the behavior you're describing, I assume you're using a machine with a touch screen and also a physical keyboard?

Which exact Block Caribou extension are you using? I'm seeing what appears to be the original extension [here](https://extensions.gnome.org/extension/1326/block-caribou/) and there are reports in the comments that it stops working with GNOME 3.36 (which we ship with 20.04 LTS.) There is a fork of that extension updated for 3.36 [here](https://extensions.gnome.org/extension/3222/block-caribou-36/), does the fork work for you?

I'm seeing possibly related issues filed upstream with [caribou](https://gitlab.gnome.org/GNOME/caribou/-/issues/9) and [gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/2353).

**Comment by 7f043** [comment]
Block Caribou 36 resolved this issue. I assumed Block Caribou wasn't supported, but was unaware of the fork. Thanks.
