### ISSUE TITLE
keepassxc not in PATH after flatpak installed

### ISSUE THREAD

**Issue by MaliRemorker** [pop-os/pop#1141]
**Distribution (run `cat /etc/os-release`):**
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
keepassxc:
  Installed: (none)
  Candidate: 2.4.3+dfsg.1-1build1
  Version table:
     2.4.3+dfsg.1-1build1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

**Issue/Bug Description:**
After moving from keepassxc on apt, to keepassxc from flatpak (as recommended by the system dialog after a recent pop-os update), I lost keepassxc from my PATH. The only way to start it is by running it from the GUI. I am allergic to GUIs.
Is this a feature, or a bug? I don't have any experience with flatpaks, so I don't want to hunt down some possibly transient path. 

Oh, in addition, after I installed the flatpak version, my keepassxc browser plugin froze firefox on several occasions. Had to disable it.

**Steps to reproduce (if you know):**
1. remove keepassxc from apt package management system
2. add it to flatpaks

**Expected behavior:**
$ keepassxc && [ "$?" ] && echo It ran!
It ran!

**Other Notes:**

**Comment by mmstick** [comment]
Symlinks to flatpak containers are in `~/.local/share/flatpak/exports/bin/`. Keepass is `org.keepassxc.KeePassXC`. Alternative run `flatpak run org.keepassxc.KeePassXC`, or make an alias for it.

**Comment by MaliRemorker** [comment]
Wouldn't it make sense to provide links to weird-flatpak-path/org.weird.flatpak.rename.foobar, since flatpak clearly breaks the expected behaviour? They could go into ~/.local/bin, or somewhere such. As in `ln -s weird-flatpak-path/org.weird.flatpak.rename.foobar $HOME/.local/bin/foobar`

I mean, some of us have scripts we would like to work across different platforms. It's easy to add another path to $PATH, more annoying to create special conditions inside the scripts if there is an installation with flatpak. Even Guix respects this.

**Comment by mmstick** [comment]
This is expected behavior of flatpaks, as it's a potential security risk to pollute the PATH with third party software. My advice is to change your scripts to detect if keepassxc is a Flatpak or system application, and launch them accordingly.
