### ISSUE TITLE
Win + N key ( e.g. Win + 1 / 2 / 3 .. ) not working anymore

### ISSUE THREAD

**Issue by alphazilla** [pop-os/pop#1147]
**Distribution:**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
After the last Operating System Updates the Win + 1 / 2 / 3 ... key shortcut ( to switch to a favourite application or to open if is not running ) is not working.

**Steps to reproduce:**
Have two applications open and try to switch from one application to another by using the corresponding Win + N key combination 

**Expected behavior:**
When pressing Win + 1 / 2 to switch the focus between the applications.

**Comment by wmutschl** [comment]
I have the same behavior.

**Comment by leviport** [comment]
Please see: https://github.com/pop-os/session/issues/21 and https://github.com/pop-os/session/pull/20#issuecomment-657708579
