### ISSUE TITLE
External ViewSonic monitor broken after sleeping, until a cold boot.

### ISSUE THREAD

**Issue by justinpw** [pop-os/pop#115]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME

```

**Issue/Bug Description**
External HDMI monitor stops working until a cold boot, and the window manager endlessly tries to load it, gives up, and tries again.  Monitor is ViewSonic VA2265SMH

These lines show up in `dmesg`:
```
[45862.415021] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 1
[45886.607165] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 1
[45903.459288] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 1
[45904.535323] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 21
[45921.959402] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 1
[45922.995431] snd_hda_codec_hdmi hdaudioC1D0: HDMI: invalid ELD data byte 18
```

**Steps to reproduce (if you know)**
- Setup the ViewSonic HDMI VA2265SMH as an extended screen.
- Idle until all the screen falls alseep, long enough for the external monitor to actually turn off.
- Resume activity, and when the laptop screen wakes up, it still behaves as if it has an extended desktop but the external monitor does not wake up, including if unplugging/plugging it back in.
- check `dmesg` and note error messsages.
- perform a cold boot and see the monitor begin working again.

**Expected behavior**
I expect the monitor to wake up normally when I resume activity.  Instead, I have to manually shut it down to prevent it from falling asleep, and disable any sleep functionality in both the external monitor firmware and the computer's power-saving settings.

**Other Notes**

**Comment by sramkrishna** [comment]
Thanks for submitting the issue - I'll see if we can get some attention on it.

**Comment by AtomicCons** [comment]
I'm suspect of the video driver or another incompatibility issue.
What video card are you using?
Also, please paste the results of the below command.
'''sudo lshw -c video'''

**Comment by justinpw** [comment]
GeForce GTX 1060.  Here is the above command while it's **not** in the error-state. It'll be later today or tonight that I'll be able to idle the computer long enough to return it to the error state.. 

```
~ sudo lshw -c video 
[sudo] password for justin: 
  *-display                 
       description: VGA compatible controller
       product: GP106M [GeForce GTX 1060 Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:135 memory:db000000-dbffffff memory:90000000-9fffffff memory:a0000000-a1ffffff ioport:e000(size=128) memory:c0000-dffff
~ 
```

**Comment by justinpw** [comment]
ok it's back in the error state, and the output for above is no different.

**Comment by AtomicCons** [comment]
Can you replicate the results if you turn the monitor off then back on? Or
does it only happen when the monitor sleeps.

**Comment by justinpw** [comment]
Only upon monitor sleep.  If it hasn't slept, then power cycling the monitor works fine.  If it has slept, then power cycling the monitor doesn't help, the video card has to be power cycled.  I just confirmed that laptop suspend successfully clears the error state.  Computer is Oryx Pro 3, btw.

**Comment by bflanagin** [comment]
Thank you for filing this bug. Unfortunately it seems to have gone stale and will be closed. 

In the future our support team can help you with official system76 hardware over at https://support.system76.com
