### ISSUE TITLE
Can't add new keyboard shortcut using Fn Key

### ISSUE THREAD

**Issue by michaelbilow** [pop-os/pop#1155]
**Distribution (run `cat /etc/os-release`):**
 
 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

I'm trying to add a keyboard shortcut for "skip track." I installed `playerctl` via `sudo apt install playerctl`. I want to bind this to `Fn + Right`.

**Steps to reproduce (if you know):**
1. Open the Keyboard Shortcuts App
2. Enter a new keyboard shortcut 
3. When prompted for the shortcut, use a key combination including `Fn`. The dialog reacts, but does not show the `Add` button. 

I was able to succeed with the key combination `Shift + Alt + Right` instead.

**Expected behavior:**

I should be able to start a keyboard shortcut with the Fn key.

**Other Notes:**

**Comment by leviport** [comment]
The Fn key is almost always handled by the machine's EC, so there won't be a way in the OS to map hotkeys with it unless the EC reports that key combo differently to the OS. There are [ways to customize Fn shortcuts](https://github.com/system76/ec/blob/master/doc/keyboard-layout-customization.md) if you happen to have a System76 machine with open EC, but EC is not modifiable for the vast majority of machines out there.
