### ISSUE TITLE
HP Omen 15 Ryzen 4800h Nvidia 1650ti wont install

### ISSUE THREAD

**Issue by superhero75** [pop-os/pop#1161]
**Distribution (run `cat /etc/os-release`):**
 
 pop os 2004 installation
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
pop os wont install on the laptop and the installation hangs and stops.

**Steps to reproduce (if you know):**

**Expected behavior:**
when i install ubuntu 2004, only need to disable acpi in grub and it will at least install.

**Other Notes:**

**Comment by jacobgkau** [comment]
When you say "the installation hangs and stops," are you just talking about the installation itself, or does the mouse cursor also freeze?

There is an installation log at /tmp/installer.log on the live disk. You can find it by opening Files and navigating to Other Locations -> Computer -> tmp. We would need that log file to potentially see where the installation is stopping.

**Comment by Devorlon** [comment]
I have a similar problem (I think). 

I can download the NVIDIA image and flash it to a USB stick with etcher. When booting from it (UEFI, no Sec Boot) I'll be met with a black screen and a blinking cursor. 

To boot into the installation media I have to edit grub and change modules_load=nvidia to amdgpu, which will allow me to install PopOS. But when booting into the installed OS there's still a black screen with a cursor. And I don't know how to contuine from there. 

Specs:
4800h
RTX 2060
16GB RAM

I don't know the OEM but here are some resellers.

[https://www.eluktronics.com/RP-15/](https://www.eluktronics.com/RP-15/)
[https://bestware.com/en/xmg-core-15-amd.html](https://bestware.com/en/xmg-core-15-amd.html)
[https://www.pcspecialist.co.uk/notebooks/optimusXI-pro-15/](https://www.pcspecialist.co.uk/notebooks/optimusXI-pro-15/)

**Comment by chandanmalla** [comment]
follow the steps mentioned in https://github.com/pop-os/pop/issues/1199, it will work, it is a bug with new ryzen CPU

**Comment by dhruvindsd-dev** [comment]
> I end up installing fedora 32 instead and it works pretty well except the following:
> 
> 1. trackpad may not be recognised when external monitors are connected
> 2. external monitors must be connected at boot. after it has been booted, external monitors wont be recognised.
> 
> I think kernel 5.7 or 5.8 work a lot better. most other distros don't work well with this laptop. I have tried manjaro but external monitors have jumbled screens.
> 
> so basically only the latest Fedora works.

I've got the same laptop but in mine, there are a ton of issues : 
1. trackpad randomly stops working 
2. when i wake up the device from suspending it starts glitching 

Did you do any specific steps while installing fedora ?

**Comment by superhero75** [comment]
pop os installs now but amd ryzen renoir integrated graphics doesnt work at all for external monitors. Nvidia gpu works well for external monitors. that means, right now, under the power settings: integrated graphics and hybrid graphics, external monitors dont work.
