### ISSUE TITLE
For pop-os 20.04 focal /etc/hosts is not working

### ISSUE THREAD

**Issue by bearmonkeycat** [pop-os/pop#1163]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure

**Issue/Bug Description:**
/etc/hosts is not working. I have switched to different hosts files, cleared the cache in firefox, and tried restarting network-manager. I am unable to get the hosts file to block websites.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment]
Please visit `about:preferences`, scroll to Network Settings (at the bottom), and make sure `Enable DNS over HTTPS` is not enabled. If it's enabled (which is the default in recent Firefox versions), Firefox would not use your /etc/hosts file or your other system-wide DNS settings.

(When a user starts Firefox for the first time, they are shown a notification that DNS over HTTPS is enabled, and there are buttons to keep that option or to disable it. I've gotten in the habit of disabling it, but I can see how it could get overlooked in the numerous first-time notifications and pages Firefox displays.)

After disabling that option and completely quitting/restarting Firefox, I am able to "block" www.google.com by giving it a bad entry in `/etc/hosts`.
