### ISSUE TITLE
Sharing Folder Fail

### ISSUE THREAD

**Issue by HHuckleberry** [pop-os/pop#117]
**Reporter info**
AtomicCons

 * Distribution - "Pop!_OS 17.10 (Artful Aardvark)"

**Issue/Bug Description**
When Creating a share on POP, when you right-click, go to Local Network Share, then hit Share this folder, you receive a prompt that the **Sharing service is not installed**. You are then prompted to Install service which returns sharing service installation failed. 

**Steps to reproduce (if you know)**
Try to create a shared folder

**Expected behavior**
Expect Samba to install and then a prompt to reboot to complete the share.

**Other Notes**
Work around:
In Terminal, run ```sudo apt install samba``` prior to trying to share a folder

**Comment by sramkrishna** [comment]
I was to verify that I was not able to install samba while during the network share.  Thanks for catching that!  Mine fails with "Could not find package 'libpam-smbpass'.

**Comment by bflanagin** [comment]
These options have been removed from nautilus by default. Since the user is now required to install the software and services to re-enable the feature this issue is no longer valid.
