### ISSUE TITLE
Laptop does not suspend on lid closure

### ISSUE THREAD

**Issue by afonsosantos** [pop-os/pop#1171]
**Distribution (run `cat /etc/os-release`):**
 
 Live CD - PopOS 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

None.

**Issue/Bug Description:**

When setting the **Suspend on Lid Close** setting on **GNOME Tweaks**, nothing happens when I close the lid of my laptop (Lenovo IdeaPad 320-15-ast).

**Steps to reproduce (if you know):**

1. Open GNOME Tweaks
2. Turn on the **Suspend on Lid Close** option
3. Close the laptop lid

**Expected behavior:**

The laptop screen should turn off and suspend the computer.

**Other Notes:**

If a external monitor is connected via HDMI, the laptop screen turns off and the external screen is set as the primary one.

**Comment by beltmankelo** [comment]
I was facing a similar issue, it's an issue with Bluetooth. Check it out here- [https://askubuntu.com/questions/797590/ubuntu-wakes-up-immediately-after-suspend]

**Comment by afonsosantos** [comment]
Hi @beltmankelo 

Tried the steps in that URL and no joy, the laptop still does not suspend, event with the external monitor off.
I'm suspecting that is something to do with GNOME, beacuse I had Kubuntu, whic runs KDE, and the laptops would suspend when the lid was closed.

Thank you for the help!

**Comment by gervaisb** [comment]
I have the same issue. And there is this Reddit thread about it : https://www.reddit.com/r/pop_os/comments/fgi634/suspend_on_lid_close/

> NAME="Pop!_OS"
> VERSION="20.04 LTS"

**Comment by afonsosantos** [comment]
This issue may be closed, I switched to Kubuntu and the issue no longer happens.
Thanks for all the help provided.

**Comment by gervaisb** [comment]
I didn't and the issue is still here.
