### ISSUE TITLE
nvidia server update fails after system update due to dependencies.

### ISSUE THREAD

**Issue by sam-falvo** [pop-os/pop#1176]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
nvidia-driver-440-server
440.95.01

**Issue/Bug Description:**
Unable to install updated nvidia drivers due to dependency issues.

```
The following packages have unmet dependencies:
  nvidia-driver-440-server: Depends: libnvidia-gl-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: libnvidia-decode-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: libnvidia-encode-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: nvidia-utils-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: xserver-xorg-video-nvidia-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: libnvidia-cfg1-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Depends: libnvidia-ifr1-440-server (= 440.95.01-0ubuntu0.20.04.1) but it is not going to be installed
                            Recommends: nvidia-prime (>= 0.8)
                            Recommends: libnvidia-decode-440-server:i386 (= 440.95.01-0ubuntu0.20.04.1)
                            Recommends: libnvidia-encode-440-server:i386 (= 440.95.01-0ubuntu0.20.04.1)
                            Recommends: libnvidia-ifr1-440-server:i386 (= 440.95.01-0ubuntu0.20.04.1)
                            Recommends: libnvidia-fbc1-440-server:i386 (= 440.95.01-0ubuntu0.20.04.1)
                            Recommends: libnvidia-gl-440-server:i386 (= 440.95.01-0ubuntu0.20.04.1)
```

**Steps to reproduce (if you know):**
1. Observe Pop_OS! pop-up dialog indicating updates are available.  Click on it.
2. Perform system update by installing everything.
3. Upon completion, observe that only nvidia server remains to be updated.  Click on update.
4. Get failure message with in a **rediculously small** dialog box.
5. Copy-and-paste message from dialog box into GitHub bug report, as above.

**Expected behavior:**
Dependencies should always be met when making an LTS release.

**Other Notes:**
I expect the install failure dialog box to be appropriately-sized for the display surface I have.  On my screen, it isn't even big enough to show 8 characters across.

This problem has, so far, not been a breaking issue for me.  However, it is annoying to see it happen every single time I update packages.

**Comment by sam-falvo** [comment]
Progenitor Twitter issue, for those who care to have a complete audit trail: https://twitter.com/SamuelAFalvoII/status/1289409695929647111

**Comment by jacobgkau** [comment]
You should not install `nvidia-driver-440-server`. It is not an "update," it is an alternative driver package published by Ubuntu. The error is that it's showing up in the list.

This was fixed yesterday with an update to the Pop!_Shop, which should remove that item from your list of available drivers to install: https://github.com/pop-os/shop/pull/212 

Can you please install all updates, reboot, and if you're still seeing `nvidia-driver-440-server` offered in the list, provide the output of this command:

```
apt policy pop-shop
```

**Comment by sam-falvo** [comment]
I did not install it.  My current Pop_OS! 20.04 was an update from a prior version of Pop_OS! which came pre-installed on my System76 laptop.

Latest updates installed; I'll reboot later tonight and report back my findings.  Thanks for taking a look!

**Comment by jacobgkau** [comment]
> I did not install it.

Correct, but you attempted to install it by clicking the "Install" button that is visible in your tweet (which failed and gave an error message instead.) If it was already installed before, then the button would say "Update" instead of "Install." That's also why the "Update All" button did not include this item-- it wasn't installed to begin with.

The Pop!_Shop attempts to list available drivers on that page even if they're not currently installed, but in this case, the version of the NVIDIA driver being offered was not the correct version that we are shipping. Ubuntu's server version conflicts with the correct version that you do have installed, which is why you saw the dependency error. I'm sorry for the confusion this caused.

If you have a System76 machine, then it's best to open a [support ticket](https://support.system76.com/) for future questions (since that guarantees you'll get a response as soon as possible.) We're always happy to help!
