### ISSUE TITLE
nvidia proprietary driver does not work in 20.01 media

### ISSUE THREAD

**Issue by jwright1985** [pop-os/pop#1178]
**Distribution (run `cat /etc/os-release`):**
 20.01 Nvidia
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Nvidia driver does not work. System runs at 640x480 resolution on GTX 580, probably as result of using the fallback modesetting or VESA driver

**Issue/Bug Description:**
The screen resolution is very low (nearly unusuable) during installation, and Nvidia driver does not work on GTX 580

**Steps to reproduce (if you know):**
Boot 20.01 live media

**Expected behavior:**
Nvidia driver works and screen is running at a usable resolution

**Other Notes:**

I was able to bumble my way through the installation (lots of tabbing and guessing). The graphics issue persists from the live image to the installed os. Issue can be fixed by manually installing the latest Nvidia proprietary driver after OS installation is complete.

**Comment by leviport** [comment]
It looks like the GTX 500 series isn't supported by the current Nvidia driver any longer [[1]](https://www.nvidia.com/download/driverResults.aspx/160175/en-us). Nvidia has a cut-off, and eventually support is dropped for legacy cards on the main driver. There is usually an older version in the repos that will support legacy cards if you want to give that a try. I believe the current legacy version is nvidia-driver-390 if you want to give that a try.

**Comment by jwright1985** [comment]
The driver I downloaded from Nvidia worked.

Is there any way to force a text mode installation? I ask this because with this older GPU the installer was nearly unusable as the system was operating at 640x480 resolution

**Comment by leviport** [comment]
No, not at this time.
