### ISSUE TITLE
Suspend and APC

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/pop#118]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**

APC 1500 model

**Steps to reproduce (if you know)**

Unplug APC from wall, machine will go into battery mode from APC, plug APC back into wall machine still says in battery mode.

**Expected behavior**

Machine should be off battery mode.

**Other Notes**

**Comment by sramkrishna** [comment]
@ahoneybun do you have access to the customer?  Can you have them post some logs or something so that we can determine the issue?

**Comment by sramkrishna** [comment]
In general, we should be monitoring upower dbus connection and see if we see a status when it unplugs.  If a message is being sent then somehow that alert is not being propagated up the stack.

**Comment by brs17** [comment]
Without additional information we are unable to determine what is causing this problem. This also initially sounds like more of a hardware issue than a Pop!_OS specific issue.
