### ISSUE TITLE
Glitchy Login Screen

### ISSUE THREAD

**Issue by venkivijay** [pop-os/pop#1194]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Instead of login screen, a [glitchy screen](https://imgur.com/a/upGuQmL) is shown. The login functionality seems to be working. I can pass the login screen by presumably pressing enter and typing in the password. Afterwhich everything works fine.

**Steps to reproduce (if you know):**
Just fire up the system. 

**Expected behavior:**
The proper login screen should be shown instead of the glitchy screen.

**Other Notes:**
Laptop: HP Pavilion Gaming 15 
Processor: AMD® Ryzen 5 3550h with radeon vega mobile gfx × 8 
Graphics: GeForce GTX 1650/PCIe/SSE2 / GeForce GTX 1650/PCIe/SSE2

DualBoot setup: Alongside Windows 10
Installed PopOs that comes with Nvidia Drivers

**Comment by venkivijay** [comment]
While in the glitchy login screen, I am also able to access the terminal. Running `systemctl restart gdm3.service` solves the issue for one time and the normal login screen comes up. Then this issue is related to gdm3 right? Correct me if I'm wrong!

**Comment by mmstick** [comment]
There's a good chance that this may be fixed by a newer kernel

**Comment by venkivijay** [comment]
Hi @mmstick,
The new kernel 5.8 fixed this issue. Thanks for the help.

**Comment by mmstick** [comment]
You should upgrade to 20.10 when it's available, because that's the kernel there
