### ISSUE TITLE
Pop!_OS Splash screen is squished with AMD graphics card

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#12]
_From @brs17 on October 16, 2017 15:8_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
Installed Pop!_OS on a Leopard WS with an AMD Radeon RX 580. The splash screen displays squished with no animation.

**Expected behaviour**
Normal splash screen animation.

_Copied from original issue: pop-os/iso#164_

**Comment by brs17** [comment]
Closing this issue because the splash screen will be removed in 18.04.
