### ISSUE TITLE
Graphical Problems while using AMD cpu with integrated gpu.

### ISSUE THREAD

**Issue by AKA-Beastmaster** [pop-os/pop#1201]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
This applies to any native Linux game

**Issue/Bug Description:**
 When playing video games, the in-game textures appear torn. There also other numerous graphical issues, like there being black flickering areas at the edges of in-game objects 

**Steps to reproduce (if you know):**
Use a system with an 'Athlon 3000g' with it's integrated graphics. Make sure you're using 'amdgpu' driver. Then play any native Linux game.

**Expected behavior:**
The game should work normally

**Other Notes:**
Windows games running through Wine, work perfectly fine

PC specs:

PCPartPicker part List: https://pcpartpicker.com/list/vC6pf9

CPU: AMD Athlon 3000G 3.5 GHz Dual-Core Processor 
Motherboard: MSI B450M PRO-M2 MAX Micro ATX AM4 Motherboard  
Memory: Corsair Vengeance LPX 8 GB (1 x 8 GB) DDR4-2666 CL16 Memory  
Storage: Team MS30 512 GB M.2-2280 Solid State Drive  
Case: Thermaltake Versa H18 MicroATX Mini Tower Case  
Power Supply: Thermaltake Smart Series 430 W 80+ Certified ATX Power Supply

**Comment by mmstick** [comment]
There's no guarantee that games run through wine will render correctly. Check with ProtonDB / WineHQ for workarounds required. It's not uncommon for games to have these issues — especially when using OpenGL for rendering instead of Vulkan.

**Comment by AKA-Beastmaster** [comment]
> There's no guarantee that games run through wine will render correctly. Check with ProtonDB / WineHQ for workarounds required. It's not uncommon for games to have these issues — especially when using OpenGL for rendering instead of Vulkan.

Oh yeah right, I probably should have updated this issue. 
I found a solution with these to posts:
https://www.reddit.com/r/archlinux/comments/gbg0ou/psa_workaround_for_ryzen3mesa20_opengl_glitches/?utm_source=share&utm_medium=web2x&context=3

https://www.reddit.com/r/linux_gaming/comments/i38fkz/graphical_issues_with_amd_integrated_graphics/?utm_source=share&utm_medium=web2x&context=3
