### ISSUE TITLE
Screen no signal after selecting 2560*1440

### ISSUE THREAD

**Issue by arjenp** [pop-os/pop#1206]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When selecting 2560 x 1440 resolution my screen goes no signal found.  It is in the overview of the displays to select and also in xrandr. But when selecting it the screen doesn't receive a signal.
The screen in question is a iiyama ProLite XUB2792QSU-B1.

**Steps to reproduce (if you know):**

**Expected behavior:**
That the screen would get a signal.

**Other Notes:**

**Comment by mmstick** [comment]
Are you using DisplayPort? Maybe your cable isn't quite up to specs, or there's an issue between your display and the graphics card.

**Comment by arjenp** [comment]
I tried it with the thunderbolt one and with that it worked. But with the normal hdmi port it works fine with windows but not on pop_os. So it looks like the signal that pop_os sends is different then on windows on the 2560X1440.

**Comment by mmstick** [comment]
There's probably a patch in Windows for bad EDID info from this particular monitor. If the monitor has the ability to do firmware updates, it may be fixed with a firmware update of the monitor.
