### ISSUE TITLE
Discord package outdated

### ISSUE THREAD

**Issue by DanielPower** [pop-os/pop#1208]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
discord:
  Installed: (none)
  Candidate: 0.0.10
  Version table:
     0.0.10 500
        500 http://apt.pop-os.org/proprietary focal/main amd64 Packages

**Issue/Bug Description:**
Discord package is outdated. Latest version is 0.0.11. Since you cannot connect to the Discord servers with an outdated version (it simply gives you a window telling you to update), I would suggest dropping the package from your repos so that when users search the Pop Shop, they'll find the flatpak on Flathub, which is more actively maintained.

The current experience is that a user will install Discord from the Pop Shop, and will then be told it's outdated when they try to run it. New users in particular may not know that there is a dropdown menu from which they can download a more recent package from Flathub.

**Steps to reproduce (if you know):**
Download Discord from Pop repository using Pop Shop or apt.

**Expected behavior:**
Package should be up to date. Or defaulted to the flatpak.

**Other Notes:**

**Comment by jacobgkau** [comment]
Earlier this year, the reason the Discord package was not dropped in favor of Flatpak was because the Flatpak wasn't working with game integration or drag-and-drop file attachments. There's some ongoing discussion about the file access situation, but it doesn't look like there is a road forward for game integration:

https://github.com/flathub/com.discordapp.Discord/issues/99

https://github.com/flathub/com.discordapp.Discord/issues/11

For now, the .deb package will need to be upgraded.

**Comment by DanielPower** [comment]
I wasn't aware of that limitation with the Flatpak. Thanks for pointing that out.

**Comment by mmstick** [comment]
Deb's been updated

**Comment by jacobgkau** [comment]
@mmstick @ids1024 I know we just updated from 0.0.10 to 0.0.11, but 0.0.12 was released today, and 0.0.11 is no longer launching.

**Comment by DanielPower** [comment]
Discord 0.0.13 has been released, so the deb package no longer works.

**Comment by GDBlaster** [comment]
0.0.24 is out and it broke the old one the old one same as always apparently
