### ISSUE TITLE
Black Screen with blinking cursor

### ISSUE THREAD

**Issue by rajshak123** [pop-os/pop#1209]
I love Pop OS esp the Tile feature.Its fast & has nice & clean GUI.

 **Issue/Bug Description:** POP OS doesnt boot.After Try or Install Pop OS,it doesnt move forward just freezes with a blinking cursor.

**Steps to reproduce (if you know):** I think it has got to do something with my CPU architecture or Nvidia graphics card.
I had tested both POP OS image (normal one & one with support for Nvidia drivers).

I am already using it on other laptop with Intel i5 & POP OS runs fine but i bought this new laptop HP Omen 15 & after clicking on try or Install OS it directs to a black screen with blinking cursor.

**Specs of laptop:** 
**CPU**: AMD Ryzen 7 4800H with Radeon Graphics
**External GPU** : Nvidia GeForce GTX 1650 Ti

**Expected behavior:** Blank screen with blinking shouldnt appear for too long & should redirect to testing window from where i can test & install POP OS.

**Comment by mmstick** [comment]
Recently-released laptops with Ryzen 4000 processors aren't supported with the current Linux kernel. This would be one of them. You'll have to try again with 20.10 when that releases, as it should feature a kernel new enough to support it. You can ask HP for specifics on which kernel works with their hardware.

**Comment by rajshak123** [comment]
@mmstick Not sure about this.I was able to install Fedora 32 & Nvidia drivers without any hassle.

**Comment by mmstick** [comment]
Fedora 32 has a newer kernel than Ubuntu 20.04; so you'll have to revisit in 20.10
