### ISSUE TITLE
Evaluate packages that do not have groovy branches

### ISSUE THREAD

**Issue by jackpot51** [pop-os/pop#1214]
Create master_groovy branches:

- [x] gdm3
- [x] gnome-control-center
- [x] gnome-online-accounts
- [x] gnome-settings-daemon
- [x] gnome-shell
- [x] gnome-shell-extension-system76-power
- [x] gnome-terminal
- [x] libhandy
- [x] linux
- [x] meta-python
- [x] mutter
- [x] pyflatpak
- [x] python-apt
- [x] shell
- [x] shell-shortcuts
- [x] steam
- [x] systemd
- [x] tensorman
- [x] transition
- [x] ubuntu-drivers-common

Verify package built on groovy:

- [x] gdm3
- [x] gnome-control-center
- [x] gnome-online-accounts
- [x] gnome-settings-daemon
- [x] gnome-shell
- [x] gnome-shell-extension-system76-power
- [x] gnome-terminal
- [x] libhandy
- [x] linux
- [x] meta-python
- [x] mutter
- [x] pyflatpak
- [ ] python-apt
- [x] shell
- [x] shell-shortcuts
- [x] steam
- [x] systemd
- [x] tensorman
- [x] transition
- [x] ubuntu-drivers-common

Ensure package is up to date with Ubuntu:

- [x] gdm3
- [x] gnome-control-center
- [x] gnome-online-accounts
- [x] gnome-settings-daemon
- [x] gnome-shell
- [x] gnome-terminal
- [x] libhandy
- [x] linux
- [x] mutter
- [ ] python-apt
- [x] shell
- [x] shell-shortcuts
- [x] steam
- [x] systemd
- [x] ubuntu-drivers-common

**Comment by ids1024** [comment]
I've deleted the `master_groovy` branch of libhandy, since it's just a backport of a package already in groovy.
