### ISSUE TITLE
"Edit Software Sources..." Button Does Nothing in Pop!_Shop

### ISSUE THREAD

**Issue by m1waterman88** [pop-os/pop#1216]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shop:
  Installed: 3.3.0pop0~1596509290~20.04~027c175
  Candidate: 3.3.0pop0~1596509290~20.04~027c175
  Version table:
 *** 3.3.0pop0~1596509290~20.04~027c175 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Clicking on the "Edit Software Sources..." button doesn't open the software sources menu.

**Steps to reproduce (if you know):**
Open the Pop!_Shop and click on the "Edit Software Sources..." button.

**Expected behavior:**
Clicking on the "Edit Software Sources..." opens the software sources menu to configure software sources.

**Other Notes:**
This is a brand new Thelio-r2 that I set up today.

**Comment by mmstick** [comment]
Try running `repoman` from a terminal. That's what that button launches.

**Comment by m1waterman88** [comment]
> Try running `repoman` from a terminal. That's what that button launches.

I just tried, and I'm getting a "permission denied" error from dbus, even when running with sudo or as root directly.

**Comment by sysdrum** [comment]
At this time on 3 systems I can only install software from the Pop! Shop from flat pack and it is refusing to update without doing a apt update && apt upgrade with sudo from terminal.
Installing works fine from terminal.
This start 48 hours ago after my last round of updates.
repoman does not work it gives me a dbus error no matter how it is run in terminal. 
All  3 system are:
20.04 Pop OS
5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP

**Comment by m1waterman88** [comment]
Still the same:

```
m1waterman88@dark-thelio:~$ repoman 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 177, in activate_name_owner
    return self.get_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 361, in get_name_owner
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get owner of name 'org.pop_os.repoman': no such name

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/repoman", line 50, in <module>
    from repoman import main
  File "/usr/lib/python3/dist-packages/repoman/main.py", line 32, in <module>
    from .window import Window
  File "/usr/lib/python3/dist-packages/repoman/window.py", line 25, in <module>
    from .headerbar import Headerbar
  File "/usr/lib/python3/dist-packages/repoman/headerbar.py", line 25, in <module>
    from .ppa import PPA
  File "/usr/lib/python3/dist-packages/repoman/ppa.py", line 33, in <module>
    privileged_object = bus.get_object('org.pop_os.repoman', '/PPA')
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 241, in get_object
    return self.ProxyObjectClass(self, bus_name, object_path,
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 250, in __init__
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 182, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 277, in start_service_by_name
    return (True, self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: Failed to execute program org.pop_os.repoman: Permission denied
m1waterman88@dark-thelio:~$ 

```

**Comment by m1waterman88** [comment]
Aaron was able to resolve it with a simple command:

```sudo apt install --reinstall pop-shop dbus repoman```

I tried this with repoman, so either pop-shop or dbus must have been the culprit.
