### ISSUE TITLE
Default Look and feel of QT5 and QT4 applications are not consistent with GTK theme

### ISSUE THREAD

**Issue by gamunu** [pop-os/pop#122]
**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)
 * Related Application and/or Package Version - GTK 3.22.25
```

**Issue/Bug Description**

Add fixes to make look and feel of QT applications more uniform with GTK styling

e.g: Installing qt5-styleplugins and setting the following environment variable: `QT_QPA_PLATFORMTHEME=gtk2`

more information,
[Uniform look for Qt and GTK applications](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications)

**Steps to reproduce (if you know)**

Install and open QT application e.g: vlc

**Expected behavior**

Consistent look with other applications

**Other Notes**

**Comment by sramkrishna** [comment]
@jackpot51 do you think you can add the right packages to Pop!_OS to make this work?
