### ISSUE TITLE
Applications are disappearing

### ISSUE THREAD

**Issue by avdzm** [pop-os/pop#1222]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I have noticed some applications that i have installed have disappeared.
I had installed lutris and shotwell via pop shop and vlc via apt-get.

**Steps to reproduce (if you know):**
I checked the logs and i found a dist-upgrade had uninstalled some of my applications.

Start-Date: 2020-08-29  08:55:02
Commandline: apt dist-upgrade
Requested-By: avdzm (1000)
Install: libqt5gui5-gles:amd64 (5.12.8+dfsg-0ubuntu1, automatic)
Remove: lutris:amd64 (0.5.7.1-202007191015~ubuntu20.04.1), xserver-xorg-video-qxl:amd64 (0.1.5+git20200331-1), libqt5svg5:amd64 (5.12.8-0ubuntu1), gir1.2-clutter-1.0:amd64 (1.26.4+dfsg-1), vlc-plugin-qt:amd64 (3.0.9.2-1), vlc-plugin-skins2:amd64 (3.0.9.2-1), rhythmbox-plugins:amd64 (3.4.4-1ubuntu2), gnome-sushi:amd64 (3.34.0-2), xserver-xorg-input-wacom:amd64 (1:0.39.0-0ubuntu1), cheese:amd64 (3.34.0-1build1), gnome-2048:amd64 (3.36.0-1), gir1.2-rb-3.0:amd64 (3.4.4-1ubuntu2), gstreamer1.0-gtk3:amd64 (1.16.2-1ubuntu2), gir1.2-cogl-1.0:amd64 (1.22.6-1), libqt5gui5:amd64 (5.12.8+dfsg-0ubuntu1), gnome-sound-recorder:amd64 (3.34.0-1), xserver-xorg-video-intel:amd64 (2:2.99.917+git20200226-1), vlc:amd64 (3.0.9.2-1), gnome-online-accounts:amd64 (3.36.0-1ubuntu1pop1~1583953963~20.04~22b5af3), shotwell:amd64 (0.30.10-0ubuntu0.1), gir1.2-gst-plugins-base-1.0:amd64 (1.16.2-4), totem-plugins:amd64 (3.34.1-2ubuntu2), gir1.2-totem-1.0:amd64 (3.34.1-2ubuntu2), gir1.2-coglpango-1.0:amd64 (1.22.6-1), gir1.2-webkit2-4.0:amd64 (2.28.4-0ubuntu0.20.04.1), gnome-shell-extension-system-monitor:amd64 (38+git20200414-32cc79e-1), gstreamer1.0-gl:amd64 (1.16.2-4)
End-Date: 2020-08-29  08:55:17

Start-Date: 2020-08-29  08:55:48
Commandline: apt dist-upgrade
Requested-By: avdzm (1000)
Remove: vlc-plugin-video-output:amd64 (3.0.9.2-1), qt5-gtk-platformtheme:amd64 (5.12.8+dfsg-0ubuntu1), zoom:amd64 (5.2.440215.0803), libqt5widgets5:amd64 (5.12.8+dfsg-0ubuntu1), libegl1-mesa:amd64 (20.3~git2008290730.373e25~oibaf~f), libqt5x11extras5:amd64 (5.12.8-0ubuntu1), gnome-startup-applications:amd64 (3.36.0-2ubuntu1), libqt5gui5-gles:amd64 (5.12.8+dfsg-0ubuntu1)
End-Date: 2020-08-29  08:56:01

**Expected behavior:**
To upgrade without uninstalling my applications.
I know i should have paid more attention, but still a little weird.

**Other Notes:**
I have uploaded the history log file
[history.log](https://github.com/pop-os/pop/files/5184714/history.log)

**Comment by mmstick** [comment]
Be very careful when you run `dist-upgrade`, because it will remove things if there's a conflict somewhere.
