### ISSUE TITLE
io.elementary.appcenter update daemon prevents desktop from running in wayland session

### ISSUE THREAD

**Issue by Aceler** [pop-os/pop#123]
**Reporter info**

```
 * Distribution - NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"

* Package - pop-shop:
  Установлен: 0.2.7-1+1513960937+17.10~e48e495
  Кандидат:   0.2.7-2+1516129929+17.10~eae4fb3
  Таблица версий:
     0.2.7-2+1516129929+17.10~eae4fb3 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu artful/main amd64 Packages
 *** 0.2.7-1+1513960937+17.10~e48e495 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description**
I use wayland session for desktop, because X session have some bugsm that annoying for me. The problem is, that sometimes after login, the system hangs up entirely. I made some research and found out, that it is not a gdm3 but, it is a bug in appcenter (POP Shop). I waited some time and got a notification "you have new updates", after that system works normally.

I removed /etc/xdg/autostart/io.elementary.appcenter-daemon.desktop and system boots correctly every time since then. I made a test for more than a week to be sure.

**Steps to reproduce (if you know)**
Comment out WaylandEnable=false in /etc/gdm3/custom.conf to enable wayland session. Launch session several times, as bug is not always reproducible.

**Expected behavior**
System boot correctly without hangs.

**Other Notes**
I have AMD Radeon 7570 video card and Intel Core i3-2120, if it is matters. My notebook with Intel Pentium 977 and corresponding video card is not affected by this bug. Xorg session is not affected.

**Comment by sramkrishna** [comment]
Wayland isn't a tested setup for Pop!_OS.  I would expect that there would be bugs.  Unfortunately, Wayland is not a priority at the moment.  This bug report would be useful though once we start considering the Wayland session.

**Comment by Aceler** [comment]
OK, if you need an excessive Wayland testing, just call me :-)

**Comment by dragonbite** [comment]
Ubuntu just announced that they are going to X.org as the default, and allow Wayland as an option.  So it sounds like there will be less support in Pop! OS for Wayland.
