### ISSUE TITLE
After logging in, I have many memory hungry gdm-owned gnome session processes

### ISSUE THREAD

**Issue by timrichardson** [pop-os/pop#1235]
**Distribution (run `cat /etc/os-release`):**
 tim@indigo:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
tim@indigo:~$ 

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gdm3 ?

**Issue/Bug Description:**
After logging in, I have many gdm-owned processes. 

In a virtual pop os, these gdm processes die a few seconds after the user logs on.  (< ten seconds) 
But on my main desktop, they are not dying. 

What is killing them on my virtual pop install but is not killing them on my desktop?

One of the gdm-owned /usr/bin/gnome-shell processes will run away with resident ram, hitting > 3GB after 5 days of uptime for instance. 

restarting the shell has no effect because it is not my user. 
If I kill it, I get errors logged (see below)

tim@indigo:~$ ps -f -u gdm
UID          PID    PPID  C STIME TTY          TIME CMD
gdm         1377       1  0 16:13 ?        00:00:00 /lib/systemd/systemd --user
gdm         1384    1377  0 16:13 ?        00:00:00 (sd-pam)
gdm         1405    1377  0 16:13 ?        00:00:00 /usr/bin/pulseaudio --daemon
gdm         1407    1377  0 16:13 ?        00:00:00 /usr/libexec/tracker-miner-f
gdm         1414    1365  0 16:13 tty1     00:00:00 /usr/lib/gdm3/gdm-x-session 
gdm         1416    1414  0 16:13 tty1     00:00:05 /usr/lib/xorg/Xorg vt1 -disp
gdm         1419    1377  0 16:13 ?        00:00:00 /usr/bin/dbus-daemon --sessi
gdm         1432    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfsd
gdm         1459    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfsd-fuse /run
gdm         1465    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfs-udisks2-vo
gdm         1472    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfs-goa-volume
gdm         1476    1377  0 16:13 ?        00:00:00 /usr/libexec/goa-daemon
gdm         1552    1377  0 16:13 ?        00:00:00 /usr/libexec/goa-identity-se
gdm         1590    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfs-gphoto2-vo
gdm         1595    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfs-afc-volume
gdm         1600    1377  0 16:13 ?        00:00:00 /usr/libexec/gvfs-mtp-volume
gdm         1661    1414  0 16:13 tty1     00:00:00 /usr/libexec/gnome-session-b
gdm         1726    1377  0 16:13 ?        00:00:00 /usr/libexec/at-spi-bus-laun
gdm         1733    1726  0 16:13 ?        00:00:00 /usr/bin/dbus-daemon --confi
gdm         1774    1377  0 16:13 ?        00:00:00 /usr/libexec/gnome-session-c
gdm         1779    1377  0 16:13 ?        00:00:00 /usr/bin/gnome-keyring-daemo
gdm         1789    1377  0 16:13 ?        00:00:00 /usr/libexec/gnome-session-b
gdm         1797    1377  0 16:13 ?        00:00:03 /usr/bin/gnome-shell
gdm         1870    1797  0 16:13 ?        00:00:00 ibus-daemon --panel disable 
gdm         1873    1870  0 16:13 ?        00:00:00 /usr/libexec/ibus-dconf
gdm         1876    1377  0 16:13 ?        00:00:00 /usr/libexec/ibus-x11 --kill
gdm         1878    1377  0 16:13 ?        00:00:00 /usr/libexec/ibus-portal
gdm         1891    1377  0 16:13 ?        00:00:00 /usr/libexec/at-spi2-registr
gdm         1894    1377  0 16:13 ?        00:00:00 /usr/libexec/xdg-permission-
gdm         1909    1377  0 16:13 ?        00:00:00 /usr/bin/gjs /usr/share/gnom
gdm         1928    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-a11y-settin
gdm         1929    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-color
gdm         1930    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-keyboard
gdm         1931    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-media-keys
gdm         1933    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-power
gdm         1935    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-print-notif
gdm         1937    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-rfkill
gdm         1939    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-smartcard
gdm         1943    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-sound
gdm         1944    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-usb-protect
gdm         1947    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-wacom
gdm         1949    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-wwan
gdm         1954    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-xsettings
gdm         1963    1870  0 16:13 ?        00:00:00 /usr/libexec/ibus-engine-sim
gdm         1998    1377  0 16:13 ?        00:00:00 /usr/libexec/gsd-printer
gdm         2339    1377  0 16:13 ?        00:00:00 /usr/libexec/dconf-service
tim@indigo:~$ 

**Steps to reproduce (if you know):**
This happens at every boot. I can't find any extensions or software which causes this.
Is it due to some lock screen setting, or switch users setting? 

**Expected behavior:**
According to documentation I have found, after logging in, the gdm-owned sessions should be "torn down". 

**Other Notes:**
When I kill the problem process, and then go to virtual terminal one, it looks like a new gdm is spawned. 

If I just kill the process, I see this in 
journalctl _UID=110

Sep 14 16:49:46 indigo systemd[1377]: gnome-shell-x11.service: Main process exited, code=killed, status=9/KILL
Sep 14 16:49:46 indigo systemd[1377]: gnome-shell-x11.service: Failed with result 'signal'.
Sep 14 16:49:46 indigo systemd[1377]: gnome-shell-x11.service: Scheduled restart job, restart counter is at 2.
Sep 14 16:49:46 indigo systemd[1377]: Stopped target GNOME X11 Session (session: gnome-login).
Sep 14 16:49:46 indigo systemd[1377]: Stopping GNOME X11 Session (session: gnome-login).
Sep 14 16:49:46 indigo systemd[1377]: Stopped target GNOME X11 Session.
Sep 14 16:49:46 indigo systemd[1377]: Stopping GNOME X11 Session.
Sep 14 16:49:46 indigo systemd[1377]: Stopped target GNOME Shell on X11.
Sep 14 16:49:46 indigo systemd[1377]: Stopping GNOME Shell on X11.
Sep 14 16:49:46 indigo systemd[1377]: Stopped GNOME Shell on X11.
Sep 14 16:49:46 indigo systemd[1377]: Starting GNOME Shell on X11...

This repeats every few minutes
If I hit ctrl-alt-F1, a new sessions is spawned and the error messages go away.

**Comment by timrichardson** [comment]
In /var/lib/gdm/.local/share/xorg I think I have the x session log for the gdm session. 
The working install, in the VM, terminates with these lines:

```
5568.023] (II) event3  - VirtualPS/2 VMware VMMouse: device removed
[  5568.025] (II) UnloadModule: "libinput"
[  5568.025] (II) systemd-logind: releasing fd for 13:67
[  5568.110] (II) UnloadModule: "libinput"
[  5568.110] (II) systemd-logind: releasing fd for 13:68
[  5568.421] (II) UnloadModule: "libinput"
[  5568.421] (II) systemd-logind: releasing fd for 13:66
[  5568.469] (II) UnloadModule: "libinput"
[  5568.469] (II) systemd-logind: releasing fd for 13:65
[  5568.485] (II) UnloadModule: "libinput"
[  5568.485] (II) systemd-logind: releasing fd for 13:64
[  5568.517] (WW) xf86CloseConsole: KDSETMODE failed: Input/output error
[  5568.517] (WW) xf86CloseConsole: VT_GETMODE failed: Input/output error
[  5568.517] (WW) xf86CloseConsole: VT_ACTIVATE failed: Input/output error
[  5568.520] (II) Server terminated successfully (0). Closing log file.
```

My desktop shows the mouse being removed, but the call to unload libinput never comes:

```
 4196.411] (II) event23 - Logitech M280/320/275: device removed
[  4196.411] (II) AIGLX: Suspending AIGLX clients for VT switch
[  4196.493] (II) systemd-logind: got pause for 13:89
[  4196.493] (II) systemd-logind: got pause for 13:84
[  4196.493] (II) systemd-logind: got pause for 13:87
[  4196.493] (II) systemd-logind: got pause for 13:68
[  4196.493] (II) systemd-logind: got pause for 13:65
[  4196.493] (II) systemd-logind: got pause for 13:83
[  4196.493] (II) systemd-logind: got pause for 13:64
[  4196.493] (II) systemd-logind: got pause for 13:66
[  4196.493] (II) systemd-logind: got pause for 13:82
[  4196.493] (II) systemd-logind: got pause for 226:0
[  4196.493] (II) systemd-logind: got pause for 13:67


that's the end of the file, it does not terminate. 
```

**Comment by timrichardson** [comment]
I can kill all the gdm processes by killing the gdm-owned process running /usr/lib/xorg/Xorg

ctrl-alt-f1 starts the gdm-owned xserver again, and once again, it does not terminate

**Comment by jacobgkau** [comment]
Thank you for filing an issue. I see that you also filed https://github.com/pop-os/gdm3/issues/2. Are these two issues for the same problem?

**Comment by mmstick** [comment]
Not related to Pop Shell, and this is an upstream issue in GNOME
