### ISSUE TITLE
exclude certain programs from tiling

### ISSUE THREAD

**Issue by tbeason** [pop-os/pop#1236]
As the title says, I would like to be able to exclude certain windows or programs from participating in window tiling. 

Use cases:
- I pull up the system monitor to check my memory usage, suddenly my windows are scattered around.
- I click a "help" tip on a website that opens a small browser window displaying the help, suddenly my windows are scattered around.
- I open the file explorer in order to open a new file, suddenly my windows are scattered around.

I think you get the idea.

I understand that I can user `Super+G` _ex post_ on problematic windows, but that isn't a preventative thing.

**Comment by mmstick** [comment]
Already possible by defining the WM details to `~/.config/pop-shell/config.json`

**Comment by tbeason** [comment]
Where is this documented so that I can understand what to put there?

**Comment by mmstick** [comment]
https://github.com/pop-os/shell/blob/master_focal/src/config.ts#L18:L29

https://github.com/pop-os/shell/blob/master_focal/src/config.ts#L36:L41

**Comment by tbeason** [comment]
It's not much but I'll take it.

Thanks

**Comment by tbeason** [comment]
Sorry, not sure this is working for me. I edited it to be this
```
{
  "float": [
    {
      "class": "vpnui",
      "title": "Cisco AnyConnect Secure Mobility Client"
    },
    {
      "class": "gnome-system-monitor",
    },
    
      "class": "gnome-control-center",
    }

  ],
  "log_on_focus": false
}
```
but those three programs still tile when I open them. I have turned on/off tiling and restarted my system.

**Comment by mmstick** [comment]
Your values aren't valid. To see the correct values, enable `log_on_focus` and watch gnome-shell logs when clicking on windows.
