### ISSUE TITLE
NetworkManager changes resolv.conf on reboot

### ISSUE THREAD

**Issue by AtomicCons** [pop-os/pop#124]
`Community,`

I have an interesting issue, not sure if it is OS related or VPN related.

What Happens:
When I set a nameserver at /etc/resolv.conf, save changes, then reboot, Network Manager re-writes the file and I end up with only
 `# Generated by NetworkManager`
`nameserver 127.0.1.1` 
 as an entry.

If I enter a custom nameserver, save changes, turn on PIA, turn it back off, my custom name server stays. 

Anyone else experiencing this?

**Comment by sramkrishna** [comment]
Is PIA - personal internet access? (eg VPN?)

**Comment by AtomicCons** [comment]
@sramkrishna 
Yes, private internet access. this still happens after I uninstall PIA. So unsure if this is PIA related or Network Manager related.
If confirmed not Network Manager, i'm comfortable with closing this ticket and ill poke PIA and see what they think.

**Comment by AtomicCons** [comment]
Confirmed PIA issue.
