### ISSUE TITLE
Screen artifacts using dedicated Radeon RX5500XT GPU

### ISSUE THREAD

**Issue by dbidwell94** [pop-os/pop#1242]
**Distribution (run `cat /etc/os-release`):**
 
Pop!_OS 20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Flatpak versions of VS Code, Slack, Zoom, OBS Studio, MS Teams

**Issue/Bug Description:**

Screen artifacts 

**Steps to reproduce (if you know):**

**Expected behavior:**

No screen artifacts

**Other Notes:**

Originally was using the iGPU (AMD Ryzen5 2400g). Switched to RX5500XT for dual monitor support Got these issues:

https://ibb.co/M9cXKr6
https://ibb.co/Nsf4LHR

**Comment by Aisyk** [comment]
I had theses artefacts with my PopOS. Solution : update to a newer Mesa.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/3323
