### ISSUE TITLE
Firefox window disappears after running for a while

### ISSUE THREAD

**Issue by morganwahl** [pop-os/pop#1249]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
firefox:
  Installed: 80.0.1+build1-0ubuntu0.20.04.1
  Candidate: 80.0.1+build1-0ubuntu0.20.04.1
  Version table:
 *** 80.0.1+build1-0ubuntu0.20.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     75.0+build3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```

**Issue/Bug Description:**

After running for a while, eventually the firefox window just becomes completely transparent. The window manager (gnome-shell) still sees it, and I can quit firefox. The dialog to ask me whether I want to quite with open tabs opens up, but is just a blank window. Thankfully I know where the "close tabs" button is and I click there and it works.

So, input events seem to work find and the window manager still sees the window, but it's gone.

If I run firefox on the console I see this output when it happens:

```
Unflushed glGetGraphicsResetStatus: 0x92bb
[GFX1-]: [OPENGL] Failed to init compositor with reason: FEATURE_FAILURE_OPENGL_CREATE_CONTEXT
```

There is an upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1535721 that suggests looking at the value of `layers.acceleration.force-enabled` . Indeed it's set to true by default in this build.

Looking at the package version, I thought was an Ubuntu package, and filed a bug with them: 

https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/1896508

```
$ apt show firefox
Package: firefox
Version: 80.0.1+build1-0ubuntu0.20.04.1
```

```
$ firefox --full-version
Mozilla Firefox 80.0.1 20200831163820 20200831163820
```

But, poking around the `firefox` package's files, I see this:

```
$ cat /usr/lib/firefox/defaults/pref/pop-default-settings.js
pref("layers.acceleration.force-enabled", true);
pref("widget.content.gtk-theme-override", "Pop");
```

I'm on an oryx pro 5, running with the nvidia driver, since I need external monitors to work.

**Steps to reproduce (if you know):**

Run firefox for a while... eventually errors. Don't see a particular pattern to it other than that.

I haven't tested on the integrated graphics (intel). Could do that if it helps.

**Expected behavior:**

Window doesn't disappear.

**Other Notes:**

I'm a professional software developer, so I'm OK with running firefox with some kind of debug logging if that helps.

For now, I'll set `layers.acceleration.force-enabled` to `false`.

**Comment by Adam-Kadmon** [comment]
I'm not sure if this is the done thing, but I just wanted to add that I've had the same problem for a while. Firefox reliably turns transparent after a while. Responds to super+q and can be opened normally straight after closing. I've read at least two more reports on the Planet Pop forums

**Comment by jacobgkau** [comment]
https://github.com/pop-os/default-settings/pull/96 should fix this, although it may reduce performance. Until that's released, when this issue occurs, you should be able to recover Firefox without closing/re-opening by restarting GNOME Shell (press Alt-F2, r, and Enter.)

If you want to apply that fix before it's released, you can open `about:config`, search for `layers.acceleration.force-enabled` and set it to `false`, search for `gfx.xrender.enabled` and set it to `true`, and optionally search for `layout.frame_rate` and set it to `144` (or the refresh rate of your display) if your display is running at more than 60Hz.

**Comment by jacobgkau** [comment]
This was fixed by https://github.com/pop-os/default-settings/pull/96.
