### ISSUE TITLE
software updates from popshop even when password for authentication is wrong. 

### ISSUE THREAD

**Issue by ShashankArora92** [pop-os/pop#1263]
**Issue/Bug Description:**
when we receive an update from the Pop os community and we install that update from the pop shop, it installs that update even when the password for authentication provided is wrong. After installing that update from the pop shop hangs.

**Comment by leviport** [comment]
Did you see which updates were available before installing? Flatpak updates don't require authentication since they install at the user level, so I believe those updates can install even when the wrong password is entered. The hang is troubling though. I will see if I can make this happen next time I have updates available.

**Comment by ShashankArora92** [comment]
I only install .deb softwares so they require my authentication.

**Comment by leviport** [comment]
And you're certain there are no flatpak runtimes installed? IIRC, you don't necessarily need to have a flatpak application installed in order to have a flatpak runtime installed.

**Comment by ShashankArora92** [comment]
I can tell you about my last update...it was of firefox and which is .deb version in my laptop. I entered wrong password and installation started. After completion on installation it never finishes just keep on going. I have to manually stop it by closing pop shop.

**Comment by ShashankArora92** [comment]
This is what happens everytime when I enter wrong password. I have to close pop shop in order to finish software's installation. I don't know if it is affecting my OS or not.

**Comment by leviport** [comment]
On my machine this morning, I had 5 updates available. Two of them were flatpak runtimes. In Pop Shop, I clicked "Update All" and entered an incorrect password. The password prompted me to try again, so I again entered a wrong password, three more times. Each time I was prompted again, so I closed the prompt. The flatpak packages updated, but the .debs did not, meaning Pop Shop now showed 3 updates. When I tried to update and authenticate with the wrong password again, I keep getting prompted to try again, as expected. If I then close the prompt, none of the .debs are updated, despite Pop Shop briefly flashing an "Updating" progress bar. The progress bar flashing is a UI bug, but everything underneath seems to be working as expected.

If Firefox never actually updated, my suspicion is that you're seeing the progress bar appear when it should not, but no updates are actually being applied. If you can readily reproduce this issue, the next time you have an update in Pop Shop, can you check the version of that package with `apt policy` both before and after reproducing the bug? That will tell us if the update is really being installed.

**Comment by ShashankArora92** [comment]
Ok.. thnx for your help.
