### ISSUE TITLE
Super+Q (default hotkey to close active window) not working

### ISSUE THREAD

**Issue by Eurus100** [pop-os/pop#1265]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Super+Q (default hotkey to close active window) not working upon return from Suspend.

**Steps to reproduce (if you know):**

Upon return from Suspend, Super+Q fails to work. It will not close active window of browser, terminal, or other default and installed application windows that I have tried. Whether there is a single active window, or multiple open windows, Super+Q fails to work.

After a reboot, Super+Q will work again, but stops working after a return from Suspend. Each time, I have to reboot in order for it to function again.

**Expected behavior:**

Super+Q should close active window.

**Other Notes:**

Absolutely love this OS — and my old Galago UltraPro (which is still going strong)!

Thank you System76 and contributors to Pop!_OS for all of the hard work you put into your great products and contributions to the open-source community!

**Comment by leviport** [comment]
Interesting, I can't seem to make this happen. If you're in the state where the hotkey isn't working, does restarting gnome-shell (Alt+F2, type `r` and hit enter) make it start working again?

**Comment by Eurus100** [comment]
Seems to have magically resolved itself today!  It hasn't happened all day through multiple resumes from suspend, so I never even had to try restarting the shell or resort to rebooting today.

If it's okay, I'd like to keep this issue open another day or two, just in case.  Thank you for your super-fast response!

*I also should have mentioned in my original post that I use Dash to Dock, in case it was some extension conflict.

Thanks again!

**Comment by Eurus100** [comment]
It's been functioning properly for two days now, so whatever it was seems to have resolved itself.

Thanks again!
