### ISSUE TITLE
Google Chrome display issues using AMD grpa

### ISSUE THREAD

**Issue by nofluffdigital** [pop-os/pop#1271]
**Distribution (run `cat /etc/os-release`):**
 
 POPOS (Ubuntu 20.04)
```bash
Linux pop-os 5.4.0-7642-generic 20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Google Chrome (v85)

**Issue/Bug Description:**
On Google Chrome there appears to be display / graphic issues that only affect the top left (under address bar) corner of the screen. It appears that this only occurs when the mouse is active in this area, or the page is being scrolled

**Steps to reproduce (if you know):**
Open Google Chrome browser, start typing in the address bar, or scrolling in the Google Chrome settings

**Expected behavior:**
No display issues 

**Other Notes:**
System details:

- CPU: i7-6700
- GPU: AMD Radeon R9 390x (Running default popos graphic drivers)

**Comment by nofluffdigital** [comment]
Forgot to add video example: https://youtu.be/6QI1R1hVlPw

**Comment by holmes1d** [comment]
Try turning off Chrome hardware acceleration in settings

**Comment by nofluffdigital** [comment]
@holmes1d Yep that did the trick! Thanks - Closing issue.
