### ISSUE TITLE
Second screen in dual screen is independent of desktop

### ISSUE THREAD

**Issue by hugomilan** [pop-os/pop#129]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
When I'm in dual screen, if I press the Ubuntu button, which allows me to change the desktop I'm working in, I can only change the desktop on my first screen. No matter which desktop I chose for the first screen, the desktop for the second screen is static. Is it expected?

**Steps to reproduce (if you know)**
Open windows and scatter them in different desktops. Then press the Ubuntu (or Windows) key to change the desktop you are working with. Only the desktop on the first screen changes.

**Expected behavior**
When changing the desktop, it should change the desktop for both, first and second screen.

**Other Notes**

**Comment by sramkrishna** [comment]
yes, this is expected behavior.  The primary screen can move from workspace to workspace, the secondary screen is static.  You can change the behavior in GNOME Tweaks.  Hit the ubuntu button and type tweaks.  Then go to Workspaces.  Under Display Handling, unclick "Workspaces on primary display only" and you should be good to go.

**Comment by cassidyjames** [comment]
@sramkrishna Tweaks is not pre-installed on Pop!\_OS, so the first step would be installing it from Pop!\_Shop.

**Comment by beltet** [comment]
> yes, this is expected behavior. The primary screen can move from workspace to workspace, the secondary screen is static. You can change the behavior in GNOME Tweaks. Hit the ubuntu button and type tweaks. Then go to Workspaces. Under Display Handling, unclick "Workspaces on primary display only" and you should be good to go.

Thanks! Worked like a charm for me!

**Comment by mastoj** [comment]
@sramkrishna , do you know if there is possible to have the workspaces on the different screens to be independent on each other? I mean, if I do super+shift+up on one screen only that screen should change workspace and not both.
