### ISSUE TITLE
Increasing number of freezes

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1293]
Hi, 
I'm experiencing often freezes of my POP_OS 20.04. This now happens a couple of times a day. 
I'm running it on Dell XPS 17 (9700) 

Which kind of diagnostics I can help with?

Thanks!

**Comment by leviport** [comment]
This sounds like a duplicate of https://github.com/pop-os/pop/issues/1172

Let me know if I am mistaken and I will reopen.
