### ISSUE TITLE
Weird orange line below the top bar

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1294]
Hi, this has been happening in the last couple of weeks, where I suddenly get some weird orange line below the top bar: 

![image](https://user-images.githubusercontent.com/6358061/96036171-60e3ea80-0e64-11eb-8975-30c96f02adb0.png)

Then I need to do `ALT + F2 -> r` to let the issue disappear. 
I'm not sure how to troubleshoot it. 

Thanks

**Comment by leviport** [comment]
This is the Stacking feature in Pop!_OS. Hitting `Super` + `S` converts a window into a stack, on which you can stack multiple windows on top of. The yellow bar you are seeing will begin dividing into tabs as you add other windows to the stack. If you want to deactivate stacking mode, simply hit `Super` + `S` once more.

**Comment by dodalovic** [comment]
Perfect @leviport thanks!
