### ISSUE TITLE
Close Button disapears and does not return during installation

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#13]
_From @brs17 on October 13, 2017 22:0_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
After choosing an installation type and selecting install, a confirmation for writing changes to disk appears. If the user selects "Go back" the close button does not reapear.

![screenshot from 2017-10-13 14-10-09](https://user-images.githubusercontent.com/7460774/31568026-883682f0-b02f-11e7-877e-8891ca4325db.png)

![screenshot from 2017-10-13 14-10-54](https://user-images.githubusercontent.com/7460774/31567999-6d016d88-b02f-11e7-9933-f853563f65c4.png)

![screenshot from 2017-10-13 14-10-58](https://user-images.githubusercontent.com/7460774/31568000-6e432da8-b02f-11e7-85ba-968ac9c2e077.png)

**Expected behaviour**
The Close button should return when selecting "Go back".

**Other Notes**
The Close button disapears during the installation process (expected) and that is probably triggered by the user pressing "Install now". There isn't however, logic to return the Close button if Installation doesn't begin.

_Copied from original issue: pop-os/iso#161_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
