### ISSUE TITLE
What do you think about integrating steam for better experience and performance?

### ISSUE THREAD

**Issue by filipeGamaBR** [pop-os/pop#131]
What do you think of integrating steam and some games into the system to improve performance and gameplay had some difficulties and problems after installation such as: he did not want to start the steam just did the update and then did not open anymore.Thanks for the atention and sorry for my bad english.

GPU: IntelHD5500
Processor: corei3 5 gen.

**Comment by sramkrishna** [comment]
Hi there, we don't really want to include games or steam as part of the default installatiaon.  Adding steam is a quick install.  We would of course be interested in performance issues with nvidia or intel drivers though if there are issues after installing steam.  Thanks for the bug!

**Comment by filipeGamaBR** [comment]
Thanks a lot,Love the pop os and sorry for my bad english
