### ISSUE TITLE
Question: when will we get pop!_OS 20.10 ?

### ISSUE THREAD

**Issue by Amazeryogo** [pop-os/pop#1314]
So I had a question, Groovy Gorrila has been released yesterday, so when will we get 20.10 on pop!_OS?

**Comment by leviport** [comment]
Today

**Comment by jacobgkau** [comment]
Thank you for your interest! 20.10 has officially been released as of 9:00 MDT this morning. First, install all updates through the Pop!_Shop (or using `sudo apt update` / `sudo apt full-upgrade`). After that, navigate to Settings -> OS Upgrade (or run `pop-upgrade release upgrade`) to start the upgrade.

That said, this is not a forum, this is a development bug tracker. In the future, please see our [Twitter page](https://twitter.com/system76/), [blog](https://blog.system76.com/), or [website](https://system76.com/) for announcements, or the [Mattermost chat](https://chat.pop-os.org/) or [subreddit](https://old.reddit.com/r/System76/) for community discussion.

**Comment by Amazeryogo** [comment]
ok thanks
