### ISSUE TITLE
Alacritty Won't open in Pop_OS 20.10 [Walyland only]

### ISSUE THREAD

**Issue by jawadalkassim** [pop-os/pop#1316]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

alacritty:

  Installed: 0.5.0~1596299148~20.10~ac39dfd
  Candidate: 0.5.0~1596299148~20.10~ac39dfd

  Version table:
 *** 0.5.0~1596299148~20.10~ac39dfd 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.5.0~1596299148~20.04~ac39dfd 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages

**Issue/Bug Description:**
Won't open after 20.10 update only in Wayland, working in X11

**Steps to reproduce (if you know):**
updated to 20.10
switched to Wayland session
open Alacritty

**Expected behavior:**
run normally

**Other Notes:**

https://imgur.com/a/qQ02caL

**Comment by mmstick** [comment]
Have to raise it with alacritty and switch to X11.

**Comment by jawadalkassim** [comment]
https://github.com/alacritty/alacritty/issues/4206
it's alacritty issue with gnome 3.38 and Wayland

**Comment by mmstick** [comment]
I'll pull from master
