### ISSUE TITLE
Incomplete system translation (French)

### ISSUE THREAD

**Issue by gquittet** [pop-os/pop#1329]
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

System translate 75% to French and 25% stays in English.

**Steps to reproduce (if you know):**

1. Install PopOS 20.04 or 20.10
2. Set French language during installation
3. Finish the French language installation after reboot

**Expected behavior:**

The best behavior for newcomers is to have a system translate to 100% in the desired language.

**Other Notes:**

![Capture d’écran du 2020-10-25 15-04-00](https://user-images.githubusercontent.com/11082739/97109583-5501ef00-16d4-11eb-9af5-5c2a274539bd.png)

![Capture d’écran de 2020-10-25 15-04-37](https://user-images.githubusercontent.com/11082739/97109588-58957600-16d4-11eb-869e-26a4e3e5f316.png)

**Comment by leviport** [comment]
Thank you for the report! We are tracking this issue at https://github.com/pop-os/pop/issues/1224
