### ISSUE TITLE
20.10 Won't Boot with Thunderbolt Docking Station Attached 

### ISSUE THREAD

**Issue by havanahjoe** [pop-os/pop#1339]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"

Linux pop-os 5.8.0-7625-generic #26~1603126178~20.10~210fe73-Ubuntu SMP Tue Oct 20 01:12:15 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Issue/Bug Description:**

After upgrade to 20.10, laptop will not boot with the 5.8 kernel if the docking station is connected. Previous kernel (in boot menu) works fine.

If I boot into the latest kernel without the docking station attached, the system boots without a problem. I can then attach the docking station and everything is happy.

When it didn't boot, I was able to get text output by removing the silent and splash entries from the boot entry, but all I saw was some quick garbage (random characters) after the version number (ie Pop!_OS 20.10&@*$) and then it was stuck.

Without disabling the splash, all I see is the Dell logo.

Using an XPS 9530 with a TB15 docking station

**Steps to reproduce (if you know):**

Turn on laptop and let it boot into the default 5.8 kernel on 20.10. Machine will not boot, will be stuck on Dell splash screen and needs to be powered down or rebooted with Ctrl Alt Del. 

**Other Notes:**

Unplugging docking station will allow system to boot. This did not happen on 20.04 nor does it happen when booting into the older kernel through the boot menu.

**Comment by nint8835** [comment]
I am also running into the same problem on an XPS 15 9570 with a Dell TB16 dock. Laptop sticks at the Dell splash screen unless I boot with the dock unplugged. Worked on 20.04, only broke after upgrading.

**Comment by andymuk** [comment]
Running into issues with Thinkpad T480 with Thunderbolt dock.

System seems to boot however goes to sleep at the login screen. I then find myself changing run levels until I get a login screen.

Again only seemed to break after upgrading from 20.04

**Comment by Paralda** [comment]
Removing "quiet" from kernel options allowed me to boot into 5.8.

I didn't try removing my dock, but this might help you.

**Comment by nint8835** [comment]
> Removing "quiet" from kernel options allowed me to boot into 5.8.
> 
> I didn't try removing my dock, but this might help you.

Using `sudo kernelstub -d quiet` to remove the kernel option fixed it for me, thanks for the suggestion!

**Comment by havanahjoe** [comment]
> > Removing "quiet" from kernel options allowed me to boot into 5.8.
> > I didn't try removing my dock, but this might help you.
> 
> Using `sudo kernelstub -d quiet` to remove the kernel option fixed it for me, thanks for the suggestion!

This doesn't work for me. 
![PXL_20201101_181325376](https://user-images.githubusercontent.com/5197858/97810788-4616c180-1c2b-11eb-91ea-4f3eee036f36.jpg)

I still get this. Unplugging the dock until it gets past this point is the only thing that works on my XPS and Thunderbolt dock

**Comment by jl-tric** [comment]
Same as @havanahjoe - Removed the quiet option, but still cant boot. This is with a Dell XPS 9750 and TB16 dock.

**Comment by lundsted** [comment]
Same as @havanahjoe - Removed the quiet option, but still cant boot. This is with a Dell XPS 9750 and TB16 dock.

**Comment by pahofmann** [comment]
I also have issues with the XPS15 9500 and TB19WD dock on Pop 20.10. 
With Kernel 5.4 everything is okay, with kernel 5.8 it seems random when the monitors connected to the dock will work. 

I haven't found a reliable way to produce/fix the issue. It appears most of the time and after some un/replugging and reboots the monitors work until the next reboot.

**Comment by havanahjoe** [comment]
New kernel upgrade installed today, along with Nvidia driver and Gnome updates. No change. Still crashing in the same place with docking station attached. Oddly, the kernel version is still the same, but the build date has changed... 

Linux pop-os 5.8.0-7625-generic #26~1604441477~20.10~d41e407-Ubuntu SMP Wed Nov 4 01:25:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by daniel-dsouza** [comment]
I'm having similar (among other issues) on a Dell Precision 7530 running Pop! OS 20.04.

- usually cannot boot with dock connected. Can always boot with the dock disconnected, I *think* I can always boot if the dock is connected but a display is not connected to the dock.
- internal display artifacts when a monitor is connected through the dock, displayport appears OK. This is using the iGPU.

Kernel version
`5.8.0-7625-generic #26~1603389471~20.04~f6b125f-Ubuntu SMP Thu Oct 22 20:35:49 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Hardware firmware is up to date:
- Dell Firmware: 1.13.1
- Dell WD19TB Firmware: 1.00.14.01

**Comment by ximian** [comment]
I've got a similar issue on my HP Elitebook 840 G2 running Pop!_OS with kernel 5.8.0-7625-generic. When the laptop is connected to HP 2013 UltraSlim Docking Station I cannot boot into the system.
I've also noticed that when I disconnect the laptop from the docking station and connect it again after "Please unlock disk cryptdata" (but before entering the password) dialog shows up then the system freezes.

**Comment by daniel-dsouza** [comment]
looks like there was a kernel update today, I'm now on: 

`5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu SMP Wed Nov 11 22:42:16 UTC  x86_64 x86_64 x86_64 GNU/Linux`

the NVidia GPU drivers were updated at the same time, now I have 455.38 installed.

I was able to reboot once while docked (see my previous post for specs) without issue. A sample size of one is useless, so I will update here if I encounter any issues.

**Comment by havanahjoe** [comment]
I can confirm that after installing the latest updates (kernel 5.8.0-7630 and Nvidia GPU drivers) I can also reboot with my docking station attached

**Comment by ximian** [comment]
I can also confirm that the newest kernel (5.8.0-7630-generic on Pop!_OS 20.04) also fixed problem for me (Intel® HD Graphics 5500, HP 2013 UltraSlim Docking Station).

**Comment by curiousercreative** [comment]
can this issue be closed?
