### ISSUE TITLE
Touchpad doesn't work on Lenovo Ideapad Gaming 3

### ISSUE THREAD

**Issue by domalak** [pop-os/pop#1341]
I've made a fresh install of Pop!_OS 20.10 on Lenovo IdeaPad Gaming 3 15ARH05 laptop. Everything works great!

Except the touchpad which doesn't work properly. I can't move the pointer, but clicking works.

I think OS didn't recognize the device. See xinput output:
```
➜  ~ xinput
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ MSFT0001:00 06CB:CE2D Mouse             	id=13	[slave  pointer  (2)]
⎜   ↳ MSFT0001:00 06CB:CE2D Touchpad          	id=14	[slave  pointer  (2)]
⎜   ↳ USB OPTICAL MOUSE                       	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Video Bus                               	id=8	[slave  keyboard (3)]
    ↳ Power Button                            	id=9	[slave  keyboard (3)]
    ↳ Integrated Camera: Integrated C         	id=11	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=15	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=12	[slave  keyboard (3)]

```

I think this is related to another very similar bug (slightly different device codes) reported here:
[https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190)
There users solved it by creating a patch and patching their kernels.

What should I do?

**Comment by domalak** [comment]
I've applied this patch:
[the patch](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190/+attachment/5418465/+files/0303-pinctrl-amd2.patch)
from the bug report above and it helped.

**Comment by PhantomHydrino** [comment]
Hello good sir, hope you are having a great day. May you please provide me the steps to apply this patch ?
I tried using patch -p1 command , but it didn't seem to work as such. My operating system is ubuntu budgie. Thanking you in advance.

**Comment by domalak** [comment]
Hi @PhantomHydrino ,
I wrote a little instruction on how to apply the patch if you go to this link:
[link](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190)
and see comment #254.

There is another way as I see from further comments there. It's to install kernel 5.11.* which already includes the fix. I personally still use kernel 5.8 to be in line with Pop OS and have to patch it every time kernel gets updates.

**Comment by PhantomHydrino** [comment]
Hello, good sir, @domalak , the thing is , I've tried using kernel 5.11 and it works fine with the touchpad , but, it doesn't accept nvidia drivers for some reason which makes the screen go crazy, in my case. Touchpad problem gets resolved but, graphics card problem comes into action while using kernel 5.11 (which is still in beta phase)

**Comment by domalak** [comment]
Then it was right for me to stay with 5.8

**Comment by PhantomHydrino** [comment]
Sir, I can't find your comment there

**Comment by domalak** [comment]
@PhantomHydrino turned I can give direct link to my comment
[https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190/comments/254](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1887190/comments/254)

**Comment by domalak** [comment]
hi @nevzatseferoglu ,
Can you give more info? Are you in the root folder of linux source when running patch command? Which source do you want to patch?
This `linux-signed-hwe-5.8-5.8.0` doesn't look like legit source. Also can you check if you have `drivers/pinctrl/pinctrl-amd.c` file there?

**Comment by nevzatseferoglu** [comment]
> hi @nevzatseferoglu ,
> Can you give more info? Are you in the root folder of linux source when running patch command? Which source do you want to patch?
> This `linux-signed-hwe-5.8-5.8.0` doesn't look like legit source. Also can you check if you have `drivers/pinctrl/pinctrl-amd.c` file there?

```
- Yes, I'm in the root folder.
- In your tutorial, after the  second command, you go through kernel which is 5.8 with cd. In my machine, kernel were signed.
- I have drivers and pinctrl directory, but there is no pinctrl-amd.c file in it. Problem probably was occured for that reason. Is is dangereous to add that .c file to my pinctrl directory. 
```

**Comment by domalak** [comment]
@nevzatseferoglu 
if after running `apt-get source linux-image-$(uname -r)` you get a different source then I can't help you. This is also pretty new for me. I am not sure if putting `.c` file will help. Are you on Pop OS 20.10 or 20.04?

**Comment by nevzatseferoglu** [comment]
20.04

**Comment by domalak** [comment]
That can explain the differences. Isn't it kernel 5.4 there for 20.04?

**Comment by nevzatseferoglu** [comment]
Yes, the kernel version is 5.4.

**Comment by marlightt** [comment]
hi @domalak ! 
really hope i can get to solve the exact same problem with this patch. have checked and the filename that appears to me is indeed (builtin) as an output to modinfo pinctrl-amd
the thing is, and that might be really basic but i really don't have enough knoledge to know how, i don't know how to download the patch of 179 comment as you explain in your own comment.
could please explain me how i can download the file?
give thanks since noww and apologize for the not so good english!

**Comment by domalak** [comment]
Hi @marlightt ,
just save these lines to some file and use it:
```
diff --git a/drivers/pinctrl/pinctrl-amd.c b/drivers/pinctrl/pinctrl-amd.c
index 9a760f5cd7ed..e786d779d6c8 100644
--- a/drivers/pinctrl/pinctrl-amd.c
+++ b/drivers/pinctrl/pinctrl-amd.c
@@ -472,7 +472,7 @@ static int amd_gpio_irq_set_type(struct
 		pin_reg &= ~(ACTIVE_LEVEL_MASK << ACTIVE_LEVEL_OFF);
 		pin_reg |= ACTIVE_LOW << ACTIVE_LEVEL_OFF;
 		pin_reg &= ~(DB_CNTRl_MASK << DB_CNTRL_OFF);
-		pin_reg |= DB_TYPE_PRESERVE_HIGH_GLITCH << DB_CNTRL_OFF;
+		/** pin_reg |= DB_TYPE_PRESERVE_HIGH_GLITCH << DB_CNTRL_OFF; */
 		irq_set_handler_locked(d, handle_level_irq);
 		break;
```

**Comment by domalak** [comment]
I think I can close this issue now. Pop OS 20.10 has been updated to kernel 5.11 and touchpad works out of the box without patching.
