### ISSUE TITLE
gnome-sushi doesn't work on PopOS 20.10

### ISSUE THREAD

**Issue by ctarx** [pop-os/pop#1346]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-sushi:
  Installed: 3.34.0-2
  Candidate: 3.34.0-2
  Version table:
 *** 3.34.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

no files preview

**Steps to reproduce (if you know):**

Install gnome-sushi and try to use preview in Nautilus 

**Expected behavior:**

files preview 

**Other Notes:**

version 3.34.0-2 has a bug and was fixed in 3.38.0

**Comment by leviport** [comment]
Thanks for the report! We are tracking this at https://github.com/pop-os/pop/issues/1332 and it appears to be an upstream issue.

**Comment by nch3d** [comment]
the problem with video pressing again space bar to close, does not close it reopens creating a bugle *loop. Please this tools is very important for best user experience. Po OS 21.04 Ryzen 9/RTX 2080 Ti/64RAM
