### ISSUE TITLE
Changing GDM Wallpaper 

### ISSUE THREAD

**Issue by linusrg1** [pop-os/pop#1347]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Issue with GDM

**Issue/Bug Description:**
I wish there was a userfriendly way to change the wallpaper of GDM as I cannot seem to figure out how to change it. It would be nice if you would allow for something like this to be done just like how it can be done in different distros with different DMs.

**Steps to reproduce (if you know):**
Try incredibly hard to try and figure out how to change it and then give up miserably.

**Expected behavior:**
To have the ability to change the wallpaper in a userfriendly method

**Other Notes:**
I hope you have a way I can resolve this issue

**Comment by VentGrey** [comment]
You can try with this script: https://github.com/thiggy01/ubuntu-20.04-change-gdm-background
However, please bear in mind that this might break your Pop! OS gdm config so please make a backup of your config files. 

Also I think the right place for these questions might be: https://pop-planet.info/forums/ :smile:

**Comment by leviport** [comment]
The ability to change the GDM background was removed in Gnome 3.36 in favor of using a blurred version of the desktop background instead. We're probably not going to deviate from upstream on this.

> Also I think the right place for these questions might be: https://pop-planet.info/forums/

Yep, pop-planet is a good place for questions, or you can visit our live chat at https://chat.pop-os.org
