### ISSUE TITLE
Random kernel panics after updating to 20.10

### ISSUE THREAD

**Issue by 0x1eaf** [pop-os/pop#1349]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
> apt policy cryptsetup
cryptsetup:
  Installed: 2:2.3.3-1ubuntu6
  Candidate: 2:2.3.3-1ubuntu6
  Version table:
 *** 2:2.3.3-1ubuntu6 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
> apt policy pop-shell
pop-shell:
  Installed: 0.1.0~1603503416~20.10~05e531e
  Candidate: 1.0.0~1603994289~20.10~ecc9b38
  Version table:
     1.0.0~1603994289~20.10~ecc9b38 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
 *** 0.1.0~1603503416~20.10~05e531e 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

After updating to Pop!_OS 20.10 the system has started to hang during boot on- or right after "cryptsetup: cryptdata: set up successfully" message. Sometimes it hangs while still showing that message, sometimes it starts to render the login screen. When it starts to render the login screen, the mouse cursor is no longer able to move. The system hangs during start-up more often then not.

Hang right after cryptsetup (video): https://www.icloud.com/iclouddrive/00JWZTCq9alGiVJvmIlIXkDDA#IMG%5F4097
Hang at cryptsetup (video): https://www.icloud.com/iclouddrive/05KGifyI8PIbEyFr0zPHVtoAQ#IMG%5F4098
Hand at/before login screen (video): https://www.icloud.com/iclouddrive/0f6XCeOH4ahLA_lLNev5vvIfA#IMG%5F4100

**Steps to reproduce (if you know):**

Update Pop!_OS from 20.04 to 20.10 on a system with disk encryption. Try to boot into the system. Maybe it has something to do with the peripherals (seen issues submitted about Thunderbolt docks). I don't have a dock, but I do have a USB switch (KM switch) and a USB hub chained together. If you need more info from the output of some terminal command, please let me know.

**Expected behavior:**

The system boots without hanging.

**Other Notes:**

There is a `pop-shell` update available in Software Center, and I will install it and give it a try. It's just that I'm writing this after 3 consecutive unsuccessful attempts at booting the computer, so I'd rather post this before risking to reboot again...

**Comment by 0x1eaf** [comment]
Installing updates didn't help. And I also got some hands after pressing enter on the login screen:
1. https://www.icloud.com/iclouddrive/0UlBYJe-mnroJwN5Kes5tA6jA#IMG%5F4104
2. https://www.icloud.com/iclouddrive/05MV6CZRVQoAWjgrU7xeBO5_A#IMG%5F4105
3. https://www.icloud.com/iclouddrive/0953G_GOjSwQ7-0VSFH27fPAw#IMG%5F4106

The last one is especially curious as it's on a black screen during mode-setting right after login. Which makes me wonder if it's a mode-setting related bug, as that seems to be happening both at: 
* the end of cryptsetup / start of login screen
* end of login screen

As it is a hi-dpi monitor: first mode change from low-res cryptsetup to full-res 1x login screen, and the second mode change from 1x full-res to 2x full-res after login.

**Comment by 0x1eaf** [comment]
Or maybe there is no mode-setting after cryptsetup, and it just looks low-res because of how it's rendered... 🤷‍♀️️

Anyway, now I've also got a hang on desktop, after the login screen, with mouse cursor still working:  https://www.icloud.com/iclouddrive/0leJ4Jjr_78qaowcF3Hs0THbA#IMG%5F4109

**Comment by 0x1eaf** [comment]
More information on these hangs:
* when they happen and the mouse cursor does not work - Ctrl+Alt+F# doesn't work too
* when the cursor works - I can switch to tty and I see errors from the kernel (see photos)
* the hangs also started happening after successfully logging in: sporadically while using any browser, or while downloading a game via Battle.Net app (tried with 3 different versions of Wine/Proton - same problem)

```
> uname -r
5.8.0-7630-generic
```

![IMG_4120](https://user-images.githubusercontent.com/8768743/99726563-83de6b80-2aae-11eb-97c1-cc42d8a29c5a.JPEG)
![IMG_4119](https://user-images.githubusercontent.com/8768743/99726566-850f9880-2aae-11eb-99a4-507d8c1efc72.JPEG)

**Comment by koopacommando** [comment]
Hi! Did you have any further development on this? 
I am struggling with something similar and right now I just gave up on updates for the time being, after having to reinstall several times last week.

**Comment by 0x1eaf** [comment]
No, just got many more kernel panics: while booting the system, while browsing web and while playing games. The system is largely unusable now. And given the lack of any response from the devs for such a long time, I’m contemplating either manually switching to a different kernel via “mainline” app, or switching to a different distro altogether…

![71E59C5D-0EFC-4EFF-835E-D172F2C6B2C8](https://user-images.githubusercontent.com/8768743/100267073-c094e180-2f4a-11eb-9f28-550cea6aec82.jpeg)
![976F0BB7-C120-407F-B2DE-A692C9C74FED](https://user-images.githubusercontent.com/8768743/100267091-c5f22c00-2f4a-11eb-9d62-52e59671bb5a.jpeg)
![A85502BD-1F92-4C7B-B66E-7273E1E136B3](https://user-images.githubusercontent.com/8768743/100267095-c68ac280-2f4a-11eb-83f5-c9e2147a4b7a.jpeg)

**Comment by 0x1eaf** [comment]
Closing this as I can no longer be the point of contact for this issue. If it's still relevant for someone — please feel free to re-open.
