### ISSUE TITLE
Pre-release .ISO

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/pop#135]
Publish to twitter, mattermost chat, blog, reddit, and provide a semi-hidden link to download/test.

**Comment by sarahpandabeara** [comment]
Once this is ready, we'll want to share and get feedback from customers before we launch 18.04 in April. Jeremy's estimate is that we can have it ready in the next two weeks so we'd have all of March to test this pre-released .iso with the installer.

**Comment by cassidyjames** [comment]
Considering this is long done… I'm gonna close this.
