### ISSUE TITLE
Sometimes, Wifi stops working after suspend and wake

### ISSUE THREAD

**Issue by ArjunSingh99** [pop-os/pop#1351]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

Wireless adapter: Realtek RTL8723BE PCIe Wireless Network Adapter
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
(Wireless)

**Issue/Bug Description:**
Sometimes, on suspend and wake, wifi stops working altogether. It isn't that wifi networks aren't being detected. The wifi option itself disappears from both the settings menu and the top panel menu. This hadn't been an issue on 20.04.
Restarting using the Restart option does not fix this issue.
Power off and power on fixes this issue temporarily, till it happens again.

**Steps to reproduce (if you know):**
Suspend the device and wake.
Repeat this process till wireless options disappear completely.

**Expected behavior:**
Suspension of device should not cause wireless options to disappear.

**Other Notes:**
This was never an issue on 20.04.
Restart using the 'Restart' option doesn't fix it, only power off and power on helps.

**Comment by mattemoore** [comment]
Same issue here.  @ArjunSingh99  how did you fix this?

**Comment by Made-of-Clay** [comment]
Still curious if you ever fixed this @ArjunSingh99

**Comment by rajdal** [comment]
Try this: 

- Delete the old service if you created it:

sudo systemctl disable wifi-resume.service
sudo rm /etc/systemd/system/wifi-resume.service

- Create a file: 

sudo nano /lib/systemd/system-sleep/wifi-fix

- Add this content: 

#!/bin/sh
case $1/$2 in
  pre/*)
    modprobe -r iwlmld iwlmvm iwlwifi
    ;;
  post/*)
    modprobe iwlmld iwlmvm iwlwifi
    ;;
esac

- Make it executable:

sudo chmod +x /lib/systemd/system-sleep/wifi-fix

- Test it: 

systemctl suspend

**Comment by bloodred17** [comment]
There is another solution in the cosmic thread that works:
[https://github.com/pop-os/cosmic-epoch/issues/3372#issuecomment-4257701141](https://github.com/pop-os/cosmic-epoch/issues/3372#issuecomment-4257701141)
