### ISSUE TITLE
No screen sharing

### ISSUE THREAD

**Issue by rav242** [pop-os/pop#1352]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 20.10 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Gnome Settings

**Issue/Bug Description:**
There is no Screen sharing menu in Settings->Sharing. But it was here in Pop!_OS 20.04

**Steps to reproduce (if you know):**
Go to Gnome Settings->Sharing. There is no Screen sharing.

**Expected behavior:**
There should be "Screen sharing" menu.

**Other Notes:**

**Comment by ids1024** [comment]
Should be fixed in https://github.com/pop-os/mutter/pull/13 (once that's merged).

**Comment by ToranSharma** [comment]
I had to run `sudo apt install pop-session` to get the option to appear in 20.10, as that package was being kept back for some reason.

**Comment by jacobgkau** [comment]
https://github.com/pop-os/mutter/pull/13 has been released and this is working by default now. For the `pop-session` issue, that has been addressed in https://github.com/pop-os/desktop-icons-ng/pull/2 and will no longer be an issue once that's been released from proposed.
