### ISSUE TITLE
NVIDIA driver not building w kernel 5.8.0-7625-generic

### ISSUE THREAD

**Issue by ronaaron** [pop-os/pop#1355]
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
 
Install fails, dpgk --configure -a reports
````
------------------------------
Deleting module version: 455.28
completely from the DKMS tree.
------------------------------
Done.
Loading new nvidia-455.28 DKMS files...
Building for 5.8.0-7625-generic
Building for architecture x86_64
Building initial module for 5.8.0-7625-generic
ERROR (dkms apport): kernel package linux-headers-5.8.0-7625-generic is not supported
Error! Bad return status for module build on kernel: 5.8.0-7625-generic (x86_64)
Consult /var/lib/dkms/nvidia/455.28/build/make.log for more information.
dpkg: error processing package nvidia-dkms-455 (--configure):
 installed nvidia-dkms-455 package post-installation script subprocess returned error exit status 10
dpkg: dependency problems prevent configuration of nvidia-driver-455:
 nvidia-driver-455 depends on nvidia-dkms-455 (>= 455.28); however:
  Package nvidia-dkms-455 is not configured yet.

dpkg: error processing package nvidia-driver-455 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of system76-driver-nvidia:
 system76-driver-nvidia depends on nvidia-driver-455; however:
  Package nvidia-driver-455 is not configured yet.

dpkg: error processing package system76-driver-nvidia (--configure):
 dependency problems - leaving unconfigured
Processing triggers for initramfs-tools (0.137ubuntu12) ...
update-initramfs: Generating /boot/initrd.img-5.8.0-7625-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 20.10
    Root partition:....../dev/dm-1
    Root FS UUID:........6d7894c1-e702-4d8c-8e81-fc9691eed214
    ESP Path:............/boot/efi
    ESP Partition:......./dev/nvme0n1p1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash mem_sleep_default=deep
    Kernel Image Path:.../boot/vmlinuz-5.8.0-7625-generic
    Initrd Image Path:.../boot/initrd.img-5.8.0-7625-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     Making entry file for Pop!_OS
Errors were encountered while processing:
 nvidia-dkms-455
 nvidia-driver-455
 system76-driver-nvidia
````

**Comment by kendocode** [comment]
Same problem here, I believe related to [https://github.com/pop-os/pop/issues/1338](url) -- I was able to get the 455.28 driver and module to build on 5.4 but it still fails on 5.8 with the "kernel package linux-headers-5.8.0-7625-generic is not supported" message. Has anyone been able to successfully build against 5.8? I have to believe that this is working on some systems (e.g. System76 hardware).

**Comment by curiousercreative** [comment]
@kendocode I'm on 20.04 and kernel 5.8 and had success with the following (adapted from [this reddit thread](https://www.reddit.com/r/pop_os/comments/byzinz/how_to_reinstall_nvidia_drivers_after_a_failed/)):
```bash
sudo apt-get remove *nvidia*
sudo apt install pop-desktop system76-driver-nvidia
```
If you see the kernel module build and install succeed, then a reboot should have you rocking.

**Comment by ronaaron** [comment]
I gave up and switched to Linux Mint 20, which works a treat

**Comment by kendocode** [comment]
Thanks @curiousercreative -- I'm in a bit of a crunch at the moment and haven't had time to wrestle with the issue since I got back to work on 5.4.

I did remove (actually purged, which might have been unwise) all nvidia, and then reinstalled system76-driver-nvidia but it wouldn't build under 5.8. I didn't try also reinstalling pop-desktop. I'll try the full procedure that worked for you when I get some tinker time. 

I posted the build logs in #1338 -- tldr:
```
ERROR: Kernel configuration is invalid.
include/generated/autoconf.h or include/config/auto.conf are missing.
Run 'make oldconfig && make prepare' on kernel src to fix it.
```
I tried running the make command from ``` /usr/src/linux-headers-5.8.0-7625-generic/kernel gives:```, which failed, and I couldn't figure out where it wanted to be run from.  I wish I better understood why it is failing, but I had to sacrifice mental satisfaction (temporarily) to get some work done.

So, I'm limping along on 5.4 for the moment, hoping this is a temporary issue and maybe it'll just work when I come back in a couple of days and try again.

**Comment by kendocode** [comment]
Can confirm that everything is building correctly now on Pop!OS 20.04 5.8 kernel and Nvidia 455.38 with nothing done on my end aside from waiting for the next updates. Thanks System76!

Working package versions on Lenovo ThiinkPad P71:
$ apt list --installed | grep system76

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

gnome-shell-extension-system76-power/focal,focal,now 2.0.0~1601675659~20.04~81924ad all [installed,automatic]
linux-firmware/focal,focal,now 1.190.1+system76~1605123765~20.04~3894207 all [installed,automatic]
linux-headers-5.0.0-21-generic/now 5.0.0-21.22+system76 amd64 [installed,local]
linux-headers-5.0.0-21/now 5.0.0-21.22+system76 all [installed,local]
linux-image-5.0.0-21-generic/now 5.0.0-21.22+system76 amd64 [installed,local]
linux-modules-5.0.0-21-generic/now 5.0.0-21.22+system76 amd64 [installed,local]
linux-system76/focal,now 5.8.0.7630.32~1605108853~20.04~8bcf10e amd64 [installed,automatic]
system76-acpi-dkms/focal,now 1.0.2~1600812457~20.04~0bc966c amd64 [installed,automatic]
system76-dkms/focal,now 1.0.9~1597073326~20.04~5b01933 amd64 [installed]
system76-driver-nvidia/focal,focal,now 20.04.15~1604686585~20.04~0415c0c all [installed]
system76-driver/focal,focal,now 20.04.15~1604686585~20.04~0415c0c all [installed,automatic]
system76-firmware-daemon/focal,now 1.0.19~1601670775~20.04~afb6944 amd64 [installed,automatic]
system76-io-dkms/focal,now 1.0.1~1559663713~20.04~ea5f61a amd64 [installed,automatic]
system76-oled/focal,now 0.1.4~1588092956~20.04~805ebb1 amd64 [installed,automatic]
system76-power/focal,now 1.1.11~1603307462~20.04~81e6cbf amd64 [installed,automatic]
system76-wallpapers/focal,focal,now 18.04.2~1525874807~20.04~d6171e2 all [installed,automatic]

libnvidia-cfg1-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-common-455/focal,focal,now 455.38-1pop0~1605144088~20.04~3cf77da all [installed,automatic]
libnvidia-compute-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-compute-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
libnvidia-decode-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-decode-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
libnvidia-encode-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-encode-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
libnvidia-extra-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-fbc1-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-fbc1-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
libnvidia-gl-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-gl-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
libnvidia-ifr1-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
libnvidia-ifr1-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da i386 [installed,automatic]
nvidia-compute-utils-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
nvidia-dkms-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
nvidia-driver-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
nvidia-kernel-common-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
nvidia-kernel-source-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
nvidia-settings/focal-updates,now 440.82-0ubuntu0.20.04.1 amd64 [installed,automatic]
nvidia-utils-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]
system76-driver-nvidia/focal,focal,now 20.04.15~1604686585~20.04~0415c0c all [installed]
xserver-xorg-video-nvidia-455/focal,now 455.38-1pop0~1605144088~20.04~3cf77da amd64 [installed,automatic]

@ronaaron you might give Pop a whirl again and close the issue if it works. ;) Or, if you prefer Mint, you might still close the issue as it appears to have been resolved.

**Comment by sawyermade** [comment]
Happened again, this OS is seriously turning out to be a nightmare.

**Comment by zfields** [comment]
FWIW, still having this issue on a System76 machine, running Pop_OS!

**Comment by zfields** [comment]
Here is how I "fixed" my problem...

```
sudo apt-get remove *nvidia*
sudo apt install libnvidia-compute-460 libnvidia-fbc1-460 system76-driver-nvidia
```

**Comment by sawyermade** [comment]
Thanks, I ended up doing this to get it to work and needed cuda too:

sudo apt purge "*nvidia*"
sudo apt purge "*nvidia*:i386"
sudo apt install pop-desktop system76-driver-nvidia system76-cuda-latest

We shouldn't have to do this from system76 distro packages, this is getting ridiculous. I am pretty sure Pop Shop update is what jacked up my system in the first place.

**Comment by leviport** [comment]
That issue is being tracked here: https://github.com/pop-os/nvidia-graphics-drivers/issues/94 

There is a bug in Launchpad that was causing some i386 packages to not be built.
