### ISSUE TITLE
Top bar shows a black border when using a transparent theme

### ISSUE THREAD

**Issue by daramez** [pop-os/pop#136]
**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)
 * Related Application and/or Package Version - Gnome Shell top bar
```

**Issue/Bug Description**

When I change the shell theme to Adapta, a black border below the top bar is shown.

**Steps to reproduce**

1. Install Adapta
2. Set the shell theme to Adapta using Gnome Tweaks

**Expected behavior**

Top bar should be transparent without borders.

**Comment by brs17** [comment]
This should no longer be an issue, especially since current themeing is based heavily off of upstream Adwaita/Yaru.
