### ISSUE TITLE
no notification sound

### ISSUE THREAD

**Issue by FDiskas** [pop-os/pop#1360]
Manufacturer:      LENOVO
Product Name:      20UD001CMH
Product Version:   ThinkPad T14 Gen 1
Firmware Version:  R1BET56W(1.25 )
Board Vendor:      LENOVO
Board Name:        20UD001CMH

**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**
When notification popup shows - no sound is played - other sounds are ok

**Steps to reproduce (if you know):**
unknown, it was from fresh install

**Expected behavior:**
on each popup sound should be played

**Other Notes:**

System info: http://alsa-project.org/db/?f=28c0012cc52ad181a158adc11f3e5a3d8dd32245

**Comment by cesarrew** [comment]
Steps to reproduce (if you know):
Tip: use de command "notify-send <MESSAGE>"

**Comment by leviport** [comment]
As mentioned in https://github.com/pop-os/gtk-theme/issues/601#issuecomment-1414173580, GNOME doesn't play a notification sound for notifications. It's currently up to the application that sends the notification.
