### ISSUE TITLE
Chromium crashes when any tab is closed

### ISSUE THREAD

**Issue by rodericktech** [pop-os/pop#1365]
**Distribution:**

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

(I am running a Thelio with Nvidia graphics, latest drivers installed on Pop! 20.10)
 
**Related Application and/or Package Version:**

```
chromium:
  Installed: 84.0.4147.105-1pop1
  Candidate: 84.0.4147.105-1pop1
  Version table:
 *** 84.0.4147.105-1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Chromium crashes any time a tab is closed, even by the program itself when trying to sign in / doing Settings edits.

Console output when opening Chromium (with only an empty tab), opening a new tab, and attempting the close the new tab is as follows:

```
[28399:28399:1104/105441.201927:ERROR:vaapi_wrapper.cc(511)] vaInitialize failed: unknown libva error
malloc_consolidate(): unaligned fastbin chunk detected
Received signal 11 SEGV_MAPERR 000000000000
Received signal 6
#0 0x562df39b3209 #0 0x562df39b3209 (/usr/lib/chromium/chromium+0x53c3208)
#1 0x(/usr/lib/chromium/chromium+0x53c3208)562df3915c73
 #1 0x562df3915c73 (/usr/lib/chromium/chromium+0x5325c72)
#2(/usr/lib/chromium/chromium+0x5325c72) 
0x#562df39b2deb2  0x562df39b2deb (/usr/lib/chromium/chromium+0x53c2dea)
#3 0x(/usr/lib/chromium/chromium+0x53c2dea)7f6b60524bb0
 #3 0x7f6b60524bb0 (/usr/lib/x86_64-linux-gnu/libpthread-2.32.so+0x14baf)
#4 0x7f6b5b5168cb gsignal
#5 0x7f6b5b4fb864 (/usr/lib/x86_64-linux-gnu/libpthread-2.32.so+0x14baf)
  r8: 0000000000000016  r9: 0000000000000000abort r10: 
0000000000000000# r11: 60000000000000286 
0x r12: 7f6b5b55eaf600007ffd564b3601  r13: 0000562dfa5a8268 r14: 0000000000000000 r15: 0000562dfa5a8558
  di: 0000562dfa5a8268  si: 0000000000000000  bp: 00007ffd564b3480  bx: 0000000000000000
  dx: 0000562df991dcf0  ax: 0000562dfa559d70  cx: 0000562dfa5a8558  sp: 00007ffd564b3408
  ip: 0000000000000000(/usr/lib/x86_64-linux-gnu/libc-2.32.so+0x89af5) efl: 
0000000000010203# cgf: 7002b000000000033 0x7f6b5b56746c  erf: 0000000000000014
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

**Steps to reproduce (if you know):**

Install Chromium from either the Pop! Shop or the terminal (`apt install chromium`).  Open Chromium.

Open a new tab.  Attempt to close the tab.

**Expected behavior:**

Chromium will crash when the new tab is closed.  When attempting to reopen the program, if Chromium notices that it crashed and offers to restore the tabs from prior to the crash, if you click the 'Restore' button it will simply crash again.

**Other Notes:**

This began happening a day or two ago without warning or any config changes on my end and many in the subreddit have also posted about it.  I have removed the application and cleared all its caches on the system, reinstalled it bare / vanilla, and I get the same results.

**Comment by ArjunSingh99** [comment]
I have this issue too, and apparently a lot of other people too.

**Comment by FritosBag** [comment]
This seems to be only affecting chromium, regular chrome and firefox work just fine

**Comment by RogueRiot** [comment]
I have the same issue after updating the system yesterday other browsers seem to be not affected.

**Comment by M-erb** [comment]
Same here, Chromium Version 84.0.4147.105 on Pop!_OS 20.10 installed from the pop shop. Every time a tab is closed it crashes and I have to start over. The restore button that pops up in the top right when restarting Chromium also crashes it.

**Comment by didenko** [comment]
Same here Chromium Version 84.0.4147.105. Also crashes all windows if multiple windows open with the same or different profiles and one is closed - regardless if it is closed by a mouse click on the windows close button or a Ctrl-W key-press.

**Comment by didenko** [comment]
When checking if reinstalling it would have any effect, found that Chromium does not seem to be available in the repositories any more:
```
$ sudo apt-get install chromium
[sudo] password for user: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package chromium is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  chromium-bsu

E: Package 'chromium' has no installation candidate
$ 
```
![Screenshot from 2020-11-05 16-39-45](https://user-images.githubusercontent.com/99670/98312377-6ecdec80-1f86-11eb-9fb7-4ff13f95dac2.png)

there are plenty of transitional packages to chromium snap though

**Comment by rodericktech** [comment]
Just tried the chromium snap package instead (`chromium-browser` transitional), and so far it seems to be free of the tab-crash problem.  Not sure if this is supposed to be the intended way forward but I will test further and see if any other issues arise.

**Comment by Paulmicha** [comment]
This is fixed in last update for me (yesterday).

**Comment by wlangston** [comment]
I was having the same issue. As noted by **didenko** above, `chromium` seems to no longer be in the default repositories. I purged `chromium` and installed `chromium-browser` and everything is working again as **rodericktech** has suggested above. 

`sudo apt purge chromium`
`sudo apt install chromium-browser`

The version of chromium-browser is also updated to **Version 86.0.4240.183 (Official Build) snap (64-bit)**

**Comment by arvigeus** [comment]
Another workaround would be to [install chromium from Linux Mint repositories](https://www.zdnet.com/article/linux-mint-introduces-its-own-take-on-the-chromium-web-browser/). It has no `snap` dependency.

I would not risk adding the whole repo, but rather just use the deb package: [link](http://packages.linuxmint.com/search.php?release=any&section=any&keyword=chromium). The latest release is `86.0.4240.183~linuxmint1+ulyana`

**Comment by econdepe** [comment]
Yeah, installing a snap can break some extensions, like KeePassXC. I hope PopOS considers upgrading their version

**Comment by didenko** [comment]
Snap is a no-go for me. Today the 83.0.4103.116 (Developer Build), pity not the official same in the snaps, appeared in the repos,  Installed, do not have the issue.

**Comment by rodericktech** [comment]
I can confirm that the build which is now in the Pop repos no longer has the issue.
