### ISSUE TITLE
Amdgpu drivers gone. How to get them back?

### ISSUE THREAD

**Issue by WuerfelDev** [pop-os/pop#1369]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Amdgpu I guess

**Issue/Bug Description:**
Only the primary monitor is working
the system feels slow
desktop has no animations
gnome runs without acceleration (it reports that in journalctl)

**Steps to reproduce (if you know):**
1. install amdgpu from the amd webpage (because I need amdgpu-pro) 
2. Run into this problem #1135 
3. uninstall with the amdgpu-pro-uninstall command
4. I install updates via pop shop (but not sure if that's relevant)
5. reboot

**Expected behavior:**
fall back to preinstalled drivers which did work previously. Should not have any of the issues mentioned above.

**Other Notes:**
My system has an AMD Radeon RX 5500 XT graphics card
Current AMD drivers release is 20.40

graphic card is detected:
```
sudo lspci
28:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c5)
```

but the settings show this instead the graphics card:
![Screenshot from 2020-11-05 22-16-16](https://user-images.githubusercontent.com/12686819/98297440-afdcf580-1fb4-11eb-8348-af7ced0bccdc.png)

Is there a way to get pop's default drivers back? Or any idea how I can fix it for now?

**Comment by curiousercreative** [comment]
@WuerfelDev I'm by no means an expert and have only been running with this solution/workaround for a few minutes, but here's how I got them back after getting into the same mess with `amdgpu-pro`:

```bash
sudo rm /etc/modprobe.d/blacklist-amdgpu.conf
sudo update-initramfs -u -k all
```
After that, reboot.

If you find you need to restore that file (revert my workaround):
```bash
echo 'blacklist amdgpu' | sudo tee /etc/modprobe.d/blacklist-amdgpu.conf
sudo update-initramfs -u -k all
```
and reboot

**Comment by Greifent** [comment]
It work also for me, thanks

**Comment by Askaiant** [comment]
@curiousercreative Thank you for your tip, this helped me very much. 

The issue I stumbled across is:  
1. Install ROCm (on an older kernel i think it was 5.8)
2. Upgrade the kernel
3. Uninstall ROCm (as instructed [here](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#uninstalling-rocm-packages-from-ubuntu))
4. Install rocm-dev

Issue:
Only the primary monitor is working
the system feels slow
desktop has no animations

To anyone that might get this bug, possibly linked with [#1467](https://github.com/pop-os/pop/issues/1467)

**Comment by KerickHowlett** [comment]
> @WuerfelDev I'm by no means an expert and have only been running with this solution/workaround for a few minutes, but here's how I got them back after getting into the same mess with `amdgpu-pro`:
> 
> ```bash
> sudo rm /etc/modprobe.d/blacklist-amdgpu.conf
> sudo update-initramfs -u -k all
> ```
> After that, reboot.
> 
> If you find you need to restore that file (revert my workaround):
> ```bash
> echo 'blacklist amdgpu' | sudo tee /etc/modprobe.d/blacklist-amdgpu.conf
> sudo update-initramfs -u -k all
> ```
> and reboot

I just wanna say thank you!

You really saved my bacon tonight. When I encountered this after tinkering around with the driver settings, so I could get DaVinci Resolve to work (by replacing the Mesa Vulcan drivers with AMD Pro), I thought I was gonna have to completely reset my system. 😅

**Comment by Michael-Sjogren** [comment]
> @WuerfelDev I'm by no means an expert and have only been running with this solution/workaround for a few minutes, but here's how I got them back after getting into the same mess with `amdgpu-pro`:
> 
> ```shell
> sudo rm /etc/modprobe.d/blacklist-amdgpu.conf
> sudo update-initramfs -u -k all
> ```
> 
> After that, reboot.
> 
> If you find you need to restore that file (revert my workaround):
> 
> ```shell
> echo 'blacklist amdgpu' | sudo tee /etc/modprobe.d/blacklist-amdgpu.conf
> sudo update-initramfs -u -k all
> ```
> 
> and reboot

Thanks, worked perfectly!
