### ISSUE TITLE
clock freezing when out of screen. 

### ISSUE THREAD

**Issue by r-murmu** [pop-os/pop#1375]
Distribution : pop! _os 20.10 ×86_64
 
Related Application: clock on top bar

Issue/Bug Description: When top bar clock is out of sight (i.e doing something in full screen mode) 
the chock freezes the time which can be fixed by hovering pointer on the clock again. 

Steps to reproduce: Playing video on full screen mode and when you exit from full screen mode after few minutes, the clock time is frozen. 

Expected behavior: The clock should not freeze when out of sight.

**Comment by r-murmu** [comment]
![IMG_20201107_223727](https://user-images.githubusercontent.com/57767031/98447318-db451900-2149-11eb-997e-0cb94f92a76b.jpg)

see timestamp on the pic and time on top bar. my clocks are perfectly in sink.

**Comment by ArjunSingh99** [comment]
I'm facing this issue too

**Comment by itsmordecai** [comment]
sorry for the duplication and yes the problem still exists at the moment

**Comment by ArjunSingh99** [comment]
This no longer seems to be a problem for me. Can others confirm?

**Comment by itsmordecai** [comment]
> This no longer seems to be a problem for me. Can others confirm?

@ArjunSingh99 updated mine today and i can confirm the problem no longer exists

**Comment by jacobgkau** [comment]
Good to hear, it was probably GNOME Shell and/or Mutter 3.38.2: https://github.com/pop-os/gnome-shell/pull/51, https://github.com/pop-os/mutter/pull/16.
