### ISSUE TITLE
Pop_os 20.04: Clicking "Customize shortcuts" in Settings > Keyboard broken. Closes Settings window

### ISSUE THREAD

**Issue by adipmeesse** [pop-os/pop#1382]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Shortcut customization

**Issue/Bug Description:**
When you click  "Customize shortcuts" in Settings, the Settings Window disappears and nothing happens

Here the log from journalctl:

![image](https://user-images.githubusercontent.com/49441277/98705502-12037500-237e-11eb-889e-baa4739b1e88.png)
![image](https://user-images.githubusercontent.com/49441277/98705893-7c1c1a00-237e-11eb-87d6-3bb331c3cd13.png)

**Steps to reproduce (if you know):**
Open settings > go to Keyboard > Customize shortcuts

**Expected behavior:**
A Window should open to customize the shortcuts

**Other Notes:**

**Comment by ids1024** [comment]
Hm. What is the output of `apt policy pop-shell`?

**Comment by adipmeesse** [comment]
pop-shell:
  Installed: 0.1.0~1598032836~20.04~8416328
  Candidate: 1.0.0~1603994289~20.04~ecc9b38
  Version table:
     1.0.0~1603994289~20.04~ecc9b38 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main i386 Packages
 *** 0.1.0~1598032836~20.04~8416328 100
        100 /var/lib/dpkg/status

**Comment by ids1024** [comment]
```
  Installed: 0.1.0~1598032836~20.04~8416328
  Candidate: 1.0.0~1603994289~20.04~ecc9b38
```

Looks like commit `8416328` was before `pop-workspace-down` was added, so updating that package should fix it.

**Comment by adipmeesse** [comment]
Can i update this without any os related update?

**Comment by adipmeesse** [comment]
ok " sudo apt-get upgrade pop-shell-shortcuts "  did the job.  Thanks!
