### ISSUE TITLE
TouchPad is not working.

### ISSUE THREAD

**Issue by suyog-pipliwaal** [pop-os/pop#1390]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** 

**Issue/Bug Description:**
I have Lenovo Ideapad 330 laptop and have install pop os 20.04 recently. After installation, my touchpad is not working and also not recognize by os. I have an external mouse attached to the system.
System Info:-
Lenovo IdeaPad 330 core-i5 with AMD Radeon GPU.
The output of uname -ar:-
Linux suyog 5.8.0-7630-generic #32~1605108853~20.04~8bcf10e-Ubuntu SMP Wed Nov 11 22:42:16 UTC  x86_64 x86_64 x86_64 GNU/Linux

The output of xinput list:- 
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ E-Signal USB Gaming Mouse Consumer Control	id=13	[slave  pointer  (2)]
⎜   ↳ E-Signal USB Gaming Mouse               	id=15	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ Power Button                            	id=7	[slave  keyboard (3)]
    ↳ EasyCamera: EasyCamera                  	id=8	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=9	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=10	[slave  keyboard (3)]
    ↳ E-Signal USB Gaming Mouse System Control	id=11	[slave  keyboard (3)]
    ↳ E-Signal USB Gaming Mouse Keyboard      	id=12	[slave  keyboard (3)]
    ↳ E-Signal USB Gaming Mouse Consumer Control	id=14	[slave  keyboard (3)]

**Steps to reproduce (if you know):**

**Expected behavior:**
TouchPad should work as expected.

**Other Notes:**

**Comment by ids1024** [comment]
I assume you don't have the touchpad disabled with a key or switch? On some laptops that can be easy to accidentally do.

In my experience things like touchpads generally work out of the box on Linux. But if there's an issue it's presumably related to the specific laptop model.

**Comment by suyog-pipliwaal** [comment]
I am using my laptop without a touchpad for the last 4 days and it was working fine with ubuntu 20.04 but when I install pop-os 20.04  it stops working. Any suggestion for fixing this problem. My laptop specifications are below:-
baseboard-manufacturer : LENOVO
system-version : Lenovo ideapad 330-15IKB
system-product-name : 81DE
chassis-type : Notebook
system-serial-number : PF118B0Q
bios-release-date : 03/11/2018
bios-version : 8TCN07WW

**Comment by DrRSatzteil** [comment]
Please see my comments here: https://github.com/pop-os/pop/issues/1071

All solutions seem to be far from being perfect but
The touchpad does work pretty stable from 5.9.x kernels. However only when the notebook is connected to the power during boot...

**Comment by domalak** [comment]
Also check issue #1341

**Comment by suyog-pipliwaal** [comment]
Thanks to @domalak, Touchpad is now.

**Comment by neoabs** [comment]
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

Touchpad not working with/or without mouse. When I go to options after reboot and disable/enable it it works for a while then stops after I close settings.

**Comment by leviport** [comment]
@neoabs please open a support ticket: https://support.system76.com/
