### ISSUE TITLE
 chromium: outdated version, more than 100 open security issues

### ISSUE THREAD

**Issue by obfusk** [pop-os/pop#1396]
Pop!_OS seems to have the [same issue as Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973858) (where I assume the `chromium` package originates).

(This only applies to the `chromium` package, not the the snap-based `chromium-browser` from the Ubuntu repositories).

**Comment by mmstick** [comment]
The package is copied from Debian, so when they get an updated package out, Pop will have it soon after.

**Comment by obfusk** [comment]
Debian now has an update package, but it seems Pop is still behind?

**Comment by mmstick** [comment]
I'd recommend using the Flatpak version of Chromium since Debian is often behind.

**Comment by waja** [comment]
> We are working to transition to the flathub package by default

Really? Do you know that people where migrating over to Pop only cause there is no need for using Snap or Flathub?
Anyway ... that's the issue porting back Chromium from Debian stable (or unstable)? That's something that can be automated in most aspects.

**Comment by jackpot51** [comment]
The debian version is consistently out of date

**Comment by waja** [comment]
> The debian version is consistently out of date

https://packages.qa.debian.org/c/chromium.html looks (for unstable) not that bad and they even a version in stable-security they consider as "secure".

**Comment by mmstick** [comment]
> > The debian version is consistently out of date
> 
> https://packages.qa.debian.org/c/chromium.html looks (for unstable) not that bad and they even a version in stable-security they consider as "secure".

It doesn't build on Ubuntu, and it will only be a matter of time before it is out of date again, and again, and again. Flatpak means we only need one maintainer across all Linux distributions. Therefore we can spend more time on Pop and less time maintaining Chromium.

**Comment by raxod502** [comment]
I'm happy in principle to make this migration as a user, but right now it's not an option for me since [Browserpass](https://github.com/browserpass/browserpass-extension) does not seem to be supported (it uses a native messaging host, and requires access to `~/.password-store`). I ran into the same problem with Snap back when I used Ubuntu, which forced me to install from an unofficial PPA. Is there any plan to resolve this issue?

**Comment by ids1024** [comment]
@raxod502 If you just need to give it access to the directory, you can configure flatpak to grant access to `~/.password-store`, either through the command line or through Flatseal.

**Comment by raxod502** [comment]
I've enabled the "All system files" permission through Flatseal. I also saw in [the documentation](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) that `/usr` is denylisted, so I explicitly added `/usr` to the list of additional files to grant access to.

However, these changes don't seem to change anything after restarting Chromium: Browserpass still doesn't show up in my extensions list, despite being installed at `/usr/share/chromium/extensions/browserpass/manifest.json`. Are additional steps required to make it work?

![image](https://user-images.githubusercontent.com/6559064/108450401-00055e00-721a-11eb-874a-6187e2615021.png)

**Comment by obfusk** [comment]
> Browserpass still doesn't show up in my extensions list, despite being installed at `/usr/share/chromium/extensions/browserpass/manifest.json`. Are additional steps required to make it work?

I don't use flatpak (and it's been a while since I wrote a chromium extension), but I would assume it ignores `/usr` even when given access. I expect installing the extension manually or from the chrome web store works. Or creating a symlink from the appropriate subdirectory of your profile to the directory in `/usr`.

But hopefully this works:
* go to chrome://extensions
* enable developer mode
* load unpacked -> choose `/usr/share/chromium/extensions/browserpass`

**Comment by obfusk** [comment]
> It doesn't build on Ubuntu, and it will only be a matter of time before it is out of date again, and again, and again. Flatpak means we only need one maintainer across all Linux distributions, and we won't have to maintain a build of it for Pop. Therefore we can spend more time on Pop and less time maintaining Chromium.

I appreciate that maintaining chromium takes time. But flatpak also means distributions can no longer make different choices/tradeoffs in packaging: e.g. flatpak means you automatically get widevine DRM, which Debian removes (which makes the flatpak version not an option for me -- but of course benefits those who do want it).

**Comment by raxod502** [comment]
> hopefully this works

Unfortunately, no dice. Although I can navigate to `/usr/share` in the "load unpacked" file chooser dialog, there is no `chromium` directory in the list, even though it definitely does exist with standard permissions according to `ls`.

**Comment by obfusk** [comment]
> > hopefully this works
> 
> Unfortunately, no dice. Although I can navigate to `/usr/share` in the "load unpacked" file chooser dialog, there is no `chromium` directory in the list, even though it definitely does exist with standard permissions according to `ls`.

According to the docs you linked: "These directories are mounted under /var/run/host: /etc, /usr".
So does "/var/run/host/usr/share/chromium/extensions/browserpass" work?

**Comment by obfusk** [comment]
> It doesn't build on Ubuntu

That's unfortunate. But hopefully not to hard to fix.

> and it will only be a matter of time before it is out of date again, and again, and again.

There was some discussion in Debian regarding the small number of maintainers for chromium and the situation has already improved; Debian just got an updated version today.

**Comment by obfusk** [comment]
> Debian just got an updated version today.

It looks like Debian unstable got the latest update at the same time as snap & flathub and Debian stable followed two days later.

**Comment by raxod502** [comment]
> So does `/var/run/host/usr/share/chromium/extensions/browserpass` work?

Hey, it does! Well, in the sense that I can add the extension. However, the native messaging host still can't be found. I presume this is because the manifest file `/etc/chromium/native-messaging-hosts/com.github.browserpass.native.json` is not at the correct location inside the sandbox, or because the executable it references can't be found. Contents of this manifest are:

```json
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Chromium extension",
    "path": "/usr/lib/browserpass/browserpass-native",
    "type": "stdio",
    "allowed_origins": [
        "chrome-extension://naepdomgkenhinolocfifgehidddafch/",
    "chrome-extension://cbfnbkdnigbahbkcikfppmaonggdbcpa/",
        "chrome-extension://pjmbgaakjkbhpopmakjoedenlfdmcdgm/",
        "chrome-extension://klfoddkbhleoaabpmiigbmpbjfljimgb/"
    ]
}
```

Just on the off chance the executable path was the problem, I updated the path in this file to `/var/run/host/usr/lib/browserpass/browserpass-native`. Same result though---and furthermore, when I use a file dialog from inside Chromium, although the directory `/var/run/host/usr/lib/browserpass` exists, it apparently has no contents. Despite that `/usr/lib/browserpass/browserpass-native` clearly does exist outside on the system.

Same thing for `/etc/chromium/native-messaging-hosts`, it definitely has contents and yet `/var/run/host/etc/chromium/native-messaging-hosts` is empty within the container.

That said... making this work seems like a gigantic hack. Is Flatpak for Chromium really production ready if extensions don't work out of the box?

**Comment by obfusk** [comment]
> That said... making this work seems like a gigantic hack.

Yeah :(

> Is Flatpak for Chromium really production ready if extensions don't work out of the box?

I expect it works fine for many people (since most extensions don't require native messaging). But it's clearly not a drop-in replacement for everyone.

**Comment by obfusk** [comment]
> It doesn't build on Ubuntu

I just built the chromium source package from Debian unstable on Pop!_OS 20.04 without any problems (or modifications).

**Comment by obfusk** [comment]
> > It doesn't build on Ubuntu
> 
> I just built the chromium source package from Debian unstable on Pop!_OS 20.04 without any problems (or modifications).

It builds just fine on groovy & focal: https://launchpad.net/~flx/+archive/ubuntu/chromium

**Comment by obfusk** [comment]
Debian unstable got an updated chromium package two days ago, the same day as flathub.
My PPA is building it for Ubuntu right now.
