### ISSUE TITLE
Cannot install wine32

### ISSUE THREAD

**Issue by PanderMusubi** [pop-os/pop#1398]
**Distribution (run `cat /etc/os-release`):**

    NAME="Pop!_OS"
    VERSION="20.10"
    ID=pop
    ID_LIKE="ubuntu debian"
    PRETTY_NAME="Pop!_OS 20.10"
    VERSION_ID="20.10"
    HOME_URL="https://pop.system76.com"
    SUPPORT_URL="https://support.system76.com"
    BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
    PRIVACY_POLICY_URL="https://system76.com/privacy"
    VERSION_CODENAME=groovy
    UBUNTU_CODENAME=groovy
    LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

    wine32:i386:
      Installed: (none)
      Candidate: 5.0-3ubuntu1
      Version table:
         5.0-3ubuntu1 500
            500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages

**Issue/Bug Description:**

    sudo apt-get install wine32
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     libdbus-1-3:i386 : Depends: libsystemd0:i386 but it is not going to be installed
     libpulse0:i386 : Depends: libsystemd0:i386 but it is not going to be installed
     libusb-1.0-0:i386 : Depends: libudev1:i386 (>= 183) but it is not going to be installed
     libwine:i386 : Depends: libudev1:i386 (>= 183) but it is not going to be installed
                    Recommends: libsane:i386 (>= 1.0.24)
                    Recommends: gstreamer1.0-plugins-good:i386 but it is not installable
    E: Unable to correct problems, you have held broken packages.

**Steps to reproduce (if you know):**

    sudo apt-get install wine wine32

**Expected behavior:**

Installations without these issues.

**Other Notes:**

Issue at higher level is after downloading and unzipping https://rekordbox.com/en/download/

    $ wine Install_rekordbox_x64_6_3_0.exe 
    it looks like wine32 is missing, you should install it.
    as root, please execute "apt-get install wine32"
    wine: created the configuration directory '/home/pander/.wine'
    0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
    0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
    0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
    0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
    0012:err:ole:get_local_server_stream Failed: 80004002
    0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
    0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
    0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
    0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
    0014:err:ole:get_local_server_stream Failed: 80004002
    Could not find Wine Gecko. HTML rendering will be disabled.
    it looks like wine32 is missing, you should install it.
    as root, please execute "apt-get install wine32"
    Could not find Wine Gecko. HTML rendering will be disabled.
    wine: configuration in L"/home/pander/.wine" has been updated.
    it looks like wine32 is missing, you should install it.
    as root, please execute "apt-get install wine32"
    0038:err:module:__wine_process_init L"Z:\\home\\pander\\Downloads\\Install_rekordbox_x64_6_3_0.exe" not supported on this system

**Comment by PanderMusubi** [comment]
Installing wine from their own deb repo on popos system also fails. Probably this has the same root cause. See https://wiki.winehq.org/Ubuntu and the result is

    $ sudo apt-get install winehq-stable
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     winehq-stable : Depends: wine-stable (= 5.0.3~groovy)
    E: Unable to correct problems, you have held broken packages.

and

    $ sudo  apt-get install wine-stable
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     libdbus-1-3:i386 : Depends: libsystemd0:i386 but it is not installable
     libpulse0:i386 : Depends: libsystemd0:i386 but it is not installable
     libusb-1.0-0:i386 : Depends: libudev1:i386 (>= 183) but it is not installable
     wine-stable-i386:i386 : Depends: libudev1:i386 (>= 183) but it is not installable
                             Recommends: libsane:i386 or
                                         libsane1:i386 but it is not installable
    E: Unable to correct problems, you have held broken packages.

**Comment by ids1024** [comment]
I'm not seeing this error. Perhaps try running `apt update` first, if you haven't.

**Comment by PanderMusubi** [comment]
Found the problem, this line in `/etc/apt/sources.list`

    deb [arch=amd64] http://ppa.launchpad.net/system76/pop/ubuntu groovy main

should be

    deb http://ppa.launchpad.net/system76/pop/ubuntu groovy main

A little too much tuning on my part.

**Comment by isantop** [comment]
> Found the problem, this line in `/etc/apt/sources.list`
> 
> ```
> deb [arch=amd64] http://ppa.launchpad.net/system76/pop/ubuntu groovy main
> ```
> 
> should be
> 
> ```
> deb http://ppa.launchpad.net/system76/pop/ubuntu groovy main
> ```
> 
> A little too much tuning on my part.

That line probably should not be in your `sources.list` file. That should instead be present in `/etc/apt/sources.list.d/pop-os-ppa.list`. Pop_OS doesn't use `sources.list` by default and all sources should be configured inside of `.list` files in `sources.list.d`. The actual `sources.list` file is only kept for backwards compatibility with some third-party tools which configure repositories there.

If you remove that line from your `sources.list`, you can re-add it in the correct location using the following command:
`apt-manage add ppa:system76/pop --ident pop-os-ppa`

**Comment by razvan01** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}       Sent from my BlackBerry — the most secure mobile device
