### ISSUE TITLE
Installer does not allow for dual boot with Windows

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#14]
_From @brs17 on October 13, 2017 21:27_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
On Oryxp3, Ubiquity installer recognizes "Windows Boot Manager" but only recommends erasing the disk to install Pop!_OS by itself.

**Steps to reproduce (if you know)**
Attempt to install Pop!_OS with Windows 10 already installed.

**Expected behaviour**
The Ubiquity installer should provide an option to dual boot the two machines. 

**Other Notes**
Screenshot:

![screenshot from 2017-10-13 14-10-09](https://user-images.githubusercontent.com/7460774/31566817-874357ca-b029-11e7-9ab0-578d15392153.png)

Gparted can see and resize the windows partition and fast boot has been disabled. 

_Copied from original issue: pop-os/iso#160_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity

**Comment by anderejd** [comment]
Is this supported now?

**Comment by mmstick** [comment]
Not automatically, yet.

**Comment by anderejd** [comment]
Ok thanks for the reply!

I ended up choosing to do "Erase disk and install Pop_OS", very good experience and I appreciate that the official nvidia drivers are installed by the OS installer. 👍
