### ISSUE TITLE
Graphical issue Brave browser after suspend

### ISSUE THREAD

**Issue by gioab** [pop-os/pop#1407]
**Distribution (run `cat /etc/os-release`):** Pop OS 20.04
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Brave Browser 

**Issue/Bug Description:** When waking machine up from suspend with a brave browser previously open, everything aside from the loaded page is black. Cannot see tabs or any buttons. Restarting app fixes issue though

**Steps to reproduce (if you know):**

**Expected behavior:** No change in behavior before suspend, and after waking 

**Other Notes:**

**Comment by jacobgkau** [comment]
Thank you for the report. This has already been reported here: https://github.com/pop-os/nvidia-graphics-drivers/issues/69 

(If you are not using NVIDIA graphics, let us know and we can re-open with that additional detail.)
