### ISSUE TITLE
Install Pop_OS 17.10 hangs at keyboard installation ( English US - English US)

### ISSUE THREAD

**Issue by cuvtixo** [pop-os/pop#141]
**Issue/Bug Description**

Install Pop_OS 17.10 hangs at keyboard installation ( English US - English US)

**Steps to reproduce (if you know)**

Click on Icon (Install Pop_OS 17.10) on install choose English US when presented with keyboard layout titles. WAIT..............................

**Comment by brs17** [comment]
Thanks for reporting this issue @cuvtixo . Is this problem still happening?

Could you run the command `journalctl` once the installation hangs? These logs should hopefully be able to explain what is going on exactly.

**Comment by cuvtixo** [comment]
Sorry. I ended up getting around the problem by installing Ubuntu and "updating" it to Pop. I forget if I manually updated repositories, or not. If I can find the time, I'll try to replicate the problem.

**Comment by brs17** [comment]
@cuvtixo We are working on a new installer for Pop!_OS 18.04 and would love it if you could give it another chance when it releases (or if you're feeling up to it, try out a test iso: https://system76.com/pop/testing)
