### ISSUE TITLE
Missing title bar on some windows

### ISSUE THREAD

**Issue by Shivansumaji** [pop-os/pop#1410]
**Distribution** : Pop!_OS 20.10  x86_64

**Host Machine** : Core i3, Intel UHD Graphics, fresh installation, X11 with Pop default themes.
 

**Bug Description** : Missing title bar on some windows (Brave, Synaptic Package Manager, Visual Studio Code, potentially among others;
See image - https://user-images.githubusercontent.com/44332366/99761926-55e44000-2b1d-11eb-9d13-298ec003e0a0.jpg)

**Steps to reproduce** : Download and launch any of the specified applications.

**Expected Behavior** : The app launches without the titlebar and hence neither with minimise, maximise or close buttons

**Note** : This issue can get resolved by resetting GNOME settings to factory defaults by running the following comand in the terminal - 
$ dconf reset -f /org/gnome/

**Comment by mmstick** [comment]
Check "Show Window Titles" in the Pop Shell panel menu

**Comment by Shivansumaji** [comment]
Didn't see that earlier. Thanks.

**Comment by Shivansumaji** [comment]
> Check "Show Window Titles" in the Pop Shell panel menu

Yeah that works. Didn't see it earlier. Thanks.
