### ISSUE TITLE
Launcher shortcut not working

### ISSUE THREAD

**Issue by tsrobinson** [pop-os/pop#1413]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
All

**Issue/Bug Description:**
After last set of OS updates, the launcher keyboard shortcut (super + /) no longer works. I've tried disabling all keyboard customization, and switching keyboard languages, but nothing seems to work. All other super + shortcuts seem to be fine (open Terminal, close window, show apps etc.)

**Steps to reproduce (if you know):**

**Expected behavior:**
Should see the launcher tab.

**Other Notes:**

**Comment by tsrobinson** [comment]
After a couple of restarts this seems to have resolved itself -- I don't know if it's because I refreshed the keyboard layout settings? But I assume it's not a launcher specific issue so closing.

**Comment by keulinho** [comment]
Same issue here, all other shortcuts work as expected.

**Comment by mbainter** [comment]
I have also experienced this after this round of updates.  If I can't resolve it with trying to do some keyboard configuration refreshes I'll reopen this if nobody else has.

**Comment by mmstick** [comment]
Any chance that there's something else bound to the same shortcut?

**Comment by mbainter** [comment]
No, this is a known issue from upgrading to 20.10.  See pop-os/shell#749, and pop-os/gnome-control-center#130
