### ISSUE TITLE
New apps not in alphabetical order in app menu

### ISSUE THREAD

**Issue by itsmordecai** [pop-os/pop#1416]
**Distribution (run cat /etc/os-release):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

```
**Issue/Bug Description:**
When you install a new application, the app menu does not update to alphabetical order. I installed Slack but despite it installing it didn't appear where i expected it to only to later realise it was the last item on the list. To reproduce this, I did the same by installing Discord and it happened as well. This may be nitpicking especially since one can drag to the expected spot but it would be better if it worked how it used to.

**Steps to reproduce :** 
Open Discord's website
Download the .deb file
Install using the preinstalled Eddy

**Expected behaviour:** 
The apps should be in alphabetical order

**Comment by itsmordecai** [comment]
**Other Notes:**
I also updated Android Studio and the new icon appears on the Jetbrain Toolbox for updates but on the app menu it remains the older icon so I'm not sure if its the shell that's not updating as fast in relation to the clock freeze bug or some other bug.

**Comment by itsmordecai** [comment]
![Screenshot from 2020-11-24 20-24-01](https://user-images.githubusercontent.com/39312305/100129786-08583200-2e93-11eb-8376-03ac58b9b0c8.png)

as you can not from that screenshot, the android studio icon is the older icon, the date on the top bar can prove the date. also note that after uninstalling an app, the first app menu page has a blank spot at the end not populated from an icon from page 2

**Comment by ArjunSingh99** [comment]
This isn't a bug, it's a feature. Icon ordering in Gnome 3.38 appmenu no longer uses alphabetical ordering as the default for newly installed apps, because they can be reordered. Think of it as similar to an iOS home screen. Maybe there's an extension that can fix that for you, but it isn't a bug AFAIK.

**Comment by itsmordecai** [comment]
thank you for the clarification. i will close the issue.
