### ISSUE TITLE
"Failed to start Show Plymouth Power Off Screen."

### ISSUE THREAD

**Issue by jounlye** [pop-os/pop#142]
**Distribution**

 NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Issue/Bug Description**

Hello, 
I have a problem when my laptop comes to shutdown. 
My screen, instead of being totally black, shows me all the background processes
during the shutdown. I have noticed a error during this phase : 

[FAILED] Failed to start Show Plymouth Power Off Screen.

After rebooting, when I open a terminal and type "systemctl status plymouth-poweroff.service", I have in return this information : 

● plymouth-poweroff.service - Show Plymouth Power Off Screen
   Loaded: loaded (/lib/systemd/system/plymouth-poweroff.service; static; vendor
   Active: inactive (dead)

**Expected behavior**

If anyone can explain to me why my screen is not just black when I reboot/power off, and help me
to fix this problem with the Plymouth service.

Thank you :smile:

**Comment by brs17** [comment]
We have definitely noticed some odd behaviour with Plymouth. The plan is to do away with Plymouth splash screen stuff for 18.04 so this will no longer be an issue. In the meantime, I believe you should be able to disable the plymouth systemd service(s) if the problem prevents you from completely shutting down your machine.
