### ISSUE TITLE
Internal audio device not working on System76 Oryx Pro

### ISSUE THREAD

**Issue by elfsternberg** [pop-os/pop#1424]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
alsa-base:
  Installed: 1.0.25+dfsg-0ubuntu5
  Candidate: 1.0.25+dfsg-0ubuntu5
  Version table:
 *** 1.0.25+dfsg-0ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
        100 /var/lib/dpkg/status
```

```
pulseaudio:
  Installed: 1:13.99.2-1ubuntu2.1
  Candidate: 1:13.99.2-1ubuntu2.1
  Version table:
 *** 1:13.99.2-1ubuntu2.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:13.99.2-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
```

**Issue/Bug Description:**

`Audio Device: Intel Corporation Cannon Lake PCH cAVS (rev 10)` not recognized by Pulseaudio; attempting to use it directly via `aplay -D` produces one of two outcomes: either "device is busy" _or_ the speakers work and WAV files can be played through them.  I received this laptop from System76 in December of 2019 and this feature was working then.  I have not manually changed any configuration detalis of the drivers or supporting programs.  I have attempted several of the fixes found here or on Reddit, without success.

**Steps to reproduce (if you know):**

Boot the system.  Attempt to play any audio at all.  Review Control Panel -> Sound -> Hardware and see that device is not listed, and that control over the volume / mute features of the speakers and the headphones are available and sticky (settings survive between reboots).

**Expected behavior:**

Audio output can be directed to the speakers via the Volume Control widget in the dock.  

**Other Notes:**

Other sound features, including some complex PulseAudio configurations, work just fine.  The Bluetooth and HDMI sound is reliable.

**Comment by elfsternberg** [comment]
Amendment: I can *only* play the audio files through the internal speakers and/or the headphone jack this way:
```
sudo aplay -D "sysdefault:CARD=PCH" ~/media/narf.wav
```
Note the required use of sudo.  Ordinary users get a `permission denied` error.

**Comment by jacobgkau** [comment]
I'm sorry about the audio trouble. If you're having an issue on System76 hardware, it's best to open a [support ticket](https://support.system76.com/) so our support team can help you directly.

Does the issue occur in a new user account? Does it occur in Recovery mode (hold down spacebar during boot)? You mentioned that you haven't changed any configuration details, but also that "complex PulseAudio configurations" are working-- what complex PulseAudio configuration have you performed? What are the several fixes from GitHub and Reddit that you attempted?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by elfsternberg** [comment]
By "complex" I mean that for those features that hook into PulseAudio, such as creating multiple paths out of a source and using multiple sinks, that part works fine. 

I did figure it out.  The breakage happened after upgrading from 18 to 20, and there are two issues.  The first is that in order to use ALSA, users must be part of the `audio` group.  That's a breaking change from earlier versions, and it seems mysterious since "audio" for most users continues to work just fine: Pulse will dutifully pass audio to Bluetooth and HDMI-connected devices, but not those that use "the sound card" on the hardware.

The second is that the ALSA device name for "route through Pulse" has changed; it is now "default," which is understandable and fine, but for older games that required the device specified in its configuration this resulted in breakage.  This only affects older games, but lots of people like older games.
