### ISSUE TITLE
(EFI system partition too small) Can not add PopOs to existing multiboot machine

### ISSUE THREAD

**Issue by mc4man** [pop-os/pop#1431]
**Distribution (run `cat /etc/os-release`):**
 Latest 20.10 image
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When trying to do advanced install will not let me proceed after choosing partition to install to 
Appears that the existing EFI partition (210MB) doesn't meet the min. of 500MB?? 

**Steps to reproduce (if you know):**
Try to add PopOs to existing multiboot with an EFI/boot partition less than 500MB

**Expected behavior:**
Use my existing EFI partition
(which is located on sdb as sda is a small unallocated internal drive

**Other Notes:**

**Comment by jacobgkau** [comment]
My work machine with Pop!_OS only is currently using 315MB in the EFI system partition. A lab machine with a relatively fresh install is using 201MB. I don't think it's possible for Pop to share an EFI partition as small as 210MB with another OS that's already taking up space.

**Comment by mmstick** [comment]
You can have multiple EFI partitions
