### ISSUE TITLE
Package tensorflow-cuda-latest unavailable in Pop!_OS 20.10

### ISSUE THREAD

**Issue by ScriptAutomate** [pop-os/pop#1432]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 20.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`tensorflow-cuda-latest`, which installs without issue on Pop!_OS 20.04 and earlier via the following doc, doesn't install in Pop!_OS 20.10:

- [Pop!_OS: Install Tensorflow](https://support.system76.com/articles/install-tensorflow/)
  - [Source on GitHub](https://github.com/system76/docs/blob/master/_articles/install-tensorflow.md)

**Issue/Bug Description:**

Previously, running the following would install Tensorflow as expected:

```
sudo apt install tensorflow-cuda-latest
```

It no longer does. Either it needs to be made available for Pop!_OS 20.10, or the documentation needs to be updated to reflect the deprecation (with alternative directions, if able).

**Comment by mmstick** [comment]
It hasn't been possible to install since 19.04. It does mention in the documentation that 19.10 and later uses [tensorman](https://support.system76.com/articles/use-tensorman/)
