### ISSUE TITLE
Please Add "Arial" font inside fonts default system

### ISSUE THREAD

**Issue by thiagolucio** [pop-os/pop#1434]
This is not a bug because it does not prevent the system from functioning. However, the absence of the "Arial" font makes Google Chrome in Pop OS 20.10 render the standard display fonts by a font that is very strange and quite uncomfortable to read. 

**Distribution (run `cat /etc/os-release`):**
` 
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os  
`
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
- Google Chrome Version 87.0.4280.88 (Official Build) (64-bit)

**Issue/Bug Description:**
The absence of the "Arial" font makes Google Chrome in Pop OS 20.10 render the standard display fonts by a font that is very strange and quite uncomfortable to read. 

**Steps to reproduce (if you know):**
- Just remove Arial font from your system and you can see the font rendering problem. 

**Other Notes:**
- If you like. I have a repository with a lot coding fonts to use. Inside them i have the Arial fonts I used to solve my problem.
- https://github.com/thiagolucio/code-editor-fonts

**Comment by ids1024** [comment]
I believe there are some legal concerns with distributing Microsoft's fonts. You can install the `ttf-mscorefonts-installer` package.

**Comment by thiagolucio** [comment]
Arial it's created in 1982. But I think you're wright about this. In my caso I just put this font inside my system. But in the System76 company I think it's possible because POPOS it's a free O.S by MIT. But I don't have knowledge about this legal rules. But doesn't matters because your solution it's a great choice. Thank's to share. 

I don't know if I close this Issue or stay open. What you suggest?

**Comment by ids1024** [comment]
> Arial it's created in 1982.

I believe under current US law that would remain in copyright for 95 years, so until 2077 ([funnily enough](https://en.wikipedia.org/wiki/Cyberpunk_2077)).

Do you happen to know if fonts in Google Chrome have similar issues with the default configurations other distros like Ubuntu? If not we could see what they do to deal with this.

It would make sense for Chrome to use Liberation Sans as a fallback for Ariel if it isn't installed (for instance). Not sure if there's a good mechanism for that.

**Comment by thiagolucio** [comment]
Wow! Too much time. I don't know if the humanity be exist in 2077 \o/.
I think I can try simulate this fonts by google. Some fonts are free to use. The problem in this case it's put this font (and remove again Arial) and don't change the definition inside the POP OS (i think) because inside pop will be currently the Arial declaration. But doesn't hurt to try...

**Comment by mmstick** [comment]
The fonts that Google uses are in the `fonts-croscore` package. They don't contain Arial, but it's a collection of fonts that approximately emulate Microsoft's font selection, and do get applied as a suitable replacement.

**Comment by thiagolucio** [comment]
I did not know that. However, when installing version 20.10 of PopOS and installing Chrome I really got a bad result from the font when browsing most of the pages like the pages of Google, Gmail, and others. I also had bad font renderings on the GitHub website for example. The fonts had a deformed appearance, compressed horizontally, and inspecting the codes of these fonts did not return an explicit source declaration. Numeric codes only. I, in this case, suggested to Arial because she solved my problem as described.
I then believe that my problem is specific to my installation and is not being replicated in other installations in this case. In this sense, I believe that closing this issue is the most appropriate. If someone believes it is important, they can reactivate the topic.
