### ISSUE TITLE
GNOME occasionally glitching in 20.10

### ISSUE THREAD

**Issue by ianrgraham** [pop-os/pop#1441]
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
 
gnome:
  Installed: (none)
  Candidate: 1:3.30+3
  Version table:
     1:3.30+3 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages

Hi there, I'm having an issue where glitchy artifacts are produced by the UI elements of GNOME. This happens suddenly, and occurs in bursts when interacting with the UI elements (pressing the super key, moving between desktops, clicking on the activities bar, interacting with application windows). I can stop the behaviour by restarting the shell, but the same artifacts are sure to crop up within a few hours after I've fixed it. I also tried screen capturing the behaviour, but the artifacts are not visible in the capture. I noticed this occurring immediately after upgrading from 20.04 to 20.10.

**Comment by tbeason** [comment]
I can confirm this behavior on 20.10, although it has not always existed on 20.10 for me. I usually do a few things, then lock the desktop, log back in, and I think that usually fixes things on the first try.

**Comment by paines** [comment]
I can confirm this too with 20.10 on a nvidia+intel notebook running in hybrid mode, meaning, intel is the main gfx card while nvidia would kick in on demand. The glitches started when e.g. a pop up or dialog would be shown to save e.g. a file from the browser. Now I rebooted into nvidia graphics only mode, and it seems to be better, BUT which is now acceptable workaround what so ever. I will  observe this some more and report back.
