### ISSUE TITLE
Hardware Related problems.

### ISSUE THREAD

**Issue by gghhkm** [pop-os/pop#1448]
## **Distribution**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

[Install-logs.zip](https://github.com/pop-os/pop/files/5716496/Install-logs.zip)

**Comment by leviport** [comment]
Care to describe the problems a little?

**Comment by gghhkm** [comment]
> Care to describe the problems a little?

just missing a bunch of firmware (mostly GPU)
AMD ATHLON silver.

**Comment by ids1024** [comment]
That's still not very specific. Radeon could mean a card released in 2020, or one from 2000.

**Comment by gghhkm** [comment]
> That's still not very specific. Radeon could mean a card released in 2020, or one from 2000.
> 
> Edit: I guess that's an integrated GPU?

Nope, I pretty sure it's not

**Comment by gghhkm** [comment]
> That's still not very specific. Radeon could mean a card released in 2020, or one from 2000.
> 
> Edit: I guess that's an integrated GPU?

Neofetch :
CPU: AMD Athon Silver 3050U with Radeon Graphics (2) @ 2.300GHz
GPU: AMD ATI 03:00.0 Picasso
I'm going to have to find the box if you want anything more conclusive then that.

**Comment by jacobgkau** [comment]
> just missing a bunch of firmware (mostly GPU)

Are you seeing messages about "missing firmware" or "possibly missing firmware" while installing updates via the terminal? Those messages do not indicate an actual issue. I'm familiar with what the messages look like, and that sounds like what you're describing, so I'm closing this issue for now. (If you are having an actual problem using the computer, please let us know what it is and we can re-open.)

The CPU you named is a laptop CPU (that is not in any System76 hardware off the top of my head.) If firmware was actually missing, you would probably need to contact your hardware manufacturer and/or AMD to add the firmware to the Linux kernel and/or `linux-firmware` package.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by gghhkm** [comment]
> > just missing a bunch of firmware (mostly GPU)
> 
> Are you seeing messages about "missing firmware" or "possibly missing firmware" while installing updates via the terminal? Those messages do not indicate an actual issue. I'm familiar with what the messages look like, and that sounds like what you're describing, so I'm closing this issue for now. (If you are having an actual problem using the computer, please let us know what it is and we can re-open.)
> 
> The CPU you named is a laptop CPU (that is not in any System76 hardware off the top of my head.) If firmware was actually missing, you would probably need to contact your hardware manufacturer and/or AMD to add the firmware to the Linux kernel and/or `linux-firmware` package.
> 
> System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

The install logs are right there, you can easily look yourself lmao. Possible missing.
I do have an Issue with it but it has more to do with flatpak not Pop itself. Realtek WiFi drivers are also an issue but I'm not going to worry about it sense it's .1) advisable in the Pop_shop and .2) they work just now for WPA3.
