### ISSUE TITLE
Computer doesn't respond after opening lid

### ISSUE THREAD

**Issue by Mycheze** [pop-os/pop#1460]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not an issue with an application.

**Issue/Bug Description:**
When I open my computer after having it closed, the screen turns on, but is frozen. The time is still set to when the computer was shut and doesn't update. No buttons respond to pressings and I need to restart my computer. The past few times it's happened, there were 0-1 programs running when the computer was closed.

**Steps to reproduce (if you know):**
Close windows and computer lid as usual. Come back in a few minutes (or overnight) and open the lid. About a 50% chance that the computer will be on the wrong time and won't respond to any input.

**Expected behavior:**
No response and need to restart the laptop.

**Other Notes:**
I just downloaded OS version 20.10, so that might (hopefully) fix the issue. I'm still going to submit this issue because I don't have time later to redo everything.

**Comment by ids1024** [comment]
This is likely related to drivers for the computer you're running on.
