### ISSUE TITLE
Default Settings of Pop OS Make Gaming Impossible with Trackpad

### ISSUE THREAD

**Issue by richardanaya** [pop-os/pop#1463]
By default, the gnome settings have trackpad disabled when "typing". This makes it impossible for me to play a game using WASD controls and trackpad.

![image](https://user-images.githubusercontent.com/294042/103324117-e6eee680-49fa-11eb-96c9-3e9868b00b26.png)

Once I disable this, keyboard and trackpad can be used at the same time.

**Comment by leviport** [comment]
I always thought gaming with the trackpad was pretty much impossible anyway.

In seriousness, I think the number of users benefiting from the better palm rejection provided by this setting is higher than the number of people that game with trackpads and need it turned off. Default settings can only cater to the many, while some people may still need to tweak them manually for their use cases. As someone who doesn't use a qwerty keyboard, I live this struggle every day.

Thank you for the report though!

**Comment by leviport** [comment]
Although being required to install gnome-tweaks to turn off the setting doesn't seem reasonable. There's some upstream discussion about making it appear in Gnome Control Center here: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/125. Perhaps we'll be able to make that happen so users who need to change that setting are able to do so more easily.

**Comment by ids1024** [comment]
This is awkward, because the setting is indeed problematic for a lot of games, but probably better for most other uses.

Though looking at this, another problem is that you had to go to Gnome Tweaks to disable it, when it probably should be in Settings. There's an [upstream issue](https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/125) about that. That should probably be changed.

The upstream issue also discusses trying to enable it only when a game isn't active, but it's not clear how that could work reliably.

**Comment by richardanaya** [comment]
In my experience, allowing trackpad motion while keys are pressed is NOT a problem.  I don't have this problem at all. 

I think what concerns me about how this issue was closed is that it seems like you are going by gut feel of an issue than comparing Pop OS.

"Oh, I suffer with Qwerty, so you have to suffer with trackpad and key presses?"

What??

A better way to resolve this would be exploring the bigger community:
* comparing to other competing operating systems
* getting actual user data from PopOS users

Does PopOS not do user experience surveys?

**Comment by richardanaya** [comment]
@leviport

**Comment by mmstick** [comment]
It is a very real problem with many issue reports to have touchpad input when keys are actively being pressed. When many people type on a laptop keyboard, a portion of their hand touches the touchpad from time to time. With this feature deactivated, it causes it to move the cursor and click on things, which is not acceptable when you're trying to type. Even qwerty is affected by this.

**Comment by leviport** [comment]
> In my experience, allowing trackpad motion while keys are pressed is NOT a problem. I don't have this problem at all.
Sorry, but you are in the minority with that one, and I'm absolutely confident of that. 

My point with the keyboard was meant to be an analogy about default settings and how they can't possibly cater to 100% of users. Qwerty is best for most users, but not for me, so I have to change default settings. Most users benefit much more from the trackpad being inactive when they are typing, so other users who can't have that happen will need to override the default. Sorry if my first comment didn't make sense, it was typed before I had finished my coffee.

Still, if there are users that need a setting to be changed, such as yourself, it should definitely be more easily accessible. The setting being changeable in a tool that isn't installed by default (gnome-tweaks) certainly isn't great.

We do user surveys when they are necessary, but this is a very minor question that we already know the answer to.

**Comment by richardanaya** [comment]
@mmstick you all have a differrent default setting here that is related to that problem

![image](https://user-images.githubusercontent.com/294042/103367266-8357ce00-4a79-11eb-90f9-e91e52a25e5e.png)

Right now popup seems setup by default "hey, if your palm even lightly touches the touch pad, we'll think that's a click."

**Comment by ids1024** [comment]
> comparing to other competing operating systems

For reference, according to the Gnome issue I linked, Disable While Typing is the default in Gnome, and not a change specific to Pop!_OS. Not sure if some distros change the setting, or how KDE compares.

**Comment by richardanaya** [comment]
@leviport Appreciate the response. In all humbleness, I know my experience isn't what everone's is.  I'll tell you all a story of maybe why i'm so grumbly about this issue. When I got this laptop I tried playing games, and for 6 months I had this issue, and I had no way to resolve it.  I thought my keyboard + mouse inputs were just broken in some way I never thought to ask about when buying a laptop.  Only randomly did I figure out how to solve that, and in the back of my mind it bothers me thinking that other people are walking around confused and upset about their purchases because of some rando hidden setting.

**Comment by richardanaya** [comment]
@ids1024 true, i'm mentioning my feedback to this issue here because I want PopOS to be awesome even if the rest of Linux operating systems just do whatever Gnome does  :)

**Comment by leviport** [comment]
Ah, I definitely see why that would be frustrating. If the setting were in Gnome Control Center where it would be easier to find, do you think that would have been less of a pain?

**Comment by richardanaya** [comment]
@leviport definitely, I think also part of the problem is how cryptic the setting "Disable while typing" is.  I'm not sure what the best way to word it would be.  "Using keyboard prevents mouse movement?"

The issue is most pronounced when you are playing an FPS game and you are using WASD controls.

if I'm holding down W to move forward, I literally cannot move my move my characters view around around with my trackpad.  It's like, while i'm holding down W to move forward, my camera is locked, and only when I stop moving can I move around with my trackpad to look at stuff in game.

**Comment by richardanaya** [comment]
Thanks @ids1024 🙏🏽

**Comment by ids1024** [comment]
I've submitted a merge request upstream to add a toggle for this to Settings, as well as PRs for the Pop!_OS fork backporting the change.

An ideal solution might be dependent on both the software one is using and the touchpad hardware (some may have better methods of supporting palm rejection). But at least having a discoverable setting to change should be an improvement here.
