### ISSUE TITLE
TypeScript plugin for Sublime Text 3 not working

### ISSUE THREAD

**Issue by Fulguritude** [pop-os/pop#1478]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
Package files:
 100 /var/lib/dpkg/status
     release a=now
1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
     release v=20.10,o=LP-PPA-system76-pop,a=groovy,n=groovy,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
     release v=20.10,o=LP-PPA-system76-pop,a=groovy,n=groovy,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://apt.pop-os.org/proprietary groovy/main all Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary groovy/main amd64 Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=amd64
     origin apt.pop-os.org
Pinned packages:
```

**Issue/Bug Description:**

I'm trying to get the TypeScript plugin for Sublime-Text 3 to run on Pop! OS. This plug-in needs access to the node executable for nodejs to function. It seems like apps downloaded from Pop! Shop, when launched, are set in a chroot-jail-like environment; and most binaries needed are missing. More details on my issue can be found here. https://forum.sublimetext.com/t/bug-sublime-text-cant-find-nodejs-on-pop-os-ubuntu-20-10/55553

 I would like to know **how to change this chroot-jail-like environment (ie, add node to it), or how to override it, and run an app un-chrooted**.

**Other Notes:**

I tried to go to the mattermost channel to ask this question but there was "no team I could join", apparently. Additionally, this might be a better place to have a reference on how to solve this issue than mattermost.

**Comment by jacobgkau** [comment]
> It seems like apps downloaded from Pop! Shop, when launched, are set in a chroot-jail-like environment; and most binaries needed are missing.

I see someone on the Sublime Text forum suggested this to you, but they were not familiar with Pop!_OS and were only giving you a guess at what _might_ have been happening:

> Sublime doesn’t do that; it’s just a standard application. It sounds like PopOS is a Linux distro that tries to run all apps in their own sandboxed chroot jail or something along those lines, if the file system as Sublime sees it is different than reality.

Pop!_OS does not "try to run all apps in their own sandboxed chroot jail." I think what's going on is that you downloaded a [Flatpak](https://flatpak.org/) version of Sublime Text (the only Sublime Text available in the Pop!_Shop is a Flatpak):

![image](https://user-images.githubusercontent.com/7199422/104066997-95471880-51bf-11eb-82c8-2fec531e59f7.png)

The behavior you're seeing should be the same for Flatpaks on any distribution.

> I would like to know how to change this chroot-jail-like environment (ie, add node to it), or how to override it, and run an app un-chrooted.

If the Flatpak package is not working for your use case, you can install the regular apt version using the instructions on Sublime's website: https://www.sublimetext.com/docs/3/linux_repositories.html 

You might also want to report this on the GitHub repository for the Flathub package of Sublime Text, since that's most likely where this would need to be fixed: https://github.com/flathub/com.sublimetext.three 

> I tried to go to the mattermost channel to ask this question but there was "no team I could join", apparently. Additionally, this might be a better place to have a reference on how to solve this issue than mattermost.

What steps did you take to sign up for Mattermost? Does logging in or signing up again at this link not work? https://chat.pop-os.org/ If not, could you provide a screenshot of what you're seeing instead?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by Fulguritude** [comment]
> I see someone on the Sublime Text forum suggested this to you, but they were not familiar with Pop!_OS and were only giving you a guess at what might have been happening

I had a similar hypothesis before, but indeed the flatpak "sandbox" environment is the correct description.

> If the Flatpak package is not working for your use case, you can install the regular apt version using the instructions on Sublime's website: https://www.sublimetext.com/docs/3/linux_repositories.html

Worked for me, thank you very much !!

> What steps did you take to sign up for Mattermost? Does logging in or signing up again at this link not work? https://chat.pop-os.org/ If not, could you provide a screenshot of what you're seeing instead?

It worked today, so I suppose this was probably an issue of my user account not being retrieved properly from the database, since I had just created it.

> You might also want to report this on the GitHub repository for the Flathub package of Sublime Text, since that's most likely where this would need to be fixed: https://github.com/flathub/com.sublimetext.three

I created an issue to let them know. But since my problem is now solved by following the apt install procedure, I'm marking this as closed.

Many thanks again !
