### ISSUE TITLE
Nautilus does not display progress of compressing 

### ISSUE THREAD

**Issue by themccallister** [pop-os/pop#148]
**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

nautilus:
  Installed: 1:3.26.0-0ubuntu1
  Candidate: 1:3.26.0-0ubuntu1
  Version table:
 *** 1:3.26.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description**

When compressing folders on the Desktop using the mouse, the nautilus window has no concept/reporting of the progress. When compressing, in any other directory, nautilus will display a progress.

**Steps to reproduce (if you know)**

1. Use the tweaks tool and enable "Show Icons" on the desktop 
2. Right click on a folder that on the desktop
3. Click compress
4. Check any nautilus window and look for the compression status 

**Expected behavior**

The progress of the compression/file operation will be displayed in nautilus.

**Comment by brs17** [comment]
This is an issue with Nautilus upstream. With GNOME's plans to remove desktop icon support, I would imagine it would be quite difficult to get a fix in.
