### ISSUE TITLE
RAW thumbnailer does not work in Nautilus/Files

### ISSUE THREAD

**Issue by andre-fuchs** [pop-os/pop#1484]
I cannot get thumbnail images to work for RAW files in Nautilus/Files. [Fixes](https://medium.com/@abelmahefa/getting-thumbnails-of-your-raw-files-in-ubuntu-19-10-or-later-d5600391fd42) via gdk-pixbuf-thumbnailer that should work for Ubuntu 19.10 and newer did not work for me in Pop!_OS 20.10. Not sure how to debug this. 

With a recent version of Darktable my Linux machine is my new favorite tool for photo development, no joke! Thanks for your efforts, you rock.

**Comment by bflanagin** [comment]
I'm a big fan of Darktable too, though I'm sure I don't use it half as well as you do. I'll follow the fix you tried and see where it gets me.

**Comment by bflanagin** [comment]
Possible fix: modify `/usr/share/thumbnailers/gdk-pixbuf-thumbnailer.thumbnailer` to include RAW image mime-types

```
[Thumbnailer Entry]
TryExec=/usr/bin/gdk-pixbuf-thumbnailer
Exec=/usr/bin/gdk-pixbuf-thumbnailer -s %s %u %o
MimeType=image/png;image/bmp;image/x-bmp;image/x-MS-bmp;image/gif;image/x-icon;image/x-ico;image/x-win-bitmap;image/vnd.microsoft.icon;application/ico;image/ico;image/icon;text/ico;application/x-navi-animation;image/jpeg;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/tiff;image/x-xpixmap;image/x-xbitmap;image/x-tga;image/x-icns;image/x-quicktime;image/qtif;image/x-3fr;image/x-adobe-dng;image/x-arw;image/x-bay;image/x-canon-cr2;image/x-canon-crw;image/x-cap;image/x-cr2;image/x-crw;image/x-dcr;image/x-dcraw;image/x-dcs;image/x-dng;image/x-drf;image/x-eip;image/x-erf;image/x-fff;image/x-fuji-raf;image/x-iiq;image/x-k25;image/x-kdc;image/x-mef;image/x-minolta-mrw;image/x-mos;image/x-mrw;image/x-nef;image/x-nikon-nef;image/x-nrw;image/x-olympus-orf;image/x-orf;image/x-panasonic-raw;image/x-panasonic-raw2;image/x-pef;image/x-pentax-pef;image/x-ptx;image/x-pxn;image/x-r3d;image/x-raf;image/x-raw;image/x-rw2;image/x-rwl;image/x-rwz;image/x-samsung-srw;image/x-sigma-x3f;image/x-sony-arw;image/x-sony-sr2;image/x-sony-srf;image/x-sr2;image/x-srf;image/x-x3f;
```

**Comment by bflanagin** [comment]
@andre-fuchs 

Whats the extension found at the end of the raw files your camera is generating? It may be as easy as adding the mine type to the list.

**Comment by andre-fuchs** [comment]
> Whats the extension found at the end of the raw files your camera is generating? It may be as easy as adding the mine type to the list.

Thanks for looking into this, @bflanagin. I got a ARW files, that is Sony’s popular RAW standard. Your list already includes "x-sony-arw" with no effect.

**Comment by bflanagin** [comment]
@andre-fuchs 
Its no trouble, we want Pop!_OS to be as feature complete for as many types of creators as possible. 

Unfortunately you and I have gotten as far as we can using the supplied fix and it seems that the gdk-pixbuf team isn't really concerned with raw image previews. I believe there still may be a fix but I'll have to do more digging. If I find something I'll update the issue and put in a PR for inclusion.

**Comment by andre-fuchs** [comment]
Thanks @bflanagin! I appreciate it.

**Comment by bflanagin** [comment]
@andre-fuchs I have a possible fix for us, but I need you to be my guinea pig, and be aware its not a super fast solution.
you'll need to install rawtherapee first.

Using the terminal:

`sudo apt install rawtherapee`

Then download [rawtherapee.thumbnailer.txt](https://github.com/pop-os/pop/files/5914382/rawtherapee.thumbnailer.txt), rename the file rawtherapee.thumbnailer and put it in /usr/share/thumbnailers with the others like it. 

`sudo mv /path/to/rawtherapee.thumbnailer /user/share/thumbnailers/`

Once its in place you'll need to delete your cached thumbnails

`rm ~/.cache/thumbnails/*` 

After all that, you can log out and back in or just hit F5 in a folder containing images and the previews should start showing up. 

**issues** rawtherapee-cli takes ~1 second per image, on average. So large directories will take a while to update. Batching the images would be a better solution and will be a part of the PR when I have it written. 

Until then let me know if it works for you.

**Comment by andre-fuchs** [comment]
Thanks @bflanagin!
It works, although as slow as mentioned, but that is not a major issue for thumbnails. Some minor corrections to your little guide to make it work on my machine. Not sure if these are typos or not. The `/user/` directory is names `/usr/`, right? And I have sub-directories in the` /thumbnail/` directory, so better use

`sudo mv /path/to/rawtherapee.thumbnailer /user/share/thumbnailers/`

and

```
rm ~/.cache/thumbnails/normal/*
rm ~/.cache/thumbnails/large/*
```

or maybe
`
rm -rf ~/.cache/thumbnails/`    ?

**Comment by bflanagin** [comment]
That's what I get for typing while listening to someone talking.  You're right, `/usr` not `/user` and `rm -r ~/.cache/thumbnails/*` 

Thanks for being able to read between the typos :)

 Updated my comment with the fixes.

**Comment by bflanagin** [comment]
Here is a link to the support document created from this thread. Hopefully there will be a true fix added upstream at some point.

https://support.system76.com/articles/fix-raw-image-previews/
