### ISSUE TITLE
By default, highlight searches in VIM

### ISSUE THREAD

**Issue by PanderMusubi** [pop-os/pop#1487]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
vim:
  Installed: 2:8.2.0716-3ubuntu2
  Candidate: 2:8.2.0716-3ubuntu2
  Version table:
 *** 2:8.2.0716-3ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
VIM is not highlighting searches automatically, e.g. gedit and other text editors and IDE's do this by default.

**Steps to reproduce (if you know):**
1. vi /tmp/a
2. enter text `blabla`
3. search text `lab`

**Expected behavior:**
When searching `lab` is highlighted

**Other Notes:**
Add `set hlsearch` to the system's default user settings for VIM. Otherwise, all users need to add this to `~/.vimrc` themselves. Implementing this would IMHO be in line for the aim of popos to have practical settings for developers.

**Comment by jackpot51** [comment]
You will have to talk to the vim project directly about this. We don't intend to custom package vim
