### ISSUE TITLE
Grub2 checking the wrong directory for grub.cfg

### ISSUE THREAD

**Issue by TiniTinyTerminator** [pop-os/pop#1491]
there's is a problem with installing grub and grub opening the grub.cfg file

**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

grub2:
  Installed: (none)
  Candidate: 2.04-1ubuntu26.7
  Version table:
     2.04-1ubuntu26.7 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages
     2.04-1ubuntu26.2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages
     2.04-1ubuntu26 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

**Issue/Bug Description:**

when installing grub and rebooting to test grub, you will not enter the grub gui in which you can choose your OS. instead it will boot into the grub terminal. a workaround is to manually load the /boot/grub/grub.cfg via grub-commands.

while looking into the problem i found out that grub at first only looks in the /EFI/ubuntu folder for a grub.cfg file (echo $prefix). this means that the grub.cfg file in /EFI/pop/ will never be used.

**Steps to reproduce (if you know):**

install grub to boot-partition
reboot
echo $prefix

**Expected behavior:**

grub opening the /EFI/pop/grub.cfg to load the grub configuration.

**Other Notes:**

another workaround is to move the files of /EFI/pop to /EFI/ubuntu
this way the grub.cfg file will be opened as normal

**Comment by bflanagin** [comment]
Thanks for the report @TiniTinyTerminator, Pop!_OS doesn't use grub as its boot manager so the version you install is the package maintainers version (hence the Ubuntu references.) We appreciate the work that went into finding the solution but as there is no bug here the issue will be closed to help keep the number of open issues under control.
