### ISSUE TITLE
Drawing pad not functioning properly in POP OS!20.10

### ISSUE THREAD

**Issue by jobins1492** [pop-os/pop#1498]
**Distribution (run `cat /etc/os-release`):*Pop Os 20.10*
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):*$pop-desktop*

**Issue/Bug Description:*The drawing pad's pointer gets stuck in the middle of drawing or doing something and need to tap the drawing pad to make it work again*

**Steps to reproduce (if you know):*Connect any drawing pad(In my case, Veikk Drawing Tablet) and try to draw with it.*

**Expected behavior:*While drawing, it gets stuck in between and you need to double-tap on the drawing pad with a drawing pen for making it work again*

**Other Notes:*It is reducing my productivity. Please fix it fast as it is not a hardware problem as it works well with other Os's.*

**Comment by leviport** [comment]
Thanks for the report. That sounds like it might be an issue with the driver for that tablet. Both my Wacom and Monoprice tablets don't have the same behavior. Did you have to install a driver separately, or is it using one that was included in Pop?

**Comment by jobins1492** [comment]
Thanks leviport, it was a problem with the driver. Now everything is fixed.
