### ISSUE TITLE
Touchpad scrolling to right indefinitely

### ISSUE THREAD

**Issue by sina-n** [pop-os/pop#1499]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
  
**Issue/Bug Description:**
Touchpad scrolling to right indefenitely in all applications (chrome, okular, pycharm, gedit)

**Comment by bflanagin** [comment]
Thanks for reaching out, 

This very well could be a hardware issue so check the touchpad for anything weird, as there are some residues that can affect the touchpad and cause all sorts of weird issues like the one you describe. 

If cleaning the pad doesn't fix the issue we'll need a little more information before we can figure out whats wrong. 

1. Whats the brand and model of your laptop:
2. Did this start happening the moment you installed Pop!_OS?
3. If you have a button combination on the keyboard that enables/disables the touch pad try toggling it. Its usually marked with something that resembles the touch pad.

**Comment by bflanagin** [comment]
Most likely a hardware issue, not something we can fix on the software level.
