### ISSUE TITLE
Totem Movie Player does not start playing selected media after plugin install

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#15]
_From @brs17 on October 13, 2017 21:1_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
After opening a file in a proprietary media format (such as .avi) for the first time, the user is prompted to install the appropriate plugins. After these plugins are installed the media player just sits there at a blank screen.

**Expected behaviour**
The movie player should restart on its own and load the previously selected media.

_Copied from original issue: pop-os/iso#159_

**Comment by WatchMkr** [comment]
Bug filed against Pop!_Shop to handle codec installation. This should also fix this bug. https://github.com/pop-os/pop/issues/16
