### ISSUE TITLE
Mouse cursor jumps to upper left corner on resize and other window events

### ISSUE THREAD

**Issue by rojizo** [pop-os/pop#1503]
**Distribution:**

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

When you resize a window from any corner of side, when you finish the cursor magically jumps to upper left corner... This is an annoying new bug recently introduced... It is like if the position of the mouse is reseted to (0,0) in window coordinates... just a wild guess. Curiously enough it doesn't happens in BraveBrowser (probably the resize code is different from the one in gnome... )

**Steps to reproduce (if you know):**

just drag and drop... i'm attaching an image...  sorry for the size

![output](https://user-images.githubusercontent.com/11900271/105410423-327b6580-5c32-11eb-8a5c-a59f72beb419.gif)

**Expected behavior:**

You know... the mouse should remain in its position

**Comment by leviport** [comment]
I believe this is the same bug as https://github.com/pop-os/shell/issues/842. https://github.com/pop-os/shell/pull/843 should address it, and is nearly ready to go.

If that update doesn't fix it, let me know here and I can reopen the issue.
