### ISSUE TITLE
Sound settings won't show Plantronics USB Microphone on input device.

### ISSUE THREAD

**Issue by rmsolera** [pop-os/pop#1507]
**NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
**

**Issue/Bug Description:**
I have a Plantronics C5220 Headset that is properly recognized as output device as "Headphones - Plantronics Blackwire 5220 Series", however when I set the microphone to be the one from the Plantronics device, I can only set "Internal Microphone - Built-in Audio. 
It seems that both output and input devices cannot be the Plantronics USB Device and only one can be chosen at a time. So If I set the input device to be the Plantronics USB Mic, then the output can only be the "Speakers - Built in audio" and viceversa.

**Steps to reproduce (if you know):**
1. Connect the headset to the USB of the laptop.
2. Go to settings/sound and check that output device is "Headphones - Plantronics Blackwire 5220 Series".
3. Go to Input group and change the Input Device from Internal Microphone - Built-in audio" to -> "Headset Microphone - Plantronics Blackwire 5220 Series".
4. Consequently, the output device automatically changed to "Speakers - Built-in Audio.

**Expected behavior:**
When in settings/sound the Output Device is "Headphones - Plantronics Blackwire 5220 Series", the Input Device should be "Headset Microphone - Plantronics Blackwire 5220 Series".

**Other Notes:**
I have tried to reset my pulse audio settings following this guide: http://support.system76.com/articles/audio/
lspci listed my sound card as:
Audio device: Intel Corporation 7 Series/C216 Chipset Family High Definition Audio Controller (rev 04), however I believe the headset has an integrated usb sound card as well.

**Comment by bflanagin** [comment]
I have a very similar issue with my Yeti microphone with a built in audio out. I'm still sorting out whether it is software, hardware, or a combination of the two.  For our purposes we will need a little more information run these two commands and add their output to your response.

1. apt policy pulseaudio
2. apt policy pulseaudio-module-gsettings

Also, in my tests I've found that changing out the usb cord on my Microphone fixes the issue, but I'm not yet ready to say that's all that's needed. Does your Plantronics Microphone have a interchangeable usb cord? If so, can you try a new cord with it and report back? If not, lets hope its a software issue.

**Comment by rmsolera** [comment]
Hi bflanagin. 
Thanks for letting me know about your issue as well. 
**I have downgraded to POP OS 20.04 LTS** and **the issue is not reproducing.** I guess it's a matter of software **happening only in 20.10**. I even can unplug and plug back several times the headset and it sets the output and input to the headset almost instantly.
The usb cable cannot be removed and It's useless to run the commands on 20.04 since this version doesn't have such issue.

**Comment by bflanagin** [comment]
Glad to hear it. Given that you've found a suitable work around I'll go ahead and close the ticket. Thanks for bringing it to our attention.
