### ISSUE TITLE
Internet is very slow and unstable

### ISSUE THREAD

**Issue by gnevesdev** [pop-os/pop#1509]
It keeps disconnecting and reconnecting and it's very slow. Around 500KB/s, while in ZorinOS it was 2MB/s. The internet speed itself is 500Mbps, and itś still working on my phone as normal. My internet type is wi-fi, by the way. Also PopOS version is 20.4 LTS.

**Comment by bflanagin** [comment]
We are going to need more info before we can diagnose the problem.
1. Whats the model of the computer/laptop you have Pop!_OS installed on? 
2. Is the connection better or worse on Pop!_OS 2010? (You can run it from a live usb to avoid installing it)

As a possible fix you can check for newer firmware by going to Settings-->Firmware. Of course it may take a while for the updated firmware to download and install given the speed of your connection. 

Feel free to respond to this ticket with the request information or the fix gets things working as expected.

**Comment by gnevesdev** [comment]
> We are going to need more info before we can diagnose the problem.
> 
> 1. Whats the model of the computer/laptop you have Pop!_OS installed on?
> 2. Is the connection better or worse on Pop!_OS 2010? (You can run it from a live usb to avoid installing it)
> 
> As a possible fix you can check for newer firmware by going to Settings-->Firmware. Of course it may take a while for the updated firmware to download and install given the speed of your connection.
> 
> Feel free to respond to this ticket with the request information or the fix gets things working as expected.

My computer is all custom, so I don't know the model... And I've never tried PopOS 20.10, but in the installation media of 20.04 the internet was working fine actually. It started after installing the OS for some reason. Also in Settings -> Firmware it says that there's no hardware supporting firmware automatic updates.

**Comment by bflanagin** [comment]
That's odd. Sense its all custom, do you know the make and model of the network card? Maybe there is a configuration tweak that applied to it after install. Something you can do for now, and something we can add to an update.

**Comment by gnevesdev** [comment]
> That's odd. Sense its all custom, do you know the make and model of the network card? Maybe there is a configuration tweak that applied to it after install. Something you can do for now, and something we can add to an update.

No idea about the network card model... Gonna switch distro for now and keep an eye on Pop. Test it from time to time, and see if it starts working with the new updates and all. It's an interesting OS.
