### ISSUE TITLE
MariaDB install bugs

### ISSUE THREAD

**Issue by Yuri6037** [pop-os/pop#1511]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
mariadb-server

**Issue/Bug Description:**
mysqld[71391]: /usr/sbin/mysqld: error while loading shared libraries: liblz4.so.1: cannot open shared object file: No such file or directory

**Steps to reproduce (if you know):**
- Install mariadb-server on v20.04
- Upgrade to v20.10
- Enjoy broken mariadb-server

**Expected behavior:**
The mariadb-server package should not be broken after an upgrade

**Other Notes:**
The problem only occured under a HP ElliteBook 840 G3.

**Comment by Yuri6037** [comment]
All right apparmor is a peace of crap. Steps to fix the problem:
`sudo ln -siv /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/`
`sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld`

It's maybe not an elegant solution but it works and allows me to work.

**Comment by mmstick** [comment]
Might be useful to report that with Ubuntu (or whomever is packaging mariadb)
