### ISSUE TITLE
GDM / Gnome fail to start after the install of the NVIDIA variant of Pop!_OS

### ISSUE THREAD

**Issue by osbama** [pop-os/pop#1514]
**Distribution (run `cat /etc/os-release`):**
 20.04 or 20.10 Nvidia variants of Pop_os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
3D accelerated desktop environment. 

**Issue/Bug Description:**
I have tried to install Pop_os 20.04LTS and 20.20 on two desktop machines. One is AMD 5900x + Nvidia RTX 2080 the second one is Intel I7 (something from 8 years ago) + Nvidia GTX1060. Both of them boot to a zombie state desktop, where I can move the mouse around on a black screen and nothing else.  ctrl+alt+Fx for obtaining a terminal does NOT work; no key combination (including ctrl+alt+del) responds. Only a hard power cut restores the system. 

If I edit the grub to include kernel parameter "nomodeset" I am presented with a desktop, albeit not very pleasant to use. 
nvidia-drm modeset=1 does NOT work. Actually, I don't see any nvidia-drm module in the live os.  

**Steps to reproduce (if you know):**
Plug the USB, try to boot into OS without altering kernel parameters. 

**Expected behavior:**
A 3d accelerated desktop environment where I can install the system. 

**Other Notes:**
I tried older Nvidia drivers, to no avail. Non-accelerated environments such as XFCE work, but anything that relies on acceleration does NOT work, including Gnome on X.

**Comment by osbama** [comment]
After a debug session, I think the problem might be repeated got pause for xx:xx entries, and never any resume. For some reason xorg is told to block input. I couldn't identify why. A google search points Nvidia drivers and gdm3 update conflict in Arch wiki. I will try nouveau drivers, however, I am a CUDA programmer, and this is far from ideal.

**Comment by osbama** [comment]
After hours of mangling with various kernel options and suggestions, a complete purge of Nvidia drivers by apt remove *nvidia*; followed by ubuntu-driver install Nvidia did the trick. Though I really don't know if it is a combination of my attempts or not. 
Nouveau only works with nouveau.modeset=0 or xorg-driver=modesetting, both of which result in a 1024x768 mode with no option to change.

**Comment by osbama** [comment]
sorry, I forgot to mention even with nomodeset, gdm3 still does not work. All the above was about being able to use lightdm

**Comment by osbama** [comment]
I verified using a fresh install of pop-os 20.01 LTS that in both machines both with NVIDIA drivers, and nomodeset
the XFCE, KDE PLASMA, lightdm works, 
gdm, gnome, gnome on X,ubuntu, ubuntu on wayland and anything related to gnome does NOT work.
I really like the tiling window manager of pop!_os, so I would really appreciate help fixing this issue.

**Comment by bflanagin** [comment]
@osbama thanks for all the information. Given the specificity of the hardware it will be hard to test the exact reason why its failing. We have similar machines both more and less powerful and can't replicate the issue. 

Its possible that the installation media is damaged in some way that doesn't affect the install but causes faults once it has been installed (its rare but it can happen.)  I would suggest formatting the installation media and re-downloading the iso. If the nvidia version still causes an issue download the non-nvidia media and see if it gets you into gnome. It will be running on the opensource driver but for the sake of troubleshooting it will be a good base to diagnose further. 

Once you have a working desktop you can install the nvidia drivers `sudo apt install system76-driver-nvidia` which will require a reboot. 

Let us know if that gets you running as expected.

**Comment by osbama** [comment]
@bflanagin 
Thanks for the quick response.
The installation media is not the problem, I've tried at least three USB sticks (each in perfect working order), and both 20.4 and 20.20 variants several times. I also have the habit doing checksums each time I download something, so, no problems there either. 

Actually, after I narrowed the problem down to gnome, I started hitting many similar support requests in the past few months. The problem seems to be the transition of Gnome to Wayland, and Nvidia not supporting/playing with Wayland yet. Disabling Wayland modifications in /etc/gdm3/custom.config solved the problem with gdm3. I rolled back to a pre-Wayland gnome on x11, and I am writing this message using gnome desktop. 
Unfortunately, I couldn't get pop shell working.   
I guess I will wait until Nvidia properly supporting Wayland until I try Pop!_Os again. 
Best, 
Baris

**Comment by jacobgkau** [comment]
> Disabling Wayland modifications in /etc/gdm3/custom.config solved the problem with gdm3.

> I guess I will wait until Nvidia properly supporting Wayland until I try Pop!_Os again.

Pop!_OS ships with Wayland disabled (the `WaylandEnable=false` option is present and un-commented, as can be seen in https://github.com/pop-os/default-settings.) It sounds like you tried to enable Wayland with an NVIDIA card, and disabling it again solved the issue?

> Unfortunately, I couldn't get pop shell working.

I don't see anything else about Pop Shell in this issue. If you're having a separate issue with Pop Shell, please open an issue specifically for that in the Pop Shell repository (after searching to confirm nobody else has already reported it): https://github.com/pop-os/shell/issues 

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
