### ISSUE TITLE
Pop_OS! doesn't finish the suspend process and it stuck on a black screen

### ISSUE THREAD

**Issue by alberpilot** [pop-os/pop#1517]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Not always but usually, when I suspend the laptop from the upper right corner men, the suspend starts but it never ends, stuck in a black screen. 

**Steps to reproduce (if you know):**
Sometimes occurs with some applications opened and sometimes with others. 

**Expected behavior:**
A correct suspension. 

**Other Notes:**
Nvidia drivers
[nvidia_packages.txt](https://github.com/pop-os/pop/files/5897792/nvidia_packages.txt)
/var/log/syslog log
[syslog.1.txt](https://github.com/pop-os/pop/files/5897806/syslog.1.txt)

**Hardware specs**
Laptop Dell Inspiron 7567 variant 2: https://www.notebookcheck.net/Dell-Inspiron-15-7000-7567-Gaming-Notebook-Review.196454.0.html
16Gb ram, 16Gb Swap, Intel Core i7-7700HQ

**Comment by bflanagin** [comment]
@alberpilot, power management is very hardware specific and Linux APM support is still a little rough around the edges. Mind give us a little more info on your system CPU,Ram,model (if available).

**Comment by alberpilot** [comment]
Sorry, I edited the issue. I forgot to mention it. 
Thanks

**Comment by bflanagin** [comment]
Thanks for the update, unfortunately power management for non system76 machines falls into the realm of the mainline kernel developers and the hardware manufactures. If we're lucky 21.04 will have a fix for your hardware but there is little we can do internally. 
That being said, you could check out https://www.dell.com/community/Linux-General/bd-p/Linux to see if they have a solution or suggestions about your problem. 

And feel free to check out our community support channels on MatterMost [here](https://chat.pop-os.org/)
