### ISSUE TITLE
Do the correct thing with .iso and .img files

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#152]
Rename muff to usb-flasher.
Add it to the default install in the Utilities folder.
Set as the default application when opening .iso's and .img's
Other formats?

**Comment by mmstick** [comment]
Could support compressed images, like `.{img,iso}.xz`

**Comment by brs17** [comment]
I just clicking on a .iso that was on a flash drive and it took quite a while to show up in popsicle. I tried again, and it happened much quicker. Both times top shows quite heavy cpu usage.

![screenshot from 2018-03-29 16-33-50](https://user-images.githubusercontent.com/7460774/38117361-c0d41468-3371-11e8-83cb-f95379a28cc5.png)

**Comment by brs17** [comment]
Ah, I stand corrected, the cpu usage seems to be whenever popsicle is running.

**Comment by brs17** [comment]
@mmstick So .iso, .img, .img.xz all work. .iso.xz still defaults to archive manager.

**Comment by brs17** [comment]
While probably not blocking for release, it looks like none of these file types consistently open with popsicle anymore.

**Comment by mmstick** [comment]
Anything `xz`-related shouldn't be supported at the moment -- just `iso` and `img`.

**Comment by brs17** [comment]
And it wasn't working with .iso

**Comment by jackpot51** [comment]
This will be fixed with a new pop-default-settings

**Comment by brs17** [comment]
.iso, .img, .img.xz all seem to work now. .iso.xz still opens in archive manager

**Comment by brs17** [comment]
Looks like .iso.xz only has a mime type of .xz so there is no way to determine an extension of of .iso.xz. The other three extensions work so I'm going to close this!
