### ISSUE TITLE
Window switching works only in current workspace

### ISSUE THREAD

**Issue by kwehsadilla** [pop-os/pop#1520]
**Distribution**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

After a fresh re-install of pop-os, I can no longer have the application switcher disable grouping of windows of the same application. I remember it was a pain to get it to work like that on my previous installation, and I can't remember how to do it again.

The issue:
-In Keyboard Shortcuts under Settings, "Switch applications" almost works how it should, but it groups windows of the same applications, and for my workflow I don't want to keep switching between alt-tab and alt-` to instantly get to the window I want.

-"Switch windows" works exactly how it should, but only in the current workspace. How can I have that feature but across all workspaces?

**Comment by bflanagin** [comment]
So for the first issue, not remembering how to change gnome from "switch applications" to "switch windows" you go to Gnome Settings-->Keyboard-->Customize ShortCuts--> Navigation and look for the two options and swap out their hotkeys or assign one hotkey to SA and one to SW. Screenshot for reference:
![Screenshot from 2021-02-02 08-03-45](https://user-images.githubusercontent.com/10382037/106611481-a3bdf100-652d-11eb-8d9e-ebd471566d41.png)

**Comment by bflanagin** [comment]
For your other issue, I don't see the option right off the bat but you can use `super+/` to pull up the launcher that by default shows all currently running applications on all desktops.

That being said our usual support channel for non-bug / features requests is our mattermost server at https://chat.pop-os.org. For issues like this they are a far faster resource than our issues channel here on github. Hope to see you there.

**Comment by kwehsadilla** [comment]
Hello. Really sorry for not explaining more.
That's not what I didn't remember, but rather I forgot how I solved what you call my second issue.

On my side it's a bug because switching windows does not switch between windows but switches between applications

**Comment by kwehsadilla** [comment]
And it does so only in the current active workspace. The issue is how to make it work across all workspaces.
