### ISSUE TITLE
Medion Akoya S15449 Keyboard not recognized

### ISSUE THREAD

**Issue by replydev** [pop-os/pop#1528]
## Distribution (run `cat /etc/os-release`):
Pop OS 20.10 AMD-Intel Version
 
 
 
## Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):
The entire system

## Issue/Bug Description:
Hi and thank you for developing this amazing distribution. I have a brand new laptop, an **Medion Akoya S15449**, that comes without an operating system installed. I wanted to install POP OS, but the keyboard isn't recognized at all. I think that the kernel is missing the correct keyboard driver.

### Useful informations:
 - The keyboard works in the Windows 10 Installer
 - The keyboard works in Windows 10
 - If i connect an external keyboard it will be recognized correctly
 - If i install Pop OS using the external keyboard and launch a system update using `sudo apt update && sudo apt upgrade`, the keyboard doesn't work either
 - The keyboard works in the first screen, when it says "Try or install Pop Os", because the system recognizes enter and arrow keys (but also all the others).
![immagine](https://user-images.githubusercontent.com/43727434/107043674-9e79d400-67c3-11eb-8467-ba2464ed07ef.png)
 - The same problem appers in Arch Linux, the keyboard is detected in grub screen (boot archiso UEFI), but it's not detected in the tty.
![immagine](https://user-images.githubusercontent.com/43727434/107043783-c0735680-67c3-11eb-950f-5f6496b68f76.png)
 - In the first try i used the [ventoy ](https://www.ventoy.net/en/index.html) tool, so i though it were a ventoy's problem, but after i retried to flash pop os with Rufus and the problem is still the same.

## Steps to reproduce (if you know):
Just launch the Pop Os live iso

## Expected behavior:
A fully functional keyboard.

## Other Notes:
I think that this laptop is built with new components, so we are missing new kernel modules to recognize the keyboard.
I do not know the reason why the keyboard works in the "Try on Install Pop Os" screen, maybe grub is using some **generic** keyboard driver.

**Comment by bflanagin** [comment]
Seems to be an issue in MS Windows as well under certain circumstances. If you have an external usb keyboard plug it in and see if this forces Pop!_OS to load the keyboard drivers. Then test both keyboards. If the built in keyboard still doesn't work its possible that the keyboard might be "locked"  Try using they built in function keys found on the laptop keyboard. 

All that being said, you may have better luck finding support for non-system76 hardware on one of our community hubs: [Reddit](https://www.reddit.com/r/pop_os/), [MatterMost](https://chat.pop-os.org)

**Comment by replydev** [comment]
As i wrote in the first comment, i tried one external keyboard and it works well, but the built in laptop keyboard doesn't work at all. 

Which function keys are you talking about? Thank a lot for your help.

**Comment by bflanagin** [comment]
Oh, sorry missed the part about the external keyboard. 

>Which function keys are you talking about? Thank a lot for your help.
It was a long shot, I was hoping there was a keyboard lock on the keyboard that I just didn't see when looking at the images I found on google for your hardware. I'm sure if you had one it would be obvious by now given the trouble you're having. 

> Pop os recognizes fn + function_key hotkey(for example to increase the brigtness)
That is odd 

I'll ask around, but the community will be your best bet links can be found in my comment above.

**Comment by replydev** [comment]
This is related: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1909814

**Comment by replydev** [comment]
A patch fix has been merged into the mainline kernel branch. We can consider this issue closed. 

For more information please check this thread: https://bugzilla.kernel.org/show_bug.cgi?id=213031
