### ISSUE TITLE
[BUG] Can't update flatpak for Visual Studio Code in Shop / command line

### ISSUE THREAD

**Issue by dodalovic** [pop-os/pop#1529]
* The latest Pop OS
* When updating via Shop app, it updates, and then seems like it's done, but then the Update button appears again. It never updates
* Via command line:
![image](https://user-images.githubusercontent.com/6358061/107033979-5902da00-67b6-11eb-9de5-d4fc3ef636ea.png)

* Via cmd line, verbose mode
![image](https://user-images.githubusercontent.com/6358061/107034188-aa12ce00-67b6-11eb-8446-5ecee4ce4a0a.png)

**Comment by jacobgkau** [comment]
The shell repository is for the GNOME window tiling extension, Pop Shell. I have transferred this issue to the general Pop repository.

**Comment by jacobgkau** [comment]
The shell repository is for the GNOME window tiling extension, Pop Shell. I have transferred this issue to the general Pop repository.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by jacobgkau** [comment]
The shell repository is for the GNOME window tiling extension, Pop Shell. I have transferred this issue to the general Pop!_OS repository.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by bflanagin** [comment]
Looks like a problem with the flatpak which was updated yesterday. I suggest you go to: https://flathub.org/apps/details/com.visualstudio.code and see if the publisher has a support link. 

We may have bugs, but this one isn't ours.
