### ISSUE TITLE
Steam & Installed Steam Games Won't Start

### ISSUE THREAD

**Issue by evilthreads669966** [pop-os/pop#1531]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
- Steam
- Counter-Strike

**Issue/Bug Description:**
The two applications won't launch. I'm trying to download Elder Scrolls Online

**Steps to reproduce (if you know):**
They used to launch.

**Expected behavior:**
Steam should run and obviously counter-strike probably depends on the latter.

**Comment by evilthreads669966** [comment]
I re-installed Steam from pop shop and it still won't start. Should I try switching to flatpak instead of .deb file

**Comment by evilthreads669966** [comment]
It's actually showing 3 steam processes in system monitor

**Comment by evilthreads669966** [comment]
going to end them all and try again

**Comment by evilthreads669966** [comment]
all 3 steam processes run when I try to launch steam

**Comment by evilthreads669966** [comment]
I installed all the most recent operating system updates earlier. Like 180 of them.

**Comment by bflanagin** [comment]
@evilthreads669966 as frustrating as this answer is we have no control over steam, its games, or how they interact with your system and github is meant for bugs and software requests that are related to Pop!_OS and other things System76. 

BUT as I have had a similar issue in the past you should try re-initializing steam for your user account. 

First move the .steam folder to .steam-old in your home directory using the terminal 
`win+T` 
``` 
mv ~/.steam ~/.steam-old
```
Then without closing the terminal window run steam through it

`steam`

This should rebuild the .steam directory and launch steam. You will need to move the folders from .steam-old to the new .steam directory if you want to avoid reinstalling all your games. If you don't mind going through that process you can simply delete .steam-old.


For further more in-depth support go to our reddit page [here](https://www.reddit.com/r/pop_os/) or join our mattermost server [here](https://chat.pop-os.org) 

You can also try the steam support forums [here](https://support.steampowered.com/kb_cat.php?s=192fc81dc1e6335d47a8b4fc158e792f&id=97)

Closing Ticket.

**Comment by evilthreads669966** [comment]
@bflanagin perfect brother. Thank you. It worked great deleting .steam. I don't know why I didn't try that. I haven't had time to provide more info on the other issues but I will as soon as I can. Busy developing.
