### ISSUE TITLE
Oryx Pro 6 - Suspend issue

### ISSUE THREAD

**Issue by JeffLabonte** [pop-os/pop#1533]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Hey guys,

I am having some issues with suspends on my Oryx Pro 6. My laptop wasn't showing anything on the screen, and the fans were running at, at least 4000 rpm/

I hesitated to post this in `nvidia-driver, but I figured it would be linked to something as well since the machine is quite new and the kernel is 5.8 so it could go in the kernel repo. 

**Steps to reproduce (if you know):**

* Use the latest `nvidia-drviers` available with Pop!_OS
* Use the latest kernel available with Pop!_OS 
* Use your computer on battery
   * Plug/unplug AC
   * Run a while
   * Close and open the lid

**Expected behavior:**

Not end up with a black screen, fan running, and battery draining.

**Other Notes:**

[Xorg.0.log.old Gist](https://gist.github.com/598f4eedc3771231d7c81227d81bf712)
[Xorg.1.log.old Gist](https://gist.github.com/b30dbc43336e7d05a9cb02b3fa49e91b)

**Comment by bflanagin** [comment]
Thanks for the report @JeffLabonte. Though this may very well be a bug we need to address your first stop should be our support channels. https://support.system76.com/ 

I'll leave this issue open if you want to reference it in your communications with them.

**Comment by JeffLabonte** [comment]
I will close this issue since I had a firmware upgrade and the issue didn't reappear.
