### ISSUE TITLE
Encryption service in use without permission!

### ISSUE THREAD

**Issue by G4L1T0** [pop-os/pop#1534]
#### $ cat /etc/os-release

```bash
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

#### $ neofetch

```bash
OS: Pop!_OS 20.04 LTS x86_64 
Host: HP Desktop Pro A MT 
Kernel: 5.8.0-7642-generic 
Uptime: 8 mins 
Packages: 1928 (dpkg) 
Shell: bash 5.0.17 
Resolution: 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD PRO A6-9500 R5 2C+6G (2) @ 3 
GPU: AMD ATI Radeon R5/R6/R7 Graphics 
Memory: 2032MiB / 6927MiB 
```

#### EN  🇺🇸
My problem is at the time of installation. I do not select the disk encryption mode! And yet it performs disk encryption. I started having this problem two days ago

#### PT_BR 🇧🇷
Meu problema é no momento da instalação, eu não escolho a opção para criptografar o disco porém mesmo assim ele realiza essa criptografia, que resulta na mostra de vários erros durante o desligamento da máquina.

#### Below is a link with photos about the error

Imgur: https://imgur.com/a/Sm8nvKd

I like this distro 🙃
Waiting for feedback...

**Comment by mmstick** [comment]
The swap partition is encrypted by default, hence the service exists
