### ISSUE TITLE
Automatic blank screen doesn't work.

### ISSUE THREAD

**Issue by wychuzord** [pop-os/pop#1535]
**Distribution**
   OS: Pop!_OS 20.10 x86_64 
Kernel 5.8.18 (but don't go 'we don't support that kernel' because once it stopped working, then you got it working back again and now it's borked again. I've used alternate mainline kernels for months now and nothing of this sort ever happened)
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Maybe pop power play or whatever it was called? I saw that in the list of updates. Can't remember exact name though so can't check. I've updated today (Feb 8 2021) but it was couple weeks worth of updates.

**Issue/Bug Description:**
Screen won't blank even though in Power>Power Saving>Blank Screen options I put 1 minute. Same with Privacy>Screen Lock>Blank Screen Delay, set to 1 minute. I can wait several minutes and monitor won't go blank. Doing it manually (via sleep 3 ; xset dpms force off) works.

**Steps to reproduce (if you know):**
1. Set screen blank to shortest amount of time (1 minute)
2. Wait couple minutes
3. Screen doesn't go blank

**Expected behavior:**
The screen should go blank after the time set in the settings I mentioned above.

**Other Notes:**
I'll repeat just one thing in case it wasn't too clear. It broke several weeks before. Then some update fixed it, not sure what. Then I was afraid to update so nothing gets broken again and today I did naively and bam. Back to blanking the screen out manually.

**Comment by bflanagin** [comment]
Can you give us a little more information about your computer, I'm unable to replicate the issue here, but I don't want to rule out some hardware component causing the problem. 

gpu,cpu, computer make, and model number if you computer has one.

**Comment by wychuzord** [comment]
Sure.
Ryzen 5 3600, RX 5700 XT, Tomahawk Max B450
I'm running latest drivers from Oibaf PPA.
Not 100% about computer make and model but this isn't a pre-built PC so I'd guess it doesn't apply?

**Comment by bflanagin** [comment]
> Not 100% about computer make and model but this isn't a pre-built PC so I'd guess it doesn't apply?

Correct.

After doing a little research it looks like you're not the only one having the issue, and its occurring on multiple OSes (Ubuntu,Arch,SuSE,etc.) and configurations. Some are suggesting that this article may have a work around: https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling.  I'll keep and eye on the updates and circle back to this issue if there's one that might help.

**Comment by wychuzord** [comment]
Thank you. 
Workaround helped. It works now, just without the fancy gradual darkening. Maybe I'll have to change it every restart but at least I don't have to feel like a caveman anymore, manually blanking my monitor out.

So I didn't have xorg.conf.d in /etc/X11/xorg.conf.d/ so I checked the one I had in /usr/share/X11/xorg.conf.d/ but it didn't have anything with 'monitor' in it so I made a 10-monitor.conf file following the example on the wiki page, just changing "BlankTime". That didn't work (maybe a restart was needed) but then I tried "xset s 60" in the terminal and it worked. It works even without 10-monitor.conf file.
However, even with "xset s 60" after trying "xset q" when I find the screensaver section I see:
Screen Saver:
  prefer blanking:  yes    allow exposures:  yes
  timeout:  0    cycle:  0
So it's somehow off by default if I understand it correctly? Maybe problem lies there.

**Comment by wychuzord** [comment]
Okay, I've confirmed it.
Maybe it's obvious that it should happen this way but after I close the terminal in which I set "xset s 60" the timer setting will get back to 0.

**Comment by wychuzord** [comment]
I've installed today's updates, rebooted my system and automatic screen blanking works again, with fancy gradual dimming and all.
I guess it got fixed? 
¯\_(ツ)_/¯

**Comment by wychuzord** [comment]
After couple hours the problem returned.
Again xset q shows timeout: 0 cycle: 0 and the screen refuses to blank out.
Should I report somewhere else?

**Comment by wychuzord** [comment]
I'm becoming more and more convinced it was caused by Lutris blocking the screen blanking because of a game that failed to boot but didn't get closed automatically and kept figuring on the processes list. I haven't noticed it before but Lutris has an option to stop monitor from blanking out.

Terribly sorry for raising false alarm.
