### ISSUE TITLE
Opening Gazelle15 bottom cover

### ISSUE THREAD

**Issue by evilthreads669966** [pop-os/pop#1538]
I understand this is not the correct forum but I was looking on a pointer on how to open my bottom case. The instructions on system76 claim a certain number of screws but I have one less. I purchased in 2020 June. I took them out and have pried and it isn't budging and I don't want to damage it. I am trying to install a m.2. nvme ssd. I've worked on over 50 laptops hardware before so I am at odds with this. I even tried removing the keyboard as it says by applying pressure with the screw driver where the keyboard screw is to see and it did not work either.

**Comment by leviport** [comment]
Is this a 17" gaze15? The bottom panel on that machine just hangs on super tight and is a pain to get off. I had the best luck with one of those little plastic prying tools starting at each of the hinges. This is the sort of tool I mean: 
![PRY_TOOLS-2](https://user-images.githubusercontent.com/13512097/107585513-9fdc3f80-6bbb-11eb-8f7b-cb123196afc3.jpg)

Regarding the screws, the picture in the tech-docs might be a little out of date, but you're just removing every screw you see on the back panel. There aren't any screws under the keyboard on this model that hold the bottom panel on.

**Comment by evilthreads669966** [comment]
@leviport yeah I tried a butter knife but I'm about to go to the hardware store for some non magnetic tools. I'm gonna look around for something like that. I appreciate that. I didn't want to damage it because I started scuffing the cover pretty noticeably with my nails. But I mean how durable is the cover? I don't want to crack it.

**Comment by evilthreads669966** [comment]
@leviport  anyways thank you for the super fast support. I really appreciate it.

**Comment by leviport** [comment]
>But I mean how durable is the cover?

It's pretty durable as long as you work your way around the edges a little at a time. Getting the first edge separated is definitely the hardest part. Let me know if it keeps giving you trouble.

**Comment by jacobgkau** [comment]
> Okay because the instructions said start at the front and work towards the hinges.

For what it's worth, that's just a guideline (which has been reversed for newer service manuals.) I personally find it easier to start at the hinges and battery slot with gaze15 (although it's still tough due to how closely it attaches.)

> The instructions on system76 claim a certain number of screws but I have one less.

I do want to ask again, is this a 15" or 17" Gazelle? I know the number listed in the tech docs should be correct for the 17" model, I'm confirming about the 15" with someone who has access to that one but would want to add a note about it if it actually has less screws. Which screw is the one that you don't have? https://tech-docs.system76.com/models/gaze15/img/bottom-panel-screws.jpg (I was just taking the 17" model apart yesterday, and I nearly forgot to remove the third under-battery screw right next to the contacts.)

**Comment by jacobgkau** [comment]
I did just confirm with a colleague that the 15" version of the gaze15 has 17 screws, the same number as the 17" version. We list 17 screws in the tech docs here: https://tech-docs.system76.com/models/gaze15/repairs.html 

@evilthreads669966 Was that the page you were looking at for the screw count, or was it a different page? How many screws do you have?

(For future reference, a [support ticket](https://support.system76.com/) is the best place for questions like this, or confirmed issues with the tech docs can be filed in the [tech-docs repo](https://github.com/system76/tech-docs), but we're happy to help out in any case.)

**Comment by evilthreads669966** [comment]
I''m not sure. However, I did find a pryer for automotive mirrors that worked great. Similar to what you had. I really appreciate the support. I installed it no problem and have a windows boot now. Thanks.

**Comment by evilthreads669966** [comment]
I will recount the screws in the morning and will file the issue there if I find that it does not match the docs for fun.
