### ISSUE TITLE
Alienware Aurora R7 suspend and start-up issues

### ISSUE THREAD

**Issue by Metaph413** [pop-os/pop#1539]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

I use Pop on an Alienware Aurora R7. Sometimes when I suspend the rig, it hangs, which means the side lights don't turn off (when they do, it signifies the computer sleeps) and it is on a black screen that interaction with a keyboard and mouse can't get rid of. A hard restart is the only way to restore the computer back to normal.

But when I restart, the mouse glitches. Last time I did it, the mouse moved left uncontrollably until I unplugged it and plugged it in again. EDIT: I had this happen to me on February 12th, and the mouse stuck itself near the upper right corner of the password screen. I could drag it away, but it always came back, until I unplugged and plugged it back in.

**Steps to reproduce (if you know):**
Suspend the computer.
Restart it by pushing the power button.

**Expected behavior:**
For the computer to suspend normally, the side lights to turn off, and the mouse to act normally after restarts.

**Other Notes:**
I recommend you add notes about Alienware support to the support documentation. I previously had to add "initcall_blacklist=dw_i2c_init_driver" (I believe using sudo kernelstub -a "initcall_blacklist=dw_i2c_init_driver") to the Kernelstub configuration file to get my computer to shut down without requiring the power button.

**Comment by bflanagin** [comment]
@Metaph413 Thanks for the report. However, this fix would be better served upstream in Ubuntu. That way the fix replicates down to all the distributions that use Ubuntu as a base. Its also worth noting that Dell may also be willing to add this to they're stack as they contribute to the Linux community as well. Either way, its not something we handle.
