### ISSUE TITLE
battery drains after laptop is shutdown in pop os 20.04

### ISSUE THREAD

**Issue by ShashankArora92** [pop-os/pop#1542]
Hello,
I am using an HP laptop and I have recently noticed that my laptop is draining battery after it is shutdown. I have installed tlp and disabled the wake-on-lan option but of no use.
Any help I can get.
Thank You

**Comment by bflanagin** [comment]
Unfortunately @ShashankArora92 this isn't something that we handle here on our github page. For two reasons:

1. Your HP laptop isn't created or distributed by System76 which means all drivers and the like are handled by HP or another party.
2. If you are sure the laptop is Shutdown then this is a hardware only issue and should be taken up with HP.

https://support.hp.com/
