### ISSUE TITLE
Dell Inspiron 15 7567 gaming having trouble with Pop_OS! 20.04

### ISSUE THREAD

**Issue by BlackOutedMind** [pop-os/pop#1547]
-->

**Distribution (run `cat /etc/os-release`):**
Can't...

**Issue/Bug Description:**
So i had this system with linux for one week straight until it died. Nvidia drivers weren't loading any more, i was stuck on live boot and if i installed it would not start with nvidia, it worked one or 2 times in the new installation and the old was freezing.
I don't know if its a hardware issue or its just really a combination of events to make me think its a hardware issue.
one part of the keyboard just gets hot (fans work and no heavy processing, its just working).
Freezes were very common on the first installation. During a normal gameplay the Laptop froze and nothing worked. Pop Os wont boot on live usb. X just died after the freeze and nvidia is not recognized in the newest installation. Tried every driver and installed ubuntu but no difference.
Windows i installed to try games and it BSOD in 5 minutes of the os running, but this is normal for windows(JK)
If you need more info im here, i hope someone can help.

**Steps to reproduce:**
Have a Dell Inspiron 15 7567 gaming and try to install Pop os or any linux distro and install nvidia drivers.

**Expected behavior:**
Be able to run Pop Os on live usb and nvidia run just fine.

**Other Notes:**

**Comment by leviport** [comment]
If two different OSes are freezing up and giving you trouble, I'd be very suspicious of some kind of hardware failure. As such, I don't believe this is related to Pop!_OS. If you find information in the future that contradicts my assumption, please let me know and I can reopen this issue.
