### ISSUE TITLE
System sound cause ringing noise on the right ear of bluetooth headphones.

### ISSUE THREAD

**Issue by kevinwish** [pop-os/pop#1565]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
bluetooth:
  Installed: (none)
  Candidate: 5.55-0ubuntu1.1
  Version table:
     5.55-0ubuntu1.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages
     5.55-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
**Issue/Bug Description:**
Using Bluetooth headphones, the right ear of the headphone ringing from system sound.

**Steps to reproduce (if you know):**
1. After connected to a Bluetooth headphone that supports stereo, turn the headphone's value to the maximum from the headphone's media keys. 
2. Turn System Sound and System volume to at least 70%
3. Open to Pop!_Shop, click on the search bar and repeat hitting the backspace key.
4. You find your right ear hear the ring/noise when hitting the backspace key

**Expected behavior:**
System sound should not cause unwanted noise when hitting backspace keys.

**Other Notes:**
Tested with 2 different brands of Bluetooth headphones.

System-info:
inxi -Fxz
System:
  Kernel: 5.8.0-7642-generic x86_64 bits: 64 compiler: gcc v: 10.2.0 
  Desktop: N/A Distro: Pop!_OS 20.10 base: Ubuntu 20.10 Groovy 
Machine:
  Type: Laptop System: LENOVO product: 20BHS08H08 v: ThinkPad W541 
  serial: <filter> 
  Mobo: LENOVO model: 20BHS08H08 v: NO DPK serial: <filter> UEFI: LENOVO 
  v: GNET72WW (2.20 ) date: 02/26/2015 
Battery:
  ID-1: BAT0 charge: 55.3 Wh condition: 70.1/99.5 Wh (71%) 
  model: SANYO 45N1779 status: Unknown 
  Device-1: hidpp_battery_0 model: Logitech M305 
  charge: 55% (should be ignored) status: Discharging 
  Device-2: hidpp_battery_1 model: Logitech K520 
  charge: 70% (should be ignored) status: Discharging 
CPU:
  Info: Quad Core model: Intel Core i7-4800MQ bits: 64 type: MT MCP 
  arch: Haswell rev: 3 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx 
  bogomips: 43103 
  Speed: 898 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 934 2: 904 
  3: 900 4: 1060 5: 1087 6: 903 7: 978 8: 910 
Graphics:
  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: Lenovo 
  driver: i915 v: kernel bus ID: 00:02.0 
  Device-2: NVIDIA GK106GLM [Quadro K2100M] vendor: Lenovo driver: nvidia 
  v: 460.39 bus ID: 01:00.0 
  Device-3: Acer Integrated Camera type: USB driver: uvcvideo bus ID: 2-12:6 
  Display: x11 server: X.Org 1.20.9 driver: modesetting,nvidia 
  unloaded: fbdev,nouveau,vesa resolution: 1920x1080~60Hz 
  OpenGL: renderer: Quadro K2100M/PCIe/SSE2 v: 4.6.0 NVIDIA 460.39 
  direct render: Yes 
Audio:
  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio 
  vendor: Lenovo driver: snd_hda_intel v: kernel bus ID: 00:03.0 
  Device-2: Intel 8 Series/C220 Series High Definition Audio vendor: Lenovo 
  driver: snd_hda_intel v: kernel bus ID: 00:1b.0 
  Device-3: NVIDIA GK106 HDMI Audio vendor: Lenovo driver: snd_hda_intel 
  v: kernel bus ID: 01:00.1 
  Device-4: GYROCOM C&C Fiio E10 type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 2-2:2 
  Sound Server: ALSA v: k5.8.0-7642-generic 
Network:
  Device-1: Intel Ethernet I217-LM vendor: Lenovo driver: e1000e v: 3.2.6-k 
  port: 5080 bus ID: 00:19.0 
  IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: <filter> 
  Device-2: Intel Wireless 7260 driver: iwlwifi v: kernel port: 4000 
  bus ID: 03:00.0 
  IF: wlp3s0 state: down mac: <filter> 
Drives:
  Local Storage: total: 2.74 TiB used: 1.58 TiB (57.6%) 
  ID-1: /dev/sda vendor: Samsung model: SSD 860 EVO 500GB size: 465.76 GiB 
  ID-2: /dev/sdb model: NT-512 size: 476.94 GiB temp: 30 C 
  ID-3: /dev/sdc type: USB vendor: Toshiba model: MQ04UBD200 size: 1.82 TiB 
Partition:
  ID-1: / size: 48.96 GiB used: 6.96 GiB (14.2%) fs: ext4 dev: /dev/sdb3 
  ID-2: /home size: 376.64 GiB used: 10.85 GiB (2.9%) fs: ext4 
  dev: /dev/sdb4 
Swap:
  ID-1: swap-1 type: partition size: 38.79 GiB used: 0 KiB (0.0%) 
  dev: /dev/dm-0 
Sensors:
  System Temperatures: cpu: 53.0 C mobo: 0.0 C gpu: nvidia temp: 45 C 
  Fan Speeds (RPM): cpu: 2325 
Info:
  Processes: 328 Uptime: 1h 16m Memory: 31.24 GiB used: 4.73 GiB (15.2%) 
  Init: systemd runlevel: 5 Compilers: gcc: 10.2.0 Packages: 1927 
  Shell: Bash v: 5.0.17 inxi: 3.1.07

**Comment by bflanagin** [comment]
After doing some research, it seems to be an issue with the headsets internals and not the device its connected to. When the headset is set to maximum volume the internal amplifier  it can cause a small squeal usually imperceptible to  the wearer. It seems that the tone used as our alert sound triggers the squeal to become more noticeable, but regardless to this finding the best course of action is to turn down the headphones to the volume that the squeal is no longer audible and use the systems audio system to control the volume.

If you want to find out more about the issue a simple search engine query "squeal [or noise  ]  bluetooth headset" will give you plenty to results.

**Comment by kevinwish** [comment]
Thank you for the comment and solutions, I will close this issue.
