### ISSUE TITLE
Install/Upgrade VSCode getting wrong version

### ISSUE THREAD

**Issue by AlefCS** [pop-os/pop#1568]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os 

``` 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
code:
  Instalado: 1.54.1-1614898113
  Candidato: 1.53.2~pop1~1613505423~20.04~6168708
  Tabela de versão:
 *** 1.54.1-1614898113 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
        100 /var/lib/dpkg/status
     1.54.0-1614738538 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.53.2-1613044664 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.53.2~pop1~1613505423~20.04~6168708 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
     1.53.1-1612827767 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.53.0-1612368357 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.52.1-1608136922 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.52.0-1607640828 500
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
     1.51.1-1605051630 500
        500 http://apt.pop-os.org/proprietary focal/main amd64 Packages
        500 http://packages.microsoft.com/repos/code stable/main amd64 Packages
```

**Issue/Bug Description:**
PopOS VSCode's candidate for new version is 1.53.2 but I'm already at 1.54.1 (most recent one).

**Steps to reproduce (if you know):**
1. Run `apt policy code`
2. See that candidate's version is not the newer one.
3. Try to install/upgrade running `apt install code` or via Pop!_Shop
4. Run `apt policy code`
5. See that it actually install version 1.53.2

**Expected behavior:**
Candidate's version should be the newer (1.54.1).

**Other notes:**
To get the correct new version, I had to run `apt install code=1.54.1-1614898113`

**Comment by bflanagin** [comment]
This is usually caused when the repository with the newer version is set to a lower priority than the repository they system is trying to install from.  If you want to be sure that you are always getting the newest version from Microsoft you can pin that repo with a higher priority than the one we supply. Using the steps detailed in the link below.

https://wiki.debian.org/AptConfiguration

**Comment by mmstick** [comment]
Pop's PPA always has highest priority by default. There's no need to add Microsoft's PPA for VS Code since we update it as they do.
