### ISSUE TITLE
Pop! Shop notifications bug.

### ISSUE THREAD

**Issue by ModcoLocko** [pop-os/pop#1571]
Pop-OS 20.04 LTS

Pop! Shop has notifications and has a "2" by the installed button, but clicking their has no applications that need updating or any actions

There shouldn't be a notification their, running sudo apt update says all packages are up to date.

![image](https://user-images.githubusercontent.com/69701885/110222897-c3856380-7ea3-11eb-8693-2b49075154fd.png)

**Comment by bflanagin** [comment]
Thank you for your report. We are aware of the issue and the up stream developers, along with our team are working on a fix. 

For the time being run these commands from the terminal [super(win)+T] in this order:

1. `sudo flatpak update`

2. `flatpak update` (without sudo this time)

3. `sudo apt update`

4. `sudo apt upgrade`

This should get rid of the indicator. Given that this is a duplicate ticket, for a known issue it will be closed.
