### ISSUE TITLE
Weather not displaying properly in Pop!_OS notification tray

### ISSUE THREAD

**Issue by barthvader13** [pop-os/pop#1577]
I opened this ticket after I found [this reddit thread](https://www.reddit.com/r/pop_os/comments/lzcnai/weather_not_showing_in_the_notification_tray_2021/) describing the same issue. It may be related to [this old issue](https://github.com/pop-os/pop/issues/126)?

I also tried changing the auto location setting and that did not work.

![image](https://user-images.githubusercontent.com/5341581/110676309-6f2afe00-8199-11eb-828a-866b1110cff3.png)

**Distribution (run `cat /etc/os-release`):**
`NAME="Pop!_OS"`
`VERSION="20.10"`
`ID=pop`
`ID_LIKE="ubuntu debian"`
`PRETTY_NAME="Pop!_OS 20.10"`
`VERSION_ID="20.10"`
`HOME_URL="https://pop.system76.com"`
`SUPPORT_URL="https://support.system76.com"`
`BUG_REPORT_URL="https://github.com/pop-os/pop/issues"`
`PRIVACY_POLICY_URL="https://system76.com/privacy"`
`VERSION_CODENAME=groovy`
`UBUNTU_CODENAME=groovy`
`LOGO=distributor-logo-pop-os`
 
 

**Issue/Bug Description:**
Pop!_OS does not display the weather information correctly inside of the notification tray

**Expected behavior:**
Weather should display correctly inside of the notification tray

**Comment by bflanagin** [comment]
Seems to be an issue with where gnome-weather gets its information 

From gnome-weather:

```
Failed to get Yr.no forecast data: 404 Not Found
```

**Comment by ids1024** [comment]
Related upstream issue: https://gitlab.gnome.org/GNOME/gnome-weather/-/issues/154

**Comment by jacobgkau** [comment]
This has been fixed upstream in GNOME (versions 40.0 and 3.36.2), and Debian has backported the fix in unstable (version 3.36.1-3), but the fix has not made its way down to Ubuntu yet: https://github.com/pop-os/pop/issues/126#issuecomment-827138186

**Comment by llsaboya** [comment]
Works like a charm. Thank you. It's fixed in Gnome 40 and Fedora, but POP OS is my daily driver.
