### ISSUE TITLE
starting gnome fails after update linux-image-4.13-37-generic

### ISSUE THREAD

**Issue by estokes** [pop-os/pop#158]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**

On galago3, screen blinks a couple of times after successfull gdm login and then goes straight back to gdm when gnome desktop is selected. Fluxbox works fine, I think because I'm not using hidpi with it.

**Steps to reproduce (if you know)**

log in

**Expected behavior**

gnome should start

**Other Notes**

a couple of suspicious lines from Xorg log,
[   327.233] (WW) xf86CloseConsole: KDSETMODE failed: Input/output error
[   327.233] (WW) xf86CloseConsole: VT_GETMODE failed: Input/output error
[   327.233] (WW) xf86CloseConsole: VT_ACTIVATE failed: Input/output error
[   327.281] (II) Server terminated successfully (0). Closing log file.

**Comment by djordan2** [comment]
Please run updates (via VT if needed) and see if the issue is resolved.  This sounds like an issue that was briefly in the system76 driver.  If it is, an update should fix the issue.

**Comment by brs17** [comment]
@estokes, thanks for submitting the issue. 
This sounds similar to an issue we dealt with last week (and fixed in the latest version of the HiDPI daemon). Have you tried/could you try updating your machine and letting us know if the issue persists?

**Comment by estokes** [comment]
I confirm this issue is fixed on my machine after the latest update
