### ISSUE TITLE
Laptop getting put to sleep when trying to log in for 2nd time

### ISSUE THREAD

**Issue by coops8D** [pop-os/pop#1586]
**Distribution:**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
When I boot up from power off and login everything is good. But after first login if I close the laptop lid and then open and log back in it will work for about 20 seconds then screen goes black and I am pretty sure laptop goes back to sleep and It just keeps going in that loop until I do a hard reset. The other odd thing is this problem does not seem to happen if I click 'Suspend'  before closing the laptop lid

I did a complete fresh re install and still have the issue. Also did update and upgrade so everything should be upto date 

**Steps to reproduce (if you know):**
Turn laptop on, login then close lid and log back in

**Expected behavior:**
Should keep me logged in

**Other Notes:**
I did a full fresh install
Ran update and upgrade
Tried it on GPU, Hybrid and Integrated graphics

**Comment by leviport** [comment]
Thanks for the report! Could you clarify the sequence of events needed to produce this behavior a bit more? How much time do you wait after the first login after the cold boot before you close the lid, then how long are you leaving the machine suspended for before opening the lid again? Is any of this done with an external monitor connected? 

Or am I misunderstanding this completely and you don't want to see the lock screen after resuming from suspend? If that's the case, try turning off this setting (Settings > Privacy > Screen Lock > Lock Screen On Suspend): 
![2021-03-17_07-43](https://user-images.githubusercontent.com/13512097/111477315-9a12d600-86f4-11eb-865f-4075798a3a78.png)

**Comment by coops8D** [comment]
You are pretty bang on, after cold boot it runs fine so I'm using prob for few hours +

I did the option to have no lock screen but it still does same behaviour just now going to the desktop then 20 or so seconds suspended.

Would it help if I film a video of the issue?

**Comment by leviport** [comment]
Yeah that might help. If you could also describe your laptop, it might also help if we knew a bit more about your hardware.

**Comment by coops8D** [comment]
Sure I'll make one now.
Laptop is 2019 razer blade 15inch

**Comment by coops8D** [comment]
https://vimeo.com/525242617

Here you go. If need more let me know

**Comment by coops8D** [comment]
![IMG_20210318_112243_1](https://user-images.githubusercontent.com/80822216/111555414-77f48300-87dc-11eb-9f14-4981d4a025bf.jpg)
 This also pops up when it gets suspended, not sure if anything of value there

**Comment by coops8D** [comment]
Another thing as well to add that might help. Looked at the logs and there is heaps of these similar errors

"Mar 18 15:36:38 pop-os systemd[1448]: Not generating service for XDG autostart app-org.gnome.SettingsDaemon.Rfkill-autostart.service, startup phases are not supported."

**Comment by leviport** [comment]
Well that's strange. The only way to get it out of that cycle is to reboot, correct? Have you been able to replicate this behavior on either a Pop!_OS live disk, or perhaps an Ubuntu live disk?

**Comment by coops8D** [comment]
Yeah hard reset, and no only just started using Linux this week with Pop OS so have not really used say other ones.

**Comment by leviport** [comment]
Well I definitely think it's worth trying a couple live disks, especially Ubuntu and Pop!_OS. No need to fully install the OS, just boot into the live environment and see if the same behavior happens. That way we can narrow down whether it's also upstream, just Pop, or even just a bug in your specific configuration.

**Comment by coops8D** [comment]
So by this you mean have it on USB and boot from that? Or what would be best way?

**Comment by leviport** [comment]
Yep, just burn an ISO onto a USB and boot to it, just don't proceed through the installer after booting. This article covers how to make a live disk in Pop: https://support.system76.com/articles/pop-live-disk/ .

**Comment by coops8D** [comment]
Ok, so just did it and same thing with Ubuntu...
I also checked on the Windows 10 partition and that works fine. Seems to be just not ment to use Linux on this laptop :/

**Comment by coops8D** [comment]
Fixed it! :D
Apparently it is a problem with Razer laptops and doing "bash sudo kernelstub -a "button.lid_init_state=open" " will fix the issue! 

Thanks for the help though, appreciate it and hopefully if someone else comes across this problem in the future this solution will help you and save you wasting hours trying to fix it.

**Comment by leviport** [comment]
Awesome, thanks for sharing the solution! I'm going to close this issue since you found a fix, but I'll keep a link handy in case I see anyone else run into the same thing. Razer hardware seems pretty popular, so I'm sure it'll help other people somewhere along the line.
