### ISSUE TITLE
Graphic artifacts waking from suspend

### ISSUE THREAD

**Issue by egruber** [pop-os/pop#1587]
**Distribution (run `cat /etc/os-release`):**
```NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
**Issue/Bug Description:**
When restarting from a suspended state, there is constant screen tearing, graphical artifacts, and sections of the display not showing. This occurs when leveraging either integrated graphics or NVIDIA graphics in a Balanced power mode.

**Steps to reproduce (if you know):**
1. Log into machine.
2. Select system menu 
3. Select "Power Off/Log out"
4. Select "Suspend"
5. Wait approximately ten seconds
6. Press Enter to wake machine

**Expected behavior:**
Artifact free login screen displays.
Logging in has no graphical artifacts

**Other Notes:**
When booting fresh, there are no issues. And continuous use will generate no graphical issues. After the first suspend graphical issues will begin and not stop. 
Suspending again, and attempting to log in again will not resolve the issue.

**Comment by bflanagin** [comment]
Ah yes, the integrated graphics corruption bug. We have a few threads on the topic. We'll need a little more information about your hardware to sort you into the right group. However, this issue is upstream in the integrated graphics driver and or Xorg. For our records respond with the outputs from these programs:

`lspci | grep VGA`

and

`lsmod | grep video`

and if you could give us your computers make and model (or motherboard model if its DIY)

**Comment by egruber** [comment]
```lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation UHD Graphics (rev 05)
01:00.0 VGA compatible controller: NVIDIA Corporation Device 2520 (rev a1)
egruber@pop-os:~$ ^C
```
And:
```
lsmod | grep video
uvcvideo               98304  0
videobuf2_vmalloc      20480  1 uvcvideo
videobuf2_memops       20480  1 videobuf2_vmalloc
videobuf2_v4l2         28672  1 uvcvideo
videobuf2_common       53248  2 videobuf2_v4l2,uvcvideo
videodev              245760  3 videobuf2_v4l2,uvcvideo,videobuf2_common
mc                     57344  5 videodev,snd_usb_audio,videobuf2_v4l2,uvcvideo,videobuf2_common
video                  49152  1 i915
```
As for make and model, I'm using a System76 Oryx Pro 15"

Definitely appreciate the direction toward the chat section. I figured this was some form of typical behavior, but I thought it would be best to report out here regardless, as I'm not entirely sure what Pop_OS pulls directly, or has modified before distribution. Thanks again!

**Comment by bflanagin** [comment]
@egruber Ah, well if you're running official System76 hardware you can ask our official support channels. They do a good job. Also, we just updated the Kernel and mesa. It may not fix the issue, but if its working better we'd like to know.

**Comment by mtimofiiv** [comment]
I'm having the same issue on a Gazelle. Latest kernel and mesa versions.

This all seemed to start with installing the latest NVIDIA drivers, before that I did not notice any problem like this.
