### ISSUE TITLE
Screen blink after 5 mins of sleep mode.

### ISSUE THREAD

**Issue by priyaanyadav99** [pop-os/pop#1589]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Using Pop os on Asus Tuf laptop. After some time when wake up from sleep mode screen starts blinking. It gets stops when I reboot the system.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
Hmm, that sounds kinda [familiar](https://github.com/pop-os/pop/issues/1586)... Can you try booting with the kernel parameter `button.lid_init_state=open` and seeing if that helps? 

If it does, you can add it permanently with `sudo kernelstub -a button.lid_init_state=open`
