### ISSUE TITLE
Hiri snap doesn't launch

### ISSUE THREAD

**Issue by dhitchcock** [pop-os/pop#159]
**Reporter info**

```
 * Distribution - 
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version
hiri (snap) 1.3.6.1 rev 42
```

**Issue/Bug Description**
After installing the hiri snap, it fails to launch with the error 
`Permission denied: '/etc/os-release'`

That seems like it'd be obvious to fix, but the permissions are 644 on the file that is linked to.  So the only difference is in ubuntu this is a link to ../usr/lib/os-release, while in pop it's a link to /etc/popos/os-release, perhaps the difference is because where confined snaps have access to?

**Steps to reproduce (if you know)**
snap install hiri
snap run hiri

**Expected behavior**
hiri starts

**Other Notes**
I contacted hiri support first a few weeks ago and they ignored me, so I was hoping you might fix it on your end.  It's actually easy for me to workaround, I can rm /etc/os-release link and copy the real file in pop-os/etc-release to /etc, and then it works, but wanted to improve out of box experience and not cause any update breakage.

**Comment by brs17** [comment]
@dhitchcock, thanks for submitting this issue. It seems odd that a snap should care what is contents of `/etc/os-release`. Regardless, the file is set to be readable by all so this definitely seems to be an issue with the hiri snap itself.

Perhaps jumping in to the [Pop!_OS chat](chat.pop-os.org) channel on mattermost and asking around you may find someone who has had the same issue (and solved it).

**Comment by dpowert2** [comment]
Hi there - I'm one of the founders of Hiri. If you are still experiencing this issue please let me know - dave [@] hiri [dot] com

**Comment by Matakaheru** [comment]
![hiri_error](https://user-images.githubusercontent.com/16819390/38316418-b8292fac-37f8-11e8-90b9-c68aca415903.png)
Can confirm the error lies in the Python scripts Hiri is using. Install from snap and run as expected and you get the error message that /etc/os-release is permission denied. This is due to the script not being able to follow the symlink.

![hiri_test](https://user-images.githubusercontent.com/16819390/38316487-dd425138-37f8-11e8-8aa1-7d7d5ac0d0db.png)
Removing the symlink and placing os-release in the expected location allows Hiri to run.

![hiri_run](https://user-images.githubusercontent.com/16819390/38316548-f9d01a4c-37f8-11e8-9b94-9a5f90267748.png)

**Comment by rdegges** [comment]
I'm also having the exact same issue as above, and can confirm the same behavior. I just purchased hiri for use on my work stuff after getting it working on my laptop (which runs ubuntu budgie), but on pop os! it won't launch =/

**Comment by hunnsdon** [comment]
Using pop-os, this fix works for me.

**Comment by mmstick** [comment]
@hunnsdon It still requires the workaround to launch?

**Comment by hunnsdon** [comment]
Yes that is correct. I have contacted the creator of Hiri and they (he) is working on Gmail integration at present. He advised me that Linux is the next focus for better integration

> Not yet, but as soon as we get Gmail out of the way we intend to add more Linux support.

So crossed fingers because the only other Linux Email app I like is Mailspring but I find it buggy, so I use but won't pay for it. Hiri looks very promising, so far so good!

**Comment by rsmithlal** [comment]
@Matakaheru thanks a lot! I was having this problem with another snap package (Gitkraken) and your solution solved the problem for me as well!

**Comment by 8bg** [comment]
Will removing the symlink and copying the release file cause future problems with Pop upgrades? Wondering if it's better just to do manual tarball install for now.

**Comment by leonallen22** [comment]
I have the same concern as 8bg - any guidance on this?

**Comment by colinodell** [comment]
I also have this issue. @brs17 is there a reason `/etc/os-release` needs to be a symlink? Will the workaround proposed in this thread cause any future issues?

**Comment by brs17** [comment]
I believe the symlink is created when the default settings for Pop!_OS are being set here: https://github.com/pop-os/default-settings . Specifically setting the `NAME` and `PRETTY_NAME`: https://github.com/pop-os/default-settings/blob/master_disco/src/os-release.sh

I'm not sure specifically, but I would imagine a number of things may look at `/etc/os-release` and do specific things when the os is listed as Pop!_OS. 

Read permissions look like they should be permitted from `/etc/pop-os/os-release` why is writing/executing of that file being attempted?

**Comment by Obiken** [comment]
Seeing this issue with the Gitkraken snap which yields this when trying to start from cli:
`
> snap run gitkraken
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
state:  update-not-available
cat: /etc/os-release: Permission denied
> ls -lh /etc/os-release
lrwxrwxrwx 1 root root 17 Jul  9 16:14 /etc/os-release -> pop-os/os-release
`
Their .deb file installs fine, and application runs from that. So seems to be something specific to how their Snap is unable to follow the symlink.

Have reported it to Gitkraken.

**Comment by zeronet-work** [comment]
> ![hiri_error](https://user-images.githubusercontent.com/16819390/38316418-b8292fac-37f8-11e8-90b9-c68aca415903.png)
> Can confirm the error lies in the Python scripts Hiri is using. Install from snap and run as expected and you get the error message that /etc/os-release is permission denied. This is due to the script not being able to follow the symlink.
> 
> ![hiri_test](https://user-images.githubusercontent.com/16819390/38316487-dd425138-37f8-11e8-8aa1-7d7d5ac0d0db.png)
> Removing the symlink and placing os-release in the expected location allows Hiri to run.
> 
> ![hiri_run](https://user-images.githubusercontent.com/16819390/38316548-f9d01a4c-37f8-11e8-9b94-9a5f90267748.png)

Above fix is working in Pop!_OS 19.04

**Comment by andreoua** [comment]
A better approach might be to create a hard link instead. This will ensure that any update or modification to the original file will carry over to the linked one.
```sudo ln /etc/pop-os/os-release /etc/os-release```

**Comment by 8bg** [comment]
Side note: appears that Hiri is a dead project. No site/blog/Twitter updates for 6+ months. No response to support requests/inquiries I've made.

**Comment by cryos** [comment]
Yeah, this is still an issue and it looks like no updates for quite a while. I was able to workaround the issue with a hard link.
