### ISSUE TITLE
dual monitors wake intermittently during power saving inactivity

### ISSUE THREAD

**Issue by m-crabtree** [pop-os/pop#1590]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
1. 2x external DP monitors wake from sleep shortly after monitor power saving mode is enabled,
2. an inconsistent amount of time passes, though usually between 45-60 seconds
3. both monitors wake from sleep, enter  "scanning for signal" mode at the same time,
4. no signal is found, monitors both go back into power saving mode at the same time
5. repeat 2-5

**Steps to reproduce (if you know):**
- configure displays to power off after one minute
- wait

**Expected behavior:**
- monitors should stay off until someone interacts physically with the computer

**Other Notes:**
- the few times i've run `# journalctl > output.txt` shortly after step 3 the following lines are almost always present

`# tail output.txt`
```
Mar 20 20:51:17 pop fwupd[2341]: 20:51:17:0410 FuEngine             thunderbolt failed to change udev device /sys/devices/pci0000:00/0000:00:03.1/0000:2d:00.0/drm/card0: cannot ensure ID: FuUdevDevice:
Mar 20 20:51:17 pop fwupd[2341]: Unknown Device
Mar 20 20:51:17 pop fwupd[2341]:   Flags:                none
```
- the issue does _not_ persist on a windows 10 install on an alternate boot drive

thanks!

**Comment by bflanagin** [comment]
I'll have to pass this off to someone with multiple monitors but two questions before we move on.

1. Does the pattern repeat after the initial "scanning for signal" or do the monitors go to sleep for good after the first round?
2. Is your computer set to blank the screen at one point, and then go to sleep at another? (Could be the computer sending a signal to the DP ports right before going into suspend)

**Comment by bflanagin** [comment]
Mind giving us a little more info? 

1. GPU (Make,Model,Driver) 
2. Your power settings, primarily your screen blanking and sleep settings.
