### ISSUE TITLE
changing hostname via GUI does not respect uppercase

### ISSUE THREAD

**Issue by crysman** [pop-os/pop#1591]
**Distribution (run `cat /etc/os-release`):**
```NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```$ apt policy gnome-shell
gnome-shell:
  Installed: 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0
  Candidate: 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0
  Version table:
 *** 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.38.2-1ubuntu1~20.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages

```

**Issue/Bug Description:**

1. Changing hostname via standard GUI Settings makes it lowercase, which forces you to change it manually via editing /etc/...
2. /etc/hosts is not being updated at all

**Steps to reproduce (if you know):**

1. change hostname via `settings -> about -> device name` to UPPERCASE_HOSTNAME
2. check hostname via `hostnamectl` - it is lowercase
3. check /etc/hosts - not updated at all

**Expected behavior:**

1. No case changes at all.
2. /etc/hosts updated properly

**Other Notes:**

**Comment by bflanagin** [comment]
So there are really two parts to this issue:
1. Hostnames are made lowercase
2. /etc/hosts isn't updated.

For the first issue, nothing will be done. The standard naming convention for host names is for them to be lower case. You are seeing the host name properly formatted, it may not be what you would like, but it is correct.  

As far as etc/hosts is concerned systemd moves the localhost name to a file called `hostname` and found in `/etc/`. Neither systemd nor hostnamectl reference /etc/hosts they don't make changes to it either. 

Its worth noting that /etc/hosts is still a viable file and can be used for other purposes, but it seems to be obsolete when it comes to controlling localhost names.

**Comment by crysman** [comment]
OK, have not known about the convention. Anyways, @bflanagin, if it makes it lowercase, so be it, BUT... then it should notify the user about the change, IMHO. I do not like when applications change my input without having me notified - this is not transparent behavior. Or it might be as a small "hint" text nearby... or just something... don't you think?

**Comment by jacobgkau** [comment]
> Its worth noting that /etc/hosts is still a viable file and can be used for other purposes, but it seems to be obsolete when it comes to controlling localhost names.

I would not say `/etc/hosts` is "obsolete." Without the hostname present in that file, applications won't be able to resolve the hostname, which can lead to problems. However, there is already an issue open about that here: https://github.com/pop-os/systemd/issues/5 

@crysman Does this issue also occur on Ubuntu, Fedora, or other distributions shipping GNOME? If so, it would make more sense to report it upstream: https://gitlab.gnome.org/GNOME/gnome-control-center/
