### ISSUE TITLE
Czech formats missing in Region & Language settings

### ISSUE THREAD

**Issue by crysman** [pop-os/pop#1592]
**Distribution (run `cat /etc/os-release`):**
```NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```$ apt policy gnome-shell
gnome-shell:
  Installed: 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0
  Candidate: 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0
  Version table:
 *** 3.38.3-2ubuntu0.20.10.2pop1~1614116211~20.10~0176ca0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.38.2-1ubuntu1~20.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages

```

**Issue/Bug Description:**

Czech formats missing in Region & Language settings:

![image](https://user-images.githubusercontent.com/5269350/111905438-ed19bf80-8a4b-11eb-8758-c1daa0cbe9f9.png)

**Steps to reproduce (if you know):**

Settings -> Region & Language -> Formats ...

**Expected behavior:**

Czech formats are available

**Other Notes:**

**Comment by crysman** [comment]
Until it gets fixed, what is the workaround, please? I have all wrong: paper size, time and date format, measurement units... :( Thanks!

**Comment by ids1024** [comment]
Looks like the `language-pack-gnome-cs` package is required.

There's a button in the region panel called "Manage Installed Languages" to help with installing such packages. (That's added by a patch from Ubuntu; I believe upstream Gnome has general plans to better integrate that support.)

**Comment by crysman** [comment]
@ids1024 this has, indeed, helped, thanks!
