### ISSUE TITLE
Can't install pop!_OS. Installer app is not starting

### ISSUE THREAD

**Issue by lemurweb-dev** [pop-os/pop#1596]
**Distribution (run `cat /etc/os-release`):**
 
 pop!_OS 20.04 and 20.10 (live USB)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Install pop!_OS

**Issue/Bug Description:**

When running pop!_OS live USB, the "install pop!_OS" application does not start. When launched, it is displayed on the top bar with a loading spinner on the right but after 10 seconds it disappears and nothing happens.
Tested with different live USBs (20.04 nvidia, 20.10 standard, 20.10 nvidia).

**Steps to reproduce (if you know):**

Just run install application when live booting

**Expected behavior:**

Installer starts

**Other Notes:**

Currently i have a dual-boot setup with windows10 and elementaryOS. I want to install pop!_OS over elementaryOS

**Comment by bflanagin** [comment]
@lemurweb-dev: Odd, as you can imagine we haven't seen this yet in our tests. Have you done any image verification tests on the images you downloaded?

**Comment by lemurweb-dev** [comment]
Yes i checked the SHA256 sum.
Is there a way to launch the application from terminal that can output the error?

**Comment by bflanagin** [comment]
Yes, you should be able to launch it using this command:
`io.elementary.installer`

**Comment by lemurweb-dev** [comment]
After mounting the second HDD, the installer launched...
Can't really understand what was going on, but it's working now. I could install pop_OS! without issues.
Thanks for support!
