### ISSUE TITLE
Bluetooth media controls not working

### ISSUE THREAD

**Issue by RPGHank** [pop-os/pop#1598]
**Distribution**

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version**

Not sure

**Issue/Bug Description:**

Unable to use Bluetooth speaker built-in media controls to pause and skip songs

**Steps to reproduce (if you know):**

- Connect to a Bluetooth headset or speaker

- Play some sort of audio or video

- Attempt to use the Bluetooth device's built-in media controls to pause and/or skip the audio or video

**Expected behavior:**

The audio or video responds to the media controls and pauses or skips

**Other Notes:**

I am not quite sure but this issue seems to be related to something upstream and has been common in Ubuntu and its derivatives for some time

**Comment by bflanagin** [comment]
I have a bluetooth headset with media controls and the buttons are working as expected (if not a little confusing as the skip track and volume controls are the same buttons.) It may be app or device specific. Mind giving us more information on the tests you've done, and the hardware you're using?

**Comment by RPGHank** [comment]
I tried pausing and skipping on GNOME Celluloid, the official Spotify desktop app, and Youtube on both Chrome and Firefox

The testing was done on a JBL Flip 4, but if I remember correctly controls didn't work on some Bluetooth headphones either

**Comment by RPGHank** [comment]
I am not sure if it helps but the Bluetooth controls worked perfectly on Solus 4.2

Solus does use a newer kernel so maybe its related to that?

**Comment by bflanagin** [comment]
That sound about right. We're in the process of testing 5.11 for the next release, it should be backported to 20.10 and 20.04 in not too long. When it does lets be sure to update the ticket with any new findings. I imagine it wont be more than a week, two tops.

**Comment by RPGHank** [comment]
I received the kernel update but the issue is still present :/

**Comment by RPGHank** [comment]
It works now so support must have been added in one of the updates
