### ISSUE TITLE
Required plugins not found - error message should provide solution

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#16]
_From @brs17 on October 13, 2017 20:47_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 35 (noNVIDIA)

**Issue/Bug Description**
When Pop!_OS is installed without an internet connection and then a proprietary media format such as: .avi, .mov, .mp4, mp3, or .wav is played, an error returns that the required plugin could not be found. The user is not informed that with an internet connection, the proper media plugins are found and installed.

**Expected Behavior**

The error message seen in the screen-shot attached below should include a message that if the user connects to the internet, the plugins will be found and the file can be viewed.

**Other notes**

![screenshot from 2017-10-13 13-37-35](https://user-images.githubusercontent.com/7460774/31565695-0bdb488a-b025-11e7-80b2-47578842978d.png)

_Copied from original issue: pop-os/iso#158_

**Comment by isantop** [comment]
@brs17 Normally the system then asks you if you want to install the plugins. What application was this in?

**Comment by WatchMkr** [comment]
Bug filed against Pop!_Shop to handle codec installation. This should also fix this bug. https://github.com/pop-os/pop/issues/16

**Comment by isantop** [comment]
@carl I think this was being caused by a lack of internet connectivity. Totem does offer installation of the required codecs automatically when there is internet available.
