### ISSUE TITLE
Installer: Move drive selection to two-pane layout

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/pop#160]

**Comment by cassidyjames** [comment]
Upstream issue https://github.com/elementary/installer/issues/219

**Comment by cassidyjames** [comment]
Super rough sketch, but should communicate the idea for @mmstick. We should retain the same content and iconography, just re-laid-out to be side-by-side like the other views. The right side should be vertically center-aligned, but overflow into a scroll box (like how the current one works horizontally).

![drives-sketch](https://user-images.githubusercontent.com/611168/37610205-9b209dbe-2b64-11e8-88b7-c98ee2caf0d5.jpg)

**Comment by isantop** [comment]
Current progress on this issue as of 6d6338d3c02225437881aabdeb543b6bec6026a9:

![screenshot from 2018-03-28 17-14-47](https://user-images.githubusercontent.com/5883565/38061194-95a1ceb4-32ab-11e8-9385-c2a79a7207ff.png)
