### ISSUE TITLE
Files removing progress indicator keeps counting to infinity

### ISSUE THREAD

**Issue by AhmedEzzat12** [pop-os/pop#1600]
**Distribution:**

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version:**

```
nautilus:
  Installed: 1:3.38.1-1ubuntu1
  Candidate: 1:3.38.1-1ubuntu1
  Version table:
 *** 1:3.38.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

when trying to remove a directory that has files used by a process, files removing counter keeps counting to infintiy.

**Steps to reproduce (if you know):**

try running for example npm run serve to an application and then try to delete node_modules directorty.

**Expected behavior:**

if files are used by a process show a warning/error to inform the user of the problem

**Other Notes:**
![Peek 2021-03-27 22-01](https://user-images.githubusercontent.com/14370282/112733533-389b0480-8f49-11eb-9a48-0dd62a8ca240.gif)

**Comment by bflanagin** [comment]
Nautilus(or Files) is out of scope for our project at this time. If you would like you can check out the issues over on the projects gitlab page about this issue using the provided link: https://gitlab.gnome.org/GNOME/nautilus/-/issues?scope=all&utf8=%E2%9C%93&state=opened&search=transfer

Its a worth feature request so I would encourage you to file it there.
