### ISSUE TITLE
ask before delete (PopOS 20)

### ISSUE THREAD

**Issue by zekeriyaayan** [pop-os/pop#1602]
**Distribution (run `cat /etc/os-release`):** PopOS 20.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** delete asking option

**Issue/Bug Description:** 

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment]
This is not enough information to describe what issue you're having or what feature you're requesting. If you're able to fill out the rest of the issue template, please let us know and this can be re-opened.
