### ISSUE TITLE
bcmwl-kernel-source error

### ISSUE THREAD

**Issue by prahas23** [pop-os/pop#1603]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
bcmwl-kernel-source gives error after the latest update
![Screenshot from 2021-03-31 20-31-07](https://user-images.githubusercontent.com/59818767/113166076-10204c80-9260-11eb-8736-4e3a9f859e24.png)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by khalilRhouma** [comment]
After installing the recent update, the wifi becomes not working  and it says `No Wi-Fi Adapter found`
when installing `sudo apt install bcmwl-kernel-source`  I got this error related to kernel version I think:

> Loading new bcmwl-6.30.223.271+bdcom DKMS files...
> Building for 5.11.0-7612-generic
> Building for architecture x86_64
> Building initial module for 5.11.0-7612-generic
> ERROR (dkms apport): kernel package linux-headers-5.11.0-7612-generic is not sup
> ported
> Error! Bad return status for module build on kernel: 5.11.0-7612-generic (x86_64
> )
> Consult /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log for more informati
> on.
> dpkg: error processing package bcmwl-kernel-source (--configure):
>  installed bcmwl-kernel-source package post-installation script subprocess retur
> ned error exit status 10
> Errors were encountered while processing:
>  bcmwl-kernel-source
> E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jackpot51** [comment]
Please ensure you have bcmwl-kernel-source 6.30.223.271+bdcom-0ubuntu7pop0 or later installed. This should fix issues with compiling the driver on linux 5.11
