### ISSUE TITLE
[Issue] The login screen at boot is not scalled for my 4k monitor and starts at landscape mode on the second vertical monitor

### ISSUE THREAD

**Issue by MustaphaAlioglou** [pop-os/pop#1608]
**Distribution (run `cat /etc/os-release`):**
 popos 20.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
The login screen at boot is not scalled for my 4k monitor and 
starts at landscape mode on the second vertical monitor

**Steps to reproduce (if you know):**

**Expected behavior:**
the settings should apply before i login with my password.

**Other Notes:**

**Comment by bflanagin** [comment]
@MustaphaAlioglou yes GDM3 is a bit of a mess when it comes to things like this. There is no UI method to fix your problem but you can copy your monitor setup from gnome to GDM3 to achieve the result. 

``` 
sudo cp ~/.config/monitors.xml  /var/lib/gdm3/.config/
sudo chown gdm:gdm /var/lib/gdm3/.config/monitors.xml

```
Let us know how it works out.
