### ISSUE TITLE
Installer: Install to partition setup screen with gparted launcher.

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/pop#161]

**Comment by cassidyjames** [comment]
So to clarify: this is the "Custom" screen that lists all available drives and their partitions. It does **not** handle creating/resizing/deleting partitions. A "Modify Partitions…" button will open GParted or whatever applicable partition editor we're using, and once that closes, the view should reload with new details of partitions.

**Comment by cassidyjames** [comment]
This was the super rough sketch I did when we were first talking about it. I can work on something a little more formal.

![img_20180307_155727](https://user-images.githubusercontent.com/611168/37610403-207037ae-2b65-11e8-9478-ba6a9cb0ba4c.jpg)

I think the button in the bottom-left should say "Modify Partitions…". See [the HIG](https://elementary.io/docs/human-interface-guidelines#using-ellipses) for rationale on the ellipsis if you're curious, and not that the ellipsis should be an actual ellipsis character (…), not three periods.
