### ISSUE TITLE
Laptop Freezing on Suspend

### ISSUE THREAD

**Issue by bboggess** [pop-os/pop#1611]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Package files:
 100 /var/lib/dpkg/status
     release a=now
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu groovy-backports/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-backports,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-updates,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy-security/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy-security,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/multiverse amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/restricted amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main i386 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu groovy/main amd64 Packages
     release v=20.10,o=Ubuntu,a=groovy,n=groovy,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main i386 Packages
     release v=20.10,o=LP-PPA-system76-pop,a=groovy,n=groovy,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
     release v=20.10,o=LP-PPA-system76-pop,a=groovy,n=groovy,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://apt.pop-os.org/proprietary groovy/main all Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary groovy/main amd64 Packages
     release v=20.10,o=system76,a=groovy,n=groovy,l=System76,c=main,b=amd64
     origin apt.pop-os.org

**Issue/Bug Description:**

When suspending the system by closing my laptop, there is a common problem where upon reopening the laptop, the keyboard is unresponsive. This leaves me unable to log back in, and a hard reboot is required to get back into the system.

**Steps to reproduce (if you know):**

Seems to be random. This doesn't happen every time, though it seems to happen more often than not, and I have not noticed any common behaviors that trigger the bug.

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
Could you share the make and model of your laptop? If it has a suspend hotkey (it's Fn+F12 on many System76 machines), does that hotkey still work? If it does, does suspending and waking restore keyboard functionality?

**Comment by bboggess** [comment]
Using a System76 Galaga Pro. The suspend key seems to have done the trick earlier today, so hopefully that gets the job done in the future as well.

**Comment by jacobgkau** [comment]
Glad the suspend key did the trick. For future reference, it's best to [contact support](http://support.system76.com/) for assistance with System76 hardware.

If this is happening often, you can try adding a kernel boot option to prevent it using this command:

```
sudo kernelstub -a "i8042.nomux i8042.reset"
```

If that stops the issue, then knowing which particular model/revision of the Galago you have may be helpful to further investigate. (And it is "Galago," like [the animal](https://en.wikipedia.org/wiki/Galago).)
