### ISSUE TITLE
Error: invalid magic number

### ISSUE THREAD

**Issue by alvinbengeorge** [pop-os/pop#1614]
I dual booted my Windows 10 laptop successfully, but due to some issue(Gnome display manager failed) I was unable to get back in, so I removed the OS using Windows entirely. I wanted to re-install. I tried to flash using balena etcher, the flash failed, and then I tried Rufus and it worked. When I restarted the computer, I got a message:
error: invalid magic number
error: you need to load the kernel first

**I disabled secure boot**
**UEFI**

I also saw in the beginning "file \boot is not found", 
I would like you to either resolve the issue or guide me through this issue

Thank you in advance

**Comment by bflanagin** [comment]
If this is on System76 hardware we offer support through our website [here](https://support.system76.com/).
If you aren't using our hardware we have several documents over how to install pop os [here](https://support.system76.com/articles/install-pop/).

**Comment by alvinbengeorge** [comment]
Its an acer laptop, I went through the process, but do you know when this
happens usually, and could you also tell how to resolve this issue?

**Comment by alvinbengeorge** [comment]
But now I installed Fedora, I think System 76 needs its own Flasher. It can be my pendrive's fault, not computer's fault. but I installed Fedora and its working fine for me.

**Comment by crawfxrd** [comment]
> error: invalid magic number

That sounds like a grub error, and we don't use grub.

Installing Fedora would have fixed it because it would have reinstalled grub.

**Comment by alvinbengeorge** [comment]
> > error: invalid magic number
> 
> That sounds like a grub error, and we don't use grub by default.
> 
> Installing Fedora would have fixed it because it would have reinstalled grub.

I didnt use grub, I used windows boot manager. F12 in my computer

**Comment by Cattodeveloper909** [comment]
Hello! i have passed through the same error one time, and is the pendrive, try another usb drive and see how it goes, since the invalid magic number comes from a corrupted usb or installation, try etcher to see how it goes on a new usb drive, more info [here](https://www.reddit.com/r/linux4noobs/comments/96dktl/invalid_magic_number_and_you_need_to_load_the/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=5ad288c8eb8b4bac95cf74697818aeeb&utm_source=embedly&utm_term=96dktl)

**Comment by alvinbengeorge** [comment]
> Hello! i have passed through the same error one time, and is the pendrive, try another usb drive and see how it goes, since the invalid magic number comes from a corrupted usb or installation, try etcher to see how it goes on a new usb drive, more info [here](https://www.reddit.com/r/linux4noobs/comments/96dktl/invalid_magic_number_and_you_need_to_load_the/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=5ad288c8eb8b4bac95cf74697818aeeb&utm_source=embedly&utm_term=96dktl)

Oh yes, that could be the problem, Thank you for responding

**Comment by Cattodeveloper909** [comment]
> > Hello! i have passed through the same error one time, and is the pendrive, try another usb drive and see how it goes, since the invalid magic number comes from a corrupted usb or installation, try etcher to see how it goes on a new usb drive, more info [here](https://www.reddit.com/r/linux4noobs/comments/96dktl/invalid_magic_number_and_you_need_to_load_the/?ref=share&ref_source=embed&utm_content=body&utm_medium=post_embed&utm_name=5ad288c8eb8b4bac95cf74697818aeeb&utm_source=embedly&utm_term=96dktl)
> 
> Oh yes, that could be the problem, Thank you for responding

No problem! Glad I could help!
