### ISSUE TITLE
Pop os stuck in log in loop

### ISSUE THREAD

**Issue by kharevkk** [pop-os/pop#1617]
During my last use I updated my system, later i switched it off. Now whenever I power on and try to log in with my password, I get stuck in loop at the login page. 

I tried to login via ctrl+alt + f3 , where I put my password and login id. It successfully gave me access there but came with some error (image attached) . Some library file missing or something. Actually this is the second time it is happening, last time I just reinstalled the os again. But this time I am looking for solution. Any one ???

![20210403_211353](https://user-images.githubusercontent.com/71775770/113484253-f3d11980-94c4-11eb-940d-80014e006d14.jpg)

**Comment by bflanagin** [comment]
Looks like your hard drive might be having issues. Notice all the references to a read only filesystem? If you have the installation media handy you can boot it up into demo mode (follow the installer until is say "try demo mode" in the lower left hand corner.)

Once there you have two options:
1. Use Disks from the activities menu and check the install drives for possible issues. 
2. Using the terminal you can run fsck  on each drive you have installed. example: `sudo fsck -f /dev/sda2`

It will probably ask you what to do if it runs into issues. The default action is usually the safe bet. Once its done you should be able to reboot and be back in business.

**Comment by bflanagin** [comment]
The other possible issue is that the video card isn't initializing properly, so if the above comment doesn't help we'll try that next.

**Comment by kharevkk** [comment]
Thanks for the help. It worked. 
Although if that also doesn't workout and possibly the video card isn't initializing properly whats the next step? Because list time I did run the fsck check for the drive. So just wondering if I ran in to the same problem again what will be the next step. Thanks for the help.

**Comment by bflanagin** [comment]
@kharevkk: Glad it worked. The steps will reset each time, check the harddrive for errors using fsck, then you would need to check the amount of storage space you have left using `df -h` if the one mounted at "/' is at 100% full that will keep your computer from fully booting. You would need to clear out space by getting rid of some of the files in your home directory. Thankfully that isn't the case. 

Closing the ticket to make room for new ones.
