### ISSUE TITLE
Missing VPN Settings

### ISSUE THREAD

**Issue by dietrichson** [pop-os/pop#162]
**Reporter info**

``NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
`
```


**Issue/Bug Description**
In my VPN connection I am asked to enter "additional search domains", but there is no interface to input this information.



**Steps to reproduce **

Settings > Network > VPN



**Expected behavior**

A field to input "additional search domains" (and corresponding configuration happening).

**Comment by brs17** [comment]
Thank you @dietrichson for reporting this issue.

Would you possibly be able to submit a screenshot of the screen where the missing input is (or isn't)?

**Comment by dietrichson** [comment]
This is where I would expect to find this:

![screenshot from 2018-03-21 09-37-37](https://user-images.githubusercontent.com/2222669/37710158-92c603d8-2ceb-11e8-8253-1bc1c4f70d10.png)

Here's where it is on 'vanilla ubuntu':

![screenshot from 2018-02-14 13-58-03](https://user-images.githubusercontent.com/2222669/37710188-a8779d54-2ceb-11e8-93b7-943981c34bc5.png)

**Comment by brs17** [comment]
@dietrichson So with the move to GNOME you'll see neither Ubuntu(17.10) nor Pop!_OS has it there under adding a new VPN. 

However after doing some digging, running `nm-connection-editor` you will get the `Additional search domains` option. 

Going to close this issue since we found where it can be done.

**Comment by dietrichson** [comment]
@brs17 Thanks!
