### ISSUE TITLE
can't pair headset

### ISSUE THREAD

**Issue by godzillarzillo** [pop-os/pop#1625]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
bluetooth:
  Installed: (none)
  Candidate: 5.55-0ubuntu1.1
  Version table:
     5.55-0ubuntu1.1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy-updates/universe i386 Packages
     5.55-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu groovy/universe i386 Packages

**Issue/Bug Description:**
cannot pair galaxy buds + or beast solo3

**Steps to reproduce (if you know):**
Initiate Bluetooth Pairing Mode on the headset, find device in the bluetooth section of settings, click the device, the loading starts but nothing happen.

**Expected behavior:**
device paired and connected

**Other Notes:**
i tryed with a fresh installation in two pc, same problem.

**Comment by Cattodeveloper909** [comment]
How Wierd, could you give us the name of the headset? and also, what kernel are you running? here's some [help](https://support.system76.com/articles/bluetooth/)

**Comment by godzillarzillo** [comment]
the headset names are in the bug description (galaxy buds + or beast solo3), 5.11.0-7612-generic is the kernel running.
