### ISSUE TITLE
Can't mount LUKS encrypted volumes in 18.04

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#163]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

**Reporter info**

```
 * Distribution -
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 * Related Application and/or Package Version - 
udisks-2.7.6-2ubuntu4
libblockdev-crypto2
```

**Issue/Bug Description**
When attempting to unlock a LUKS-encrypted volume using Disks, an error message is displayed after entering the password that reads:
```
Error unlocking: The function 
'bd_crypto_luks_open_blob' called, but not 
implemented! (udisks-error-quark, 0)
```

It appears upstream Ubuntu is missing a package as a dependency, `libblockdev-crypto2`. Installing that package and restarting udisks allows it to work correctly:
```
sudo apt install libblockdev-crypto2
systemctl restart udisks2.service
```

**Steps to reproduce (if you know)**
Create a LUKS-encrypted volume on any drive (internal or removable)
Attempt to unlock the volume.

**Expected behavior**
Volume unlocks, data can be accessed

**Other Notes**
Upstream bug: https://bugs.launchpad.net/ubuntu/+source/udisks2/+bug/1757321

**Comment by JulianKunkel** [comment]
Thanks for reporting the solution, too! Works.

**Comment by axel-h** [comment]
Thanks, I had the same issue after upgrading from Mint 18.3 to Mint 19.

**Comment by Ub3rZ4cH** [comment]
> On virtualbox LUbuntu 18.0.4 and Host Windows 10 pro
> 
> When i plug an USB key of Tails OS, an error message appears.
> With your solution, my problem was solved.
> 
> Thanks for solution,
> 
> Sorry for my english (I'm french)

This is also a bug in Lubuntu 18.04 (standalone installer/live ISO).

The solution;

> sudo apt install libblockdev-crypto2
systemctl restart udisks2.service

**Comment by un1337-baSh-sh0mer** [comment]
Above solution also applies to Debian (sid). 09/2020.

**Comment by QEDeD** [comment]
@isantop  it seems this has been resolved? :)

**Comment by allan59300** [comment]
Same solution still applies for uncompleted LUKS installation on PiOs (Raspbian) updatef 2022 June.

**Comment by leviport** [comment]
I think this can be closed now
