### ISSUE TITLE
Sound output switch from headphone/Speaker to controller when connecting controller via USB

### ISSUE THREAD

**Issue by arthurlch** [pop-os/pop#1630]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Settings /sound

**Issue/Bug Description:**
When headphones are used ( jack ) or  Speaker and a controller is connected via USB-A sound output goes to analog output instead of staying on headphones/Speaker, tested with different types of controller: Sony PS4 & Microsoft XBOX/PC controllers.

**Steps to reproduce (if you know):**
Plug controller via USB-A while using headphones(jack) or using Speaker, output switching to controller. 

**Expected behavior:**
Sound output will switch from Headphone to Analog output(controller) when connecting the controller. 

**Other Notes:**
Some of these controllers have jack port(Sony controller) or sound output options. So the sound output from the controller takes on the output bu default but since on PC it's odd that the controller output override the headphone/Speaker output.

**Comment by Cattodeveloper909** [comment]
That is wierd, have you tried changing the output in pulseaudio? if you don't have it installed run this in your terminal `$ sudo apt install pulseaudio` and try to change the output in pulseaudio since is more customizable, let us know if something happend, cheers!

**Comment by arthurlch** [comment]
I'm using it already no config from pulseaudio can fix the problem and I don't think it could fix the problems since when you change the output in pulse audio it also change the output in your setting/audio, controllers still override default output.  I couldn't find similar issues on forums.
