### ISSUE TITLE
Backlight and key light changes reset redshift applied overlay

### ISSUE THREAD

**Issue by arbitrary-dev** [pop-os/pop#1633]
**Distribution:**
```
NAME="Pop!_OS"
VERSION="20.10"
``` 
 
**Related Application and/or Package Version:**
```
redshift 1.12-2
```

**Bug Description:**
Changing backlight or key lights results in red overlay reset (set by redshift).

**Expected behavior:**
Backlight/keylighs doesn't reset red overlay.

**Comment by Fushko** [comment]
The issue is caused by the "colord" daemon. To disable it:
`systemctl disable colord`
`systemctl stop colord`
