### ISSUE TITLE
feture request : mixer of sound shortcut in panel of notification

### ISSUE THREAD

**Issue by tridoxx** [pop-os/pop#1648]
![imagen_2021-04-14_181340](https://user-images.githubusercontent.com/22879539/114792020-242e7880-9d4d-11eb-88b6-40d640afa75c.png)

I would like to ask if you could put this mixer volume, in this way, by clicking on sound, since this shortcut would be a great help so as not to go every time you want to level the volume of an application, go to settings and sound, thank you very much for your work , and this great system that I recommend to everyone

**Comment by leviport** [comment]
Thanks for the suggestion! We likely won't implement this as a default setting, but there are quite a few Gnome Shell extensions that do this sort of thing. [This one](https://extensions.gnome.org/extension/3499/application-volume-mixer/) seems to be working pretty well currently. There are a [number](https://extensions.gnome.org/extension/3499/application-volume-mixer/) of [others](https://extensions.gnome.org/extension/937/laine/) you could try out, but they may be hit-and-miss for more current versions of Gnome Shell.

**Comment by tridoxx** [comment]
thanks for you reply,!!
