### ISSUE TITLE
Testing ISO #5 Issues

### ISSUE THREAD

**Issue by jackpot51** [pop-os/pop#165]
Intel
http://209.212.58.90:8080/job/pop-os/job/release/job/18.04/5/artifact/build/pop-os/18.04/pop-os_18.04_amd64_intel_5.iso

NVIDIA
http://209.212.58.90:8080/job/pop-os/job/release/job/18.04_nvidia/5/artifact/build/pop-os/18.04/pop-os_18.04_amd64_nvidia_5.iso

Please report any issues here as concisely as possible indicating which machine and ISO had the issue if that is relevant. I will create new issues attached to the correct project based on these comments.

**Comment by jackpot51** [comment]
The boot order is currently not being set by `distinst` to avoid mucking up developer machines. This must be fixed before relasing a public ISO

**Comment by brs17** [comment]
**Leow9 (GTX1080, SATA SSD, HiDPI):**
Seen both on encyrpting and not encrypting the drive. After completing Gnome-initial-setup, the machine will go back to the gdm login, after typing in password the system will hang. (similar to issue we had before releasing wilp14). The disk encryption password is not asked for when logging in either. After hard rebooting, system goes to an initramfs prompt.
![20180323_143314](https://user-images.githubusercontent.com/7460774/37852255-8752c9f6-2ea7-11e8-80c3-fa7cf9c943c3.jpg)

**Silw12 (GTX 970, 1TB SATA RAID)**
With this machine also had the system hang after gnome-initial-setup. Have not seen the initramfs prompt. Noticed that after rebooting, gnome-initial-setup does not come up again.

**Comment by aia832003** [comment]
@jackpot51 is that why it's not recognizing UEFI on my Dell XPS 13? Install only boots with Legacy installation.

**Comment by djordan2** [comment]
@aia832003 If this bug were responsible, it would install fine, but not change the boot order (you would have to pick it from the boot list).  

Is your laptop's bios set to legacy mode?  Often the USB boot media will show twice in the boot menu, once for UEFI and once for legacy.  Whichever you pick will affect how the system installs.

**Comment by aia832003** [comment]
With bios set to UEFI install completes but fails to boot. Reinstallation with bios changed to legacy was successful and boots to Pop. @djordan2

**Comment by aia832003** [comment]
May have just been a bad download guys. Downloaded again and seems to be fine. Keep up the great work.
