### ISSUE TITLE
Bug Kernel 5.11.0-7612-generic - POP OS 20.10

### ISSUE THREAD

**Issue by mariofelesdossantosjunior** [pop-os/pop#1650]
Loading new system76-io-1.0.1~1616424744~20.10~57c15ff DKMS files...
Building for 5.11.0-7612-generic
Building initial module for 5.11.0-7612-generic
ERROR (dkms apport): kernel package linux-headers-5.11.0-7612-generic is not supported
Error! Bad return status for module build on kernel: 5.11.0-7612-generic (x86_64)
Consult /var/lib/dkms/system76-io/1.0.1~1616424744~20.10~57c15ff/build/make.log for more information.
dpkg: erro ao processar o pacote system76-io-dkms (--configure):
 o subprocesso instalado, do pacote system76-io-dkms, o script post-installation retornou erro do status de saída 10
Configurando libnvidia-cfg1-460:amd64 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando xserver-xorg-video-nvidia-460 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
dpkg: problemas com dependências impedem a configuração de system76-driver:
 system76-driver depende de system76-dkms; porém:
  Pacote system76-dkms não está configurado ainda.
 system76-driver depende de system76-io-dkms; porém:
  Pacote system76-io-dkms não está configurado ainda.

dpkg: erro ao processar o pacote system76-driver (--configure):
 problemas de dependência - deixando desconfigurado
Configurando nvidia-kernel-source-460 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Nenhum relatório apport escrito pois a mensagem de erro indica que é um erro de seguimento de um erro anterior.
                                                                                                               Configu
rando system76-acpi-dkms (1.0.2~1600812457~20.10~0bc966c) ...
Removing old system76_acpi-1.0.2~1600812457~20.10~0bc966c DKMS files...

------------------------------
Deleting module version: 1.0.2~1600812457~20.10~0bc966c
completely from the DKMS tree.
------------------------------
Done.
Loading new system76_acpi-1.0.2~1600812457~20.10~0bc966c DKMS files...
Building for 5.11.0-7612-generic
Building initial module for 5.11.0-7612-generic
ERROR (dkms apport): kernel package linux-headers-5.11.0-7612-generic is not supported
Error! Bad return status for module build on kernel: 5.11.0-7612-generic (x86_64)
Consult /var/lib/dkms/system76_acpi/1.0.2~1600812457~20.10~0bc966c/build/make.log for more information.
dpkg: erro ao processar o pacote system76-acpi-dkms (--configure):
 o subprocesso instalado, do pacote system76-acpi-dkms, o script post-installation retornou erro do status de saída 10
Nenhum relatório apport escrito pois MaxReports já foi atingido
                                                               Configurando libnvidia-gl-460:amd64 (460.67-1pop0~16164
30777~20.10~71e1ad1) ...
Configurando libnvidia-gl-460:i386 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando nvidia-settings (460.39-0ubuntu0.20.10.1) ...
Configurando libnvidia-extra-460:amd64 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando nvidia-utils-460 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando libnvidia-decode-460:amd64 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando libnvidia-ifr1-460:amd64 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando libnvidia-ifr1-460:i386 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Configurando nvidia-compute-utils-460 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
Alerta: o diretório pessoal /nonexistent que você especificou não pode ser acessado: No such file or directory
Adicionando usuário de sistema 'nvidia-persistenced' (UID 123) ...
Adicionando novo grupo `nvidia-persistenced' (GID 130) ...
Adicionando novo usuário `nvidia-persistenced' (UID 123) ao grupo `nvidia-persistenced' ...
Sem criar diretório pessoal `/nonexistent'.
Configurando nvidia-dkms-460 (460.67-1pop0~1616430777~20.10~71e1ad1) ...
update-initramfs: deferring update (trigger activated)
INFO:Enable nvidia
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-serw10
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-oryp3-ess
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-oryp3
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-oryp2-ess
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/put_your_quirks_here
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-oryp3-b
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-oryp2
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/lenovo_thinkpad
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/system76-nvidia-quirks-bonw11
DEBUG:Parsing /usr/share/ubuntu-drivers-common/quirks/dell_latitude
Loading new nvidia-460.67 DKMS files...
Building for 5.11.0-7612-generic
Building for architecture x86_64
Building initial module for 5.11.0-7612-generic
ERROR (dkms apport): kernel package linux-headers-5.11.0-7612-generic is not supported
Error! Bad return status for module build on kernel: 5.11.0-7612-generic (x86_64)
Consult /var/lib/dkms/nvidia/460.67/build/make.log for more information.
dpkg: erro ao processar o pacote nvidia-dkms-460 (--configure):
 o subprocesso instalado, do pacote nvidia-dkms-460, o script post-installation retornou erro do status de saída 10
Nenhum relatório apport escrito pois MaxReports já foi atingido
                                                               Configurando libnvidia-encode-460:amd64 (460.67-1pop0~1
616430777~20.10~71e1ad1) ...
dpkg: problemas com dependências impedem a configuração de system76-driver-nvidia:
 system76-driver-nvidia depende de system76-driver (>= 20.04.31~1617661455~20.10~b3a83f8); porém:
  Pacote system76-driver não está configurado ainda.

dpkg: erro ao processar o pacote system76-driver-nvidia (--configure):
 problemas de dependência - deixando desconfigurado
Nenhum relatório apport escrito pois MaxReports já foi atingido
                                                               dpkg: problemas com dependências impedem a configuração
 de nvidia-driver-460:
 nvidia-driver-460 depende de nvidia-dkms-460 (>= 460.67); porém:
  Pacote nvidia-dkms-460 não está configurado ainda.

dpkg: erro ao processar o pacote nvidia-driver-460 (--configure):
 problemas de dependência - deixando desconfigurado
Nenhum relatório apport escrito pois MaxReports já foi atingido
                                                               A processar 'triggers' para mime-support (3.64ubuntu1) 
...
A processar 'triggers' para gnome-menus (3.36.0-1ubuntu1) ...
A processar 'triggers' para libc-bin (2.32-0ubuntu3) ...
A processar 'triggers' para man-db (2.9.3-2) ...
A processar 'triggers' para desktop-file-utils (0.24-1ubuntu4) ...
A processar 'triggers' para initramfs-tools (0.137ubuntu12) ...
update-initramfs: Generating /boot/initrd.img-5.11.0-7612-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
kernelstub.Config    : INFO     Looking for configuration...
kernelstub           : INFO     System information: 

    OS:..................Pop!_OS 20.10
    Root partition:....../dev/sda2
    Root FS UUID:........5facabbe-3cb5-4bf7-bafe-bee98779248a
    ESP Path:............/boot/efi
    ESP Partition:......./dev/sda1
    ESP Partition #:.....1
    NVRAM entry #:.......-1
    Boot Variable #:.....0000
    Kernel Boot Options:.quiet loglevel=0 systemd.show_status=false splash
    Kernel Image Path:.../boot/vmlinuz-5.11.0-7612-generic
    Initrd Image Path:.../boot/initrd.img-5.11.0-7612-generic
    Force-overwrite:.....False

kernelstub.Installer : INFO     Copying Kernel into ESP
kernelstub.Installer : INFO     Copying initrd.img into ESP
kernelstub.Installer : INFO     Setting up loader.conf configuration
kernelstub.Installer : INFO     Making entry file for Pop!_OS
kernelstub.Installer : INFO     Backing up old kernel
kernelstub.Installer : INFO     No old kernel found, skipping
Erros foram encontrados durante o processamento de:
 system76-dkms
 system76-io-dkms
 system76-driver
 system76-acpi-dkms
 nvidia-dkms-460
 system76-driver-nvidia
 nvidia-driver-460
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@pop-os:/home/mario# 

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
What were you running and why were you running it as root?

**Comment by mariofelesdossantosjunior** [comment]
This command 
sudo dpkg --configure -a

**Comment by leviport** [comment]
You shouldn't really be running apt or dpkg commands as root. Use your normal user account and `sudo` instead. There are very few instances in which you should be using root instead of `sudo`.

**Comment by mariofelesdossantosjunior** [comment]
But this problem is not sudo, and yes the erros  nvidia-dkms-460
 system76-dkms
 system76-io-dkms
 system76-driver
 system76-acpi-dkms
 nvidia-driver-460
