### ISSUE TITLE
Cannot change graphics modes on 20.10

### ISSUE THREAD

**Issue by Mango0x45** [pop-os/pop#1652]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-power:
  Installed: 1.1.16~1618506466~20.10~214e1c8
  Candidate: 1.1.16~1618506466~20.10~214e1c8
  Version table:
 *** 1.1.16~1618506466~20.10~214e1c8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu groovy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When running `system76-power graphics`, I get the output `integrated`. I have tried switching to both Nvidia and Hybrid modes from both the CLI and the widget, but I cannot switch to anything but integrated mode.

**Steps to reproduce (if you know):**
Switch to integrated mode, reboot, and try to switch to nvidia or hybrid modes.

**Expected behavior:**
For the output of `system76-power graphics` to be either `nvidia` or `hybrid`

**Other Notes:**

**Comment by leviport** [comment]
Can you describe the hardware you're seeing this on? I've seen this happen from time to time on the System76 Oryx Pro (oryp6), and I can usually fix it by reinstalling the NVIDIA drivers: https://support.system76.com/articles/login-loop-pop/#reinstall-nvidia-driver. Perhaps that'll also do the trick for you?

**Comment by Mango0x45** [comment]
> Can you describe the hardware you're seeing this on? I've seen this happen from time to time on the System76 Oryx Pro (oryp6), and I can usually fix it by reinstalling the NVIDIA drivers: https://support.system76.com/articles/login-loop-pop/#reinstall-nvidia-driver. Perhaps that'll also do the trick for you?

I have already done this, and the issue still continues.

**Comment by leviport** [comment]
The make/model of your machine would be helpful to know.
