### ISSUE TITLE
Suspend after logging in while lid closed

### ISSUE THREAD

**Issue by jwefers** [pop-os/pop#1655]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Logging in to laptop while closed (external monitor), laptop goes into sleep.

**Steps to reproduce (if you know):**
- Laptop off and closed
- external monitor plugged in
- openlaptop, hit power, close
- Reach login screen
- Type in my password in the login screen
- _Laptop goes into standby_
- Open again, hit power, close.
- Laptop now runs as expected on external monitor and lid closed.

**Expected behavior:**

- Since the laptop is closed the whole time, it should not go into sleep on login
- After this undesired standby, i expected the laptop be locked. Its not (it is when going into standby on purpose)

**Other Notes:**
Laptop is Thinkpad X13 with Ryzen Pro 4650U (https://www.notebookcheck.net/Lenovo-ThinkPad-X13-AMD-Ryzen-5-Pro-4650U.479124.0.html)
- latest BIOS as of 04/18/2021

**Comment by leviport** [comment]
Does your external keyboard wake the machine from suspend with the lid closed?

**Comment by jwefers** [comment]
No but it also doesnt on Windows - and i think the bios has no option to allow that - but i could check

**Comment by jwefers** [comment]
Always On USB was off, let me try your question again with an actually powered keyboard

**Comment by leviport** [comment]
> Now i cannot reproduce it anymore - Turned Always On USB on, tried, everything worked. Then off again, it still works. Well...

Interesting. Well I saw another [similar report](https://github.com/pop-os/system76-power/issues/239) this morning, so I'm going to leave this open a bit longer. Since this may not be specific to your model of laptop, I have edited the issue title to be more generic.

**Comment by jwefers** [comment]
Its back - after not being able to reproduce it, i turned USB Always on Off again (mainly so my RBG keyboard goes off as well), and now i am back at this behaviour.

To narrow, i am gonna leave usb on for a while and see if that mitigates it over a period of multiple boots

**Comment by jwefers** [comment]
Had it now again with USB power on - no correlation.
i cannot correlate with anything currently.
Is there any event log i could `tail` where a standby event trigger would be listed?
