### ISSUE TITLE
Wake-up after suspension fails with nvidia binary driver

### ISSUE THREAD

**Issue by ng1905** [pop-os/pop#166]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
...

 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
nvidia-390: 390.25-0ubuntu1~17.10.0

**Issue/Bug Description**
With proprietary nvidia drivers enabled, my laptop fails to wake up (screen turns on but shows black; cpu-fan gets louder than normal) after any duration of time in suspension.

**Steps to reproduce (if you know)**
Close laptop or switch to suspension-mode in the menu. After waking up the device, the problem occures.

**Expected behavior**
Device should wake up properly and display the lock screen.

**Other Notes**
- Fresh install of Pop!OS
- Graphics chip: Nvidia GTX 950M
- X-org drivers also have an issue on my device (freezing on shutdown (and preventing it) after laptop has been in suspension mode in the same power cycle)

**Comment by gdonald** [comment]
I have this same issue.  I close the lid, it suspends.  Later I open the lid and all I get is a black screen, a loud fan, and a hot cpu.  I've waited as long as 15 minutes, but it never wakes up.  I have to hold the power button and hard reboot it.

> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 17.10 (Artful Aardvark)
Release:	17.10
Codename:	artful

**Comment by ng1905** [comment]
It came to me that the kernel seems to be the issue here (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1720622) 

After upgrading to a newer one (v4.16-rc7 in my case), waking up the notebook works perfectly fine.
