### ISSUE TITLE
Hybrid mode using 30~50% of one CPU core when HDMI monitor is connected

### ISSUE THREAD

**Issue by FranLMSP** [pop-os/pop#1662]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Process: `/usr/lib/xorg/Xorg vt2 -displayfd 3 -auth /run/user/1000/gdm/Xauthority -nolisten tcp -background none -noreset -keeptty -novtswitch -verbose 3`, I think the parent process is `gdm-x-session`

**Issue/Bug Description:**
`/usr/lib/xorg/Xorg` is always using 30~50% of one CPU core

**Steps to reproduce (if you know):**
1. Switch to Hybrid mode
2. Connect an external HDMI monitor
3. The CPU usage in one core goes to 30\~50%. When I unplug it, it goes down to 10\~20%. This doesn't happen on Nvidia mode, but Nvidia consumes way more vram (less vram form games) and it produces more heat on my laptop.
4. I'm having a very similar behavior to this (if not the same): https://forums.developer.nvidia.com/t/high-cpu-usage-on-xorg-when-the-external-monitor-is-plugged-in/169173/9

**Expected behavior:**
not to kill the CPU when I plug in the monitor?

**Other Notes:**
My laptop is a Dell G3 3579, with an i5-8300h and a GTX 1050ti

I couldn't find any related issue so sorry if this is duplicated

**Comment by ehannes** [comment]
I have the same problem. I have two external screens, one on HDMI and one on DisplayPort, and I'm also using hybrid mode. Pulling both of them out stops the heavy CPU usage.

```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

I will soon upgrade to a newer PopOS version. Maybe that will help...

**Comment by aalvarado** [comment]
Same problem, cpu sits between 25%-30% on `Xorg` 
`VERSION="21.04"`

from the forums:

> The monitors get requeried in fast succession, which gets written to the log, which is why clock_gettime is called. No idea what initiates the query, though.

**Comment by wokawoka** [comment]
I experience the exact same problems when I connect monitors in hybrid mode.
Thinkpad X1 extreme gen 2 running the last pop os.

**Comment by leviport** [comment]
Sounds like this could be related to https://github.com/pop-os/nvidia-graphics-drivers/issues/61

**Comment by FranLMSP** [comment]
Update on this:
I noticed that this happens on other distros as well so it could be an Xorg or Nvidia issue. I haven't been able to test Wayland with Nvidia because it crashes when I try to use the Nvidia card.
On Arch I managed to fix the stuttering by using `optimus-manager` and switching to the `xf86-video-intel` driver instead of the `modesetting` driver: https://gist.github.com/FranLMSP/c2bec545f7afc7b714b2d06094a19c60
I'm not sure if there's a way to use `xf86-video-intel` with `system76-power` (not related but it would be nice to have `system76-power` on non-systemd or non-debian distros!). 
I still have the ~30% CPU usage, but at least the video is more smooth on hybrid mode with an HDMI monitor.

**Comment by aisivan36** [comment]
I had encountered the same issue, it happened on all Linux's distribution. When I set to hybrid mode with external monitor connected the xorg went to 30-40% of CPU usage, on the other hand I had switched to Nvidia Full and I noticed the GPU power Nvidia draw constantly on idle at 30watt as long as I move cursor, it made Laptop's charger went so hot, Nvidia temperature went to around 40 - 50 degree constantly it defected CPU and was triggered Fan spun up out loud

**Comment by chaosrun** [comment]
Same issue here

```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Comment by aalvarado** [comment]
if I stop using picom, cpu usage goes down. 

maybe it needs:

```
__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia picom
```

**Comment by omer-musa-battal** [comment]
it seems like this issue will be resolved in the next nvidia release driver:

https://forums.developer.nvidia.com/t/high-cpu-usage-on-xorg-when-the-external-monitor-is-plugged-in/169173/84

**Comment by ikus060** [comment]
I think this issue should be closed. I had that problem back then and 545 fixed it.

**Comment by leviport** [comment]
Sounds good. We can reopen it later if needed. Thanks for the update!
