### ISSUE TITLE
Pop OS not booting up, Getting initramfs screen.

### ISSUE THREAD

**Issue by mayankdutta** [pop-os/pop#1665]
**Distribution (run `cat /etc/os-release`):*Pop OS 20.04 LTS*
 
 

**Issue/Bug Description:** I was getting this screen [see picture](https://github.com/pop-os/pop/issues/1254) then when I rebooted after long time i am now seeing `initramfs` I don't know what to type. Already been through [this page](https://github.com/pop-os/pop/issues/626) holding down space only bringing 3 options not 5.
- Pop_OS-oldkern 
- Pop_OS-currentkern 
- Reboot

Neither my usb stick working, some error commands keep repeating. I don't even have nvidea stuff, Below I am sharing my laptop specs <br><br>
![Screenshot 2021-04-23 at 3 38 21 PM](https://user-images.githubusercontent.com/33067129/115856395-0f876a00-a44a-11eb-83e0-1977196bc50d.png)
![Screenshot 2021-04-23 at 3 38 30 PM](https://user-images.githubusercontent.com/33067129/115856404-11e9c400-a44a-11eb-8e45-9870c2fd014a.png)
![Screenshot 2021-04-23 at 3 38 37 PM](https://user-images.githubusercontent.com/33067129/115856408-131af100-a44a-11eb-8d40-c666254aabd9.png)

<br><br>
I don't know what to do. 
I am completely stuck. please help.
[More specs](https://www.amazon.in/gp/product/B07WL4RB1X/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) if you want to see.

**Comment by bflanagin** [comment]
@mayankdutta: Sorry to hear you're having trouble. The first thing that stands out is that you aren't able to boot to your usb disk. Is there a chance you can test it on another computer -or- make a new one with the latest iso from our website? https://pop.system76.com/

I'm thinking it may be a hardware issue more than a OS one, though more testing is required, and a picture of the error that repeats when you use the usb stick would be helpful.

Thanks

**Comment by mayankdutta** [comment]
> @mayankdutta: Sorry to hear you're having trouble. The first thing that stands out is that you aren't able to boot to your usb disk. Is there a chance you can test it on another computer -or- make a new one with the latest iso from our website? https://pop.system76.com/
> 
> I'm thinking it may be a hardware issue more than a OS one, though more testing is required, and a picture of the error that repeats when you use the usb stick would be helpful.
> 
> Thanks

I am really sorry to raise issue in haste actually i just found out that my HDD got corrupted. Thank you for your quick support !!
