### ISSUE TITLE
qemu is not a package

### ISSUE THREAD

**Issue by XxMicrowavexX** [pop-os/pop#1669]
When I type
`qemu`
in the terminal, it asks me to instal aqemu so I went to the qemu website and found that u need to instal with apt-get so I did but when it finished I typed `qemu` and it still failed and asked me to instal aqemu

**Comment by leviport** [comment]
`qemu` is a package that you can install (which it sounds like you have), but `qemu` in the terminal is not how you run it. `aqemu` is a graphical frontend for managing qemu, which is something else entirely. You might want to check out the [quick start guide](https://qemu-project.gitlab.io/qemu/system/quickstart.html) in the qemu docs to get up and running with qemu. 

If you're looking for a quicker way to get up and running with virtual machines, I would suggest trying out [GNOME Boxes](https://help.gnome.org/users/gnome-boxes/stable/) or [virt-manager](https://virt-manager.org/).
