### ISSUE TITLE
[Issue] Mouse speed becomes slower and feels like it has slower respond time when connected to a second 4k monitor.

### ISSUE THREAD

**Issue by MustaphaAlioglou** [pop-os/pop#1670]
**Distribution (run `cat /etc/os-release`):**
 popos 20.04 fully upgraded.
 

**Issue/Bug Description:**
i have an 1080p and 4k display. when i connect the 4k one the mouse speed decreases and i believe the respond time becomes bigger. my specs are i7 8700k, 1050 ti , 970 evo plus.

**Steps to reproduce (if you know):**
connect a second 4k display.

**Comment by leviport** [comment]
How are you connecting your 4k display? If it's over HDMI, you have to make sure that your machine, your cable, and your display all support HDMI 2.0, otherwise it won't be able to push 60Hz, which I would guess is what's making it feel slower.

**Comment by MustaphaAlioglou** [comment]
Both displays definitely push 60 hz. The 1080 display uses hdmi 2 and the 4K uses a display port.

**Comment by MustaphaAlioglou** [comment]
I noticed that if I set the refresh rate from the nvidia settings directly it fixes the problem enough to make it not noticable or completely I am not sure. But then I can rescale the 1080 monitor from 200% to 100% because I lose all the settings.

**Comment by MustaphaAlioglou** [comment]
i just set the 4k monitor to 60hz from the nvidia application (nvidia x server settings)
