### ISSUE TITLE
Build in wireless only working on 2.4GHZ

### ISSUE THREAD

**Issue by peter1512** [pop-os/pop#168]
**Distribution - **
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"

**Issue/Bug Description**
Wireless card in Lenovo Thinkpad Edge E540 (Intel Dual Band Wireless-AC 7260) not working with 5GHZ, only working with 2.4GHZ.
(was working with pop_os 17.10)

**Comment by brs17** [comment]
@peter1512 Thank you for submitting this issue.

Could you perhaps try Ubuntu 18.04 or another distribution with the 4.15 kernel and let us know if the card works with 5Ghz then?

**Comment by peter1512** [comment]
I'll give it a swirl in the morning with Ubuntu 18.04 and let you know the outcome

**Comment by peter1512** [comment]
![screenshot from 2018-04-03 00-57-51](https://user-images.githubusercontent.com/37885971/38230086-3456f9d0-36da-11e8-8340-49b65e911c25.png)
Here is the relevant lsmod part.

**Comment by peter1512** [comment]
Results are the same with Ubuntu 18.04 b1 (Budgie). 2.4ghz is working but no 5ghz. Lsmod showing same results.

**Comment by brs17** [comment]
Alright, @peter1512 so this shows that it isn't Pop!_OS specific. My thought then is that this is a kernel regression (since 17.10 uses a different kernel). I guess it's time to do some research to see if anyone has mentioned a similar issue/if it has been reported upstream.

**Comment by peter1512** [comment]
I was afraid of that. I'll poke around and see what I find. 
Closing the issue.
