### ISSUE TITLE
[Issue]  system76-power : Conflicts: nvidia-prime

### ISSUE THREAD

**Issue by MustaphaAlioglou** [pop-os/pop#1681]
**Distribution (run `cat /etc/os-release`):**
 fresh installation 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 

**Issue/Bug Description:**
The following packages have unmet dependencies:
 system76-power : Conflicts: nvidia-prime
E: Broken packages

**Steps to reproduce (if you know):**
sudo apt update; sudo apt upgrade

**Comment by JaffoS1** [comment]
Same here.
System not useable right now, grafic drivers not working.

`ERROR (dkms apport): kernel package linux-headers-5.11.0-7614-generic is not supported
Error! Application of patch disable_fstack-clash-protection_fcf-protection.patch failed.
Check /var/lib/dkms/nvidia/460.73.01/build/ for more information.
dpkg: Fehler beim Bearbeiten des Paketes nvidia-dkms-460 (--configure):
 »installiertes nvidia-dkms-460-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 6 zurück
Trigger für initramfs-tools (0.137ubuntu12) werden verarbeitet ...
update-initramfs: Generating /boot/initrd.img-5.11.0-7614-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
Fehler traten auf beim Bearbeiten von:
 nvidia-dkms-460
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by MustaphaAlioglou** [comment]
I marked the two packages and put the to hold  and then  upgraded but the graphics were broken. So re installed and now I m waiting for a fix.

**Comment by tuhlmann** [comment]
I ran across this too with a pristine new installation of Pop OS 20.04.

I installed Pop OS 20.04 NVidia on a new hard drive (unencrypted), bootet into it and was going to install the suggested updates when this error occured. I didn't install anything extra before the updates.

**Comment by mmstick** [comment]
This has always been true. nvidia-prime is not compatible with system76-power.

The NVIDIA driver issues are a different issue entirely. Simply wait until the PPA has been updated with new drivers, and don't try to force install any drivers.

**Comment by jonkracht** [comment]
Also had the conflict between the system76-power and nvidia-prime packages on a fresh PopOS 22.04 install.  While "apt upgrade" was not permitted because of the conflict, "sudo apt dist-upgrade" seems to have corrected the problem.  Hope this is of help to someone.

**Comment by euphroshub** [comment]
Thanks @jonkracht this fixed it for me.

**Comment by ScriptAutomate** [comment]
> Also had the conflict between the system76-power and nvidia-prime packages on a fresh PopOS 22.04 install. While "apt upgrade" was not permitted because of the conflict, "sudo apt dist-upgrade" seems to have corrected the problem. Hope this is of help to someone.

An alternative approach, via the [System76 Discord from one of the System76 Happiness Engineers](https://discord.com/channels/845005478111346708/1004403699956850728/1004466467858817115):

```bash
sudo apt purge ~nnvidia
sudo apt clean
sudo apt update
sudo apt install system76-driver-nvidia
sudo systemctl reboot
```

This also fixed things for me.
