### ISSUE TITLE
No close icon after opening properties of folder

### ISSUE THREAD

**Issue by kshitijzutshi** [pop-os/pop#1687]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
On right clicking a folder to view its properties(to know its size etc), one cant just close the pop up as there is no close icon for the window.
Attached the screenshot here:

![Screenshot from 2021-05-06 13-15-18](https://user-images.githubusercontent.com/13203059/117260964-3cd21000-ae6d-11eb-8dc9-33d0ea8221cd.png)

**Steps to reproduce (if you know):**

**Expected behavior:**
There should be a close X icon to close the pop up window

**Other Notes:**

**Comment by bflanagin** [comment]
I'm not seeing this on my machines. Did you install/uninstall anything recently? How often do you run updates?

**Comment by leviport** [comment]
It looks like you have "Show Window Titles" disabled in pop-shell. If it is disabled, this is intended behavior.

![Screenshot](https://user-images.githubusercontent.com/13512097/117318313-890a5980-ae47-11eb-91cc-1d0de0fabc1f.png)

**Comment by kshitijzutshi** [comment]
> I'm not seeing this on my machines. Did you install/uninstall anything recently? How often do you run updates?

Hi, I run the updates daily on my system wake. I have kept everything updated actually. The only way I get the pop up to go away is when I force close the app or disconnect my drive. :/

**Comment by kshitijzutshi** [comment]
> It looks like you have "Show Window Titles" disabled in pop-shell. If it is disabled, this is intended behavior.
> 
> ![Screenshot](https://user-images.githubusercontent.com/13512097/117318313-890a5980-ae47-11eb-91cc-1d0de0fabc1f.png)

@leviport Thanks a lot, seems like the toggling helped me get the Close option on the pop window. Appreciate your response. Issue resolved. Pl close this. :+1:
