### ISSUE TITLE
Windows 10 failed during installation via QUME using Virtual-Manager

### ISSUE THREAD

**Issue by Jernel-dotcom** [pop-os/pop#1699]
**Windows 10 from any version failed during installation via QUME using Virtual-Manager.**

Once the installation finished the VM should head to restart, however it didn't happen even after 1 or 10 hours.
If you try to reboot the VM manually it will start, then show the Windows 10 logo with black background, round the loading circle and popup an error that the PC experience unexpected restart. After a few minutes it will show blue screen, collect logs and suggest updating the support team with code error SYSTEM SERVICE EXCEPTION

* Re-installation didn't help.
* However, after the manual reboot, accessing the VM from QEMU window manager (build in), the window machine boot up correctly. Then the VM become accessible from virt-mngr as well 
* This issue didn't happen on Ubuntu, so it is logical to suppose that it is an issue with Pop!_OS 

VM hardware configuration:
8 GB of RAM
4 cores

NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
Linux pop-os 5.11.19-xanmod1 x86_64 x86_64 x86_64 GNU/Linux (on the original kernel it didn't work as well)
 
ipxe-qemu-256k-compat-efi-roms/groovy,groovy,now 1.0.0+git-20150424.a25a16d-0ubuntu4 all [installed,automatic]
ipxe-qemu/groovy,groovy,now 1.0.0+git-20190125.36a4c85-5ubuntu3 all [installed,automatic]
libvirt-daemon-driver-qemu/groovy-updates,now 6.6.0-1ubuntu3.5 amd64 [installed,automatic]
qemu-block-extra/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed,automatic]
qemu-kvm/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed]
qemu-system-common/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed,automatic]
qemu-system-data/groovy-updates,groovy-updates,now 1:5.0-5ubuntu9.8 all [installed,automatic]
qemu-system-gui/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed,automatic]
qemu-system-x86/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed,automatic]
qemu-utils/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed,automatic]
qemu/groovy-updates,now 1:5.0-5ubuntu9.8 amd64 [installed]

Steps to reproduce:
1. Install the latest Pop_!OS 
2. Install the latest QEMU kvm
3. Download the latest pack of Windows 10 from the official web.
4. Run through the Windows 10 installation on QUME > failed

The expected behavior is to get the VM working properly.

CPU: AMD 5800x
Mather board: B550F ASUS
Virtualization: Turned on (SVM)

**Comment by Oymate** [comment]
Shouldn't this be in qemu forums?

**Comment by Jernel-dotcom** [comment]
It didn't happen on other OSs, so might be the OS issue?
