### ISSUE TITLE
Bug with Document Viewer printing wrong multiples

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#17]
_From @sarahpandabeara on October 12, 2017 19:25_

Carl and I found that this is specific to Pop!_OS where printing a PDF from Document Viewer in any multiple other than 1 sends the request off more than once (ie: ask for 2 copies, get 4).

Confirmed: Not an issue with Libre open docs.
Confirmed: Not an issue with Ubuntu Document Viewer

_Copied from original issue: pop-os/iso#155_

**Comment by isantop** [comment]
@brs17 We probably need to re-test this from Ubuntu 17.10 again, to ensure that everything is up to date.

**Comment by WatchMkr** [comment]
Confirmed in 17.10.

**Comment by bflanagin** [comment]
No longer an issue in 20.04 or 21.10
