### ISSUE TITLE
Firefox prompts to make it the default browser on clean installs

### ISSUE THREAD

**Issue by leviport** [pop-os/pop#1706]
**Distribution (run `cat /etc/os-release`):**
 Pop!\_OS 20.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Firefox

**Issue/Bug Description:**
After a fresh install, opening Firefox shows me the "Make Firefox your default" prompt when I first run it. If I open my Default Application settings, I can see that Firefox is already my default web browser. 
![Screenshot from 2021-05-18 14-04-18](https://user-images.githubusercontent.com/13512097/118717305-21f38a00-b7e3-11eb-9cea-4a3a0f5cb2aa.png)

**Steps to reproduce (if you know):**
After a clean install, open firefox.

**Expected behavior:**
I wouldn't expect to see the "Make Firefox your default" prompt when it's already the default web browser.

**Other Notes:**
This is definitely a minor issue since it doesn't really break anything, and is only seen once after a clean install.

**Comment by bjr0421** [comment]
I can also confirm this is an issue for Pop!_OS, however, this is also an issue for Fedora.

**Comment by rajmondburgaj** [comment]
This happened to me on ubuntu 20.04 LTS as well, so I guess is not exactly pop os related.

**Comment by rsbrux** [comment]
There are posts on the Support forum going back 10 years for similar problems under various operating systems.  I have encountered this problem with the default snap installation of Firefox in both Ubuntu Studio 22.04 LTS and 24.04.1 LTS. Clicking on the "make default" button in Settings has no effect.  Firefox still doesn't realize that it is already the default. I am aware that I can stop Firefox from prompting me to make it default by disabling the check in Settings (or in about:config), but this is only a workaround for a long-standing, OS-independent bug which repeatedly bites many users.  What are the chances of getting it fixed?
