### ISSUE TITLE
21.04 can't add PPA

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/pop#1711]
**Distribution (run `cat /etc/os-release`):**
 Pop!OS 21.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
distro-info-data or likely pop-default-setting

**Issue/Bug Description:**
Customer needed to copy /usr/share/distro-info/ubuntu.csv >> pop.csv to add PPA's. He tested with Yubikey, Timeshift, and Nextcloud-client PPAs and was able to install packages

**Expected behavior:**
`sudo apt-add-repository  ppa:<your ppa here>` adds the PPA correctly to the system.

**Other Notes:**
This change was not needed in 20.10 or 20.04 in my testing.

**Comment by jackpot51** [comment]
Fixed in pop-default-settings 5.0.0, which I will release today
