### ISSUE TITLE
Mouse click doesn't work on resuming from suspend state

### ISSUE THREAD

**Issue by binayakdev** [pop-os/pop#1716]
**Distribution (run `cat /etc/os-release`):
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After resuming the computer from the suspend state the mouse click from the trackpad doesn't work. This doesn't happen all the time but it does happen frequently. Every time this happens, I have to reload the mouse driver using `sudo modprobe -r psmouse` and then `sudo modprobe psmouse`

**Steps to reproduce (if you know):**
Suspend the computer >> Resume the computer

**Expected behavior:**
1. The clicks from the trackpad are not registered
2. Sometimes the highlight/selection of the mouse doesn't go away

**Other Notes:**
Sometimes I have to reload the mouse driver a couple of times

**Comment by jacobgkau** [comment]
What model of touchpad/laptop is this? Does suspending and resuming again bring the mouse back? Have you tried any [i8042 options](https://lightrush.ndoytchev.com/random-1/i8042quirkoptions)? (I'd try `reset` first, followed by `noaux` and `nomux` if it doesn't work. You can apply them using e.g. `sudo kernelstub -a "i8042.reset"` and remove them using `sudo kernelstub -d "i8042.reset"`.)

**Comment by binayakdev** [comment]
Suspending and resuming seem to have worked but I am not sure. I tried the reset option and it didn't work. I will try out the noaux and nomux options and follow up.

**Comment by jacobgkau** [comment]
> Suspending and resuming seem to have worked but I am not sure.

I'm not sure I follow, you're not sure if the mouse worked or not after suspending/resuming a second time?

**Comment by binayakdev** [comment]
Yes I meant the second time. Also, I added the noaux option and I am not getting this issue anymore.
