### ISSUE TITLE
Missing ABNT/ABNT2 keyboard layout during installation

### ISSUE THREAD

**Issue by wcardozo** [pop-os/pop#172]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 LTS ( Testing )
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
Installer

**Issue/Bug Description**
Missing ABNT/ABNT2 keyboard layout during installation

**Steps to reproduce (if you know)**
Try to select a ABNT/ABNT2 during installaition

**Comment by brs17** [comment]
@wcardozo Thank you for submitting this issue. 
I believe right now, installations do not work in any language other than English. After the installation, in gnome-initial-setup you can once again pick a keyboard layout, is the `Portuguese (Brazil)` keyboard not the keyboard you are looking for? (layout below)

![port](https://user-images.githubusercontent.com/7460774/38218685-db6cce16-368f-11e8-9264-6339b872ec65.png)

**Comment by wcardozo** [comment]
Hi Ben,

Yes, after the installation I was able to select the right keyboard layout, no problem at all.

Thanks!

**Comment by RicardoSQueen** [comment]
Hello,
I'm having some issues as well, after choosing the Portuguese (Brazil) Keyboard. The layout I found was exactly like @brs17 showed, but it seems to be missing a key. The following image shows the keyboard layout 275 from ascii (same as ABNT2 - the current brazilian pattern):
![image](https://user-images.githubusercontent.com/64474885/94930588-07abac80-049d-11eb-83ea-b305b46b11c0.png)
The key left of the right shift seems to me missing, and can't find an option for the ABNT 2 layout.
The weird part is, sometimes the missing key works and sometimes it doesn't. haven't figured out a pattern yet.

**Comment by hugohernani** [comment]
I am having the same issue here. ABNT 2 (with interrogation mark near right shift) is not available on pop os first startup.

**Comment by jefferson-jscode** [comment]
Same issue. There is a key missing in the left of the right Shift key with  the characters /?°.

**Comment by neosoyo** [comment]
same here, no abnt2 layout
