### ISSUE TITLE
Elementary App Center failed to update infinite pop-ups

### ISSUE THREAD

**Issue by gregbenner** [pop-os/pop#173]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
io.elementary.appcenter

**Issue/Bug Description**
Popups many popups, all failed to update

![screenshot from 2018-04-02 10-11-50](https://user-images.githubusercontent.com/1177690/38215854-0bddfd20-3697-11e8-9d02-1d3216836488.png)

**Steps to reproduce (if you know)**
open it

**Expected behavior**
no popups, no errors

**Other Notes**

**Comment by brs17** [comment]
@gregbenner Are you connected to the internet when this popup appears?

**Comment by gregbenner** [comment]
Yes 80mb/s so much internet

**Comment by gregbenner** [comment]
is there a CLI way to try updating the package maybe?

**Comment by gregbenner** [comment]
Oh I found a way to enable debugging. Looks like my problem is emoji's
![screenshot from 2018-04-02 17-05-47](https://user-images.githubusercontent.com/1177690/38216255-3d1e0794-3698-11e8-937b-cbc7ca533c87.png)

**Comment by brs17** [comment]
You added that repository yourself?

**Comment by gregbenner** [comment]
Yeah I think so as part of a Riot chat client install, any tips to remove it I guess?

**Comment by brs17** [comment]
That repository is not built for 17.10.

GUI way to remove it is to open up the "Software and Updates" program.
Go to the "Other Software" tab and remove that PPA.

**Comment by gregbenner** [comment]
Thanks will give it a go
