### ISSUE TITLE
System randomly freezes and stops sending video signal.

### ISSUE THREAD

**Issue by AKA-Beastmaster** [pop-os/pop#1732]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
There doesn't seem to be a related application or package.

**Issue/Bug Description:**
My computer will randomly freeze. The screen freezes and the keyboard/mouse become unresponsive. For a couple of seconds the computer still plays back audio, but after a bit, the audio stops, and the screen turns black. The computer then stops sending a video signal and the only way to recover to press the reset button on my PC.

**Steps to reproduce (if you know):**
I do not know.

**Expected behavior:**

My computer should not do the issue mentioned.

**Other Notes:**
I am using 16 gigs of RAM along with an AMD Athlon 3000G with its integrated graphics.

**Comment by bflanagin** [comment]
Checkout the support article below, and let us know if anything comes of it. 
https://support.system76.com/articles/freezing-behavior

**Comment by AKA-Beastmaster** [comment]
> Checkout the support article below, and let us know if anything comes of it.
> https://support.system76.com/articles/freezing-behavior

Sorry for the late reply, after running the memtest, I got some errors:

`memtester version 4.3.0 (64-bit)
Copyright (C) 2001-2012 Charles Cazabon.
Licensed under the GNU General Public License version 2 (only).

pagesize is 4096
pagesizemask is 0xfffffffffffff000
want 9216MB (9663676416 bytes)
got  9216MB (9663676416 bytes), trying mlock ...locked.
Loop 1/3:
  Stuck Address       : ok         
  Random Value        : ok
  Compare XOR         : ok
  Compare SUB         : ok
FAILURE: 0xcf17c9fa7bdd00bc != 0xcf17c9ea7bdd00bc at offset 0x41ae3ea0.
  Compare MUL         :   Compare DIV         : ok
  Compare OR          : ok
  Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
  Checkerboard        : ok         
  Bit Spread          : ok         
  Bit Flip            : ok         
  Walking Ones        : ok         
  Walking Zeroes      : ok         
  8-bit Writes        : -FAILURE: 0x7fd3a4107bfeee6b != 0x7fd3a4307bfeee6b at offset 0x3af9b280.
  16-bit Writes       : -FAILURE: 0xf3ff29e332ebe6e6 != 0xf3ff29f332ebe6e6 at offset 0x49b5c480.

Loop 2/3:
  Stuck Address       : ok         
  Random Value        : ok
  Compare XOR         : ok
FAILURE: 0x8b866e9ec69e1299 != 0x8b866ebec69e1299 at offset 0x404dc0a0.
  Compare SUB         : FAILURE: 0xab1d7fda30c8d219 != 0xc81aeffa30c8d219 at offset 0x404dc0a0.
FAILURE: 0x6d57c0c384a2cd55 != 0x6d57c0d384a2cd55 at offset 0x418c0c80.
  Compare MUL         : FAILURE: 0x00000007 != 0x00000008 at offset 0x404dc0a0.
FAILURE: 0x2000000008 != 0x00000008 at offset 0x48d79c80.
  Compare DIV         : FAILURE: 0x3ff67bba1adf2a4f != 0x3ff67bba1adf2a4e at offset 0x404dc0a0.
  Compare OR          :   Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
  Checkerboard        : ok         
  Bit Spread          : ok         
  Bit Flip            : ok         
  Walking Ones        : ok         
  Walking Zeroes      : ok         
  8-bit Writes        : ok
  16-bit Writes       : -FAILURE: 0x1d9da34f6d6de3a9 != 0x1d9da36f6d6de3a9 at offset 0x3c18dca0.

Loop 3/3:
  Stuck Address       : ok         
  Random Value        : ok
FAILURE: 0xd9998649c346e56 != 0xd9998449c346e56 at offset 0x4e956240.
FAILURE: 0x3f62f2f1e83596fc != 0x3f62f2e1e83596fc at offset 0x4e956260.
  Compare XOR         : FAILURE: 0xc7a3efe9dbe5d349 != 0xc7a3eff9dbe5d349 at offset 0x4c094a00.
  Compare SUB         : FAILURE: 0xbb67daec539208f9 != 0xc8e55dfc539208f9 at offset 0x4c094a00.
  Compare MUL         : FAILURE: 0x2000000000 != 0x00000000 at offset 0x46e96240.
FAILURE: 0x1000000000 != 0x00000000 at offset 0x4879a840.
  Compare DIV         : FAILURE: 0x7b7e3a7c33b72eef != 0x7b7e3a6c33b72eef at offset 0x4879a840.
  Compare OR          :   Compare AND         : ok
  Sequential Increment: ok
  Solid Bits          : ok         
  Block Sequential    : ok         
  Checkerboard        : ok         
  Bit Spread          : ok         
  Bit Flip            : ok         
  Walking Ones        : ok         
  Walking Zeroes      : ok         
  8-bit Writes        : ok
  16-bit Writes       : ok

Done.
`
I haven't had a chance to do the other tests yet, I'll do them tomorrow.

**Comment by bflanagin** [comment]
That will cause what you're seeing. I'd pull out all but one stick of ram and run memtester again, do this for each stick of ram until you find the bad one. It will be time consuming, but you shouldn't run into any issues once the bad stick is isolated and removed.

**Comment by AKA-Beastmaster** [comment]
> That will cause what you're seeing. I'd pull out all but one stick of ram and run memtester again, do this for each stick of ram until you find the bad one. It will be time consuming, but you shouldn't run into any issues once the bad stick is isolated and removed.

Ah, alright, thank you.
