### ISSUE TITLE
The Gimp clone tool will can not aquire a sample of the active image in PopOS. 

### ISSUE THREAD

**Issue by Robin-MC** [pop-os/pop#1735]
The Gimp clone tool will not work on PopOS. It works on Lubuntu on the same machine (Lubuntu booted from external USB with Gimp installed)  I found an ubuntu fix on the internet, to tick a box in the Mouse setup panel, but the tick-box is not there on POP.
The reports of the same problem on the web are mostly on Mac & Windows The clone tool itself works to apply texture but when set to "Image" the control-click looks as if it works but when I start to try to apply the cloning I get an "set a source image first" message.  I can work round the problem by booting into Lubuntu, but I thought that it should be fed back

**Comment by Robin-MC** [comment]
I found the fix from the internet. I was mistaken, it was from "Hans" a linuxmint forum. https://forums.linuxmint.com/viewtopic.php?t=208772

**Comment by Robin-MC** [comment]
This is the Ubuntu one from Hairboy  http://gimp.1065349.n5.nabble.com/Clone-tool-not-working-td39294.html#a40866

**Comment by leviport** [comment]
> This is the Ubuntu one from Hairboy http://gimp.1065349.n5.nabble.com/Clone-tool-not-working-td39294.html#a40866

From this link, it looks like the fix is to disable the "Show pointer location when Ctrl key is pressed". I don't believe this setting is set by default on Pop!\_OS, so I don't think we should keep this issue open. If the same setting breaks the clone tool in the same way upstream, as well as in other Ubuntu downstreams, then I think an upstream bug report would be better.

**Comment by Robin-MC** [comment]
All I know is that the clone tool is not working in POP whereas it is in lubuntu. Can i fix that?

**Comment by leviport** [comment]
As the link says, make sure that gsetting is deactivated:

1) If you haven't already installed gnome-tweaks, you can do so either in Pop!\_Shop or by running `sudo apt install gnome-tweaks`
2) Open gnome-tweaks and go to the "Keyboard and Mouse" section
3) Make sure the "Pointer Location" setting is disabled:
![2021-06-18_09-19](https://user-images.githubusercontent.com/13512097/122583659-bcc7ca00-d016-11eb-8f19-3d5ef8158327.png)

When I turned that setting on, it also broke the clone tool for me, so I'm pretty sure that's the issue.

**Comment by Robin-MC** [comment]
Yes, That has fixed it!
Thank you for your help

**Comment by leviport** [comment]
You're welcome!
