### ISSUE TITLE
Unable to scroll on results of Gnome search

### ISSUE THREAD

**Issue by rdgh8** [pop-os/pop#1739]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome 3.38.3

**Issue/Bug Description:**

I am unable to scroll on the results of Gnome search. 

**Steps to reproduce (if you know):**

1. Hit the super key to enter Activities
2. Type something into the search box
3. Attempt to scroll using your scroll wheel

**Expected behavior:**

Scrolling of results 

**Other Notes:**

See video here:

https://user-images.githubusercontent.com/66289396/122658064-ea0b9980-d136-11eb-99cd-f4fcf12e42f6.mp4

**Comment by jacobgkau** [comment]
I don't think that area is supposed to scroll, but it does look like the last icon is cut off.

It looks like you're using a lot of GNOME Shell extensions. If you disable those using the Extensions app (green icon), does the issue still occur? What shell and GTK themes are you using? What is your screen resolution?

**Comment by rdgh8** [comment]
Extensions: Dash to Panel, GSConnect, Just Perfection, User Themes
Themes: Skeuos-blue-dark (applications), Flat-remix-blue-dark-fullpanel (shell), others are default
Resolution: 1080p

Interesting, I didn't turn change anything but the issue seems to have fixed itself. I guess it isn't supposed to scroll but the icons are now all fully visible.
