### ISSUE TITLE
On login screen, cannot press enter after typing password to login

### ISSUE THREAD

**Issue by juanton69** [pop-os/pop#174]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - 

 NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
SDDM login screen
KDE Lock screen

**Issue/Bug Description**
After typing password cannot press enter to login

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
@juanton69 thank you for filing an issue.

Pop!_OS is a GNOME based distribution and we are focused on providing the best possible experience with GNOME.

This is not something we are going to put time into to reproduce but I would recommend you asking around on the [Pop!_chat](http://chat.pop-os.org) to see if anyone else has had similar issues.
