### ISSUE TITLE
2021-06-22 Upstream Updates

### ISSUE THREAD

**Issue by jackpot51** [pop-os/pop#1742]
## All

- [ ] linux - https://launchpad.net/ubuntu/+source/linux/5.11.0-20.21
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] linux-firmware - https://launchpad.net/ubuntu/+source/linux-firmware/1.197.1
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] mesa - https://launchpad.net/ubuntu/+source/mesa/21.0.1-2
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] virtualbox - https://launchpad.net/ubuntu/+source/virtualbox/6.1.18-dfsg-5
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released

## 20.04

- [ ] gnome-online-accounts - https://launchpad.net/ubuntu/+source/gnome-online-accounts/3.36.1-0ubuntu1
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] gnome-shell - https://launchpad.net/ubuntu/+source/gnome-shell/3.36.9-0ubuntu0.20.04.2
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] mutter - https://launchpad.net/ubuntu/+source/mutter/3.36.9-0ubuntu0.20.04.1
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] systemd - https://launchpad.net/ubuntu/+source/systemd/245.4-4ubuntu3.7
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released

## 20.10

- [ ] systemd - https://launchpad.net/ubuntu/+source/systemd/246.6-1ubuntu1.4
    - [x] pushed to git
    - [x] built in proposed
    - [ ] tested in proposed
    - [ ] released

## 21.04

- [ ] flatpak - https://launchpad.net/ubuntu/+source/flatpak/1.10.2-1ubuntu1
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] gnome-control-center - https://launchpad.net/ubuntu/+source/gnome-control-center/1:3.38.5-1ubuntu1
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] gnome-shell-extension-multi-monitors - https://launchpad.net/ubuntu/+source/gnome-shell-extension-multi-monitors/23-1
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [x] gnome-shell-extension-ubuntu-dock - https://launchpad.net/ubuntu/+source/gnome-shell-extension-ubuntu-dock/69ubuntu1
    - [x] pushed to git
    - [x] built in proposed
    - [x] tested in proposed
    - [x] released
- [ ] mozc - https://launchpad.net/ubuntu/+source/mozc/2.26.4220.100+dfsg-4ubuntu3
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released
- [ ] steam - https://launchpad.net/ubuntu/+source/steam/1:1.0.0.68-1ubuntu1
    - [ ] pushed to git
    - [ ] built in proposed
    - [ ] tested in proposed
    - [ ] released

**Comment by jacobgkau** [comment]
linux, linux-firmware, mesa tested on:
- darp7
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio (HDMI & DP), including 4k@60Hz
    - [X] Hotkeys
        - Airplane mode key only enables airplane mode; also happening on current kernel.
    - [X] Suspend/resume w/ Firefox video
    - [X] Powers off
    - [X] WiFi speed test before suspend
    - [X] WiFi speed test after suspend
- oryp7 (3070)
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio (HDMI & DP)
    - [X] Hotkeys
        - Airplane mode key only enables airplane mode; also happening on current kernel.
    - [X] Suspend/resume w/ Firefox video
    - [ ] Graphics switching works
        - https://github.com/system76/firmware-open/issues/160 still applies.
    - [X] Powers off
    - [X] WiFi speed test before suspend
    - [X] WiFi speed test after suspend
- serw12 (2070)
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio (HDMI & DP)
    - [X] Hotkeys
    - [X] Suspend/resume w/ Firefox video
    - [X] Powers off
    - [X] WiFi speed test before suspend
    - [X] WiFi speed test after suspend
- gaze14 (1650)
    - [X] Audio ports
    - [X] Display outputs & configuration w/ audio (HDMI & DP)
    - [X] Hotkeys
    - [X] Suspend/resume w/ Firefox video
    - [X] Powers off
    - [X] WiFi speed test before suspend
    - [X] WiFi speed test after suspend

@bflanagin is taking a look at these components on desktops.

**Comment by bflanagin** [comment]
linux,linux-firmware,mesa test on:

* Thelio-B2
  - [x] Wifi speed tests Suspend (before/after) 
  - [x] Wired Ethernet 
  - [x] Audio
  - [x] Suspend/ Resume
  - [x] Powers off  
  -  Nvidia 2080 ti
     - [x] Suspend/resume w Firefox video
     - [x] Video and audio out DP/HDMI
  - Radeon RX580
     - [x] Suspend/resume x Firefox video
     - [x] Audio out DP/HDMI

* Thelio-R1
   - [x] Wifi speed tests suspend (before/after)
   - [x] Wired Ethernet
   - [x] Audio
   - [x] Suspend/Resume
   - [x] Powers Off
   - Radeon RX 5500 XT
     - [x] Suspend/Resume w Firefox video
     - [x] Video and audio out DP/HDMI

**Comment by jackpot51** [comment]
Is linux, linux-firmware, mesa ready to release?

**Comment by jackpot51** [comment]
I will release Monday just to be safe

**Comment by bflanagin** [comment]
* Meer6
  - [x] Wifi speed tests Suspend (before/after) 
  - [x] Wired Ethernet 
  - [x] Bluetooth 
  - [x] Audio HDMI (no mic)
  - [x] Suspend/ Resume
  - [x] Powers off  
  
* Meer5
  - [x] Wifi speed tests Suspend (before/after) 
  - [x] Wired Ethernet 
  - [x] Audio 
  - [x] Bluetooth 
  - [x] Suspend/ Resume
  - [x] Powers off  
  - [x] HDMI (Audio/Display)

**Comment by bflanagin** [comment]
Same tests run on Mira-r1,Massive-b3,Major-r1.1. All passed.

**Comment by bflanagin** [comment]
VirtualBox:
- [x] Installs 
- [x] Existing virtual machines boot (Windows 10, Pop!_OS 21.04)
- [x] New Virtual machines can be created. (tested 21.04 as guest)
- [x] Virtual machine guest driver packages install properly on Linux guest.
