### ISSUE TITLE
Desktop Enviroment leaving ghost windows open

### ISSUE THREAD

**Issue by AMoonRabbit** [pop-os/pop#1749]
**Distribution:**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Issue/Bug Description:**
When minimising windows, a ghost version of the window remains in the background. Any interactions in the area of this ghost window result in interactions with the desktop area.  Suspect this could be something to do with X11?

**Expected behavior:**
Minimising windows shoulld remove the visible window

**Other Notes:**
Seems to take a snapshot of the window as you can have an application full screen or in the snap mode and minimise it but the floating "restored" window will remain on the desktop

![Screenshot from 2021-06-27 13-04-51](https://user-images.githubusercontent.com/3766988/123543826-534b6800-d748-11eb-9528-25efece0ecff.png)
This screenshot actually has no windows open, this is everything minimised

**Comment by helios2k6** [comment]
I'm also noticing this as well, and it's not X11 specific. I'm running this on Wayland. This defect is also visible when switching between workspaces -- previously visible windows in the prior workspace will still appear in the new (empty) workspace.

**Comment by AMoonRabbit** [comment]
Closing this as I have re-logged this under the shell repo https://github.com/pop-os/shell/issues/1140
