### ISSUE TITLE
Warning on running "sudo apt update"

### ISSUE THREAD

**Issue by lulzsec14** [pop-os/pop#1751]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
apt list

**Issue/Bug Description:**
On running **sudo apt update** a warning is shown. 

`Hit:1 http://ppa.launchpad.net/system76/pop/ubuntu groovy InRelease`                                    
`Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease`                 
`Get:3 http://apt.pop-os.org/proprietary groovy InRelease [8,438 B]`                              
`Hit:4 http://us.archive.ubuntu.com/ubuntu groovy InRelease `
`Hit:5 http://us.archive.ubuntu.com/ubuntu groovy-security InRelease`
`Hit:6 http://us.archive.ubuntu.com/ubuntu groovy-updates InRelease`
`Hit:7 http://us.archive.ubuntu.com/ubuntu groovy-backports InRelease`
`Fetched 8,438 B in 2s (4,025 B/s)`
`Reading package lists... Done`
`Building dependency tree`
`Reading state information... Done`
`All packages are up to date.`
`W: Conflicting distribution: http://apt.pop-os.org/proprietary groovy InRelease (expected groovy but got stable)`

**Steps to reproduce (if you know):**
just running **sudo apt update** on my system shows warning like this, don't know about other systems.

**Expected behavior:**
Should show no warnings.

**Other Notes:**

**Comment by bflanagin** [comment]
Support for Pop!_OS 20.10 has ended. Please upgrade to 21.04 and resubmit the issue if you are still experiencing the problem.

**Comment by jacobgkau** [comment]
There's a support article about upgrading here: https://support.system76.com/articles/upgrade-pop#upgrading-pop_os-to-2104-from-2010 

Visit Settings -> OS Upgrade or run `pop-upgrade release upgrade` in a terminal.
