### ISSUE TITLE
Incorrect mouse 'low battery' pop-up

### ISSUE THREAD

**Issue by the-questjon** [pop-os/pop#1757]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Settings

**Issue/Bug Description:**

Keep getting pop-up notifying me of low battery in my mouse, even after changing to a new, full powered battery. When I click on the notification it takes me to the Mouse and Keyboard battery status page where it recognises that the mouse in fact has full battery as indicated by the full, green coloured meter/gauge.

**Steps to reproduce (if you know):**

Login to a new session.

**Expected behavior:**

Pop-up notifying me of mouse low battery status.

**Other Notes:**

This isn't release specific as was the same in the 20.04 LTS release.
I am using a Logitech M720 Triathlon Mouse and MX keyboard on a single Unifying USB receiver.

![IMG_20210630_202541](https://user-images.githubusercontent.com/86742897/124019881-83f9fe80-d9e1-11eb-9d83-d9bec2cf65d4.jpg)

![IMG_20210630_202532](https://user-images.githubusercontent.com/86742897/124019914-8c523980-d9e1-11eb-80fb-9000dd51f6db.jpg)

**Comment by bflanagin** [comment]
I notice that your keyboard's battery is a little low. Does the message go away (or not appear) if they're both at full power?

**Comment by the-questjon** [comment]
D'oh! I'm so literal. I have charged my keyboard and the notifications have stopped. Thanks and apologies for being so dumb.
