### ISSUE TITLE
I can't open the the settings (gnome-control-center) on pop-os after the update to 21.04

### ISSUE THREAD

**Issue by jannnis** [pop-os/pop#1762]
**Distribution :**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version:**
gnome-control-center:
```
  Installiert:           1:3.38.3-1pop1~1624555020~21.04~668f3c0
  Installationskandidat: 1:3.38.3-1pop1~1624555020~21.04~668f3c0
  Versionstabelle:
     1:3.38.5-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
 *** 1:3.38.3-1pop1~1624555020~21.04~668f3c0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
I can't open gnome-control-center as normal user, it works fine if I try to open it as a privileged user. When I try to open it via the terminal it shows: 

```
(gnome-control-center:9299): GLib-GIO-ERROR **: 15:05:08.160: Settings schema 'org.gnome.shell.extensions.dash-to-dock' does not contain a key named 'manualhide'
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)

```
I tried to solve the issue by adding the key manualhide to the config using: `dconf write /org/gnome/shell/extensions/dash-to-dock/manualhide true`

**Steps to reproduce (if you know):**
The Issue started to appear after the upgrade to 21.04 from 20.10. I had the gnome extension dash-to-dock installed before the update.

**Comment by bucky2076** [comment]
yeah me too... is there a workaround for this ?

**Comment by Vlek** [comment]
I was having this same issue. There was a new update for some Pop libs that may have resolved the issue.

**Comment by bucky2076** [comment]
yes the update came through and is all good now. well done all.
