### ISSUE TITLE
error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FiloSpaTeam** [pop-os/pop#1767]
**Distribution (run `cat /etc/os-release`):**
```bash
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```bash
otpclient:
  Installato: (nessuno)
  Candidato:  2.4.2-1build1
  Tabella versione:
     2.4.2-1build1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages
```

**Issue/Bug Description:**
As title

**Steps to reproduce (if you know):**
1. Install otpclient package
2. Run it

**Expected behavior:**
Should works as expected

**Other Notes:**

**Comment by jacobgkau** [comment]
As you can see from your `apt policy otpclient` output, the `otpclient` package is coming from upstream Ubuntu. Does this issue also occur on Ubuntu?

Your `apt policy otpclient` output also indicates you do not have the package installed. How did you install otpclient? Are you using the flatpak package?

I am not seeing this issue on Pop!_OS 21.04 with either the deb package or the flatpak package. Where are you seeing the error message? Can you provide a screenshot?

**Comment by FiloSpaTeam** [comment]
I need to admit that i don't remember how i installed this package in the past...
I removed the package, reinstalled with apt and actually (without libzip.so.5) it's working.

I apologize for the false positive.
