### ISSUE TITLE
pop-cosmic-launcher.desktop not working

### ISSUE THREAD

**Issue by tino242424** [pop-os/pop#1768]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-cosmic-launcher.desktop

**Issue/Bug Description:**
After the upgrade from Pop os 20.04 LTS to 21.04, I can't launch the launcher.
If I click on super button nothing happens, if I click on the desktop shortcut "pop-cosmic-launcher.desktop" nothing happens too.

**Steps to reproduce (if you know):**
Upgrade POP os from 20.04 LTS to 21.04
click on the shortcut "pop-cosmic-launcher.desktop"

**Expected behavior:**
launcher open on a window

**Other Notes:**
I have no clue how to launch the launcher from the terminal to see errors messages

**Comment by ids1024** [comment]
The launcher is provided the Pop Shell extension. In the Extensions app, is that extension enabled with no errors shown?

`journalctl /usr/bin/gnome-shell` also shows errors from Gnome Shell.

**Comment by tino242424** [comment]
Thank you very munch :-)

The Pop Shell extension was not enabled, now it is working
