### ISSUE TITLE
Sluggish Laggy OS Performance w/ random freezes after Upgrade to 21.04 on Oryx Pro

### ISSUE THREAD

**Issue by barthvader13** [pop-os/pop#1769]
**Distribution:**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

KERNEK=Linux 5.11.0-7620-generic x86_64
 ```

Laptop is set to Nvidia Graphics Mode with the High Performance -  Power Profile

I'm using two external monitors - one via hdmi, one via display-port

I have a usb hub with a mouse and keyboard plugged in.

**Issue/Bug Description:**

I have an 2020 Oryx Pro. I upgraded to 21.04 yesterday and I've noticed some very sluggish performance from the system. This happens afaik after at least an hour of uptime but basically there's: **keyboard input lag**, **random menu animations feeling sluggish or laggy**, and also **random screen freezes** that seem to have something to do with gnome? I've been able to alt+f2 and r to reset some of the freezes but a couple times I had to just restart.

Just a couple minutes ago **the entire system froze for a few seconds** similar to the old freeze bug in 20.04 (that was resolved as a Kernel issue I think?) and then **one of my external monitors just went blank**. This was while I was on a zoom call with audio/video looking at a miro board in chrome. I was able to press the super key and after a few seconds the os unfroze but I had to re-plug in the monitor to get the laptop to use it again - it was the display-port if that's relevant.

Another weird anecdote is that I've noticed that the fans don't seem to be starting up as much and the CPU utilization of most applications is generally lower than before - except for **gnome-shell which is taking up 70%+ of CPU**. IDK if this has anything to do with the issue or if this normal - just throwing that out there. 

![image](https://user-images.githubusercontent.com/5341581/124316670-925c2d80-db3b-11eb-9f48-ad061cf3ee94.png)

Also this may be just my perception but the **system-monitor application resources tab seems to update its graphs very rigidly** when compared to 20.10. I feel like it used to be more fluid, not as static/robotic updating graphs on the second, if that makes sense. 

The final super random thing that I wanted to note was that yesterday after I updated and after a couple hours of use - **the audio on my laptop randomly turned to MONO**. All audio was only coming out of the LEFT speaker on the laptop (I verified it was the laptop not the speakers after plugging my phone directly into aux of speakers) Again, IDK if this has anything to do with the sluggish/laggy system but I figured it'd be worth mentioning since it has never happened before now.

I know I'm throwing a lot of random things out here but I figured its better to include as much information as possible in case any of it is relevant.

**Steps to reproduce (if you know):**
As far as I know, I cannot reproduce this issue because it occurs randomly for a bit after about an hour of uptime.

After some time it becomes unbearable to the point where everything is lagging - literally clicking the time/date panel -  and I have to restart the computer. My first guess would be something like a memory leak maybe but I have no idea.

I found a [reddit thread](https://www.reddit.com/r/pop_os/comments/obxe7z/cursor_freezes_or_lagging_keyboard_also_does_this/) describing somewhat similar issues.

[recent issue with gnome-shell problems after screen lock](https://github.com/pop-os/pop/issues/1766)
- I have caffeine on all the time so I don't think my problem is the same, but maybe worth mentioning..?

And obviously there's been a bunch of [threads/issues](https://github.com/pop-os/pop/issues/1172)opened up about the old freezing bugs that may have to do with the kernel?

**Other Notes:**

Applications that are usually running when this happens:
- Slack
- VSCode
- Discord
- Chrome
- Zoom
- Sublime
- Konsole

Gnome Extensions I have installed:
- Clipboard Indicator
- Dash to Panel
- Applicaitons Menu
- Emoji Selector
- User Themes
- system-monitor is installed but not selected
- Cosmic Dock off  
- Pop Cosmic on

![image](https://user-images.githubusercontent.com/5341581/124315121-15c84f80-db39-11eb-82e6-14593c4a1319.png)

**Comment by barthvader13** [comment]
I think this has something to do with the `gnome-shell` - I find myself having to restart gnome via `ALT + F2 - r` every couple hours because of how much the CPU usage spikes.

**Comment by barthvader13** [comment]
linking to an [issue](https://github.com/pop-os/pop/issues/1750) that seems similar - Oryx Pro user experiencing system freezes as well (though they're on 20.10)

**Comment by bflanagin** [comment]
@barthvader13 what output do you see when you run nvidia-smi in the terminal?

**Comment by barthvader13** [comment]
I have nvidia updated afaik

```
Fri Jul 16 11:10:05 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 2060    Off  | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P3    27W /  N/A |    973MiB /  5934MiB |     32%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      5905      G   /usr/lib/xorg/Xorg                450MiB |
|    0   N/A  N/A      6509      G   /usr/bin/gnome-shell               97MiB |
|    0   N/A  N/A     12523      G   ...AAAAAAAAA= --shared-files       23MiB |
|    0   N/A  N/A     12872      G   ...AAAAAAAAA= --shared-files      246MiB |
|    0   N/A  N/A     15829      G   /opt/zoom/zoom                     46MiB |
|    0   N/A  N/A     16163      G   ...AAAAAAAAA= --shared-files       24MiB |
|    0   N/A  N/A     16392      G   ...AAAAAAAAA= --shared-files       10MiB |
+-----------------------------------------------------------------------------+

```

**Comment by mmstick** [comment]
You have quite a few extensions. How does it perform with stock settings?

**Comment by barthvader13** [comment]
Over the past few days I've disabled every extension except for dash-to-panel and still seen the issue. I don't think its dash-to-panel but I will disable it as well  and get back to you. 

The more I've been reading online, the more I think this is a `gnome-shell` issue not necessarily a `popos` specific issue.

It's frustrating tho because I find myself needing to restart gnome `ALT+F2 r` every couple hours to avoid the sluggish performance.

Pop!_OS is my first linux distro, is there another shell I could try to use or is gnome kinda "built-in" to the os?

**Comment by barthvader13** [comment]
I turned off all extensions including`dash-to-panel` the last two days and `gnome-shell` hasn't had any obvious problems... :grimacing: so I guess you were right - it was extensions. :upside_down_face: weird that the cpu spike wasn't happening before the upgrade to 21.04 though..?


I'm going to stick to vanilla popos cosmic settings for now. Just FYI - some of the UX and workflows kinda suck now that I don't have the top panel available on all monitors. I know that's something System76 is aware of and going to implement in future updates so I'll be looking out for that.

![image](https://user-images.githubusercontent.com/5341581/126244544-32b2ce69-78e8-40e5-a96e-be013d61345e.png)

Thanks!

**Comment by erwstout** [comment]
Wow. I am still having this issue as well even on Pop!_OS 21.10 - disabling my (two) extensions seems to fix the issue. Kind of a bummer!

**Comment by jacobgkau** [comment]
> Wow. I am still having this issue as well even on Pop!_OS 21.10 - disabling my (two) extensions seems to fix the issue. Kind of a bummer!

If the issue stops happening when you disable a third-party extension, you may want to investigate why that extension is causing lag. Or if the issue can also be stopped when you disable one of the built-in extensions (indicating some kind of conflict between the built-in extensions and the ones you're adding), then include that information.

**Comment by erwstout** [comment]
> > Wow. I am still having this issue as well even on Pop!_OS 21.10 - disabling my (two) extensions seems to fix the issue. Kind of a bummer!
> 
> If the issue stops happening when you disable a third-party extension, you may want to investigate why that extension is causing lag. Or if the issue can also be stopped when you disable one of the built-in extensions (indicating some kind of conflict between the built-in extensions and the ones you're adding), then include that information.

Thanks for the reply!

The two extensions I was using were **OpenWeather** and **Transparent Topbar**

I'll have to investigate further after work but Transparent Topbar does not seem to even work correctly with the latest version of Pop_OS so disabling it is kind of a wash. However, even with just OpenWeather it is still laggy. Will reboot with just OpenWeather and see how it goes from there and report back!

**Comment by hungLink** [comment]
I don't have any extensions, and I get laggy behavior that is fixed by restarting the gnome shell via `ALT+F2 r` how does one go about investigating the lag as jacobgkau mentioned.

I don't necissarily need in depth instructions, but some general tips and direction would be nice.
