### ISSUE TITLE
Pop OS ISO crashes

### ISSUE THREAD

**Issue by EmilZackrisson** [pop-os/pop#1770]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 21.04
Can't get terminal access.
 

**Issue/Bug Description:**
The Pop OS 21.04 ISO crashes after ~10 sec after the GUI pops up. Tested it on 2 computers and in Virtualbox and the same issue occurs. 

This is the screen from Virtualbox.
![bild](https://user-images.githubusercontent.com/51415707/124329500-d119d400-db8b-11eb-824b-c3f4b370a294.png)

**Comment by eesau65** [comment]
Same here. Downloaded the iso again and tried four different methods (Etcher, Gnome Disks, Ventoy and the command line) to create bootable USB, but no luck. Ventoy didn't boot at all, but it does that anyway with some isos.

**Comment by eesau65** [comment]
Ok, with _ethernet cable unplugged_ it seems to work.

**Comment by EmilZackrisson** [comment]
Thanks that worked perfectly.

**Comment by leviport** [comment]
Thanks for the report! We're testing a fresh batch of isos this morning, and we hope to have them released today. The bug does not appear to be present on these latest isos.
