### ISSUE TITLE
IBus crashes launcher

### ISSUE THREAD

**Issue by rongcuid** [pop-os/pop#1771]
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**Related Application:** application launcher

**Description:** When an IBus input method is used, (e.g. Chinese Pinyin), typing in launcher immediately crashes desktop

**Steps to reproduce (if you know):**

1. Enable Chinese Intellegent Pinyin input method
2. Use this input method
3. Press `Super` to open launcher
4. Type any letter
5. Desktop crashes and reload

**Expected behavior:** launcher accepts input like other apps

**Comment by rongcuid** [comment]
The same issue is in https://github.com/pop-os/shell/issues/967

**Comment by leviport** [comment]
Thanks for the report! Since this was already reported in pop-os/shell#967, I'm going to close this issue. It's much easier to track bugs when there aren't multiple open reports for the same item.
