### ISSUE TITLE
When in SteamVR games, bringing up workspaces overview causes system to be non-functional

### ISSUE THREAD

**Issue by TehGameMaster** [pop-os/pop#1774]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
SteamVR games - _Hellblade: Senua's Sacrifice VR_ + _Elite Dangerous VR_
_Only have the 2 games installed. I assume other games will do the same._

**Issue/Bug Description:**
When in a SteamVR game, if I press the superkey to bring up my workspaces overview, all my monitors darken slightly, all windows vanish, but the workspaces overview does not appear.

Can still move mouse cursor, but can't click anything.

Superkey+T brings up terminal _(darkened, like rest of screen)_, but can't type anything.

Ctrl+Atl+Delete brings up logout timer. Can click _"Logout Now"_, but just closes window _(can't click anything else)_. Need to wait for timer, to actually log out. _(Sometimes it just never logs out and I must hard shutdown)_

**Steps to reproduce (if you know):**
1: Set superkey to open workspaces overview.
2: Run a VR game through SteamVR.
3: When game is fully loaded press superkey to bring up workspaces overview or if possible click the _"Workspaces"_ button.

**Expected behavior:**
Should bring up workspaces overview so I can select a different workspace/window.

**Other Notes:**
Never happened in Pop_OS 20.10. Only started after upgrade.

Using Valve Index

Does not happen in SteamVR home. Only seems to affect games that use the monitor _(Hellblade puts fullscreen on main monitor and Elite Dangerous places a window)_.

When running Elite Dangerous, I can move my mouse around and interact with other windows, but the issue presents itself if I click the _"Workspaces"_ button.

Computer never locks up. I can always move the mouse and look around in VR.

Tested with several non-VR games _(all on Steam)_, both native Linux and Proton based. Windowed and fullscreen. Superkey brings up workspaces overview every time, without issue.

**Comment by bflanagin** [comment]
This one will be tricky due to the lack of hardware on our end. Could you provide us with the following logs by running the commands below:

```
sudo journalctl -r -n 100 > journal.txt
sudo dmesg > dmseg.txt

```

Also we might need to see the dbus output when you're running steem-vr as well. Use `dbus-monitor > dbus.txt` in a terminal and then go through the above tests to cause the issue. Hopefully this will capture the events.

**Comment by TehGameMaster** [comment]
I tested in Elite Dangerous and Hellblade, and was unable to replicate the problem. Pressing the superkey gave me the workspaces overview as it should.

The Steam client and SteamVR have both received several updates in the past week. I assume Valve fixed whatever was causing the conflict.

As this no longer seems to be an issue, I guess this can be closed.

Here are the files anyways, in case they may be useful.
[dbus.txt](https://github.com/pop-os/pop/files/6833801/dbus.txt)
[dmseg.txt](https://github.com/pop-os/pop/files/6833802/dmseg.txt)
[journal.txt](https://github.com/pop-os/pop/files/6833803/journal.txt)

Thanks.

**Comment by jacobgkau** [comment]
Glad to hear it's no longer happening after Steam updates! Let us know if it comes back.
