### ISSUE TITLE
Uptime of ~3+ days breaks Gnome: clock, menus, and icons dissapear until reboot.

### ISSUE THREAD

**Issue by Seltonu** [pop-os/pop#1775]
**Distribution (run `cat /etc/os-release`):**
 Pop 21.04

**Issue/Bug Description:**
When computer has been on for several days, Gnome breaks until system is rebooted. Top bar icons disappear (clock, some app icons, etc), and all Gnome menu options (top right menu, right click context menus, etc.). Generally this happens when uptime exceeds 3 days, and has occurred both on my desktop with no sleep, and my laptop with sleep enabled. 

**Steps to reproduce (if you know):**
Do not shut down system for several days. Generally between 3-5 days uptime, Gnome will suddenly break and menu/icons will disappear until reboot. No specific cause (application, etc.) determined aside from uptime, and this has been reproduced by me on 2 systems every few days for months now.

**Expected behavior:**
Gnome top bar should continue to display clock and icons regardless of uptime. Menus should continue to display options regardless of uptime.

**Other Notes:**
This issue was present in 20.10 as well. Disabling extensions does not fix it, only reboot does.

![gnome_topbar_bug](https://user-images.githubusercontent.com/10287568/124382267-5cbe5e00-dc7b-11eb-835a-8e0bc9fdbff1.png)

![gnome_2](https://user-images.githubusercontent.com/10287568/124382296-84152b00-dc7b-11eb-9ab7-9df6e0d24c52.jpg)
![gnome_1](https://user-images.githubusercontent.com/10287568/124382299-86778500-dc7b-11eb-9f48-ec8b729ba4d9.jpg)

**Comment by bflanagin** [comment]
Wow, that is weird. Mind giving us a little more information about your computer (CPU/Memory/GPU/etc.?) Also what are your power settings set at? A screenshot will do if you don't want to type them all out.

**Comment by Seltonu** [comment]
Yeah for sure! I generally never change my power settings just default Balanced, and I tend to use my desktop PC far more so I notice this issue there the most.

Laptop:
-Intel i7-8565U w/ integrated graphics
-HP Spectre x360 Convertible 13-ap0xxx
-SKU Number: 4CJ13AV

Desktop has been upgraded a few months ago, but this issue persisted even before the upgraded parts:
- CPU: Ryzen 5900x (formerly 3900x)
- GPU: 6800XT (formerly Vega 64)
- RAM: 64GB Nemix 3200MHz **ECC** (formerly 32GB HyperX)
- Motherboard: x570i Aorus Pro Wifi

I first noticed this issue months ago mostly on my desktop PC as I use it most, and continues despite nearly a full rebuild of the system so it's not a hardware issue. The fact that it also happens on my laptop assures me it's a software bug.

**Comment by ids1024** [comment]
> Top bar icons disappear (clock, some app icons, etc), and all Gnome menu options (top right menu, right click context menus, etc.).

Not sure exactly what would cause that, but it sounds like a Gnome Shell issue. `journalctl /usr/bin/gnome-shell` might have some relevant error messages.

**Comment by Seltonu** [comment]
Hmm so I took a look at the logs, I'm not seeing anything particularly that stands out. I'm seeing a lot of what appear to be errors, but these are spread throughout the logs, and I don't see anything unique at the time/date this bug occurred.

Here is a screenshot of the logs from while the bug was happening, based on the time stamp I took the photos and also you can see where I opened gnome-tweaks to try disabling extensions in the hopes it would help (it didn't).

![image](https://user-images.githubusercontent.com/10287568/124843602-1e5cc380-df47-11eb-9f22-0c04b79ce4da.png)

The error message is `Jul 04 03:39:53 blueberry gnome-shell[1680]: Object .Gjs_pop-cosmic_system76_com_topBarButton_CosmicTopBarButton (0x55570b4fc380), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs."`

but as noted, this error shows up at other times in the logs when the UI is working fine. Any ideas where I might look next? Or suggestions for what I should do to help debug before rebooting when it occurs again?

**Comment by bflanagin** [comment]
This issue must be more hardware specific than I first hoped. 

My machine has now been on for 6+ days with standard usage without fail which leads me to believe the issue is more hardware specific. @Seltonu are you using the Pop!_OS provided version or do you use something like [kisak-mesa's ppa](https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa) to get a newer version? If you are using the Pop!_OS version it might be worth trying the ones provided by the aforementioned ppa, If you are using a 3rd party source for mesa the the reverse might also be an option.

**Comment by Seltonu** [comment]
That's very interesting! I had this issue happen again after ~2.5 days of uptime a few days ago. I had assumed it *wasn't* hardware specific because it happens on my AMD CPU/GPU desktop, but also on my Intel (integrated GPU) laptop. Perhaps it's related to software I have installed, as it's the same on both systems. The only Gnome extension I add is ["Bluetooth quick connect"](https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/) and a quick scan of their Github doesn't show this issue reported by others. Also as noted, disabling extensions *while* the problem was occurring did not fix it.

I can fairly confidently say I don't think it's related to the Mesa version, as I have used both kisak's PPA and default Mesa over these last few months on my desktop PC and don't recall noticing any change. I have also used more recent kernels (now on kernel 5.13 when this last happened on my laptop) and no change.

I will try reverting to stock kernel and installing kisak's PPA on this laptop just to be sure, but do you have any recommendations for what to do in the moment when the UI bug happens again? I checked the gnome-shell logs when it happened again a few days ago, and again noticed nothing out of the ordinary.

**Comment by Seltonu** [comment]
Update: Kisak's PPA seems to have fixed the problem for now, I made it 6 days uptime without seeing the UI bug. Unfortunately I haven't been able to test for longer as I've needed to reboot. 

In about a week or two I will report back with updates on if Kisak's PPA fixes the issue on my Desktop PC, as that's where I noticed this bug the most, though I am currently moving and unable to setup yet.

Also NOTE: I realized I forgot I had enabled Wayland. I've wiped my laptop and am now testing a stock Pop to make sure this issue isn't present.

**Comment by Seltonu** [comment]
Update: I have not had this issue on stock Pop, I believe it is related to enabling Wayland before it's ready. With that in mind, I will close this issue as Wayland is not officially supported. Thank you for your time, and my apologies for the hassle.
