### ISSUE TITLE
App not launch after 21.04

### ISSUE THREAD

**Issue by AlexDep** [pop-os/pop#1776]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Snap app are not launched (installed on 20.04/20.10, both working):
spotify            1.1.55.498.gf9a83c60        46        latest/stable  spotify✓       -
freecad            0.19                        22        latest/stable  vejmarie       -
discord            0.0.15                      128       latest/stable  snapcrafters   -

Ubuntu (deb) from Pop!_Shop are not launched (installed after update):
Arduino IDE 

Flatpack from Pop!_Shop WORKING (installed after update) :
Arduino IDE 

**Issue/Bug Description:**
After update to 21.04 can't open this app anymore/

**Steps to reproduce (if you know):**
Update to 21.04 with this app installed and launch them.

**Expected behavior:**
They should open, work.

**Other Notes:**
Your distrib is great, but this update is not usable..

**Comment by bflanagin** [comment]
I can confirm that the Arduino IDE deb file isn't working. Unfortunately the package is maintained by Ubuntu and we will need to wait for an update from them for that issue to be resolved. However, it looks like the flatpak version is working so unless there is an issue with that version I would suggest using it instead. 

As far as snaps are concerned we don't officially support snap packages and would recommend you install the flatpak version of the other three application stated. If for some reason you must use the snap packages you can install snapd manually which should fix your issue.

**Comment by ids1024** [comment]
Upstream issue for Arduino package: https://bugs.launchpad.net/ubuntu/+source/arduino/+bug/1916278

**Comment by AlexDep** [comment]
I fixed this issues by installing again with Deb or snaps when possible all the package (mostly flatpacks) that didn't worked.
