### ISSUE TITLE
[18.04] Unable to switch right mouse button to primary

### ISSUE THREAD

**Issue by briggs1978** [pop-os/pop#178]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
When i try to change the primary mouse button in settings, the correct button highlights but the change does not happen.

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
Hello @briggs1978 thanks for submitting this issue.

I quickly tried to change the primary mouse button on a Galago Pro 3 and could not recreate the issue. On what hardware are you running Pop!_OS?

**Comment by briggs1978** [comment]
Dell XPS 13 9360 with touchscreen (that is disabled in bios)
`xinput list`
`⎡ Virtual core pointer                    	id=2	[master pointer  (3)]`
`⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]`
`⎜   ↳ DLL082A:01 06CB:76AF Touchpad           	id=11	[slave  pointer  (2)]`
`⎜   ↳ Logitech USB Optical Mouse              	id=12	[slave  pointer  (2)]`
`⎜   ↳ SynPS/2 Synaptics TouchPad              	id=18	[slave  pointer  (2)]`
`⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]`
`    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]`
`    ↳ Power Button                            	id=6	[slave  keyboard (3)]`
`    ↳ Video Bus                               	id=7	[slave  keyboard (3)]`
`    ↳ Power Button                            	id=8	[slave  keyboard (3)]`
`    ↳ Sleep Button                            	id=9	[slave  keyboard (3)]`
`    ↳ Integrated_Webcam_HD: Integrate         	id=10	[slave  keyboard (3)]`
`    ↳ Intel Virtual Button driver             	id=13	[slave  keyboard (3)]`
`    ↳ Intel HID 5 button array                	id=14	[slave  keyboard (3)]`
`    ↳ Intel HID events                        	id=15	[slave  keyboard (3)]`
`    ↳ Dell WMI hotkeys                        	id=16	[slave  keyboard (3)]`
`    ↳ AT Translated Set 2 keyboard            	id=17	[slave  keyboard (3)]
`

**Comment by briggs1978** [comment]
Oops.  I think I closed this accidentally.

**Comment by brs17** [comment]
So we don't have access to a touch screen machine like that but I would say if you're able, hop into the [Pop!_Chat](http://chat.pop-os.org/) and ask around if anyone has had a similar issue (or can recreate the issue). I'm going to keep investigating as I can, but I'm thinking/hoping your quickest fix could be in the Pop!_Chat.

**Comment by briggs1978** [comment]
Sorry to waste your time.  I realized that a USB-C/Thunderbolt dock I'm plugged into could be gumming up the works. I unplugged the mouse from the dock and when I plugged it directly into the computer, the change worked.  

Thanks for your help!
