### ISSUE TITLE
21.04 Bluetooth unavailable in GUI after hibernate

### ISSUE THREAD

**Issue by sebltm** [pop-os/pop#1782]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Bluetooth issues after wake from hibernate: Bluetooth works (through `bluetoothctl`), when a device is connected it appears as so in the small top right hand menu, but through the System settings, the Bluetooth settings page says "No Bluetooth Found. Plug in a dongle to use Bluetooth"

**Steps to reproduce (if you know):**
Enable hibernate through something like this: https://pop-planet.info/forums/threads/guide-to-hibernate-answer-is-a-guide.426/
Restart pop-os, Bluetooth should work normally.
Put the system to sleep through: `sudo systemctl hibernate`
Wake the system from hibernate: Bluetooth now shows as not found in System settings, but still works through `bluetoothctl`
Restart the system: everything works as normal

**Expected behavior:**
Bluetooth should still work as normal through System settings after wake from hibernate

**Comment by bflanagin** [comment]
Sorry for your issue @sebltm unfortunately this is the reason we don't ship Pop!_OS with hibernate enabled by default. When we revisit hibernation we'll be sure to test bluetooth, until then the only answer we have for you is to go back to suspending your computer instead.
