### ISSUE TITLE
At low screen resolutions, Applications icons oversized after restart

### ISSUE THREAD

**Issue by PranavDalvi** [pop-os/pop#1786]
**Distribution:** 
- NAME="Pop!_OS"
- VERSION="21.04"
- ID=pop
- ID_LIKE="ubuntu debian"
- PRETTY_NAME="Pop!_OS 21.04"
- VERSION_ID="21.04"
- VERSION_CODENAME=hirsute
- UBUNTU_CODENAME=hirsute

**Issue/Bug Description:**
- I clean installed POP OS 3 times but after some time or some restarts Application icons are oversized in show applications

- I'm new to Linux so if I have done some mistakes please help me.

- Screenshot is attached below
![Screenshot from 2021-07-06 12-29-20](https://user-images.githubusercontent.com/70306291/124560876-e8421580-de5a-11eb-8b96-befe9f840637.png)

Thank you

**Comment by Brierith** [comment]
The same issue i'm currently experiencing, it persist every logged in session, and seems to correct itself if you change the dock span and/or display resolution.

**Comment by PranavDalvi** [comment]
> The same issue i'm currently experiencing, it persist every logged in session, and seems to correct itself if you change the dock span and/or display resolution. 

Thank you for replying.
I tried to change dock span and/or display resolution and icons size went back to normal (temporarily).

**Comment by bflanagin** [comment]
@PranavDalvi: I don't think you're making any mistakes, sometimes the right combination of factors can cause all sorts of odd behaviors. Does anything else seem bigger when it happens? Text, window borders, etc. ? Also does your computer have a dedicated GPU or is it integrated?

**Comment by PranavDalvi** [comment]
> @PranavDalvi: I don't think you're making any mistakes, sometimes the right combination of factors can cause all sorts of odd behaviors. Does anything else seem bigger when it happens? Text, window borders, etc. ? Also does your computer have a dedicated GPU or is it integrated?

Thank you for commenting.
POP OS is installed on my laptop. Except application icons issue everything works like a charm.

- **Model**: hp 15-ba008au
- **CPU**: AMD APU A8 7410 with integrated R5 graphics.
- **RAM**: 8 GB
- **Display Resolution**: 1366x768

**Comment by jacobgkau** [comment]
I can recreate this on a Darter Pro by changing the screen resolution to 1368x768 and restarting GNOME Shell. Switching to Workspaces and then back to Applications seems to fix it until the next shell restart.

**Comment by PranavDalvi** [comment]
**Update on the issue**

The frequency of the issue is really reduced on my PC it happens once every 7th reboot or login into the shell 

Thank you everyone for helping.

**Comment by Mavincs** [comment]
The issue also happens with me.

- **CPU:** Ryzen 5 3600 6-Core
- **GPU:** AMD Radeon RX 560 Series
- **RAM:** 16Gb
- **Display Resolution:** 1366x768

**Comment by ariasyqolani** [comment]
The issue also happens with me.

    CPU: Intel Core i3 1115G4
    GPU: Nvidia MX350
    RAM: 4Gb
    Display Resolution: 1366x768
