### ISSUE TITLE
c0f1

### ISSUE THREAD

**Issue by Jatzelberger** [pop-os/pop#1789]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment]
This issue is blank, so I'm closing it. Feel free to open a new issue or leave a comment after editing this one with information about the issue.
