### ISSUE TITLE
[18.04] Boot up warnings/errors on Dell XPS13 9360

### ISSUE THREAD

**Issue by briggs1978** [pop-os/pop#179]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
I'm receiving these two messages on each boot.

`Unable to add image options measurement: Invalid Parameter`

`WARNING: Failed to connect to lvmetad. Falling back to device scanning.
2 logical volume(s) in volume group "data" now active
[    5.283027] tpm tpm0: A TPM error (257) occurred continue selftest
[    5.283065] tpm tpm0: TPM self test failed`

The computer starts up and functions properly

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
Thanks @briggs1978 for submitting this issue.

We are doing what we can to suppress unnecessary messages on boot.

It does look like the lvmetad message you got could be related to something we are not implementing properly. @mmstick Have you seen this before?

**Comment by mmstick** [comment]
@brs17 [This is the upstream Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799295). [Red Hat patched theirs to remove the warning](https://bugzilla.redhat.com/show_bug.cgi?id=813766). The error happens because the `lvmetad` service isn't running yet, because root is on a LVM device, which hasn't been mounted yet. There does exist a ` lvm2-lvmetad` systemd service that can be enabled to start after root is mounted, but this error is of course happening because `use_lvmetad` is set to `1` in `/etc/lvm/lvm.conf` by Debian by default.

**Comment by jeffreyscottgraham** [comment]
Was running the first testing iso just fine. Yesterday (Friday the 13th) did normal suggested updates and all was well until after power down. Now the system won't boot.... same issue as above:

                           **Failed to connect to lvmetad.**

This is a 2017 Dell XPS 15 9560 with bios 1.7.1 with intel+nvidia graphics and an SSD on nvme0n1p2.

What is the fix?!

**Comment by mmstick** [comment]
The lvmetad message can be ignored. It's supposed to happen.

**Comment by jackpot51** [comment]
This should be fixed now with a new lvm2

**Comment by albe-rosado** [comment]
Same on Lenovo Thinkpad P51, Pop_OS 17.10 install with no problem, everything works perfectly, but when doing a clean install of 18.04, shows the error commented above.
