### ISSUE TITLE
Volume Slider on the UI tray doesn't actually change volume

### ISSUE THREAD

**Issue by mauricio-fidalgo** [pop-os/pop#1797]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After upgrading, Changing the volume directly from the system tray doesn't actually change the volume. Changing the volume using the volume keys on the keyboard still works, changing the volume on the settings application also works.

**Steps to reproduce (if you know):**
Using the scroll wheel on top of the volume Icon changes the slider bar visually, but has no effects on the volume, the same happens if I click on the icon and change the volume by using the slider bar.

**Expected behavior:**
The sound volume should change according to the visual feedback given, like in previous versions.

**Other Notes:**

**Comment by ids1024** [comment]
Strange. It works fine for me.

If you run `pavucontrol`, does the volume slider in the system tray seem in sync with any of the controls there?

Does `journalctl /usr/bin/gnome-shell` have any errors that might be relevant?

**Comment by mauricio-fidalgo** [comment]
I just rebooted and it now works fine, 
I don't know what caused it then.
After the reboot I did the pavucontrol test and it works fine,
about the `journalctl /usr/bin/gnome-shell` I looked into it, but there is too much stuff in there to know what I'm looking for, there are a few errors that I don't think they're related.

**Comment by mauricio-fidalgo** [comment]
Closing this because it didn't happen again after reboot.
