### ISSUE TITLE
Hot Corner no longer working in 21.04

### ISSUE THREAD

**Issue by ChaseClark** [pop-os/pop#1798]
**Distribution**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
 

**Issue/Bug Description:**

Top-left hot corner no longer working in COSMIC desktop. I have enabled the option in gnome-tweaks as well as in the new COSMIC settings.

**Steps to reproduce (if you know):**

Enable top-left hot corner in settings. Move mouse to the top left of the screen. Nothing happens.

**Expected behavior:**

The workspace view opens.

Let me know if you need any more information.

**Comment by jacobgkau** [comment]
Is this in a virtual machine or on a physical computer?
