### ISSUE TITLE
Lost UI after GTK update

### ISSUE THREAD

**Issue by wout** [pop-os/pop#180]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution**
 NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Issue/Bug Description**
After installing the pop-gtk theme update, offered through the Pop!_Shop, my interface has been reset to something that looks like the default.

**Other Notes**
This is what it looks like right now:
![screenshot from 2018-04-05 09-48-18](https://user-images.githubusercontent.com/107324/38353499-e40dac9c-38b6-11e8-80fd-e48319793dff.png)

**Comment by brs17** [comment]
Hello @wout thank you for filing this issue.

I was unable to recreate your issue. It definitely looks like you have the Cinnamon desktop environment installed and running. If you log out, on the login screen you should see a gear/settings button that should let you choose between different desktop environments, the `Pop(xorg)` choice is the one you want.

Once logged in, you could then go ahead and remove cinnamon if you wanted, `sudo apt purge cinnamon` should work.

**Comment by wout** [comment]
Hi @brs17 
I don't know what happened.
After a reboot I suddenly got the Cinnamon UI but I didn't see the gear.

In the meantime I reinstalled everything but that's of course not the ideal solution.
Thanks anyway!

**Comment by wout** [comment]
Thanks!
I'll keep my eyes open the next time I have a similar situation.

I'm fairly new to Linux so I'm still finding my way.
But so far I love Pop!_OS, I installed it and everything just worked (my Nvidia card included).

**Comment by brs17** [comment]
Well, welcome to Linux! I'd definitely recommend joining the [Pop!_Chat](http://chat.pop-os.org/). There's some pretty knowledgable people there and it's a great place to ask questions!
