### ISSUE TITLE
Applications Crop in 21.04

### ISSUE THREAD

**Issue by Robin-MC** [pop-os/pop#1801]
Just a little bug this one. The application menu in PopOS 21.04  sometimes comes up too large for the screen after a reboot (such that the icons at the edge are cropped off). if I click Workspace & then back to Applications it all comes good.I am sure this will get fixed ASAP & it will not disturb my sleep. ZZZZZZ

**Comment by jacobgkau** [comment]
Duplicate of https://github.com/pop-os/pop/issues/1786.

**Comment by Robin-MC** [comment]
Thanks Jacob,

That one a a bug that doesn't bite anyway.

I am much more bothered by the loss of my scanner.

Robin
