### ISSUE TITLE
Gnome-control-center 3.38.3 returns to an old stage

### ISSUE THREAD

**Issue by fakergt** [pop-os/pop#1803]
Distribution (run cat /etc/os-release):
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

Related Application and/or Package Version (run apt policy $PACKAGE NAME):
apt policy gnome-control-center
```
gnome-control-center:
  Installed: 1:3.38.3-1pop1~1625268318~21.04~2880306
  Candidate: 1:3.38.3-1pop1~1625337172~20.04~bdcf8ad
  Version table:
     1:3.38.5-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
     1:3.38.3-1pop1~1625337172~20.04~bdcf8ad 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
 *** 1:3.38.3-1pop1~1625268318~21.04~2880306 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.36.5-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
     1:3.36.1-1ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
```
Issue/Bug Description:
Currently when you upgrade from normla pop os to cosmic you get this version of gnome-control-center which provides the new features like "Desktop". version : `1:3.38.3-1pop1~1625268318~21.04~2880306`
But pop shop offers a new update version : `1:3.38.3-1pop1~1625337172~20.04~bdcf8ad`
Which if you upgrade to it, desktop and all it's features disapear, basically returning the old state to " Appearance" which contains nothing more than background wallpaper and black or white theme

Steps to reproduce (if you know):
upgrade GNome Settings

Expected behavior:
to work as expected, but it returns to a previous state.

Other Notes:
To fix this I had to remove the new version of gnome-control-center and install the older version
`1:3.38.3-1pop1~1625268318~21.04~2880306`

**Comment by bflanagin** [comment]
@fakergt did you upgrade to 21.04 from 20.04 or was it a fresh install?

Looking at the information you provided it looks like it "upgraded" to a version meant for 20.04, so now we need to figure out why. Check out your apt sources by going to /etc/apt/sources.list.d/ and making sure all references to focal have been commented out.

Also I added a little formatting to your original issue to make it easier to read.

**Comment by fakergt** [comment]
Thanks for formatting and sorry about that.
I upgraded from 20.04 to 21.04.
then I did another apt update to check if there is anything new, and the Gnome Settings provided an update the one I mentioned above.
Could you please explain how to the check those sources ?
![Screenshot from 2021-07-09 16-37-42](https://user-images.githubusercontent.com/52929902/125086134-01093000-e0d4-11eb-9119-dc214d4da5be.png)
I have this when I get to this folder

**Comment by jacobgkau** [comment]
Please provide the output of the following commands in a text file:
```
cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*
```

**Comment by fakergt** [comment]
> **cat /etc/apt/sources.list**

# deb cdrom:[Pop_OS 20.04 _Focal Fossa_ - Release amd64 (20210623)]/ focal main restricted
deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://apt.pop-os.org/proprietary focal main

> **cat /etc/apt/sources.list.d/***

deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
X-Repolib-Name: Pop_OS Apps
Enabled: yes
Types: deb
URIs: http://apt.pop-os.org/proprietary
Suites: hirsute
Components: main
## This file was generated by pop-upgrade
#
## X-Repolib-Name: Pop_OS PPA
deb http://ppa.launchpad.net/system76/pop/ubuntu hirsute main
deb-src http://ppa.launchpad.net/system76/pop/ubuntu hirsute main
deb http://ppa.launchpad.net/system76/pop/ubuntu focal main
deb-src http://ppa.launchpad.net/system76/pop/ubuntu focal main
X-Repolib-Name: Pop_OS System Sources
Enabled: yes
Types: deb deb-src
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: hirsute hirsute-security hirsute-updates hirsute-backports
Components: main restricted universe multiverse
X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu/


> I used the usual apt update, and apt upgrade/ full-upgrade or dist-upgrade, as I installed yesterday the distro probably 3 times to figure out the problem, so I can't say with confidence which one was yesterday unfortunately.
what I can say is the update was successful after restart. Desktop was in Settings, but after updating the gnome settings again because that's what pop shop suggested, I lost the Desktop setting. Currently I have Desktop because I use a previous commit/version of the gnome-control-center. If I update it it will revert to previous version. Strange enough though the Dock is present as with the new update 
Like in the below picture.
![Screenshot from 2021-07-09 16-54-01](https://user-images.githubusercontent.com/52929902/125088728-6100d600-e0d6-11eb-9b25-1e93b22f098c.png)
I'm new to Pop OS so I maybe I did something incorrectly.

**Comment by jacobgkau** [comment]
> I used the usual apt update, and apt upgrade/ full-upgrade or dist-upgrade,

None of those commands would perform a distribution upgrade (20.04 -> 21.04) unless you manually edited the sources files in advance. If you didn't edit the files in advance, then a `pop-upgrade release upgrade` or the unsupported `do-release-upgrade` would be required to update the files for you.

I see `This file was generated by pop-upgrade` in one of the files, so I believe you ran `pop-upgrade release upgrade` or else used the pop-upgrade GUI in the Settings app, correct? `pop-upgrade` should have emptied the classic `/etc/apt/sources.list` file; that file is causing an issue because it's providing 20.04 packages to your 21.04 system. Are you using Timeshift or any other application that might be editing/restoring your system files for you?

Please remove the obsolete `sources.list` file:
```
sudo rm /etc/apt/sources.list
```
Then try updating your system with these commands:
```
sudo apt update
sudo apt full-upgrade
```

**Comment by fakergt** [comment]
Yes I also did pop-upgrade. I apologize I forgot.
Unfortunately I didn't install any TimeShift or like it application yet. SO I don't have a previous version save. 
Should I still do those steps you mentioned ?

**Comment by jacobgkau** [comment]
> Should I still do those steps you mentioned ?

Yes.

**Comment by fakergt** [comment]
I did those steps, and also a restart just in case.
It happened again. 
because it installed the last version of gnome-control-center I lost desktop setting
![Screenshot from 2021-07-09 17-20-24](https://user-images.githubusercontent.com/52929902/125092358-f5206c80-e0d9-11eb-97fd-d2e97e0e81a0.png)

I'll provide again the 
```
cat /etc/apt/sources.list
cat /etc/apt/sources.list.d/*
```
immediately

**Comment by fakergt** [comment]
cat /etc/apt/sources.list.d/*
deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
X-Repolib-Name: Pop_OS Apps
Enabled: yes
Types: deb
URIs: http://apt.pop-os.org/proprietary
Suites: hirsute
Components: main
## This file was generated by pop-upgrade
#
## X-Repolib-Name: Pop_OS PPA
deb http://ppa.launchpad.net/system76/pop/ubuntu hirsute main
deb-src http://ppa.launchpad.net/system76/pop/ubuntu hirsute main
deb http://ppa.launchpad.net/system76/pop/ubuntu focal main
deb-src http://ppa.launchpad.net/system76/pop/ubuntu focal main
X-Repolib-Name: Pop_OS System Sources
Enabled: yes
Types: deb deb-src
URIs: http://us.archive.ubuntu.com/ubuntu/
Suites: hirsute hirsute-security hirsute-updates hirsute-backports
Components: main restricted universe multiverse
X-Repolib-Default-Mirror: http://us.archive.ubuntu.com/ubuntu/

cat /etc/apt/sources.list
cat: /etc/apt/sources.list: No such file or directory

**Comment by jacobgkau** [comment]
Remove this file too:
```
sudo rm /etc/apt/sources.list.d/system76-ubuntu-pop-focal.list
```
Then update again:
```
sudo apt update
sudo apt full-upgrade
```
You may need another reboot after that.

**Comment by fakergt** [comment]
Yeah ! That did the trick. I have desktop setting and pop os 21.04.
Thank you very much for your help and have a great day !

**Comment by jacobgkau** [comment]
Closing since this seems to have been a configuration error. If anyone else encounters this and/or has steps to recreate, please leave a comment and we can re-open.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
