### ISSUE TITLE
Workspaces Hot Corner Not Working

### ISSUE THREAD

**Issue by absoluteinc** [pop-os/pop#1810]
**Distribution (run `cat /etc/os-release`):**
 
 21.04 NVIDIA
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Fresh Install of 21.04. For the top left taskbar, I removed the Workspaces button and left the Activities button. I then went to the Settings and turned on the Hot Corner for the top left to open up Workspaces. This worked yesterday on a different install of 21.04. On this fresh install, the hot corner does not work. I tried toggling it on and off, restarting, updating. 

**Steps to reproduce (if you know):**

Turn on Hot Corner for Workspaces to open up when you move your mouse to the top left corner.

**Expected behavior:**

Workspaces should open.

**Other Notes:**

**Comment by bflanagin** [comment]
Mind running `apt policy pop-shell` and '`apt policy `pop-cosmic` @absoluteinc I'm not seeing the issue on my end, so I want to make sure we're all on the same version.

**Comment by absoluteinc** [comment]
apt policy pop-shell: 

pop-shell:
  Installed: 1.1.0~1625501479~21.04~b33c5e2
  Candidate: 1.1.0~1625501479~21.04~b33c5e2
  Version table:
 *** 1.1.0~1625501479~21.04~b33c5e2 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status

apt policy pop-cosmic: 

pop-cosmic:
  Installed: 0.1.0~1625761311~21.04~82efb97
  Candidate: 0.1.0~1625761311~21.04~82efb97
  Version table:
 *** 0.1.0~1625761311~21.04~82efb97 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status

**Comment by bflanagin** [comment]
We're on the same version. I did notice that there was a slight increase in how fast I have to move my cursor into the corner. Which may have been changed due to people accidentally triggering the event when trying to click top bar options. 

I've included a video of what I mean,


https://user-images.githubusercontent.com/10382037/125491599-7a6af17a-5547-4a16-b57d-95fb65d9923a.mp4

**Comment by absoluteinc** [comment]
> We're on the same version. I did notice that there was a slight increase in how fast I have to move my cursor into the corner. Which may have been changed due to people accidentally triggering the event when trying to click top bar options.
> 
> I've included a video of what I mean,
> Screencast.from.07-13-2021.10.36.13.AM.mp4
> 
> Let me know if that's the issue if not we might have to throw this to the community to see if anyone else has had the issue.

I have tried moving my cursor all different speeds. This feature works in a different install of 21.04 I have, on the same PC, just a different M.2 SSD. However, this fresh install of 21.04 does not work at all.

**Comment by absoluteinc** [comment]
So I've got some good news! The hot corner hasn't been working for a few days now, and to access the Workspaces I was just using the icon in the dock. Today, I was messing around with some keyboard shortcuts, including Super+Tab, Alt+Tab, Ctrl+Tab. Then, all of a sudden, the hot corner started working reliably now. The issue is gone. Before I did those keyboard shortcuts, I tried the hot corner just 5 minutes before. I did not restart in between then and when it was working. Not sure what the cause of the issue was!

**Comment by bflanagin** [comment]
Awesome! I'm a pretty heavy shortcut user so maybe there is some correlation there. I'm going to close the issue for now since I wasn't able to replicate the behavior on my end.  If it starts up again feel free to reopen the issue and we'll do more digging.
