### ISSUE TITLE
Pop OS 21.04 restore from suspend - no trackpad click or keyboard

### ISSUE THREAD

**Issue by perkinsms** [pop-os/pop#1812]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Gnome 38 maybe?

**Issue/Bug Description:**

When returning from suspend - the touchpad is able to move the pointer, but clicking or tapping does not work. Also the keyboard does not bring up the password prompt. I have been able to work around this by using control-alt-F1 to bring up the GDM screen and select my logged in user account to supply the password. 

**Steps to reproduce (if you know):**

be logged in to a user account
suspend the computer by closing the laptop lid
open the laptop lid
attempt to click or type to bring up the password prompt to re-enter the user account
no response

**Expected behavior:**

clicking the touchpad button should bring up a password prompt to allow entry to the user account

**Other Notes:**

this is on a lemp9 lemur pro laptop running POP OS 21.04. 

I have noticed this behavior also on a homebuilt desktop PC using POP OS 21.04

**Comment by bflanagin** [comment]
Sorry to hear you're having issues with your lemp9. If you haven't already head over to https://support.system76.com and open a ticket for the issue. Its a free service for those that own our hardware, and you'll get faster response times there. I'll close this issue for the time being but feel free to reference it in your support ticket. They can re-open and add to it if needs be.

**Comment by perkinsms** [comment]
Ok, but on the other hand this issue is also showing up on my homebuilt PC
as well so it may be something people outside the System 76 family are
getting.

**Comment by bflanagin** [comment]
Good point @perkinsms, for the time being lets see what they have to say, I've tested the issue against my lab lemp9 without issue so they're still your best bet at resolving the laptops issue. As far as your home built machine lets hope that the fix for the laptop transfers over and both will be fixed.
