### ISSUE TITLE
gdm fails to set brightness and logs it every second

### ISSUE THREAD

**Issue by goodmami** [pop-os/pop#182]
The system constantly tries to set the brightness and fails, presumably due to a permissions issue.

 **Distribution - (run ```cat /etc/os-release```)**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
``` 
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

```
gnome-settings-daemon:
  Installed: 3.26.2-0ubuntu0.1
  Candidate: 3.26.2-0ubuntu0.1
  Version table:
 *** 3.26.2-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.26.1-0ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```

**Issue/Bug Description**

When I run `journalctl` I see the log is full of messages about the system attempting to set the brightness with `gsd-backlight-helper`, and subsequently failing. When I run the command as myself at the command line, I get `This program can only be used by the root user`, and when I run it with `sudo` it works. The log claims that the user running the command is `root`, but it still fails. Here is a portion of my log:

```
Apr 07 10:53:26 tpy pkexec[5936]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Apr 07 10:53:26 tpy pkexec[5936]: goodmami: Executing command [USER=root] [TTY=unknown] [CWD=/home/goodmami] [COMMAND=/usr/lib/gnome-settings-daemon/gsd-backlight-helper --s
Apr 07 10:53:27 tpy pkexec[5944]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm3] [COMMAND=/usr/lib/gnome-settings
Apr 07 10:53:27 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: Error executing command as another user: Not authorized
Apr 07 10:53:27 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: This incident has been reported.
Apr 07 10:53:27 tpy pkexec[5945]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Apr 07 10:53:27 tpy pkexec[5945]: goodmami: Executing command [USER=root] [TTY=unknown] [CWD=/home/goodmami] [COMMAND=/usr/lib/gnome-settings-daemon/gsd-backlight-helper --s
Apr 07 10:53:28 tpy pkexec[5954]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm3] [COMMAND=/usr/lib/gnome-settings
Apr 07 10:53:28 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: Error executing command as another user: Not authorized
Apr 07 10:53:28 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: This incident has been reported.
Apr 07 10:53:28 tpy pkexec[5953]: pam_unix(polkit-1:session): session opened for user root by (uid=1000)
Apr 07 10:53:28 tpy pkexec[5953]: goodmami: Executing command [USER=root] [TTY=unknown] [CWD=/home/goodmami] [COMMAND=/usr/lib/gnome-settings-daemon/gsd-backlight-helper --s
Apr 07 10:53:28 tpy pkexec[5962]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm3] [COMMAND=/usr/lib/gnome-settings
Apr 07 10:53:28 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: Error executing command as another user: Not authorized
Apr 07 10:53:28 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: This incident has been reported.
```

Other parts of the log don't include the pam_unix messages, so maybe they are unrelated?

```
Apr 07 11:17:43 tpy pkexec[17465]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm3] [COMMAND=/usr/lib/gnome-setting
Apr 07 11:17:43 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: Error executing command as another user: Not authorized
Apr 07 11:17:43 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: This incident has been reported.
Apr 07 11:17:43 tpy pkexec[17471]: gdm: Error executing command as another user: Not authorized [USER=root] [TTY=unknown] [CWD=/var/lib/gdm3] [COMMAND=/usr/lib/gnome-setting
Apr 07 11:17:43 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: Error executing command as another user: Not authorized
Apr 07 11:17:43 tpy org.gnome.SettingsDaemon.Power.desktop[1232]: This incident has been reported.
```

**Steps to reproduce (if you know)**

Not sure. This is a pretty fresh install.

**Expected behavior**

I wouldn't expect it to fail like this. Also, is it normal for the system to adjust the brightness (and log it) every second? I turned off "Automatic brightness" in the power settings, but it did not seem to have any effect (though I have not restarted since turning it off; I'll try that next).

**Other Notes**

The machine is a Thinkpad Yoga 14 with a GeForce 940M discrete GPU, but I'm using the "Intel/AMD" version of Pop!_OS.

**Comment by goodmami** [comment]
Update: I restarted after turning "Automatic brightness" off, but I still see the errors in the log.

**Comment by goodmami** [comment]
Related: https://bugzilla.gnome.org/show_bug.cgi?id=756539

It seems to have been fixed upstream for Gnome 3.18, but later comments suggest it still affects 3.26

**Comment by wchest** [comment]
Just confirming that I'm seeing the same behavior as well on 17.10. It definitely seems related to the ambient light sensor on my machine. If I cover the sensor I can watch the log entries added in real-time.

**Comment by goodmami** [comment]
Thanks for confirming. I ran `journalctl -f` and noticed the brightness value adjusting when I angled my sensor toward a light. So I guess the second question is why the automatic-brightness is running even though I have it turned off? (the first question is the permissions issue of running the command).

What hardware are you running? I'm unfortunately getting the impression that this issue might not get much attention unless it affects System76 hardware...

**Comment by wchest** [comment]
Definitely a good question as to why it's running while the setting is turned off. I'm on a Yoga 2 Pro, so not much help on the System76 front.

For me, under low light conditions, the screen seems to flickr quite a bit (maybe a few times a minute, but very erratically) as if it's trying to adjust the brightness based on the brightness of the room. I'm guessing these two issues might be related. It's not nearly as noticeable in normal light.

**Comment by brs17** [comment]
Sounds like this issue is exposed by different light sensors. It definitely is difficult to assess and attempt a fix at this issue without hardware that is having this issue. My recommendation would be to :+1: any upstream bugs that mention this issue and provide information as possible.

**Comment by goodmami** [comment]
This issue, at least, has gone away after upgrading to Pop!_OS 18.04.
