### ISSUE TITLE
Pop!_OS won't switch to discrete graphics

### ISSUE THREAD

**Issue by wout** [pop-os/pop#183]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
nvidia-settings:
  Installed: 384.69-0ubuntu1
  Candidate: 384.69-0ubuntu1
  Version table:
 *** 384.69-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**
I'm using a Dell XPS 15 9560. After installing Pop!_OS Nvidia (performance mode) was enabled. Everything worked as expected right after installation. But after rebooting a few times, I am now on Intel (power saving mode).

![screenshot from 2018-04-07 20-16-57](https://user-images.githubusercontent.com/107324/38458661-ee933060-3aa0-11e8-8a08-c23072ab8ff1.png)

However, it seems I am stuck on the Intel side. There's no way of getting the Nvidia GPU enabled back again.

**Steps to reproduce (if you know)**
When I switch to NVIDIA, log out, and try to log in again, I get a black screen for a second, right after clicking the login button, and I am prompted again with the login form. At this point, I'm stuck, because after logging in again, it's the same loop.

After rebooting into BIOS (F12), doing nothing and continuing the normal boot sequence, everything is back to "normal" (Intel graphics).

**Expected behavior**
I would expect Nvidia X Server Settings to make the switch.

**Other Notes**
I had this problem before, but reinstalled Pop!_OS. Now I'm in the same situation so it is reproducible.

**Comment by brs17** [comment]
@wout Thank you for filing this issue.

This sounds like it has something to do with the NVIDIA Optimus/Prime functionality that allows you to switch between NVIDIA and Intel Graphics. 

Logged in, try running `sudo prime-select nvidia` and then reboot. Are you then able to log back in (this should be NVIDIA mode now)? 

Another though, you may also want to update to the latest driver version (390.xx), who knows perhaps they fixed a strange bug that was affecting your machine.

**Comment by wout** [comment]
@brs17, thanks for your reply.

As it turns out, Secure Boot was suddenly re-enabled in BIOS, I don't know how that happened. This prevented the Nvidia driver from working. Disabling Secure Boot again, I am now on Nvidia graphics after a reboot, without touching a thing.

As for the Nvidia driver, I was already on the latest version (390.25). But `nvidia-settings` has another version:

```
nvidia-settings:  version 384.69  (buildd@lgw01-amd64-056)  Tue Oct 10 10:21:06
UTC 2017
  The NVIDIA X Server Settings tool.

  This program is used to configure the NVIDIA Linux graphics driver.
  For more detail, please see the nvidia-settings(1) man page.
```

Not sure if that is a bad thing, though...

**Comment by jackpot51** [comment]
That is good @wout . The version difference is not an issue, nvidia-settings is patched by Ubuntu if you want to discuss it you can look here: https://bugs.launchpad.net/ubuntu/+source/nvidia-settings/

**Comment by wout** [comment]
@jackpot51 Great, thanks for letting me know.

**Comment by ryanpcmcquen** [comment]
I am affected by this issue on Pop!_OS testing (18.04), but I have Secure boot disabled ...

**Comment by hugbro** [comment]
I am affected by this issue on Pop!_OS 18.04.

My solution was installing primus package along with all dependencies.
Now i can switch graphics normally (with system76-power)
