### ISSUE TITLE
Pop OS crashes on resume from sleep . Possibly   AMD GPU related 

### ISSUE THREAD

**Issue by vinod4dev** [pop-os/pop#1830]
**Distribution (run `cat /etc/os-release`):** 
 

   1   │ NAME="Pop!_OS"
   2   │ VERSION="21.04"
   3   │ ID=pop
   4   │ ID_LIKE="ubuntu debian"
   5   │ PRETTY_NAME="Pop!_OS 21.04"
   6   │ VERSION_ID="21.04"
   7   │ HOME_URL="https://pop.system76.com"
   8   │ SUPPORT_URL="https://support.system76.com"
   9   │ BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
  10   │ PRIVACY_POLICY_URL="https://system76.com/privacy"
  11   │ VERSION_CODENAME=hirsute
  12   │ UBUNTU_CODENAME=hirsute
  13   │ LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** amdgpu (possibly)

**Issue/Bug Description:**
OS crashes upon resume from sleep . Short log mentioned below. Detailed log in  attachment from the time lid is closed to opened . Device is a Ryzen 2500u laptop  with hybrid VEGA + RX 560X graphics

[crash-lid-closed1.log](https://github.com/pop-os/pop/files/6864634/crash-lid-closed1.log)

```
Jul 21 10:08:59 pop-box kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* ring sdma0 timeout, signaled seq=786522, emitted seq=786525
Jul 21 10:08:59 pop-box kernel: [drm:amdgpu_job_timedout [amdgpu]] *ERROR* Process information: process  pid 0 thread  pid 0
Jul 21 10:08:59 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset begin!
Jul 21 10:08:59 pop-box kernel: [drm] free PSP TMR buffer
Jul 21 10:08:59 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset succeeded, trying to resume
Jul 21 10:08:59 pop-box kernel: [drm] PCIE GART of 1024M enabled (table at 0x000000F400900000).
Jul 21 10:08:59 pop-box kernel: [drm] VRAM is lost due to GPU reset!
Jul 21 10:08:59 pop-box kernel: [drm] PSP is resuming...
Jul 21 10:08:59 pop-box kernel: [drm] reserve 0x400000 from 0xf43fc00000 for PSP TMR
Jul 21 10:08:59 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: RAS: optional ras ta ucode is not available
Jul 21 10:08:59 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: RAP: optional rap ta ucode is not available
Jul 21 10:09:00 pop-box kernel: [drm] kiq ring mec 2 pipe 1 q 0
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: [gfxhub0] no-retry page fault (src_id:0 ring:222 vmid:1 pasid:0, for process  pid 0 thread  pid 0)
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:   in page starting at address 0x800000043000 from client 27
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: VM_L2_PROTECTION_FAULT_STATUS:0x001009BC
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          Faulty UTCL2 client ID: CPF (0x4)
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          MORE_FAULTS: 0x0
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          WALKER_ERROR: 0x6
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          PERMISSION_FAULTS: 0xb
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          MAPPING_ERROR: 0x1
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu:          RW: 0x0
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: [drm:amdgpu_ring_test_helper [amdgpu]] *ERROR* ring gfx test failed (-110)
Jul 21 10:09:00 pop-box kernel: [drm:amdgpu_device_ip_resume_phase2 [amdgpu]] *ERROR* resume of IP block <gfx_v9_0> failed -110
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset(1) failed
Jul 21 10:09:00 pop-box kernel: amdgpu 0000:04:00.0: amdgpu: GPU reset end with ret = -110
```

**Steps to reproduce (if you know):**

Put systtem to sleep and then resume .

**Expected behavior:**

OS should not crash 

**Other Notes:  'uname  -a'  :** Linux pop-box 5.11.0-7620-generic #21\~1624379747\~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux

**Comment by jacobgkau** [comment]
> Device is a Ryzen 2500u laptop with hybrid VEGA + RX 560X graphics

What model of laptop is it?

**Comment by bflanagin** [comment]
Thanks for the report @vinod4dev.
From the log it does look like a gpu issue. If this is on one of our laptops you can put in a support ticket over at https://support.system76.com . If not you'll need to search for possible solutions based on the make and model of your laptop. You can also chat with the community over at https://chat.pop-os.org

**Comment by vinod4dev** [comment]
Ok its not a System76 laptop  . And  i can post it in the chats . But, I  felt you might have machines of similar hardware. Never had this issue on 20.04  but now it has  become  quite frequent ( but random )   occurrence
