### ISSUE TITLE
internet doesn't work

### ISSUE THREAD

**Issue by dyanfelipe** [pop-os/pop#1856]
A internet para de funcionar do nada, isso me ocorreu duas vezes na primeira vez, escolhi formatar. E estou fazendo o mesmo.

Agora porque tenho intenet nos outros dispositivos mas o meu no meu sistema não.

Segue os exempos.

![2021-08-06_11-43](https://user-images.githubusercontent.com/32774948/128528345-26c76675-0dae-4c05-894f-81e8b2b1a86a.png)
![2021-08-06_11-44](https://user-images.githubusercontent.com/32774948/128528352-870472c5-d600-4843-bfba-2c206d273d00.png)

**Comment by jacobgkau** [comment]
Please provide information about your hardware (computer model, motherboard, and Ethernet chipset.)

**Comment by dyanfelipe** [comment]
I formatted the machine if it happens again I try to get this information for you!

**Comment by dyanfelipe** [comment]
That didn't happen after I formatted it. I'm closing this problem, if necessary, I reopen it
