### ISSUE TITLE
Boot loop with NVIDIA 396 driver....

### ISSUE THREAD

**Issue by Iiari** [pop-os/pop#186]
Pop OS 18.04

I installed the new NVIDIA 396 drivers I saw show up in my driver list after installing the NVIDIA graphics PPA.  After installing and rebooting, after I type my password in for encryption, it says:

[     33.337311] acer_wmi: Unsupported machine has AMWO_GUID1, unable to load

The screen flashes, and then the error recurs, and that keeps looping and it won't load.  Some Googling suggested it's a boot issue and turning off IVP6 fixes it?  This is a "test" laptop to try 18.04 Pop, so I'll just probably wipe it and start over, but just FYI.

**Comment by brs17** [comment]
@Iiari Currently 390.x is the "stable" NVIDIA driver and the version of the NVIDIA driver we have tested the most (it is the version we ship out of the box on System76 machines). 

@djordan2 This might be something to keep an eye out for as we test newer NVIDIA drivers.
