### ISSUE TITLE
404 errors when upgrading packages, clean install

### ISSUE THREAD

**Issue by mj-crabtree** [pop-os/pop#1867]
**Distribution:**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version:**
```
apt:
  Installed: 2.2.4ubuntu0.1
  Candidate: 2.2.4ubuntu0.1
  Version table:
 *** 2.2.4ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
```

**Issue/Bug Description:**
clean install, upgrading apt & upgrading via the pop shop results in 404 errors

**Steps to reproduce (if you know):**
1. open pop shop
2. hit 'update all'
3. error presents

```
: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385 is not (yet) available (404  Not Found [IP: 91.189.95.85 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-upgrade amd64 1.0.0~1628609583~21.04~d3061df is not (yet) available (404  Not Found [IP: 91.189.95.85 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-upgrade-gtk amd64 1.0.0~1628609583~21.04~d3061df is not (yet) available (404  Not Found [IP: 91.189.95.85 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b is not (yet) available (404  Not Found [IP: 91.189.95.85 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b is not (yet) available (404  Not Found [IP: 91.189.95.85 80])
```

1. `sudo apt-get update`
2. `sudo apt-get upgrade`
3. error presents: [gist](https://gist.github.com/mj-crabtree/eb2d99e89cb6edac1db352f7d602c7db)

**Expected behavior:**
all packages upgrade as usual

**Comment by kodosexe** [comment]
Running into the same error, clean install literally minutes before. Tried Pop!_Shop and Terminal, both giving the same error.

**Comment by allout58** [comment]
I've also run into this, deleted all the cached lists in `/var/lib/apt/lists/` and ran `apt update` again, still having the issue.

**Comment by ActIII03** [comment]
I am running into the same issue. I tried running the following (per https://support.system76.com/articles/package-manager-pop):

`sudo apt clean`
`sudo apt update -m`
`sudo dpkg --configure -a`
`sudo apt install -f`
`sudo apt full-upgrade`
`sudo apt autoremove --purge`

Expected `apt upgrade` to work as usual but encountered the same issue as @mj-crabtree. 

I choose not to manually reinstall them because I do not feel comfortable doing `apt install reinstall <pkg_name>`. Again, referencing the article above.

Until this is resolved, can I continue to use 21.04 as usual or is this a critical issue? I had no issues until today after not updating for 1 wk. 

Thanks to anyone who can help me.

**Comment by thiagolucio** [comment]
Linux pop-os 5.11.0-7620-generic #21~1626191760~21.04~55de9c3-Ubuntu SMP Tue Jul 20 22:18:55 UTC  x86_64 x86_64 x86_64 GNU/Linux

Same here:

E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385 is not (yet) available (404  Not Found [IP: 2001:67c:1560:8008::19 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-upgrade amd64 1.0.0~1628609583~21.04~d3061df is not (yet) available (404  Not Found [IP: 2001:67c:1560:8008::19 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-upgrade-gtk amd64 1.0.0~1628609583~21.04~d3061df is not (yet) available (404  Not Found [IP: 2001:67c:1560:8008::19 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b is not (yet) available (404  Not Found [IP: 2001:67c:1560:8008::19 80])
E: http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b is not (yet) available (404  Not Found [IP: 2001:67c:1560:8008::19 80])

Using the commands oriented by @ActIII03 get errors too. 

Err:40 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:41 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-upgrade amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:42 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-upgrade-gtk amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Get:43 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-cosmic all 0.1.0~1628189963~21.04~6d111bd [12.6 kB]
Ign:44 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b          
Get:45 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 flatpak amd64 1.11.2-1pop1~1627328845~21.04~d349217 [1,134 kB]
Get:46 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libflatpak-dev amd64 1.11.2-1pop1~1627328845~21.04~d349217 [54.8 kB]
Get:47 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libflatpak0 amd64 1.11.2-1pop1~1627328845~21.04~d349217 [255 kB]
Get:48 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 gir1.2-flatpak-1.0 amd64 1.11.2-1pop1~1627328845~21.04~d349217 [12.5 kB]
Ign:49 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
Err:44 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b          
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:49 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Fetched 48.1 MB in 18s (2,612 kB/s)                                                                                          
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/pop-upgrade_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/libpop-upgrade-gtk_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell-plugin-system76-power_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

And after that, try the suggest ... using "run apt-get update" and get ...
Err:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:2 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-upgrade amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:3 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-upgrade-gtk amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Ign:4 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b
Ign:5 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
Err:4 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Err:5 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/pop-upgrade_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/libpop-upgrade-gtk_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell-plugin-system76-power_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
thiagolucio@pop-os:~$ 

And in final chance using ---fix-missing in the last force choice...

E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/pop-upgrade_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/libpop-upgrade-gtk_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell-plugin-system76-power_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 2001:67c:1560:8008::19 80]


That' s it...

**Comment by robertstrom** [comment]
Same issue

Clean install of Pop!_OS 21.04 today
rstrom@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute


Have tried getting the system updated via the Pop Shop GUI and the CLI and continually run into the errors shown below.

rstrom@pop-os:~$ sudo apt update && sudo apt full-upgrade
Hit:1 http://apt.pop-os.org/proprietary hirsute InRelease
Hit:2 http://dl.google.com/linux/chrome/deb stable InRelease                                                                     
Hit:3 https://brave-browser-apt-release.s3.brave.com stable InRelease                                                            
Hit:4 http://us.archive.ubuntu.com/ubuntu hirsute InRelease                                                                      
Hit:5 http://packages.microsoft.com/repos/code stable InRelease     
Get:6 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Hit:7 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Get:8 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease [109 kB]
Hit:9 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Fetched 209 kB in 1s (246 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
49 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  alsa-ucm-conf firefox-locale-ar firefox-locale-de firefox-locale-en firefox-locale-es firefox-locale-fr firefox-locale-it
  firefox-locale-ja firefox-locale-pt firefox-locale-ru firefox-locale-zh-hans firefox-locale-zh-hant firmware-manager-notify
  firmware-manager-shared flatpak fwupd fwupd-signed gir1.2-flatpak-1.0 gnome-shell-extension-cosmic-dock
  gnome-shell-extension-desktop-icons-ng libexiv2-27 libfirmware-manager libflatpak-dev libflatpak0 libfwupd2 libfwupdplugin1
  libjavascriptcoregtk-4.0-18 libperl5.32 libpop-upgrade-gtk libsndfile1 libssl1.1 libssl1.1:i386 libwebkit2gtk-4.0-37 login
  openssh-client openssl passwd perl perl-base perl-modules-5.32 pop-cosmic pop-shell pop-shell-plugin-system76-power
  pop-upgrade python3-distupgrade ubuntu-advantage-tools ubuntu-drivers-common ubuntu-release-upgrader-core wireless-regdb
The following packages will be DOWNGRADED:
  libpop-desktop-widget
49 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
19 standard security updates
Need to get 3,386 kB/52.9 MB of archives.
After this operation, 1,848 kB disk space will be freed.
Do you want to continue? [Y/n] 
Err:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385
  404  Not Found [IP: 91.189.95.85 80]
Err:2 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-upgrade amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 91.189.95.85 80]
Err:3 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-upgrade-gtk amd64 1.0.0~1628609583~21.04~d3061df
  404  Not Found [IP: 91.189.95.85 80]
Ign:4 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b
Ign:5 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
Err:4 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell all 1.1.0~1628180617~21.04~b76b83b
  404  Not Found [IP: 91.189.95.85 80]
Err:5 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 pop-shell-plugin-system76-power all 1.1.0~1628180617~21.04~b76b83b
  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/pop-upgrade_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-upgrade/libpop-upgrade-gtk_1.0.0%7e1628609583%7e21.04%7ed3061df_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-shell/pop-shell-plugin-system76-power_1.1.0%7e1628180617%7e21.04%7eb76b83b_all.deb  404  Not Found [IP: 91.189.95.85 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I have tried to fix it based on the documentation without any success

per https://support.system76.com/articles/package-manager-pop

sudo apt clean
sudo apt update -m
sudo dpkg --configure -a
sudo apt install -f
sudo apt full-upgrade
sudo apt autoremove --purge

I've used several Linux distro's (Mint, Kubuntu, Ubuntu) over the years and have never run into this before. I can find the individual packages via the website and did do a test download and manual install of one but really do not want to download each one individually and risk possible dependency issues.

Example of one of the individual packages I downloaded

http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0~1628642559~21.04~9f5ee83_amd64.deb

Very curious as to why this is broken.

Hope to see it fixed soon.

Thanks,

Robert

**Comment by FilBot3** [comment]
To say `I have this issue too`, or `me too`, just thumbs up the first post.

**Comment by FilBot3** [comment]
Looking at the 

* http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/

it seems that,

```bash
libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
```

Full output

```bash
➜  ~ sudo apt clean
[sudo] password for filbot:
➜  ~ sudo apt update -m
Hit:1 http://us.archive.ubuntu.com/ubuntu hirsute InRelease
Get:2 http://us.archive.ubuntu.com/ubuntu hirsute-security InRelease [101 kB]
Hit:3 http://apt.pop-os.org/proprietary hirsute InRelease
Hit:4 http://ppa.launchpad.net/system76/pop/ubuntu hirsute InRelease
Hit:5 http://packages.microsoft.com/repos/code stable InRelease
Hit:6 http://us.archive.ubuntu.com/ubuntu hirsute-updates InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu hirsute-backports InRelease
Hit:8 https://dl.winehq.org/wine-builds/ubuntu hirsute InRelease
Fetched 101 kB in 1s (75.7 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
➜  ~ sudo dpkg --configure -a
➜  ~ sudo apt install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
➜  ~ sudo apt full-upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libpop-desktop-widget
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 669 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Err:1 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 libpop-desktop-widget amd64 0.1.0~1627939102~21.04~38f3385
  404  Not Found [IP: 91.189.95.85 80]
E: Failed to fetch http://ppa.launchpad.net/system76/pop/ubuntu/pool/main/p/pop-desktop-widget/libpop-desktop-widget_0.1.0%7e1627939102%7e21.04%7e38f3385_amd64.deb  404  Not Found [IP: 91.189.95.85 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
➜  ~
```

**Comment by Division991** [comment]
I have this problem

**Comment by ronaldofas** [comment]
I have the same problem too, but Is not a clean installation.

**Comment by robertstrom** [comment]
I was just able to update without issue. Somebody must have fixed the issue.

No errors using either Pop!_Shop or the CLI

**Comment by thiagolucio** [comment]
Solved in my Pop!

**Comment by FilBot3** [comment]
This should be fixed. I was able to install via Pop! Shop. @mj-crabtree , check and you could probably close this now.

**Comment by mj-crabtree** [comment]
fixed my end. cheers!
