### ISSUE TITLE
The PoP OS Works Fine On Clevo Hardware 

### ISSUE THREAD

**Issue by Lukeskywalkermint** [pop-os/pop#187]
**Distribution - (run ```cat /POP OS Nvidia Version / Ubuntu 17.10```)**

 It runs all Hardware Fine But It needs A Driver to Control Keyboard Lights 
And Video Drivers Intel and Nvidia looks Funky When you Scroll Up And Down on Web Pages And Apps

I Understand They want to differentiate from Others But They Should allow People to Use the Cinnamon Desktop Out Of the box Is  more User Friendly and for newbies  knows were everything is located.

The store Software is Limited This should be Compatible with all Linux mint and Ubuntu Compatible Software no excuses

Wine HQ Don't Even Installs correctly

Mozilla Thunderbird must be included for the Business oriented Customer (a must have)

**Comment by jackpot51** [comment]
I recommend that you break this into seperate issues that are more granular, and include more information.

I am also unsure of your meaning due to unnecessary and inconsistent capitalization.
