### ISSUE TITLE
Trackpad not working - reboot required (Darter_Pro darp7)

### ISSUE THREAD

**Issue by blacknight659** [pop-os/pop#1871]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
System, trackpad (unknown package)

**Issue/Bug Description:**
Occasionally (every between 1-5 system boot/reboot) the trackpad will not start along with the system. Cursor is visible in lower right portion of the display, but is not responsive. A second boot/reboot will bring the trackpad back into operation. 

**Steps to reproduce (if you know):**
1. Power-on OR Reboot
2. Enter drive encryption password
<trackpad is NOT working at this point>
3. Select user (able to select user with keyboard)
4. Enter Password (able to enter password with keyboard)
5. Interact with desktop env (can interact with keyboard, but NOT trackpad)

**Expected behavior:**
1. Power-on OR Reboot
2. Enter drive encryption password
<TRACKPAD SHOULD BE WORKING>
3. Select user 
4. Enter Password 
5. Interact with desktop env 

**Other Notes:**

Unable to identify steps to cause this issue.

**Comment by jacobgkau** [comment]
Have you opened a [support ticket](https://support.system76.com/) for this issue yet? It could be a hardware defect.

When this issue occurs, does suspending and resuming the system with Fn-F12 get the touchpad working without having to completely reboot? Do you ever see the touchpad stop working after a suspend/resume, or is it only after a boot/reboot?
