### ISSUE TITLE
Bug displaying folders and programs - Show Apps

### ISSUE THREAD

**Issue by igmriegel** [pop-os/pop#1872]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Show apps menu

**Issue/Bug Description:**

When I access the show apps menu some of the apps and folders appear clustered and stacked on the left upper corner.
![Peek 16-08-2021 19-53](https://user-images.githubusercontent.com/43209530/129639019-ec9facfb-ee9c-4c2d-b8bd-51ad27df7b5b.gif)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by ahmed-kaif** [comment]
@igmriegel  can you tell me what is your dock icon size? is it set to custom value? custom value creates problem in displaying the application icons.

**Comment by igmriegel** [comment]
@ahmed-kaif  I'm right now using the default small size to my dock icons. It does not seem to change the behavior I described...

**Comment by igmriegel** [comment]
I'm closing this issue after updating my system to Pop!_OS 21.10.
