### ISSUE TITLE
21.10 Hardware Enablement Backports

### ISSUE THREAD

**Issue by jackpot51** [pop-os/pop#1888]
We will backport the kernel (5.13) and mesa (21.1.4) from 21.10 to 20.04 and 21.04 so we can continue to support new hardware, like the RX 6600XT.

- [x] linux: https://github.com/pop-os/linux/pull/68
  - [x] 20.04
  - [x] 21.04
- [x] linux-firmware: https://github.com/pop-os/linux-firmware/pull/15
  - [x] 20.04
  - [x] 21.04
- [x] mesa: https://github.com/pop-os/mesa/pull/2
  - [x] 20.04
  - [x] 21.04
- [x] virtualbox: https://github.com/pop-os/virtualbox/pull/2
  - [x] 20.04
  - [x] 21.04
- [ ] Provide test ISOs to Linux reviewers to ensure out of the box support for RX6600XT: https://twitter.com/jeremy_soller/status/1432457982567088128

**Comment by leviport** [comment]
So far I've tested both 20.04 and 21.04 on darp6, gaze16, and thelio-r2 (both with integrated graphics and a 3060Ti). I'm going to spend a little time paying special attention to lemp9 and lemp10 since those had problems with kernel updates in the past.

**Comment by mbacarella** [comment]
I'd like to endorse 5.13 as an lemp10 user. Upgrading from stock kernel 5.11 to 5.13 solves a pretty nasty random but fairly immediate after-boot disk I/O bug I was experiencing, which persisted after replacing the disk and reinstalling the OS.

**Comment by leviport** [comment]
@mbacarella Have you noticed any trouble with Thunderbolt?

**Comment by mbacarella** [comment]
> @mbacarella Have you noticed any trouble with Thunderbolt?

Sorry, what's Thunderbolt?

**Comment by wsturgiss** [comment]
I have a 6600xt and would be willing to test this when its ready.

**Comment by leviport** [comment]
I was able to test with a 6600XT and it appears to work fine after these updates.
