### ISSUE TITLE
Blank Applications Menu

### ISSUE THREAD

**Issue by jeffbrown12** [pop-os/pop#1894]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Application icons not displayed in application menu (Super-A/Show Applications)

**Expected behavior:**
Application icons and icon groups display when accessing the Show Applications Menu or pressing hotkey combination.

**Other Notes:**
System: System76 Gazelle w/GTX1650TI
Installed Gnome Extensions other than System 76 specific for Cosmic and Pop_OS: Desktop Icons NG, Open Weather, Ubuntu AppIndicators, User Themes.

Work-around - if you type anything into the search bar at the top of the Applications Menu then delete, the icons will appear.

What I've tried: Disabling all extensions (followed by reboot), removing and reinstalling NVidia graphics driver packages (followed by reboot), booting into integrated graphics, booting into hybrid graphics

**Comment by PixsaOJ** [comment]
![image](https://user-images.githubusercontent.com/12684017/132410092-76878d9c-5f53-4b73-97e0-de9f423e083a.png)


This is from a recent update. First item should be terminal emulator Alacrityy

**Comment by jeffbrown12** [comment]
Turns out my issue was caused by residual settings left behind by an incomplete un-install of Gnome extension Dash-to-Dock conflicting with the Cosmos dock settings.

**Comment by PixsaOJ** [comment]
I don't think I had incomplete installation, however I did switch to Dash to panel, and changed many settings back and force. Switching to Dash to panel did not fix my issue right away, but now it is gone, so... Maybe that really is a problem?

**Comment by PixsaOJ** [comment]
I confirm, This issue happens when Dash to dock extension or Cosmic Dock is enabled.

**Comment by jeffbrown12** [comment]
"Incomplete uninstall" may not be 100% correct, but the removal process for Dash-to-Dock (and quite possibly for other gnome extensions as well) leaves all the settings in the dconf database, probably so you can return to your old set-up if you decide to reinstall later. You can verify by opening the dconf editor and going to org.gnome.shell.extensions.dash-to-dock (or whatever extension you've previously used). I ended-up re-installing Dash-to-dock and disabling settings one-at-a-time until my apps menu came back. Kind of a tedious process but it fixed my issue.

The other possibility, if you know how, is to remove those settings in the deconf database. I couldn't find anything on how to do that and gave up looking after awhile.

**Comment by ryan-micky-g** [comment]
okay good to know! I use Arc Menu anyways, but I will keep an eye on App Grid through the beta to see if the changes result in all bugs being resolved. 

I noticed this completely by accident. :-P

**Comment by WatchMkr** [comment]
Applications menu is being replaced for 21.10.

**Comment by jabbermacy** [comment]
if you toggle cosmic dock apps come back
