### ISSUE TITLE
Full disk encryption fails after updating kernel to 4.13.0.15

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#19]
_From @jackpot51 on October 12, 2017 15:20_

From `iapain` in https://chat.pop-os.org/community/channels/town-square

4.13.0.12 works fine, after updating to 4.13.0.15 it just doesn't asks for password anymore.

_Copied from original issue: pop-os/iso#150_

**Comment by isantop** [comment]
_From @Jeymz on October 12, 2017 20:38_

Tested with ISO 33 unable to replicate issue.

**Comment by isantop** [comment]
_From @iapain on October 13, 2017 13:9_

@jackpot51 Problem still persists. Often when new OS update appears then after boot it doesn't asks for password (LUKS). It stucks on

```
Waiting for rool file system ...
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
...
Gave up waiting for root device
falls to initramfs
```

**Comment by isantop** [comment]
_From @Jeymz on October 14, 2017 12:44_

are you installing the intel Microcode Driver?

**Comment by isantop** [comment]
_From @iapain on October 14, 2017 21:30_

Yes.

**Comment by isantop** [comment]
_From @jackpot51 on October 16, 2017 15:41_

@brs17 The user started with ISO `#31`

**Comment by isantop** [comment]
_From @brs17 on October 17, 2017 15:36_

@iapain So you don't get asked for a password when the system boots, then what happens? Are you taken straight to the login screen or are you unable to login at all?

**Comment by isantop** [comment]
_From @iapain on October 17, 2017 20:57_

@brs17 it could not find mapping volume and fallbacks to initramfs. No password asked!

I tested it without intel microcode driver and it works fine. It does asks for password and volume is correctly mapped and then boots.

**Comment by isantop** [comment]
_From @brs17 on October 17, 2017 21:16_

@iapain What hardware do you have on the machine you are having this issue with?

**Comment by isantop** [comment]
_From @iapain on October 17, 2017 21:40_

```
xxxxxx@pop-os:~$ lspci
00:00.0 Host bridge: Intel Corporation Skylake Host Bridge/DRAM Registers (rev 07)
00:01.0 PCI bridge: Intel Corporation Skylake PCIe Controller (x16) (rev 07)
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 530 (rev 06)
00:14.0 USB controller: Intel Corporation Sunrise Point-H USB 3.0 xHCI Controller (rev 31)
00:14.2 Signal processing controller: Intel Corporation Sunrise Point-H Thermal subsystem (rev 31)
00:16.0 Communication controller: Intel Corporation Sunrise Point-H CSME HECI #1 (rev 31)
00:17.0 SATA controller: Intel Corporation Sunrise Point-H SATA controller [AHCI mode] (rev 31)
00:1c.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #1 (rev f1)
00:1c.1 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #2 (rev f1)
00:1c.4 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #5 (rev f1)
00:1d.0 PCI bridge: Intel Corporation Sunrise Point-H PCI Express Root Port #9 (rev f1)
00:1f.0 ISA bridge: Intel Corporation Sunrise Point-H LPC Controller (rev 31)
00:1f.2 Memory controller: Intel Corporation Sunrise Point-H PMC (rev 31)
00:1f.3 Audio device: Intel Corporation Sunrise Point-H HD Audio (rev 31)
00:1f.4 SMBus: Intel Corporation Sunrise Point-H SMBus (rev 31)
00:1f.6 Ethernet controller: Intel Corporation Ethernet Connection (2) I219-LM (rev 31)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Venus XTX [Radeon HD 8890M / R9 M275X/M375X] (rev 83)
01:00.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Cape Verde/Pitcairn HDMI Audio [Radeon HD 7700/7800 Series]
02:00.0 Network controller: Intel Corporation Wireless 8260 (rev 3a)
03:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS525A PCI Express Card Reader (rev 01)
6f:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM961/PM961
```

**Comment by isantop** [comment]
@brs17 Any updates on tracking this issue down?

**Comment by ahoneybun** [comment]
Did they run:

apt update
apt autoremove 

after the install?

It's possible someone has been able to recreate this in a VM, trying to get more information.

**Comment by iapain** [comment]
@brs17 Looks like recent upgrade fixes the issue. Earlier I had to load kernel which was shipped with initial build but now I've booted to newer kernel and it does asks for password. Until week ago it didn't work.

**Comment by brs17** [comment]
That is great to hear @iapain. Going to close this issue but if additional related issues arise, feel free to open a new issue or reopen this one if appropriate.
