### ISSUE TITLE
Black box appears behind installer on hidpi systems

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#190]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 debug#8&9
 
**Issue/Bug Description**

On hidpi machines, a black box appears behind the installer. This does not go away with a mouse over or clicking on the area.
 
![screenshot from 2018-04-11 18-20-21](https://user-images.githubusercontent.com/7460774/38683365-838c81b2-3e2a-11e8-9e8d-438ac11c9387.png)

This does not effect the installation but is a subpar first impression.

**Comment by cassidyjames** [comment]
I've seen this when switching the scaling factor of a GTK window live. I wonder if the installer is starting before Mutter or GNOME Shell are starting, so when it starts, it's changing the scaling factor from unset (1) to 2.

**Comment by jackpot51** [comment]
@cassidyjames that sounds probable

**Comment by brs17** [comment]
Let's change the sleep time to 3 seconds and try again.

1 second was too long, 5 seems too long on some machines

**Comment by brs17** [comment]
Fixed in time for release.
