### ISSUE TITLE
Cannot update Pop OS component from PopShop

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/pop#1901]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When I tried to update pop os component, it shows error with message like this:
```
The following packages have unmet dependencies:
  update-notifier-common: Depends: update-manager-core (>= 1:17.04.2) but 1.0.0~1630504302~20.04~c43efce is to be installed

```
if i run sudo apt update, not all components are updated. Only a few.

**Steps to reproduce (if you know):**
Go to pop shop then update the pop component

**Expected behavior:**
Should update correctly

**Other Notes:**
![Screenshot from 2021-09-09 19-57-27](https://user-images.githubusercontent.com/26734262/132690321-3e4510b3-9b85-4f08-89e2-4e030a5f0801.png)

![Screenshot from 2021-09-09 20-00-36](https://user-images.githubusercontent.com/26734262/132690425-0ecf9af8-bc79-4fcd-b5b7-16c46daa4f57.png)

**Comment by leviport** [comment]
This looks to be related to https://github.com/pop-os/upgrade/issues/213

Does it clear up if you run `sudo apt update && sudo apt full-upgrade` ?

**Comment by ydhnwb** [comment]
Does full upgrdae make my machine download pop os 21.04? I want to keep in 20.04

**Comment by leviport** [comment]
No, it will not upgrade your release version

**Comment by mmstick** [comment]
Same issue as https://github.com/pop-os/upgrade/issues/213
