### ISSUE TITLE
Failed to fetch updates. Repo is not (yet) available. Temporary failure resolving socks5.

### ISSUE THREAD

**Issue by TermoZour** [pop-os/pop#1908]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 21.04 hirsute
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
installed & candidate: `pop-shop 3.4.2pop0\~1625253683\~21.04\~eff4ef8`

**Issue/Bug Description:**
I get a popup saying "Failed to fetch updates. This may have been caused by external, manually added software repositories or a corrupted sources file."

Error shown in Details panel:
`E: http://apt.pop-os.org/proprietary hirsute InRelease is not (yet) available (Temporary failure resolving 'socks5')`

**Steps to reproduce (if you know):**
1. Enter proxy settings for network
2. Remove proxy settings
3. Open pop-shop
4. Error shows up.

**Expected behavior:**
Open pop-shop. Expect the app to refresh repos properly/install apps properly without this socks5 issue showing up.

**Other Notes:**
Other repo URLs also show up in the error page. All of them with the socks5 error.
I needed a proxy so I added my proxy settings in network control panel. When I didn't need the proxy, I removed the settings from my network and carried on with my work. At some point, when I removed the proxy settings and went to pop-shop, this error started popping up.

**Comment by ziacik** [comment]
Have you found any workaround to this?
