### ISSUE TITLE
User not aligned on user menu

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#191]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 debug build#10
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
GNOME

**Issue/Bug Description**
The user icon and name is not aligned with everything else.

![screenshot from 2018-04-12 15-43-00](https://user-images.githubusercontent.com/7460774/38706229-ab84a868-3e69-11e8-9ec9-59cb701bcd1a.png)

**Expected behavior**
Everything is aligned.

**Comment by cassidyjames** [comment]
Can confirm here. It's aligned in Adwaita and the old theme, but not the new one.

**Comment by isantop** [comment]
Fixed in the Feedback branch

**Comment by brs17** [comment]
Fixed here: https://github.com/pop-os/gnome-shell-theme/pull/10
