### ISSUE TITLE
Unable to update libglx-mesa0

### ISSUE THREAD

**Issue by SavexG** [pop-os/pop#1910]
Hello I'm new to Linux so please try to simplify any followup questions to my report (if there are any)

I'm on popOS 20.04 LTS 

I'm wanted to report this issue where it tells me there is a operating system update in the popOS shop but the update can not be installed:

Failed to update “Operating System Updates”
This may have been caused by external or manually compiled software.

The following packages have unmet dependencies:
  libglx-mesa0: Depends: libgl1-mesa-dri but it is not going to be installed

my conclusion was to just manually install the unmet dependencies then by running sudo apt install libgl1-mesa-dri
this gave me this: 

The following packages have unmet dependencies:
 libgl1-mesa-dri : Depends: libglapi-mesa (= 21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49) but 20.0.4-2ubuntu1 is to be installed
                   Depends: libllvm12 (>= 1:9~svn298832-1~) but it is not installable
E: Unable to correct problems, you have held broken packages.

Then I did sudo apt install libglapi-mesa, but this will effectively break peoples system completely: 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apg apport apport-symptoms avahi-utils cheese-common cups-pk-helper
  docbook-xml evolution-data-server-common firmware-manager-notify
  firmware-manager-shared folks-common fprintd gir1.2-accountsservice-1.0
  gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdm-1.0 gir1.2-gnomebluetooth-1.0
  gir1.2-graphene-1.0 gir1.2-handy-0.0 gir1.2-nm-1.0 gir1.2-nma-1.0
  gir1.2-polkit-1.0 gir1.2-rsvg-2.0 gir1.2-secret-1 gir1.2-upowerglib-1.0
  gkbd-capplet gnome-control-center-data gnome-control-center-faces
  gnome-session-common gnome-settings-daemon gnome-shell-common
  gnome-shell-extension-system76-power gstreamer1.0-pulseaudio
  gtk2-engines-murrine ippusbxd libcamel-1.2-62 libclutter-1.0-common
  libcogl-common libcolord-gtk1 libdouble-conversion3 libebackend-1.2-10
  libebook-1.2-20 libebook-contacts-1.2-3 libecal-2.0-1 libedata-book-1.2-26
  libedata-cal-2.0-1 libedataserver-1.2-24 libegl1 libevdev2
  libfirmware-manager libfolks25 libfontenc1 libfprint-2-2 libfprint-2-tod1
  libgdm1 libgles2 libglvnd0 libgmime-3.0-0 libgnomekbd-common libgnomekbd8
  libgraphene-1.0-0 libgsound0 libgstreamer-plugins-bad1.0-0 libinput-bin
  libinput10 libjavascriptcoregtk-4.0-18 libmessaging-menu0 libmtdev1
  libpam-fprintd libphonenumber7 libpop-theme-switcher libpop-upgrade-gtk
  libpulse-mainloop-glib0 libqalculate20 libqalculate20-data libqt5core5a
  libqt5dbus5 libqt5gui5-gles libqt5network5 libqt5widgets5
  librygel-core-2.6-2 librygel-db-2.6-2 librygel-renderer-2.6-2
  librygel-server-2.6-2 libs76-hidpi-widget libsbc1 libva-wayland2
  libwacom-bin libwacom-common libwacom2 libwebpdemux2
  libwhoopsie-preferences0 libwhoopsie0 libwoff1 libxcb-glx0 libxcb-res0
  libxcb-shape0 libxcb-xinerama0 libxcb-xinput0 libxcb-xv0 libxfont2
  libxkbfile1 libxklavier16 libxxf86dga1 libytnef0
  mobile-broadband-provider-info mutter-common network-manager-gnome
  policykit-1-gnome pop-gnome-shell-theme pop-gtk-theme pop-icon-theme
  pop-launcher pop-shell pop-shell-plugin-system76-power pop-shell-shortcuts
  pop-sound-theme pop-theme pulseaudio-module-bluetooth python3-apport
  python3-blinker python3-cups python3-cupshelpers python3-entrypoints
  python3-httplib2 python3-jwt python3-keyring python3-launchpadlib
  python3-lazr.restfulclient python3-lazr.uri python3-oauthlib
  python3-problem-report python3-secretstorage python3-simplejson
  python3-systemd python3-wadllib qalc qt5-gtk-platformtheme
  qttranslations5-l10n rygel session-migration sgml-base sgml-data
  switcheroo-control system-config-printer system-config-printer-common
  system-config-printer-udev system76-power whoopsie-preferences x11-apps
  x11-session-utils x11-xkb-utils xbitmaps xfonts-base xfonts-encodings
  xfonts-scalable xfonts-utils xinit xinput xml-core xserver-common
  xserver-xorg-legacy yaru-theme-gnome-shell yelp-xsl zenity-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libegl-mesa0 libgbm1 libqt5gui5-gles policykit-1-gnome
Suggested packages:
  qt5-image-formats-plugins qtwayland5
Recommended packages:
  libqt5svg5
The following packages will be REMOVED:
  chrome-gnome-shell evolution-data-server flameshot gdm3 geary
  gir1.2-mutter-6 gnome-control-center gnome-getting-started-docs
  gnome-session-bin gnome-shell
  gnome-shell-extension-alt-tab-raise-first-window
  gnome-shell-extension-always-show-workspaces
  gnome-shell-extension-appindicator gnome-shell-extension-desktop-icons-ng
  gnome-shell-extension-pop-shop-details gnome-shell-extension-prefs
  gnome-tweaks gnome-user-docs gstreamer1.0-clutter-3.0 gstreamer1.0-vaapi
  libcheese-gtk25 libcheese8 libclutter-1.0-0 libclutter-gst-3.0-0
  libclutter-gtk-1.0-0 libcogl-pango20 libcogl-path20 libcogl20
  libedataserverui-1.2-2 libgl1 libgl1-mesa-dri libglu1-mesa libglx-mesa0
  libglx0 libgoa-backend-1.0-1 libgstreamer-gl1.0-0 libmutter-6-0 libqt5gui5
  libqt5svg5 libvdpau-va-gl1 libwebkit2gtk-4.0-37 libyelp0 mutter
  pop-default-settings pop-desktop pop-gnome-initial-setup pop-session
  ubuntu-docs x11-utils xorg xserver-xephyr xserver-xorg xserver-xorg-core
  xserver-xorg-input-all xserver-xorg-input-libinput xwayland yelp zenity
The following NEW packages will be installed:
  libqt5gui5-gles policykit-1-gnome
The following packages will be upgraded:
  libegl-mesa0 libgbm1 libglapi-mesa
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-session (due to pop-desktop)
  gnome-control-center (due to pop-desktop)
  pop-gnome-initial-setup (due to pop-desktop)
  chrome-gnome-shell (due to pop-desktop) gdm3 (due to pop-desktop)
  gnome-shell (due to pop-desktop) xorg (due to pop-desktop)
  pop-default-settings (due to pop-desktop)
  gstreamer1.0-vaapi (due to pop-desktop) libvdpau-va-gl1 (due to pop-desktop)
3 upgraded, 2 newly installed, 58 to remove and 4 not upgraded.
Need to get 3,247 kB of archives.
After this operation, 399 MB disk space will be freed.
You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
 ?] 

if anyone that has no Linux experience runs this command with "Yes, do as I say" they will not be able to properly use their pc anymore and break their system after a reboot, just wanted you to be aware of this issue 

![image](https://user-images.githubusercontent.com/65229679/133788735-2d051949-5a4b-4509-8a16-e9ed3cc43dd0.png)

![image](https://user-images.githubusercontent.com/65229679/133788814-f5647917-a3c9-4874-8d32-02273dbfb565.png)

**Comment by mmstick** [comment]
We can't stop someone from going out of their way to ignore all warnings and type out "Yes, do as I say" despite the strong warning about the operating being harmful.

**Comment by SavexG** [comment]
Yes I understand but why does the update even show up in the first place when it's not even possible to do?

**Comment by jacobgkau** [comment]
```
The following packages have unmet dependencies:
 libgl1-mesa-dri : Depends: libglapi-mesa (= 21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49) but 20.0.4-2ubuntu1 is to be installed
                   Depends: libllvm12 (>= 1:9~svn298832-1~) but it is not installable
```

The version listed for `libglapi-mesa` is the version that's currently being shipped. I have it installed on a 20.04 test machine. The version listed for `libllvm12` is strange, it doesn't look like a version that Ubuntu is shipping for 20.04.

Can you please provide the output of `apt policy libgl1-mesa-dri libglapi-mesa libllvm12` so we can see what versions your system thinks is available for all of these packages? Also, do you have Steam installed? If you can create a list of installed packages with `apt list --installed > packages.txt` and a list of configured sources with `cat /etc/apt/sources.list{,.d/*} > sources.txt` and provide those lists, that may be helpful as well.

**Comment by SavexG** [comment]
1)
save@pop-os:~ $ apt policy libglx-mesa0 libgl1-mesa-dri libglapi-mesa libllvm12
libglx-mesa0:
  Installed: 20.0.4-2ubuntu1
  Candidate: 21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49
  Version table:
     21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
 *** 20.0.4-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
libgl1-mesa-dri:
  Installed: 20.0.4-2ubuntu1
  Candidate: 21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49
  Version table:
     21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
 *** 20.0.4-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
libglapi-mesa:
  Installed: 20.0.4-2ubuntu1
  Candidate: 21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49
  Version table:
     21.2.1-2ubuntu1pop0~1631200248~20.04~4d5cd49 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
 *** 20.0.4-2ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
libllvm12:
  Installed: (none)
  Candidate: (none)
  Version table:


2)
[packages.txt](https://github.com/pop-os/pop/files/7186623/packages.txt)


3
[sources.txt](https://github.com/pop-os/pop/files/7186629/sources.txt)
)

**Comment by jacobgkau** [comment]
@SavexG Your system does not have the `focal-updates` repository. That is why `libllvm12` has no candidate version. `focal-updates` is enabled out-of-the-box. I see that you've added a number of other repositories, and this one must have gotten removed at some point.

If you open Repoman by running `repoman` or clicking the gear icon in the Pop!_Shop, navigate to the `Updates` page, and make sure `focal-updates` is checked (along with `focal-security` and `focal-backports`):

![Screenshot from 2021-09-17 11-10-11](https://user-images.githubusercontent.com/7199422/133827564-2484db0f-6662-4163-9bf3-17efdffe8d6f.png)

Then run `sudo apt update` and `apt policy libllvm12` again, you should see a candidate version listed. Your updates should then install normally. Can you confirm this?

Any information about how you updated your mirrors and other sources that resulted in this configuration would also be helpful, so we can understand how users are getting into this situation and potentially prevent it.

**Comment by SavexG** [comment]
@jacobgkau thank you very much I think this worked the only issue I have no is that my /boot ran out of disk space during the update but everything else worked

> Any information about how you updated your mirrors and other sources that resulted in this configuration would also be helpful

I only add repos when it's suggested in a guide to download something and I always remove repos when they give me a error message due to a repo so that's probably why I had some removed 
but I can't remember at all that I unchecked those 3 boxes (focal-security,....) ever.

**Comment by jacobgkau** [comment]
Thank you for the additional information. I'm glad to hear that the system is working again after adding back the system repositories. I'm closing this issue because it sounds like it was a configuration error.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).
