### ISSUE TITLE
Screen Crash on wake

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/pop#192]
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description**
Dell Latitude E6400 laptop.
When I opened the lid today the screen had gone crazy and the machine was unresponsive.  I'm running the Intel version with full disk encryption.  After a hard reboot the system started as normal.
![image](https://user-images.githubusercontent.com/1308152/38712000-ca2203c4-3e7d-11e8-86cc-6dbba9d060e2.png)

**Steps to reproduce (if you know)**
Close laptop lid without shutting down computer.
Reopen lid at later time.
Computer crashes.

**Expected behavior**

Computer wakes up normally.

**Other Notes**
This has only happened once, so we'll see. If memory serves only Chrome was open at the time.

**Comment by Appalbarry** [comment]
No. It seems it was a one-off thing, at least since a fresh install of 18.10

**Comment by brs17** [comment]
Awesome!
