### ISSUE TITLE
Launcher sometimes does not show opened apps.

### ISSUE THREAD

**Issue by killer4639** [pop-os/pop#1936]

**Comment by leviport** [comment]
The issue template helps us a lot with things like this. Can you give us the output of `cat /etc/os-release`? How often are you seeing it happen? Is there anything in particular you've found that induces this behavior? Does restarting gnome-shell (alt+f2, `r`, enter) solve it?

**Comment by killer4639** [comment]
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

This is the output of cat /etc/os-release

How often are you seeing it happen?
Like 60-70% of the time I'm using my laptop.

Does restarting gnome-shell (alt+f2, r, enter) solve it?
No, it did not.

**Comment by BorysSerbyn** [comment]
Hi, I also have this issue. Restarting my computer seems to be the only way to solve it, but not for long. I also noticed that it opens new windows of already opened applications.

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

**Comment by jacobgkau** [comment]
Would either of you happen to be using Spotify? If so, it would be the same issue as this: https://github.com/pop-os/shell/issues/1208
