### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by malanak2** [pop-os/pop#1939]
**Distribution (run `cat /etc/os-release`):**
 will be updated, but it happens on os installation, so... (dont have acces to ps rn)
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

none

**Issue/Bug Description:**
 When selecting czech language on installation, the installation does not open the restart pc window, and when restarted, there is just black screen with flickering _

**Steps to reproduce (if you know):**
New os installation, specificly the nvidia version. Select this language: "čeština". Then proceed with the installation as you want. Select any keyboard setup, etc.

**Expected behavior:**
Booting up into the login screen

**Other Notes:**

**Comment by jacobgkau** [comment]
I ran the installer with `pkexec io.elementary.installer`, found the Rust error message being shown from this crash, and created https://github.com/pop-os/distinst/pull/267 to fix this issue.

https://github.com/pop-os/installer/issues/185 is a different issue-- that one entails a failed installation, but the installer does not actually crash.
