### ISSUE TITLE
Program "Videos" bug

### ISSUE THREAD

**Issue by LWJerri** [pop-os/pop#1947]
**Distribution (run `cat /etc/os-release`):**
```text
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Program `Videos`

**Issue/Bug Description:**
When I use full-screen mode, the program starts a bug and every time resizes the icon and if wait - the laptop stop working.

https://user-images.githubusercontent.com/50290430/136853016-2e2d0fe8-5f43-4311-b50d-67cf96e0a17f.mp4

**Steps to reproduce (if you know):**
1. Open random video.
2. Click on a full-screen button.
![image](https://user-images.githubusercontent.com/50290430/136852281-e72ed646-b38f-401e-99c3-70c6cede3d8e.png)
3. See bug.

**Expected behavior:**
- Normal full-screen video displaying.

**Comment by bflanagin** [comment]
Thanks for your report. However, Videos (Totem) is a part of the Gnome project's application suite and not maintained by us. If you could submit the issue over on the program's gitlab page they will be able to help you further.

Gitlab: https://gitlab.gnome.org/GNOME/totem/-/issues
