### ISSUE TITLE
Kernel update errors on encypted volume. Full /boot. 'autoremove' and 'full-upgrade' errors.

### ISSUE THREAD

**Issue by Eurus100** [pop-os/pop#1981]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Running updates through both the Pop!_Shop and the terminal a couple of days ago threw errors involving kernel 5.13 updates. (Sorry, I don't currently have the original log of the error on hand — had trouble parsing the journal — but do have detailed errors below of my attempt to address the problem.)  

It also appears my /boot is full.  This installation has standard default full-encryption using legacy BIOS on an old Galago Ultra Pro.  (*Install defaulted to GRUB with legacy BIOS install.)  Assume I can't easily increase /boot size on an encrypted install.

Thought the issue with old kernels not being flagged for removal was resolved quite a while back.

'sudo apt autoremove' returns errors involving cryptsetup and cryptswap:

"Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up initramfs-tools (0.139ubuntu3) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.139ubuntu3) ...
update-initramfs: Generating /boot/initrd.img-5.13.0-7620-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.13.0-7620-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)

'sudo apt full-upgrade' threw similar errors:

"Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up initramfs-tools (0.139ubuntu3) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.139ubuntu3) ...
update-initramfs: Generating /boot/initrd.img-5.13.0-7620-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
Error 24 : Write error : cannot write compressed block 
E: mkinitramfs failure cpio 141 lz4 -9 -l 24
update-initramfs: failed for /boot/initrd.img-5.13.0-7620-generic with 1.
dpkg: error processing package initramfs-tools (--configure):
 installed initramfs-tools package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 initramfs-tools
E: Sub-process /usr/bin/dpkg returned an error code (1)"

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

I'm a bit nervous to try to manually delete entries in /boot at the moment, and I'm not sure how that would even resolve the cryptsetup errors.  For what it's worth, I haven't manually downloaded extra kernels — /boot only has whatever I have received during standard updates over the life of this install.

Side note:  I really want to thank all of the hardworking devs, contributors, System76 employees and community members that make Pop!_OS the best OS I have ever used. Thank you so much for all of the hard work you do!!!

**Comment by Eurus100** [comment]
Ended up manually deleting kernels and doing sudo apt full-upgrade.  This seems to have also resolved the cryptsetup warnings.

Won't close this report myself, in case someone wants to explore whether or not old kernels are being flagged correctly or look into the cryptsetup warnings.

Cheers!

**Comment by leviport** [comment]
This can be reopened if others experience the same thing
