### ISSUE TITLE
VirtualBox won't close.

### ISSUE THREAD

**Issue by DavidSmolinski** [pop-os/pop#1987]
**Distribution (run `cat /etc/os-release`):**
 
 VERSION="21.04"
 
**Related Application and/or Package Version (run `apt policy virtualbox`):**

  Installed: 6.1.26-dfsg-4pop0~1631198478~21.04~f648cb0
  Candidate: 6.1.26-dfsg-4pop0~1631198478~21.04~f648cb0

**Issue/Bug Description:**

bug 1:
The dock (bottom menu) has a dot that shows VirtualBox is open after I closed it.

bug 2:
In the dock, if I right click the VirtualBox icon, a menu appears in the top left. It doesn't close easily. To close it, in the dock double click "Show Workspaces". Turn your second monitor on/off before repeating the bug.

image of both issues:
https://drive.google.com/file/d/1ANLOX2_zTr47LyQx9xue_AOHxD2B8b_M/view?usp=sharing

**Comment by jacobgkau** [comment]
>  The command `apt policy $VirtualBox` didn't work.

The command would just be `apt policy VirtualBox`. Dollar signs are for environment variables.

**Comment by jacobgkau** [comment]
I'm not seeing either of these happen on Pop!_OS 22.04. Please comment if you're still experiencing an issue on the latest Pop!_OS, but otherwise, I assume this was fixed in the next major release after it was reported.
