### ISSUE TITLE
[ASUS ROG Crosshair VIII Hero Wi-Fi] Pop OS fails to boot on its first try after being off for around 10 hours

### ISSUE THREAD

**Issue by ImTheSquid** [pop-os/pop#1990]
**Distribution:**
```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version:**
Booting the system

**Issue/Bug Description:**
On the first boot after around 8-10 hours of the PC being off Pop gets stuck during the ACPI handoff with a VGA error and fails to POST. Holding down the power button to shut off and reboot or pressing the Reset button allows Pop to boot normally. Further boots (even after turning off and on the power supply) work fine as long as they happen within a small amount of time. The issue only occurs after a prolonged time.

**Steps to reproduce (if you know):**
Unknown.

**Expected behavior:**
Computer boots on first attempt.

**Other Notes:**
Motherboard: ASUS ROG Crosshair VIII Hero Wi-Fi
BIOS Version: 3401
POST Code: `AA`, white LED lit
GPU: Nvidia RTX 2080 SUPER
GPU Driver: Nvidia version 470.82.00
Drive encryption is enabled

**Comment by jacobgkau** [comment]
> Pop gets stuck during the ACPI handoff with a VGA error and fails to POST.

From what I understand, POST should happen before the UEFI or BIOS firmware loads an OS. This sounds more like a firmware issue. Does this not happen with other operating systems? Does it happen with Ubuntu or other Linux distributions?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by ImTheSquid** [comment]
I've booted Lubuntu on it before with the same BIOS revision and it worked fine. Lubuntu did use GRUB so it may be a problem with systemd-boot but I'm not 100% sure.

**Comment by ImTheSquid** [comment]
Turning off Fast Boot solved the problem.
