### ISSUE TITLE
Screen Lock Stopped working.

### ISSUE THREAD

**Issue by dustin-hawkins** [pop-os/pop#1993]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Super-Escape shortcut stopped working. Remapping to another key does not resolve the issue. 

Looks like it is calling `xdg-screensaver lock` correctly but nothing is happening. 

**Steps to reproduce (if you know):**

```
dhawkins@dhawkins-thelio:~$ bash -x xdg-screensaver lock
+ check_common_commands lock
+ '[' 1 -gt 0 ']'
+ parm=lock
+ shift
+ case "$parm" in
+ '[' 0 -gt 0 ']'
+ '[' -z '' ']'
+ unset XDG_UTILS_DEBUG_LEVEL
+ '[' 0 -lt 1 ']'
+ xdg_redirect_output=' > /dev/null 2> /dev/null'
+ mv -T ... ...
+ grep '\.\.\.'
+ DEBUG 1 'mv -T available'
+ '[' -z '' ']'
+ return 0
+ MV='mv -T'
++ echo :1
++ sed s/:/-/g
+ screensaver_file=/tmp/xdg-screensaver-dhawkins--1
++ which lockfile
+ lockfile_command=
++ which xprop
+ XPROP=/usr/bin/xprop
+ '[' xlock '!=' x ']'
+ action=
+ window_id=
+ case $1 in
+ action=lock
+ detectDE
+ unset GREP_OPTIONS
+ '[' -n pop:GNOME ']'
+ case "${XDG_CURRENT_DESKTOP}" in
+ '[' x = x ']'
+ '[' x '!=' x ']'
+ '[' xthis-is-deprecated '!=' x ']'
+ DE=gnome
+ '[' xgnome = x ']'
+ '[' xgnome = x ']'
+ '[' xgnome = xgnome ']'
+ which gnome-default-applications-properties
+ DE=gnome3
+ '[' -f /run/user/1000/flatpak-info ']'
+ xscreensaver-command -version
+ grep XScreenSaver
+ dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.gnome.ScreenSaver
+ DE=gnome_screensaver
+ dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.mate.ScreenSaver
+ dbus-send --print-reply --dest=org.freedesktop.DBus /org/freedesktop/DBus org.freedesktop.DBus.GetNameOwner string:org.cinnamon.ScreenSaver
+ xautolock -enable
+ '[' lock = resume ']'
+ perform_action lock
+ result=1
+ '[' lock = resume ']'
+ '[' lock = reset ']'
+ case "$DE" in
+ screensaver_gnome_screensaver lock
+ case "$1" in
+ dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
+ result=0
+ '[' -n :1 -a lock = suspend ']'
+ '[' lock = suspend ']'
+ '[' 0 -eq 0 ']'
+ exit_success
+ '[' 0 -gt 0 ']'
+ exit 0
```

executing `dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock` produces no output

```
dhawkins@dhawkins-thelio:~$ dbus-send --session --dest=org.gnome.ScreenSaver --type=method_call /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
dhawkins@dhawkins-thelio:~$ echo $?
0
```

**Expected behavior:**

The Screen Locks.

**Other Notes:**

**Comment by leviport** [comment]
Any chance you were running Phoronix Test Suite? It changes the gsetting `/org/gnome/desktop/lockdown/disable-lock-screen` to make sure test runs aren't interfered with by screen locks or suspends. It usually sets it back afterwards, but interrupting test runs can sometimes leave it disabled.

If not, I'd still check that gsetting in dconf-editor. Something else may have changed it, and changing it back might fix it.

**Comment by dustin-hawkins** [comment]
Man, that was it exactly.

checking journalctl 

`Nov 11 10:41:40 dhawkins-thelio gnome-shell[414105]: Screen lock is locked down, not locking`


```
dhawkins@dhawkins-thelio:~$ gsettings get org.gnome.desktop.lockdown disable-lock-screen
true
dhawkins@dhawkins-thelio:~$ gsettings set org.gnome.desktop.lockdown disable-lock-screen false
```

works again.
