### ISSUE TITLE
Uninstalls essential elements out of nowhere.

### ISSUE THREAD

**Issue by Kanishk951** [pop-os/pop#1996]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 21.04 Cosmic
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
apt 

**Issue/Bug Description:**
One day when I was trying to install wine, a bug (I think) destroyed the entire GUI of the OS. I entered sudo apt-get install wine then it asked me to write "DO AS I SAY". After doing so the screen went black and it started the OS in the terminal asking for my username and password. While writing DO AS I SAY I did not read things above it as I thought it was for safety purposes. This issue however is not limited to wine only, it is a widespread issue that happens rarely. Linus [from](https://www.youtube.com/watch?v=0506yDSgU7M) (at 10:45 in the video) Linus media group (Linus Tech Tips) also faced the same problem while installing steam. It seems that the issue is only seen on Pop OS. I had to run sudo apt-get install gnome-ubuntu after the described incident to get the GUI running. Now I have a buggy mixture of Pop OS and Ubuntu running. It thinks it is Ubuntu but it has all the exclusive features of Cosmic desktop. By the way props to the pop team, Pop still remains one of the best Linux distros I have seen to this very day.

**Steps to reproduce (if you know):**
It is quite hard to reproduce it sometimes comes out of nowhere while doing normal day-to-day stuff.

**Expected behaviour:**
The expected behaviour was to install the given package normally without uninstalling the entire GUI.

**Other Notes:**
Nil

**Comment by isantop** [comment]
Fixed in pop-os/apt#1

**Comment by leviport** [comment]
In case this is a genuine report, you want to install `pop-desktop`, not `gnome-ubuntu`.
