### ISSUE TITLE
Mouse cursor suddenly gains momentum when using touchpad

### ISSUE THREAD

**Issue by unilock** [pop-os/pop#1999]
**Distribution (`cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
```
 
**Issue/Bug Description:**
Occasionally, when using my Dell Latitude 7400 laptop, the mouse cursor will start moving with momentum; that is, I'll stop moving my finger when swiping across the touchpad, and the cursor will continue moving for a few fractions of a second, gradually slowing to a stop. Scrolling via touchpad is affected in the same way.

**Steps to reproduce:**
No known cause; it seems to happen at random.

**Expected behavior:**
When I stop moving my finger(s) on the touchpad, the cursor / scrolling should stop (almost?) immediately.

**Other Notes:**
A reboot fixes the issue, at least temporarily.
I have not yet tested whether the momentum carries over to a physical mouse.

`sudo dmidecode -t 1,2`:
```
Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Dell Inc.
	Product Name: Latitude 7400
	Version: Not Specified
	Serial Number: <REDACTED>
	UUID: <REDACTED>
	Wake-up Type: Power Switch
	SKU Number: 08E1
	Family: Latitude

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: Dell Inc.
	Product Name: 07WDVW
	Version: A01
	Serial Number: <REDACTED>
	Asset Tag: Not Specified
	Features:
		Board is a hosting board
		Board is replaceable
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Motherboard
	Contained Object Handles: 0
```
`sudo i2cdetect -l`:
```
i2c-3	i2c       	i915 gmbus dpc                  	I2C adapter
i2c-10	i2c       	AUX B/DDI B/PHY B               	I2C adapter
i2c-1	i2c       	Synopsys DesignWare I2C adapter 	I2C adapter
i2c-8	i2c       	Synopsys DesignWare I2C adapter 	I2C adapter
i2c-6	i2c       	Synopsys DesignWare I2C adapter 	I2C adapter
i2c-4	i2c       	i915 gmbus misc                 	I2C adapter
i2c-11	i2c       	AUX C/DDI C/PHY C               	I2C adapter
i2c-2	i2c       	i915 gmbus dpb                  	I2C adapter
i2c-0	smbus     	SMBus I801 adapter at efa0      	SMBus adapter
i2c-9	i2c       	AUX A/DDI A/PHY A               	I2C adapter
i2c-7	i2c       	Synopsys DesignWare I2C adapter 	I2C adapter
i2c-5	i2c       	i915 gmbus dpd                  	I2C adapter
```

`sudo dmesg | grep -i mouse`:
```
[    0.741907] mousedev: PS/2 mouse device common for all mice
[    1.280041] input: DELL08E1:00 06CB:CD97 Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-6/i2c-DELL08E1:00/0018:06CB:CD97.0001/input/input6
[    1.280347] hid-generic 0018:06CB:CD97.0001: input,hidraw0: I2C HID v1.00 Mouse [DELL08E1:00 06CB:CD97] on i2c-DELL08E1:00
[    1.775746] input: PS/2 Generic Mouse as /devices/platform/i8042/serio1/input/input5
[    9.856701] input: DELL08E1:00 06CB:CD97 Mouse as /devices/pci0000:00/0000:00:15.1/i2c_designware.1/i2c-6/i2c-DELL08E1:00/0018:06CB:CD97.0001/input/input14
[    9.858612] hid-multitouch 0018:06CB:CD97.0001: input,hidraw0: I2C HID v1.00 Mouse [DELL08E1:00 06CB:CD97] on i2c-DELL08E1:00
```

Let me know if you need any more information.

**Comment by xerohackcom** [comment]
**Fixing Mouse Acceleration With Settings**

You can try this solution if not tried already:

- Open the Activities overview and start typing Mouse & Touchpad.
- Click on Mouse & Touchpad to open the panel.
- Adjust the Mouse Speed or Touchpad Speed slider until the pointer motion is comfortable for you. Sometimes the most comfortable settings for one type of device are not the best for the other.

**Fixing xinput**

If you still have issues, especially if you use other hardware mouse, then you can try settings via xinput. [xinput mouse speed decrease](https://askubuntu.com/questions/688270/mouse-speed-too-fast)

You can apply the above xinput settings to your start using: startup application > add > enter xinput command

I hope this helps

**Comment by unilock** [comment]
@xerohackcom 
The issue isn't with the mouse/touchpad speed; I can adjust that just fine.
The problem is that, sometimes, the cursor will slide a bit past where I move it.

Think of the cursor as a shopping cart, and the screen as a parking lot. When I push the shopping cart, it doesn't stop immediately when I let go; it keeps moving in the direction I pushed it until the friction of the asphalt stops the wheels from turning.
The cursor does the same; when I stop moving my finger on the touchpad, the cursor continues moving in the direction I moved my finger, until some invisible force of friction slows it to a halt. Ideally, the cursor should stop almost immediately when I stop moving my finger, rather than sliding about.

I'd add a video of the issue, but it happens so sporadically that it's rather hard to capture. Sometimes it stops after a few minutes, too. It's a conundrum.

**Comment by xerohackcom** [comment]
@unilock 

Thanks for the input. _I think I understand what your issue might be!_ 

Anyway, without wasting your time, here's the solutions that worked for everyone having this same issue:

**Solutions** : **_Perform the first two solutions_** from here: https://askubuntu.com/questions/894679/ubuntu-touchpad-issues-mouse-pointer-jumps-around

Your can read more about this bug on Ubuntu: You can read more about this here: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-input-synaptics/+bug/1574667 but it's kind of long and boring bug report. Since Pop!_OS is based on Ubuntu, I can see guess bug being the same one.

**Comment by unilock** [comment]
@xerohackcom Unfortunately, I don't believe that solution / bug report are relevant to my issue. My mouse cursor doesn't jump to the bottom corner of the screen; rather, it moves in the direction I want it to, but it then slides further than intended, like an ice cube being pushed around a plate.

Anyway, I've recently replaced my Latitude with a Thinkpad, so I can no longer test nor potentially record this issue. Here's hoping I don't have the same problem on my new laptop.

If that does turn out to be the case, or someone else runs into this same problem, I'll reopen the issue.

Thanks for the help!
