### ISSUE TITLE
Logout when screen switches off

### ISSUE THREAD

**Issue by sudhirj** [pop-os/pop#2]
When my screen goes off based on the power savings settings (tested this at both 1 minute and 5 minutes), I'm also logged out for no apparent reason. This happens both with the Privacy / Screen Lock on and off. 

Locking my screen using the lock icon works fine - this only happens when the screen goes off because of inactivity. 

Have confirmed that it is a logout and not a restart as well - my disk is encrypted and it doesn't ask for the decryption password when this happens. 

I'm running an Intel Skull Canyon NUC.

**Comment by sudhirj** [comment]
One more piece of info is that the log out (with all windows closing) happens even when I suspend, which might explain what's going on. Does the screen switch off also suspend?

**Comment by sudhirj** [comment]
Can't do Ubuntu, but is there a log file I can post? I can post the last 1000 lines off whichever log you think will help debug immediately after this happens.

**Comment by WatchMkr** [comment]
This appears specific to the Skull Canyon NUC. We're unable to replicate and there seems to be some other odd graphics behavior. We won't be able to fix this bug.
