### ISSUE TITLE
Upper right power control drop-down menu does not respect dark theme colors

### ISSUE THREAD

**Issue by dwangoac** [pop-os/pop#200]
**Distribution:**
`Pop!_OS 18.04 LTS (Testing)`
 
**Steps:**
Using the default dark theme, click on the power control menu in the far upper-right of the screen.

**Result:**
The window that drops down will be black text on a white background.

**Expected:**
When a dark theme is used the drop-down should respect the theme colors to use a light font on a dark background.

**Additional information:**
I was unable to find any settings related to themes, appearance, or anything indicating a dark theme other than the high contrast toggle under accessibility. It is not clear to me exactly how I ended up with a dark theme in the first place, although one of the first things I did upon commpleting the installation was replacing the rather bright default background with the color black. I also installed over an existing home directory that may have specified theming information from my Linux Mint installation. With all those caveats out of the way, the gist of this issue is that theming should be consistent throughout the UI when using appropriately supported themes.

**Comment by jackpot51** [comment]
Could you provide a screenshot?

**Comment by brs17** [comment]
I imagine it is similar to: https://github.com/pop-os/gtk-theme/issues/152#issuecomment-385160719
@dwangoac can you confirm?

**Comment by brs17** [comment]
The shell theme is not set in 19.10 when selecting the dark theme in gnome-control-center.
