### ISSUE TITLE
Pop!_OS 21.04 Hang on Idle

### ISSUE THREAD

**Issue by besselfunct** [pop-os/pop#2007]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
* Suspend on Idle is Disabled
* Lock Screen is Disabled
* After ~ 12h Idle, the machine will lock up, and provide no power to USB devices (as evidenced by status LEDs not lighting on mice, keyboards, or my USB DAC).
* The cursor is visible on a black screen.
* Hot-plugging USB devices does not resolve the issue
* The state can be resolved by pressing the power button to send the device into suspend, and then waking the device. Authentication at the login screen fails however, and the current session can only be recovered by pressing the "switch users" button in the bottom right.

**Steps to reproduce (if you know):**
* Unsure what could be causing this

**Expected behavior:**
* System should continue polling USB devices indefinitely when suspend is disabled.

**Other Notes:**
* I'm not looking for a specific resolution here, I'm just wondering if there's a log file I can provide that might provide more info about what's going on here. I'm not exactly sure where to start with narrowing down this problem.

**Comment by crawfxrd** [comment]
What hardware is this on?

> I'm not exactly sure where to start with narrowing down this problem.

What does journalctl say? Are there any errors from the time it happened?

**Comment by besselfunct** [comment]
Hardware is:
```
Motherboard: Gigabyte Z170X-UD3
CPU: Intel i5-6600K
GPU: NVIDIA GTX 1080
RAM 16Gb
SSD: Crucial P5 500Gb
```
The problem is intermittent, and the `journalctl` log is...verbose, but the `journalctl` command is exactly what I was looking for. I'll look through the logs now, and see if I find anything, and make sure to check them next time this happens.

**Comment by crawfxrd** [comment]
If you reproduce it you can limit the log to just that boot: `journalctl -b`.

**Comment by besselfunct** [comment]
I had this issue 3 times in one week, and haven't been able to reproduce. I'll reopen if I can get a `journalctl` log.
