### ISSUE TITLE
OS freezing when downloading games in Lutris or Steam

### ISSUE THREAD

**Issue by itz4blitz** [pop-os/pop#2008]
**Distribution:**

NAME="Pop!_OS"
VERSION="21.04"

 
**Related Application and/or Package Version:**

Lutris / Steam

**Issue/Bug Description:**
OS / apps such as Brave or Firefox become unresponsive when downloading games. I have to wait a few seconds for them to respond again.

**Steps to reproduce:** Download and install any game

**Expected behavior:** Still being able to browse the interwebz

**Other Notes:** I have a desktop, Ryzen 9 5900x, 64GB DDR4 RAM, MSI MPG X570 Gaming Plus motherboard, a 2TB SSD on which Pop is installed, Msi Gaming X GTX 1080Ti - so I don't think my system is the issue.

I'm monitoring the resources, I'm using about 25% of my ram, 0.5% of my CPU, and temps look good. System load isn't usually over 5. Right now it's 2.86 and I'm still getting intermittent lockups.

**Comment by bflanagin** [comment]
Can you monitor your hard-drive activity during the downloads using iotop or similar program?
