### ISSUE TITLE
neither test iso boots on xps 15 9560 with ssd

### ISSUE THREAD

**Issue by jeffreyscottgraham** [pop-os/pop#201]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 both 1st and 2nd test iso for nvidia. Also failed for intel/amd.
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
Stable pop 17 nvidia worked fine until daily update from friday the 13th. Would not boot on powerup.

**Issue/Bug Description**
installer wont boot

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by jeffreyscottgraham** [comment]
The update blew away the UEFI partition. And apparently the 1804 ISOs assume it is there and wont recreate it if missing.

**Comment by brs17** [comment]
@jeffreyscottgraham Numerous issues/bugs were fixed with the test isos, have you tried again since release?

**Comment by jacobgkau** [comment]
We never received follow-up information about this issue, and there are several newer issues that refer to having Pop!_OS installed on the XPS 15 9560, so either newer isos should work, or more information about the specific configuration that isn't working would be needed.
