### ISSUE TITLE
Pipewire is required by pop-desktop

### ISSUE THREAD

**Issue by youdontneedtoknow22** [pop-os/pop#2012]
so I installed Pipewire on my Pop_OS and couldn't find a way to make Pulseaudio the default anymore, so I just wanted to delete Pipewire in order for Pulseaudio to be the default.
My command:

`sudo apt purge gstreamer1.0-pipewire pipewire-media-session libspa-0.2-bluetooth libspa-0.2-jack pipewire pipewire-audio-client-libraries`

What I got:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  fd-find gir1.2-accountsservice-1.0 gir1.2-gck-1 gir1.2-gcr-3 gir1.2-gdm-1.0
  gir1.2-gnomebluetooth-1.0 gir1.2-graphene-1.0 gir1.2-mutter-7 gir1.2-nma-1.0
  gir1.2-rsvg-2.0 gir1.2-upowerglib-1.0 gnome-session-bin gnome-session-common
  gnome-shell-common gnome-shell-extension-system76-power
  gnome-startup-applications libfreeaptx0 libfreerdp2-2 libldacbt-abr2
  libldacbt-enc2 libmutter-7-0 libopenfec libpipewire-0.3-modules libroc
  libvncserver1 libwinpr2-2 mutter-common pop-gnome-shell-theme pop-gtk-theme
  pop-icon-theme pop-launcher pop-shell pop-shell-plugin-system76-power
  pop-shell-shortcuts pop-sound-theme pop-theme qalc switcheroo-control
  xwayland
Use 'sudo apt autoremove' to remove them.
The following packages will be REMOVED:
  chrome-gnome-shell* gdm3* gnome-remote-desktop* gnome-shell*
  gnome-shell-extension-appindicator* gnome-shell-extension-cosmic-dock*
  gnome-shell-extension-desktop-icons-ng* gnome-shell-extension-prefs*
  gstreamer1.0-pipewire* libspa-0.2-bluetooth* libspa-0.2-jack* pipewire*
  pipewire-audio-client-libraries* pipewire-bin* pipewire-media-session*
  pipewire-pulse* pop-cosmic* pop-default-settings* pop-desktop* pop-session*
WARNING: The following essential packages will be removed.
This should NOT be done unless you know exactly what you are doing!
  pop-desktop pop-session (due to pop-desktop)
  chrome-gnome-shell (due to pop-desktop) gdm3 (due to pop-desktop)
  gnome-shell (due to pop-desktop) pop-default-settings (due to pop-desktop)
0 upgraded, 0 newly installed, 20 to remove and 0 not upgraded.
After this operation, 14.9 MB disk space will be freed.
This operation is not permitted because it will break the system.
Abort.
```

**Comment by jacobgkau** [comment]
You cannot simply replace "install" with "purge" to undo a command you copied from a tutorial. "install" will update or ignore packages that you already have installed, so attempting to "purge" the same list can remove things that were already present before you started (and should not be removed).

> If necessary, I can also provide a copy of the history.log when I'm on my Pop_OS machine

Please provide the log if you still need assistance determining what you added to your system. You would need to remove the PPA from your system as well: https://support.system76.com/articles/manage-repos-pop 

> you can change it if the responsible developer decides to fix/change this :)

I don't see anything that needs to be "fixed" right now. I've moved this to the general Pop repository for the time being.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by youdontneedtoknow22** [comment]
Oh then it's basically a mistake from a newbie. Thanks and feel free to close this issue if necessary, I'd be asking for help from the community.

**Comment by PixsaOJ** [comment]
Same problem, I have replaced Pulseaudio with PipeWire while ago. But now I had issues with version mismatch from PipeWire apt repository. Naturally I tried to remove PipeWire but could not because of this. Now, I can't use their repo to reinstall it.  Can't uninstall it, either.  

This issue happened without my action, therefore, I don't think everyone should fix it by themselves.

**Comment by 0xD34DC0DE** [comment]
Same thing for me, unable to remove pipewire

**Comment by jacobgkau** [comment]
Pop!_OS 22.04 LTS will be transitioning completely away form pulseaudio to pipewire (already done for the pre-release in https://github.com/pop-os/desktop/pull/80.)

**Comment by youdontneedtoknow22** [comment]
@jacobgkau should I close this issue then? (or maybe you can close it)
