### ISSUE TITLE
gnome-shell segfault

### ISSUE THREAD

**Issue by goodmami** [pop-os/pop#202]
Gnome-shell occasionally dies and restarts. I haven't found out any consistent reason, but it happens about twice a day.

 **Distribution - (run ```cat /etc/os-release```)**
 
```
Pop!_OS 17.10 (Artful Aardvark)
```
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

```
gnome-shell:
  Installed: 3.26.2-0ubuntu0.1
  Candidate: 3.26.2-0ubuntu0.1
  Version table:
 *** 3.26.2-0ubuntu0.1 500
        500 http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.26.1-0ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
```

**Issue/Bug Description**

Under normal usage (web browsing or text editing) gnome-shell dies and restarts. The relevant lines from `journalctl` are below:

```
Apr 15 17:54:15 tpy kernel: gnome-shell[1734]: segfault at 1000002a5 ip 00007f4253eb0cdf sp 00007ffd5d619758 error 4 in libgobject-2.0.so.0.5400.1[7f4253e7b000+52000]
Apr 15 17:54:15 tpy polkitd(authority=local)[1053]: Unregistered Authentication Agent for unix-session:2 (system bus name :1.76, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Apr 15 17:54:15 tpy gnome-session[1623]: gnome-session-binary[1623]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Apr 15 17:54:15 tpy gnome-session-binary[1623]: WARNING: Application 'org.gnome.Shell.desktop' killed by signal 11
Apr 15 17:54:15 tpy gsd-power[1841]: Failed to acquire idle monitor proxy: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

**Steps to reproduce (if you know)**

Not sure how to reliably reproduce.

**Expected behavior**

No segfaults.

**Other Notes**

None for now.

**Comment by goodmami** [comment]
Update: one trigger for the segfault is touching the screen. After logging in, the first touch of the screen causes gnome-shell to crash. It restarts and I generally don't lose any work, although it strangely defocuses whatever window was previously focused (i.e., sends it to the "back" in z-order). After this initial crash, subsequent touches on the screen do not cause gnome-shell to crash, and the on-screen keyboard pops up.

These seem related:
 * https://github.com/NixOS/nixpkgs/issues/25968
 * https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1567427

Note that I do have Caribou installed. And similar to the commenters in the first link, I am also on a thinkpad (Thinkpad Yoga 14), although that might be a red herring.

Also, i'm pretty sure gnome-shell has crashed without touching the screen, but there could be a second issue causing those crashes.

**Comment by mmstick** [comment]
Does this still happen in 18.04?

**Comment by mmstick** [comment]
> Shall we tentatively close this bug and I can reopen it if the issues come back?

Sounds like a good idea, but you may want to report issues with GNOME Shell to GNOME's GitLab repo for gnome-shell[[1]](https://gitlab.gnome.org/GNOME/gnome-shell/issues). That will at least ensure that the developers are aware of the issue.

[1] https://gitlab.gnome.org/GNOME/gnome-shell/issues

**Comment by goodmami** [comment]
Sounds good. I initially reported it here because I had been running the same (or maybe newer) version of gnome-shell in Antergos without any issue, so it seemed to be a problem affecting Pop!_OS.
