### ISSUE TITLE
Changing brightness only affects built-in monitor (on laptop)

### ISSUE THREAD

**Issue by neverett8fr** [pop-os/pop#2022]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 21.04
64 bit
GNOME - 3.38.5
Windowing System - X11

NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Changing brightness via toolbar only affects the built-in display (laptop) - regardless of primary display.  

**Steps to reproduce (if you know):**
![Screenshot from 2021-11-29 00-26-02](https://user-images.githubusercontent.com/43852724/143792566-c3259c85-b7c9-4bf2-9df9-ee1044e5654b.png)

**Expected behavior:**
Two possible solutions.
1. Adjusting settings should affect all attached displays simultaneously.  
OR  
2. Should affect only the Primary Display (not just the built-in) then have an (p)option elsewhere to change the other displays

**Other Notes:**
The nightlight affects all screens! So that's not an issue

**Comment by jackpot51** [comment]
External monitors are not meant to be controlled by brightness controls

**Comment by neverett8fr** [comment]
I'm not sure I'd necessarily agree with that @jackpot51  
But happy to accept  nevertheless

**Comment by jackpot51** [comment]
It is a technical limitation. There isn't usually an interface the OS can use.

**Comment by jackpot51** [comment]
It is important to note that this adjusts brightness in software, and therefore reduces color resolution when doing so, which is different from the backlight adjustments that most laptop displays have.

**Comment by neverett8fr** [comment]
Ahh fair enough - I guess I can make the changes to my own system instead.  
Thanks for being so quick in getting back to me!!

**Comment by jackpot51** [comment]
Sure thing, I hope that works well enough for you. It may be possible to sync the backlight brightness on your laptop panel from /sys/class/backlight with the xrandr brightness value on your external monitors.

**Comment by jackpot51** [comment]
You could look at this project that does essentially that: https://github.com/pop-os/system76-oled

We decided losing color resolution on OLED panels was acceptable because they usually have 10-bit color instead of 8-bit.

**Comment by neverett8fr** [comment]
Nice - I'll have a look, thanks!
