### ISSUE TITLE
Do not disturb toggle is off center

### ISSUE THREAD

**Issue by kylecorry31** [pop-os/pop#203]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="18.04 LTS (Testing)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
gnome-shell-extension-do-not-disturb:
  Installed: 0.1.0~1523470769~18.04~9410d4a
  Candidate: 0.1.0~1523470769~18.04~9410d4a
  Version table:
 *** 0.1.0~1523470769~18.04~9410d4a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**
It appears that the do not disturb text is off center from the toggle. This seems to have been created when the appearance of the toggle changed in Pop!_OS 18.04, as it is aligned in 17.10.

**Steps to reproduce (if you know)**
Click on the date menu.

**Expected behavior**
The text is centred with the switch.

**Other Notes**
![screenshot from 2018-04-16 12-18-44](https://user-images.githubusercontent.com/5938560/38822341-270db240-4171-11e8-82cf-7ad5da8c1954.png)

**Comment by cassidyjames** [comment]
This was fixed in https://github.com/pop-os/gnome-shell-theme/pull/18
