### ISSUE TITLE
Freezes on `5.15.5-76051505-generic` kernel

### ISSUE THREAD

**Issue by dxps** [pop-os/pop#2036]
Dear Pop!_OS community,

I just want to report a couple of issues that appeared on my Pop!_OS systems after the upgrade and usage of the new `5.15.5-76051505-generic` kernel. If I can do something to help, please tell me. I'm not writing these just to complaining.

<br/>

### Using Pop!_OS 21.04

First of all, I'm running Pop!_OS 21.04 on both systems, and everything went all great until recently.

Meanwhile, to overcome these, I added a `timeout 6` line to `/boot/efi/loader/loader.conf` file, so that I could still use the previous (and very stable) `5.13.0-7620-generic` kernel.

Btw, I love this distro and I'm not planning to switch to a different one any time soon.

<br/>

### The Issues

Here are the issues that are happening when using the new kernel.

 1. UI (X11) freezes, followed by automatic OS/system reboots on my daily driver, or just UI (X11) freezes.
     These happened on a Dell XPS 8930 workstation with a GeForce 1080 card.
     Quite impactful being my daily driver for almost 1 year.

2. UI (X11) freezes (and had to force turn off system by keep pressing the power button for 3+ seconds) on a Dell Latitude 5410 laptop.

3. It seems that I cannot kill a process as root.
    I never thought I could see this one happening in more than a decade of using Unix/Linux systems.

<br/>

### Reproducible Steps

I'm having the "recipe for disaster" for the 1st and 3rd aforementioned cases, so I can replicate them at any time.

For the 1st issue, the steps are:
- I open Font Manager.
- I'm trying to "add" (install) the latest (v6) Fira Code.
   - I'm selecting the files, and click Open.
   - The UI freezes, and in around 3 seconds the whole system reboots.

For the 3rd issue, the steps are:
- I open an epub using Foliate
- I close that app
- However, it seems that the app's process is still running.
   - The associated process `/usr/libexec/xdg-document-portal` uses 100% of a CPU core,
     the cpu temp increases, and the fan is getting louder.
   - But a `kill -9 {pid}` does nothing!
      - And trying that as `root` user (not just using `sudo kill -9 {pid}`).
      - Tried multiple times, no change at all.
      - Not even logout/shutdown/reboot works, but a hard keep pressing the power button eventually ends this.

<br/>

Thanks and keep up the good work!

**Comment by decaturguy** [comment]
I'm using an older laptop Lenovo T510 and i have basically almost same problem.

During boot the kernel puts out some error and after login in to the desktop environment, it is simply unusable and everything freezes. After i do hard reboot and select an older kernel (5.13) the problem goes away.

**Comment by decaturguy** [comment]
> 

SOLVED: It's fixed by adding **intel_iommu=igfx_off** to grub kernel parameters.

**Comment by mmstick** [comment]
`kernelstub -a intel_iommu=igfx_off` for EFI installs.

**Comment by dxps** [comment]
The new kernel update (to `5.15.8-76051508-generic`) seems to solve all the problems.
At least I didn't encounter any issue, and I feel like I'm loving again the stability of the Pop!_OS distro.
