### ISSUE TITLE
WIFI driver 5.5.2.1 will not install

### ISSUE THREAD

**Issue by Grim622** [pop-os/pop#2037]
21.10

**Distribution (run `cat /etc/os-release`):** 21.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**Driver will not install

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by Grim622** [comment]
wifi card is Realtek 8821C PCIe the driver is rtl8821ce-dkms

**Comment by jacobgkau** [comment]
Duplicate of https://github.com/pop-os/pop/issues/1956.
