### ISSUE TITLE
cant procede to install after selecting partations.

### ISSUE THREAD

**Issue by jwbloodorth** [pop-os/pop#205]
**Distribution - (run ```cat /etc/os-release```)**
18.04 testing

  **Related Application and/or Package Version - apt policy $PACKAGE NAME**

Installer

**Issue/Bug Description**

after selecting custom partitions there does not apper to be any change in  the buttons that will allow the installation to continue.
 
**Steps to reproduce (if you know)**
From the install POP!_OS Screen, select a drive
Select "customize Partitions"

![screenshot from 2018-04-17 03-10-10](https://user-images.githubusercontent.com/31707130/38880536-d541742e-421a-11e8-875c-d29d4d851a01.png)

**Expected behavior**
Once partations are selected, install should be allowed to continue.

**Other Notes**
system is a lenovo x131e amd version and is to the best of my knowledge only running BIOS

**Comment by jackpot51** [comment]
Thanks for the information. I believe there is a bug in the validation. Also, we will be adding the rules somewhere so you can see what is missing.

**Comment by bublik77** [comment]
Hi, the same problem, cannot continue installation after custom partition selected.

**Comment by jackpot51** [comment]
This will be fixed for BIOS systems with the next ISO

**Comment by jgawlik83** [comment]
has this been fixed? because after selecting custom partitions and NOT selecting format to my /data partition, I was in fact able to install, but the partition has been wiped. Not ideal, but thankfully it was mostly GIT partition, so have backups.

I have used 18.04_amd64_intel_18.iso

**Comment by thomsch98** [comment]
Installation worked with pop-os_18.04_amd64_intel_18.iso. I did NOT select any partition to be mounted during install (neither with or without formatting) so no new insight to unintentionally formatting ...

It was necessary to select the EFI partition, though.  (BTW: I added a swap-file after installation)

**Comment by jackpot51** [comment]
@jgawlik83 this issue refers to the inability to continue installation on BIOS systems and has been fixed. Please open a new issue.
