### ISSUE TITLE
Failed to update “Operating System Updates”. This may have been caused by external or manually compiled software.

### ISSUE THREAD

**Issue by Marivishnu** [pop-os/pop#2051]
![image](https://user-images.githubusercontent.com/67962094/145710886-65f2264c-85aa-44ea-94f0-a809e5fccb5d.png)

Hi, I am using Pop!_OS 21.04. Today I tried to run `sudo apt update` and `sudo apt upgrade` and I got this error.

![image](https://user-images.githubusercontent.com/67962094/145710952-6baf21ae-d3d1-4541-89e0-8aa3ccb06755.png)

I also tried to update via the Pop!_Shop and got the same error message.
![image](https://user-images.githubusercontent.com/67962094/145710969-a2c16f27-a639-410c-b92a-909b67f60b1e.png)

**Comment by jacobgkau** [comment]
The currently-published version of `pop-shell` in the 21.04 PPA is `1.1.0~1638899293~21.04~6a49503`, as can be seen here: https://launchpad.net/~system76/+archive/ubuntu/pop/+packages?field.name_filter=pop-shell&field.status_filter=published&field.series_filter=hirsute 

Can you please provide the output of `sudo apt update` to confirm that your package lists are being updated successfully?

**Comment by Marivishnu** [comment]
![image](https://user-images.githubusercontent.com/67962094/146020928-ae6a07fa-9ce2-4388-978c-c225826a2ae4.png)

![image](https://user-images.githubusercontent.com/67962094/146020961-237901d3-2f71-4804-a492-42dd229ada15.png)

**Comment by jacobgkau** [comment]
Try removing your apt cache:

```
sudo rm -r /var/cache/apt/*
sudo rm -r /var/lib/apt/lists/*
```

Then run `sudo apt update` and `sudo apt upgrade` again.

**Comment by Marivishnu** [comment]
Working perfectly now! Thanks a lot!!

**Comment by nikhil-user123** [comment]
![Screenshot from 2023-04-13 00-21-07](https://user-images.githubusercontent.com/60343350/231556404-eb7cd436-6594-49d0-9fce-7a5c5eca64c9.png)
how can i deal with this error

**Comment by nikhil-user123** [comment]
#here is an another screenshot
![Screenshot from 2023-04-13 00-25-42](https://user-images.githubusercontent.com/60343350/231557518-014cc413-385c-4205-a5bc-f3d66dca5849.png)
