### ISSUE TITLE
After upgrade to 21.10 gnome extenuations didn't work

### ISSUE THREAD

**Issue by bahtioraliev** [pop-os/pop#2063]
**Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy chrome-gnome-shell`):**
```
chrome-gnome-shell:
  Installed: 10.1-5
  Candidate: 10.1-5
  Version table:
 *** 10.1-5 500
        500 http://us.archive.ubuntu.com/ubuntu impish/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu impish/universe i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
"Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector."

**Steps to reproduce (if you know):**
Upgrade popos from 20.04 to 21.10

**Expected behavior:**
The gnome extensions web page should work correctly and let the user to install extensions

**Other Notes:**
It happens for firefox based browser and chromium as well.
Chromium installation - flatpack (96.0.5664.110)
LibreWolf installation - flatpack (94.0.2-2)

**Comment by leviport** [comment]
Seems to be working fine for me. Perhaps a `sudo apt install --reinstall chrome-gnome-shell` and a reboot will clear it up?

**Comment by bahtioraliev** [comment]
The behavior is the same after reinstall and reboot.

**Comment by bahtioraliev** [comment]
![image](https://user-images.githubusercontent.com/76793434/146668690-961e505a-d30d-4695-8f7c-e200e62be9d2.png)

**Comment by jacobgkau** [comment]
Does it work if you use a web browser that is installed natively and not via Flatpak?

**Comment by neurosys-zero** [comment]
> Does it work if you use a web browser that is installed natively and not via Flatpak?

Works fine using the default FF

**Comment by bahtioraliev** [comment]
I think this issue has been fixed. 
Thanks for the help.
