### ISSUE TITLE
Can't start bluetooth after updating from 21.04 to 21.10

### ISSUE THREAD

**Issue by AriaanBruinsma** [pop-os/pop#2079]
**Distribution**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version**
Not sure

**Issue/Bug Description:**
After updating from 21.04 to 21.10, bluetooth was off by default and I can't toggle it back on again in the settings. I've got another machine and noticed it was running pipewire, so I am hesitant to use all the steps in the Bluetooth trouble shooting bit (https://support.system76.com/articles/bluetooth/) Since I'm not sure if pipewire and alsa will work together.

**Steps to reproduce**
Update PopOS to 21.04

**Expected behavior:**
That it works. Sorry, don't know what else to say here.

**Other Notes:**
HW: Dell XPS 15" 9550 - Intel i7-6700HQ

**Comment by AriaanBruinsma** [comment]
Additional note: btmon reports:
```
Bluetooth monitor ver 5.60
= Note: Linux version 5.15.5-76051505-generic (x86_64)                 0.891425
= Note: Bluetooth subsystem version 2.22                               0.891430
= New Index: 00:00:00:00:00:00 (Primary,USB,hci0)               [hci0] 0.891432
@ MGMT Open: bluetoothd (privileged) version 1.21             {0x0001} 0.891434
```

But if I play with the bt settings interface it doesn't change (turn on/off, can't pair). Also the UI spams the syslogs with faults, I'll have to filter that for more context.

**Comment by AriaanBruinsma** [comment]
Here's my syslog output when I toggle the BT switches in PopOS.

After turning BT **off** through the toggle in the top-bar:
```
Dec 18 12:28:00 pop-os systemd[1]: Starting Check PMIE instances are running...
Dec 18 12:28:00 pop-os systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 18 12:28:00 pop-os systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 18 12:28:00 pop-os systemd[1]: pmie_check.service: Deactivated successfully.
Dec 18 12:28:00 pop-os systemd[1]: Finished Check PMIE instances are running.
Dec 18 12:28:05 pop-os systemd[1]: systemd-rfkill.service: Deactivated successfully.
```

After turning it **on** through the toggle in the top-bar
```
Dec 18 12:28:12 pop-os systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 18 12:28:12 pop-os systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 18 12:28:17 pop-os systemd[1]: systemd-rfkill.service: Deactivated successfully.
```

And this is what i see when i toggle in the BT interface... it actually does less:
```
Dec 18 12:28:00 pop-os systemd[1]: Starting Check PMIE instances are running...
Dec 18 12:28:00 pop-os systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 18 12:28:00 pop-os systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 18 12:28:00 pop-os systemd[1]: pmie_check.service: Deactivated successfully.
Dec 18 12:28:00 pop-os systemd[1]: Finished Check PMIE instances are running.
Dec 18 12:28:05 pop-os systemd[1]: systemd-rfkill.service: Deactivated successfully.
Dec 18 12:28:12 pop-os systemd[1]: Starting Load/Save RF Kill Switch Status...
Dec 18 12:28:12 pop-os systemd[1]: Started Load/Save RF Kill Switch Status.
Dec 18 12:28:17 pop-os systemd[1]: systemd-rfkill.service: Deactivated successfully.
```

**Comment by AriaanBruinsma** [comment]
Todays update fixed the issue!

**Comment by allout58** [comment]
Just updated to 21.10 this morning and running into this exact issue, and have no updates available.

**Comment by AriaanBruinsma** [comment]
Okay... It's not solved... Here's an update... I'll repost the issue if this is ignored.

Bluetooth works when I have selected my power profile to "Hybrid Graphics". However, as soon as I switch to dedicated "NVIDIA Graphics", my bluetooth is dead. It reports wrong, it doesn't toggle on or off and I don't get any settings options.

![image](https://user-images.githubusercontent.com/539121/147554556-fb4a9298-44bd-45f7-b4c3-b733f3f4feca.png)

**Comment by AriaanBruinsma** [comment]
> Just updated to 21.10 this morning and running into this exact issue, and have no updates available.

Yeah, I thought it was the updates. But I forgot I switched power profiles, also I didn't think it was relevant at the time.

**Comment by AriaanBruinsma** [comment]
@allout58 

> Just updated to 21.10 this morning and running into this exact issue, and have no updates available.

Does it enable when you switch to hybrid? And what kind of Hardware are you using?

**Comment by jcastillopro** [comment]
Hello @AriaanBruinsma @allout58, after updating a month ago and having problems with my Bluetooth. And I go back to 21.04 without solution.

Yesterday I went back to Pop!_OS 21.10 and thought there was a patch, but my Bluetooth issue came back.

Use this thread  https://askubuntu.com/questions/1231074/ubuntu-20-04-bluetooth-not-working

![image](https://user-images.githubusercontent.com/32829258/150433513-43f78df1-391e-409f-9364-f9aca16e4259.png)

**My problem continued, trying to format, I pressed F11, and it showed me this.**

![image](https://user-images.githubusercontent.com/32829258/150433665-83ef9c19-e61c-4138-b70c-101edfbd93ba.png)
Use the second option, and this solved my problem. I don't know if the previous step has any influence, but I'll mention it anyway.

**Comment by AriaanBruinsma** [comment]
Since it changes behavior, it seems to me that it is a driver issue. However my BT mysteriously started working again after another random update. Haven't switched back to Hybrid mode yet (to scared of losing functionality). I'll try it again, when I don´t have a meeting, regarding making life changing choices. XD
