### ISSUE TITLE
pop os upgrade failed 21.04 -> 21.10

### ISSUE THREAD

**Issue by iota-008** [pop-os/pop#2084]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

ppp:
  Installed: (none)
  Candidate: 2.4.7-2+4.1ubuntu8
  Version table:
     2.4.7-2+4.1ubuntu8 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages

network-manager:
  Installed: 1.30.0-1ubuntu3
  Candidate: 1.30.0-1ubuntu3
  Version table:
 *** 1.30.0-1ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu hirsute/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

pop os upgrade failed from 21.04 to 21.10

**Steps to reproduce (if you know):**

downloaded the upgrade from the pop shop but it shows the error : 

![Screenshot from 2021-12-18 18-16-24](https://user-images.githubusercontent.com/46680697/146641606-109d5149-c7f3-4cb4-8cb2-a23c4c8c8719.png)

**Expected behaviour:**

download and install the upgrade

**Other Notes:**

depedancy issues for network manager and PPP

![Screenshot from 2021-12-18 18-18-55](https://user-images.githubusercontent.com/46680697/146641705-ff185316-79f2-4ba8-9721-c9672d34c353.png)

![Screenshot from 2021-12-18 18-19-48](https://user-images.githubusercontent.com/46680697/146641723-80096a0e-5daf-40ff-bb3a-4e5906bd8e61.png)

**Comment by RelicCornhusk** [comment]
I'm getting similar messages after a failed upgrade. Bumping this issue.

**Comment by nanoharsha** [comment]
This issue is also being discussed here : 
https://github.com/pop-os/pop/issues/2059

**Comment by crubel** [comment]
I have an Orxp7 and was prompted to upgrade to 21.10 yesterday when booting into my pop-os V21.04.  System upgraded with no apparent errors and rebooted to the login screen.  I logged in and QT Creator 6 needed an update according to the system.  I clicked on update and it returned almost immediately.  I finally just removed and reinstalled it using the GUI tool.  Everything looked good until I rebooted, pop appears to boot up ok, but no login screen only a blank dark grey screen, no cursor visible either.  I attempted to ALT F1-F12 and did not get any consoles or anything, but I'm new to pop so I'm not sure if the ALT Fx sequence should even work on pop, been using OpenSuSE for a long time.

Anyhow, I was looking around and didn't find this same issue yet.  Any suggestions or comments would be welcomed before I attempt a fresh install after saving away anything I need to keep.  

Thanks in advance..

**Comment by jacobgkau** [comment]
@crubel If you have a System76 computer, please open a support ticket at https://support.system76.com/ so the support team can help you directly.

> downloaded the upgrade from the pop shop but it shows the error :

The release upgrade is downloaded via Settings, not the Pop!_Shop.

@iota-008 You opened this issue on December 18th. What date did you _first_ attempt to upgrade? I suspect this was caused by an issue that https://github.com/pop-os/upgrade/pull/232 should prevent going forward.

You will need to correct the dependency errors by manually specifying the versions of packages that will work for each other. For example:

```
sudo apt install ppp=2.4.7-2+4.1ubuntu8 libnm0=1.30.0-1ubuntu3
```

This command may not be complete, but you'll need to read the additional packages/versions that the error messages show and add them to the command until it works.

**Comment by iota-008** [comment]
@jacobgkau I did try this upgrade on 15th or 16th December and was searching for solution since then. Then did a clean install of pop os 21.10 from the USB flash drive. lol :)
