### ISSUE TITLE
Blank screen on boot when using Optimus (nvidia-prime) with 18.04 NVIDIA ISO.

### ISSUE THREAD

**Issue by ryanpcmcquen** [pop-os/pop#209]
**Distribution - (run ```cat /etc/os-release```)**
 Pop!_OS 18.04 testing.

**Issue/Bug Description**
Unable to boot into the 18.04 NVIDIA ISO. Given a blank screen. I have double checked that secure boot is disabled.

**Steps to reproduce (if you know)**
- Download the Pop!_OS 18.04 NVIDIA ISO.
- Boot into ISO.

**Expected behavior**
I could boot and install this awesome OS!

**Comment by ryanpcmcquen** [comment]
I used the NVIDIA ISO. The Intel ISO works, until I install `nvidia-prime`, then the same issue persists (blank screen on boot).

**Comment by WatchMkr** [comment]
What model of hardware do you have?

**Comment by ryanpcmcquen** [comment]
A Clevo W230SS.

**Comment by kerroncheddie** [comment]
I've just tested 18.04 nvidia 13, blank screen on boot and unable to set boot parameters because of the --nopromt.
Its possible to test this better if we are able to set some kernel parameters while booting.

**Comment by ryanpcmcquen** [comment]
Wondering if `nvidia-prime` `0.8.8` fixes it?

```
nvidia-prime (0.8.8) bionic; urgency=medium

  * 90-nvidia.conf,
    debian/dirs.in,
    debian/install.in,
    debian/rules,
    oem/00-prime-offload,
    prime-offload,
    prime-switch:
    - Restore the Lightdm configuration snippets, as it removing
      them caused a black screen on boot on all the Ubuntu flavours
      that rely on Lightdm (LP: #1764005).
      Leave only prime-switch out, since a reboot is required now.

 -- Alberto Milone <alberto.milone@canonical.com>  Fri, 20 Apr 2018 12:25:01 +0200
```
http://changelogs.ubuntu.com/changelogs/pool/main/n/nvidia-prime/nvidia-prime_0.8.8/changelog

**Comment by ryanpcmcquen** [comment]
@jackpot51, will that be rolled into the NVIDIA ISO?

**Comment by jackpot51** [comment]
@ryanpcmcquen it already is.

**Comment by ryanpcmcquen** [comment]
I think that resolves this issue then.

**Comment by cpkdevries** [comment]
For me, when using `sudo system76-power graphics intel`, the system will freeze when I try to log in. I'll have to log in via the CLI and run `sudo system76-power graphics nvidia` in order to login properly again.

**Comment by cpkdevries** [comment]
Just an update: If using Pop on Wayland, I can log in using Intel Graphics. If not using Wayland, I can not log in (unless using Nvidia graphics)
