### ISSUE TITLE
Glorious Model D not doubleclicking

### ISSUE THREAD

**Issue by Sarreos** [pop-os/pop#2091]
**Distribution (run `cat /etc/os-release`):**
 Pop OS 21.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Glorious Model D software

**Issue/Bug Description:**
After upgradubg to Pop OS 21.10
My Glorious Model D mouse stopped double clicking and debounce time is already set to the lowest so was there anything that affected double clicking in 21.10 update?

**Steps to reproduce (if you know):**
Plug the mouse and click

**Expected behavior:**
Mouse should double click

**Other Notes:**

**Comment by jacobgkau** [comment]
> Glorious Model D software

Is this software you have installed? Where did you install it from?

**Comment by Sarreos** [comment]
It's a Windows Software. It used to work just fine by flashing mouse
settings from a windows machine or a VM and then plugging the mouse to a
Linux machine. But after upgrading from 21.04 to 21.10 it stopped double
clicking. The debounce time in software is set to the lowest and it seems
like 21.10 is adding additional debounce time on top of the default.
