### ISSUE TITLE
[ThinkPad T420s] WIFI is slow, plus some graphical issues

### ISSUE THREAD

**Issue by thatfatblackcat** [pop-os/pop#2095]
I upgraded from 21.04 to 21.10 using the GUI after having issued `apt full-upgrade` on the terminal.
I'm running Pop!_OS on my ThinkPad T420s and I'm experiencing the following issues:

## Technical Issues
- WIFI is painfully slow. Here's the stats reported by `speedtest-cli`.

```
# speedtest --single running Pop!_OS 21.04
Retrieving speedtest.net configuration...
Testing from ______________ (______________)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by ____________ (________________) [112.06 km]: 18.21 ms
Testing download speed................................................................................
Download: 44.89 Mbit/s
Testing upload speed......................................................................................................
Upload: 16.53 Mbit/s

# speedtest --single running Pop!_OS 21.10
Retrieving speedtest.net configuration...
Testing from ______________ (______________)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by _____________ (_________________) [603.37 km]: 72.807 ms
Testing download speed................................................................................
Download: 10.61 Mbit/s
Testing upload speed......................................................................................................
Upload: 9.45 Mbit/s
```
 
## Graphical Issues

- Launcher appears at the bottom of the screen when running full screen applications.
- Desktop icons appear on top of the current window when moving between workspaces.
- Gnome bar feels slightly bigger and volume splash has changed (idk if that's intended).   

https://user-images.githubusercontent.com/75761474/146648426-206b0612-567d-4e90-9ed9-fd98ab9a822c.mp4

## Additional Notes

- Seems like this update prevents users from customizing Gnome bar transparency with extensions.

**Comment by jacobgkau** [comment]
What wireless card is in your ThinkPad T420s?

> Launcher appears at the bottom of the screen when running full screen applications.

Do you mean maximized, or truly full-screen? By "launcher," do you mean dock? Full-screening is working for me, it's tested regularly during Pop Shell regression testing.

> Desktop icons appear on top of the current window when moving between workspaces.

There is already an issue open for this: https://github.com/pop-os/beta/issues/320 

> Gnome bar feels slightly bigger and volume splash has changed (idk if that's intended).

The volume icon that shows in the top bar and OSD was tweaked recently.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by thatfatblackcat** [comment]
> What wireless card is in your ThinkPad T420s?

03:00.0 Network controller: Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)
00:19.0 Ethernet controller: Intel Corporation 82579LM Gigabit Network Connection (Lewisville) (rev 04)

I checked yesterday and the problem appears also on wired connection.

> Do you mean maximized, or truly full-screen? By "launcher," do you mean dock?

Not maximized, full screen like when you press `F11` on `Firefox`.
No, I mean the floating window mapped to `SUPER`. The program like `dmenu` or `rofi`.

Maybe you are using some mail client, you seem to have skipped the video I shared on the main post.
For unknown reasons it's not displaying well on GitHub. You can download it with `wget`.

## I found another graphical issue

- Switching workspace from a full screen app to a maximized one makes the latter bounce

I think this because the desktop calculates the space for the Gnome bar after the one for the window.
If you examine the video closely I think you can see that too. Am I the only one experiencing this?

## Additional Notes
What's the OSD? Also is there a way I can bring back the old Gnome bar size?

**Comment by thatfatblackcat** [comment]
I ended up reinstalling Pop!_OS 21.10 using the ISO file on the website, here's what I found.

- WIFI is back to normal, the problem was the DNS I was using.
- Graphical issues still persist, just look the previous posts. 

The biggest issue is gone so I'm going to close, but don't forget the graphical issue. Thank you for the support.
