### ISSUE TITLE
21.10 is ignoring display and power settings and powering off displays too early

### ISSUE THREAD

**Issue by n-hebert** [pop-os/pop#2096]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
gnome-shell:
  Installed: 40.5-1ubuntu2pop0~1633630918~21.10~91d3049
  Candidate: 40.5-1ubuntu2pop0~1633630918~21.10~91d3049
  Version table:
 *** 40.5-1ubuntu2pop0~1633630918~21.10~91d3049 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
        100 /var/lib/dpkg/status
     40.5-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu impish/main amd64 Packages
```
**Issue/Bug Description:**

The screen keeps going to black and powering off my external monitor after a *very* short window (30 seconds?) and there's no way to configure the time-out nor stop it from doing so.

**Steps to reproduce (if you know):**

1. Leave the computer alone for 60s

**Expected behavior:**

1. Timeout and power settings are observed properly

**Other Notes:**
I have configured my power settings *not* to dim any displays when inactive and to go to blank after 10 minutes. Nothing is being observed properly.
![image](https://user-images.githubusercontent.com/68243838/146802060-e20d4a4f-a94d-43a9-8224-bd331245432a.png)

This is also exacerbating #2074, making computing on this a drag.

**Comment by melizasw** [comment]
I had this same problem after updating my Lemur Pro from 21.04 to 21.09. The command `xset -dpms` provided some relief, but also meant that the the screen wouldn't power off when it was supposed to. Today's update which included the 5.15.8 kernel seems to have fixed it.

**Comment by n-hebert** [comment]
I'll give that kernel a shot and report back, too.

**Comment by allout58** [comment]
I was having the same problem (screen turning off after 30s inactivity), realized I hadn't rebooted since updating yesterday, then things started behaving normally. Seems like kernel 5.15.8 did fix the issue for me.

**Comment by n-hebert** [comment]
Hooray - the system updates *did* seem to fix this.
The functional kernel is `Linux 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux`
