### ISSUE TITLE
apt not auto completing package names

### ISSUE THREAD

**Issue by dasunsrule32** [pop-os/pop#210]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**

> NAME="Pop!_OS"
> VERSION="18.04 LTS (Testing)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Pop!_OS 18.04 LTS (Testing)"
> VERSION_ID="18.04"
> HOME_URL="https://system76.com/pop"
> SUPPORT_URL="http://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**

You cannot  tab complete any package name when using `sudo apt install $package`. It will not tab complete at all.

**Steps to reproduce (if you know)**
Try to install a package using apt and tab complete the package name, it won't tab complete.

**Expected behavior**

bash-completion should tab complete package names using apt.

**Other Notes**

**Comment by cassidyjames** [comment]
This can happen on first boot or if for some reason the apt cache doesn't exist. Running `sudo apt update` first should fix it.
