### ISSUE TITLE
Blue Recorder froze and overwrote recording

### ISSUE THREAD

**Issue by joeitu** [pop-os/pop#2101]
see https://github.com/xlmnxp/blue-recorder/issues/23

**Comment by jacobgkau** [comment]
Blue Recorder is available via [Flathub](https://flathub.org). The Pop!_Shop does not filter or restrict the apps that display from sources configured on the system, which include Flathub and the Ubuntu repositories.

If you wish to speak to the Flathub maintainers about the app, the app's page is [here](https://flathub.org/apps/details/sa.sy.bluerecorder) and that page links to the publisher repository [here](https://github.com/flathub/sa.sy.bluerecorder). It looks like you already filed an issue in the appropriate upstream repository, though, so I'm not sure if there's any action Flathub will take, either.

**Comment by xlmnxp** [comment]
@joeitu  sorry for that, we will make release today for add that feature
@jacobgkau you can close this ticket and we will handle this issue from our side

**Comment by joeitu** [comment]
Hi @jacobgkau ,

The software has been updated by @xlmnxp , but the update is still not available on the popshop, does it take some time to update the repos?

**Comment by xlmnxp** [comment]
> Hi @jacobgkau ,
> 
> The software has been updated by @xlmnxp , but the update is still not available on the popshop, does it take some time to update the repos?

it updated in flatpak and snap
yasterday it take hour and 30 minute to show in flathub

try
```
flatpak update sa.sy.bluerecorder
```

**Comment by joeitu** [comment]
Actually the software was properly updated, see https://github.com/xlmnxp/blue-recorder/issues/23#issuecomment-1000332993
