### ISSUE TITLE
Fresh upgrade to 21.10 resulted in black flickering and app ghosting

### ISSUE THREAD

**Issue by ruineka** [pop-os/pop#2102]
![PXL_20211221_210652045.jpg](https://user-images.githubusercontent.com/16360335/147022487-9bab2962-f45a-416b-a4ab-c79f03f9f25e.jpg)

![PXL_20211221_210847745.jpg](https://user-images.githubusercontent.com/16360335/147022505-29f8eb61-fc5c-4c26-a333-43e9366a3810.jpg)

This started after applying all updates to 21.04 and restarting. After this happened I decided to give 21.10 a go and it has the same issue.

**Comment by ruineka** [comment]
This issue also exists when using KDE, the only way to get rid of it is to change compositor settings to xrender, or set vsync to full screen repaints which puts the laptop into a heavy GPU usage situation making my systems fans go crazy at idle. From what I gather it's an Nvidia related matter and I'm not sure how I can fix this on the Pop Desktop.

**Comment by ruineka** [comment]
The laptop is a ROG Zephyrus G14 GA401QM with an RTX 3060 and Ryzen 9 5900HS with Vega 8 graphics. The display settings are handled by the Prime display within Nvidia X settings.

**Comment by mmstick** [comment]
You can try reinstalling the NVIDIA drivers

```
sudo apt remove '~nnvidia'
sudo apt install nvidia-driver-470
```

If you've already tried reinstalling the NVIDIA drivers, perhaps you could try the 495.46 driver.

```
git clone https://github.com/pop-os/pop
cd pop
./scripts/apt add 495.46
sudo apt full-upgrade
```

When the staging branch is deleted, you'll have to manually remove it

```
./scripts/apt remove 495.46
```

**Comment by ruineka** [comment]
> You can try reinstalling the NVIDIA drivers
> 
> ```
> sudo apt remove '~nnvidia'
> sudo apt install nvidia-driver-470
> ```
> 
> If you've already tried reinstalling the NVIDIA drivers, perhaps you could try the 495.46 driver.
> 
> ```
> git clone https://github.com/pop-os/pop
> cd pop
> ./scripts/apt add 495.46
> sudo apt full-upgrade
> ```
> 
> When the staging branch is deleted, you'll have to manually remove it
> 
> ```
> ./scripts/apt remove 495.46
> ```

Alright thanks. I wiped my computer out to try Ubuntu and I haven't had issues with it. I'll try installing Pop OS again to see if I can replicate the issue, if I can I'll attempt to update the Nvidia driver. Side note it's been a long while since I've used Ubuntu and I find it rather nice how it has a easy GUI solution to switch between proprietary drivers, which I don't recall seeing in Pop OS. Is it possible to enable an Experimental branch that would would execute a script like you listed to test 495.46 in a manner like how Ubuntu handles it?

**Comment by EliDenning** [comment]
Having same issue, seemed to have somewhat tracked it down to this error.

E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

I'm new to this so I have no idea what any of this means

**Comment by ruineka** [comment]
I've upgraded on a few different devices recently again and haven't been able to replicate this issue so I'm assuming it's been fixed. Closing this ticket.
