### ISSUE TITLE
Pop-dark shell theme does not display any typed characters in Activities Overview search.

### ISSUE THREAD

**Issue by knapolian** [pop-os/pop#211]
**Distribution - POP!_OS 18.04 LTS Testing**
 
 
**Issue/Bug Description** After choosing Pop-dark shell theme, cannot see characters typed in Activities Overview search. If the shell theme is Pop or Pop-light, the typed search characters are white on a dark background and very visible. Those same letters are invisible in POP-dark

**Steps to reproduce**  After installing Gnome-Tweaks, go to Appearance... Shell, select Pop-dark. Then switch to Activities Overview and start a search. The letters typed do not display.

**Comment by demoklion** [comment]
This is also true in many forms throughout the UI and even on some websites (eg. asana.com).
See attached screenshots with and without dark mode.

dark mode on
![image](https://user-images.githubusercontent.com/1686152/57122011-448ce480-6d7b-11e9-8bab-30603d4d0542.png)

dark mode off
![image](https://user-images.githubusercontent.com/1686152/57122039-65553a00-6d7b-11e9-8692-04cf472d7cae.png)

**Comment by mmstick** [comment]
Seems the original issue here is fixed.

@demoklion Which web browser are you using?

**Comment by demoklion** [comment]
oh, sorry @mmstick , I failed to notice that. Should I submit a new issue?

It's `Firefox Developer Edition 67.0b16 (64-bit)`
