### ISSUE TITLE
Unmet dependencies for pop-desktop

### ISSUE THREAD

**Issue by Haych13** [pop-os/pop#2115]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=hirsute
UBUNTU_CODENAME=hirsute
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
apt policy pop-desktop
pop-desktop:
  Installed: 1.6.0~1625267683~21.04~ac0465f
  Candidate: 1.6.0~1625267683~21.04~ac0465f
  Version table:
 *** 1.6.0~1625267683~21.04~ac0465f 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu hirsute/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
When running apt dist-upgrade I get an error that following packages have unmet dependencies

```
sudo apt dist-upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Error!
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 pop-desktop : Depends: pop-session but it is not going to be installed
               Depends: chrome-gnome-shell but it is not going to be installed
               Depends: gdm3 but it is not going to be installed
               Depends: gnome-shell but it is not going to be installed
               Depends: pop-default-settings but it is not going to be installed
               Recommends: geary but it is not going to be installed
               Recommends: gnome-calendar but it is not going to be installed
               Recommends: gnome-contacts but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
               Recommends: libreoffice-calc but it is not going to be installed
               Recommends: libreoffice-impress but it is not going to be installed
               Recommends: libreoffice-writer but it is not going to be installed
               Recommends: gnome-remote-desktop but it is not going to be installed
               Recommends: gnome-shell-extension-prefs but it is not going to be installed
               Recommends: libreoffice-ogltrans
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Steps to reproduce (if you know):**
`sudo apt dist-upgrade`
or
`sudo apt-get full-upgrade`

**Expected behavior:**
dist-upgrade should upgrade as normal

**Other Notes:**
I am unable to upgrade to 21.10 and think this might be related and I'm not sure where to go from here. Here is the output from trying to upgrade pop

```
pop-upgrade release upgrade
checking if pop-upgrade requires an update
Current Release: 21.04
Upgrading to: 21.10
New version available: 3
Recovery event: fetching recovery files
Event: updating package lists
Event: fetching updated packages for the current release
Release upgrade status: release upgrade aborted: failed to fetch apt URIs to fetch
pop-upgrade: calling ReleaseUpgradeFinalize method failed
  caused by: release upgrade cannot be finalized, because a release upgrade was not performed
```

**Comment by jacobgkau** [comment]
The easiest way to recover from this would be to boot from Pop!_OS Recovery (space bar on an EFI system) or a USB live disk, and perform a Refresh Install. This will reset the system's packages to 21.10 defaults, but will leave your personal home directory intact.

If that's not an option for some reason, you would need to look at what package versions are currently installed on your system and which ones are available:

```
apt policy gnome-settings-daemon libgweather-3-16 gdm3 gnome-shell libmutter-7-0 pop-desktop pop-session chrome-gnome-shell gnome-shell pop-default-settings gnome-calendar gnome-contacts gnome-weather gnome-remote-desktop gnome-shell-extension-prefs
```

Determine which ones have incorrect versions installed, and force the correct versions to install:

```
mkdir packages
cd packages
apt download <package-name>=<package-version> <package-name>=<package-version> ...
sudo dpkg --force-all -i ./*.deb
```

The idea is that the system should have only 21.04 (or only 21.10) packages installed when you're done. This may become tedious depending on how many packages need to be upgraded/downgraded.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by jacobgkau** [comment]
I'm closing this old support request. If you still need any assistance, feel free to comment again, create a new issue, or join us on the [Pop!_OS Mattermost chat server](https://chat.pop-os.org/).
