### ISSUE TITLE
Feature request: Integrate bolt/boltd to enable security levels in thunderbolt

### ISSUE THREAD

**Issue by sramkrishna** [pop-os/pop#212]
According to - https://christian.kellner.me/2018/04/23/the-state-of-thunderbolt-3-in-fedora-28/ - they have integrated thunderbolt access levels which would be useful for docks and the like.  There are many parts of it but the main workhorse is the bolt/boltd - https://gitlab.freedesktop.org/bolt/bolt  that might be worth packaging and integrating  into the pop experience.

**Comment by jiaowoshabi** [comment]
+1

**Comment by jackpot51** [comment]
@jiaowoshabi have you checked under Devices -> Thunderbolt in gnome-control-center?

**Comment by jiaowoshabi** [comment]
@jackpot51 Thanks. I upgrade my os and fount it in 18.04 ;).
