### ISSUE TITLE
Massive spam of errors in system journal when Cosmic Dock is enabled

### ISSUE THREAD

**Issue by bitterhalt** [pop-os/pop#2122]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Cosmic Dock extension

**Issue/Bug Description:**
I get thousands error messages every time I launch apps If I enable Cosmic Dock
![popspam](https://user-images.githubusercontent.com/95308907/147509036-65f470ec-412e-48a6-8f54-59fe65f4bce7.png)

**Steps to reproduce (if you know):**
Enable Cosmic Dock when I launch apps

**Expected behavior:**
I should not get thousands of errors just opening apps

**Other Notes:**
Errors stop If I extend the Dock in edges of the screen but I don't like It that way.

**Comment by 13r0ck** [comment]
This appears to be related to drag and drop. Interestingly only when dragging over another icon.

![handle drag over](https://user-images.githubusercontent.com/58987761/147787073-692a86c7-4079-46ae-87e0-0b95e79fff3d.gif)

> `handling drag over` is debug code I added. Release build will show nothing when this is showing these messages.

**Comment by 13r0ck** [comment]
closed via pop-os/cosmic-dock#107
