### ISSUE TITLE
Needed A dedicated tool/way to upgrade newer kernel/modules & graphics drivers (a 'pop_core') separately from rest of OS (Avoids Breaks)

### ISSUE THREAD

**Issue by Daasin** [pop-os/pop#2123]
**Pop OS: Pop In General (but 21.10)** Could be a supported way to have a standard core and then proposed ones that people upgrade themselves if they want newer drivers and kernel versions (E.g. *5.15.11/5.16* & *Nvidia 495* from Nvidia's servers) Useful for those who want to track faster updates but still use Pop OS. Currently have to use the 'Mainline' Tool everytime an incremental update for the kernal is release from actual mainline, aswell as Ubuntu's Software & Updates to see all the proprietary graphics driver versions that are available to install.
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Pop Shop/Pop Store

**Issue/Bug Description: N/A listed in first paragraph,** would also help some testers find early workarounds to current bugs such as needing to manually refresh by changing display settings to see updated wallpaper after changing it, or even network issues.

**Steps to reproduce (if you know):** N/A 

**Expected behavior:** To have this functionality implemented similarly to Manjaro or OpenSUSE (Or Ubuntu) where you can set it to track updates from even unstable and get RC Kernel updates automatically.

**Other Notes:** Many apologies if this was filed incorrectly but new to Pop OS after 21.10 release & wanted to request this somewhere, could be very helpful to a lot of people looking to rule out causes of issues or even find quick fixes/features to workaround with! :)

**Comment by Daasin** [comment]
Also to clarify (just in case) "pop_core" was more of a placeholder for what a core-modules + graphics driver bundle could be called than anything else

**Comment by jacobgkau** [comment]
Related feature request: https://github.com/pop-os/nvidia-graphics-drivers/issues/112
