### ISSUE TITLE
wifi power management enabled by default

### ISSUE THREAD

**Issue by PGQT** [pop-os/pop#2141]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf

**Issue/Bug Description:**

wifi power management on by default, lowering network speed to VERY low. sometimes single digit bits/sec.
~.001 mb/s

**Steps to reproduce (if you know):**

install pop!_os on hp pavillion gaming pc 16-a0075d
core i7 10750h
NV168 / Mesa Intel® UHD Graphics (CML GT2)
nvidia gtx1660ti with MAXq
31.1GiB ddr4
gnome 40.4.0
intel wifi 6 card 

**Expected behavior:**

~100mb/sec

**Other Notes:**
default installation options. changing wifi power text file to say value of '2' instead of '3' fixed the issue.

**Comment by bflanagin** [comment]
Thanks for the report, 
This is now the default power level in the last few images published. (Based on lab tests)
Closing ticket.

**Comment by PGQT** [comment]
same issue just came up in a different laptop.  default-wifi-powersave-on.conf   was set to 3 again. this laptop has not had issues with wifi speed until now
