### ISSUE TITLE
Dell Thunderbolt dock USB ports stopped working after update to Pop!_OS 21.10

### ISSUE THREAD

**Issue by kubahejda** [pop-os/pop#2144]
**Distribution (run `cat /etc/os-release`):** 
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
**Issue/Bug Description:**
When upgraded Pop!OS to the latest version, suddenly my keyboard and mouse plugged into the DELL Thunderbolt dock TB16 stopped working. The displays (both HDMI and DisplayPort) work fine. Also the thunderbolt socket on the docking station stopped working. Tried to reboot, replug everything, even resetted the docking station, but nothing helped, all the USBs are dead.

**Steps to reproduce (if you know):**
Plug in docking station via thunderbolt port.

**Expected behavior:**
Everything plugged into the docking station works.

**Other Notes:**

**Comment by connorf25** [comment]
Am also having the same issue on the WD19TB docking station, can confirm that all drivers are up to date. Did you end up getting it to work?

**Comment by connorf25** [comment]
Just managed to fix it, go to `settings -> privacy -> thunderbolt` and authorize the device there

**Comment by kubahejda** [comment]
> Just managed to fix it, go to `settings -> privacy -> thunderbolt` and authorize the device there

Oh, did not think about that one, have already authorized it previously, but maybe after the update it got resetted. Will try next week when return to work. Thank you

**Comment by kubahejda** [comment]
Worked for me as well, thanks :)

**Comment by Mauhing** [comment]
> Just managed to fix it, go to `settings -> privacy -> thunderbolt` and authorize the device there

Thank for the solution, I had the same problem.
