### ISSUE TITLE
Encryption password prompt not visible

### ISSUE THREAD

**Issue by NPaudel** [pop-os/pop#2170]
**Distribution:**
 Pop!_OS 21.10

**Issue/Bug Description:**
After the update, when booting up, the prompt for LUKS password is not present, just a blank screen. But, if you type in your password and hit enter, it does get unlocked.

**Steps to reproduce (if you know):**
On a laptop with encryption enabled, update
Reboot

**Expected behavior:**
A prompt for unlocking the disk appears.

**Other Notes:**
When I restored a backup created before the update, the prompt reappeared. But updating made it disappear again

**Comment by leviport** [comment]
If you hit `Esc` twice when it's at the blank screen, does the prompt appear normally? If so, this is probably related to Plymouth.

**Comment by NPaudel** [comment]
Yes, the prompt is visible after pressing `Esc` twice. [This solution ](https://github.com/pop-os/plymouth-theme/issues/19#issuecomment-904697078) in pop-os/plymouth-theme solved it. Thanks
