### ISSUE TITLE
Prolonged or indefinite wifi dropouts on Pop!_OS 21.10 on Thelio Major R2

### ISSUE THREAD

**Issue by nickgerace** [pop-os/pop#2188]
**Distribution (run `cat /etc/os-release`):**

 ```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** I cannot determine which package is causing the issue. I checked `dmesg`, but saw nothing out of the ordinary. I'd be happy to look further with some recommendations.

**Issue/Bug Description:** Wifi drops out intermittently and for prolonged or indefinite periods. It does not come back unless I turn on and off wifi functionality in the GNOME menu bar applet (in the top right section of the menu bar by default). Restarting the OS "resolves" the issue as well.

The issue _may_ eventually resolve itself, but given that occurs during my workday, I have not had the time to wait and find out. I use the aforementioned workarounds in the interim.

The issue usually occurs twice in a row, with about a minute in between the two dropouts. It occurs intermittently for multiple times within the same day. I'd say it does not happen more than once per hour though.

**Steps to reproduce (if you know):**

1. Use Thelio Major R2 with Threadripper 3970X (or equivalent system for network setup)
2. Use Pop!_OS 21.10 native install and update all packages (`apt update && apt upgrade`)
3. Ensure packages are updated as of 24 Jan 2022 ~1900 UTC and kernel version is at least `5.15.15-76051515-generic`
4. Leave desktop setup mostly stock (no DE tweaks, custom kernels, etc.)
5. Observe issue intermittently (happens whether or not the OS has been restarted

**Expected behavior:** Wifi continues to work without prolonged dropouts. Occasional, small dropouts ("blips") would be fine or expected, but prolonged dropouts that halt internet usage and videoconferencing calls should not happen.

**Other Notes:**

- The hardware is stock, uses an AMD GPU and I am unsure if it uses a separate wifi card or one built into the motherboard
- It has been encountered most often when using Zoom (installed as a `.deb`), though I think this is red herring since Zoom is my most consistent usage of the internet on a daily basis (e.g. downtime could easily occur between checking Slack, compiling code, reading docs, getting up for a break, etc.)

**Comment by Pramodh-G** [comment]
I have this issue as well, with a NVIDIA GPU. Internet drops out unless and until I restart it. I have an ASUS ROG laptop with an i7 intel core. Happens once an hour too.

**Comment by Pramodh-G** [comment]
Hi, I'm sorry to keep pushing this thread up, but it is debilitating if your WiFi goes poof every hour. I request the maintainers to please look into this issue. Bump.

Thanks.

**Comment by nickgerace** [comment]
## Update

I'm closing this issue to while it was oddly timed that WiFi dropouts were happening right after a new Pop_OS! installation, I was able to observe that shared 5 GHz and 2.4 GHz bands under one SSID was the issue causing the dropouts.

## Likely Culprit

The router is supposed to support shared network under one SSID, and I'm surprised these dropouts haven't occurred in the past, but disabling it appears to have solved the problem.

## Could it still be Pop_OS! (or Linux, by extension)?

Sure, maybe there's an edge case where Pop_OS! and my router might be flip flopping between bands.
These dropouts did not occur with this same machine running Fedora 35, so maybe that's what triggered it (especially weird since these dropouts do not occur when my Thelio is turned off...), but I think that's a battle for a different day.
I am not a hardware networking expert, so I thought I'd drop the anecdote regardless.

## Future Plans

I will re-open this issue if the aforementioned culprit isn't the real one.

@Pramodh-G I recommend opening another issue as a result :) hope it gets solved for you!

**Comment by cloo** [comment]
I can confirm that a similar issue can be resolved by renaming one of wi-fi bands so that the names start differing. 

I suggest to reopen the issue, because neither Windows, nor MacOs or Android do not have this problem, and users should not be forced to alter router settings just for it to work reliably with Pop!_OS. 

Expected behavior of non-techie user should be just user declaring that OS is buggy and unreliable out of the box, instead of dedicating their time  to find out what is happening with hopes to be able to fix it. (I had almost no hopes honestly, it was mostly luck).

**Comment by rschlack** [comment]
I have the same issue on an HP Dev One laptop with a fresh pop install.   I upgraded the card in this laptop to 6e.  I had previously thought it was a wifi card problem until I found this report.

**Comment by KevinGenus** [comment]
> I have the same issue on an HP Dev One laptop with a fresh pop install. I upgraded the card in this laptop to 6e. I had previously thought it was a wifi card problem until I found this report.

Same here.... 

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by JonasPhilbert** [comment]
This problem persists on my machine, a HP ZBook Firefly

```
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```
