### ISSUE TITLE
Keyboard backlight just seems to have stopped working

### ISSUE THREAD

**Issue by juanejot** [pop-os/pop#2189]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown; perhaps gnome-settings in some capacity? Conjecture, as I see that in the 21.10 installer, that gnome-settings (or the "Settings" app) actually had a slider for the keyboard backlight on the "Power" pane, but it does not seem to be there now (and as below in the "Steps to reproduce" section, it works when booted from the live install media, not when booted from my system as presently updated).

**Issue/Bug Description:**
Sorry to add this to the main "pop" repository, but I'm unsure which pop-os sub-repository it might fall under; input welcome. I just noticed (and don't see exactly among any issues with any version earlier than 18.04) that my keyboard backlight is not lit, not possible to light, and the keyboard backlight hotkeys only prompt the keyboard backlight icon to be shown over the rest of the display, but not the actual backlight level. Therefore, the hovering icon does not show any change, whether pressing the up or down hotkey. The icon just shows up hovering over the rest of the display for a moment, but with no level indicator (I suppose the backlight level remains zero).
`system76-power profile` returns the following:

> Power Profile: Balanced
Backlight gmux_backlight: 35048/82311 = 42%
Keyboard Backlight smc::kbd_backlight: 0/255 = 0%

**Steps to reproduce (if you know):**
Tap either up or down keyboard backlight hotkey. This issue survives logout/in, and reboots. Booting 21.10 live install media (as mentioned above in "Related Application or Package Version") reverts to expected behavior (so I know the backlight isn't physically burnt out, and it _is_ down to a recent software update), including a usable & responsive slider in the Power pane of the Settings app (gnome-settings?).

**Expected behavior:**
For the actual level of the keyboard backlight to go up and down per the correct key press, and for the level and its change to be indicated by the keyboard backlight icon which hovers over the rest of the display for a moment.

**Other Notes:**
The two most recent `sudo apt update && sudo apt full-upgrade` installations having been all the components that go with kernel 5.15.15. Full list of packages installed/upgraded from /var/log/apt/history.log:

> Install: linux-headers-5.15.15-76051515-generic:amd64 (5.15.15-76051515.202201160435~1642693824~21.10~97db1bb, automatic), linux-headers-5.15.15-76051515:amd64 (5.15.15-76051515.202201160435~1642693824~21.10~97db1bb, automatic), linux-modules-5.15.15-76051515-generic:amd64 (5.15.15-76051515.202201160435~1642693824~21.10~97db1bb, automatic), linux-image-5.15.15-76051515-generic:amd64 (5.15.15-76051515.202201160435~1642693824~21.10~97db1bb, automatic)
Upgrade: linux-system76:amd64 (5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21, 5.15.15.76051515.202201160435~1642693824~21.10~97db1bb), udev:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), linux-headers-generic:amd64 (5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21, 5.15.15.76051515.202201160435~1642693824~21.10~97db1bb), systemd-container:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), popsicle:amd64 (1.3.0~1640021224~21.10~b02ebf5, 1.3.0~1642705636~21.10~eb02826), systemd-timesyncd:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), libpam-systemd:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), libsystemd0:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), libnss-systemd:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), systemd:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), libudev1:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), linux-generic:amd64 (5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21, 5.15.15.76051515.202201160435~1642693824~21.10~97db1bb), pop-gnome-initial-setup:amd64 (3.36.1~1633446370~21.10~f7c0b46, 3.36.1~1642716511~21.10~0764d5d), libnss-mymachines:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), popsicle-gtk:amd64 (1.3.0~1640021224~21.10~b02ebf5, 1.3.0~1642705636~21.10~eb02826), linux-image-generic:amd64 (5.15.11.76051511.202112220937~1640185481~21.10~b3a2c21, 5.15.15.76051515.202201160435~1642693824~21.10~97db1bb), systemd-sysv:amd64 (248.3-1ubuntu8pop0~1634223273~21.10~0f0b7aa, 248.3-1ubuntu8.2pop0~1642619863~21.10~47b8972), linux-libc-dev:amd64 (5.15.11-76051511.202112220937~1640185481~21.10~b3a2c21, 5.15.15-76051515.202201160435~1642693824~21.10~97db1bb)
End-Date: 2022-01-21  16:57:29

 Following that, I did  a `sudo apt autoremove` that got rid of the kernel 5.15.8 packages, then a separate `sudo apt update && sudo apt full-upgrade` that upgraded pop-transition to 1.1.2~1642814356~21.10~617772e.
I've only just noticed the new behavior, so I don't know for sure whether it was concurrent with one, the other, or neither of these installations. Booting to kernel 5.15.11 does _not_ alleviate the behavior, so while it may have happened concurrent with its installation, it may have been a change to pop-gnome-initial-setup or another package, which changed this behavior. 
This change in behavior is sadly ironic, as I run OpenCore on a MacBookPro5,3 with one partition being macOS (where due to OpenCore configuration, the backlight hasn't worked for several OS versions), but the keyboard backlight has worked perfectly in Pop!_OS on the other partition, since at least 21.04, until I noticed it no longer working today.
Oh well, hopefully that functionality will come back, as it's particularly useful while typing on the computer at night.

**Comment by juanejot** [comment]
Well, this is odd in terms of apparent lack of relation, but upgrading the flatpak org.freedesktop.Platform.GL.nvidia-340-108 (specific to my system as I have an old seems to have an old GeForce 9400M/9600M GT, which needs a legacy version of Nvidia driver 340.108 that will work with a >5.4 kernel) fixed it. Not sure how a flatpak that interacts with/acts for flatpaks as (?) the video driver fixed a keyboard backlight issue, but cool.
If someone noted my issue & pushed an update, thanks! If it was just a side-effect of whatever was else was worth updating in that flatpak, cool too. Closing this issue, as it appears resolved.

**Comment by sriniferal** [comment]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

system76-power profile
Power Profile: Balanced
Backlight amdgpu_bl1: 85/255 = 33%

The backlight on my pangolin (pang11) has stopped working and it is stuck in a blue light. I cannot turn it off, increase/decrease the brightness, nor change the colour. I keep the back light is turned off, and I use it only when required. The Fn keys work normally, and it is not an keyboard issue. The backlight disappears when the laptop goes to sleep, it cannot be turned on after exiting the sleep mode. 
This seems to be a software issue as the same problem is not faced if I boot using a live disk. I’m not sure if this is due to any recent software updates. 

I would like to revert to my preferred setting, kindly let me know how to get the backlight to work properly.

**Comment by carlosfherrera** [comment]
@sriniferal I've the same issue since a couple of months with my Oryx Pro (oryp5). The keyboard is stuck with the blue light, with no possibility of adjusting anything. Maybe some software update messed it up.

**Comment by sriniferal** [comment]
I reinstalled system76-dkms system76-acpi-dkms and a reboot fixed the issue.
https://github.com/pop-os/pop/issues/3299
