### ISSUE TITLE
"Wifi can be turned off to save power" toggles wifi off

### ISSUE THREAD

**Issue by TheDevoyage** [pop-os/pop#2199]
**Distribution (run `cat /etc/os-release`):**
Pop OS 21.10 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

System Settings > Power Settings > Wifi > Wifi can be turned off to save power

**Issue/Bug Description:**

Toggle this setting to disable wifi turning off actually turns off the wifi.

**Steps to reproduce (if you know):**

Open settings, top right corner. Hit "Power" from sidebar menu. Be sure to be connected to wifi. Toggle the "Wifi can be turned off to save power" to the off position, and the wifi will turn off. 

**Expected behavior:**

After toggling, the wifi should not be allowed to turn off when system sleeps/suspends.

**Other Notes:**

<3 loving Pop, hope this helps

**Comment by leviport** [comment]
I agree that the switch labels can be confusing, but that's how they're intended to work. Wifi and bluetooth can be turned off with the switch, which does save power. 

Wireless cards are powered down during suspend on pretty much all machines anyway, so there wouldn't need to be a setting to enable that behavior.

**Comment by jacobgkau** [comment]
There is another issue open about the confusing wording here (so this issue would be a duplicate): https://github.com/pop-os/gnome-control-center/issues/13
