### ISSUE TITLE
Icons Duplicated on Desktop

### ISSUE THREAD

**Issue by Banjarini** [pop-os/pop#2208]
'
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

System:
  Host: pop-os Kernel: 5.15.5-76051505-generic x86_64 bits: 64 compiler: gcc 
  v: 11.2.0 Desktop: GNOME 40.5 Distro: Pop!_OS 21.10 base: Ubuntu Impish 
Machine:
  Type: Desktop Mobo: Acer model: Veriton M4620G 
  serial: <superuser required> BIOS: Acer v: P01-A0 date: 05/10/2012 
CPU:
  Info: Quad Core model: Intel Core i5-3470 bits: 64 type: MCP 
  arch: Ivy Bridge rev: 9 cache: L2: 6 MiB 
  flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 25541 
  Speed: 1684 MHz min/max: 1600/3600 MHz Core speeds (MHz): 1: 1684 2: 2783 
  3: 3593 4: 2300 
Graphics:
  Device-1: NVIDIA GF116 [GeForce GTX 550 Ti] driver: nvidia v: 390.144 
  bus-ID: 01:00.0 
  Display: x11 server: X.Org 1.20.13 driver: loaded: nvidia 
  unloaded: fbdev,modesetting,nouveau,vesa resolution: 1366x768~60Hz 
  OpenGL: renderer: GeForce GTX 550 Ti/PCIe/SSE2 v: 4.6.0 NVIDIA 390.144 
  direct render: Yes 
Network:
  Device-1: Broadcom NetXtreme BCM5761 Gigabit Ethernet PCIe 
  vendor: Acer Incorporated ALI driver: tg3 v: kernel port: e000 
  bus-ID: 03:00.0 
  IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: ec:a8:6b:8c:66:ad 
  IF-ID-1: vmnet1 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:01 
  IF-ID-2: vmnet8 state: unknown speed: N/A duplex: N/A 
  mac: 00:50:56:c0:00:08 
Drives:
  Local Storage: total: 1.47 TiB used: 32.19 GiB (2.1%) 
  ID-1: /dev/sda model: KLLISRE 120GB size: 111.79 GiB temp: 30 C 
  ID-2: /dev/sdb vendor: Seagate model: ST1000VT001-1RE172 size: 931.51 GiB 
  temp: 33 C 
  ID-3: /dev/sdc vendor: Western Digital model: WD5000AAKX-221CA1 
  size: 465.76 GiB temp: 38 C 
Partition:
  ID-1: / size: 105.53 GiB used: 32.19 GiB (30.5%) fs: ext4 dev: /dev/sda1 
  ID-2: swap-1 size: 4 GiB used: 0 KiB (0.0%) fs: swap dev: /dev/dm-0 
  mapped: cryptswap 
Info:
  Processes: 242 Uptime: 25m Memory: 11.64 GiB used: 2.24 GiB (19.2%) 
  Init: systemd runlevel: 5 Compilers: gcc: 11.2.0 Packages: 2607 
  Shell: Bash v: 5.1.8 inxi: 3.3.06 
`

**Issue/Bug Description:**
When logging into the desktop the icons are duplicated.
the smaller ones in the background are not clickable.
see attached screenshot
![Screenshot from 2022-02-08 19-02-51](https://user-images.githubusercontent.com/52288498/153040585-f1281626-48eb-4664-9834-9ce14e3eb70b.png)

**Steps to reproduce (if you know):**
login to desktop

to remove switch to workspace two triple left click and they disappear.
left clicking on workspace 1 does nothing changing the wallpaper also does nothing.

**Expected behavior:**
Icons are not duplicated

--!>

**Comment by bflanagin** [comment]
Thanks for all the info. Could you provide a list of gnome-extensions you have installed?

**Comment by Banjarini** [comment]
`jordan@pop-os:~$ ls /usr/share/gnome-shell/extensions/
cosmic-dock@system76.com        pop-shell@system76.com
cosmic-workspaces@system76.com  system76-power@system76.com
ding@rastersoft.com             ubuntu-appindicators@ubuntu.com
pop-cosmic@system76.com
`
is this what you are looking for?

**Comment by bflanagin** [comment]
You may also have some locally installed as well under ~/.local/share/gnome-shell/extensions/.  Ding is the extension responsible for desktop icons.

**Comment by Banjarini** [comment]
the directory ~/.local/share/gnome-shell/extensions/ does not exist

**Comment by Banjarini** [comment]
[packages.txt](https://github.com/pop-os/pop/files/8107825/packages.txt)
i just have the default file manager.

**Comment by Banjarini** [comment]
solved by opening extentions https://askubuntu.com/questions/1264002/duplicated-icons-on-the-desktop-after-upgrading-to-ubuntu-20-04
