### ISSUE TITLE
Tensorflow and CUDA install issues on POP os 

### ISSUE THREAD

**Issue by cameronaaron** [pop-os/pop#221]
@sramkrishna 
**Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
Install instructions for CUDA on the system 76 website are wrong and result in an error 
 http://support.system76.com/articles/cuda/

 get The following packages have unmet dependencies:
 cuda : Depends: cuda-9-1 (>= 9.1.85) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
"Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming."

I then tried to do a nvidia-cuda-dev nvidia-cuda-toolkit nvidia-nsight but after installing tensorflow I get a  I still get an error ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory which tells me this is missing some of the major lib files

also the pop repo is missing the cuda-command-line-tools

which will then lead to more and more errors because of missing packages in POP OS repos 

This is much harder to install than on UBUNTU. If possible could you please start packaging these tools in pop shop and  making sure all your packages are up to date

**Steps to reproduce (if you know)**
follow these two guides 
https://www.tensorflow.org/install/install_linux#gpu_support
 http://support.system76.com/articles/cuda/

**Expected behavior**

CUda and Tensorflow should be able to install correctly 

**Other Notes**

**Comment by brs17** [comment]
Currently the latest version that is officially supported by NVIDIA is for 17.04(Ubuntu). Once the toolkit is released compatible/working with 18.04 the support doc will be updated with the proper instructions (and tested to make sure it actually works).

**Comment by cameronaaron** [comment]
The issue is this was not working on 17.4 either and the support docs are even wrong for that platform

**Comment by cameronaaron** [comment]
I also troubleshooted with @sramkrishna on pop mattermost group about it and he said to open a ticket this was when it was still on 17.4

**Comment by cameronaaron** [comment]
Traceback (most recent call last):
  File "/home/cameronaaron/.local/bin/flow", line 4, in <module>
    from darkflow.cli import cliHandler
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/darkflow/cli.py", line 3, in <module>
    from .net.build import TFNet
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/darkflow/net/build.py", line 1, in <module>
    import tensorflow as tf
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/cameronaaron/.local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
cameronaaron@pop-os:~$

**Comment by cameronaaron** [comment]
I was able to some how get the installer to work in another go around but I installed the wrong version so I tried uninstalling it but when it installed again it did not put the proper files back into /usr/local meaning it was not reinstalling right

**Comment by cameronaaron** [comment]
I then tried to figure out why and i also noticed that it demanded that I do a apt-get update –fix-missing but then that errored out saying 

cuda-command-line-tools-9-0 set to manually installed.
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
cuda-cudart-dev-9-0 : Depends: cuda-driver-dev-9-0 but it is not going to be installed
cuda-libraries-dev-9-0 : Depends: cuda-driver-dev-9-0 (>= 9.0.176) but it is not going to be installed
cuda-samples-9-0 : Depends: cuda-driver-dev-9-0 but it is not going to be installed
cuda-toolkit-9-0 : Depends: cuda-nvml-dev-9-0 (>= 9.0.176) but it is not going to be installed
cuda-visual-tools-9-0 : Depends: cuda-driver-dev-9-0 but it is not going to be installed
Depends: cuda-nvml-dev-9-0 but it is not going to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
cameronaaron@pop-os:/Desktop$ apt --fix-broken install
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
cameronaaron@pop-os:/Desktop$ apt --fix-broken install
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
cameronaaron@pop-os:/Desktop$ sudo apt --fix-broken instal
E: Command line option --fix-broken is not understood in combination with the other options
cameronaaron@pop-os:/Desktop$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree
Reading state information... Done
Correcting dependencies... Done
The following packages were automatically installed and are no longer required:
g++-6 libaccinj64-9.1 libcublas9.1 libcudart9.1 libcufft9.1 libcufftw9.1
libcuinj64-9.1 libcurand9.1 libcusolver9.1 libcusparse9.1 libnppc9.1
libnppial9.1 libnppicc9.1 libnppicom9.1 libnppidei9.1 libnppif9.1
libnppig9.1 libnppim9.1 libnppist9.1 libnppisu9.1 libnppitc9.1 libnpps9.1
libnvblas9.1 libnvgraph9.1 libnvrtc9.1 libnvtoolsext1 libnvvm3 libthrust-dev
libvdpau-dev nvidia-opencl-dev nvidia-profiler nvidia-visual-profiler
ocl-icd-opencl-dev opencl-c-headers
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
cuda-driver-dev-9-0 cuda-nvml-dev-9-0
The following NEW packages will be installed:
cuda-driver-dev-9-0 cuda-nvml-dev-9-0
0 upgraded, 2 newly installed, 0 to remove and 1 not upgraded.
22 not fully installed or removed.
Need to get 0 B/58.5 kB of archives.
After this operation, 509 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 file:/var/cuda-repo-9-0-local cuda-driver-dev-9-0 9.0.176-1 [10.9 kB]
Get:2 file:/var/cuda-repo-9-0-local cuda-nvml-dev-9-0 9.0.176-1 [47.6 kB]
(Reading database ... 260736 files and directories currently installed.)
Preparing to unpack .../cuda-driver-dev-9-0_9.0.176-1_amd64.deb ...
Unpacking cuda-driver-dev-9-0 (9.0.176-1) ...
dpkg: error processing archive /var/cuda-repo-9-0-local/./cuda-driver-dev-9-0_9.0.176-1_amd64.deb (--unpack):
trying to overwrite '/usr/local/cuda-9.0/lib64', which is also in package cuda-cudart-9-0 9.0.176-1
Preparing to unpack .../cuda-nvml-dev-9-0_9.0.176-1_amd64.deb ...
Unpacking cuda-nvml-dev-9-0 (9.0.176-1) ...
dpkg: error processing archive /var/cuda-repo-9-0-local/./cuda-nvml-dev-9-0_9.0.176-1_amd64.deb (--unpack):
trying to overwrite '/usr/local/cuda-9.0/lib64', which is also in package cuda-cudart-9-0 9.0.176-1
Errors were encountered while processing:
/var/cuda-repo-9-0-local/./cuda-driver-dev-9-0_9.0.176-1_amd64.deb
/var/cuda-repo-9-0-local/./cuda-nvml-dev-9-0_9.0.176-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by cameronaaron** [comment]
So i deleted /var/cuda-repo-9-0-local/ and now it still asks to be fixed plus cant find /var/cuda-repo-9-0-local/ and there appears to be no way to get apt to forget about /var/cuda-repo-9-0-local/ it seems to be unremovable for some reason even though the local repo no longer exists 
Cameron, 5/27/2018 3:12 am

**Comment by cameronaaron** [comment]
So i deleted /var/cuda-repo-9-0-local/ and now it still asks to be fixed plus cant find /var/cuda-repo-9-0-local/ and there appears to be no way to get apt to forget about /var/cuda-repo-9-0-local/ it seems to be unremovable for some reason even though the local repo no longer exists

**Comment by peshmerge** [comment]
@cameronaaron execute this command 
`sudo apt-get --purge -y remove 'cuda*`
it will solve it! It solved for me

**Comment by mmstick** [comment]
CUDA and Tensorflow are in our software repository. The following metapackages make it an easy install:

- `system76-cuda-latest`
- `tensorflow-cuda-latest`
- `tensorflow-cpu-latest`

It's also possible to install multiple versions of CUDA / TF alongside each other, so check out what's in the repos with `apt search system76-cuda` / `apt search tensorflow`.
