### ISSUE TITLE
Control key not firing after suspend

### ISSUE THREAD

**Issue by kevinroleke** [pop-os/pop#2213]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 21.04

**Issue/Bug Description:**
The control key does not fire for the first ~30 minutes of usage after waking up from suspend.

**Other Notes:**
This is on a System76 Lemur laptop. I have heard of similar issues, but can't seem to find anything useful.

**Comment by leviport** [comment]
Which generation Lemur do you have? I'm not seeing this issue on the lemp9

**Comment by jacobgkau** [comment]
@kevinroleke Are you still experiencing this issue? Are you using a lemp9 or a lemp10? Does the issue continue to occur if you upgrade to Pop!_OS 21.10?

**Comment by jacobgkau** [comment]
Closing due to lack of response; please leave another comment and/or open a [support ticket](https://support.system76.com/) if you still need assistance.
