### ISSUE TITLE
Asus ZenBook UX425 function keys and sound stop working after deep sleep

### ISSUE THREAD

**Issue by franckgaga** [pop-os/pop#2217]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
```
![image](https://user-images.githubusercontent.com/34136215/153936079-5a9f8e3e-44e9-49d9-89ba-25f5c6cc4bde.png)

**Issue/Bug Description:**
My function keys (brightness, volume, etc.) and Fn Lock (Fn+Esc) stop working after I wake my Asus ZenBook UX425 (Intel 11th generation) from deep sleep (with kernel option `mem_sleep_default=deep`), hybrid sleep or hibernation. The sound also stop working. I need a reboot to make them works again. This issue does not appear if I use shallow sleep (without `mem_sleep_default=deep` kernel option). `acpi_listen` reports event at key press before deep sleep, but nothing is printed in the terminal after deep sleep.

**Steps to reproduce (if you know):**

1. Boot Pop!_OS : Fn keys and sound work properly
2. Deep sleep or hibernate computer
3. Wake computer
4. Fn keys and sound does not work

**Expected behavior:**
Deep sleep and/or hibernate should work since battery drain with shallow sleep is high (about 30% overnight)

**Other Notes:**
It may be a kernel problem. I've updated my Kernel to 5.15.23 and there is no improvement. Should I report a bug for linux kernel ?
Same issue repported here for Ubuntu : https://askubuntu.com/questions/1326292/fn-keys-and-sound-not-working-after-resume-from-deep-suspend-ubuntu-20-04-2-lt
And here for windows 10 : https://zentalk.asus.com/en/discussion/48290/zenbook-13-ux325-fn-keys-not-working-after-sleep-anyone

**Comment by franckgaga** [comment]
Edit : the sound stop working only after deep sleep + hybrid sleep. With hibernation, everything works except the Fn Lock feature (Fn+Esc), so my function keys does work but only by holding Fn+F1-12. It kind of makes sense since hibernation is similar to a full shutdown and startup.

**Comment by franckgaga** [comment]
As it seems to be a common issue on the device, and literally nobody suggest viable solution, here's my workaround in the meantime:

1. First activate Hibernation and Hybrid Sleep. See [here](https://support.system76.com/articles/enable-hibernation/) for Pop!_OS
2. Keep the default default sleep mode (don't provide `mem_sleep_default=deep` option with `kernelstub`)
3. Disable hybrid-sleep with `sudo systemctl mask hybrid-sleep.target` (since it causes issues with Fn keys and sound)
4. Disable the Fn-Lock in UEFI/BIOS settings (since it no longer works after hibernation)

This workaround give two alternatives for suspension : the default sleep mode, that leads to ~20-30% battery drain overnight, and hibernation for longer period. The Fn keys keep their functionality (e.g. brightness, volume, etc) but you will loose the Fn-Lock feature (with Fn+Esc).

**Comment by franckgaga** [comment]
Good news, I found a better workaround with trial and error :alembic: !
I disabled "Intel VMD Controller" in UEFI/BIOS settings and now the default sleep mode (modern standby) leads to only ~1-3 % battery drain overnight. Thus, hibernation can be avoided and the Fn-Lock feature still works after modern standby. I will close this issue.

**Comment by gop9000** [comment]
But what can you say about possible overheating when the laptop is stored e.g. in a backpack?

**Comment by franckgaga** [comment]
I've never experienced overheating when the lid is closed. I did have some issue with connected Bluetooth devices that inhibit the modern standby, but it did not cause significant heating problems, only a higher battery drain. You still have hibernation for longer periods that works well (except for the Fn-Lock) and guarantees no overheating/battery drain.

**Comment by encrustace** [comment]
> Good news, I found a better workaround with trial and error ⚗️ ! I disabled "Intel VMD Controller" in UEFI/BIOS settings and now the default sleep mode (modern standby) leads to only ~1-3 % battery drain overnight. Thus, hibernation can be avoided and the Fn-Lock feature still works after modern standby. I will close this issue.
> 
> edit : woah, there is even an ~1-2 h battery life gain on normal load without Intel VMD. I highly recommand to disable Intel VMD on asus zenbook !!

Thank You So much, now my power drop is below 3W per hour which is awesome before it was 6-7W per hour (I have laptop-mode enabled I'm using Arch Linux)
