### ISSUE TITLE
Cryt unlock wizard will not allow me to unlock the machine 

### ISSUE THREAD

**Issue by cameronaaron** [pop-os/pop#222]
**Distribution - (run ```cat /etc/os-release```)**
Serval WS (serw11) with POP os 17.10
 
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
I reinstalled but now I am stuck on the crypt unlock screen. I am entering my key but it is not even recognizing that I am typing at all after following this guide:
https://support.system76.com/articles/encryption-bug/
ref https://bugs.launchpad.net/ubuntu/+source/plymouth/+bug/1386005
My system now boots up to a blank screen

**Steps to reproduce (if you know)**
1. Go through setup 
2. On setup screen select enable disk encryption
3. On reboot you will be unable to get into the system anymore because the splash screen will not allow you to enter your password or even recognize your typeing 

4. follow this guide https://support.system76.com/articles/encryption-bug/
5 will reboot to nothingness 

**Expected behavior**
Be able to type in password and use computer 

**Other Notes**

**Comment by mmstick** [comment]
> POP os 17.10

Try out the new 18.04 ISO.

**Comment by cameronaaron** [comment]
Thanks does appear ti be fixed
