### ISSUE TITLE
[Suggestion] Add a desktop entry for repoman package for managing system repositories

### ISSUE THREAD

**Issue by tur1ngb0x** [pop-os/pop#2224]
**Distribution:**

```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Suggestion:**
Add a desktop entry for `repoman` package in `/usr/share/applications` for easier management of apt, flatpak, snap repositories

```
$ cat /usr/share/applications/repoman.desktop
[Desktop Entry]
Comment=Manage system repositories
Exec=repoman
Icon=repoman
Name=Repoman
Type=Application
```

**Screenshots:**
![repoman](https://user-images.githubusercontent.com/25666761/155183188-90817515-ef4e-4cf2-8af3-925c0e3191f5.png)

![repoman](https://user-images.githubusercontent.com/25666761/155183701-b0bdea68-0d1c-4842-ab48-f7f6db94f106.png)

**Comment by isantop** [comment]
Repoman in Pop is not intended to be a standalone application, and we explicitly disable the desktop entry for it. There are not currently plans to change this.
