### ISSUE TITLE
Can't open steam anymore

### ISSUE THREAD

**Issue by tin-pham** [pop-os/pop#2225]
Distribution: PopOS 21.10
App: Steam
Bug: Can't open steam anymore
Step to reproduce: I don't know if anyone could reproduce this but just open steam
Expected behavior: It tells me that 'verifying installation' and nothing happens

It very hard to capture this
![image](https://user-images.githubusercontent.com/20679090/155231988-dc43c10d-fbc5-44f6-bd7b-2d9eb2ad1bb9.png)

Yee, it hangs but nothing happens
![image](https://user-images.githubusercontent.com/20679090/155232045-6eb455d4-8a3d-4387-aac2-36ad2a07748c.png)

I have tried to uninstall deb and install the flatpack instead, I am able to open it once, but after closing it like this again, I even remove the ~/.steam, but no luck

**Comment by leviport** [comment]
21.04 is EOL. I'd recommend updating to 21.10 as soon as possible.

**Comment by tin-pham** [comment]
> 21.04 is EOL. I'd recommend updating to 21.10 as soon as possible.

![image](https://user-images.githubusercontent.com/20679090/155233675-e7fab7e6-1b53-4a52-8e4b-0f42a4fd4bf7.png)

My apologies, I used 21.10, I forgot about that, I updated the post above

**Comment by tin-pham** [comment]
> 

That post from from reddit is mine haha, thanks mate. But I think I will wait for the fix, because hybrid mode is smooth but when I alt tab between workspace or do something it very laggy

**Comment by leviport** [comment]
A gnome-shell update to fix this bug on 21.10 has just been released. Let us know if it clears up the issue for you.

**Comment by tin-pham** [comment]
> A gnome-shell update to fix this bug on 21.10 has just been released. Let us know if it clears up the issue for you.

Yesss, they fixed it thanks god.
