### ISSUE TITLE
libnvidia-fbc1-510 NVIDIA showing update Notification all time

### ISSUE THREAD

**Issue by smk97** [pop-os/pop#2233]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
libnvidia-fbc1-510 NVIDIA OpenGL-based Framebuffer Capture runtime library Version: 510.54-1pop0~1645719405~21.10~10b5fec

**Issue/Bug Description:**

The above mentioned package update notification is being shown all the time by PopShop. 
It is not getting updated as well. 
Not showing apt autoremove also.

**Steps to reproduce (if you know):**
Just boot the system.

**Expected behavior:**
1) Successful package update
2) Update notification should not be shown for the package after the update
3) At least should be able to do apt autoremove if it is not required.

**Other Notes:**

**Comment by atreya2011** [comment]
I am having the same issue as well. Clicking on the `Update` button does nothing.
![Screenshot from 2022-02-27 13-08-21](https://user-images.githubusercontent.com/44151328/155867855-3a1eb1f1-ec2d-4dd2-a8cd-37c7e511778b.png)

**Comment by atreya2011** [comment]
Seems to have disappeared...

**Comment by smk97** [comment]
![image](https://user-images.githubusercontent.com/64006261/155885531-7ec3be27-5332-4fe7-9cc4-cb77b0802e16.png)


Still able to see ....

**Comment by goolash761** [comment]
Having the same exact problem, and now I have an update for nvidia that will not install because it has a dependency on this update.

**Comment by jimdolmas** [comment]
> Try running `sudo apt remove '*nvidia*470*'` and then try updating.

Just encountered this problem today, and your suggestion worked for me.

**Comment by eventhorizon02** [comment]
Thanks, worked for me too
