### ISSUE TITLE
Pop os bad at detecting if windows os is present 

### ISSUE THREAD

**Issue by cameronaaron** [pop-os/pop#224]
*Distribution - (run ```cat /etc/os-release```)**

 Serval WS (serw11) 17.10
 

**Issue/Bug Description**
 trying to reinstall the OS  but I get this error "Force UEFI Installation?". why though I don't have windows. This message is an error 

**Steps to reproduce (if you know)**
Reinstall pop 
get the false UEFI error 

**Expected behavior**
Should be able to accurately detect things.

**Other Notes**

**Comment by im7FFY** [comment]
This is cause of the fact that windows want to be the only operating system installed and they even don't want you to like,  grab an external HDD and boot windows on it... Windows is really a shitty OS!

**Comment by mmstick** [comment]
Closing due to being a 17.10 issue with Ubiquity.
