### ISSUE TITLE
Blank icon in about

### ISSUE THREAD

**Issue by Oridaro** [pop-os/pop#2241]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Hi! In settings, section about, there is a blank icon instead of PopOS logo
![Zrzut ekranu z 2022-03-06 17-27-04](https://user-images.githubusercontent.com/101059356/156933139-0a0aeaf8-1971-4811-ad5b-73acb8e7be3c.png)

**Comment by leviport** [comment]
It looks like you might be using a non-default theme. Does the logo return when setting the theme back to default?

**Comment by Oridaro** [comment]
> It looks like you might be using a non-default theme. Does the logo return when setting the theme back to default?

Unfortunately no :'(

**Comment by leviport** [comment]
Did you restart gnome-shell after restoring themes to default? Because it looks fine on the systems I've checked. Perhaps a screenshot of your Gnome Tweaks settings would help?
![2022-03-11_07-42](https://user-images.githubusercontent.com/13512097/157889184-1c6aa913-3b38-4741-8359-c13135c8fbbd.png)

**Comment by Oridaro** [comment]
Huh weird. the issue still exists, even after reboot with default appearance
![Zrzut ekranu z 2022-03-11 22-06-41](https://user-images.githubusercontent.com/101059356/157966893-b1a6bda4-cbed-42d6-b02a-252e7c39273d.png)
![Zrzut ekranu z 2022-03-11 22-07-16](https://user-images.githubusercontent.com/101059356/157966908-2f503540-7f7a-4bf9-b16d-77d9989c62f0.png)

.

**Comment by leviport** [comment]
Neither of those pictures show default Pop theming. This is what those settings should be set to, and then you should try restarting Gnome Shell.
![2022-03-11_14-55](https://user-images.githubusercontent.com/13512097/157976965-ec9a75fd-55f2-4191-b035-a7e44d6233bb.png)

**Comment by Oridaro** [comment]
I know. I'm just showing what i've got as a custom theme. The white one was made when all themes was set to pop.

**Comment by leviport** [comment]
Custom themes are known to cause the Pop logo to not appear in the Settings > About screen. The white theme you have pictured is not the light Pop theme either.

**Comment by Oridaro** [comment]
I see. Thank you for answer!
