### ISSUE TITLE
Night Light in dual monitor setup only applies to one

### ISSUE THREAD

**Issue by serkor1** [pop-os/pop#2245]
```
NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**

Night Light only applies to one of my two monitors. Both are `ASUS PG32UQ`

**Steps to reproduce (if you know):**

I tried to boot into my windows partition, and night light works out of the box in that partition.

**Other Notes:**

Only one of my monitors are shown in the color profile section.

**Comment by DevSallSa** [comment]
I have the same problem here with my laptop and my dual monitor (both `Dell S2421HSX`)
The night light effect applies only on my laptop screen and not on my monitors

**POP_OS!**: 21.10 impish
**Host**: Dell XPS 13 7390 2-in-1
**CPU**: Intel i7-1065G7
**GPU**: Intel Iris Plus graphics G7
**RAM**: 8GB

**Comment by leviport** [comment]
I'm still unable to replicate this behavior. Is it still an issue on 22.04?

**Comment by clarkhenry** [comment]
Same here, this is still an issue. Easy to reproduce with dual external monitors.

Work-around: just use `redshift`.

`sudo apt install redshift`

You can use redshift config files, or run `redshift -O 3500K` from the terminal, for example. It matters where your terminal is placed to apply the filter to either one monitor or all monitors.

**Comment by serkor1** [comment]
@clarkhenry I suspect that this is a issue with Ubuntu. The same issue persists there, and in all of its derivatives that I have tested. Namely, Zorin OS and Ubuntu.

**Comment by albert-tomanek** [comment]
> @clarkhenry I suspect that this is a issue with Ubuntu. The same issue persists there, and in all of its derivatives that I have tested. Namely, Zorin OS and Ubuntu.

This is an issue on Fedora 37 (GNOME 43.6) as well.

**Comment by DevSallSa** [comment]
For those who are still facing this issue.

If you're using a display Link compatible dock for your monitors, then it is the cause of the issue.
After some research (done in the past), I discovered that displaylink's linux drivers doesn't support night light for now (june 2024).

I tried to connect one of my monitor to my laptop using HDMI and night light worked.

**Comment by hoangcuongzk1** [comment]
i am using HDMI to connect to my laptop. Dell U32 4k
Reconnect, reboot, etc ... but still NOT HAVE Night Light.
It only has Night Light at Build-in Monitor.
Ubuntu 24.04

**Comment by nicarettajp** [comment]
> i am using HDMI to connect to my laptop. Dell U32 4k Reconnect, reboot, etc ... but still NOT HAVE Night Light. It only has Night Light at Build-in Monitor. Ubuntu 24.04

Same issue, Ubuntu 24.04 LTS. Using Redshift until it's fixed.

**Comment by sl1pstream** [comment]
same issue here. identical monitors, both DP, only primary gets night shift.

Will try out redshift, or just stick to no night shift

**Comment by seedspaul** [comment]
AMD R9 5950x
AMD 7900 XT

DP from both display directly to GPU (no docks)

Still broken in 24.04 lts xorg & 26.04 lts wayland
