### ISSUE TITLE
Pop OS 21.10 Sluggish, Slow After 2022-03-11 Updates

### ISSUE THREAD

**Issue by ganakee** [pop-os/pop#2250]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Firefox 98, GNOME apps, Thunderbird 91.5.0, Evolution
All applications appear affected.

Current kernel (this appears to have been updated with the recent updates)
uname -r
5.16.11-76051611-generic

nvidia-smi
Tue Mar 15 15:59:17 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
| 43%   50C    P1    N/A /  N/A |    421MiB /  1991MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Issue/Bug Description:**
After POP SHOP standard updates during week of 2022-March-11, overall system sluggishness, apps run slowly, poor screen repaints, and overall poor performance. Apparent updates included Firefox 98 and a Linux Kernel update.

The problem occurs on two very different systems--an older laptop (i5, 8GB RAM, SSD) and a newer desktop (i7, 32GB RAM, SSDs, NVidia Card).

**Steps to reproduce (if you know):**
Reboot after updates caused sluggishness.

**Expected behavior:**
Pop OS 21.10 fine before updates with pre-issue snappy performance. Notable sluggishness, chunky display elements, and overall slow performance after updates.

**Other Notes:**
Tried several things to try to fix.

1. Use ALT+F2 and r to restart GNOME periodically--no help.
2. Reset Firefox. No help.
3. Installed and used Stacer to remove old cached materials. No help.
4. Installed (temporarily) Chromium. Also affected by sluggishness and no real help (also sluggish but less sluggish than Firefox 98. (Tried to rule-out Firefox itself.)
5. On laptop, removed old kernels and manually updated initramfs. No help.
6. Ran several speed tests for internet connectivity. (Just to verify. All apps, not just internet-enabled, are affected but trying to rule-out causes.) Speed test fine. NOTE: direct CAT6 cabled connections. Not a WIFI issue.
7. Rebooted several times. No help.

**Comment by leviport** [comment]
Should this issue be closed then?

**Comment by ganakee** [comment]
Yes. This has been stable for about two weeks at least. Thank you for looking at it.
