### ISSUE TITLE
Launcher not showing anything (Pop Shell and Pop Launcher compiled from source)

### ISSUE THREAD

**Issue by yusi1** [pop-os/pop#2260]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Void"
ID="void"
PRETTY_NAME="Void Linux"
HOME_URL="https://voidlinux.org/"
DOCUMENTATION_URL="https://docs.voidlinux.org/"
LOGO="void-logo"
ANSI_COLOR="0;38;2;71;128;97"

DISTRIB_ID="void"
```

 
 
**Related Application and/or Package Version:**
Pop shell and launcher compiled from source since Void Linux does not package Pop OS GNOME extensions.

**Issue/Bug Description:**
When pressing the keybind to activate Pop Launcher `Super + /` it doesn't show anything, it only shows the search bar.

**Steps to reproduce (if you know):**
- Compile and install Pop Shell from source
- Activate the Pop Shell extension in GNOME extension settings app
- Logout and log back in for the extension to be activated properly
- Press `Super + /` to activate the Pop Launcher
- Observe that only the search bar is shown

**Expected behavior:**
Applications, running applications, etc.. are shown and can be searched through / executed.

**Other Notes:**
Not using a distro packaged version of Pop Shell, it is compiled from source.
Also the same with Pop Launcher which I also had to compile from source.

**Images for further context:**
![Screenshot from 2022-03-22 09-41-34](https://user-images.githubusercontent.com/82241382/159451951-fc455336-27b2-4110-ba81-365b5f633c7d.png)

**Comment by yusi1** [comment]
Noticed a similar issue that someone else had when Spotify was opened, but for me it happens everytime.
https://github.com/pop-os/shell/issues/1208

**Comment by mmstick** [comment]
> Noticed a similar issue that someone else had when Spotify was opened, but for me it happens everytime, even if all applications are closed.
> https://github.com/pop-os/shell/issues/1208

Do you have pop-launcher installed?

**Comment by yusi1** [comment]
> > Noticed a similar issue that someone else had when Spotify was opened, but for me it happens everytime, even if all applications are closed.
> > [pop-os/shell#1208](https://github.com/pop-os/shell/issues/1208)
> 
> Do you have pop-launcher installed?

yes I built that from source too and installed it but running `pop-launcher` in the terminal doesn't do anything

**Comment by yusi1** [comment]
FYI: I haven't installed COSMIC or any other COSMIC components.

**Comment by mmstick** [comment]
If you run `pop-launcher` from a terminal, can you query anything with a search like `{"Search":"Firefox"}`?

**Comment by yusi1** [comment]
I ran: `pop-launcher {"Search":"Firefox"}`
It doesn't seem to do anything, no output in the terminal, nothing.

**Comment by mmstick** [comment]
Then the plugins may not be installed correctly. Did you install them with the makefile?

**Comment by yusi1** [comment]
yes

**Comment by yusi1** [comment]
Closing issue as I've found an alternative application launcher that is packaged on my distro and is close enough to the Pop Launcher, plus I won't need to compile from source.

**Comment by gnomo223** [comment]
I was experiencing your problem and could solve it by building the launcher from source

**Comment by Abel808** [comment]
My super key is not working is there any way to reassign the shortcut to another key ?

**Comment by felixhatesbugs** [comment]
> Closing issue as I've found an alternative application launcher that is packaged on my distro and is close enough to the Pop Launcher, plus I won't need to compile from source.

name?

**Comment by yusi1** [comment]
> > Closing issue as I've found an alternative application launcher that is packaged on my distro and is close enough to the Pop Launcher, plus I won't need to compile from source.
> 
> name?

I'm pretty sure it was called ULauncher.
