### ISSUE TITLE
GNOME Weather 42.0 on POP OS 21.10 Via Flatpak Now Fails to Use POP OS Dark Theme

### ISSUE THREAD

**Issue by ganakee** [pop-os/pop#2265]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
GNOME Weather 42.0 installed via POP SHOP Flatpak.

**Issue/Bug Description:**
The newly updated GNOME Weather 42.0 (from 41.0) via flatpak fails to apply the POP OS Dark Mode/Theme.

**Steps to reproduce (if you know):**
PO Shop update.
Update GNOME Weather.

**Expected behavior:**
GNOME Weather should use the POP OS Dark Mode Theme.

**Other Notes:**
This is specific to the new Weather 42.0. Weather 41.0 was fine and properly applied the POP OS Theme/Mode.

I note this as a **canary issue** because Weather 42 apparently uses GNOME GTK 42 via flatpak. If this app's themeing is broken, others may also break as GNOME apps update to to GNOME 42.

**Comment by ganakee** [comment]
Thanks for looking at it. This may portend more issues as apps update to GNOME 42. Ironically, the release notes for Weather 42.0 extol the new dark theme. I tried several "tricks" posted online such as flatpak overrides etc. but nothing solves the issue.

**Comment by ganakee** [comment]
Thank you.
I followup with a related question On POP OS, I cannot downgrade the flatpak org.gnome.Weather app no matter what I do. (This is a vision issue and having the bright, glaring white suddenly appear exacerbates a vision issue.) 

You should be able to issue 
`sudo flatpak update -v --commit=92c42fd2e7cefc91a817f50c14dd2e8fe2ad54e4c457596463c717e5b5a933c9 org.gnome.Weather`
to downgrade from the problematic Version 42 to the stable version 41.

When I issue this command, however, I get a persistent error:
```
sudo flatpak update -v --commit=92c42fd2e7cefc91a817f50c14dd2e8fe2ad54e4c457596463c717e5b5a933c9 org.gnome.Weather
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /root/.local/share/flatpak
Looking for updates…
error: org.gnome.Weather not installed
```

I have tried uninstalling the problematic flatpak and various names but nothing will install--the same error occurs stating that weather is not installed when it is:
`flatpak list `
verifies that Weather is installed (and at version 42.0) and results in 
```
...
Weather     org.gnome.Weather      42.0       stable     flathub   user
...
```

I verified the hash using 
`flatpak remote-info --log flathub org.gnome.Weather`

Stuck with why I cannot downgrade (this is basic flatpak functionality) because Flatpak reports that the org.gnome.Weather app is not installed. Even if I try older commits using different hashes, none (that I tried) installed with the same error.

Flatpak notes these downgrade procedures at [](https://docs.flatpak.org/en/latest/tips-and-tricks.html)

**Comment by jacobgkau** [comment]
Pop!_OS uses user-mode Flatpaks, and running with sudo would be a different user than your own account. What does the command output when you run it without sudo?

**Comment by ganakee** [comment]
Ack. Well now I feel like a total incompetent but **thank you** @jacobgkau for the lightening quick response. 
Yes, that was the issue with installing. I am trying it now.

Yep, running as a user instead worked.
If anyone else encounters this, the correct command on POP OS to downgrade a flatpak is:
flatpak update -v --commit=92c42fd2e7cefc91a817f50c14dd2e8fe2ad54e4c457596463c717e5b5a933c9 org.gnome.Weather

Thanks for the quick response.
