### ISSUE TITLE
Bluetooth not found, firmware-atheros, card qualcomm-atheros QCA9565-AR9565

### ISSUE THREAD

**Issue by taveiracoder** [pop-os/pop#2267]
I used google translate to make this post, so thanks for understanding the language errors.
My problem is that, after the last Pop!_OS system updates, both in version 20.04lts and 21.10, bluetooth doesn't work anymore. It doesn't even recognize the presence of the bluetooth card.  It only shows the message on the screen "Bluetooth not found". I've already ruled out a defect in it because it works on other systems. My card is a Qualcomm Atheros QCA9565-AR9565. In the output of lshw the driver for it is ath9k, and in the pop repo is available ath9k-htc. But even with him it didn't work. On other occasions I would solve this by installing the firmware-atheros, but it is not available in the official Pop!_OS repos.

![Captura de tela de 2022-03-31 18-09-29](https://user-images.githubusercontent.com/88001258/161153195-a516250a-79a6-49d1-944c-b6784aa28a12.png)
![Captura de tela de 2022-03-31 18-08-17](https://user-images.githubusercontent.com/88001258/161153269-fa54a175-b20c-4949-91e9-643056e8d933.png)
.

**Comment by charleswesleybotchwey** [comment]
same problem here

**Comment by taveiracoder** [comment]
In this link: https://support.system76.com/articles/bluetooth. An article was made available with the download link for other versions of linux-firmware. To help with our bluetooth issues. In my case I solved it with a previous version of the package, but a newer version is also available which has not yet entered the repository and can be installed with dpkg.

**Comment by leandrodias95** [comment]
I'm with the same problem

**Comment by taveiracoder** [comment]
> I'm with the same problem

https://plus.diolinux.com.br/t/nao-foi-encontrado-bluetooth-pop-os/43991/9?u=andretaveira

**Comment by taveiracoder** [comment]
> I used google translate to make this post, so thanks for understanding the language errors. My problem is that, after the last Pop!_OS system updates, both in version 20.04lts and 21.10, bluetooth doesn't work anymore. It doesn't even recognize the presence of the bluetooth card. It only shows the message on the screen "Bluetooth not found". I've already ruled out a defect in it because it works on other systems. My card is a Qualcomm Atheros QCA9565-AR9565. In the output of lshw the driver for it is ath9k, and in the pop repo is available ath9k-htc. But even with him it didn't work. On other occasions I would solve this by installing the firmware-atheros, but it is not available in the official Pop!_OS repos.
> 
> ![Captura de tela de 2022-03-31 18-09-29](https://user-images.githubusercontent.com/88001258/161153195-a516250a-79a6-49d1-944c-b6784aa28a12.png) ![Captura de tela de 2022-03-31 18-08-17](https://user-images.githubusercontent.com/88001258/161153269-fa54a175-b20c-4949-91e9-643056e8d933.png) .

Here is the solution to this problem. It's in Brazilian Portuguese, because I posted it in a community here in Brazil.
https://plus.diolinux.com.br/t/nao-foi-encontrado-bluetooth-pop-os/43991/9?u=andretaveira

**Comment by leandrodias95** [comment]
I solved with apt-mark hold linux-kernel. I did download of older kernel
and back to version before actual.

Em sáb, 9 de abr de 2022 17:27, André Taveira ***@***.***>
escreveu:
