### ISSUE TITLE
Is wayland now the default in 18.04 LTS?

### ISSUE THREAD

**Issue by enilsen16** [pop-os/pop#227]
**Reporter info**

```
 * Distribution - Pop OS 18.04 LTS
```

**Issue/Bug Description**

```
~ loginctl                       
   SESSION        UID USER             SEAT             TTY             
         2       1000 e                seat0            tty2            
        c1        118 gdm              seat0            tty1            

2 sessions listed.
~ loginctl show-session 2 -p Type
Type=wayland
~ loginctl show-session c1 -p Type
Type=wayland

```

**Other Notes**

After installing latest iso (version 15), today I noticed that now wayland seems to be the default. Where as when I was using pop os installed via version 13 of the iso, I didn't have a problem opening x11 applications.

**Comment by jackpot51** [comment]
Thanks for reporting this. We enabled the use of wayland, but were not intending to make it the default. Updates will be coming that change the default to Xorg, but you are free to use Wayland if you wish.
