### ISSUE TITLE
Busybox error

### ISSUE THREAD

**Issue by A-childs-encyclopedia** [pop-os/pop#2271]
I downloaded the latest Nvidia iso from the pop os website and flashed it with etcher. I was able to install it but after I clicked reboot it just throws me into busybox. How do I fix this?

**Comment by A-childs-encyclopedia** [comment]
Reddit post for more context and images
:-
[https://www.reddit.com/r/pop_os/comments/tos6hh/please_help/?utm_medium=android_app&utm_source=share](see link)

**Comment by mmstick** [comment]
The message states that it cannot find the encrypted partition. There is something wrong with the state of the system's encrypted install, but I can't be sure what. Either reinstall or reinstall without encryption.

**Comment by A-childs-encyclopedia** [comment]
That's the first thing I tried

**Comment by A-childs-encyclopedia** [comment]
> Either reinstall or reinstall without encryption.

That's the first thing I tried

**Comment by A-childs-encyclopedia** [comment]
nvm. it works now.

note to self:- don't use the nvidia iso
