### ISSUE TITLE
Apt keys stored in trusted.gpg kering

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/pop#2276]
**Distribution (run `cat /etc/os-release`):**
 Pop!OS 22.04
 
 **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
apt version 2.4.3

**Issue/Bug Description:**
`sudo apt update` issues warnings with both the `apt.pop-os.org/proprietary` and `apt.pop-os.org/release` InRelease keys are stored in the /etc/apt/trusted.gpg keyring (see DEPRECATION section in apt-key(8) for details.

**Steps to reproduce (if you know):**
`sudo apt update`

**Expected behavior:**
No errors

**Other Notes:**
Save Pop!OS pub key in `/etc/apt/trusted.gpg.d/` or `/etc/apt/keyrings/`
Use of `/etc/apt/keyrings/` will likely need updates to reference `Signed-By` in the repository setup.

**Comment by jackpot51** [comment]
Fixed in https://github.com/pop-os/default-settings/pull/135
