### ISSUE TITLE
Issue booting Pop!_OS with live ISO (Intel/AMD & NVIDIA)

### ISSUE THREAD

**Issue by NewEve** [pop-os/pop#228]
Booting on the booting Pop!_OS with live ISO (Intel/AMD & NVIDIA) gets stuck as this point (see image below).

Only difference in-between Intel/AMD & NVIDIA ISO is it flickers on the latter ISO.

This is using a Dell XPS 9650.

![img_1640](https://user-images.githubusercontent.com/29798378/39400089-d9fae49c-4b29-11e8-98a6-c0aaa9860215.JPG)

**Comment by andersab** [comment]
Same thing in virtualbox...
![virtualbox_pop-18 04-intel](https://user-images.githubusercontent.com/931507/39402245-e41b07ba-4b27-11e8-99f2-5bca0861b726.png)
