### ISSUE TITLE
Window Tile | Switching work space with 2 external monitors, only 1 will switch.

### ISSUE THREAD

**Issue by bahtioraliev** [pop-os/pop#2280]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Tile windows 

**Issue/Bug Description:**

Switching working spaces when 2 external monitors connected, only 1 will switch (from 3 monitors, 1 monitor laptop and 2 external monitors).

**Steps to reproduce (if you know):**

Install the latest popOS
Connect 2 external monitors to laptop via thunderbolt docking station. The issue appear a few months ago, previously it worked fine when all monitors will switch to the next work space. 

**Expected behavior:**

That all windows will switch together instated of only 1 monitor.

**Comment by leviport** [comment]
Can you double check the Settings > Desktop > Workspaces > Multi-Monitor Behavior setting? Sounds like it might be set to "Primary Display Only"

![2022-04-12_09-30](https://user-images.githubusercontent.com/13512097/163001722-022b716f-63e0-4535-859c-7a0587142d68.png)

**Comment by bahtioraliev** [comment]
@leviport yes, you are correct. 
Maybe we can improve the terminology, or adding a small animation?

**Comment by leviport** [comment]
Sorry, I don't follow. Do you mean that this setting needs to be clearer?

"Workspaces span displays" is the default setting on Pop, so I'm not sure users will change that setting unless they know what it does and want to override it.

**Comment by bahtioraliev** [comment]
Thank you for your help. 
Closing.
