### ISSUE TITLE
Selection is too dim  when using Dark Mode and when the Applications menu is activated

### ISSUE THREAD

**Issue by ssoufi-code** [pop-os/pop#2282]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Selection is too dim when using Dark Mode  and when theApplications menu is activated

**Steps to reproduce (if you know):**
Use Dark Mode
press super key

**Expected behavior:**
Lighten up the selected option

**Other Notes:**
![Screenshot from 2022-04-13 16-36-01](https://user-images.githubusercontent.com/85808224/163286739-3466007f-e16f-4e14-9be6-f82ac46a2730.png)

**Comment by leviport** [comment]
Kinda looks like a custom theme problem. Can you share a screenshot of the "Appearance" section of Gnome Tweaks?

**Comment by ssoufi-code** [comment]
![image](https://user-images.githubusercontent.com/85808224/163300037-517809bf-7ccd-49cc-b174-5e07aec02d3b.png)

**Comment by ssoufi-code** [comment]
I have not installed a custom theme

**Comment by leviport** [comment]
Hmm, something must be different. This is what a fresh Pop 21.10 install looks like for me:
![2022-04-13_20-15](https://user-images.githubusercontent.com/13512097/163300768-c8bc690b-6860-4aae-8487-e680f9dd2463.png)

What else is different from a fresh install?

**Comment by ssoufi-code** [comment]
Linux version 5.16.15-76051615-generic (jenkins@warp.pop-os.org) (gcc (Ubuntu 11.2.0-7ubuntu2) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.37) #202203161444~1647964027~21.10~e706226 SM
This wasn't like this yesterday and I just updated it today
I also have this extension installed [CPU Power Manager](https://extensions.gnome.org/extension/945/cpu-power-manager/)

**Comment by mircea-mihail** [comment]
How did you solve this problem? Happened to me as well today.
