### ISSUE TITLE
[Request:] a System76/Staging repo that can be used as a source for daily proposed-devel upgrades (Like a Canary Ring vs Beta)

### ISSUE THREAD

**Issue by Daasin** [pop-os/pop#2284]
Requesting for Pop to have a higher up or early testing option before Public Beta's like Ubuntu's Rolling Rhino or Fedora's Rawhide or Manjaro's Unstable/Testing Branch as opposed just the Public Beta Builds that are closer to release 
 
> **(Please see below for a clearer desc:)** 
 

_**Distribution (run `cat /etc/os-release`):**_ 22.04 Public Beta   **|**   _**Related Package Version:**_ N/A

**Issue/Bug Description:** Can't get proposed system packages & next/rc-kernels without manually building from alternative sources such as Ubuntu/devel, Ubuntu's Daily Canary Builds, or even manually installing dpkg's that are in Debian/Patches sources. (Although that last one seems to be something a lot of users have needed to do to install RC Kernel Header's correctly for a while now)

**Expected Behavior/Other Notes:** _To be able to get a pending image based off of the latest available code similar to_ [CDimage Source](http://cdimage.ubuntu.com/daily-canary/pending/) or [Latest QA Daily Build](http://iso.qa.ubuntu.com/qatracker/milestones/429/builds) and pulls from Ubuntu's Applied/Debian/sid series on Launchpad or even the latest from Debian. 

**Steps to reproduce (if you know):** _N/A - Not Implemented Due to currently provided image being based on 22.04's Public Beta and no automatic way to be in any 'canary ring'_ 

Not asking for daily Pop Images with latest Pull Requests (That's just an example from the Manjaro Equivalent) ...but perhaps automated on a biweekly schedule, or something similar? 
 _**Of course there would be a disclaimer saying that by design any updates from the branch will be buggy, some apps may not work such as GIMP or Virtualbox-dkms/Vmware-Modules and that it is purely for those that would want to find and test for bugs**_   
  
![image](https://user-images.githubusercontent.com/92701426/163461014-b2e43248-80e1-471f-93ca-1de8aa9ea96d.png)

**Comment by Daasin** [comment]
Or if there is something that's already built for QA, maybe released to users that would want to test for bugs every now and again?

**Comment by mmstick** [comment]
There is one, but nothing gets past without a final engineering and QA review.

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add master
```

**Comment by Daasin** [comment]
> There is one, but nothing gets past without a final engineering and QA review.
> 
> ```
> git clone https://github.com/pop-os/pop
> ./pop/scripts/apt add master
> ```

Tysm! Would this be best to add onto the pre-existing beta installation? 
 
...Or would even a normal 21.10 one "work"? 🤔  (Relatively speaking, due to its nature being more bleeding edge.) 

And sorry to ask so many questions but is there any place that prebuilt testing iso's are made? I can't remember if there was an automated system added or not 😅

**Comment by mmstick** [comment]
We've stopped pushing most updates to 21.10 since all efforts are on 22.04 right now. The only update I'd expect for 21.10 is pop-upgrade at this point. You can add that to a 22.04 install to get updates that are currently queued for release. Packages in here usually get released soon after.

**Comment by jacobgkau** [comment]
I'm going to go ahead and close this since we already have a public staging repo and our build system already makes PR testing repos available automatically, too.
