### ISSUE TITLE
DKMS module kernel compilation errors

### ISSUE THREAD

**Issue by cyberbloke** [pop-os/pop#2286]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
Bug report is incomplete. Please edit this post and fill in the issue template, then we can reopen this issue.
