### ISSUE TITLE
kernel version 5.17.1 cannot install dkms modules 

### ISSUE THREAD

**Issue by cyberbloke** [pop-os/pop#2287]
**Distribution (run `cat /etc/os-release`):**  
 NAME="Linux Mint"
VERSION="20.3 (Una)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 20.3"
VERSION_ID="20.3"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=una
UBUNTU_CODENAME=focal
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

doesn't show any thing 

**Issue/Bug Description:**
Whilre compiliig the linux kernel 5.17.1  getting the error as below:

Building module:
cleaning build area...(bad exit status: 2)
make -j8 KERNELRELEASE=5.17.1-firwire-amd -j8 TTM_NAME=amdttm SCHED_NAME=amd-sched -C /lib/modules/5.17.1-firwire-amd/build M=/var/lib/dkms/amdgpu/5.13.11.21.50-1384495/build...(bad exit status: 2)
ERROR (dkms apport): kernel package linux-headers-5.17.1-firwire-amd is not supported
Error! Bad return status for module build on kernel: 5.17.1-firwire-amd (x86_64)
Consult /var/lib/dkms/amdgpu/5.13.11.21.50-1384495/build/make.log for more information.

**Steps to reproduce (if you know):**
make install for the kernel and this will appear again...does not install DKMS

**Expected behavior:**
expected behavior would, the kernel along with DKMS module would do a install.

**Other Notes:**
i have tried to with various options shown on this topic here in this forum and still fails to install.
I have tried to install the deb packages of amdgpu+dkms on the the same kernel version and it fails install the deb package.
it comlains that the kernel does not support this DKMS.
Though i have compiled this with amdgpu modules in the config file...but to no use.
Definitely this is a very important issue as I have my servers installed with amd radeon gpu..
Thanks and I look forward to some work around and if there is a permanent fix that will be the best.

**Comment by leviport** [comment]
Sorry, I don't see what this has to do with Pop!\_OS. I'm closing this issue, but I can reopen if I'm mistaken.

**Comment by cyberbloke** [comment]
This in regards to dkms modules not being compiled in the kernel and the forum I have put the issue in the after reading the entire topic..if in a wrong forum my sincere apologies for inconvenience caused…  

-  
Pritpal S Bhogal
E: ***@***.******@***.***
P: +1-301-500-0918
