### ISSUE TITLE
"Operating System Updates" fail in the POP!_Shop

### ISSUE THREAD

**Issue by hl2guide** [pop-os/pop#2292]
**Distribution (run `cat /etc/os-release`):**
 
21.10 (64-bit) 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

The POP!_Shop app fails to install "Operating System Updates".

I've tried restarting, waiting and also running it on the command line. No fix from doing that though.

**Steps to reproduce (if you know):**

Run a system update check using the POP!_Shop app.

**Expected behavior:**

System updates download and apply, like normal.

**Other Notes:**

Error Message:

```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1988 (apt-get)
W: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```

**Comment by leviport** [comment]
Can you try again? It sounds like `apt` was busy when this was tried. The lock files prevent packages from being modified by two different processes simultaneously, as that can break the package manager.

**Comment by hl2guide** [comment]
> Can you try again? It sounds like `apt` was busy when this was tried. The lock files prevent packages from being modified by two different processes simultaneously, as that can break the package manager.

I'll try an upgrade to Pop!_OS 22.04 and see if the issue goes away.

**Comment by hl2guide** [comment]
@leviport hmmm, it's happening again in Pop!_OS 22.04. Unable to update at all now 😔

in the terminal I ran:

```
sudo apt update && sudo apt upgrade -y && flatpak update -y
```

output:

```
Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1988 (apt-get)... 543s
```

**Comment by leviport** [comment]
Did you try rebooting?
