### ISSUE TITLE
Installation: Wrong recognition of 4Kn HDD partition size.

### ISSUE THREAD

**Issue by AKmatiAK** [pop-os/pop#2296]
**Distribution (run `cat /etc/os-release`):**
 
Pop OS 22.04
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Installer

**Issue/Bug Description:**

Pop OS installer incorrectly calculates partition sizes on 2TB 4Kn sector size disk, looks like it assumes it's composed of 512b sectors, and says EFI partition is too small (real size: 520mb, displayed size: about 64mb if I remember correctly - 8 times smaller).

**Steps to reproduce (if you know):**

Possible probably only on 4Kn disks

**Expected behavior:**

Proper calculation of disk size and ability to install

**Comment by AKmatiAK** [comment]
also side question: can I encrypt installation when using advanced installation without configuring lvm? In installer, when I try to mount my encrypted partition it says no LVM detected, and I read that when using advanced install there's no encryption prompt.

**Comment by jacobgkau** [comment]
The first issue seems like a duplicate of https://github.com/pop-os/distinst/issues/177.

To answer your second question, the installer will only set up encryption for you if you use the default partition layout. https://github.com/pop-os/distinst/pull/286 may make it easier to have custom encrypted setups if it's merged.

**Comment by AKmatiAK** [comment]
Ok so I'm closing this issue because duplicate.
