### ISSUE TITLE
Dash to Dock appearance persists after Pop!_OS 22.04 upgrade uninstalls the extension

### ISSUE THREAD

**Issue by gridlocdev** [pop-os/pop#2298]
**Distribution:**
 Pop!_OS 22.04 LTS
 
 
**Related Application:**
Cosmic Dock

**Issue/Bug Description:**
After upgrading to Pop!_OS 22.04 (from Pop!_OS 20.04), any extension settings from the GNOME extension "Dash to dock" still persist, and overrides the Cosmic Dock extension's settings.

**Steps to reproduce:**
Using an installation of Pop!_OS 20.04 with the GNOME extension "Dash to dock" installed and some settings tweaked (such as setting the dock's background opacity), upgrade to Pop!_OS 22.04.

![image](https://user-images.githubusercontent.com/60323737/165208644-b061983a-d606-4c5e-81ab-58d58bb85664.png)

**Expected behavior:**
I would expect that once my GNOME extensions are uninstalled during the system upgrade, any side-effects that the GNOME extensions might have had are also removed.

Specifically, GNOME extension settings in `/org/gnome/shell/extensions/<extension-name>` for any extensions that were uninstalled during the system upgrade (particularly, dash to dock) are reset, and the backup is still stored in `~/.local/share/gnome-shell/extensions.bak`.

**Other Notes:**

I actually was able to manually fix this on my own machine by running `dconf reset -f /org/gnome/shell/extensions/dash-to-dock/`. 
> This command fully resets the contents of the "dash-to-dock" shell config directory to the default state (which is empty) and restores the appearance of the dock to the Cosmic Dock settings.

![image](https://user-images.githubusercontent.com/60323737/165212970-e2d4ffce-cdc0-4f0d-96fb-a661538e47a9.png)

**Comment by ydhnwb** [comment]
Thanks! your solution to do this
```
dconf reset -f /org/gnome/shell/extensions/dash-to-dock/
```

 works for me

**Comment by rakitanc** [comment]
H

> **Distribution:** Pop!_OS 22.04 LTS
> 
> **Related Application:** Cosmic Dock
> 
> **Issue/Bug Description:** After upgrading to Pop!_OS 22.04 (from Pop!_OS 20.04), any extension settings from the GNOME extension "Dash to dock" still persist, and overrides the Cosmic Dock extension's settings.
> 
> **Steps to reproduce:** Using an installation of Pop!_OS 20.04 with the GNOME extension "Dash to dock" installed and some settings tweaked (such as setting the dock's background opacity), upgrade to Pop!_OS 22.04.
> 
> ![image](https://user-images.githubusercontent.com/60323737/165208644-b061983a-d606-4c5e-81ab-58d58bb85664.png)
> 
> **Expected behavior:** I would expect that once my GNOME extensions are uninstalled during the system upgrade, any side-effects that the GNOME extensions might have had are also removed.
> 
> Specifically, GNOME extension settings in `/org/gnome/shell/extensions/<extension-name>` for any extensions that were uninstalled during the system upgrade (particularly, dash to dock) are reset, and the backup is still stored in `~/.local/share/gnome-shell/extensions.bak`.
> 
> **Other Notes:**
> 
> I actually was able to manually fix this on my own machine by running `dconf reset -f /org/gnome/shell/extensions/dash-to-dock/`.
> 
> > This command fully resets the contents of the "dash-to-dock" shell config directory to the default state (which is empty) and restores the appearance of the dock to the Cosmic Dock settings.
> 
> ![image](https://user-images.githubusercontent.com/60323737/165212970-e2d4ffce-cdc0-4f0d-96fb-a661538e47a9.png)

Hi there..So i actually didn't know that after the upgrade all the gnome extension will be removed. Is there a way to get back all the extensions with there setting. It would really mean a lot if you can help me here

**Comment by gridlocdev** [comment]
@rakitanc I would try a few things:

1. Check to make sure the extensions you had are supported on GNOME 42 (E.g. Dash to Dock is not)
2. If it is supported, check to see if your extensions' settings are located in the directory `~/.local/share/gnome-shell/extensions.bak` 
3. If it's in the above directory, re-install the extension and then you might be able to just copy the necessary files per extension from there into `/usr/share/gnome-shell/extensions`. 
   > _Note: If the extension version you install is significantly newer and incompatible with the settings from your old installation, this may not work. If that happens, you may just need to manually re-do all of the settings you previously had._

You can view installed gnome shell extensions in a few ways:

- Shell: `gsettings get org.gnome.shell enabled-extensions` and `gsettings get org.gnome.shell disabled-extensions`
- Website: https://extensions.gnome.org/ with the appropriate browser extension
- [Gnome Extension Manager](https://github.com/mjakeman/extension-manager): Installing the "Extension Manager" community application from the Pop!_Shop

**Comment by rakitanc** [comment]
> @rakitanc I would try a few things:
> 
> 1. Check to make sure the extensions you had are supported on GNOME 42 (E.g. Dash to Dock is not)
> 2. If it is supported, check to see if your extensions' settings are located in the directory `~/.local/share/gnome-shell/extensions.bak`
> 3. If it's in the above directory, re-install the extension and then you might be able to just copy the necessary files per extension from there into `/usr/share/gnome-shell/extensions`.
>    > _Note: If the extension version you install is significantly newer and incompatible with the settings from your old installation, this may not work. If that happens, you may just need to manually re-do all of the settings you previously had._
> 
> You can view installed gnome shell extensions in a few ways:
> 
> * Shell: `gsettings get [org.gnome.shell](http://org.gnome.shell) enabled-extensions` and `gsettings get [org.gnome.shell](http://org.gnome.shell) disabled-extensions`
> * Website: https://extensions.gnome.org/ with the appropriate browser extension
> * [Gnome Extension Manager](https://github.com/mjakeman/extension-manager): Installing the "Extension Manager" community application from the Pop!_Shop

![photo_2022-07-10_14-10-12](https://user-images.githubusercontent.com/64612555/178138417-f2ce989e-e9fa-4e13-ace6-96d0666e2b18.jpg)

After upgrading to Pop 21.04..This shows up when i am rebooting the pc..But if i do manually with button it boot normally. Please help

**Comment by gridlocdev** [comment]
@rakitanc I'm not sure what's going on there, but if it only started after doing the steps I suggested up there you could always just do the _opposite_ of the steps I suggested above (which might involve uninstalling the gnome extension, then changing the files back to the orientation they were before)

If that doesn't work, I would recommend looking through System76's Pop!_OS Incomplete Upgrade documentation here: https://support.system76.com/articles/pop-incomplete-upgrade/
