### ISSUE TITLE
Custom Partitioning allows for overwrite of liveusb

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#23]
_From @brs17 on October 11, 2017 19:58_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
During installation when choosing to custom partition the drives, the liveusb drive is listed and can be reformatted. This should not be allowed.

**Steps to reproduce (if you know)**
Choose to custom partition the drives in Ubiquity. Notice that /dev/sdb(most likely) is the liveusb drive.

**Expected behaviour**
Mounted drives running the live-cd should not be listed as a possible install medium.

**Other Notes**

_Copied from original issue: pop-os/iso#142_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
