### ISSUE TITLE
4-fingers touchpad gesture stop working after modifications in gnome extensions

### ISSUE THREAD

**Issue by franckgaga** [pop-os/pop#2302]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
If i toggle (disable and enable) any **manually installed** gnome extensions in "Extensions" settings e.g. [Bluetooth Quick Connect](https://extensions.gnome.org/extension/1401/bluetooth-quick-connect/), the touchpad gesture stop working afterward. I need to logout and login to make them work again.

**Steps to reproduce (if you know):**
1. Test any 4-fingers drag gesture on the touchepad (i.e. switch workspace)
2. Open "Extensions"
3. Toggle any installed gnome extension
4. Re-test any 4-fingers drag gesture

**Expected behavior:**
It should works after toggling gnome extension (same thing after extension update)

**Other Notes:**
![image](https://user-images.githubusercontent.com/34136215/165343229-11376fa5-1326-496e-b78f-ab881f208cba.png)

**Comment by franckgaga** [comment]
Weird, can no longer reproduce today. Maybe an update corrected the bug. I will wait a bit and close the issue if it doesn't come back.

**Comment by franckgaga** [comment]
Cannot reproduce since about 2-3 weeks. It seems that one of the update fixed the issue. I will close this issue.

**Comment by Novaturiente** [comment]
I am also having the same issue. Os is updated to latest version. 4 finger gesture to open app menu and switch workspace are working when Bluetooth quick connect is active. The 4 finger swipe to show the overview is not working. 
It is working when the extension is disable.

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
