### ISSUE TITLE
Cannot Open Any Popup From Top Bar When Fullscreen Mode on Second Monitor

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/pop#2306]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
I have laptop running on PopOS 22.04 and second monitor. When I open browser on second monitor and watch youtube in full screen mode, the top bar on primary display will not give you popup when clicked (Date popup, battery, option, etc. Basically everything that clicked on top bar). I need to exit from fullscreen mode on second monitor, then my top bar will works (show popup when clicked).

**Steps to reproduce (if you know):**
Connect to second monitor then go to fullscreen mode on youtube in second monitor. After that, click date/battery/option that available on top bar in your primary display. It will have no effect.

**Expected behavior:**
Should give the effect/popup

**Other Notes:**
Happens on: youtube
not happens on: google meet

**Comment by linuxgnuru** [comment]
This might be an issue with gnome, if you open a terminal and hit F11 to go into full screen mode, do you also not see the pop up notification?

**Comment by ydhnwb** [comment]
Yes. I can see popup when terminal is on full screen mode in second monitor. So far it was only happens for videos like youtube, twitch, twitter etc.
