### ISSUE TITLE
How to turn off upgrade to upgrade to pop 22.04 notification?

### ISSUE THREAD

**Issue by ApproximateIdentity** [pop-os/pop#2309]
I tried the following:

```
$ pop-upgrade release dismiss
checking if pop-upgrade requires an update
Only LTS releases may dismiss notifications
```

I looked online, but found nothing beyond that command which doesn't seem to work. I do not wish to upgrade. How to I remove this notification?

edit: The following is my system:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 21.10
Release:	21.10
Codename:	impish
```

**Comment by mmstick** [comment]
Only LTS releases may dismiss the notification

**Comment by ApproximateIdentity** [comment]
> Only LTS releases may dismiss the notification

Could you please add in the same functionality for non-LTS versions? I mean seriously there are issues about the upgrade being broken all over the issues in this repo. I don't even understand why you would display the notification for anyone until things work as expected.

Besides restricting to LTS versions makes no sense at all. I could sort of understand the idea of not allowing dismissal once support has ended, but support for 21.10 isn't over yet. Why wouldn't you respect a user's wishes in this instance?

**Comment by ApproximateIdentity** [comment]
> Only LTS releases may dismiss the notification

Regardless of your policies for the OS in general, you could possibly still help me out. I tried disabling the pop-upgrade server as in this thread

https://github.com/pop-os/upgrade/issues/235

but the service was re-enabled on the next boot. If you know what one must to do to keep it disabled, I would appreciate the information. If not, I guess I can continue hacking at it and post the solution for others who are looking to fix this bug in pop os themselves.

**Comment by ApproximateIdentity** [comment]
Actually scratch that I figured out how to disable it. For anyone else curious, the following worked for me:

```
sudo systemctl mask pop-upgrade.service
```

**Comment by jacobgkau** [comment]
> I mean seriously there are issues about the upgrade being broken all over the issues in this repo. I don't even understand why you would display the notification for anyone until things work as expected.

This is a repo issue tracker, it will only ever contain issues. There are many more successful upgrades than failed ones. The notifications _are_ only pushed when upgrades are working as expected as tested by a dedicated QA team with an ever-growing variety of configurations.

> I could sort of understand the idea of not allowing dismissal once support has ended, but support for 21.10 isn't over yet.

Once support has ended, other issues start to pop up. Some of them, like Ubuntu moving their repositories from `us.archive.` to `old-releases.`, are outside the control of Pop!_OS entirely; while we're still able to push updates to Pop!_OS packages after that since moving off of Launchpad, we are then fighting against a system frozen in time at a point where none of the other parties (Ubuntu, PPA maintainers, etc) have any inclination to monitor or fix issues. You are more likely to have problems upgrading if you wait until after end-of-support, which is why it's recommended to upgrade sooner than that.

**Comment by ApproximateIdentity** [comment]
> This is a repo issue tracker, it will only ever contain issues. There are many more successful upgrades than failed ones. The notifications are only pushed when upgrades are working as expected as tested by a dedicated QA team with an ever-growing variety of configurations.

Why not allow your users to decide the level of risk they're comfortable with?

> Once support has ended, other issues start to pop up. Some of them, like Ubuntu moving their repositories from us.archive. to old-releases., are outside the control of Pop!_OS entirely; while we're still able to push updates to Pop!_OS packages after that since moving off of Launchpad, we are then fighting against a system frozen in time at a point where none of the other parties (Ubuntu, PPA maintainers, etc) have any inclination to monitor or fix issues. You are more likely to have problems upgrading if you wait until after end-of-support, which is why it's recommended to upgrade sooner than that.

Seriously it's been out a couple of days. How about you show just a little respect for your users' wishes?

Either way it's fine. Masking the unit file isn't that hard so those who wish can do so if they find this thread or figure it out on their own. Seems weird you wouldn't just make it an option without forcing people to jump through such hoops.
