### ISSUE TITLE
Not be able to finish boot from pendrive

### ISSUE THREAD

**Issue by Corsseir** [pop-os/pop#231]
Picture worth more than a thousand words:

![20180428_234210](https://user-images.githubusercontent.com/11137173/39401178-4b1aec66-4b3f-11e8-8107-fd0f09ba6e20.jpg)

**Comment by Corsseir** [comment]
Yep, I wanted to switch from Ubuntu to Pop OS as my main operating system for daily web development but I will rethink it - especially that they have published stable release day after roadmap deadline. They have said that more time is necessary for tests. Well, that didn't help I guess.

**Comment by jmilne22** [comment]
Same issue here on my xps 13 9360 with the 8th Gen Intel processor.

**Comment by matfantinel** [comment]
Having same issue. Dell Vostro with NVidia GeForce 830m, 5th gen i7 processor

**Comment by billdote** [comment]
Same issue on System76 Gazelle.

**Comment by jackpot51** [comment]
Which ISO did you use, and what software did you use to write it?

**Comment by jmilne22** [comment]
I can't get either ISO to boot on anything I try. My dell Optiplex 710 also
wont boot using either the nvidia or intel iso's

Tried writing with Etcher first, then gnome disks and also switched uefi
off and on for each try.

**Comment by andersab** [comment]
Same issue on Virtualbox on both nvidia and intel.
![virtualbox_pop-18 04-intel](https://user-images.githubusercontent.com/931507/39402240-c9b62198-4b27-11e8-92ab-ed0fdb83420f.png)

**Comment by billdote** [comment]
I'm using the Intel ISO. I've tried Etcher on Linux and Rufus on my Windows
10 machine.

**Comment by matfantinel** [comment]
I'm also running the Intel ISO, wrote the USB drive with Deepin's Boot Maker.

**Comment by jackpot51** [comment]
I have identified the issue in the latest ISO. A fix will be available as soon as possible.

**Comment by jackpot51** [comment]
There was a packaging mistake that has been corrected here: https://github.com/pop-os/session/commit/8c552505d5223c04e2c57c52bdd607cf3335721c

A new ISO will be built very soon to fix the issue.

**Comment by besser** [comment]
Good to know that this issue have a fix, I've got too this same issue on my notebook  with hybrid video card Intel/Nvidia, is a Dell Inspiron 7460.

**Comment by jackpot51** [comment]
The builds are happening now, should be ready in about 30 minutes.

**Comment by jackpot51** [comment]
Fixed in ISO #17. Please open new issues if there are remaining problems.

**Comment by Corsseir** [comment]
Thank you for this fix. I have already tested PopOS 18.04. The best distro I have ever used.
