### ISSUE TITLE
Issue After Upgrading to Pop OS 22.04

### ISSUE THREAD

**Issue by rbharathkumar** [pop-os/pop#2312]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```shell
**apt policy swtpm**
swtpm:
  Installed: 0.6.0-1~impish1.2
  Candidate: 0.6.3-0ubuntu3
  Version table:
     0.6.3-0ubuntu3 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
 *** 0.6.0-1~impish1.2 100
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

- After the update to Pop OS 22.04, I am having issues with the following.
- Unable to update `swtpm`
- Broken package - `libdvd-pkg`

I have already tried the steps given in the below link
https://support.system76.com/articles/package-manager-pop/

I have also manually tried to reinstall, purge swtpm but I have not had any success.

**Steps to reproduce (if you know):**
- Update Pop OS to 22.04
- Try performing upgrade using below commands.
```shell
sudo apt update
sudo apt full-upgrade
  ```
- I am receiving the below error message.
```shell
sudo apt full-upgrade 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  swtpm
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
6 not fully installed or removed.
Need to get 0 B/47.5 kB of archives.
After this operation, 93.2 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
(Reading database ... 283380 files and directories currently installed.)
Preparing to unpack .../swtpm_0.6.3-0ubuntu3_amd64.deb ...
Unpacking swtpm (0.6.3-0ubuntu3) over (0.6.0-1~impish1.2) ...
dpkg: error processing archive /var/cache/apt/archives/swtpm_0.6.3-0ubuntu3_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/swtpm/libswtpm_libtpms.so.0.0.0', which is also in package swtpm-libs:amd64 0.6.0-1~imp
ish1.2
Errors were encountered while processing:
 /var/cache/apt/archives/swtpm_0.6.3-0ubuntu3_amd64.deb
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.3.orig.tar.bz2: OK
libdvd-pkg: `apt-get check` failed, you may have broken packages. Aborting...
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
**Expected behavior:**
Update should complete as expected.

**Other Notes:**
This is a dual boot machine with Windows 10

**Comment by linuxgnuru** [comment]
The swtpm-libs package isn't in the standard repositories; was a PPA added for this package? If so, you may need to first uninstall that package before the swtpm package can be upgraded.

**Comment by rbharathkumar** [comment]
Hi @linuxgnuru ,
you were absolutely spot on.
The package was part of the quickemu PPA. I followed the steps mentioned in one of the issues on their github page and I was able to get it upgraded as expected. 

Now only the following issue still remains

```shell
libdvd-pkg: Checking orig.tar integrity...
/usr/src/libdvd-pkg/libdvdcss_1.4.3.orig.tar.bz2: OK
libdvd-pkg: `apt-get check` failed, you may have broken packages. Aborting...
```

Is there something we can do for this ?
Appreciate all the help...Thank you very much....

**Comment by Seibz** [comment]
https://support.system76.com/articles/upgrade-pop/
