### ISSUE TITLE
Xorg crashed with SIGSEGV when using the RADEON driver - please help with Launchpad Bug #1970473

### ISSUE THREAD

**Issue by tulpina** [pop-os/pop#2315]
Please confirm and solve:
https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-ati/+bug/1970473

It affect Pop_os because it is based on Xorg

Thank you!

**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by Seibz** [comment]
If booting into Pop!_OS 22.04 in a gnome session running x11, does changing your screen orientation crash the system?

I have not seen this on my Ryzen 7 4700 pang10 nor Ryzen 9 4900H G5 15 SE.

**Comment by tulpina** [comment]
Yes, booting into Pop!_OS 22.04 in a gnome session running x11 crashed with these tested devices:

1. Advanced Micro Devices, Inc. [AMD/ATI] Caicos [Radeon HD 6450/7450/8450 / R5 230 OEM]
2. Advanced Micro Devices, Inc. [AMD/ATI] Kaveri [Radeon R7 Graphics] (rev d7)
3. Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 01)

**Comment by linuxgnuru** [comment]
Are you running the Pro drivers or just the kernel / mesa ones?

**Comment by Seibz** [comment]
May we have a video or the journalctl log? You can attach those by dragging and dropping them to a response.
`sudo journalctl > journalctl.log` could get that log

**Comment by tulpina** [comment]
> Are you running the Pro drivers or just the kernel / mesa ones?

Just kernel drivers.



> May we have a video or the journalctl log? You can attach those by dragging and dropping them to a response. `sudo journalctl > journalctl.log` could get that log
[journalctl.zip](https://github.com/pop-os/pop/files/8588211/journalctl.zip)

Yes, please find attached.

Video here
https://drive.google.com/file/d/1PQUSLhDckcbZ5nYtLIwJ8atFLW6D_104/view?usp=sharing

**Comment by linuxgnuru** [comment]
Could you attach the file stated from this error message?

`(EE) Please also check the log file at "/home/daniel/.local/share/xorg/Xorg.0.log" for additional information.`

**Comment by tulpina** [comment]
[xorg.zip](https://github.com/pop-os/pop/files/8596245/xorg.zip)

**Comment by tulpina** [comment]
No, I discover this using Ubuntu 22.04 live, so I did not install anything.

lun., 2 mai 2022, 19:35 John Wiggins ***@***.***> a scris:

**Comment by Seibz** [comment]
If you do an install of Ubuntu 22.04 or Pop!_OS 22.04 using the updated ISOs available, let us know if you experience that crash.

**Comment by tulpina** [comment]
I have pop_os update with latest software and the Bug îs still prezent.
Ubuntu is using Wayland when installed and it's not relevant. I'm waiting
for a real fix crom developers, no work around. The Bug is conformer on
Launchpad

lun., 2 mai 2022, 21:06 Seibz ***@***.***> a scris:

**Comment by linuxgnuru** [comment]
As this bug is upstream in Ubuntu, I'll be closing this
