### ISSUE TITLE
Previosuly focused window in a workspace not focused upon switching to a workspace with no window and then going to a workspace with atleast one window

### ISSUE THREAD

**Issue by Manish0925** [pop-os/pop#2316]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pop-shell:
  Installed: 1.1.0\~1649099191\~22.04\~cb76a4c
  Candidate: 1.1.0\~1649099191\~22.04\~cb76a4c
  Version table:
 *** 1.1.0~1649099191\~22.04\~cb76a4c 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Upon switching to a workspace with no window, and returning to a workspace containing atleast one window, the previously focused window in the workspace no longer remains focused, unless explicitly clicked on. 

**Steps to reproduce (if you know):**
* Open any application in the current workspace (if no window exists in the current workspace) and switch focus to it (automatically done if it's the only window in the workspace)
* Switch to a workspace containing no windows
* Return back to the original workspace
* Previously focused window in the workspace no longer focused, unless explicitly clicked on

**Expected behavior:**
* The previously focused window in the workspae should remain focused upon returning to it from a workspace containing no windows

**GIF demo**
![output](https://user-images.githubusercontent.com/56510798/165633282-6447b15c-6708-452e-8784-02891d15eb53.gif)

**Comment by linuxgnuru** [comment]
It looks like this is upstream from Gnome.  I found this issue which looks like the same as this one.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5410

**Comment by linuxgnuru** [comment]
This might be fixed in an upcoming update.

https://github.com/pop-os/shell/pull/1408
