### ISSUE TITLE
Unable to install pulseaudio

### ISSUE THREAD

**Issue by deanfourie1** [pop-os/pop#2324]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Unable to install pulseaudio using APT

**Steps to reproduce (if you know):**

sudo apt install pulseaudio

**Expected behavior:**

**Other Notes:**

ERROR

root@dean-surface-dedain:/home/dean# sudo apt install pulseaudio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Conflicts: pulseaudio
               Recommends: firefox but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
               Conflicts: pulseaudio:i386
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by mmstick** [comment]
Pulseaudio is deprecated in 22.04. Pipewire is the audio server now.
