### ISSUE TITLE
The alt+tab window/app switcher icons are not visible in pop-shell

### ISSUE THREAD

**Issue by beunerd** [pop-os/pop#2335]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pop-shell:
  Installed: 1.1.0~1649099191~22.04~cb76a4c
  Candidate: 1.1.0~1649099191~22.04~cb76a4c
  Version table:
 *** 1.1.0~1649099191~22.04~cb76a4c 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

No icons or other visual indicators appear when using alt+tab to toggle between applications and window. I just upgraded from 21.10, where the switcher looked [something like this](https://ubuntuhandbook.org/wp-content/uploads/2019/02/alttab-app2window.jpg). I have assigned the Alt+Tab combination shortcut to the "Switch Windows" option in keyboard settings, but have also tried with the shortcut assigned to "Switch Applications":

![image](https://user-images.githubusercontent.com/13452062/166122017-873ed2a4-609b-413c-bfe7-3fb4e9b0dfbb.png)

I am able to switch between applications and windows, though unpredictably because there is no indication of the logic or how many windows are open of which types.

**Steps to reproduce (if you know):**

Upgrade from Pop!_OS 21.10 to 22.04. Set keyboard shortcut for "Switch Windows" or "Switch Applications" to "Alt+Tab". Press Alt+Tab -- you will see that the active window can be switched, but there isn't any visual indication.

**Expected behavior:**

As noted in the description, I would expect to see something like this:

![image](https://ubuntuhandbook.org/wp-content/uploads/2019/02/alttab-app2window.jpg)

**Other Notes:**

**Comment by linuxgnuru** [comment]
Do you have any gnome-shell extensions? Are you running in x11 or wayland?

**Comment by beunerd** [comment]
@linuxgnuru, thanks for the quick response!

I have gnome shell extensions entirely disabled, and running in x11.

**Comment by linuxgnuru** [comment]
Are you holding down the alt key while pressing the tab key? What do you have Switch applications to and does that behave in the same way?

**Comment by beunerd** [comment]
I just fresh-installed 22.04 - the problem is no more! Thanks again.
