### ISSUE TITLE
temperater hot after update , and wyhy u r not sending error logs to github . then u would know all erorrs :(

### ISSUE THREAD

**Issue by marcinCrypto** [pop-os/pop#2337]
**Distribution (run `cat /etc/os-release`):**
 
 cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

top - 09:12:29 up 3 days, 18:36,  1 user,  load average: 0.49, 0.79, 0.83
Tasks: 261 total,   1 running, 260 sleeping,   0 stopped,   0 zombie
%Cpu(s): 11.1 us,  6.3 sy,  3.2 ni, 77.8 id,  1.6 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :   7772.7 total,    162.3 free,   2188.8 used,   5421.5 buff/cache
MiB Swap:   4095.5 total,   3754.2 free,    341.2 used.   5018.5 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
   3291 mar5      20   0 4169312 604156 162956 S  37.5   7.6   1999:37 firefox
 382904 mar5      39  19  256.2g  25380  22928 S  18.8   0.3   0:00.03 baloo_f+
   1902 root      20   0  358476  84956  59300 S   6.2   1.1  79:56.53 Xorg
   2004 mar5      20   0    8232   4028   3792 S   6.2   0.1   0:01.34 dbus-da+
   2042 mar5      -2   0 4602232 234260  55232 S   6.2   2.9  46:50.75 gnome-s+
   2063 mar5      20   0  332116  17056   6600 S   6.2   0.2   1:09.66 ibus-da+
   2169 mar5      39  19  256.2g  32692  21772 S   6.2   0.4   1:27.17 baloo_f+
 378337 root      20   0       0      0      0 I   6.2   0.0   0:11.12 kworker+
 382658 root      20   0       0      0      0 I   6.2   0.0   0:00.62 kworker+
 382901 mar5      20   0   22632   4048   3332 R   6.2   0.1   0:00.01 top
      1 root      20   0  170332  11640   6684 S   0.0   0.1   0:17.17 systemd
      2 root      20   0       0      0      0 S   0.0   0.0   0:00.10 kthreadd
      3 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_gp
      4 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 rcu_par+
      6 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker+
      9 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 mm_perc+
     10 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tas+
     11 root      20   0       0      0      0 S   0.0   0.0   0:00.00 rcu_tas+
     12 root      20   0       0      0      0 S   0.0   0.0   0:07.20 ksoftir+
     13 root      20   0       0      0      0 I   0.0   0.0   5:24.59 rcu_sch+
     14 root      rt   0       0      0      0 S   0.0   0.0   0:01.38 migrati+
     15 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_in+
     16 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/0
     17 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/1
     18 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_in+
     19 root      rt   0       0      0      0 S   0.0   0.0   0:00.93 migrati+
     20 root      20   0       0      0      0 S   0.0   0.0   0:04.95 ksoftir+
     22 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker+
     23 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/2
     24 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_in+
     25 root      rt   0       0      0      0 S   0.0   0.0   0:01.21 migrati+
     26 root      20   0       0      0      0 S   0.0   0.0   0:04.80 ksoftir+
     28 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker+
     29 root      20   0       0      0      0 S   0.0   0.0   0:00.00 cpuhp/3
     30 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 idle_in+
     31 root      rt   0       0      0      0 S   0.0   0.0   0:00.94 migrati+
     32 root      20   0       0      0      0 S   0.0   0.0   0:36.01 ksoftir+
     34 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kworker+
     35 root      20   0       0      0      0 S   0.0   0.0   0:00.00 kdevtmp+
     36 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 netns
     37 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 inet_fr+
     38 root      20   0       0      0      0 S   0.0   0.0   2:08.54 kauditd
     39 root      20   0       0      0      0 S   0.0   0.0   0:00.33 khungta+
     40 root      20   0       0      0      0 S   0.0   0.0   0:00.00 oom_rea+
     41 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 writeba+
     42 root      20   0       0      0      0 S   0.0   0.0   0:16.39 kcompac+
     43 root      25   5       0      0      0 S   0.0   0.0   0:00.00 ksmd
     44 root      39  19       0      0      0 S   0.0   0.0   0:00.00 khugepa+
     91 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kintegr+
     92 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kblockd
     93 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 blkcg_p+
     95 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 tpm_dev+
     96 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 ata_sff
     97 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 md
     98 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 edac-po+
     99 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 devfreq+
    100 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 watchdo+
    102 root       0 -20       0      0      0 I   0.0   0.0   0:06.53 kworker+
    104 root      20   0       0      0      0 S   0.0   0.0   0:20.85 kswapd0
    105 root      20   0       0      0      0 S   0.0   0.0   0:00.00 ecryptf+
    107 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kthrotld
    109 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 acpi_th+
    110 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 vfio-ir+
    114 root       0 -20       0      0      0 I   0.0   0.0   0:04.75 kworker+
    115 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 ipv6_ad+
    117 root       0 -20       0      0      0 I   0.0   0.0   0:03.92 kworker+
    125 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kstrp
    128 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 zswap-s+
    134 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 charger+
    184 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 cryptd
    205 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    206 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    207 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    208 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    209 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    210 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    211 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    212 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    213 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    214 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    215 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    216 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    223 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 card0-c+
    224 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 card0-c+
    225 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 card0-c+
    226 root       0 -20       0      0      0 I   0.0   0.0   0:03.91 kworker+
    254 root      20   0       0      0      0 S   0.0   0.0   0:00.00 scsi_eh+
    255 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 scsi_tm+
    256 root      20   0       0      0      0 S   0.0   0.0   0:15.12 usb-sto+
    257 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 uas
    285 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 raid5wq
    389 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kdmflush
    397 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kcryptd+
    398 root       0 -20       0      0      0 I   0.0   0.0   0:00.08 kcryptd+
    399 root      20   0       0      0      0 S   0.0   0.0   0:17.80 dmcrypt+
    402 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kdmflush
    451 root      20   0       0      0      0 S   0.0   0.0   0:16.43 jbd2/dm+
    452 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 ext4-rs+
    501 root      19  -1  274200 175232 173412 S   0.0   2.2  11:50.75 systemd+
    534 root      20   0   25268   7100   3264 S   0.0   0.1   0:01.40 systemd+
    539 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop0
    559 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop2
    581 root       0 -20       0      0      0 S   0.0   0.0   0:00.02 loop3
    583 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop4
    584 root       0 -20       0      0      0 S   0.0   0.0   0:00.01 loop5
    590 root       0 -20       0      0      0 S   0.0   0.0   0:00.01 loop6
    591 root       0 -20       0      0      0 S   0.0   0.0   0:00.03 loop7
    592 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop8
    593 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop9
    594 root       0 -20       0      0      0 S   0.0   0.0   0:00.02 loop10
    595 root       0 -20       0      0      0 S   0.0   0.0   0:00.09 loop11
    596 root       0 -20       0      0      0 S   0.0   0.0   0:00.02 loop12
    598 root       0 -20       0      0      0 S   0.0   0.0   0:00.02 loop13
    602 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop14
    613 root       0 -20       0      0      0 S   0.0   0.0   0:00.01 loop15
    618 root     -51   0       0      0      0 S   0.0   0.0   0:00.00 irq/32-+
    619 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop16
    637 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 cfg80211
    753 root       0 -20       0      0      0 I   0.0   0.0   0:00.03 kworker+
    755 root       0 -20       0      0      0 I   0.0   0.0   0:52.21 kworker+
    899 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kdmflush
    901 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kcryptd+
    902 root       0 -20       0      0      0 I   0.0   0.0   0:00.00 kcryptd+
    904 root      20   0       0      0      0 S   0.0   0.0   0:00.17 dmcrypt+
    922 systemd+  20   0   25308  12152   8020 S   0.0   0.2   0:47.84 systemd+
    927 systemd+  20   0   91220   4932   4144 S   0.0   0.1   0:05.62 systemd+
   1038 root      20   0  248972   7408   6520 S   0.0   0.1   0:09.54 account+
   1039 root      20   0    2528    924    852 S   0.0   0.0   0:01.73 acpid
   1041 avahi     20   0    9416   3488   3148 S   0.0   0.0   0:05.48 avahi-d+
   1042 root      20   0    9392   4932   4560 S   0.0   0.1   0:00.03 bluetoo+
   1044 root      20   0   19184   2960   2700 S   0.0   0.0   0:00.62 cron
   1048 message+  20   0   10860   6120   3756 S   0.0   0.1  10:28.99 dbus-da+
   1050 root      20   0  273560  17816  14116 S   0.0   0.2  24:45.94 Network+
   1054 root      20   0   82784   3716   3384 S   0.0   0.0   0:22.46 irqbala+
   1056 root      20   0   50020  18548  11092 S   0.0   0.2   0:00.13 network+
   1059 root      20   0  251884  11132   7404 S   0.0   0.1   0:04.95 polkitd
   1062 root      20   0  363744   5768   3520 S   0.0   0.1   0:27.01 pop-upg+
   1072 syslog    20   0  221128   4824   3348 S   0.0   0.1   0:06.98 rsyslogd
   1085 root      20   0 1317176  23812   8484 S   0.0   0.3   1:29.92 snapd
   1086 root      20   0  245356   6216   5668 S   0.0   0.1   0:00.06 switche+
   1087 root      20   0  356892   5900   5224 S   0.0   0.1   3:17.07 system7+
   1091 root      20   0   17984   7012   5904 S   0.0   0.1   0:02.45 systemd+
   1092 root      20   0  137256   7604   6784 S   0.0   0.1   0:19.57 thermald
   1093 root      20   0  471824  13688   9864 S   0.0   0.2   0:26.21 udisksd
   1095 root      20   0   15116   7060   5880 S   0.0   0.1   3:19.49 wpa_sup+
   1108 avahi     20   0    9228    340      0 S   0.0   0.0   0:00.00 avahi-d+
   1152 colord    20   0  256972  14120   8896 S   0.0   0.2   0:00.27 colord
   1163 root      20   0  315032   9628   7912 S   0.0   0.1   0:00.10 ModemMa+
   1206 root      20   0  250116   8452   7276 S   0.0   0.1   0:00.10 gdm3
   1221 root      20   0       0      0      0 S   0.0   0.0   0:00.00 ath9k-h+
   1292 rtkit     21   1  153800   3124   2872 S   0.0   0.0   0:04.98 rtkit-d+
   1392 root      20   0  259704   7748   6480 S   0.0   0.1   0:00.53 upowerd
   1543 geoclue   20   0  913536  20160  11888 S   0.0   0.3   9:46.19 geoclue
   1777 root      20   0  329080  10884   8396 S   0.0   0.1   0:00.20 gdm-ses+
   1784 mar5      20   0   27752  15676   6580 S   0.0   0.2   0:36.38 systemd
   1785 mar5      20   0  108560   3228      0 S   0.0   0.0   0:00.00 (sd-pam)
   1795 mar5      20   0   97476   5592   5204 S   0.0   0.1   0:00.24 pipewire
   1796 mar5      20   0   19236   1424   1356 S   0.0   0.0   0:18.66 pop-upg+
   1797 mar5       9 -11 2018156  14700  12180 S   0.0   0.2   0:26.32 pulseau+
   1800 mar5      39  19  804124  18824  11448 S   0.0   0.2   0:47.96 tracker+
   1804 mar5      20   0   17144  13020   3864 S   0.0   0.2   0:54.65 dbus-da+
   1810 mar5      20   0   25824   5412   5224 S   0.0   0.1   0:00.01 pipewir+
   1817 mar5      20   0  249628   6812   6224 S   0.0   0.1   0:01.08 gvfsd
   1820 mar5      20   0  249996   7188   6552 S   0.0   0.1   0:01.47 gnome-k+
   1825 mar5      20   0  378344   5568   5488 S   0.0   0.1   0:00.03 gvfsd-f+
   1844 mar5      20   0  325044   9056   7632 S   0.0   0.1   0:19.18 gvfs-ud+
   1852 mar5      20   0  245584   5316   4848 S   0.0   0.1   0:00.51 gvfs-mt+
   1857 mar5      20   0  245656   5456   5232 S   0.0   0.1   0:00.50 gvfs-go+
   1861 mar5      20   0  629352  10056   9696 S   0.0   0.1   0:00.97 goa-dae+
   1873 mar5      20   0  324580   6512   6260 S   0.0   0.1   0:01.29 goa-ide+
   1884 root      10 -10       0      0      0 S   0.0   0.0   0:00.00 krfcommd
   1887 mar5      20   0  247864   5308   5084 S   0.0   0.1   0:00.51 gvfs-gp+
   1894 mar5      20   0  324104   6184   5852 S   0.0   0.1   0:15.94 gvfs-af+
   1900 mar5      20   0  174668   6212   5968 S   0.0   0.1   0:00.02 gdm-x-s+
   1932 mar5      20   0  199136   9608   9212 S   0.0   0.1   0:00.03 gnome-s+
   1993 mar5      20   0    6040     56      0 S   0.0   0.0   0:01.63 ssh-age+
   1999 mar5      20   0  305388   6084   5840 S   0.0   0.1   0:00.11 at-spi-+
   2016 mar5      20   0  100708   4000   4000 S   0.0   0.1   0:00.00 gnome-s+
   2023 mar5      20   0  568952  11304   9772 S   0.0   0.1   0:02.67 gnome-s+
   2067 mar5      20   0  172500   6368   6148 S   0.0   0.1   0:00.02 ibus-me+
   2068 mar5      20   0  358448  16752  14080 S   0.0   0.2   0:07.43 ibus-ex+
   2070 mar5      20   0  354260  12720  11940 S   0.0   0.2   0:00.26 ibus-x11
   2074 mar5      20   0  246300   6652   6132 S   0.0   0.1   0:00.84 ibus-po+
   2088 mar5      20   0  163744   6872   6540 S   0.0   0.1   0:03.34 at-spi2+
   2091 mar5      20   0  245380   5800   5512 S   0.0   0.1   0:00.15 xdg-per+
   2096 mar5      20   0  581964   8900   7912 S   0.0   0.1   0:03.16 gnome-s+
   2102 mar5      20   0 1081504  12380  10808 S   0.0   0.2   0:00.67 evoluti+
   2110 mar5      20   0  156444   5880   5220 S   0.0   0.1   0:00.44 dconf-s+
   2115 mar5      20   0 1391000  13816  12240 S   0.0   0.2   0:02.29 evoluti+
   2126 mar5      20   0  790408  15060  13632 S   0.0   0.2   0:01.27 evoluti+
   2141 mar5      20   0 2746628  23824  18096 S   0.0   0.3   0:05.68 gjs
   2151 mar5      20   0  319416   5916   5636 S   0.0   0.1   0:00.16 gsd-a11+
   2152 mar5      20   0  587620  17416  14904 S   0.0   0.2   0:03.27 gsd-col+
   2154 mar5      20   0  465836  10956  10460 S   0.0   0.1   0:01.28 gsd-dat+
   2155 mar5      20   0  321816   7152   6464 S   0.0   0.1   0:23.22 gsd-hou+
   2156 mar5      20   0  354488  13780  12864 S   0.0   0.2   0:00.41 gsd-key+
   2165 mar5      20   0   19236   1644   1580 S   0.0   0.0   0:18.67 pop-upg+
   2174 mar5      20   0  959036  20632  17016 S   0.0   0.3   0:01.14 gsd-med+
   2175 mar5      20   0  428652  15972  14120 S   0.0   0.2   0:02.02 gsd-pow+
   2176 mar5      20   0  258936   8760   8208 S   0.0   0.1   0:00.22 gsd-pri+
   2177 mar5      20   0  466860   5548   5260 S   0.0   0.1   0:00.77 gsd-rfk+
   2180 mar5      20   0  245288   5820   5440 S   0.0   0.1   0:00.36 gsd-scr+
   2184 mar5      20   0  474596   9744   8720 S   0.0   0.1   2:42.68 gsd-sha+
   2189 mar5      20   0  325072   5880   5680 S   0.0   0.1   0:00.29 gsd-sma+
   2196 mar5      20   0  329984   7840   7592 S   0.0   0.1   0:00.16 gsd-sou+
   2197 mar5      20   0  428028  13100  11776 S   0.0   0.2   0:00.55 gsd-wac+
   2198 mar5      20   0  355300  12820  11572 S   0.0   0.2   0:00.56 gsd-xse+
   2205 mar5      20   0  433500  26244  20904 S   0.0   0.3   2:53.27 indicat+
   2242 mar5      20   0  268228  11640  11420 S   0.0   0.1   0:00.15 hidpi-n+
   2245 mar5      20   0  172764   6948   6388 S   0.0   0.1   0:07.62 ibus-en+
   2250 mar5      20   0  648552  21272  17608 S   0.0   0.3   0:01.10 evoluti+
   2270 mar5      20   0  521156  17892  17300 S   0.0   0.2   0:00.60 hidpi-d+
   2271 mar5      20   0  232052   5884   4872 S   0.0   0.1   0:00.31 gsd-dis+
   2323 mar5      20   0  353116  10376   9916 S   0.0   0.1   0:00.34 gsd-pri+
   2675 root      20   0  115452  31800  11992 S   0.0   0.4   0:00.90 python3
   2784 mar5      20   0  172476   6480   5616 S   0.0   0.1   0:00.42 gvfsd-m+
   2810 mar5      20   0  324260   7716   6148 S   0.0   0.1   0:01.74 gvfsd-t+
   3347 mar5      20   0  194380  27016  24464 S   0.0   0.3   0:02.70 Socket +
   3375 mar5      20   0 2509792  98516  74124 S   0.0   1.2   0:32.67 Privile+
   3524 mar5      20   0   26.5g 145896  80808 S   0.0   1.8   5:40.16 WebExte+
   4010 mar5      20   0  253536  25392  23116 S   0.0   0.3   4:52.99 RDD Pro+
   5556 mar5      20   0  447164  13480  11600 S   0.0   0.2   0:00.46 gvfsd-h+
  44356 mar5      20   0  397628   6812   6496 S   0.0   0.1   0:00.26 gvfsd-n+
  44390 mar5      20   0  325664   7092   6844 S   0.0   0.1   0:00.46 gvfsd-d+
  99637 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop18
  99813 root       0 -20       0      0      0 S   0.0   0.0   0:00.00 loop1
 105189 mar5      20   0  566404  49068  33476 S   0.0   0.6   1:43.22 gnome-t+
 105197 mar5      20   0   20756   5048   3316 S   0.0   0.1   0:00.08 bash
 110536 mar5      20   0  869216  54992  41832 S   0.0   0.7   0:01.29 gnome-c+
 111402 mar5      20   0  629088  41944  30912 S   0.0   0.5   5:50.91 baobab
 277676 mar5      20   0   20624   5016   3552 S   0.0   0.1   0:00.02 bash
 278213 root      20   0   25836   5936   4964 S   0.0   0.1   0:00.02 sudo
 278220 root      20   0  454900 157436   9132 S   0.0   2.0  53:33.69 python3
 279095 mar5      20   0 1343820 121552  44540 S   0.0   1.5   2:44.01 nautilus
 281777 mar5      20   0  551608  41624  26640 S   0.0   0.5   0:00.29 seahorse
 282882 mar5      20   0 2730616 646152  52584 S   0.0   8.1   3:29.82 io.elem+
 284065 mar5      20   0  957096 104056  77500 S   0.0   1.3   0:27.69 gnome-c+
 284900 mar5      20   0  445424  34512  14860 S   0.0   0.4   0:06.42 tracker+
 295405 root      20   0       0      0      0 I   0.0   0.0   0:10.36 kworker+
 311398 root      20   0   81324  13892  11504 S   0.0   0.2   0:00.04 cupsd
 311400 root      20   0  178932  11960  10376 S   0.0   0.2   0:00.08 cups-br+
 362819 root      20   0       0      0      0 I   0.0   0.0   0:03.67 kworker+
 365603 root      20   0       0      0      0 I   0.0   0.0   0:02.74 kworker+
 366290 root      20   0       0      0      0 I   0.0   0.0   0:00.00 kworker+
 369515 root      20   0       0      0      0 I   0.0   0.0   0:24.20 kworker+
 370005 root      20   0  396204  29184  24520 S   0.0   0.4   0:00.66 fwupd
 370866 root      20   0       0      0      0 I   0.0   0.0   0:00.00 kworker+
 372971 root      20   0       0      0      0 I   0.0   0.0   0:27.24 kworker+
 373910 root      20   0       0      0      0 I   0.0   0.0   0:23.87 kworker+
 376526 root      20   0       0      0      0 I   0.0   0.0   0:11.92 kworker+
 380368 root      20   0       0      0      0 I   0.0   0.0   0:03.64 kworker+
 381146 mar5      20   0 2773988  46764  34628 S   0.0   0.6   0:00.32 gjs
 381308 root      20   0       0      0      0 I   0.0   0.0   0:00.41 kworker+
 381309 root      20   0       0      0      0 I   0.0   0.0   0:00.00 kworker+
 381342 root      20   0       0      0      0 I   0.0   0.0   0:00.00 kworker+
 381625 root      20   0       0      0      0 I   0.0   0.0   0:02.01 kworker+
 381676 mar5      20   0 2606748 170016 111272 S   0.0   2.1   0:20.37 Web Con+
 381921 mar5      20   0   20624   5072   3428 S   0.0   0.1   0:00.02 bash
 382285 mar5      20   0   22628   4240   3340 S   0.0   0.1   0:01.19 top
 382383 root      20   0       0      0      0 I   0.0   0.0   0:00.00 kworker+
 382425 mar5      20   0 2423704  83812  69792 S   0.0   1.1   0:00.35 Web Con+

**Issue/Bug Description:**

i am using cooler but it is hard to work that way :(

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by marcinCrypto** [comment]
i do not know how to log historic temperature :( https://unix.stackexchange.com/questions/269858/does-linux-typically-log-system-temperature-data

**Comment by leviport** [comment]
> VERSION="20.10"

Pop!\_OS 20.10 has been unsupported for quite some time now. I recommend installing 22.04 LTS and seeing if the issue persists there.

It would also be useful to describe your hardware, as well as the methods with which you are measuring system temperatures. If you need a utility to help monitor them, I recommend searching for PSensor in Pop!\_Shop.

**Comment by marcinCrypto** [comment]
I did , i have 22.04 but after installing sensors it was not booting :(

**Comment by leviport** [comment]
I use `sensors` very regularly on a variety of hardware, and I have never seen a machine fail to boot after simply installing that package. I think something else is the cause.

**Comment by marcinCrypto** [comment]
re open it on 22.04 erorr exist

**Comment by marcinCrypto** [comment]
after using PSensor and other system was not working . so give me please commends do show u errors. 
2. more important decrypt partition so i can use normal operating system :(
