### ISSUE TITLE
After upgrading to 22.04, touchpad settings are not applying on Framework laptop

### ISSUE THREAD

**Issue by e-staats** [pop-os/pop#2343]
**Distribution** (run `cat /etc/os-release`): Pop OS 22.04 on Framework laptop

**Issue/Bug Description:** The touchpad settings aren't respected on my Framework after upgrading to 22.04. I have Tap to Click off and Natural Scrolling on, but the touchpad still does Tap to Click and the scroll is reversed. The settings still don't work after restarting.

**Steps to reproduce** (if you know): upgrade to 22,04 on a Framework laptop

**Expected behavior:** If Tap to Click is toggled off, tapping should not register as a click. If Natural Scrolling is on, scrolling should move the content, not the viewport.

**Comment by Seibz** [comment]
As we've moved to Gnome 42 in Pop!_OS 22.04, some previous settings may have been cleared and previous Gnome extensions may have been disabled for stability during the update process.

If you turn natural scrolling back on, and enable Tap to Click, are those working for you now?

**Comment by e-staats** [comment]
I tried putting the settings in my desired state (Tap to Click off, Natural Scrolling on) and restarting, and it still is not applying them (e.g. tapping the touchpad still clicks). No matter what I do, I can't seem to change the behavior of the touchpad. I don't think I have any other extensions or packages installed that would interfere with these settings, but let me know if there's somewhere I can look to check!

**Comment by Seibz** [comment]
Going to test a fresh 22.04 install on my Framework when I get time during work today.

**Comment by Seibz** [comment]
While I did a fresh install and not an upgrade on my Framework, Tap to Click and Natural Scrolling for the Touchpad section of settings are working fine. If you update your recovery partition via the OS & Upgrade menu, and then boot into the recovery partition by holding the spacebar at boot time, are you able to set tap to click fine in there?

More information about our recovery partition: https://support.system76.com/articles/pop-recovery/

**Comment by leviport** [comment]
It might also be worth checking whether any old Synaptic packages are installed. Someone on Mattermost had similar-sounding touchpad issues, and it turned out that some old Synaptic package had been installed at some point and was causing trouble.

**Comment by e-staats** [comment]
Booting into the recovery partition shows the settings working as expected. I don't think I have any Synaptic packages installed.

So given this, would using the Refresh OS option be my best bet?

**Comment by Seibz** [comment]
I second Levi's suggestion. If you are seeing the same anomaly on a second user account, give the Refresh OS option a shot.

**Comment by DennisFaucher** [comment]
I created a second user account and the touchpad settings will not stick there either. I cannot turn off tap to click nor disable while typing. Do I really need to wipe and recover?

**Comment by DennisFaucher** [comment]
My gsettings even report that tap to click and disable while typing are off but they are not

$ gsettings list-recursively org.gnome.desktop.peripherals.touchpad
org.gnome.desktop.peripherals.touchpad click-method 'fingers'
org.gnome.desktop.peripherals.touchpad disable-while-typing true
org.gnome.desktop.peripherals.touchpad edge-scrolling-enabled false
org.gnome.desktop.peripherals.touchpad left-handed 'mouse'
org.gnome.desktop.peripherals.touchpad middle-click-emulation false
org.gnome.desktop.peripherals.touchpad natural-scroll false
org.gnome.desktop.peripherals.touchpad send-events 'enabled'
org.gnome.desktop.peripherals.touchpad speed 0.0
org.gnome.desktop.peripherals.touchpad tap-and-drag true
org.gnome.desktop.peripherals.touchpad tap-and-drag-lock false
org.gnome.desktop.peripherals.touchpad tap-button-map 'default'
org.gnome.desktop.peripherals.touchpad tap-to-click false
org.gnome.desktop.peripherals.touchpad two-finger-scrolling-enabled true

**Comment by jthak002** [comment]
I had the same issue - I looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

**Comment by Seibz** [comment]
Refresh Install will only wipe out your installed deb applications, not flatpaks or snaps if you have applications installed there. Refresh OS will also keep your user data. Let us know if that helps.

**Comment by DennisFaucher** [comment]
I refreshed. I don't use Flatpak. I reinstalled my apps and Gnome extensions. Too bad that was necessary as the 22.04 upgrade broke the trackpad settings

**Comment by e-staats** [comment]
>  looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

This worked for me! I didn't realize that was installed or how to look for it.

I'm going to mark this as closed, since either the above workaround or the Refresh OS option should work to resolve this.

**Comment by DennisFaucher** [comment]
Outstanding. Nice work and thank you for documenting this.

**Comment by AndyCodez** [comment]
> I had the same issue - I looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

Worked for me! Thanks!

**Comment by fsevenm** [comment]
> I had the same issue - I looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

Worked for on Ubuntu 22.04 too. I almost did a fresh install. Thanks.

**Comment by hardik124** [comment]
> I had the same issue - I looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

I did this and touchpad stopped working
How can i fix this?

**Comment by niksbanna** [comment]
> I had the same issue - I looked for `synaptic` packages on my machine using `sudo apt list --installed | grep synaptic` and I found one `xserver-xorg-input-synaptics`. After running `sudo apt autoremove xserver-xorg-input-synaptics`, and restarting my computer, it fixed the issue.

after this my touchpad stopped working and I need to install same package again to use touchpad and now it's same problem again.
