### ISSUE TITLE
pop 20.10 after reistalling in pop shop i click  Update all

### ISSUE THREAD

**Issue by marcinCrypto** [pop-os/pop#2344]
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 libnss-systemd amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 libudev1 amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 udev amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 libsystemd0 amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 systemd amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 systemd-timesyncd amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 libpam-systemd amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])
E: http://us.archive.ubuntu.com/ubuntu groovy-updates/main amd64 systemd-sysv amd64 246.6-1ubuntu1.4 is not (yet) available (404  Not Found [IP: 91.189.91.39 80])

**Distribution (run `cat /etc/os-release`):**
 
 cat /etc/os-release
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
a can not resize my encrypted partition and only 50 % is used but i gparted it shows as 100 % is used :(

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
20.10 has not been supported for a long time. You will not be able to install any updates on 20.10. I recommend installing 22.04 LTS instead.

**Comment by marcinCrypto** [comment]
can u tell me why u r destroying possibility of upgrading updating? it should be possible to update ever time . when i click upgrade it break , it should the worst scenario use git version from server so it should "git pull " all data from sever and overwrite me local changes in worst scenario . so why it is not doing so ? as normal user not pop os developer i should not see any conflict. u have not also respond to my other questions  :(

**Comment by mmstick** [comment]
Ubuntu only provides 9 months of support for non-LTS releases. You have a 3 month window to upgrade to the next version before support is dropped.
