### ISSUE TITLE
Unable to install microsoft fonts through ubuntu restricted extras in pop os 22.04

### ISSUE THREAD

**Issue by antenmanuuel** [pop-os/pop#2346]
Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been  moved out of  Incoming

The following information may help to resolve the situation

The following packages have unment dependencies

debconf : Breaks update -notifier-common ( < 3.187~) but 1.0.0 ~ 1651159041~22.04~106da is to be installed
E: Broken packages

I tried manually installing by running this command sudo apt install ttf-mscorefonts-installer
but I get the same issue

**Comment by davenavas** [comment]
I've tried to install restricted extras for video codecs, and the program video cant play mp4 files. I haven't done many tests, but I think the problems might be related.

**Comment by mmstick** [comment]
This is fixed by https://github.com/pop-os/msttcorefonts
