### ISSUE TITLE
not possible upgrade from 20.10 why ? 

### ISSUE THREAD

**Issue by marcinCrypto** [pop-os/pop#2350]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by marcinCrypto** [comment]
can u tell me why u r destroying possibility of upgrading updating? it should be possible to update ever time . when i click upgrade it break , it should the worst scenario use git version from server so it should "git pull " all data from sever and overwrite me local changes in worst scenario . so why it is not doing so ? as normal user not pop os developer i should not see any conflict. u have not also respond to my other questions  :(

**Comment by leviport** [comment]
We are not "destroying the possibility". It's merely the way short term releases were designed. They follow Ubuntu's release schedule, in which even numbered years in April (ex: 18.04, 20.04, 22.04) are LTS releases, and all of the semi-annual releases in between are short term releases. Short term releases are intended to be upgraded when the next release comes out, within 3-ish months of that next release. 

20.10 was released in October of 2020, so it should have been upgraded to 21.04 when that was released. 21.04 was then superseded by 21.10, which was again superseded by 22.04, which happens to be an LTS. 

If you want a release that keeps getting updates without having to upgrade, you want an LTS release. Fortunately, 22.04 happens to be exactly that. I recommend grabbing a 22.04 iso here: https://pop.system76.com/

**Comment by marcinCrypto** [comment]
Can u add CEO people responsible for that aproche ? Why that solution is useless . It should be possible to upgrade always from user perspective . Which Linux is interested in user perspective ? Which Linux distro i do not need never to update ? And i cab update If i am interested .

**Comment by marcinCrypto** [comment]
Can u add CEO , board members it should be not. Which Linux i can always update ? Why u did not use that approach ? How to tag people there ?
