### ISSUE TITLE
installer issues

### ISSUE THREAD

**Issue by ikjelle** [pop-os/pop#2355]
**Issue/Bug Description:**
I was reinstalling pop os after something got corrupted and I couldn't fix it. So I thought I would just reinstall pop os. I used the custom option and assigned partitions myself, but ran into these things:
1. The installation failed because I didn't have a recovery partition (at least I think, it was some message about recovery, which was fixed after creating and mounting a recovery partition). This is a problem because the installer doesn't make it required, but the installation will crash on it.
2. unsquashfs gave exit code 2 and stopped the process. I fixed this by formatting all the mounts and not mounting my home partition with data (I just did it after the installation). Which raises the question, if formatting is required, why is it a choice?
3. Every time the installation failed, the option to try and change it would result in taking you a few screens back. But changing options wouldn't allow you to run it again, so I had to close the installer and re-open it.

The points are just some observations I made by reinstalling the os. I'm not sure if these are issues that are fixable or the fault of pop os as it uses the io.elementary.installer.
But I just wanted it documented. Maybe it can streamline the installation process or help someone

**Comment by mmstick** [comment]
You should attach logs from `/tmp/installer.log`

**Comment by ikjelle** [comment]
I don't have those, as I got it to work eventually. And I didn't have a way to upload those errors.
