### ISSUE TITLE
Reboot reenables mouse acceleration

### ISSUE THREAD

**Issue by sjwo** [pop-os/pop#2357]
**Distribution (run `cat /etc/os-release`):**
 ```
sjw@flip:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
sjw@flip:~$
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unknown

**Issue/Bug Description:**
After upgrading to Pop!_OS 22.04 LTS, mouse acceleration is enabled after every reboot, although the Mouse Acceleration toggle in Settings > Mouse & Trackpad > Mouse still appears disabled.

**Steps to reproduce (if you know):**
1. Upgrade from Pop!_OS 20.04 to 22.04.
2. Disable acceleration in Settings > Mouse & Touchpad > Mouse > Mouse Acceleration. Observe that the mouse moves as if acceleration is disabled.
3. Reboot.
4. Observe that mouse moves as if acceleration is enabled.
6. Temporary fix:
  a. Open Settings > Mouse & Trackpad > Mouse and first enable, then disable, the toggle for Mouse Acceleration.
  b. Observe that the mouse moves as if acceleration is disabled.

**Expected behavior:**
When the Mouse Acceleration toggle in Settings > Mouse & Trackpad > Mouse is disabled, the mouse should move as if mouse acceleration is disabled, and rebooting should not affect this.

**Other Notes:**

**Comment by linuxgnuru** [comment]
Are you observing the acceleration being enabled after loging in or at the login screen?

**Comment by sjwo** [comment]
Both, and it also turns out that simply logging out will trigger the issue without rebooting.

**Comment by sjwo** [comment]
The bug also occurs when I disconnect and reconnect my machine (laptop) from/to the USB-C dock to which the mouse is connected, without logging out, rebooting, or suspending.

**Comment by sjwo** [comment]
I believe the issue is caused by the ambiguous relationship between Gnome Tweaks > Keyboard & Mouse > Mouse > Acceleration Profile on the one hand and dconf-editor > org > gnome > desktop > peripherals > trackball on the other.

The solution is to change dconf-editor > org > gnome > desktop > peripherals > trackball > accel-profile from 'default' to 'flat'.

This seems like a Gnome issue, not a pop-os issue.
