### ISSUE TITLE
No Audio after updating packages - Pulseaudio version conflict

### ISSUE THREAD

**Issue by tnfru** [pop-os/pop#2364]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pulseaudio:
  Installed: (none)
  Candidate: 1:15.99.1+dfsg1-1ubuntu1
  Version table:
     1:15.99.1+dfsg1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
     1:15.0+dfsg1-1ubuntu2.2 -1
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

After running 
```
sudo apt-get dist-upgrade -Vy --allow-downgrades &&
sudo apt-get autoremove -y &&
sudo apt-get autoclean &&
sudo apt-get clean
```

today I was asked to restart the device to finalize the update. After the reboot no sound input device is recognized any more. After some research it turns out pulseaudio
was masked and could not be unmasked. The command ran without any problem but did not unmask it. I then tried to reinitialize it
by removing the reference to /dev/null , following [this stackoverflow answer](https://unix.stackexchange.com/a/433795) which did not fix the problem. Pulseaudio itself is no longer in PATH and seems no longer installed.

When trying to install it with `sudo apt-get install pulseaudio` I get the following:
```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Conflicts: pulseaudio
               Recommends: io.elementary.sideload but it is not installable
               Conflicts: pulseaudio:i386
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Steps to reproduce (if you know):**

The following packages were updated:
```
/var/log/dpkg.log:2022-05-05 11:00:14 install libpop-system-updater-gtk:amd64 <none> 0.1.0~1651522263~22.04~6870527
/var/log/dpkg.log:2022-05-05 11:24:31 install libgweather-4-common:all <none> 4.0.0-2
/var/log/dpkg.log:2022-05-05 11:24:31 install libgweather-4-0:amd64 <none> 4.0.0-2
/var/log/dpkg.log:2022-05-05 11:24:32 install gir1.2-gweather-4.0:amd64 <none> 4.0.0-2
/var/log/dpkg.log:2022-05-05 11:24:43 install linux-image-5.17.5-76051705-generic:amd64 <none> 5.17.5-76051705.202204271406~1651504840~22.04~63e51bd
/var/log/dpkg.log:2022-05-05 11:24:43 install linux-modules-5.17.5-76051705-generic:amd64 <none> 5.17.5-76051705.202204271406~1651504840~22.04~63e51bd
/var/log/dpkg.log:2022-05-05 11:24:50 install linux-headers-5.17.5-76051705:all <none> 5.17.5-76051705.202204271406~1651504840~22.04~63e51bd
/var/log/dpkg.log:2022-05-05 11:24:58 install linux-headers-5.17.5-76051705-generic:amd64 <none> 5.17.5-76051705.202204271406~1651504840~22.04~63e51bd
```
One of them required a reboot and after the reboot the pulseaudio seems uninstalled and can't be reinstalled.

**Expected behavior:**

Sound should still work, Pulseaudio should still be available.

**Other Notes:**

ALSA link:  http://alsa-project.org/db/?f=5904a2db9b33989ae24a63e11bc4716cd9293e05

**Comment by tnfru** [comment]
So finally found out that 22.xx runs with pipewire and not with pulseaudio. So to enable audio again if you experience this issue is to make sure pipewire is installed with `sudo apt install pipewire pipewire-audio-client-libraries`. Then you deactivate pulseaudio if active with `systemctl --user --now disable pulseaudio.service pulseaudio.socket` and then activate pipewire with `systemctl --user --now enable pipewire pipewire-pulse`. 

I still get the error though when trying to install the Bluetooth utilities with `sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}` and sound should not just be completely gone after any apt-update.

**Comment by charleskyalo** [comment]
There is another issue trying to resolve the issue but did not work out on my system 
here is the link to it https://github.com/pop-os/pop/issues/2339

**Comment by tnfru** [comment]
Closing as it is a duplicate of #2339
