### ISSUE TITLE
Unable to Right and left click inside an open windows 

### ISSUE THREAD

**Issue by seremempire** [pop-os/pop#2371]
I can access any of my application with a mouse once they open up. I have been able to open the terminal and found a persistent error involving libglib2.0-0 package. Also I tried to sudo apt remove -the package however it triggered an error message only.

I try to roll back the kennel and apt full-upgrade once again it stoped with error libglib2.0-0:i386
My system is currently unusable can somebody help.

**Comment by linuxgnuru** [comment]
How does libglib affect clicking in windows? What exactly is the issue with clicking?

**Comment by seremempire** [comment]
I not could get more info ,therefore , I went to recovery that seemed to fix it
