### ISSUE TITLE
Broken NVIDIA GPU drivers (most likely) due to recent update

### ISSUE THREAD

**Issue by JordyScript** [pop-os/pop#2373]
**Distribution:**
NAME="Pop!_OS"
VERSION="22.04 LTS"
VERSION_ID="22.04"
VERSION_CODENAME=jammy

HARDWARE_MODEL="HP HP ZBook 15 G3"
PROCESSOR="Intel® Core™ i7-6820HQ CPU @ 2.70GHz × 8 "
GRAPHICS="Nvidia Quadro M1000M"
 
**Related Application and/or Package Version:**
Unsure, probably a graphics driver. 

**Issue/Bug Description:**
I can no longer use NVIDIA graphics or hybrid graphics. Every time I try to switch from integrated graphics to any other setting and reboot, the setting reverts to integrated graphics automatically. This means I can no longer  connect to displays via HDMI or USB-C ports, which are connected to the dedicated GPU.

**Expected behavior:**
Pop!_OS is able to use NVIDIA graphics and use external displays via HDMI and USB-C. 

**Other Notes:**
This problem only started after the most recent update that required me to restart to apply. Since I have automatic updates on, I don't know which exact versions are involved. The original 22.04 OS upgrade worked flawlessly for me. Then after a few days I got another update that required me to reboot and that one broke the GPU drivers (i assume that's the problem). I didn't install or uninstall any other software, nor did I change any other settings, except for reinstalling updated versions of some Gnome Extensions.

**Comment by mmstick** [comment]
Fixed by https://github.com/pop-os/nvidia-graphics-drivers-470/pull/6

**Comment by JordyScript** [comment]
You guys are amazing! Thanks :)
