### ISSUE TITLE
bcmwl-kernel-source not properly built for 5.17.5, so no broadcom wifi after update

### ISSUE THREAD

**Issue by juanejot** [pop-os/pop#2375]
**Distribution (run `cat /etc/os-release`):*
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
bcmwl-kernel-source

**Issue/Bug Description:**
Running the updates to kernel 5.17.5 seemed to work OK, but booting cold later reveals WiFi (Old Broadcom BCM4322 I had installed bcmwl-kernel-source to use) isn't available in upper right corner menu, in Settings, and isn't connecting.
Uninstalling gets a dpkg error, solved not by `apt` but by `sudo dpkg --remove bcmwl-kernel-source`. That said, can't reinstall either, even when booting to 5.16.19 kernel. `cat /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/make.log` as suggested reveals too much technicality for me to find a culprit, other than the new kernel just doesn't like it, but see in "Steps to reproduce," below.

**Steps to reproduce (if you know):**
Following on from above, here is the make.log produce when trying to build bcmwl-kernel-source for kernel 5.17.5:

> DKMS make.log for bcmwl-6.30.223.271+bdcom for kernel 5.17.5-76051705-generic (x86_64)
Fri May  6 01:52:14 PM PDT 2022
make: Entering directory '/usr/src/linux-headers-5.17.5-76051705-generic'
CFG80211 API is prefered for this kernel version
Using CFG80211 API
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/shared/linux_osl.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:81:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_iw.h:73: warning: "isprint" redefined
   73 | #define isprint(c) bcm_isprint(c)
      | 
In file included from ./include/linux/string_helpers.h:6,
                 from ./include/linux/seq_file.h:7,
                 from ./include/linux/seq_file_net.h:5,
                 from ./include/net/net_namespace.h:183,
                 from ./include/linux/netdevice.h:37,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:69,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:27:
./include/linux/ctype.h:30: note: this is the location of the previous definition
   30 | #define isprint(c)      ((__ismask(c)&(_P|_U|_L|_D|_SP)) != 0)
      | 
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/osl.h:79,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:28:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_attach’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:645:43: warning: passing argument 1 of ‘memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  645 |         bcopy(&wl->pub->cur_etheraddr, dev->dev_addr, ETHER_ADDR_LEN);
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linux_osl.h:156:49: note: in definition of macro ‘bcopy’
  156 |         #define bcopy(src, dst, len)    memcpy((dst), (src), (len))
      |                                                 ^~~
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:22,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:65,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:40,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:27:
./include/linux/fortify-string.h:212:37: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  212 | __FORTIFY_INLINE void *memcpy(void *p, const void *q, __kernel_size_t size)
      |                               ~~~~~~^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_pci_probe’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:784:9: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
  784 |         if ((val & 0x0000ff00) != 0)
      |         ^~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:786:17: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
  786 |                 bar1_size = pci_resource_len(pdev, 2);
      |                 ^~~~~~~~~
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/osl.h:79,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:28:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_set_mac_address’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:1850:31: warning: passing argument 1 of ‘memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 1850 |         bcopy(sa->sa_data, dev->dev_addr, ETHER_ADDR_LEN);
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linux_osl.h:156:49: note: in definition of macro ‘bcopy’
  156 |         #define bcopy(src, dst, len)    memcpy((dst), (src), (len))
      |                                                 ^~~
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:22,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:65,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:40,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:27:
./include/linux/fortify-string.h:212:37: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  212 | __FORTIFY_INLINE void *memcpy(void *p, const void *q, __kernel_size_t size)
      |                               ~~~~~~^
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/osl.h:79,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:28:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘_wl_add_monitor_if’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:3026:37: warning: passing argument 1 of ‘memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3026 |         bcopy(wl->dev->dev_addr, dev->dev_addr, ETHER_ADDR_LEN);
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linux_osl.h:156:49: note: in definition of macro ‘bcopy’
  156 |         #define bcopy(src, dst, len)    memcpy((dst), (src), (len))
      |                                                 ^~~
In file included from ./include/linux/string.h:253,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/cpumask.h:5,
                 from ./arch/x86/include/asm/msr.h:11,
                 from ./arch/x86/include/asm/processor.h:22,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:65,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/include/linuxver.h:40,
                 from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:27:
./include/linux/fortify-string.h:212:37: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
  212 | __FORTIFY_INLINE void *memcpy(void *p, const void *q, __kernel_size_t size)
      |                               ~~~~~~^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_proc_read’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:3307:26: error: implicit declaration of function ‘PDE_DATA’; did you mean ‘NODE_DATA’? [-Werror=implicit-function-declaration]
 3307 |         wl_info_t * wl = PDE_DATA(file_inode(filp));
      |                          ^~~~~~~~
      |                          NODE_DATA
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:3307:26: warning: initialization of ‘wl_info_t *’ {aka ‘struct wl_info *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c: In function ‘wl_proc_write’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.c:3364:26: warning: initialization of ‘wl_info_t *’ {aka ‘struct wl_info *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 3364 |         wl_info_t * wl = PDE_DATA(file_inode(filp));
      |                          ^~~~~~~~
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_iw.o
  CC [M]  /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.o
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:288: /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_linux.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:40:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c: In function ‘wl_set_auth_type’:
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.h:52:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
   52 |         if (wl_dbg_level & WL_DBG_DBG) {                        \
      |            ^
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:794:17: note: in expansion of macro ‘WL_DBG’
  794 |                 WL_DBG(("network eap\n"));
      |                 ^~~~~~
/var/lib/dkms/bcmwl/6.30.223.271+bdcom/build/src/wl/sys/wl_cfg80211_hybrid.c:795:9: note: here
  795 |         default:
      |         ^~~~~~~
make: *** [Makefile:1837: /var/lib/dkms/bcmwl/6.30.223.271+bdcom/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.17.5-76051705-generic'

**Expected behavior:**
Connect to WiFi, as I did under all previous (kernel) versions of Pop!_OS, as long as I had bcmwl-kernel-source (successfully) installed.

**Other Notes:**
At the risk of a "BTW…" joke (particularly since I don't know enough to fully interpret the log above), on the latest Arch (with kernel 5.17.5) running off a USB on the same hardware, b43-firmware (from the AUR) appears to have no such problem getting & keeping me online. I do not believe this package to be DKMS, because other DKMS packages installed after it required me to install dkms itself along with them (the dkms package therefore not having been installed yet).

**Comment by ganakee** [comment]
I also just discovered a similar issue on an older Dell E5520 laptop. 
`lspci `reads:
0a:00.0 Ethernet controller: Broadcom Inc. and subsidiaries NetXtreme BCM5761 Gigabit Ethernet PCIe (rev 10)
Lost WIFI completely--Settings does not even have a WIFI entry. Needed to manually boot into an older kernel 5.16, which still works.

**Comment by joeinnes** [comment]
Same for me on an old Macbook Pro with a Broadcom chipset.

For future internauts with this issue (assuming it persists):

Running `sudo kernelstub -v -k /boot/vmlinuz-5.16.19-76051619-generic  -i /boot/initrd.img-5.16.19-76051619-generic` will do what @ganakee says and boot using an old kernel.

**Comment by juanejot** [comment]
Thank you to those who have added their experiences so far. My machine is in fact similar to that of @joeinnes, being a MacBookPro5,3.
I've tried a completely fresh, fully updated install (not just refreshed, but including everything up through the latest dnsmasq-base of 5/10/22), to the same result. Let me know if you want the log file from that build, though to my eye it looks the same as that above.

Again, Broadcom WiFi works on the same hardware and kernel 5.17.5-arch-1-1 using b43-firmware from the AUR, so it's not the kernel, unless it's something about System76's build of the 5.17.5 kernel. It may be the DKMS nature of the broadcom driver module, as it does not appear that b43-firmware on Arch is DKMS, but that bcmwl-kernel-source on Pop!_OS is DKMS.

I can't compare installing bcmwl-kernel-source for Ubuntu 22.04 as a base, because they're still back at kernel 5.15.x, and 5.17.5 is the first kernel for which I've had trouble installing/upgrading the broadcom driver. (Also, installing Ubuntu on this hardware would be a pain, as grub would mess up every drive connected to it! Sometimes systemd can be a pain, but at least systemd-boot leaves other drives alone!)

Hopefully something clicks as a candidate to get fixed when someone sees the above build log (or today's, upon request), as WiFi is sort of mission-critical to a laptop. In the meantime, thanks for the input I've received so far!

**Comment by TheKrafter** [comment]
I am also facing this issue on a MacbookPro 9,2. Thanks joeinnes for the help for now!
