### ISSUE TITLE
microsoft fonts not showing after installing ubuntu-restricted-extras

### ISSUE THREAD

**Issue by antenmanuuel** [pop-os/pop#2377]
I ran the command sudo apt install ubuntu-restricted-extras, the wizard for the prompt for installing the fonts did show up, so I did accept but after it finished installing I checked in fonts app whether it got installed but its not there. I checked the  entire output but I didn't it see it grab any of the fonts. I had no issues when installing on ubuntu 22.04 but on this its not working. 

I have attached the output below
The following additional packages will be installed:
  cabextract chromium-codecs-ffmpeg-extra gstreamer1.0-libav
  gstreamer1.0-plugins-ugly liba52-0.7.4 libaacs0 libaribb24-0 libass9
  libavcodec-extra libavcodec-extra58 libavfilter7 libavformat58 libbdplus0
  libblas3 libbluray2 libbs2b0 libchromaprint1 libdvdread8 libflite1
  libgfortran5 libgme0 liblapack3 liblilv-0-0 libmpeg2-4 libmspack0 libmysofa1
  libnorm1 libopencore-amrnb0 libopencore-amrwb0 libopenmpt0 libpgm-5.3-0
  libpocketsphinx3 libpostproc55 librabbitmq4 librubberband2 libserd-0-0
  libsidplay1v5 libsord-0-0 libsphinxbase3 libsratom-0-0 libsrt1.4-gnutls
  libssh-gcrypt-4 libswscale5 libudfread0 libvidstab1.1 libvo-amrwbenc0
  libzimg2 libzmq5 pocketsphinx-en-us ttf-mscorefonts-installer
  ubuntu-restricted-addons unrar
Suggested packages:
  libcuda1 libnvcuvid1 libnvidia-encode1 libbluray-bdj libdvdcss2 serdi
  sidplay-base sordi
Recommended packages:
  gstreamer1.0-fluendo-mp3
The following packages will be REMOVED:
  libavcodec58
The following NEW packages will be installed:
  cabextract chromium-codecs-ffmpeg-extra gstreamer1.0-libav
  gstreamer1.0-plugins-ugly liba52-0.7.4 libaacs0 libaribb24-0 libass9
  libavcodec-extra libavcodec-extra58 libavfilter7 libavformat58 libbdplus0
  libblas3 libbluray2 libbs2b0 libchromaprint1 libdvdread8 libflite1
  libgfortran5 libgme0 liblapack3 liblilv-0-0 libmpeg2-4 libmspack0 libmysofa1
  libnorm1 libopencore-amrnb0 libopencore-amrwb0 libopenmpt0 libpgm-5.3-0
  libpocketsphinx3 libpostproc55 librabbitmq4 librubberband2 libserd-0-0
  libsidplay1v5 libsord-0-0 libsphinxbase3 libsratom-0-0 libsrt1.4-gnutls
  libssh-gcrypt-4 libswscale5 libudfread0 libvidstab1.1 libvo-amrwbenc0
  libzimg2 libzmq5 pocketsphinx-en-us ttf-mscorefonts-installer
  ubuntu-restricted-addons ubuntu-restricted-extras unrar
0 upgraded, 53 newly installed, 1 to remove and 1 not upgraded.
Need to get 58.6 MB of archives.
After this operation, 98.8 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libmspack0 amd64 0.10.1-2build2 [39.6 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 cabextract amd64 1.9-3 [23.4 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 chromium-codecs-ffmpeg-extra amd64 1:85.0.4183.83-0ubuntu2 [3,008 B]
Get:4 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libaribb24-0 amd64 1.0.3-2 [26.9 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libopencore-amrnb0 amd64 0.1.5-1 [94.8 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libopencore-amrwb0 amd64 0.1.5-1 [49.1 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libvo-amrwbenc0 amd64 0.1.3-2 [68.2 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libavcodec-extra58 amd64 7:4.4.1-3ubuntu5 [5,571 kB]
Get:9 http://apt.pop-os.org/release jammy/main amd64 ttf-mscorefonts-installer all 3.8ubuntu2pop1~1651417478~22.04~4e18be2 [34.8 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libass9 amd64 1:0.15.2-1 [97.5 kB]
Get:11 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libudfread0 amd64 1.1.2-1 [16.2 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libbluray2 amd64 1:1.3.1-1 [159 kB]
Get:13 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libchromaprint1 amd64 1.5.1-2 [28.4 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libgme0 amd64 0.6.3-2 [127 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libopenmpt0 amd64 0.6.1-1 [592 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 librabbitmq4 amd64 0.10.0-1ubuntu2 [39.3 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libsrt1.4-gnutls amd64 1.4.4-4 [309 kB]
Get:18 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libssh-gcrypt-4 amd64 0.9.6-2build1 [222 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libnorm1 amd64 1.5.9+dfsg-2 [221 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libpgm-5.3-0 amd64 5.3.128~dfsg-2 [161 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libzmq5 amd64 4.3.4-2 [256 kB]
Get:22 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libavformat58 amd64 7:4.4.1-3ubuntu5 [1,101 kB]
Get:23 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libbs2b0 amd64 3.1.0+dfsg-2.2build1 [10.2 kB]
Get:24 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libflite1 amd64 2.2-3 [13.7 MB]
Get:25 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libserd-0-0 amd64 0.30.10-2 [40.8 kB]
Get:26 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libsord-0-0 amd64 0.16.8-2 [21.2 kB]
Get:27 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libsratom-0-0 amd64 0.6.8-1 [17.0 kB]
Get:28 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 liblilv-0-0 amd64 0.24.12-2 [42.8 kB]
Get:29 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libmysofa1 amd64 1.2.1~dfsg0-1 [1,157 kB]
Get:30 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libblas3 amd64 3.10.0-2ubuntu1 [228 kB]
Get:31 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 libgfortran5 amd64 12-20220319-1ubuntu1 [883 kB]
Get:32 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 liblapack3 amd64 3.10.0-2ubuntu1 [2,504 kB]
Get:33 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libsphinxbase3 amd64 0.8+5prealpha+1-13build1 [126 kB]
Get:34 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libpocketsphinx3 amd64 0.8.0+real5prealpha+1-14ubuntu1 [132 kB]
Get:35 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libpostproc55 amd64 7:4.4.1-3ubuntu5 [60.1 kB]
Get:36 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 librubberband2 amd64 2.0.0-2 [90.0 kB]
Get:37 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libswscale5 amd64 7:4.4.1-3ubuntu5 [180 kB]
Get:38 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libvidstab1.1 amd64 1.1.0-2 [35.0 kB]
Get:39 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libzimg2 amd64 3.0.3+ds1-1 [241 kB]
Get:40 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libavfilter7 amd64 7:4.4.1-3ubuntu5 [1,496 kB]
Get:41 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 gstreamer1.0-libav amd64 1.20.1-1 [104 kB]
Get:42 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 liba52-0.7.4 amd64 0.7.4-20 [30.5 kB]
Get:43 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libdvdread8 amd64 6.1.2-1 [55.7 kB]
Get:44 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libmpeg2-4 amd64 0.5.1-9 [50.7 kB]
Get:45 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libsidplay1v5 amd64 1.36.60-1 [62.5 kB]
Get:46 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 gstreamer1.0-plugins-ugly amd64 1.20.1-1 [225 kB]
Get:47 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libaacs0 amd64 0.11.1-1 [64.1 kB]
Get:48 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libbdplus0 amd64 0.2.0-1 [52.2 kB]
Get:49 http://us.archive.ubuntu.com/ubuntu jammy/multiverse amd64 ubuntu-restricted-addons amd64 26 [3,008 B]
Get:50 http://us.archive.ubuntu.com/ubuntu jammy/multiverse amd64 ubuntu-restricted-extras amd64 67 [3,200 B]
Get:51 http://us.archive.ubuntu.com/ubuntu jammy/multiverse amd64 unrar amd64 1:6.1.5-1 [145 kB]
Get:52 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 libavcodec-extra amd64 7:4.4.1-3ubuntu5 [15.2 kB]
Get:53 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 pocketsphinx-en-us all 0.8.0+real5prealpha+1-14ubuntu1 [27.6 MB]
Fetched 58.6 MB in 1s (39.6 MB/s)              
Extracting templates from packages: 100%
Preconfiguring packages ...
(Reading database ... 231591 files and directories currently installed.)
Removing libavcodec58:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package libmspack0:amd64.
(Reading database ... 231585 files and directories currently installed.)
Preparing to unpack .../00-libmspack0_0.10.1-2build2_amd64.deb ...
Unpacking libmspack0:amd64 (0.10.1-2build2) ...
Selecting previously unselected package cabextract.
Preparing to unpack .../01-cabextract_1.9-3_amd64.deb ...
Unpacking cabextract (1.9-3) ...
Selecting previously unselected package ttf-mscorefonts-installer.
Preparing to unpack .../02-ttf-mscorefonts-installer_3.8ubuntu2pop1~1651417478~2
2.04~4e18be2_all.deb ...
Unpacking ttf-mscorefonts-installer (3.8ubuntu2pop1~1651417478~22.04~4e18be2) ..
.
Selecting previously unselected package chromium-codecs-ffmpeg-extra.
Preparing to unpack .../03-chromium-codecs-ffmpeg-extra_1%3a85.0.4183.83-0ubuntu
2_amd64.deb ...
Unpacking chromium-codecs-ffmpeg-extra (1:85.0.4183.83-0ubuntu2) ...
Selecting previously unselected package libaribb24-0:amd64.
Preparing to unpack .../04-libaribb24-0_1.0.3-2_amd64.deb ...
Unpacking libaribb24-0:amd64 (1.0.3-2) ...
Selecting previously unselected package libopencore-amrnb0:amd64.
Preparing to unpack .../05-libopencore-amrnb0_0.1.5-1_amd64.deb ...
Unpacking libopencore-amrnb0:amd64 (0.1.5-1) ...
Selecting previously unselected package libopencore-amrwb0:amd64.
Preparing to unpack .../06-libopencore-amrwb0_0.1.5-1_amd64.deb ...
Unpacking libopencore-amrwb0:amd64 (0.1.5-1) ...
Selecting previously unselected package libvo-amrwbenc0:amd64.
Preparing to unpack .../07-libvo-amrwbenc0_0.1.3-2_amd64.deb ...
Unpacking libvo-amrwbenc0:amd64 (0.1.3-2) ...
Selecting previously unselected package libavcodec-extra58:amd64.
Preparing to unpack .../08-libavcodec-extra58_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libavcodec-extra58:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package libass9:amd64.
Preparing to unpack .../09-libass9_1%3a0.15.2-1_amd64.deb ...
Unpacking libass9:amd64 (1:0.15.2-1) ...
Selecting previously unselected package libudfread0:amd64.
Preparing to unpack .../10-libudfread0_1.1.2-1_amd64.deb ...
Unpacking libudfread0:amd64 (1.1.2-1) ...
Selecting previously unselected package libbluray2:amd64.
Preparing to unpack .../11-libbluray2_1%3a1.3.1-1_amd64.deb ...
Unpacking libbluray2:amd64 (1:1.3.1-1) ...
Selecting previously unselected package libchromaprint1:amd64.
Preparing to unpack .../12-libchromaprint1_1.5.1-2_amd64.deb ...
Unpacking libchromaprint1:amd64 (1.5.1-2) ...
Selecting previously unselected package libgme0:amd64.
Preparing to unpack .../13-libgme0_0.6.3-2_amd64.deb ...
Unpacking libgme0:amd64 (0.6.3-2) ...
Selecting previously unselected package libopenmpt0:amd64.
Preparing to unpack .../14-libopenmpt0_0.6.1-1_amd64.deb ...
Unpacking libopenmpt0:amd64 (0.6.1-1) ...
Selecting previously unselected package librabbitmq4:amd64.
Preparing to unpack .../15-librabbitmq4_0.10.0-1ubuntu2_amd64.deb ...
Unpacking librabbitmq4:amd64 (0.10.0-1ubuntu2) ...
Selecting previously unselected package libsrt1.4-gnutls:amd64.
Preparing to unpack .../16-libsrt1.4-gnutls_1.4.4-4_amd64.deb ...
Unpacking libsrt1.4-gnutls:amd64 (1.4.4-4) ...
Selecting previously unselected package libssh-gcrypt-4:amd64.
Preparing to unpack .../17-libssh-gcrypt-4_0.9.6-2build1_amd64.deb ...
Unpacking libssh-gcrypt-4:amd64 (0.9.6-2build1) ...
Selecting previously unselected package libnorm1:amd64.
Preparing to unpack .../18-libnorm1_1.5.9+dfsg-2_amd64.deb ...
Unpacking libnorm1:amd64 (1.5.9+dfsg-2) ...
Selecting previously unselected package libpgm-5.3-0:amd64.
Preparing to unpack .../19-libpgm-5.3-0_5.3.128~dfsg-2_amd64.deb ...
Unpacking libpgm-5.3-0:amd64 (5.3.128~dfsg-2) ...
Selecting previously unselected package libzmq5:amd64.
Preparing to unpack .../20-libzmq5_4.3.4-2_amd64.deb ...
Unpacking libzmq5:amd64 (4.3.4-2) ...
Selecting previously unselected package libavformat58:amd64.
Preparing to unpack .../21-libavformat58_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libavformat58:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package libbs2b0:amd64.
Preparing to unpack .../22-libbs2b0_3.1.0+dfsg-2.2build1_amd64.deb ...
Unpacking libbs2b0:amd64 (3.1.0+dfsg-2.2build1) ...
Selecting previously unselected package libflite1:amd64.
Preparing to unpack .../23-libflite1_2.2-3_amd64.deb ...
Unpacking libflite1:amd64 (2.2-3) ...
Selecting previously unselected package libserd-0-0:amd64.
Preparing to unpack .../24-libserd-0-0_0.30.10-2_amd64.deb ...
Unpacking libserd-0-0:amd64 (0.30.10-2) ...
Selecting previously unselected package libsord-0-0:amd64.
Preparing to unpack .../25-libsord-0-0_0.16.8-2_amd64.deb ...
Unpacking libsord-0-0:amd64 (0.16.8-2) ...
Selecting previously unselected package libsratom-0-0:amd64.
Preparing to unpack .../26-libsratom-0-0_0.6.8-1_amd64.deb ...
Unpacking libsratom-0-0:amd64 (0.6.8-1) ...
Selecting previously unselected package liblilv-0-0:amd64.
Preparing to unpack .../27-liblilv-0-0_0.24.12-2_amd64.deb ...
Unpacking liblilv-0-0:amd64 (0.24.12-2) ...
Selecting previously unselected package libmysofa1:amd64.
Preparing to unpack .../28-libmysofa1_1.2.1~dfsg0-1_amd64.deb ...
Unpacking libmysofa1:amd64 (1.2.1~dfsg0-1) ...
Selecting previously unselected package libblas3:amd64.
Preparing to unpack .../29-libblas3_3.10.0-2ubuntu1_amd64.deb ...
Unpacking libblas3:amd64 (3.10.0-2ubuntu1) ...
Selecting previously unselected package libgfortran5:amd64.
Preparing to unpack .../30-libgfortran5_12-20220319-1ubuntu1_amd64.deb ...
Unpacking libgfortran5:amd64 (12-20220319-1ubuntu1) ...
Selecting previously unselected package liblapack3:amd64.
Preparing to unpack .../31-liblapack3_3.10.0-2ubuntu1_amd64.deb ...
Unpacking liblapack3:amd64 (3.10.0-2ubuntu1) ...
Selecting previously unselected package libsphinxbase3:amd64.
Preparing to unpack .../32-libsphinxbase3_0.8+5prealpha+1-13build1_amd64.deb ...
Unpacking libsphinxbase3:amd64 (0.8+5prealpha+1-13build1) ...
Selecting previously unselected package libpocketsphinx3:amd64.
Preparing to unpack .../33-libpocketsphinx3_0.8.0+real5prealpha+1-14ubuntu1_amd6
4.deb ...
Unpacking libpocketsphinx3:amd64 (0.8.0+real5prealpha+1-14ubuntu1) ...
Selecting previously unselected package libpostproc55:amd64.
Preparing to unpack .../34-libpostproc55_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libpostproc55:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package librubberband2:amd64.
Preparing to unpack .../35-librubberband2_2.0.0-2_amd64.deb ...
Unpacking librubberband2:amd64 (2.0.0-2) ...
Selecting previously unselected package libswscale5:amd64.
Preparing to unpack .../36-libswscale5_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libswscale5:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package libvidstab1.1:amd64.
Preparing to unpack .../37-libvidstab1.1_1.1.0-2_amd64.deb ...
Unpacking libvidstab1.1:amd64 (1.1.0-2) ...
Selecting previously unselected package libzimg2:amd64.
Preparing to unpack .../38-libzimg2_3.0.3+ds1-1_amd64.deb ...
Unpacking libzimg2:amd64 (3.0.3+ds1-1) ...
Selecting previously unselected package libavfilter7:amd64.
Preparing to unpack .../39-libavfilter7_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libavfilter7:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package gstreamer1.0-libav:amd64.
Preparing to unpack .../40-gstreamer1.0-libav_1.20.1-1_amd64.deb ...
Unpacking gstreamer1.0-libav:amd64 (1.20.1-1) ...
Selecting previously unselected package liba52-0.7.4:amd64.
Preparing to unpack .../41-liba52-0.7.4_0.7.4-20_amd64.deb ...
Unpacking liba52-0.7.4:amd64 (0.7.4-20) ...
Selecting previously unselected package libdvdread8:amd64.
Preparing to unpack .../42-libdvdread8_6.1.2-1_amd64.deb ...
Unpacking libdvdread8:amd64 (6.1.2-1) ...
Selecting previously unselected package libmpeg2-4:amd64.
Preparing to unpack .../43-libmpeg2-4_0.5.1-9_amd64.deb ...
Unpacking libmpeg2-4:amd64 (0.5.1-9) ...
Selecting previously unselected package libsidplay1v5:amd64.
Preparing to unpack .../44-libsidplay1v5_1.36.60-1_amd64.deb ...
Unpacking libsidplay1v5:amd64 (1.36.60-1) ...
Selecting previously unselected package gstreamer1.0-plugins-ugly:amd64.
Preparing to unpack .../45-gstreamer1.0-plugins-ugly_1.20.1-1_amd64.deb ...
Unpacking gstreamer1.0-plugins-ugly:amd64 (1.20.1-1) ...
Selecting previously unselected package libaacs0:amd64.
Preparing to unpack .../46-libaacs0_0.11.1-1_amd64.deb ...
Unpacking libaacs0:amd64 (0.11.1-1) ...
Selecting previously unselected package libbdplus0:amd64.
Preparing to unpack .../47-libbdplus0_0.2.0-1_amd64.deb ...
Unpacking libbdplus0:amd64 (0.2.0-1) ...
Selecting previously unselected package ubuntu-restricted-addons.
Preparing to unpack .../48-ubuntu-restricted-addons_26_amd64.deb ...
Unpacking ubuntu-restricted-addons (26) ...
Selecting previously unselected package ubuntu-restricted-extras.
Preparing to unpack .../49-ubuntu-restricted-extras_67_amd64.deb ...
Unpacking ubuntu-restricted-extras (67) ...
Selecting previously unselected package unrar.
Preparing to unpack .../50-unrar_1%3a6.1.5-1_amd64.deb ...
Unpacking unrar (1:6.1.5-1) ...
Selecting previously unselected package libavcodec-extra:amd64.
Preparing to unpack .../51-libavcodec-extra_7%3a4.4.1-3ubuntu5_amd64.deb ...
Unpacking libavcodec-extra:amd64 (7:4.4.1-3ubuntu5) ...
Selecting previously unselected package pocketsphinx-en-us.
Preparing to unpack .../52-pocketsphinx-en-us_0.8.0+real5prealpha+1-14ubuntu1_al
l.deb ...
Unpacking pocketsphinx-en-us (0.8.0+real5prealpha+1-14ubuntu1) ...
Setting up libgme0:amd64 (0.6.3-2) ...
Setting up libssh-gcrypt-4:amd64 (0.9.6-2build1) ...
Setting up libsrt1.4-gnutls:amd64 (1.4.4-4) ...
Setting up libudfread0:amd64 (1.1.2-1) ...
Setting up libvo-amrwbenc0:amd64 (0.1.3-2) ...
Setting up librabbitmq4:amd64 (0.10.0-1ubuntu2) ...
Setting up chromium-codecs-ffmpeg-extra (1:85.0.4183.83-0ubuntu2) ...
Setting up libsidplay1v5:amd64 (1.36.60-1) ...
Setting up libpgm-5.3-0:amd64 (5.3.128~dfsg-2) ...
Setting up libmspack0:amd64 (0.10.1-2build2) ...
Setting up libnorm1:amd64 (1.5.9+dfsg-2) ...
Setting up libmysofa1:amd64 (1.2.1~dfsg0-1) ...
Setting up unrar (1:6.1.5-1) ...
update-alternatives: using /usr/bin/unrar-nonfree to provide /usr/bin/unrar (unr
ar) in auto mode
Setting up libmpeg2-4:amd64 (0.5.1-9) ...
Setting up libaribb24-0:amd64 (1.0.3-2) ...
Setting up liba52-0.7.4:amd64 (0.7.4-20) ...
Setting up libopencore-amrwb0:amd64 (0.1.5-1) ...
Setting up libblas3:amd64 (3.10.0-2ubuntu1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 to provid
e /usr/lib/x86_64-linux-gnu/libblas.so.3 (libblas.so.3-x86_64-linux-gnu) in auto
 mode
Setting up libass9:amd64 (1:0.15.2-1) ...
Setting up libdvdread8:amd64 (6.1.2-1) ...
Setting up libpostproc55:amd64 (7:4.4.1-3ubuntu5) ...
Setting up libaacs0:amd64 (0.11.1-1) ...
Setting up pocketsphinx-en-us (0.8.0+real5prealpha+1-14ubuntu1) ...
Setting up libgfortran5:amd64 (12-20220319-1ubuntu1) ...
Setting up librubberband2:amd64 (2.0.0-2) ...
Setting up libbdplus0:amd64 (0.2.0-1) ...
Setting up libvidstab1.1:amd64 (1.1.0-2) ...
Setting up libflite1:amd64 (2.2-3) ...
Setting up libbs2b0:amd64 (3.1.0+dfsg-2.2build1) ...
Setting up libopencore-amrnb0:amd64 (0.1.5-1) ...
Setting up libzimg2:amd64 (3.0.3+ds1-1) ...
Setting up gstreamer1.0-plugins-ugly:amd64 (1.20.1-1) ...
Setting up libswscale5:amd64 (7:4.4.1-3ubuntu5) ...
Setting up libbluray2:amd64 (1:1.3.1-1) ...
Setting up libopenmpt0:amd64 (0.6.1-1) ...
Setting up ubuntu-restricted-addons (26) ...
Setting up libserd-0-0:amd64 (0.30.10-2) ...
Setting up liblapack3:amd64 (3.10.0-2ubuntu1) ...
update-alternatives: using /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3 to pr
ovide /usr/lib/x86_64-linux-gnu/liblapack.so.3 (liblapack.so.3-x86_64-linux-gnu)
 in auto mode
Setting up libzmq5:amd64 (4.3.4-2) ...
Setting up cabextract (1.9-3) ...
Setting up libavcodec-extra58:amd64 (7:4.4.1-3ubuntu5) ...
Setting up libsphinxbase3:amd64 (0.8+5prealpha+1-13build1) ...
Setting up libpocketsphinx3:amd64 (0.8.0+real5prealpha+1-14ubuntu1) ...
Setting up libsord-0-0:amd64 (0.16.8-2) ...
Setting up libsratom-0-0:amd64 (0.6.8-1) ...
Setting up ttf-mscorefonts-installer (3.8ubuntu2pop1~1651417478~22.04~4e18be2) .
..
Setting up liblilv-0-0:amd64 (0.24.12-2) ...
Setting up ubuntu-restricted-extras (67) ...
Setting up libchromaprint1:amd64 (1.5.1-2) ...
Setting up libavcodec-extra:amd64 (7:4.4.1-3ubuntu5) ...
Setting up libavformat58:amd64 (7:4.4.1-3ubuntu5) ...
Setting up libavfilter7:amd64 (7:4.4.1-3ubuntu5) ...
Setting up gstreamer1.0-libav:amd64 (1.20.1-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...

Please resolve this as soon as possible

**Comment by youdontneedtoknow22** [comment]
I literally just tried this too. I can't understand why such problems don't get solved. Here's an issue from 2020 (https://github.com/pop-os/pop/issues/1321)

```
sudo add-apt-repository multiverse
sudo apt update && sudo apt install ttf-mscorefonts-installer
```
After that, I expect the fonts to be shown in Libreoffice and Openoffice. But that's not the case

**Comment by antenmanuuel** [comment]
A temporary solution I found is first to run 
1. sudo apt install libmspack0 cabextract : for all missing dependencies
2.  wget http://ftp.us.debian.org/debian/pool/contrib/m/msttcorefonts/ttf-mscorefonts-installer_3.8_all.deb
3.   sudo dpkg -i ttf-mscorefonts-installer_3.8_all.deb
4. finally run sudo apt update and sudo apt upgrade to make sure the packages are all up to date

**Comment by cwsystem76** [comment]
We have a workaround for the `ttf-mscorefonts-installer` problem, which is somewhat more complicated than just using the Debian package, but which will avoid possible package dependency issues that the Debian package might cause.

The following commands should fix the issue, and also allow the `ttf-mscorefonts-installer` to be properly upgraded or removed in the future. I'm also attaching a ZIP file with these commands in a shell script, as these commands have been set up to not require user intervention.
```
echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
sudo apt install -y wget ttf-mscorefonts-installer cabextract

mkdir -p ~/Downloads/msfonts/

wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/wd97vwr32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/webdin32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/verdan32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/trebuc32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/times32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/impact32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/georgi32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/courie32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/comic32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/arialb32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/arial32.exe -P ~/Downloads/msfonts
wget https://sourceforge.net/projects/corefonts/files/the%20fonts/final/andale32.exe  -P ~/Downloads/msfonts

sudo /usr/lib/msttcorefonts/update-ms-fonts ~/Downloads/msfonts/*.exe
```
[msfonts.zip](https://github.com/pop-os/pop/files/8652393/msfonts.zip)

**Comment by antenmanuuel** [comment]
temporary solution found
