### ISSUE TITLE
Weather Icons

### ISSUE THREAD

**Issue by lennie420** [pop-os/pop#2378]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Weather widget in the notification box

**Issue/Bug Description:**
Icons for certain weather patterns show a solid block

**Steps to reproduce (if you know):**
Load weather widget and wait for it to show the weather

**Expected behavior:**
Show icons that resemble weather

**Other Notes:**

![Screenshot from 2022-05-07 09-10-42](https://user-images.githubusercontent.com/84619126/167243637-568f9a0b-bca9-4e0b-b371-b87b8b9f0dba.png)
![Screenshot from 2022-05-07 09-11-56](https://user-images.githubusercontent.com/84619126/167243639-68337518-96dc-4404-ac93-15038740a21d.png)
![Screenshot from 2022-05-07 09-19-31](https://user-images.githubusercontent.com/84619126/167243640-c3de96eb-5074-46a7-8ddc-fac6205f65cd.png)

**Comment by lennie420** [comment]
Hmm, I have reinstalled and the icons seem okay

**Comment by lennie420** [comment]
Think I closed this by mistake. I have reinstalled and the icons seem fine but not sure if it's just because the weather has changed and there is no sunshine. Will see what happens.

All I have done a fresh reinstall with a separate data partition (was initially just doing a test install.)

**Comment by lennie420** [comment]
Think I closed this by mistake. I have reinstalled and the icons seem fine but not sure if it's just because the weather has changed and there is no sunshine. Will see what happens.

All I have done a fresh reinstall with a separate data partition (was initially just doing a test install.)

**Comment by dawaltconley** [comment]
Same issue, on 22.04 upgraded from 20.10. `/usr/share/icons/Pop/scalable/status/weather-clear-symbolic.svg` does exist and looks fine in other programs.
