### ISSUE TITLE
Animation glitch when minimizing the window POP OS 22.04

### ISSUE THREAD

**Issue by PranavDalvi** [pop-os/pop#2384]
**Distribution (run `cat /etc/os-release`):**
- NAME="Pop!_OS"
- VERSION="22.04 LTS"
- ID_LIKE="ubuntu debian"
- PRETTY_NAME="Pop!_OS 22.04 LTS"
- VERSION_ID="22.04"
- VERSION_CODENAME=jammy
- UBUNTU_CODENAME=jammy
 

**Issue/Bug Description:**
When I try to minimize or maximize any window animation glitch occurs.

**Steps to reproduce (if you know):**
- **Laptop Specs:**
- **CPU:** AMD A8 7410 with integrated ATI R5.
-  **Screen Resolution:** 1366:768 (16:9)

https://user-images.githubusercontent.com/70306291/167455915-20bc08dc-9688-4a1c-8b18-13116f0b33bf.MP4

**Comment by miaoerwu** [comment]
I have the same problem. The system application and the application I installed, when minimized and restored, flicker and there is a dummy image

**Comment by PranavDalvi** [comment]
Thank you for fixing the issue

**Comment by RiffLord** [comment]
Was this issue solved and if so, how? I also have this bug on a freshly installed copy of Pop!_OS.

**Comment by PranavDalvi** [comment]
By updating to latest version
