### ISSUE TITLE
Chrome tabs crashing 

### ISSUE THREAD

**Issue by reubenfirmin** [pop-os/pop#2395]
**Distribution (run `cat /etc/os-release`):**
 
 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

google chrome

**Issue/Bug Description:**

I installed google chrome on an Intel Nuc. After some period of time, tabs in the browser crash. The system is not memory or cpu constrained. I thought maybe it was a ulimit issue, but so far have been unable to change the ulimit reported for the user. I'm not getting any insights running chrome with debug logging turned on.

**Comment by linuxgnuru** [comment]
What version of chrome are you running? Does this occur with any web sites or just certain ones in particular? Can you see if Firefox has similar issues?
