### ISSUE TITLE
Headset's microphone not working on 22.04 after Friday's 'daily update'

### ISSUE THREAD

**Issue by OvermindThe** [pop-os/pop#2398]
**Issue/Bug Description:**
https://www.reddit.com/r/pop_os/comments/ulqw0g/headsets_microphone_stopped_working_on_2204
Im running pop_os 22.04.
Exactly as in this reddit post, my headset's microphone stopped working, while playback and volume control knob work fine.
It happened after on Friday (6th of May) I installed daily updates.

**Steps to reproduce (if you know):**
Get a headset (preferably Steelseries Arctic 5), plug it to your computer and try using the microphone.

**Expected behavior:**
Microphone should work.

**Other Notes:**
Looks like I'm not the only one and it's one of the most used things during work from home era.

**Comment by linuxgnuru** [comment]
Is this issue present if you use the 3.5 mm jack or with the USB dongle or both?

**Comment by OvermindThe** [comment]
This exact model is only pluggable via USB dongle, can't tell whether I'd work or now via 3.5mm.

**Comment by OvermindThe** [comment]
Just noticed today that it works again. Must have been another of the daily updates as I have not messed with the settings since this post. I'm gonna close this issue now. Thanks!
