### ISSUE TITLE
"Force UEFI Installation?" warning mentions Debian no Pop!_OS

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#24]
_From @brs17 on October 11, 2017 19:47_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
A warning appears when trying to install in UEFI mode while a BIOS compatible OS is already installed on the system. This warning refers to Debian as the operating system being installed, not Pop!_OS.

![img_20171010_125328](https://user-images.githubusercontent.com/7460774/31462568-70995f2e-ae8a-11e7-8c4b-2d67050515e0.jpg)

**Steps to reproduce (if you know)**
Install OS in "BIOS compatible mode" then switch to UEFI mode and attempt to install Pop!_OS. Warning pop-up will appear before installation completes.

**Expected behaviour**
Error message should say Pop!_OS instead of Debian.

**Other Notes**
I imagine this is a bug upstream with Ubuntu grabbing that message from Debian or something of the like.

Also, please excuse the phone camera image!

_Copied from original issue: pop-os/iso#141_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
