### ISSUE TITLE
pop shell maximizes minimized windows

### ISSUE THREAD

**Issue by RafalSkolasinski** [pop-os/pop#2402]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop shell extension / Gnome

**Issue/Bug Description:**

Pop shell seems to maximize minimized windows if they are put on non-workspaced monitor while changing workspaces on another display.

**Steps to reproduce (if you know):**
1. Disable pop cosmic extension
2. Leave pop shell extension on
3. Set workspaces only on primary monitor 
4. Put window on second (not-workspaced monitor) and minimize it
5. Change workspaces using shortcuts (may need to add new ones)

![image](https://user-images.githubusercontent.com/10928117/167874829-33865363-e3e4-42f0-a213-0df146406a8f.png)
![image](https://user-images.githubusercontent.com/10928117/167875029-50003786-95f6-47aa-b977-28b52be55fd6.png)

**Expected behavior:**

Minimize window stays minimized.

**Other Notes:**

Disabling pop shell gets expected behaviour.

**Comment by linuxgnuru** [comment]
As Pop shell and COSMIC are interconnected this odd behavior may well exist if cosmic is disabled.  Do you see this issue without having to disable COSMIC?

**Comment by RafalSkolasinski** [comment]
Fair point, just tested. I cannot replicate this issue but https://github.com/pop-os/pop/issues/2404 still happens
