### ISSUE TITLE
Icons are blurry in Libreoffice.

### ISSUE THREAD

**Issue by SyedHasan110** [pop-os/pop#2418]
**Distribution:** 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version :** Libreoffice 7.3 

**Issue/Bug Description:** Blurry Icons in Libreoffice

![Screenshot from 2022-05-16 11-44-02](https://user-images.githubusercontent.com/70736490/168531278-cfd81b9f-d8fd-4cba-86f6-0a6ad976e018.png)

**Comment by linuxgnuru** [comment]
Are you using a custom icon set?

**Comment by SyedHasan110** [comment]
No I am only using the icon set that libreoffice provides.

**Comment by linuxgnuru** [comment]
Under Tools -> Options -> View, what do you have set for Icon style?

**Comment by SyedHasan110** [comment]
Every icon style is blurry.

**Comment by n3m0-22** [comment]
I only see this happen with the included (SVG) icon sets. All the others are working fine on my end. @SyedHasan110 are you still seeing this issue?

**Comment by SyedHasan110** [comment]
For me it is happening for both svg and non-svg icon sets.

**Comment by jackpot51** [comment]
It looks like you have a HiDPI display, what scaling factor are you using?

**Comment by SyedHasan110** [comment]
Yes, I have a HiDPI display, I am using a scaling factor of 200%.
