### ISSUE TITLE
Unable to boot pop_os! 18.04_nvidia_17 live USB

### ISSUE THREAD

**Issue by speltriao** [pop-os/pop#242]
https://github.com/pop-os/iso/issue
![20180429_170953](https://user-images.githubusercontent.com/38846168/39413545-3806b09c-4c02-11e8-9aca-fffbbb147fd3.jpg)

 **Distribution - (run ```cat /etc/os-release```)**
 Pop_os18.04_amd64_nvidia.iso
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
Boot into live CD

**Issue/Bug Description**
I'm trying to boot pop_os nvidia into a Lenovo z40-70 laptop , but it's really impossible. I'm getting stuck into an infinite loop as seing on the picture atached to this report, which was really hard to take, considering the screen was flashing all the time...... I've tried to use a different media creation tool (etcher and Rufus) and using EFI and UEFI boot and none of those made a difference.
Also, I wasn't able to access the terminal using Ctrl+Alt+F1/F2/F3 for more than two or three seconds to get more info , because the screen would (again) start to flash with the message attached.

Worth mentioning that this seems a pop_os! issue, since I was able to boot and install Ubuntu 18.04 LTS 

**Steps to reproduce (if you know)**
Just trying to boot into the live CD 

**Expected behavior**
The OS should boot into the installer.

**Other Notes**

**Comment by mmstick** [comment]
Was this ISO 17?

**Comment by cwrau** [comment]
Happened to me as well, but on dell xps 15 9550. I'm now trying the Intel iso

**Comment by sanjeevkpandit** [comment]
Same here, screen flickers and no UI at all on live boot.

**Comment by speltriao** [comment]
Yes, Nvidia ISO 17. @mmstick

**Comment by millserd** [comment]
Same for me.

**Comment by jackpot51** [comment]
Yes, you can install nvidia drivers on the intel version

**Comment by millserd** [comment]
yup. thanks

**Comment by blaubachn** [comment]
I had the same issue. Was able to get the other install working though.
Laptop: ASUS N53SV
Card: NVIDIA GeForce GT 540M
