### ISSUE TITLE
Gnome Software Center doesn't install.

### ISSUE THREAD

**Issue by DavidSmolinski** [pop-os/pop#2423]
**Distribution (run `cat /etc/os-release`):**
 
 21.04
 
**Steps to reproduce (if you know):**

command:
sudo apt install gnome-software

error:
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

**Comment by jacobgkau** [comment]
> 21.04

Version 21.04 has been end-of-life for months. Please [upgrade](https://support.system76.com/articles/upgrade-pop) to 22.04 LTS, then see if the issue still occurs. Apt does not complain about installing gnome-software for me on a 22.04 machine.

**Comment by mmstick** [comment]
Issue can be re-opened if it's also happening on 22.04
