### ISSUE TITLE
Chrome freezes often

### ISSUE THREAD

**Issue by DavidSmolinski** [pop-os/pop#2424]
**Distribution (run `cat /etc/os-release`):**
 21.04

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Google Chrome

**Issue/Bug Description:**
The computer is running fast, and Chrome freezes. A window appears that allows me to close Chrome. When I open Chrome again, the windows appear in the wrong workspaces.

**Comment by mmstick** [comment]
21.04 is not supported

**Comment by drtpotter** [comment]
Same issue on 22.04

**Comment by TheAndrewJackson** [comment]
I'm still seeing this issue in 22.04. The workaround I found was to disable the `HiDPI Daemon` in `Settings > Displays`. The freezing stopped for me as soon as it was turned off.

**Comment by Arkanius** [comment]
It keeps happening here, even with HiDPI Daemon. I'm using external screen with notebook screen.
