### ISSUE TITLE
It may erase my win10

### ISSUE THREAD

**Issue by bubblesuntie** [pop-os/pop#243]
Pop_os! 18.04_nvidia_17 will take up all my disk.I can't resize partitions.

**Comment by jackpot51** [comment]
Use the custom partitioning screen

**Comment by bubblesuntie** [comment]
There is no 'the custom partitioning screen' option. I use 'lili usb creator' not 'etcher'. Is there any reason for the possibility of the tool？But using etcher to make bootable drive will cause failure.

**Comment by jackpot51** [comment]
You need to write the .iso file to a USB stick, and then boot from that USB stick to run the installer.

**Comment by bubblesuntie** [comment]
I have write .iso file to my usb stick, and boot from the usb stick. When run the installer, I can't find 'custom partitioning screen' option.

**Comment by bubblesuntie** [comment]
Sorry, I found the option. think you very much.

**Comment by mmstick** [comment]
It's on this screen:

![screenshot from 2018-04-30 17-15-26](https://user-images.githubusercontent.com/4143535/39454705-1b70ff6c-4c9a-11e8-99c4-fb6095d8ab78.png)

Which is after this screen:

![screenshot from 2018-04-30 17-15-53](https://user-images.githubusercontent.com/4143535/39454713-26c65434-4c9a-11e8-9d2e-40fe6d9fa3b7.png)
