### ISSUE TITLE
Mouse cursor moving to activated window when changing workspace

### ISSUE THREAD

**Issue by RaunySouza** [pop-os/pop#2435]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
Mouse cursor moving to activated window when changing workspace on multi-monitor setup ("Workspaces on primary display only" enabled).

**Steps to reproduce (if you know):**
1. Open app on secondary display.
2. Move cursor to other monitor.
3. Change workspace.

Cursor moves to top left position on activated window.

**Expected behavior:**
Cursor keep its position.

**Comment by leviport** [comment]
There was recently an update to Pop Shell to add a setting that prevents the cursor from moving when window focus changes. Does turning that setting off in the Pop Shell extension settings make it behave the way you expect?

![2022-05-20_09-14](https://user-images.githubusercontent.com/13512097/169559008-ce8eaf46-a9d1-4666-bd16-74e354d3ca74.png)

**Comment by RaunySouza** [comment]
Disabling this option worked out and cursor is behaving as I expected now.

Thank you!
