### ISSUE TITLE
Ubuntu-Drivers-Common Package Causes Severe slowdown in applications (especially Flatpaks, AppImages)

### ISSUE THREAD

**Issue by ufcebuano** [pop-os/pop#2437]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
``` 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
ubuntu-drivers-common:
  Installed: 1:0.9.6.1pop0~1651070156~22.04~66ae311
  Candidate: 1:0.9.6.1pop0~1652303087~22.04~1aab0f9
  Version table:
     1:0.9.6.1pop0~1652303087~22.04~1aab0f9 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 1:0.9.6.1pop0~1651070156~22.04~66ae311 100
        100 /var/lib/dpkg/status
     1:0.9.6.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
Updating ubuntu-drivers-common package causes severe slowdown in apps. Observed with Flatpaks and AppImages. Removal and re-installation of Flatpaks does not help.

**Steps to reproduce (if you know):**
Slowdown occurs when ubuntu-drivers-common package is updated to the latest version (1:0.9.6.1pop0~1652303087~22.04~1aab0f9). The system recovers back to normal with a Timeshift Restore. I have installed all other updates to my system successfully and isolated the slowdown issue to occur with ubuntu-drivers-common package specifically.

**Expected behavior:**
Expected behaviour is to have the system run smoothly after all updates.

**Other Notes:**
[pop-support_1653184070.zip](https://github.com/pop-os/pop/files/8748631/pop-support_1653184070.zip)

(Edited to add block text to avoid ~ strike through)

**Comment by linuxgnuru** [comment]
The latest version for ubuntu-drivers-common is `1:0.9.6.1pop0~1652303087~22.04~1aab0f9`

There may be an issue with the pin priority.  What does the command `apt policy ubuntu-drivers-common` output?

**Comment by ufcebuano** [comment]
I have not upgraded the package to the latest version since it is the latest version that causes the slowdown.

Output is given below:
ubuntu-drivers-common:
Installed: 1:0.9.6.1pop0~1651070156~22.04~66ae311
  Candidate: 1:0.9.6.1pop0~1652303087~22.04~1aab0f9
  Version table:
     1:0.9.6.1pop0~1652303087~22.04~1aab0f9 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
 *** 1:0.9.6.1pop0~1651070156~22.04~66ae311 100
        100 /var/lib/dpkg/status
     1:0.9.6.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages

**Comment by ufcebuano** [comment]
I just installed a new round of updates and installed ubuntu-drivers-common package to test. It looks like it has been fixed. Not sure exactly what the cause was but everything is working fine now.
