### ISSUE TITLE
Creating archive from file manager is broken

### ISSUE THREAD

**Issue by MyNameIsArko** [pop-os/pop#2439]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
nautilus:
  Installed: 1:42.1.1-0ubuntu1
  Candidate: 1:42.1.1-0ubuntu1
  Version table:
 *** 1:42.1.1-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     1:42.0-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**

When trying to create archive by nautilus context menu "create archive", option are cropped.
![168276971-3fee91c2-56d2-4dee-a51a-6ed158387db4](https://user-images.githubusercontent.com/47687092/169714643-566c9de1-42d4-48ee-9d2b-d7943da4966f.png)

**Steps to reproduce (if you know):**

Right click a file in nautilus -> create archive -> click .zip to change -> see cropped options

**Expected behavior:**

Options fully readable.

**Other Notes:**

On fedora, newest nautilus version, that just got updated, has it fixed, so I recommend updating it to latest if stable enough.

**Comment by leviport** [comment]
It looks like the translations make those description strings significantly longer, so that might by why they're spilling over and getting cut off.
![2022-05-23_09-40](https://user-images.githubusercontent.com/13512097/169856557-6a6660d7-8da2-4137-aead-a17a6d67f5a4.png)

Good to hear that it was fixed upstream though. Hopefully we'll see the fix soon.
