### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by kerroncheddie** [pop-os/pop#244]
My machine is an Asus FX503VD with nvidia gtx1050, it worked well with 17.10, but it wont even boot with 18.04.
I've tried passing some boot arguments but so far I've had no luck. 
I've tried 15 and 17 , both amd and nvidia versions.

**Comment by revivedblaze** [comment]
I have an Asus K55VM with nvidia GT630M, had no issues with 17.10 but it wont boot with 18.04.

**Comment by brs17** [comment]
@kerroncheddie @revivedblaze are you two using the intel iso or the nvidia iso?

**Comment by kerroncheddie** [comment]
I've tried both and neither would boot

**Comment by revivedblaze** [comment]
I've tried with nvidia iso.

**Comment by kerroncheddie** [comment]
I've managed to boot the intel version with the boot arg  acpi_osi= ,
will try to install it and then install the nvidia driver to see what happens.
will comment later.

**Comment by kerroncheddie** [comment]
Ended up only being able to run live, after install back to blank screen with intel version......bump

**Comment by kerroncheddie** [comment]
I tried the nvidia 18 iso, same, blank screen, however, I did try ubuntu and it worked with the boot option acpi_osi=, also the nvidia drivers works there as well.

**Comment by kerroncheddie** [comment]
I just tried the 21 release(Intel and Nvidia versions), I could get them to boot with acpi_osi=
But after install I am back to a blank screen , each version.

**Comment by kerroncheddie** [comment]
What is this you speak off.
I don't know what it is.
