### ISSUE TITLE
Fullscreen collapses on focus loss 

### ISSUE THREAD

**Issue by tnfru** [pop-os/pop#2440]
**Distribution:**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os 

 
**Related Application and/or Package Version**

```
firefox:
  Installed: 100.0.1~1652725772~22.04~01dc5a4
  Candidate: 100.0.1~1652725772~22.04~01dc5a4
  Version table:
     1:1snap1-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
 *** 100.0.1~1652725772~22.04~01dc5a4 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

guake:
  Installed: 3.8.5-1
  Candidate: 3.8.5-1
  Version table:
 *** 3.8.5-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status

```

**Issue/Bug Description:**

If a fullscreen window is focused and I focus another window, i.e. SUPER + H
and then focus it again with SUPER + L the app will stop being in fullscreen.
If I focus any other window by clicking on it this will not happen until I click on the fullscreen
app again, but the click will not be registered, only the window exits fullscreen.
This is a very recent behavior which disrupts my workflow, as it majorly affects my drop down terminal Guake,
which can not stay fullscreen. If I hide it in fullscreen and make it reappear. I've included a video of that happening.

First I maximize a youtube video and shift focus to a different screen with SUPER + H. The video is minimized.
Then I maximize the video and click on a different screen - app stays fullscreen until I move the mouse back on the window and click.
The expected behavior is that it will start the youtube video, but it only un-fullscreens it.
Last I show the problem with guake which can not stay fullscreen, after I toggle the visibility on and off it has a weird animation
where it jumps to half-screen in a short amount of time without me pressing any button.

video: https://www.youtube.com/watch?v=fin4WC_Tzoc

**Expected behavior:**

Up until this issue happened the loss of focus did not negatively impact any application.
Apps would stay fullscreen, whether they were unfocused by keyboard or mouse and would
be correctly re assumed. 

**Other Notes:**

I've tried a refresh install and the issue persists.  It also exists if I create a new user.

**Comment by linuxgnuru** [comment]
What browser are you using? How were you entering full screen mode; F11, using the fullscreen button in Youtube, or just maximizing the window?

**Comment by tnfru** [comment]
@linuxgnuru I am using Firefox, in the video I use double click, but the same issue happens if the browser is maximized with F11, the shortcut to maximize a video on YT (F).

The same thing happens with Terminal windows, for example if I'm running a fullscreen htop on one screen and switch over the fullscreen stops.

**Comment by linuxgnuru** [comment]
Do you have tiling enabled?

**Comment by tnfru** [comment]
@linuxgnuru  Yes, I have the tiling window manager enabled.

**Comment by tnfru** [comment]
Well I definitly don't want to disable the tiling window manager

**Comment by tnfru** [comment]
Problem seems fixed to be since I updated some packages. Here is the list of the packages I updated / installed, I hope it helps:

```
2022-05-27 00:49:41 install libasound2-plugins:amd64 <none> 1.2.6-1
2022-05-27 00:49:42 install gnome-shell-extension-pop-x11gestures:all <none> 1.0.14~1653080221~22.04~bffe643
2022-05-27 10:56:49 install gir1.2-ayatanaappindicator3-0.1:amd64 <none> 0.5.90-7ubuntu2
2022-05-27 10:56:49 install blueman:amd64 <none> 2.2.4-1
```
