### ISSUE TITLE
Why is pipewire not the default alsa PCM

### ISSUE THREAD

**Issue by spacekookie** [pop-os/pop#2443]
So some background I was trying to play a game from 2014 which didn't have pulse-audio support, so used alsa lib directly. The game started, but didn't have audio. After looking into it a little bit I also noticed that `aplay` didn't work either unless I provided `-D pipewire` as a parameter.

Then I noticed that my system has a `/usr/share/alsa/alsa.conf.d/99-pipewire-default.conf`. According to the Arch `pipewire-alsa` PKGBUILD (or check here: https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/master/INSTALL.md#alsa-plugin) this file should be symlinked to `/etc/alsa/conf.d/`. That directory even already includes a `99-pulseaudio-default.conf.example` (which does the same for pulse audio) so I'm a bit confused why when Pop_OS uses pipewire by default, this symlink is not being set :thinking: 

Anyway, my game works now so I'm happy. Just thought I'd let you know that this should be fixed! (And to help anyone else finding this trying to play a game from 2014 that only supports alsa :grin:)

**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by mmstick** [comment]
It causes a 1 second audio delay to Davinci Resolv. It will be reverted once that issue is resolved.

Technically it's still using pipewire. Setting the type to pulse sends the audio to pipewire-pulse, which sends it to pipewire.

**Comment by spacekookie** [comment]
It's not defaulting to `pulse` though! A simple way to test it is to use `aplay` which produces this error, unless I set the symlink I mentioned above:

```
 ❤ (theia) ~> aplay  Projects/music/Library/Samples/inbox/quarryman.wav
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
aplay: main:831: audio open error: No such file or directory
```

Not to mention that Pop_OS _already_ sets up a bunch of symlinks to `/usr/share/alsa/alsa.conf.d/` configuration

**Comment by maciejhirsz** [comment]
After today's update (I think?) this works for me (both `aplay` and directly interfacing with alsa via C FFI)

**Comment by borisorlov21** [comment]
Having made such settings in Pop!_OS, the sound became clearly better when listening to the deadbeef player, I don’t know much about programming, but the result is there
![Screenshot from 2024-04-25 16-28-46](https://github.com/pop-os/pop/assets/66428911/ac70f6e8-42bb-4f48-9ae0-ced5e0a6fb7e)

![Screenshot from 2024-04-25 16-29-39](https://github.com/pop-os/pop/assets/66428911/e55da7a3-783b-4813-bdd9-e56c900e3a5f)
