### ISSUE TITLE
Dragging windows (chrome/alacritty/gnome-terminal) is super-laggy on Pop OS 22.04 (sometimes)

### ISSUE THREAD

**Issue by krshrimali** [pop-os/pop#2444]
**Distribution (run `cat /etc/os-release`):** Pop OS 22.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** google-chrome, alacritty, gnome-terminal, steam

**Issue/Bug Description:** Dragging opened windows with the apps listed above super laggy! This affects user experience, I usually want to drag my windows to a place, specially when it comes to terminal. Is the lag a known issue? If yes, can you please link to the issue tracker (if any)?

**Steps to reproduce (if you know):**

1. Install google-chrome
2. Open a few tabs (preferably open any YouTube links, I observed lag more frequently when a YT tab is opened)
3. Maybe open a few more windows of other apps like terminal.
4. Try to drag any of these windows.

Initially it works without lag, but after a few minutes of reboot, it starts lagging again.

**Expected behavior:**

There is no/minimum lag!

**Other Notes:**

**Comment by mmstick** [comment]
It's a known issue in GNOME right now. Particularly a bad interaction with NVIDIA drivers on the X11 version of mutter.

**Comment by krshrimali** [comment]
> It's a known issue in GNOME right now. Particularly a bad interaction with NVIDIA drivers on the X11 version of mutter.

Thanks, @mmstick - after reading your message, I searched a little on the internet and found this: https://gitlab.gnome.org/GNOME/mutter/-/issues/818. Changing to maximum performance, fixed the issue for me!

**Comment by QEDeD** [comment]
@krshrimali Apologies, but could you provide some more details on what you did? I assume changed PowerMizer, preferred mode to Prefer Maximum Performance?

If so, was that all that was needed, or did you also perform other steps, such as saving the xorg configuration file?


![image](https://user-images.githubusercontent.com/16562457/172022804-36b65b36-374a-4791-b9e3-abd57582f6a5.png)

**Comment by krshrimali** [comment]
Hi, @QEDeD - Thanks for the question. Apologies for the delay in response.

> I assume changed PowerMizer, preferred mode to Prefer Maximum Performance?

Yes! That's right. I didn't do anything else, and it seemed to fix the issue for me. However, it is still not the best in terms of smoothness, but not superlaggy anymore.

**Comment by krshrimali** [comment]
Update: I still have this issue, so it's not solved. :(

**Comment by mmstick** [comment]
I know that the issue is caused by Mutter increasing its mouse polling rate. Unfortunately that causes a busy loop in Xorg because of a long-standing NVIDIA driver issue. The issue has always been there, but this change to increase the rate of mouse inputs makes it worse.

**Comment by krshrimali** [comment]
> I know that the issue is caused by Mutter increasing its mouse polling rate. Unfortunately that causes a busy loop in Xorg because of a long-standing NVIDIA driver issue. The issue has always been there, but this change to increase the rate of mouse inputs makes it worse.

Thank you, @mmstick - I understand it's something the Pop OS team can not do much about (right now), but is there any solution the team is working? Or if there is any workaround that you're aware of?

**Comment by ydhnwb** [comment]
Taking a look for this. It really disturb me with those laggy thing.

**Comment by mmstick** [comment]
The only solution is waiting for a fix from NVIDIA in 525, or reducing your mouse polling rate.

**Comment by mmstick** [comment]
Yeah

**Comment by krshrimali** [comment]
For what it's worth, disabling hardware acceleration on Chrome helped me, but then it's not close to a solution for the meetings, etc. - I need the hardware acceleration. But in any case, I wanted to share it here if it helps any of you :)

**Comment by ydhnwb** [comment]
updated to 525 nvidia driver, looks like it fixed

**Comment by n3m0-22** [comment]
@krshrimali Did the 525 driver fix this for you?

**Comment by krshrimali** [comment]
Hi, @n3m0-22 - Yes! Just updated to 525 drivers yesterday, and it has gotten back to normal. 🎉 I guess I can close this issue now. Thank you all!

**Comment by BekManBekov1974** [comment]
@n3m0-22 Thank you very much!!!

**Comment by marcelsby** [comment]
The issue persisted for me even after the 525 NVIDIA driver version.

I've purged the packages `xserver-xorg-video-nvidia-525`, `nvidia-driver-525` and installed them again, then reboot.

The problem persists, specifically with Google Chrome and Microsoft Edge, probably the problem occurs with Chromium based browsers, in my case Firefox and Electron apps are ok.

Google Chrome is with hardware acceleration turned on, i've tried turning off but nothing changes when dragging the window, it stays laggy.

Have i done wrong or missed anything?

#### Versions
1. **Google Chrome** - 114.0.5735.198
2. **Pop OS** - 22.04 LTS
3. **NVIDIA driver** - 525.116.04

**Comment by sousaakira** [comment]
enable use system title bar in border problem solved but don´t as not a best practice

**Comment by GuiNeves00** [comment]
after losing my mind  trying to rollback from nvidia 550 to 525, this fixed it for me.

(pop_os 22.04 | gnome 42.5 | m.edge 123.0.2420.65

**Comment by GuiNeves00** [comment]
> enable use system title bar in border problem solved but don´t as not a best practice

after losing my mind trying to rollback from nvidia 550 to 525, this fixed it for me.

(pop_os 22.04 | gnome 42.5 | m.edge 123.0.2420.65

**Comment by ErikSkinnari** [comment]
> enable use system title bar in border problem solved but don´t as not a best practice

You restored my sanity! Thank you. 
My previous solution was to turn off Graphics Acceleration in Google Chrome. But that was causing issues with videos and playing GeoGuessr. Now i enabled the *use system title bar in border * option ( right click the chrome header / title bar to see this option ) and was able to turn Graphics acceleration back on again.

**Comment by ronilaukkarinen** [comment]
> enable use system title bar in border problem solved but don´t as not a best practice

Thank you. This solves the issue for me as no other trick helped.

**Comment by eric-b01** [comment]
> enable use system title bar in border problem solved but don´t as not a best practice

This is the only thing that solved the issue for me. Thank you so much.

**Comment by gkaye** [comment]
> enable use system title bar in border problem solved but don´t as not a best practice

Thank you! This worked for me.

**Comment by ferrouswheel** [comment]
I was struggling to parse the punctuation-free sentence:

> enable use system title bar in border problem solved but don´t as not a best practice

The way to decipher this is:
- Go to Chrome settings -> Appearance
- Enable "Use system title bar in border"

But it worked, so thank you!
