### ISSUE TITLE
PoP OS loosing window tiling orientation after lock screen on dual monitor setup

### ISSUE THREAD

**Issue by anuragbhatia** [pop-os/pop#2445]
**Distribution (run `cat /etc/os-release`):**
 
```NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N.A. 
(All app windows are getting impacted)

**Issue/Bug Description:**
On my dual monitor setup, after lock screen (and sleep), tiled windows move random between monitors and they re-size as well. Thus after unlocking, I have to put them again based on the preferred monitor and orientation. 

**Steps to reproduce (if you know):**

**Expected behavior:**
Application windows should stay on the prefered screen as decided & with the prefered screen size. A sleep or lock screen state should not impact it. 

**Other Notes:**

**Comment by linuxgnuru** [comment]
What GPU and monitors are you using and how are they connected?

**Comment by anuragbhatia** [comment]
GPU: NVIDIA GeForce GTX 1650
Monitors: Samsung LU28R55 (connected via display port) and a old DELL ST2220M (connected via HDMI-DVI cable)

The processor on the machine is AMD Ryzen 5 5600X

**Comment by linuxgnuru** [comment]
I'm wondering if there might be an issue with the HDMI-DVI connection. Do you have another monitor you can use that doesn't have DVI you could test with (like a spare tv)

**Comment by anuragbhatia** [comment]
Issue fixed on it's own. Might be due to some packages which are updated recently. Cannot point now to what exactly caused it but since it's fixed, I am closing this for now. 

Thanks for help @linuxgnuru

**Comment by disconn3ct** [comment]
This is happening to me also. It pushes all of the non-exception windows around, mostly to the non-primary (but lower indexed) monitor after the session is locked and both monitors sleep. No windows move around if tile mode is disabled, and excepted windows do not move.

I'm not sure if it matters, but my secondary monitor is excluded from workspaces and it is pushing them from the workspaced monitor to the non-workspaced.

Let me know if there is any other info I can add.

Quadro RTX 3000 Mobile / Max-Q
Left, secondary monitor, HDMI: LG 34UM69G-B 2560x1080@59.98
Right, primary monitor, USB-C to HDMI: Dell U2718Q 2560x1440@59.95 (native is 3840x2160), 6 workspaces

No hidpi daemon or scaling

**Comment by humunuk** [comment]
I had the same problem, for me this was the problem:

> I'm not sure if it matters, but my secondary monitor is excluded from workspaces and it is pushing them from the workspaced monitor to the non-workspaced.

After making workspaces "Multi-monitor behavior" to "Workspaces Span Displays" -> the problem disappeared.

**Comment by kramer9** [comment]
I second @sonicdmonkey 
 I have the same problem, maybe cosmic will fix it.
