### ISSUE TITLE
lemp10 suspend fan high / suspend not working, possible regression, related to ME and/or PCI/USB?

### ISSUE THREAD

**Issue by orangecms** [pop-os/pop#2450]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

When closing the lid, instead of suspending, the fans run at high speed.

**Steps to reproduce (if you know):**

close the lid

**Expected behavior:**

laptop should suspend

**Other Notes:**

Kernel:
```
Linux orangelemp 5.17.5-76051705-generic #202204271406~1653440576~22.04~6277a18 SMP PREEMPT Wed May 25 01 x86_64 x86_64 x86_64 GNU/Linux
```
cmdline
```
initrd=\EFI\Pop_OS-13e9361e-3b18-48f2-af15-8e083f43fce0\initrd.img root=UUID=13e9361e-3b18-48f2-af15-8e083f43fce0 ro systemd.show_status=false quiet splash loglevel=0
```
last boot log
```
May 30 01:34:33 orangelemp gnome-shell[2357]: [VERTICAL-OVERVIEW] disabled
May 30 01:34:33 orangelemp gnome-shell[2357]: An active wireless connection, in infrastructure mode, involves no access point?
May 30 01:34:33 orangelemp wpa_supplicant[875]: wlp0s20f3: CTRL-EVENT-DSCP-POLICY clear_all
May 30 01:34:33 orangelemp wpa_supplicant[875]: nl80211: deinit ifname=wlp0s20f3 disabled_11b_rates=0
May 30 01:34:34 orangelemp gnome-shell[2357]: Window manager warning: Overwriting existing binding of keysym 6f with keysym 6f (keycode 20).
May 30 01:34:37 orangelemp systemd[1]: Reached target Sleep.
May 30 01:34:37 orangelemp systemd[1]: Starting System Suspend...
May 30 01:34:37 orangelemp systemd-sleep[13093]: Entering sleep state 'suspend'...
May 30 01:34:37 orangelemp kernel: PM: suspend entry (s2idle)
May 30 01:34:37 orangelemp kernel: Filesystems sync: 0.007 seconds
May 30 01:34:38 orangelemp kernel: Freezing user space processes ... (elapsed 0.003 seconds) done.
May 30 01:34:38 orangelemp kernel: OOM killer disabled.
May 30 01:34:38 orangelemp kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
May 30 01:34:38 orangelemp kernel: printk: Suspending console(s) (use no_console_suspend to debug)
May 30 01:34:38 orangelemp kernel: PM: pci_pm_suspend(): hcd_pci_suspend+0x0/0x30 returns -16
May 30 01:34:38 orangelemp kernel: PM: dpm_run_callback(): pci_pm_suspend+0x0/0x190 returns -16
May 30 01:34:38 orangelemp kernel: xhci_hcd 0000:00:14.0: PM: failed to suspend async: error -16
May 30 01:34:38 orangelemp kernel: PM: Some devices failed to suspend, or early wake event detected
May 30 01:34:38 orangelemp kernel: mei_me 0000:00:16.0: hbm: dma setup response: failure = 3 REJECTED
May 30 01:34:38 orangelemp kernel: OOM killer enabled.
May 30 01:34:38 orangelemp kernel: Restarting tasks ...
May 30 01:34:38 orangelemp kernel: mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
May 30 01:34:38 orangelemp kernel: mei_pxp 0000:00:16.0-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:00:02.0 (ops i915_pxp_tee_component_ops [i915])
May 30 01:34:38 orangelemp acpid[824]: input device has been disconnected, fd 28
May 30 01:34:38 orangelemp /usr/libexec/gdm-x-session[2197]: (II) event25 - BT5.0-Audio (AVRCP): device removed
May 30 01:34:38 orangelemp /usr/libexec/gdm-x-session[2197]: (II) config/udev: removing device BT5.0-Audio (AVRCP)
May 30 01:34:38 orangelemp /usr/libexec/gdm-x-session[2197]: (**) Option "fd" "66"
May 30 01:34:38 orangelemp /usr/libexec/gdm-x-session[2197]: (II) UnloadModule: "libinput"
May 30 01:34:38 orangelemp /usr/libexec/gdm-x-session[2197]: (II) systemd-logind: releasing fd for 13:89
May 30 01:34:38 orangelemp kernel: done.
May 30 01:34:38 orangelemp kernel: thermal thermal_zone1: failed to read out thermal zone (-61)
May 30 01:34:38 orangelemp gsd-media-keys[2517]: Unable to get default sink
May 30 01:34:38 orangelemp kernel: video LNXVIDEO:00: Restoring backlight state
```

previous log:
```
May 29 02:13:05 orangelemp systemd[1]: Reached target Sleep.
May 29 02:13:05 orangelemp systemd[1]: Starting System Suspend...
May 29 02:13:05 orangelemp systemd-sleep[252725]: Entering sleep state 'suspend'...
May 29 02:13:05 orangelemp kernel: PM: suspend entry (s2idle)
May 29 02:13:05 orangelemp kernel: Filesystems sync: 0.007 seconds
May 29 02:13:06 orangelemp kernel: Freezing user space processes ... (elapsed 0.010 seconds) done.
May 29 02:13:06 orangelemp kernel: OOM killer disabled.
May 29 02:13:06 orangelemp kernel: Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
May 29 02:13:06 orangelemp kernel: printk: Suspending console(s) (use no_console_suspend to debug)
May 29 02:13:06 orangelemp kernel: PM: pci_pm_suspend(): hcd_pci_suspend+0x0/0x30 returns -16
May 29 02:13:06 orangelemp kernel: PM: dpm_run_callback(): pci_pm_suspend+0x0/0x190 returns -16
May 29 02:13:06 orangelemp kernel: xhci_hcd 0000:00:14.0: PM: failed to suspend async: error -16
May 29 02:13:06 orangelemp kernel: PM: Some devices failed to suspend, or early wake event detected
May 29 02:13:06 orangelemp kernel: mei_me 0000:00:16.0: hbm: dma setup response: failure = 3 REJECTED
May 29 02:13:06 orangelemp kernel: OOM killer enabled.
May 29 02:13:06 orangelemp kernel: Restarting tasks ...
May 29 02:13:06 orangelemp kernel: mei_hdcp 0000:00:16.0-b638ab7e-94e2-4ea2-a552-d1c54b627f04: bound 0000:00:02.0 (ops i915_hdcp_component_ops [i915])
May 29 02:13:06 orangelemp kernel: mei_pxp 0000:00:16.0-fbf6fcf1-96cf-4e2e-a6a6-1bab8cbe36b1: bound 0000:00:02.0 (ops i915_pxp_tee_component_ops [i915])
May 29 02:13:06 orangelemp kernel: done.
May 29 02:13:06 orangelemp kernel: thermal thermal_zone1: failed to read out thermal zone (-61)
May 29 02:13:06 orangelemp gsd-media-keys[79768]: Unable to get default sink
May 29 02:13:06 orangelemp acpid[832]: input device has been disconnected, fd 27
May 29 02:13:06 orangelemp /usr/libexec/gdm-x-session[79449]: (II) event25 - BT5.0-Audio (AVRCP): device removed
May 29 02:13:06 orangelemp /usr/libexec/gdm-x-session[79449]: (II) config/udev: removing device BT5.0-Audio (AVRCP)
May 29 02:13:06 orangelemp /usr/libexec/gdm-x-session[79449]: (**) Option "fd" "166"
May 29 02:13:06 orangelemp /usr/libexec/gdm-x-session[79449]: (II) UnloadModule: "libinput"
May 29 02:13:06 orangelemp /usr/libexec/gdm-x-session[79449]: (II) systemd-logind: releasing fd for 13:89
May 29 02:13:06 orangelemp kernel: video LNXVIDEO:00: Restoring backlight state
May 29 02:13:06 orangelemp kernel: PM: suspend exit
```

**Comment by jacobgkau** [comment]
Also, have you opened a [support ticket](https://support.system76.com/) about this issue yet? The support team can help troubleshoot suspend/resume issues on System76 hardware.

**Comment by orangecms** [comment]
> Also, have you opened a [support ticket](https://support.system76.com/) about this issue yet? The support team can help troubleshoot suspend/resume issues on System76 hardware.

Yea, I just created a ticket and referenced the issue here since there is only a small text input and I cannot revisit it as I can here to add more information and share the issue with other community members. :-)

**Comment by orangecms** [comment]
> Your issue title includes `possible regression`. When did the issue start occurring/after what changes do you believe the regression occurred?

Thank you for the quick response, and yea, I hadn't described that enough, sorry! The symptom had occurred early on when I had just received the laptop, and it was then gone when I upgraded. Unfortunately I do not have logs from them, and IIRC, I hadn't seen those error logs then. However, it was a different kernel, firmware and OS version, so a lot of parts have moved. From a detailed perspective, it might be wrong to call this a regression. Feel free to edit the issue title. Thank you!

**Comment by orangecms** [comment]
Addendum: I have a suspicion that this is related to having a USB-C charger connected. I just tried to suspend a few times without a charger and it works fine. When I use the barrel plug charger, from all I remember, suspend also works fine. So if anyone else faces this issue, they know a workaround. I have a desk where I have installed the charger that came with the laptop and when I'm travelling, I carry a USB-C charger with me, which had worked fine until recently, though I don't know what exactly changed to start causing the issue.

**Comment by mattzuba** [comment]
FWIW, I have a new Lemur Pro (as of last Thursday) and this is happening to me as well - it really sucks when I put the laptop in my backpack for a motorcycle ride home - this thing gets hot in there.  I have to remember to power off before I go home for the day so I don't chance it.

**Comment by orangecms** [comment]
Returned from a week of travel, and I just had it happen again back home, where I'm using Bluetooth to play audio. A similar suspicion was raised in reply to my support ticket. Unfortunately, it is not public, so here I'm copying what I just replied today:

> I also have a suspicion that this is related to Bluetooth. I frequently use my Bluetooth audio receiver here at home to play music on it. And when I was not using Bluetooth the other week when travelling, the suspend issue hadn't occurred. So the fix would be for the kernel or some systemd hook to turn it off before trying to enter suspend? Doing it manually is quite inconvenient, especially with the default GNOME utilities in Pop!_OS that make so many things hard to access. Could you offer a systemd unit for that as a workaround?

Addendum: It happens that I sometimes have to turn off and on again the Bluetooth adapter in order to be able to connect to my audio device again. Might be related. Scanning for devices still works fine, though.

**Comment by leviport** [comment]
This may have been fixed by https://github.com/pop-os/default-settings/pull/140

Once you have installed that update, please let us know if the problem persists.

**Comment by orangecms** [comment]
No way... that's what I had in mind, heh - thank you! I'll see if it works fine and report back in a few days. Saving the rf state would be cool, yea, I saw the comment, but that's the least of an issue compared to having to boot and reopen things anew. System76 just rocks! :rocket:

**Comment by orangecms** [comment]
Seems okay now, thank you for the quick workaround! Closing :)

**Comment by mattzuba** [comment]
This happens to me when I have no Bluetooth devices connected.  Could be a
Bluetooth driver issue though.

Thanks,

Matt Zuba

**Comment by usamasindhu** [comment]
It's still happening to me. Can anyone help me to fix this
