### ISSUE TITLE
Problems with the Launcher

### ISSUE THREAD

**Issue by Odin000** [pop-os/pop#2453]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Os Launcher

**Issue/Bug Description:**
pressing the super key is not running the launcher when:
-> running video in full screen.
-> having the focus on submenus from the to panel.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
This is on purpose. The launcher is not permitted to show when in a fullscreen window, such as a video game.

**Comment by senntore** [comment]
@mmstick was it removed in recent update?
I'm so used to using the launcher when using applications/games in fullscreen view(unless I'm remembering wrong). 
Removing it in fullscreen view decreases the use case of the super key(as a global hotkey).

Cosidering that both application library & window switcher requires two key presses(Super+A & Suber+Tab) when comapred to launcher(Super) for same function .

Can we somehow enable it or have a choice?

**Comment by Odin000** [comment]
It would be nice to have a setting to control that, cause I'm not a gamer at all, and feel a little restricted in my use of the launcher.

**Comment by mmstick** [comment]
I could add a setting. There were complaints about this appearing mid-game

**Comment by Odin000** [comment]
Thanx alot, you guys are awsome
