### ISSUE TITLE
Wayland breaks authentication with applications

### ISSUE THREAD

**Issue by stratacast** [pop-os/pop#246]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 18.04
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
gnome-session-wayland, evolution, gnome online accounts

**Issue/Bug Description**
Wayland seems to prevent applications from having access to a way of storing passwords and auth tokens. This prevents signing into accounts in applications such as Evolution (example, setting up a gmail account), as well as online accounts (Nextcloud account is not persistent and requires login at signing in)

**Steps to reproduce (if you know)**
Install gnome-session-wayland and at login select GNOME or Pop on wayland. Set up an online account or use Evolution or some other app that requires access to the password management system. 

**Expected behavior**
Account creation in applications is successful and credentials are stored in the proper keyring.

**Other Notes**
This issue does not happen with Xorg. Additionally, this issue does not affect Wayland on Fedora. I had a semi-related issue to accounts being created on Kubuntu and there it seemed to be AppArmor related, so I wonder if there is perhaps some conflict here too with AppArmor policies that especially conflict with Wayland?

**Comment by brs17** [comment]
Pop!_OS 18.04 ships by default with Xorg. We are not currently working on Wayland compatibility. Since you had similar issues on Kubuntu it sounds like this is an upstream issue in Ubuntu/AppArmor. I would recommend filing this issue upstream with one of those projects.
