### ISSUE TITLE
Device heats up in standby

### ISSUE THREAD

**Issue by BanorHlaalu** [pop-os/pop#2460]
**Distribution (run `cat /etc/os-release`):**
22.04
Lemur Pro
- 4.7 GHz i7-1165G7 (12MB Cache – 4 Cores – 8 Threads)
- 16 GB  Dual Channel DDR4 at 3200 MHz (2 x 8GB)
- 1 TB PCIe Gen4 Seq Read: 7,000 MB/s, Seq Write: 5,000 MB/s
- 14.1" Matte 1080p FHD Display
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not identified

**Issue/Bug Description:**
Machine heats up upon standby until touching it causes discomfort (approx. > 60°C), fans max out,
Refuses to wake up from sleep (screen stays dark when opening the lid).

**Steps to reproduce (if you know):**
Close lid to initiate standby (happens approx 10% of the time).

**Expected behavior:**
Go to standby.
Wake up from standby.

**Other Notes:**
I haven't figured out what application causes the behavior.
The only solution so far has been to force  a shutdown using the power button.

**Comment by leviport** [comment]
Sounds like it's not entering suspend mode at all. Do you have any bluetooth devices paired when trying to suspend?

**Comment by leviport** [comment]
It may be related to bluetooth then. We're testing a potential fix for bluetooth-related suspend issues here: https://github.com/pop-os/default-settings/pull/140

**Comment by BanorHlaalu** [comment]
Thank you. I got it. Will report back if issue persists.

**Comment by BanorHlaalu** [comment]
Reporting back anyway. The issue has been resolved. Thanks!
