### ISSUE TITLE
Tile Window and Launcher are not Working on Spotify 

### ISSUE THREAD

**Issue by Odin000** [pop-os/pop#2462]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**`flatpak info com.spotify.Client`**

Spotify - Online music streaming service

          ID: com.spotify.Client
         Ref: app/com.spotify.Client/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.1.84.716.gc5f8b819
     License: LicenseRef-proprietary=https://www.spotify.com/us/legal/end-user-agreement/
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 2.0 MB
     Runtime: org.freedesktop.Platform/x86_64/21.08
         Sdk: org.freedesktop.Sdk/x86_64/21.08

      Commit: 51df931abc1fca310d736d61acd178f063d98f63d5b4a769c2c15eff5234c8c3
      Parent: 4837437e1164c28ffd998a3ba8d1092a851321ce7e1f8880165ec41fbe760af2
     Subject: use same colors as the original icon (0b61f264)
        Date: 2022-05-22 03:27:21 +0000

**Issue/Bug Description:**
after last update Tile Window and Launcher are not working on the app anymore as if Spotify is a video running in full screen mode.
open Spotify in Tile Window mode:
 - press super key, nothing happens
 - bring another window to the workspace keeps spotify in fullscreen  in the background and the new window tiled over it.

**Steps to reproduce (if you know):**

**Expected behavior:**
 

**Other Notes:**

**Comment by leviport** [comment]
The Spotify Flatpak seems to be working fine for me. Are you using the Flatpak version? Could you include output from these two commands?
```
apt policy spotify
```
```
flatpak info com.spotify.Client
```

**Comment by Odin000** [comment]
it's Flatpak, I just updated the output above.

**Comment by leviport** [comment]
Can you check your floating window exception list and make sure Spotify isn't added there?

**Comment by Odin000** [comment]
it's not on the list.

**Comment by Odin000** [comment]
I removed the app and deleted this directory `~/.var/app/com.spotify.Client/` and reinstalled it. and it's working fine again.
thanx a lot.

**Comment by Odin000** [comment]
now the problem is back again. 
any thought on why this could even happen ?

**Comment by leviport** [comment]
Still kinda sounds like it's getting toggled into floating mode somehow. With the Spotify window active, what happens if you hit `Super` + `Y` ?

**Comment by Odin000** [comment]
nothing at all, it acts the same if in Tile or normal mode.
for me it's acting like Youtube in fullscreen.

**Comment by leviport** [comment]
Strange, I'm not sure what would cause that. I can't get my Spotify window to fullscreen like that at all. F11, maximize, and even Spotify's fullscreen player mode thing all still tile as I would expect.

Are you using any non-default Gnome shell extensions?

**Comment by Odin000** [comment]
yeah, but the behavior stays the same even if I shot them all down.

**Comment by leviport** [comment]
Did you restart gnome-shell after turning them off? Quickest way to do so is Alt + F2, `r`, Enter

**Comment by Odin000** [comment]
still the same !

**Comment by leviport** [comment]
The only remaining thing I can think of is to create a new user account and try to reproduce it with a fresh config. If there are clear steps to reproduce it, we can probably identify why it's happening.

**Comment by Odin000** [comment]
I tried to reproduce it on a new user without any success so far. 
so am gonna close the issue and thank you a lot for your help

**Comment by Odin000** [comment]
To fix the problem, I edited $HOME/.var/app/com.spotify.Client/config/spotify/prefs and commented out some lines related to “window”:
```

app.window.position.saved=true
# app.window.position.height=1080
app.autostart-mode="off"
autologin.canonical_username="9brywfc2l2xk9b6ow86hxcjym"
storage.last-location="/home/odino/.var/app/com.spotify.Client/cache/spotify/Storage"
# app.window.position.width=2560
core.clock_delta=0
app.last-launched-version="1.1.84.716.gc5f8b819"
app.autostart-configured=true
```
this worked like a charm.
