### ISSUE TITLE
A pinned application on the dock goes behind the Show Applications button

### ISSUE THREAD

**Issue by gabluc** [pop-os/pop#247]
**Distribution** Pop!_OS 18.04 LTS
 
 
 **Related Application and/or Package Version**  gnome-shell 3.28.1-0ubuntu2

**Issue/Bug Description**
If you add a lot of applications to favourites, the last one on the dock goes behind the `Show Applications` button.

**Steps to reproduce**
Add a lot of applications to favourites. I've added thirteen. For me, it's the number of pinned applications before the dock goes smaller again.

Here's a screenshot:
![dock](https://user-images.githubusercontent.com/15315645/39468427-35c1288a-4d33-11e8-9748-d8c83f15c293.png)

**Comment by brs17** [comment]
Thanks for filing this issue @gabluc. This issue has already been filed in the gnome-shell-theme repo, https://github.com/pop-os/gnome-shell-theme/issues/23. I'm going to close this issue as it is a duplicate.
