### ISSUE TITLE
Conflict with nvidia-prime

### ISSUE THREAD

**Issue by sztal** [pop-os/pop#2485]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

system76-power:
  Installed: 1.1.21~1655316585~22.04~54179be
  Candidate: 1.1.21~1655316585~22.04~54179be
  Version table:
 *** 1.1.21~1655316585~22.04~54179be 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

nvidia-prime:
  Installed: (none)
  Candidate: 0.8.17.1
  Version table:
     0.8.17.1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu jammy/main i386 Packages

LINUX KERNEL INFO:
Linux pop-os 5.17.5-76051705-generic #202204271406~1655476786~22.04~62dd706 SMP PREEMPT Fri Jun 17 16 x86_64 x86_64 x86_64 GNU/Linux

**Issue/Bug Description:**

I recently installed Pop!_OS on a workstation (so no AC/battery) and for a while it everything was good. However, today after a standard update I got the following error when trying to run `sudo apt upgrade`:

```
The following packages have unmet dependencies:
 system76-power : Conflicts: nvidia-prime
```

The problem is that `nvidia-prime` is not installed (as documented above) and when I try to install it I get another error:

```
The following packages have unmet dependencies:
 pop-desktop : Depends: pop-session but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
```

I also get the same error when I try to uninstall `system76-power`, which is probably what I should do, since the machine is not a laptop and does not need any firmware for managing battery and power.

So the questio is, how can I solve this problem without reinstalling the system and making sure `system76-power` does not get installed.

**Steps to reproduce (if you know):**

**Expected behavior:**

`sudo apt update && sudo apt upgrade` should run without errors.

**Other Notes:**

**Comment by leviport** [comment]
Purging and reinstalling the Nvidia driver will probably clear it up:
```
sudo apt purge ~nnvidia
sudo apt autoremove && sudo apt clean
sudo apt install nvidia-driver-515
```
and then reboot

**Comment by vinimmelo** [comment]
I solved it by installing a new version of the Nvidia driver (nvidia-515), and then I could upgrade my other dependencies.

**Comment by adamrt** [comment]
I tried the solutions above but was getting tons of errors referring to `libglib2.0-0:i386`.

The following worked for me:
```
sudo dpkg --configure -a
sudo apt --fix-broken install
sudo apt update
sudo apt install nvidia-driver-515 # most recent driver
sudo apt upgrade
```

After `--fix-broken` I still wasn't able to run `apt upgrade` until I installed the new nvidia driver.

**Comment by raphaelchristin** [comment]
> I tried the solutions above but was getting tons of errors referring to `libglib2.0-0:i386`.
> 
> The following worked for me:
> 
> ```
> sudo dpkg --configure -a
> sudo apt --fix-broken install
> sudo apt update
> sudo apt install nvidia-driver-515 # most recent driver
> sudo apt upgrade
> ```
> 
> After `--fix-broken` I still wasn't able to run `apt upgrade` until I installed the new nvidia driver.

This solution did it for me too, thanks!

**Comment by sirey-tracing** [comment]
> I solved it by installing a new version of the Nvidia driver (nvidia-515), and then I could upgrade my other dependencies.

simply clever, thanks :) it works for me ; 
pop-os 22.04 LTS,  i7 with quadro t500 graphics here

**Comment by manyet1k** [comment]
I'm still having this issue. I'm on Pop 22.04 w/ kernel 6.0.12-76060006-generic, and `nvidia-driver-515` is installed. 

```
$ sudo apt install nvidia-prime
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: pop-session but it is not going to be installed
               Recommends: io.elementary.sideload but it is not installable
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.


```

I've tried @adamrt's solution but nothing happened; `dpkg` didn't configure any packages and the other commands didn't update or install anything. Afraid that I could break things further, I didn't reinstall the drivers as @leviport suggested, and I believe there should be a different solution.

**Comment by leviport** [comment]
515 is no longer the most recent driver. Installing the 525 driver might fix it. I don't have any dependency problems with the 525 driver installed.

**Comment by TheMemeSniper** [comment]
i have 525 installed but still getting this error
```
$ sudo apt install nvidia-prime
[sudo] password for kaitlin: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 pop-desktop : Depends: pop-session but it is not going to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
```

**Comment by manyet1k** [comment]
Yeah, updating to 525 doesn't change anything. However, I was told in the Mattermost that this was intended, and `switcherooctl` should be used instead. `switcherooctl launch` does the same thing as `prime-run`.

**Comment by TheMemeSniper** [comment]
`switcherooctl` seems to be installed by default. thanks!

**Comment by pktiuk** [comment]
In my case Updating nvidia driver from 530 to 535 fixed the issue.

**Comment by Kaveh8** [comment]
The same issue with `nvidia-driver-535`

**Comment by mmstick** [comment]
> The same issue with `nvidia-driver-535`

This is not an issue though. System76 Power provides this capability.

**Comment by johnmalek312** [comment]
Facing the same issue, the above approach didn't fix it
