### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by PGQT** [pop-os/pop#2487]
sound card on my laptop is realtek alc298.

Cat /etc/os-release:

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

Describe issue:
Sound does not work on internal laptop speakers. laptop is samsung galaxybook pro 360 13.3" with core i7 1165g7
    sound card is realtek alc298
   Sound settings shows tiger lake-LP smart sound technology audio controller
sound settings shows appropriate output fluctuations from videos and music, but no sound reaches speakers.

to reproduce: install pop_os on laptop and try running sound from onboard speakers.

expected behavior:
sound should play from built in speakers.

Other Notes:
sound works perfectly through connected bluetooth devices, and through 3.5mm audio jack.
sound is not muted, and alsa mixer has been used to ensure this.

**Comment by miaoerwu** [comment]
**_[AMD] Family 17h (Models 10h-1fh) HD Audio Controller_** has the same problem. My laptop is HP EliteBook 865 16 inch G9 Notebook PC

**Comment by Gu7z** [comment]
+1, Same problem here  :/

**Comment by miaoerwu** [comment]
It looks like the problem has been solved. After upgrading the linux kernel to 5.18, the speakers are working fine.

**Comment by PGQT** [comment]
the issue is persisting for me.

**Comment by fabrizioschiano** [comment]
I have the same problem but I cannot upgrade to kernel 5.18 because otherwise it breaks my NVIDIA drivers compatibility :( 

```
lspci -v | grep -i audio 
00:1f.3 Multimedia audio controller: Intel Corporation Device 43c8 (rev 11)
	Kernel driver in use: sof-audio-pci-intel-tgl
01:00.1 Audio device: NVIDIA Corporation Device 228b (rev a1)
```
I am on this kernel 

```
uname -r
5.15.15-76051515-generic
```
Any idea on how to resolve this? 

I tried  with no luck: 

```
sudo apt reinstall pipewire pipewire-pulse

systemctl --user --now enable pipewire pipewire-pulse

reboot
```

**Comment by fabrizioschiano** [comment]
Actually I have sound problems again and I need to solve again this problem.

**Comment by TheAwiteb** [comment]
> Actually I have sound problems again and I need to solve again this problem.

Same here

**Comment by PGQT** [comment]
Sound issue is persisting for me

**Comment by TheAwiteb** [comment]
I found out that my problem is with the new kernel version, which is 6.0.3, after doing a [refresh](https://www.techrepublic.com/article/popos-refresh-install/) of the system I [prevented it](https://askubuntu.com/questions/1131060/how-to-exclude-kernel-updates-from-unattended-upgrades) from being updated. I solved the problem

**Comment by millette** [comment]
I'm also using linux kernel `6.0.3-76060003-generic` and lost HDMI sound only. Still haven't found a fix.

**Comment by leviport** [comment]
We're currently testing the 6.0.6 kernel, which we believe should fix this problem on affected systems: https://github.com/pop-os/linux/pull/188

This hasn't completed testing yet, but if you'd like to give it a try, you can add the testing branch with this command:
```
apt-manage add popdev:linux-6.0.6
```
Then install updates and reboot, and the 6.0.6 kernel will be installed.

**Comment by PGQT** [comment]
my sound was not working, and my sound card had disappeared recently.  Following @leviport directions, i installed the 6.0.6 kernel. My sound card has since re-appeared, but the issue with non-functional internal speakers persists.

**Comment by PedroMTSilva** [comment]
> We're currently testing the 6.0.6 kernel, which we believe should fix this problem on affected systems: [pop-os/linux#188](https://github.com/pop-os/linux/pull/188)
> 
> This hasn't completed testing yet, but if you'd like to give it a try, you can add the testing branch with this command:
> 
> ```
> apt-manage add popdev:linux-6.0.6
> ```
> 
> Then install updates and reboot, and the 6.0.6 kernel will be installed.
> 
> Once you're ready to remove that testing branch, run this command:
> 
> ```
> apt-manage remove popdev-linux-6-0-6
> ```

This worked for me! I have audio again after upgrading to the new kernel test version. At first, after the update, it wasn't working, but then i just had to change the output audio device. Thanks for the help!

**Comment by ismaina** [comment]
> We're currently testing the 6.0.6 kernel, which we believe should fix this problem on affected systems: [pop-os/linux#188](https://github.com/pop-os/linux/pull/188)
> 
> This hasn't completed testing yet, but if you'd like to give it a try, you can add the testing branch with this command:
> 
> ```
> apt-manage add popdev:linux-6.0.6
> ```
> 
> Then install updates and reboot, and the 6.0.6 kernel will be installed.
> 
> Once you're ready to remove that testing branch, run this command:
> 
> ```
> apt-manage remove popdev-linux-6-0-6
> ```

@leviport Thanks.. This worked for me.

**Comment by fabrizioschiano** [comment]
How to check on which kernel I am? My numbers seem with respect to yours. If I do 
```
uname -r
```
I get
```
5.15.15-76051515-generic
```

**Comment by Basanta78** [comment]
> > We're currently testing the 6.0.6 kernel, which we believe should fix this problem on affected systems: [pop-os/linux#188](https://github.com/pop-os/linux/pull/188)
> > This hasn't completed testing yet, but if you'd like to give it a try, you can add the testing branch with this command:
> > ```
> > apt-manage add popdev:linux-6.0.6
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then install updates and reboot, and the 6.0.6 kernel will be installed.
> > Once you're ready to remove that testing branch, run this command:
> > ```
> > apt-manage remove popdev-linux-6-0-6
> > ```
> 
> @leviport Thanks.. This worked for me.

Tried it.. But still the issue persists. Any other solutions?

**Comment by gray380** [comment]
I`ve solved the issue by rolling back to 6.0.2-76060002-generic

**Comment by ydhnwb** [comment]
I also have this problem on Asrock H610m hdv m2 r2 motherboard.
When I choise Line Out, the audio spectrum seems to be work but no sound reach the speaker. (I am using usb speaker)

**Comment by sayajin101** [comment]
> hasn't completed testing yet, but if you'd like to give it a try, you can add the testing branch with thi

My question regarding this is if you remove the testing branch, will the audio stop working again?

I have the same issue here, audio disappeared this morning after a cold boot.
My hardware is the following:
`
lspci -v | grep -i audio
0000:00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
	Subsystem: Dell Tiger Lake-LP Smart Sound Technology Audio Controller
	Kernel driver in use: sof-audio-pci-intel-tgl
`

**Comment by leviport** [comment]
>My question regarding this is if you remove the testing branch, will the audio stop working again?
Only

**Comment by leviport** [comment]
>My question regarding this is if you remove the testing branch, will the audio stop working again?

Only if you also downgrade the kernel, and only if you do so before the update is released.

**Comment by leviport** [comment]
The 6.0.6 kernel has been released. Normal updates should get HD audio working again on most machines. 

If you've added that testing source, apt will probably 404 on it when you try to run updates, so you'll want to remove it before updating:
```
apt-manage remove popdev-linux-6-0-6
```

**Comment by gray380** [comment]
Confirm, it works for
```
lspci -v | grep  Audio -A2
00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
	Subsystem: Dell Tiger Lake-LP Smart Sound Technology Audio Controller
	Flags: bus master, fast devsel, latency 64, IRQ 168
	Memory at 601d190000 (64-bit, non-prefetchable) [size=16K]
```
Thanks.

**Comment by fabrizioschiano** [comment]
I solved my problem by moving to ubuntu 22.04 and getting out of POP_OS. Now my laptop is working well again.

**Comment by alexheinrich** [comment]
> update the kernel to 6.0.6-76060006-generic but the issue still exists. audio spectrum on settings seems to work but no sound reach the speaker (usb speaker). only works on my headphone
> 
> ![image](https://user-images.githubusercontent.com/26734262/200497439-86ef14d2-74d3-47f4-9146-f1de070d6d34.png)

I have the same issue unfortunately, also with the same kernel version

**Comment by ydhnwb** [comment]
My device use Realtek ALC897 7.1 CH HD Audio Codec. But it only shows Intel Audio. Is it means it fails to detect my realtek?

**Comment by NOOBLINUXUSER** [comment]
is there any solution to this? upgraded to 6.0.6 as some people have regained audio output. Mine didn't.

**Comment by NOOBLINUXUSER** [comment]
any solutions guys? this happened to just today, i switched to usb headphones, and when i tried to get back into my analog audio. this happened. it works well on my windows install.
This is the output on ``pw-top``
![image](https://user-images.githubusercontent.com/66922885/201480452-b88aedad-b42e-4a70-b001-2c0f588d091b.png)
And this is what ```● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-11-13 02:55:49 +06; 5h 47min left
TriggeredBy: ● pipewire.socket
   Main PID: 1360 (pipewire)
      Tasks: 2 (limit: 18985)
     Memory: 13.2M
        CPU: 1.489s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─1360 /usr/bin/pipewire

Nov 13 02:55:49 pop-os systemd[1344]: Started PipeWire Multimedia Service.
Nov 13 02:55:49 pop-os pipewire[1360]: mod.rt: Can't find xdg-portal: (null)
Nov 13 02:55:49 pop-os pipewire[1360]: mod.rt: found session bus but no portal``` 
```systemctl --user status pipewire``` shows

**Comment by NOOBLINUXUSER** [comment]
This is on the recovery partition
![image](https://user-images.githubusercontent.com/66922885/201481527-8f18cae6-c7f8-401b-a84f-505cd48dbb0d.png)
![image](https://user-images.githubusercontent.com/66922885/201481567-059f0ebf-6f42-49c7-bf5a-7dbd7b96387e.png)

exact issue on the  recovery partition. but its kernal is 5.17. i just upgraded to 6.0.6

**Comment by NOOBLINUXUSER** [comment]
solved
```options snd_hda_intel model=headset-mode```
and a reboot
found it here https://bbs.archlinux.org/viewtopic.php?id=273805
why is this not default, what did pipewire default config lack that this needed to be done?

**Comment by NOOBLINUXUSER** [comment]
> My device use Realtek ALC897 7.1 CH HD Audio Codec. But it only shows Intel Audio. Is it means it fails to detect my realtek?

try this

**Comment by NOOBLINUXUSER** [comment]
> The issue still exists for my setup as well

try this?

**Comment by ydhnwb** [comment]
i found something.
pc mostly have 2 port, front side and backside.

i have audio port (red, green) in front and backside.
i put speaker on the back. when there are no other device use the audio port, the speaker works.'
when headphone is plugged in on the front, only the headphone will works

**Comment by NOOBLINUXUSER** [comment]
> solved
> 
> `cat /etc/modprobe.d/audio-jack.conf` `options snd_hda_intel model=headset-mode ` and a reboot found it here https://bbs.archlinux.org/viewtopic.php?id=273805 why is this not default, what did pipewire default config lack that this needed to be done?

@ydhnwb  can you try this and report back?

**Comment by ydhnwb** [comment]
> > solved
> > `cat /etc/modprobe.d/audio-jack.conf` `options snd_hda_intel model=headset-mode ` and a reboot found it here https://bbs.archlinux.org/viewtopic.php?id=273805 why is this not default, what did pipewire default config lack that this needed to be done?
> 
> @ydhnwb can you try this and report back?

there are no such files called audio-jack.conf inside that directory

![image](https://user-images.githubusercontent.com/26734262/202162192-88366fd3-3a8b-46ac-b6bd-7d6bba16d333.png)

**Comment by NOOBLINUXUSER** [comment]
> > > solved
> > > `cat /etc/modprobe.d/audio-jack.conf` `options snd_hda_intel model=headset-mode ` and a reboot found it here https://bbs.archlinux.org/viewtopic.php?id=273805 why is this not default, what did pipewire default config lack that this needed to be done?
> > 
> > 
> > @ydhnwb can you try this and report back?
> 
> there are no such files called audio-jack.conf inside that directory
> 
> ![image](https://user-images.githubusercontent.com/26734262/202162192-88366fd3-3a8b-46ac-b6bd-7d6bba16d333.png)

ah sorry i wasnt clear, you have to create that config.
it looks like this, the easiest way (for me) is to use vim.
![image](https://user-images.githubusercontent.com/66922885/202244464-dd39bfe2-3a2c-4024-a371-145131046f0c.png)
I believe there is a lua config thats is disabled by default but can be configured, just adding config files adds it to the main config file which the systemd uses.

**Comment by gayansanjeewa** [comment]
Only thing work for me was reinstalling all the 3 services and re-enabling them

```shell
sudo apt reinstall pipewire pipewire-bin pipewire-pulse
systemctl --user --now enable pipewire pipewire-pulse
```

**Comment by NOOBLINUXUSER** [comment]
what version of pop os are you on right now? pipewire is the only default
in the latest version 22.04 since 21.10

**Comment by alexheinrich** [comment]
> Only thing work for me was reinstalling all the 3 services and re-enabling them
> 
> ```shell
> sudo apt reinstall pipewire pipewire-bin pipewire-pulse
> systemctl --user --now enable pipewire pipewire-pulse
> ```

Worked for me too

**Comment by PGQT** [comment]
The problem is still here for me.  None of these suggestions have made any difference.  But audio still works if i boot into windows.

**Comment by ydhnwb** [comment]
Yeah me too.
I need to plug out headset speaker cable in order to listen on my usb speaker.

**Comment by NOOBLINUXUSER** [comment]
> Yeah me too. I need to plug out headset speaker cable in order to listen on my usb speaker.

tried pulseaudiomixer? ```sudo apt install pavucontrol```

**Comment by NOOBLINUXUSER** [comment]
> The problem is still here for me. None of these suggestions have made any difference. But audio still works if i boot into windows.

still having no audio? or audio crackling?

**Comment by PGQT** [comment]
> > Yeah me too. I need to plug out headset speaker cable in order to listen on my usb speaker.
> 
> 
> 
> tried pulseaudiomixer? ```sudo apt install pavucontrol```

I have tried pavucontrol. No dice.

**Comment by PGQT** [comment]
> > The problem is still here for me. None of these suggestions have made any difference. But audio still works if i boot into windows.
> 
> 
> 
> still having no audio? or audio crackling?

Absolutely no audio through built in speakers.

**Comment by NOOBLINUXUSER** [comment]
What's the actual speaker?, and also did you try to make the intel audio =
headphone thingy like i did ?. then a system reboot and systemctl update?
and also the newer kernel update removed all my audio problems all together
and now can auto detect any jack i put in, i use MOC player so previously
if i changed audio source, it would have just crashed (pulseaudio didn't
when pop used to use them) now pipewire doesn't either. maybe try a kernal
update or see if your the same version as i am running on?
6.0.6-76060006-generic is what i run.

**Comment by PGQT** [comment]
updated this afternoon, and my problem is resolved. sound seems to work correctly now from my built-in speakers.

**Comment by smiledra** [comment]
I think I have a similar problem -- fresh install of pop os 22.04 with Nvidia 525 and kernel 6.0.12; the built-in audio works but not the audio through HDMI. It can be recognized through `aplay` and alsamixer and plays normally, but in the setting GUI and in pipewire (e.g., in pavucontrol) the HDMI card does not show up. I have an HP omen 15 laptop with AMD CPU and I am using NVIDIA graphics (the only one with a usable HDMI connection).

I have tried everything in this thread without getting it to work. Please let me know if I can provide more information (I'm relatively new to posting issues) or start a new issue. Thanks.

**Comment by bbaster** [comment]
> solved
> 
> `cat /etc/modprobe.d/audio-jack.conf` `options snd_hda_intel model=headset-mode ` and a reboot found it here https://bbs.archlinux.org/viewtopic.php?id=273805 why is this not default, what did pipewire default config lack that this needed to be done?

I'm using Arch Linux but it fixed my issue, many thanks
