### ISSUE TITLE
Battery indicator not displaying correctly on login screen

### ISSUE THREAD

**Issue by PlugaruT** [pop-os/pop#249]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 ```
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
Maybe something related with `gnome-shell-extension-pop-battery-icon-fix` but I may be wrong.

**Issue/Bug Description**
The battery indicator is not displaying correct data on the login screen. It remains stuck with the percentage when the lid was closed.

**Steps to reproduce (if you know)**
Put the computer to sleep and charge it a little bit. Access the login screen and check battery indicator.

**Expected behavior**
The battery indicator should display the current battery level.

**Other Notes**

**Comment by Clae224** [comment]
I'm having the same issue. Running 18.04 on XPS 9360 8th gen. More info of my config in #258.

**Comment by cunctator00** [comment]
same issue here

**Comment by zhangandyx** [comment]
This is also happening for me on my Oryx Pro

**Comment by jrgermain** [comment]
This bug is almost definitely due to the fact that displaying the proper battery icon is reliant on a shell extension, which is not enabled on the lock screen. If we could get the icon to behave properly without the use of an extension then the issue should be resolved.
