### ISSUE TITLE
Reboot after installation fails and requires manual intervention

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#25]
_From @brs17 on October 11, 2017 18:18_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
Reboot after installation requires hard turn-off when remaining in the liveusb after installation completes. Error messages are displayed (see picture)

![img_20171010_105630](https://user-images.githubusercontent.com/7460774/31458716-1ef45c66-ae7e-11e7-8ade-90b78ae9de70.jpg)

**Steps to reproduce (if you know)**

Upon completion of install, user is prompted to keep exploring or reboot. If the user stays in the livecd and then manually reboots, when prompted to "remove the installation medium, then press ENTER" the machine will fail to reboot if the directions are followed properly.

**Expected behaviour**
Reboots normally

**Other Notes**

_Copied from original issue: pop-os/iso#140_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
