### ISSUE TITLE
NVIDIA graphics card not being recognized in Pop!_OS 22.04

### ISSUE THREAD

**Issue by genivalallan** [pop-os/pop#2508]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
IDK

**Issue/Bug Description:**
Dedicated NVIDIA graphics card is not being listed or recognized by the OS.
The system is using integrated graphics card, instead.

**Steps to reproduce (if you know):**
N/A

**Expected behavior:**
Expected Pop!_OS to use dedicated NVIDIA graphics card.

**Other Notes:**
I have a Dell Inspiron 14 laptop with integrated and dedicated **NVIDIA GeForce GT 740M** graphics cards.
I installed the Pop!_OS 22.04 NVIDIA system and noticed that it's using the integrated graphics card.
When ran `lspci | egrep "VGA|3D"` command, it shows only my integrated card
```
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
```
Under `Settings > About` it shows it's using `Mesa Intel® HD Graphics 4400 (HSW GT2)` driver.

Running `lspci` command under other system shows my NVIDIA card as expected
```
00:02.0 VGA compatible controller: Intel Corporation Haswell-ULT Integrated Graphics Controller (rev 09)
08:00.0 3D controller: NVIDIA Corporation GK208M [GeForce GT 740M] (rev a1)
```
I tried to reinstall the driver using the commands as indicated [here #2369](https://github.com/pop-os/pop/issues/2369#issuecomment-1118744282) with no luck

> Hi, recently I've got similar issue (nvidia kernel module not loaded and my second monitor not work) after upgrading kernel to 5.17.5. so I decide to reinstall nvidia driver, like what @linuxgnuru says with some adjustment like in this article https://support.system76.com/articles/login-loop-pop/#reinstall-nvidia-driver
```
sudo apt purge ~nnvidia # I change this to `sudo apt purge '^nvidia-*'`
sudo apt autoremove
sudo apt clean
sudo apt update
sudo apt full-upgrade
sudo apt install system76-driver-nvidia
sudo systemctl reboot
```
As far as I came to understand, there is an issue with linux kernel 5.17 and NVIDIA cards in Pop!_OS 22.04.

Is there any workaround I can do to have my NVIDIA card running?

**Comment by leviport** [comment]
Nvidia dropped support for GT7xx series in the 500 series of their driver. The 470 driver is still available on Pop, however. To install this, first purge Nvidia the way you mentioned above, then `sudo apt install nvidia-driver-470`. Your Dell likely doesn't benefit from any of the System76 packages that would be brought in by system76-driver-nvidia anyway.

**Comment by genivalallan** [comment]
> Nvidia dropped support for GT7xx series in the 500 series of their driver. The 470 driver is still available on Pop, however. To install this, first purge Nvidia the way you mentioned above, then `sudo apt install nvidia-driver-470`. Your Dell likely doesn't benefit from any of the System76 packages that would be brought in by system76-driver-nvidia anyway.

Thx, man!

That worked.
I have the 470 driver installed in other distro. I wasn't aware of the NVIDIA dropped support and driver update in Pop!_OS 22.04.
Now I have the driver installed and the controller listed by `lspci`.
