### ISSUE TITLE
[FEATURE] Include Raspberry PiServer in PopStore

### ISSUE THREAD

**Issue by blaggacao** [pop-os/pop#251]
There is a new kid in town, https://github.com/raspberrypi/piserver
Basically it is a PXE boot controller for a raspberry farm in your local network.
It would be nice to find a curated package in the Pop Store, if that's something that's in-scope...

**Comment by mmstick** [comment]
Looks easy enough to add to the proprietary repo. Since it has its own debian files, it's just a matter of adding the GitHub URL to the config and running `debrep build`.

**Comment by mmstick** [comment]
Next time the repo is updated, piserver will be there. It won't be in the store though, because that requires that the project has some appstream data (and debrep does not automatically create appstream files yet).
