### ISSUE TITLE
Bluetooth turned off after waking up from standby

### ISSUE THREAD

**Issue by Qwwertz** [pop-os/pop#2510]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
After waking up from sleep, Bluetooth is turned off, even though it had been on before putting the computer to standby.

**Steps to reproduce (if you know):**
Turn Bluetooth on, put computer to standby, wake computer up.

**Expected behavior:**
Bluetooth is in the same state as it was before standby

**Other Notes:**
computer: Thinkpad X1 Carbon Gen 9
Kernel: 5.17.5-76051705-generic

**Comment by n3m0-22** [comment]
Can you send me the output of `cat /lib/systemd/system-sleep/pop-default-settings_bluetooth-suspend`.

**Comment by n3m0-22** [comment]
May be fixed by https://github.com/pop-os/default-settings/pull/148

**Comment by Qwwertz** [comment]
Thank you very much for your quick response :+1:

**Comment by n3m0-22** [comment]
If you are still having issues with the new code the issue can be re-opened, and we can look into this further.

**Comment by timotESC** [comment]
I still experience this issue. I will try now the code, but just wanted to know if it happens only to me

**Comment by dmcskim** [comment]
I am experiencing this issue, but have the updated code. After suspend I lose bluetooth and cannot reactivate without a reboot. rfkill shows nothing blocked, btusb is displayed with lsmod, dmesg has a couple lines complaining:
---
Bluetooth: hci0: setting interface failed (110)
usb 1-10: Failed to suspend device, error -110
---
Bluetooth: hci0: Opcode 0x c03 failed: -110
Bluetooth: hci0: Failed to read MSFT supported features (-110)
---
Bluetooth: hci0: Opcode 0x c03 failed: -110
Bluetooth: hci0: MSFT extension not registered

**Comment by strikertushar19** [comment]
this issue is still happening same with me using ubuntu 22.04 jammy version

**Comment by leviport** [comment]
> this issue is still happening same with me using ubuntu 22.04 jammy version

This repo is for Pop!\_OS, not for Ubuntu. Ubuntu bugs should be reported elsewhere.
