### ISSUE TITLE
Thunderbolt stopped working after an automatic update on June 30th

### ISSUE THREAD

**Issue by hakro** [pop-os/pop#2525]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 

`uname -a`
Linux pop-os 5.17.15-76051715-generic #202206141358~1655919116~22.04~1db9e34 SMP PREEMPT Wed Jun 22 19 x86_64 x86_64 x86_64 GNU/Linux
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

`apt policy bolt`
bolt:
  Installed: 0.9.2-1
  Candidate: 0.9.2-1
  Version table:
 *** 0.9.2-1 500
        500 http://us.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

`sudo dmidecode -s system-product-name`
HP ZBook Studio x360 G5

Since an automated update on June30, Thunderbolt docks stopped being detected. No other changes have been made recently on the system. Nothing has changed on the BIOS either.
Only the power gets through. But monitors, USB devices, and Ethernet plugged in Thunderbolt are not detected.

Tried several docks at work, none of them worked.

This dock used to work before the June 30, but now is not detected at all.
`boltctl list -a`
 ○ HP, Inc. HP ZBook Studio G5
   ├─ type:          host
   ├─ name:          HP ZBook Studio G5
   ├─ vendor:        HP, Inc.
   ├─ uuid:          XXXXXXXX
   ├─ generation:    Thunderbolt 3
   ├─ status:        disconnected
   ├─ authorized:    Thu 30 Jun 2022 08:04:02 AM UTC
   ├─ connected:     Thu 30 Jun 2022 08:04:02 AM UTC
   └─ stored:        Tue 03 May 2022 02:43:46 PM UTC
      ├─ policy:     manual
      └─ key:        no

`boltctl list` returns nothing.

I've attached the result of `journalctl -u bolt` which shows logs before june 30th, when it was working, and after, when it started working.
[journalctl.txt](https://github.com/pop-os/pop/files/9102505/journalctl.txt)

Running `sudo boltctl config power-state on` returns : 
boltctl config: error: Property “PowerState” is not writable

And in the Thunderbolt area, I used to see my dock, but now I only have this : 

![2022-07-13_15-18](https://user-images.githubusercontent.com/3624853/178743084-b71d107e-b543-43a5-afcb-0a32ba3b68c2.png)

**Steps to reproduce (if you know):**
Just use a dock with an up to date PopOs 22.04

**Expected behavior:**
Thunderbolt dock should be detected and working as usual.

**Other Notes:**

**Comment by hakro** [comment]
Just a couple of minutes ago, I got a new firmware update notification, which I feel might fix the issue.

![2022-07-13_18-07](https://user-images.githubusercontent.com/3624853/178781991-0cf6c911-f0bf-4451-b31c-e5fe33409e4b.png)

Sadly, the update somehow got stack at some point, and I got this error : 

![2022-07-13_18-09](https://user-images.githubusercontent.com/3624853/178782141-0cbeafc7-759c-49c4-b742-3af7c4a276fe.png)

**Comment by hakro** [comment]
Turns out it was a BIOS issue with HP.
USB Type C was not getting detected any more, and found a solution on the HP forums.
For my case, the solution was to shutdown the laptop, and press & hold the power button for 30 seconds to flush.
After that, all worked fine.

**Comment by jonashackt** [comment]
For Thinkpad users running into the same problem. A hardware reset using a paper clip to press for 10 sec into the reset button hole on the Thinkpad's bottom did the trick ([as described here](https://bbs.archlinux.org/viewtopic.php?pid=2186894#p2186894) and [in this video](https://www.youtube.com/watch?v=AxUI5WKDr7s)). Really, no joke. Thunderbold Dock and USB-C charging now working again :)
