### ISSUE TITLE
System fail to boot if "Secure boot" enabled

### ISSUE THREAD

**Issue by ximian** [pop-os/pop#253]
**Distribution**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
linux-generic:
  Zainstalowana: 4.15.0.20.23
  Kandydująca:   4.15.0.20.23
  Tabela wersji:
 \*** 4.15.0.20.23 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description**
I cannot boot fresh Pop!_OS 18.04 LTS installation when "Secure boot" is enabled.
I'm getting "Selected boot image did not authenticate" error.

**Steps to reproduce (if you know)**
* Enable "Secure boot" in BIOS/UEFI settings
* Install Pop!_OS 18.04 LTS using Intel/AMD ISO with full disc encryption enabled
* Reboot
* System fail to load

**Expected behaviour**
System boot without problems

**Comment by brs17** [comment]
As stated on the iso download page, Pop!_OS cannot be currently used on Secure Boot systems.

**Comment by ximian** [comment]
It is stated that NVIDIA ISO cannot be used on Secure Boot systems. I was using Intel/AMD ISO.
