### ISSUE TITLE
v4l2loopback dkms module broken after 5.18.10 kernel release

### ISSUE THREAD

**Issue by mbainter** [pop-os/pop#2536]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 22.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
v4l2loopback-dkms:
  Installed: 0.12.5-1ubuntu5
  Candidate: 0.12.5-1ubuntu5
  Version table:
 *** 0.12.5-1ubuntu5 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

v4l2loopback-dkms cannot build against latest distributed kernel
```
$ sudo modprobe v42loopback
modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/5.18.10-76051810-generic
```
Module exists for older kernel
```
$ sudo dkms status
...
v4l2loopback/0.12.5, 5.17.15-76051715-generic, x86_64: installed
v4l2loopback/0.12.5, 5.17.5-76051705-generic, x86_64: installed (original_module exists)
```

Module can't be rebuilt:
```
$ sudo dkms autoinstall v4l2loopback
Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.10-76051810-generic/x86_64/dkms.conf for module v4l2loopback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
```

Uninstall and reinstall of v4l2loopback-dkms similarly says:
```
Preparing to unpack .../v4l2loopback-dkms_0.12.5-1ubuntu5_all.deb ...
Unpacking v4l2loopback-dkms (0.12.5-1ubuntu5) ...
Setting up v4l2loopback-dkms (0.12.5-1ubuntu5) ...
Loading new v4l2loopback-0.12.5 DKMS files...
Building for 5.18.10-76051810-generic
Building initial module for 5.18.10-76051810-generic
Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.10-76051810-generic/x86_64/dkms.conf for module v4l2loopback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
Skipped.
```

**Steps to reproduce (if you know):**

Apply updates that bring the system to install System76 kernel version 5.18.10-76051810-generic

**Expected behavior:**

v4l2loopback kernel module should successfully build

**Other Notes:**

**Comment by ctsdownloads** [comment]
Confirmed on 5.18.10-76051810-generic:

Loading new v4l2loopback-0.12.5 DKMS files...
Building for 5.18.10-76051810-generic
Building initial module for 5.18.10-76051810-generic
Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.10-76051810-generic/x86_64/dkms.conf for module v4l2loopback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
Skipped.

**Comment by tatrapikao** [comment]
confirmed for 5.18.0-13.1-liquorix-amd64
`Loading new v4l2loopback-0.12.5 DKMS files...
Building for 5.18.0-13.1-liquorix-amd64
Building initial module for 5.18.0-13.1-liquorix-amd64
Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.0-13.1-liquorix-amd64/x86_64/dkms.conf for module v4l2lo
opback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
Skipped.
`

**Comment by zicklam** [comment]
https://bugs.launchpad.net/ubuntu/+source/v4l2loopback/+bug/1970983

**Comment by mbainter** [comment]
Good find.  Notably from that link from zicklam:

> This bug was fixed in the package v4l2loopback - 0.12.5-1ubuntu6
> 
> ---------------
> v4l2loopback (0.12.5-1ubuntu6) kinetic; urgency=low
> 
>   * Check CONFIG_VIDEO_DEV against kernel version >= 5.18. (LP: [#1970983](https://bugs.launchpad.net/bugs/1970983))
> 
>  -- You-Sheng Yang <email address hidden> Tue, 03 May 2022 03:55:33 +0000

**Comment by mxc42** [comment]
Still an issue for me with version 0.12.5:

```
Building initial module for 5.18.10-76051810-generic
Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.10-76051810-generic/x86_64/dkms.conf for module v4l2loopback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
This indicates that it should not be built.
Skipped.
```

**Comment by jabbaxm6** [comment]
> Still an issue for me with version 0.12.5:
> 
> ```
> Building initial module for 5.18.10-76051810-generic
> Error! The /var/lib/dkms/v4l2loopback/0.12.5/5.18.10-76051810-generic/x86_64/dkms.conf for module v4l2loopback includes a BUILD_EXCLUSIVE directive which does not match this kernel/arch.
> This indicates that it should not be built.
> Skipped.
> ```

The package source needs to be updated. Version 0.15.1-1ubuntu5 is installed from the package sources, the fix was introduced with version 0.12.5-1ubuntu6.

In the meantime, you can bypass it by fixing it yourself:

Change:

```shell
if ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
    BUILD_EXCLUSIVE_KERNEL="^$"
fi
 ```
 
 to:
 
 ```shell
 if ! { echo "$kernelver"; echo 5.18; } | sort -V -C; then
  if ! grep -q '^CONFIG_VIDEO_DEV=[ym]$' $kernel_source_dir/.config; then
    BUILD_EXCLUSIVE_KERNEL="^$"
  fi
elif ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
    BUILD_EXCLUSIVE_KERNEL="^$"
fi
 
```

in: `/var/lib/dkms/v4l2loopback/0.12.5/source/dkms.conf`

As the patch says: https://launchpadlibrarian.net/599582200/v4l2loopback_0.12.5-1ubuntu6.debdiff

It might be easier using debdiff-apply, but I haven't used it yet. Maybe someone can post instructions on how to do this.

After applying the patch use `sudo dkms autoinstall v4l2loopback`  (as shown above by @mbainter) to install the module.

I did that today to get it working again after @zicklam posted the bug report.

**Comment by mxc42** [comment]
> The package source needs to be updated. Version 0.15.1-1ubuntu5 is installed from the package sources, the fix was introduced with version 0.12.5-1ubuntu6.
> 

Ah I didn't notice the minor version there, my bad.

> In the meantime, you can bypass it by fixing it yourself:
> 
> Change:
> 
> ```shell
> if ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
>     BUILD_EXCLUSIVE_KERNEL="^$"
> fi
> ```
> 
> to:
> 
> ```shell
> if ! { echo "$kernelver"; echo 5.18; } | sort -V -C; then
>  if ! grep -q '^CONFIG_VIDEO_DEV=[ym]$' $kernel_source_dir/.config; then
>    BUILD_EXCLUSIVE_KERNEL="^$"
>  fi
> elif ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
>    BUILD_EXCLUSIVE_KERNEL="^$"
> fi
> ```
> 
> in: `/var/lib/dkms/v4l2loopback/0.12.5/source/dkms.conf`
> 
> As the patch says: https://launchpadlibrarian.net/599582200/v4l2loopback_0.12.5-1ubuntu6.debdiff
> 
> It might be easier using debdiff-apply, but I haven't used it yet. Maybe someone can post instructions on how to do this.
> 
> After applying the patch use `sudo dkms autoinstall v4l2loopback` (as shown above by @mbainter) to install the module.
> 
> I did that today to get it working again after @zicklam posted the bug report.

This worked perfectly for me, thanks!

**Comment by zicklam** [comment]
> Change:
> 
> ```shell
> if ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
>     BUILD_EXCLUSIVE_KERNEL="^$"
> fi
> ```
> 
> to:
> 
> ```shell
> if ! { echo "$kernelver"; echo 5.18; } | sort -V -C; then
>  if ! grep -q '^CONFIG_VIDEO_DEV=[ym]$' $kernel_source_dir/.config; then
>    BUILD_EXCLUSIVE_KERNEL="^$"
>  fi
> elif ! grep -q '^CONFIG_VIDEO_V4L2=[ym]$' $kernel_source_dir/.config; then
>    BUILD_EXCLUSIVE_KERNEL="^$"
> fi
> ```
> 
> in: `/var/lib/dkms/v4l2loopback/0.12.5/source/dkms.conf`
> 
> As the patch says: https://launchpadlibrarian.net/599582200/v4l2loopback_0.12.5-1ubuntu6.debdiff
> 
> It might be easier using debdiff-apply, but I haven't used it yet. Maybe someone can post instructions on how to do this.
> 
> After applying the patch use `sudo dkms autoinstall v4l2loopback` (as shown above by @mbainter) to install the module.
> 
> I did that today to get it working again after @zicklam posted the bug report.

This workaround works well! Good job @jabbaxm6

**Comment by mbainter** [comment]
The 0.12.5-1ubuntu7pop1~1659015816~22.04~951a0b7 release dropped this week and resolves this issue.
