### ISSUE TITLE
Upgrading issue

### ISSUE THREAD

**Issue by kunal1234523** [pop-os/pop#2539]
**Distribution (run `cat /etc/os-release`):**
 impish 21.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
So, yesterday I was updating my packages using 'apt update', there comes the error.
Err:6 http://apt.pop-os.org/release impish Release
  404  Not Found [IP: 54.182.0.60 80]
Now, I get to know that there is update available for pop os 22.04, I got into the settings->os-upgrade and recovery, and I tried upgrading, but it didn't worked.

![Screenshot from 2022-07-22 11-47-23](https://user-images.githubusercontent.com/46216540/180376358-f7f5ee83-f42b-4922-8d23-71de05da5bc1.png)

The problem is i can't even update my normal packages let alone the os version.
What can I do?

**Steps to reproduce (if you know):**
running, apt update will reproduce the issue, also the settings->os-upgrade and recovery will produce the above screenshot

**Expected behavior:**
It is expected to updates the packages, also the os version.

**Other Notes:**
The day before yesterday, everything was ok, but from yesterday it is causing the issue. I understand the 21.10 version is not supported, but why can't I update?

**Comment by leviport** [comment]
Try again later today. The Impish repo is being put back up right now in order to accommodate users who did not upgrade to 22.04 in the three month period between the release of 22.04 and when 21.10 went EOL.

**Comment by kunal1234523** [comment]
Thanks, I update my pop os 22.04, but now there is wifi problem, so I tried installing rtl8821ce-dkms

output:
```
kunal@pop-os:~$ sudo apt install rtl8821ce-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  rtl8821ce-dkms
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/2,295 kB of archives.
After this operation, 25.2 MB of additional disk space will be used.
Selecting previously unselected package rtl8821ce-dkms.
(Reading database ... 679921 files and directories currently installed.)
Preparing to unpack .../rtl8821ce-dkms_5.5.2.1-0ubuntu10_all.deb ...
Unpacking rtl8821ce-dkms (5.5.2.1-0ubuntu10) ...
Setting up rtl8821ce-dkms (5.5.2.1-0ubuntu10) ...
Loading new rtl8821ce-5.5.2.1 DKMS files...
Building for 5.18.10-76051810-generic
Building initial module for 5.18.10-76051810-generic
ERROR (dkms apport): kernel package linux-headers-5.18.10-76051810-generic is not sup
ported
Error! Bad return status for module build on kernel: 5.18.10-76051810-generic (x86_64
)
Consult /var/lib/dkms/rtl8821ce/5.5.2.1/build/make.log for more information.
dpkg: error processing package rtl8821ce-dkms (--configure):
 installed rtl8821ce-dkms package post-installation script subprocess returned error 
exit status 10
Errors were encountered while processing:
 rtl8821ce-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by leviport** [comment]
This article might help you fix your package manager: https://support.system76.com/articles/package-manager-pop

Since the original bug is solved, I'm going to close this issue.
