### ISSUE TITLE
Selected keyboard layout cannot be tested during installation

### ISSUE THREAD

**Issue by ximian** [pop-os/pop#254]
**Distribution**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 **Related Application and/or Package Version**
pop-installer:
Installed: 0.0.1\~1525196440\~18.04\~7b200ab
Candidate: 0.0.1\~1525196440\~18.04\~7b200ab
Version table:
0.0.1\~1525196440\~18.04\~7b200ab 1001
1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
100 /var/lib/dpkg/status

**Issue/Bug Description**
Selected keyboard layout cannot be tested during installation (in my case Polish default - programmers)

**Steps to reproduce (if you know)**
* Start installation of Pop!_OS 18.04 LTS
* Select other than default keyboard layout (e.g. Polish)
* Try to test it in test box (e.g. Right Alt + a/s/z/x/c/n/l/o)
* Nothing happens when trying to type in characters typical to selected layout

**Expected behavior**
You should be able to test selected keyboard layout

**Comment by mmstick** [comment]
This was just implemented with https://github.com/pop-os/installer/commit/415d3f8f5d8b367eabd4e3373e38791299d57361
