### ISSUE TITLE
Natural scrolling with the touchpad does not work

### ISSUE THREAD

**Issue by cossio** [pop-os/pop#2542]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Issue/Bug Description:**

Touchpad natural scrolling does not work, on a Dell XPS 13 laptop.

**Steps to reproduce (if you know):**

Go to Settings -> Mouse & Touchpad -> Natural Scrolling

Attempt to scroll with the two finger gesture on the touchpad.

**Expected behavior:**

Scrolling in the natural sense. Instead, scrolls occurs in the same sense as if the 'Natural Scrolling' setting had not been set.

**Other Notes:**

System: Dell XPS 13 laptop, 7390. 
With Ubuntu 18.04 and 22.04, natural scrolling with the touchpad works fine.

**Comment by leviport** [comment]
I don't want to speak for the OP, but perhaps it was that Gnome Settings has two settings and it's a bit confusing:

![2023-01-23_09-24-45](https://user-images.githubusercontent.com/13512097/214093261-f73f3ea2-3259-4c7d-aed6-6854ab8df558.png)
