### ISSUE TITLE
Multi-monitor, gnome login on wrong screen. 

### ISSUE THREAD

**Issue by TubbyCat** [pop-os/pop#2545]
**Distribution (run `cat /etc/os-release`):**
 ```bash
NAME=POP!_OS"
VERSION="22.04 LTS"
VERSION_CODENAME=jammy
```
**Issue/Bug Description:**
On multi-monitor **without screen mirroring** , login occurs on secondary monitor.
I have already set the primary monitor in gnome settings, and therefore would expect the gnome login prompt to appear on such a monitor.

**Steps to reproduce (if you know):**
- Reboot, or logout in a multi-monitor setup. Having already set a primary monitor.  
- The gnome login prompt will then appear on a non-primary monitor.
- weep, contort neck (depending on nature of monitor arrangement)

**Expected behavior:**
Primary monitor to be locus of login prompt. 

**Other Notes:**
Have reverted to single monitor, as unable to fix in timely manner.

**Comment by leviport** [comment]
The reason for this is because GDM3 (login manager) does not inherit the monitor config of any user accounts. To manually copy your user account's config to GDM3, run this command:
```
cp ~/.config/monitors.xml ~gdm/.config/
```

**Comment by TubbyCat** [comment]
Thank you very much friend! 
🥇 😸

**Comment by joshontech** [comment]
> The reason for this is because GDM3 (login manager) does not inherit the monitor config of any user accounts. To manually copy your user account's config to GDM3, run this command:
> 
> ```
> cp ~/.config/monitors.xml ~gdm/.config/
> ```

I am running Debian Testing right now with Gnome 43.1 and this method did not work because of this error. 
`cp: cannot create regular file '~gdm/.config/': No such file or directory`
Is there a way to do this on Debian?

**Comment by joshontech** [comment]
> @joshontech Not sure, but the Pop!\_OS github repos probably isn't the place to ask Debian questions.

Normally I wouldn't but I already have a GitHub and the only other place I saw this fix was also for Debian Stable so I figured I would ask here since it was still the same solution. But it's all good I just figured I would ask.

**Comment by ozefreitas** [comment]
> The reason for this is because GDM3 (login manager) does not inherit the monitor config of any user accounts. To manually copy your user account's config to GDM3, run this command:
> 
> ```
> cp ~/.config/monitors.xml ~gdm/.config/
> ```

That worked out perfectly! Finally
