### ISSUE TITLE
Cannot decrypt disc without physical keyboard

### ISSUE THREAD

**Issue by plata** [pop-os/pop#2548]
**Distribution (run `cat /etc/os-release`):**
 22.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
not sure which package

**Issue/Bug Description:**
Booting is not possible if no physical keyboard is attached (e.g. with a touch device) and disc encryption is configured.

**Steps to reproduce (if you know):**
- install with disc encryption
- disconnect keyboard
- boot

**Expected behavior:**
decryption screen shows a virtual keyboard if no physical keyboard is available

**Other Notes:**
if this is not possible, show some hint in the installer

**Comment by linuxgnuru** [comment]
The decryption screen occurs in plymouth which has rudimentary functionality. There is no bluetooth stack nor any way to do a high level graphical interface such as a virtual keyboard

**Comment by plata** [comment]
I somewhat expected that. In that case, a hint in the installer should be sufficient to avoid that users lock themselves out of there system.
