### ISSUE TITLE
Package gstreamer1.0-vaapi can't Upgrade.

### ISSUE THREAD

**Issue by mueherizky** [pop-os/pop#2551]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
VERSION_CODENAME=jammy
```

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gstreamer1.0-vaapi 1.20.1-1 amd64

**Issue/Bug Description:**
I can't full upgrade this package, other packages is fine.
I've fresh install PopOS 22.04 original (switch from ubuntu).
And then I update and upgrade all packages, but i have issue like below:
```
The following packages have been kept back:
  gstreamer1.0-vaapi
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

**Steps to reproduce (if you know):**
I've do this. But i think that's not work in this problem.
```
sudo rm /var/cache/apt/archives/lock
sudo rm /var/lib/dpkg/lock
sudo lsof /var/lib/dpkg/lock
sudo lsof /var/lib/apt/lists/lock
sudo lsof /var/cache/apt/archives/lock
```

**Expected behavior:**
I can upgrade all my packages. But it didn't.

**Comment by mmstick** [comment]
What is the output of `apt-cache policy gstreamer1.0-vaapi`?

**Comment by mmstick** [comment]
If you are seeing `1.20.1-1ubuntu1 500 (phased 80%)`, it is because Ubuntu does phased updates for some packages.

**Comment by mueherizky** [comment]
Thank you for your response to my issue.
This is the output:
```
gstreamer1.0-vaapi:
  Installed: 1.20.1-1
  Candidate: 1.20.1-1ubuntu1
  Version table:
     1.20.1-1ubuntu1 500 (phased 70%)
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
 *** 1.20.1-1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by mueherizky** [comment]
but, if i install some new package via apt or dpkg. sometimes error "blabla handled by other packages" and "can't open var/list/apt/lock". Like that, but the package is installed successfully. Idk what problem is.

can you guess my problem is? im sorry i can't explain the error. i can't get the log from my system.

**Comment by mmstick** [comment]
Phased updates mean that updates are released gradually over time. You are at 70%. You won't be permitted to upgrade that package until it is 100%.

**Comment by mueherizky** [comment]
ohh okay thank you.
