### ISSUE TITLE
<html>Package failed to installError while installing package: 0.0000</html>

### ISSUE THREAD

**Issue by Emii-lia** [pop-os/pop#2560]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
This report lacks detail, but I think this article can help you: https://support.system76.com/articles/package-manager-pop/

If not, we can reopen.

**Comment by Emii-lia** [comment]
> This report lacks detail, but I think this article can help you: https://support.system76.com/articles/package-manager-pop/
> 
> If not, we can reopen.

I've already solved by 'dpkg --configure -a'; also there was a problem with my repositories but I've managed t solve it as well; thanks :)
