### ISSUE TITLE
GNU Octave plots break system GUI interactions or display force quit message

### ISSUE THREAD

**Issue by marsman2020** [pop-os/pop#2562]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
GNU Octave .deb version apt policy:
```
octave:
  Installed: 6.4.0-2
  Candidate: 6.4.0-2
  Version table:
 *** 6.4.0-2 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

GNU Octave flatpak version flatpak info:
```
GNU Octave - Interactive programming environment for numerical computations

          ID: org.octave.Octave
         Ref: app/org.octave.Octave/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 7.2.0
     License: GPL-3.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 427.0 MB
     Runtime: org.kde.Sdk/x86_64/5.15-21.08
         Sdk: org.kde.Sdk/x86_64/5.15-21.08

      Commit: 649d9e578450bc98d8218aaa4e14bf7e22ab61376b67df004967210232cb1226
      Parent: 77d0e7b13a78e755639cc7be5516a3b454c0d408faccff88ae88c84718a10027
     Subject: Add missing comma (e5ebab29)
        Date: 2022-08-04 04:26:29 +0000
```

**Issue/Bug Description:**
After creating a plot with a large quantity of data, interacting with the plot window results in either the entire GUI of the system being rendered unuseable (mouse pointer can be moved but can't interact with any applications via mouse or keyboard), or a 'force quit' dialog being displaced and Octave crashing, or both (a force quit dialog is displayed but can't be interacted with)

Other users are seeing this behavior as well - https://www.reddit.com/r/pop_os/comments/wh36qi/pop_os_freezes_with_octave/

**Steps to reproduce (if you know):**
1. Install Octave 
2. Launch Octave
3. Create a new script
4. Past in the script from https://www.reddit.com/r/pop_os/comments/wh36qi/pop_os_freezes_with_octave/
5. Save as 'diagram.m'
6. Run script
7. In the plot window that opens, attempt to use the zoom in/zoom out/fit zoom/add text buttons

**Expected behavior:**
User should be able to interact with the plot window, zoom in/out/fit zoom, pan, or use the 'Text' feature to add text on top of the plot.  These actions may take time for larger plots but should not result in a crash.

Confirmed the expect behavior on VMs with Fedora Workstation 36 and Ubuntu 22.04 LTS 

**Other Notes:**
HP Dev One
Official Pop!_OS repositories only
No changes made to system other then installing updates and software from Pop!_Shop

**Comment by marsman2020** [comment]
Additional note - just for an apples to apples comparison, I also installed a Pop!_OS VM.  Octave seemed to work fine in this VM.  So the behavior differs between running on bare metal and running in a VM, which is odd to me.

As an engineer having an open source version of the language that Octave implements is pretty important - please let me know if there is anything else I can do to help test.

**Comment by n3m0-22** [comment]
Based on what I'm seeing on the reddit thread can you post the output of `apt policy libcanberra-gtk-module`.

**Comment by marsman2020** [comment]
``
libcanberra-gtk-module:
  Installed: 0.30-10ubuntu1
  Candidate: 0.30-10ubuntu1
  Version table:
 *** 0.30-10ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by marsman2020** [comment]
It does seem like this is related to hardware acceleration, invoking Octave with ```LIBGL_ALWAYS_SOFTWARE=1 flatpak run org.octave.Octave --gui``` results in it working with no issues.  This might also explain why the VMs work if there is no hardware acceleration.

**Comment by n3m0-22** [comment]
I found this issue from a few years back with the flatpak that might be pertinent. https://github.com/flathub/org.octave.Octave/issues/63

Do you know if you have the latest driver installed? You can find it here https://www.amd.com/en/support/linux-drivers.

**Comment by marsman2020** [comment]
My laptop (HP Dev One) cam with Pop preinstalled, so everything should be working driver wise with the open source driver stack which is well supported on AMD hardware at this point.  

3D games in Steam, glxgears, and the KiCAD hardware accelerated canvas all work fine.

**Comment by n3m0-22** [comment]
Thank you for the info.

**Comment by n3m0-22** [comment]
I have tested this again on a Dev One. I can not reproduce the issue. I am closing this issue but can always reopen if you are still having a problem.
