### ISSUE TITLE
Suspend leads to system locking up

### ISSUE THREAD

**Issue by mdhankins1** [pop-os/pop#2568]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Unsure.  Might be a kernel issue.  5.18.10-76051810-generic

**Issue/Bug Description:**
Suspend is not working properly.  If my computer goes into a suspend state, 7/10 times it will lock up in a semi-powered on state where the screen is blank and will not respond to keyboard or mouse, but the rest of the computer will still be powered on with fans spinning and components generating heat.  I assume that this is a suspend to ram, not suspend to disk as I have not setup sufficient swap space for that.

**Steps to reproduce (if you know):**
Initiating a suspend from the top menu bar or enabling auto suspend after computer being idle for a period of time.  I have auto suspend disabled now because of this bug.

**Expected behavior:**
Normally resuming from suspend when I press a key on my keyboard

**Other Notes:**
Suspend was working properly until I replaced the Ryzen 3600 in my system with a 5600G.  I did the CPU replacement because I wanted to remove my old Nvidia GTX 1070 as I don't game much anymore and I was tired of glitchy nvidia driver issues.  The main nvidia issue was having the screen go randomly blank for a second or two throughout the day.  After I installed the new CPU I refreshed my OS so I could remove all traces of nvidia drivers.  I also updated my bios to the latest release from ASUS (I was one rev back), but it did not do anything to help the suspend issue.

My hardware info:

$ inxi -F
System:
  Host: pop-os Kernel: 5.18.10-76051810-generic x86_64 bits: 64
    Desktop: GNOME 42.3.1 Distro: Pop!_OS 22.04 LTS
Machine:
  Type: Desktop Mobo: ASUSTeK model: ROG STRIX B450-I GAMING v: Rev 1.xx
    serial: <superuser required> UEFI: American Megatrends v: 4801
    date: 03/02/2022
CPU:
  Info: 6-core model: AMD Ryzen 5 5600G with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 3 MiB
  Speed (MHz): avg: 3249 min/max: 1400/4464 cores: 1: 3251 2: 3680 3: 3304
    4: 2913 5: 3304 6: 3205 7: 3332 8: 3533 9: 3029 10: 3044 11: 3405 12: 2992
Graphics:
  Device-1: AMD Cezanne driver: amdgpu v: kernel
  Device-2: Microsoft LifeCam Cinema type: USB
    driver: snd-usb-audio,uvcvideo
  Display: wayland server: X.Org v: 1.22.1.1 with: Xwayland v: 22.1.1
    compositor: gnome-shell driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,radeon,vesa gpu: amdgpu
    resolution: 2560x1440~60Hz
  OpenGL:
    renderer: AMD RENOIR (LLVM 13.0.1 DRM 3.46 5.18.10-76051810-generic)
    v: 4.6 Mesa 22.0.5
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio driver: snd_hda_intel
  Device-2: AMD Family 17h HD Audio driver: snd_hda_intel
  Device-3: AudioQuest DragonFly Black v1.5 type: USB
    driver: hid-generic,snd-usb-audio,usbhid
  Device-4: Microsoft LifeCam Cinema type: USB
    driver: snd-usb-audio,uvcvideo
  Sound Server-1: ALSA v: k5.18.10-76051810-generic running: yes
  Sound Server-2: PipeWire v: 0.3.56 running: yes
Network:
  Device-1: Intel I211 Gigabit Network driver: igb
  IF: enp3s0 state: down mac: 0c:9d:92:7f:bb:7b
  Device-2: Realtek RTL8822BE 802.11a/b/g/n/ac WiFi adapter
    driver: rtw_8822be
  IF: wlp4s0 state: up mac: 70:c9:4e:83:fa:bd
  IF-ID-1: virbr0 state: down mac: 52:54:00:ed:46:be
Bluetooth:
  Device-1: ASUSTek Bluetooth Radio type: USB driver: btusb
  Report: hciconfig ID: hci0 state: up address: 70:C9:4E:83:FA:BE bt-v: 2.1
Drives:
  Local Storage: total: 10.94 TiB used: 4.8 TiB (43.9%)
  ID-1: /dev/nvme0n1 vendor: SK Hynix model: PC711 NVMe 1TB
    size: 953.87 GiB
  ID-2: /dev/sda vendor: Crucial model: CT2000MX500SSD1 size: 1.82 TiB
  ID-3: /dev/sdb vendor: Crucial model: CT1000MX500SSD1 size: 931.51 GiB
  ID-4: /dev/sdc type: USB vendor: Western Digital model: WD My Book 25EE
    size: 7.28 TiB
Partition:
  ID-1: / size: 933.39 GiB used: 409.91 GiB (43.9%) fs: ext4 dev: /dev/dm-1
  ID-2: /boot/efi size: 497 MiB used: 248.9 MiB (50.1%) fs: vfat
    dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 4 GiB used: 3 MiB (0.1%) file: /data/swapfile
Sensors:
  System Temperatures: cpu: 37.0 C mobo: 33.0 C gpu: amdgpu temp: 33.0 C
  Fan Speeds (RPM): cpu: 615 case-1: 580
Info:
  Processes: 420 Uptime: 2h 22m Memory: 30.73 GiB used: 4.39 GiB (14.3%)
  Shell: Bash inxi: 3.3.13

**Comment by leviport** [comment]
Looks like the latest BIOS update for your motherboard has "Improve system stability" in the changelog: https://rog.asus.com/us/motherboards/rog-strix/rog-strix-b450-i-gaming-model/helpdesk_bios/

Might be worth giving that a try?

**Comment by esotericode** [comment]
Received a new HP Dev One a couple days ago and I had it lock up in suspend as well. This of course being a device that's supposed to be well supported by Pop OS. Curiously it's also an AMD Cezanne device like yours.

**Comment by leviport** [comment]
@esotericode Did you only see a single instance of this? If it was only one occurrence, then there probably isn't any meaningful correlation. Anecdotally, I don't believe I've ever seen my Dev One lock up during suspend/resume, but that's just been my experience with the machine.

**Comment by mdhankins1** [comment]
Interesting. I had last updated my bios on 8/7, the day before that one was
released.

I just installed the latest version.  The first suspend test was
successful.  The second one locked up.

**Comment by esotericode** [comment]
@leviport I have seen only a single instance of this, but I really want to stress that fact that I've only use the laptop for a total of a couple hours, I just got it very recently and a crash during suspend so early on seemed weird. I intend to throw a totally fresh reinstall of Pop OS on it from the newest ISO and see if it's something that will keep happening or not. 

Just for some context I just returned a laptop that constantly crashed in suspend so I got "here we go again" vibes as soon as the Dev One did it. I hope that's not the case and it's just a weird one off thing.

**Comment by leviport** [comment]
>I just installed the latest version.  The first suspend test was
successful.  The second one locked up.

I see, that's a bummer. Well there is a tool called `fwts` that suspends and resumes a machine automatically while writing logs. When you're able to investigate more, try installing `fwts` and running `sudo fwts s3 --s3-multiple 10 --s3-min-delay 20 --s3-max-delay 40`. This will try to suspend and resume 10 times, with a delay between 20 and 40 seconds between each cycle. It also writes a `results.log` file as it goes, so if it crashes, it may collect some clues. Other than that, looking through normal journal logs might also have some clues.

**Comment by leviport** [comment]
@esotericode Make sure your system is fully up to date and keep trying then. I understand the timing is frustrating, but if your experience is like mine, suspend and resume is very solid on the Dev One.

**Comment by mdhankins1** [comment]
> > I just installed the latest version.  The first suspend test was
> > successful.  The second one locked up.
> 
> I see, that's a bummer. Well there is a tool called `fwts` that suspends and resumes a machine automatically while writing logs. When you're able to investigate more, try installing `fwts` and running `sudo fwts s3 --s3-multiple 10 --s3-min-delay 20 --s3-max-delay 40`. This will try to suspend and resume 10 times, with a delay between 20 and 40 seconds between each cycle. It also writes a `results.log` file as it goes, so if it crashes, it may collect some clues. Other than that, looking through normal journal logs might also have some clues.

I got an error when installing fwts.  Not sure if it's actually a problem or just costmetic.

mhankins@pop-os:~$ sudo nala install fwts
[sudo] password for mhankins: 
================================================================================
 Installing                                                                     
================================================================================
  Package:                  Version:                                     Size:  
  fwts                      22.03.00-0ubuntu1                           373 KB  
  fwts-efi-runtime-dkms     22.03.00-0ubuntu1                            14 KB  
  libfwts1                  22.03.00-0ubuntu1                           123 KB  
  libfwtsacpica1            22.03.00-0ubuntu1                           294 KB  
  libfwtsiasl1              22.03.00-0ubuntu1                           389 KB  
                                                                                
================================================================================
 Summary                                                                        
================================================================================
 Install 5 Packages                                                             
                                                                                
 Total download size  1.2 MB   
 Disk space required  4.0 MB   
                               
Do you want to continue? [Y/n] 
╭─ Downloading… ───────────────────────────────────────────────────────────────╮
│ Total Packages: 5/5                                                          │
│ Last Completed: libfwts1_22.03.00-0ubuntu1_amd64.deb                         │
│ Time Remaining: 0:00:00 ━━━━━━━━━━━━━━━━━━━━━ 100.0% • 1.2/1.2 MB • 2.9 MB/s │
╰──────────────────────────────────────────────────────────────────────────────╯
╭─ Installing Packages ────────────────────────────────────────────────────────╮
│efi_runtime.ko:                                                               │
│Running module version sanity check.                                          │
│Module has been obsoleted due to being included                               │
│in kernel 4.8.0.  We will avoid installing                                    │
│for future kernels above 4.8.0.                                               │
│You may override by specifying --force.                                       │
│depmod                                                                        │
│Setting up: libfwts1 (22.03.00-0ubuntu1)                                      │
│Setting up: libfwtsacpica1 (22.03.00-0ubuntu1)                                │
│Setting up: fwts (22.03.00-0ubuntu1)                                          │
│Processing: triggers for man-db (2.10.2-1)                                    │
│Processing: triggers for libc-bin (2.35-0ubuntu3.1)                           │
│╭────────────────────────────────────────────────────────────────────────────╮│
││✔ Running dpkg … ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0% • 0:00:00 • 11/11││
│╰────────────────────────────────────────────────────────────────────────────╯│
╰──────────────────────────────────────────────────────────────────────────────╯
Finished Successfully
mhankins@pop-os:~$

**Comment by mdhankins1** [comment]
$ cat results.log
Results generated by fwts: Version V22.03.00 (2022-03-17 06:10:44).

Some of this work - Copyright (c) 1999 - 2021, Intel Corp. All rights reserved.
Some of this work - Copyright (c) 2010 - 2021, Canonical.
Some of this work - Copyright (c) 2016 - 2021, IBM.
Some of this work - Copyright (c) 2017 - 2021, ARM Ltd.

This test run on 12/08/22 at 09:49:09 on host Linux pop-os
5.18.10-76051810-generic #202207071639~1659403207~22.04~cb5f582 SMP
PREEMPT_DYNAMIC Tue A x86_64.

Command: "fwts --s3-multiple 10 --s3-min-delay 20 --s3-max-delay 40 s3".
Running tests: s3.

s3: Sleep suspend/resume test.
--------------------------------------------------------------------------------
Test 1 of 1: Sleep suspend/resume test.
S3 cycle 1 of 10 
Detecting the power method.
Response to CanSuspend is yes 
User allowed to execute the CanSuspend action 
Using logind as the default power method.
Requesting Suspend action 
S3 duration = 33.
pm-action returned 0 after 33 seconds.
Suspend/Resume Timings:
  Suspend: 1.241 seconds.
  Resume:  3.269 seconds.
S3 cycle 2 of 10 
Using logind as the default power method.
Requesting Suspend action

**Comment by mdhankins1** [comment]
I'm going to close this issue after verifying that it is not related to Pop OS.  I installed Windows 10 on nvme1 and found that I can duplicate the suspend issue.  Will be contacting ASUS.
