### ISSUE TITLE
Second input method just disappear after shutdown, reboot or suspend.

### ISSUE THREAD

**Issue by Kai-s-cmd** [pop-os/pop#2583]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04 LTS

**Issue/Bug Description:**
When i add a second keyboard input method in setting => keyboard => input sources => push the "plus" button and add another keyboard, it just come back to stock condition (i mean only english method) after shutdown, reboot or suspend. I'm forced to add the second input every time after reboot.

**Steps to reproduce (if you know):**
setting => keyboard => input sources => push the "plus" button and add another keyboard. Reboot and check it.

**Expected behavior:**
After reboot should be 2 input method. (Example: English and Chinese).

**Other Notes:**
Please fix that. :)

**Comment by leviport** [comment]
Is this only at the gray login screen, or is the second input method also missing after you've signed in?

**Comment by Kai-s-cmd** [comment]
> Is this only at the gray login screen, or is the second input method also missing after you've signed in?

Yes, it missing when i sighed in.

**Comment by Kai-s-cmd** [comment]
I fixed the problem by editing /etc/default/keyboard. In line `XKBLAYOUT` added second method and `XKBVARIANT` replaced `qwerty` with a `phonetic`, saved and reboot.
