### ISSUE TITLE
Can't update system via Discover

### ISSUE THREAD

**Issue by cybercrypt13** [pop-os/pop#2588]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Issue/Bug Description:**
When I open Discover and tell it to update after a few seconds I get the follow message:
"There was an issue installing this update.  Please try again later."

Clicking technical details shows:
Package failed to install:

Error while installing package: 0.0000

**Comment by cybercrypt13** [comment]
NOTE: I have attempted to deselect everything and select only a single package and get the same error

**Comment by leviport** [comment]
Sounds like it might be the same issue as https://github.com/pop-os/pop/issues/2556

There is a fix in that thread, if it is the same issue.

**Comment by cybercrypt13** [comment]
Thank you, that solved the issue for me as well.

**Comment by leviport** [comment]
Glad to hear it's fixed! Since it's the same as #2556, I'm going to close this as a duplicate.
