### ISSUE TITLE
Dark theme's don't apply dark background everywhere

### ISSUE THREAD

**Issue by Memphizzz** [pop-os/pop#259]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
GNOME

**Issue/Bug Description**
The dark theme doesn't apply dark background colors for everything. See screenshot.

**Steps to reproduce (if you know)**
Use gnome-tweak-tool to change theme to Pop-dark or Adwaita-dark.
Click on the Date/Time gadget.

**Expected behavior**
Dark backgrounds everywhere.

**Other Notes**
Unfortunately this bug also causes Arc Menu (gnome extension) to have a white background. See screenshot2.

![2capture](https://user-images.githubusercontent.com/4660924/39626275-87829a9e-4fa1-11e8-9a49-00398451a3fd.JPG)
![capture](https://user-images.githubusercontent.com/4660924/39626280-87a4dbf4-4fa1-11e8-8245-fe04892b5fe0.JPG)

**Comment by jrgermain** [comment]
To get gnome shell components (i.e. the parts that still look light in your screenshot) to have a dark theme you need to change your Shell theme too, not just the Applications theme. Install [this gnome shell extension](https://extensions.gnome.org/extension/19/user-themes/) to enable changing the shell theme. Then change the shell theme to Pop-dark and let me know if that fixes it.

**Comment by Memphizzz** [comment]
Amazing! That worked! Thanks for the tip and keep up the great work! I really enjoy Pop-OS or Upuntu (as I call it) as my daily driver :)
