### ISSUE TITLE
Fix Broken Packages

### ISSUE THREAD

**Issue by kkaii** [pop-os/pop#2597]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
This bug report is empty so I'm going to close it, but it sounds like you might be having package manager issues. If that is the case, this article might be helpful: https://support.system76.com/articles/package-manager-pop

If you want to edit your issue to include more information, I can reopen this issue.
