### ISSUE TITLE
Hidden command line toggle and "Skip" button that does nothing

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#26]
_From @brs17 on October 11, 2017 16:35_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
During installation during the non-user-interactive part, by clicking near the "Copying files..." and "Skip" line, the terminal pops up showing the commands being run. There is no visible button showing this as a feature. Clicking in the same location does not always toggle the terminal either.

The skip button is also unnecessary as there is no user interaction during the setup process. 

**Steps to reproduce (if you know)**
During installation, click the "Skip" button. See terminal open, "Skip" button disappear. 

**Expected behaviour**
Replace the "Skip" button with one toggling the terminal. This button should not disappear after selected.

**Other Notes**
I can provide video of issue occurring if desired.

_Copied from original issue: pop-os/iso#139_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
