### ISSUE TITLE
No audio... anything, no audio I/O devices detected and it seems pipewire isn't running?

### ISSUE THREAD

**Issue by WilliamBehrens** [pop-os/pop#2603]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
pipewire:
  Installed: 0.3.56-0pop1~1658336739~22.04~a3894c2
  Candidate: 0.3.56-0pop1~1658336739~22.04~a3894c2
  Version table:
 *** 0.3.56-0pop1~1658336739~22.04~a3894c2 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
Audio has just stopped working... I'm not sure what else to say. My system was running just fine and was a pretty fresh install suddenly I booted up and noticed I couldn't turn the volume up (the  indicator wouldn't even show up) I then checked the settings to see for any detected audio devices and everything was grey.

I'm not sure how to reproduce this so I can't really test it but I haven't heard any issues about this for the base Ubuntu Jammy which is why I'm posting here. I have seen people suggjesting to run `systemctl --user restart pipewire` but that just gives me `Failed to restart pipewire.service: Unit pipewire.service is masked.`

**Other Notes:**
I initially [reported this](https://www.reddit.com/r/pop_os/comments/x1zfv2/no_audio_output_device_detected_2204/) issue on the Pop!_OS Reddit and it seems others have had this issue. I'm posting it here as it seems like a more proper way of handling the issue.

**Comment by leviport** [comment]
>Failed to restart pipewire.service: Unit pipewire.service is masked.

I'm not sure how it got masked, but you should be able to unmask it with `systemctl unmask pipewire`. I'm not sure whether it needs the `--user` argument, but you can try it both ways.

**Comment by WilliamBehrens** [comment]
> 

Doesn't seem to fix it, it's like something is re-masking it? I tried running without `--user` as well and I just get pipewire.service not found

**Comment by spacegears** [comment]
Downgrading the kernel to `5.18.19` solved this issue in my case, see [https://github.com/pop-os/pop/issues/2584](https://github.com/pop-os/pop/issues/2584).

**Comment by WilliamBehrens** [comment]
I was able to fix the issue by running `sudo apt install --reinstall pipewire pipewire-pulse`, they were never uninstalled but running reinstall specifically fixed the issue.
