### ISSUE TITLE
Lock screen hang

### ISSUE THREAD

**Issue by curiousercreative** [pop-os/pop#2625]
**Distribution (run `cat /etc/os-release`):**
 ```bash
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```bash
$ apt policy gnome-shell
gnome-shell:
  Installed: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Candidate: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Version table:
     42.4-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
 *** 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     42.0-2ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
Lock screen hangs, system is unresponsive. No tty switching is possible, password input field does not display, have to force shutdown.

**Steps to reproduce (if you know):**
Unknown, hasn't happened often. [See a snippet from the 1.6GB of syslog it generated](https://gist.github.com/curiousercreative/3b30417bc827db519236ab09a249d478)

**Comment by Richardswe** [comment]
This happened to me too one time. pop-os seems to be very unstable, i got other issues too like gnome freezing and that the laptop does not shutdown but reboot when i choose to "Power off".

**Comment by curiousercreative** [comment]
Hasn't happened recently, so closing.
