### ISSUE TITLE
Ubuntu font is used in Settings > Details > About

### ISSUE THREAD

**Issue by jbicha** [pop-os/pop#263]
Ubuntu's `ubuntu-gnome-version.patch` for `gnome-control-center` intentionally hard codes the Ubuntu font to be used for the Ubuntu name and version number shown in Settings > Details > About.

Since Pop!_OS is not Ubuntu and uses different fonts, maybe that should be changed too.

![About Pop!_OS](https://user-images.githubusercontent.com/876259/39707022-2bdfe51a-51e1-11e8-96f9-3ff08f7e6795.png)

On the other hand, maybe Ubuntu could drop that hard-coded font name since it's probably not very common for users to change their system fonts.

(Before Ubuntu 17.10 and still in `unity-control-center`, the version number is actually a `.png` instead of a text label.)

**Comment by jackpot51** [comment]
Thanks @jbicha for this information, I will look into patching that.

**Comment by jacobgkau** [comment]
This is no longer an issue, as current versions of GNOME Control Center display the OS name and version as regular lines of text.

![image](https://user-images.githubusercontent.com/7199422/122998148-f0358c00-d369-11eb-91ca-322cd4ad9262.png)
