### ISSUE TITLE
Automatic Updates Fail To Enable

### ISSUE THREAD

**Issue by SwiftLemon** [pop-os/pop#2634]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
**System and Application Updates**

![Screenshot from 2022-10-04 21-31-45](https://user-images.githubusercontent.com/59256449/193960309-edcf32fb-2c3f-435e-9cba-f7cfa86c708b.png)

**Issue/Bug Description:**
When attempting to switch the toggle ON for Automatic Updates after closing settings and reopening the toggle is reverted back to OFF.

**Steps to reproduce (if you know):**
1. Open settings
2. Go to "OS Upgrade & Recovery"
3. Toggle the "Automatic Updates" to the ON position
4. Close Settings
5. Open Settings
6. Go to "OS Upgrade & Recovery"
7. The "Automatic Updates" toggle is now in the OFF position

**Expected behavior:**
The "Automatic Updates" toggle should stay ON and enable automatic updating when toggled ON.

**Comment by mmstick** [comment]
The fix for this was in Monday's update. Have you updated the system recently?

**Comment by SwiftLemon** [comment]
> The fix for this was in Monday's update. Have you updated the system recently?

Yes the system should be fully updated, some additional things I tried before creating the report.

- Clean install from the "pop-os_22.04_amd64_nvidia_14.iso"
- Checked and updated from the Pop!_Shop GUI
- ran  `apt-get update` and `apt-get upgrade` (gave 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.)

**Comment by mmstick** [comment]
`systemctl status --user com.system76.SystemUpdater.Local`

The status of this service should be active.

`systemctl status com.system76.SystemUpdater`

Same with this one.

**Comment by SwiftLemon** [comment]
Using both those commands, seems to show each service as "inactive (dead)"

`systemctl status --user com.system76.SystemUpdater.Local`
com.system76.SystemUpdater.Local.service - Local session service for the Pop >
     Loaded: loaded (/usr/lib/systemd/user/com.system76.SystemUpdater.Local.ser>
     Active: inactive (dead)

`systemctl status com.system76.SystemUpdater`
com.system76.SystemUpdater.service - Distribution updater
     Loaded: loaded (/lib/systemd/system/com.system76.SystemUpdater.service; enabled; vendor preset: enabled)
     Active: inactive (dead)

**Comment by mmstick** [comment]
Did you restart after installing those updates? Any logs from these services?

**Comment by SwiftLemon** [comment]
Correct a few restarts after all the updates. Sorry, I don't know how to get/find the logs for these services.

**Comment by yerlikayao** [comment]
@SwiftLemon commands save my day, now working as well

**Comment by leviport** [comment]
We probably don't need both this issue and https://github.com/pop-os/system-updater/issues/30 open to track the same bug. I'll re-close this one for now, and let's use https://github.com/pop-os/system-updater/issues/30 to continue to track it.
