### ISSUE TITLE
Laptop wake up after suspend issues with input

### ISSUE THREAD

**Issue by aalvarado** [pop-os/pop#2641]
**Distribution (run `cat /etc/os-release`):**

```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
``` 
 
```
uname -r
5.19.0-76051900-generic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
apt policy system76-driver-nvidia nvidia-driver-510
system76-driver-nvidia:
  Installed: (none)
  Candidate: 20.04.64~1662586768~22.04~f8a17ba
  Version table:
     20.04.64~1662586768~22.04~f8a17ba 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
nvidia-driver-510:
  Installed: 510.85.02-0ubuntu0.22.04.1
  Candidate: 510.85.02-0ubuntu0.22.04.1
  Version table:
 *** 510.85.02-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-security/restricted amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/restricted amd64 Packages
        100 /var/lib/dpkg/status
     510.60.02-0ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/restricted amd64 Packages

xorg:
  Installed: 1:7.7+23ubuntu2
  Candidate: 1:7.7+23ubuntu2
  Version table:
 *** 1:7.7+23ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

Can't input anything, after wake up from sleep. Using xss-lock but also happens with the native pop os interface.

**Steps to reproduce (if you know):**

start a couple of programs, then issue a suspend with `sudo systemctl suspend` wait until screen goes black.

close lid. disconnect power source. Open lid, wait until screen comes back on. try to type something but nothing works. Input is frozen. it does detect a `REISUB` and can restart like this. ctrl + shift + F3...F7 don't work either

**Expected behavior:**
be able to type in the password after waking up from suspend

**Other Notes:**

tried this solution https://github.com/pop-os/pop/issues/2465

but gave me this error and did not suspend

```
Oct 10 16:56:34 nil-machine kernel: nvidia 0000:01:00.0: PM: pci_pm_suspend(): nv_pmops_suspend+0x0/0x30 [nvidia] returns -5
Oct 10 16:56:34 nil-machine kernel: nvidia 0000:01:00.0: PM: dpm_run_callback(): pci_pm_suspend+0x0/0x1a0 returns -5
Oct 10 16:56:34 nil-machine kernel: nvidia 0000:01:00.0: PM: failed to suspend async: error -5
Oct 10 16:56:34 nil-machine kernel: sd 1:0:0:0: [sda] Stopping disk
Oct 10 16:56:34 nil-machine kernel: PM: Some devices failed to suspend, or early wake event detected

**Comment by hakro** [comment]
I'm also facing this issue. Anytime I try to get my laptop out of suspension, including automatic suspend after 1 hour, it gets stuck on the login screen with the clock.
No input works, no keyboard, no trackpad, and no external mouse.
The only thing I can do is a hard reboot using the power button. My PopOs installation is very light on customizations, and is up to date. I don't install to much stuff on it and rely mainly on Appimages.

Here are my specs : 
```
cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

uname -a
Linux pop-os 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux
```

My laptop model & graphics card : 
![2022-10-24_13-22](https://user-images.githubusercontent.com/3624853/197515015-998aaaae-86ca-4d73-a882-640a6971d6fc.png)

**Comment by aalvarado** [comment]
I switched over to 515 drivers and my issues seem to be gone

**Comment by hakro** [comment]
I was using the 515 driver the whole time, and still got the issue.
So on my side, it's not fixed : 

![2022-10-24_16-55](https://user-images.githubusercontent.com/3624853/197557813-dc188422-85a4-4ef4-8527-70b56282818a.png)

**Comment by aalvarado** [comment]
did you try disabling the nvidia services in the linked issue by any chance?

**Comment by aalvarado** [comment]
This seems to have returned. I'm getting a black screen if i suspend with the 2nd hdmi screen connected to the dGPU, and disconnect the hdmi and try to resume from suspend I'll get a black screen and have to manually reboot with REISUB since it's the only thing that works. No ctrl + alt + fx keys work

**Comment by aalvarado** [comment]
current specs:

```
 λ uname -r
6.2.6-76060206-generic
```

```
 λ apt policy nvidia-driver-525
nvidia-driver-525:
  Installed: 525.116.04-1pop0~1686770941~22.04~ac14717
  Candidate: 525.116.04-1pop0~1686770941~22.04~ac14717
  Version table:
     525.125.06-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/restricted amd64 Packages
 *** 525.116.04-1pop0~1686770941~22.04~ac14717 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     525.105.17-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-security/restricted amd64 Packages
```

**Comment by aalvarado** [comment]
This fixes it

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/111#note_1254235
