### ISSUE TITLE
Minimization of full-screen application freezes the desktop environment.

### ISSUE THREAD

**Issue by qodroi** [pop-os/pop#2645]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Not sure if it's Gnome-specific behaviour but, **42.4** is my Gnome version.
Windowing system is **X11**

**Issue/Bug Description:**

I haven't tried that with other games but whenever I hit F11 to go into full screen mode in Minecraft, once you want to get out of full screen mode let's say with the Super key (Windows logo key), it minimizes the application as intended but freezes the whole system and locks my cursor in one monitor, the one Minecraft is on. I solve it by simply switching to a different TTY (Non GUI one) and kill the Minecraft client process.

Important to mention that the same happens with any other keys that forces the application to minimize, or ones that change the keyboard layout (Shift + Alt does the same).

**Steps to reproduce (if you know):**

1 - Enter full screen mode in an application (I only tried with MC)
2 - Click Windows logo key (Super key)
Minimizes and shows your desktop but freezes your system, you'll have to kill the full screen process.

**Expected behavior:**
Minimize, leave the application open in background and let you use the system.

**Other Notes:**
It doesn't happen when you F11 into e.g. FireFox or Visual Studio Code. It only happens with applications like Minecraft, and I don't know how the system makes the different between those apps. If any other information is needed let me know, as long as we'll improve the gaming experience (:

**I believe it might not be the issue of Pop Os specifically, but I'd love to see what we can do about it.**

**Comment by leviport** [comment]
I believe this may be specific to Minecraft. Firefox in F11 mode behaves as expected.

**Comment by qodroi** [comment]
> I believe this may be specific to Minecraft. Firefox in F11 mode behaves as expected.

I will check it with some other game soon, and post an update.

**Comment by qodroi** [comment]
> I believe this may be specific to Minecraft. Firefox in F11 mode behaves as expected.

It _does_ seem to be specific to Minecraft.. My bad!

**Comment by leviport** [comment]
It's still a bug, so it's probably worth keeping this issue open. Let's just change the title so it describes the bug more accurately.

**Comment by qodroi** [comment]
> It's still a bug, so it's probably worth keeping this issue open. Let's just change the title so it describes the bug more accurately.

Related not related bug: Minimizing Minecraft also disables Night Light, it always does. Not doing so when going Full Mode though.

**Comment by leviport** [comment]
Yeah a separate issue for that one would probably be best
