### ISSUE TITLE
VNC / Screensharing 

### ISSUE THREAD

**Issue by DrEVILish** [pop-os/pop#265]
Unable to Remote Access - Pop!_OS installation using inbuilt screen sharing.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**
VNC / vino-server

**Issue/Bug Description**
After enabling Screen Sharing from the "Settings" Pane

**Steps to reproduce (if you know)**
Install OS -> Enable Screen Sharing -> Try to VNC fails

After Enabling netstat returns
$> netstat -nap | grep 590[0-9]
tcp        0      0 0.0.0.0:5900            0.0.0.0:*               LISTEN      1666/vino-server    
tcp6       0      0 :::5900                 :::*                    LISTEN      1666/vino-server

**Comment by jbrains** [comment]
This might relate to encryption. If you configure vino not to require encryption, then you might be able to connect. See https://bugzilla.redhat.com/show_bug.cgi?id=981984 for more information.

**Comment by RemyWi** [comment]
Thank you very much! That was the issue. So, this is not a bug but a setting enabled which does not work with most of the VNC clients out of the box. I understand the security feature enable by default but there should be a warning mentioning this. Not everyone is an expert in VNC settings.

**Comment by brs17** [comment]
Looks like the issue is resolved. Feel free to comment and reopen if that is not the case.
