### ISSUE TITLE
Pop!_OS Deletes Text While Typing On a Cleavo System 

### ISSUE THREAD

**Issue by pdqwq** [pop-os/pop#2654]
**Distribution (run `cat /etc/os-release`):**
 
 22.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_OS

**Issue/Bug Description:**
Text is deleted while typing.  If two keys are depressed at the same time, or a 2nd key is slightly touched, or bumped, then text is highlighted, and the next key stroke deletes all text hightlighted. 

**Steps to reproduce (if you know):**

Normal typing at high speed, and sometimes text will get highlighted, and then will delete.  Text is easily recovered by depressing Ctrl Z a couple of times.

**Expected behavior:**

No text deletion, and no text highlighted from merely typing.

**Other Notes:**
 This is happening on a 2018 vintage Oryx Pro, and appears to be unique to this hardware which incidentally comprises the majority of System76 laptops.

**Comment by jacobgkau** [comment]
Your issue description is currently empty. Please edit the description and fill out the template.

**Comment by pdqwq** [comment]
> Your issue description is currently empty. Please edit the description and fill out the template.

Github malfunctioned, and didn't post the bug.  I have edited it so allow more time for me to finish posting before closing an issue.  It wasn't even a minute before you closed it

**Comment by jacobgkau** [comment]
> This is happening on a 2018 vintage Oryx Pro,

You wrote "Cleavo" (I assume you meant "Clevo") in your issue title. Is this an actual Oryx Pro, or is it another brand of Clevo system using the same chassis?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by pdqwq** [comment]
This is an Oryx Pro.

**Comment by pdqwq** [comment]
However, the problem has been reported on other Clevo systems.

**Comment by jacobgkau** [comment]
> However, the problem has been reported on other Clevo systems.

Where are the other reports that you're referring to?

**Comment by jacobgkau** [comment]
@n3m0-22 has an Oryx Pro (oryp4) and has been unable to replicate this issue so far.

It sounds like you may be hitting the touchpad with your palm while typing. Does the issue occur if you disable the touchpad with Fn-F1 and then type for a bit?

**Comment by pdqwq** [comment]
Fn F1 is not a suitable fix for this type of problem.  Everyone who has a rebranded Cleevo, and Pop!_OS has this problem.Dan ---- On Thu, 20 Oct 2022 20:31:36 -0700  ***@***.***  wrote ----
@n3m0-22 has an Oryx Pro (oryp4) and has been unable to replicate this issue so far.
It sounds like you may be hitting the touchpad with your palm while typing. Does the issue occur if you disable the touchpad with Fn-F1 and then type for a bit?

**Comment by leviport** [comment]
@pdqwq We weren't saying that it was a fix, we were asking if that helped. You previously mentioned nothing of the touchpad, and we had to make that assumption ourselves. 

>Everyone who has a rebranded Cleevo, and Pop!_OS has this problem

This is simply not true, and System76 machines are more than just "rebranded Cleevo" machines. If you want help with your issue, disparaging the products we proudly sell probably isn't the best way to get it.

Now, can you install `gnome-tweaks`, launch it, go to the "Keyboard & Mouse" tab and see whether the "Disable While Typing" setting under "Touchpad" is on? It is supposed to be by default, as shown here:
![tweaks](https://user-images.githubusercontent.com/13512097/197225205-33d526f4-30c3-465b-b8ab-dad446b441ff.png)

This enables palm rejection, which will prevent any touchpad input while the user is actively typing. If the setting is on, but not working as expected, a different touchpad driver may have been installed at some point, and that could be interfering. If you've installed any Synaptic drivers recently, it might be worth testing whether removing them makes the touchpad behave as expected again. I'd probably have a USB mouse handy while testing this, just in case it makes anything stop working.

**Comment by pdqwq** [comment]
I just selected Fn, and F1, and now can't turn the mouse back on. I shouldn't have tried this due to the warnings on the internet about this.  Dan ---- On Thu, 20 Oct 2022 20:31:36 -0700  ***@***.***  wrote ----
@n3m0-22 has an Oryx Pro (oryp4) and has been unable to replicate this issue so far.
It sounds like you may be hitting the touchpad with your palm while typing. Does the issue occur if you disable the touchpad with Fn-F1 and then type for a bit?

**Comment by pdqwq** [comment]
I just checked my gnome-tweaks.  Control indicates it was already on.  I shut it off, turned it back on, shut it off again, and it seems to have improved the problem, but it would be nice if a programming fix was implemented so that I and other users don't have to do this.

Dave

 ---- On Fri, 21 Oct 2022 07:57:20 -0700  leviport  wrote ---

**Comment by n3m0-22** [comment]
I just tried `Fn` + `F1` on a `oryp4` and the touchpad turned on and off without issue. Have you tried using a USB mouse as @leviport suggested? Can you please share the link or links to the warnings and reports you have referenced. They could be useful in troubleshooting your issue. It would also be helpful to know the exact model of your machine to be sure we are testing the same hardware. The output of this command `sudo dmidecode | grep -A3 '^System Information` will give that information. You may want to use a USB keyboard for this. It would also be useful to check the firmware version you have installed. You can find this under `Settings` > `Firmware`. It will be at the top. Mine shows `1.07.11RSA4-1`. You can also find this using this command `sudo dmidecode | grep -A3 '^BIOS Information`.

**Comment by pdqwq** [comment]
I was able to get the mousepad shut off, and turned back on.  It looks like the jam was only a temporary one, but it seems like a lot of hassle to have to keep turning the mouse on and off.

Dan


 ---- On Fri, 21 Oct 2022 11:50:18 -0700  Randall White  wrote ---

**Comment by n3m0-22** [comment]
Are you still having the original issue with text being selected and deleted?

**Comment by n3m0-22** [comment]
I'm closing this issue. I can reopen it if the problem come back.
