### ISSUE TITLE
Getting this error on os updates through pop shop

### ISSUE THREAD

**Issue by franklinrajasekar** [pop-os/pop#2661]
**Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
franklinr@pop-os:~$ apt policy $PACKAGE NAME
N: Unable to locate package NAME
```

**Issue/Bug Description:**
Error while installing package: 0.0000

**Steps to reproduce (if you know):**
update os through pop shop

**Expected behavior:**
run os updates 

**Other Notes:**

**Comment by leviport** [comment]
That error isn't very descriptive, but this article will likely fix whatever package manager issue is the cause: https://support.system76.com/articles/package-manager-pop

Hope that helps!

**Comment by franklinrajasekar** [comment]
cleared it up, thank you.
