### ISSUE TITLE
nvidia GPU stopped working after upgrade to kernel 6

### ISSUE THREAD

**Issue by lmassach** [pop-os/pop#2663]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 ```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
See below.

**Issue/Bug Description:**
Today I ran `sudo apt update && sudo apt full-upgrade && flatpak upgrade` and, among other things:
 - the kernel was upgraded from `5.19.16-76051916-generic` to `6.0.2.76060002-generic`;
 - the nvidia drivers were upgraded from `470.141.03-1pop0~1660260989~22.04~d973896` to `470.141.03-1pop0~1665506850~22.04~e6b02c4`;
 - flatpak upgraded the various `org.freedesktop.Platform.GL.nvidia-470-*`

Full detailed history: [apt_full_upgrade_summary_2022-10-26.txt](https://github.com/pop-os/pop/files/9873046/apt_full_upgrade_summary_2022-10-26.txt), [flatpak_upgrade_history_2022-10-26.txt](https://github.com/pop-os/pop/files/9873160/flatpak_upgrade_history_2022-10-26.txt).

After rebooting, my nvidia GPU (GeForce GTX 960M) no longer works (`nvidia-smi` does not find any device, yuzu only allows me to select the CPU integrated graphics, etc). I tried to reboot again, but with the old kernel (5.19.16 instead of 6.0.2) and the GPU works again.

Looking at `journalctl` I see this error when I boot with the new kernel
```
Oct 26 20:16:33 rog-h3ll-pop kernel: [drm:nv_drm_probe_devices [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to register device
Oct 26 20:16:33 rog-h3ll-pop kernel: [drm:nv_drm_load [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to allocate NvKmsKapiDevice
Oct 26 20:16:33 rog-h3ll-pop kernel: NVRM: GPU 0000:01:00.0: rm_init_adapter failed, device minor number 0
Oct 26 20:16:33 rog-h3ll-pop kernel: NVRM: GPU 0000:01:00.0: RmInitAdapter failed! (0x30:0xffff:874)
Oct 26 20:16:33 rog-h3ll-pop kernel: NVRM: GPU 0000:01:00.0: Failed to copy vbios to system memory.
```
Full logs [boot_with_kernel_6.0.txt](https://github.com/pop-os/pop/files/9873246/boot_with_kernel_6.0.txt), [boot_with_kernel_5.19.txt](https://github.com/pop-os/pop/files/9873247/boot_with_kernel_5.19.txt).

**Steps to reproduce (if you know):**
1. Run `sudo apt update && sudo apt full-upgrade && flatpak upgrade`
2. Reboot
3. Try to run `nvidia-smi` or anything capable of detecting/using the nvidia GPU
4. Reboot with the old kernel (5.19.16-76051916-generic)
5. Try point 3 again

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
I'd recommend reinstalling the Nvidia driver. The 960M should be supported by the 515 driver, but feel free to substitute the 470 driver instead, if you prefer that older version.

```
sudo apt purge ~nnvida
sudo apt autoremove && sudo apt clean
sudo apt install nvidia-driver-515
```
and then reboot

**Comment by lmassach** [comment]
Tried this

> I'd recommend reinstalling the Nvidia driver. The 960M should be supported by the 515 driver, but feel free to substitute the 470 driver instead, if you prefer that older version.
> 
> ```
> sudo apt purge ~nnvida
> sudo apt autoremove && sudo apt clean
> sudo apt install nvidia-driver-515
> ```
> 
> and then reboot

now it doesn't work with any kernel. If I run `nvidia-smi` I get
```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
Logs: 
[boot_with_kernel_5.txt](https://github.com/pop-os/pop/files/9878005/boot_with_kernel_5.txt)
[boot_with_kernel_6.txt](https://github.com/pop-os/pop/files/9878006/boot_with_kernel_6.txt)

**Comment by leviport** [comment]
It might be worth testing whether you can boot the latest live disk, which comes with Nvidia 515 and kernel 6.0.2. If it boots successfully and you see the Nvidia driver running, then the problem must be the way the existing installation is configured.

**Comment by lmassach** [comment]
With the latest live disk it seems to work. It has to be my configuration indeed.
[boot_with_live_usb.txt](https://github.com/pop-os/pop/files/9888097/boot_with_live_usb.txt)

**Comment by lmassach** [comment]
Tried
```
sudo apt install --reinstall linux-image-generic linux-headers-generic
sudo update-initramfs -c -k all
```
and
```
sudo apt install --reinstall linux-headers-6.0.2-76060002 linux-headers-6.0.2-76060002-generic linux-image-6.0.2-76060002-generic linux-modules-6.0.2-76060002-generic
sudo update-initramfs -c -k all
```
but nothing changed.

Terminal outputs:
[kernel_reinstall_01.txt](https://github.com/pop-os/pop/files/9893411/kernel_reinstall_01.txt)
[kernel_reinstall_02.txt](https://github.com/pop-os/pop/files/9893412/kernel_reinstall_02.txt)

**Comment by leviport** [comment]
Those outputs all look normal. Did you check whether the Nvidia driver was installed afterwards? If yes, is it 515 or 510?

**Comment by KairanD** [comment]
There is something wrong with Nvidia 470 on kernel 6.0. The driver also installs normally on my laptop, but the card is not detected. It was working fine with 5.19.

I tried purging, reinstalling, everything... Nothing works. Even a fresh install of Pop!_OS has this problem with driver 470.

There are some similar reports around. I guess it's a Nvidia problem.

**Comment by leviport** [comment]
@KairanD that sounds unrelated to this issue. Please open a new issue in https://github.com/pop-os/nvidia-graphics-drivers-470/issues and include some hardware info, especially your GPU model.

**Comment by KairanD** [comment]
@leviport Thanks for answering.

I believe it is related because this problem is affecting more people. My laptop is an Asus K46CB with Core i7 3537U and GT 740M (128 bits, Kepler). I found these reports with the same problem, always using driver 470 with the new 6.0 kernel on Pop!_OS:

- GT 640M: https://plus.diolinux.com.br/t/preciso-de-ajuda-para-gerenciar-drivers-no-pop-os-resolvido/48785
- GT 740M (another user, not me): https://discord.com/channels/845005478111346708/1035652201697259570
- GT 920M: https://discord.com/channels/845005478111346708/1035933215652859965
- Another GT 920M: https://www.reddit.com/r/pop_os/comments/ydwn4h/nvidiadriver470_nvidiasmi_says_no_device_were/
- GTX 960M (this topic).

The driver (470) was working fine with the kernel 5.19 in all cases listed above. After the update to 6.0, all these cards are not being detected.

With this new kernel, drivers 390 and 418 do not compile. Driver 470 compiles, but it's not working properly. Drivers 510, 515 and 520 are apparently working fine (when there's the possibility of using them, since it's necessary to have a newer card). My desktop PC has a GTX 1070Ti and it's working fine with driver 520 (installed before it was hidden from the Pop!_Shop).

I just found that there's already a pull request for the GT 740M, but I don't know if it's going to fix the problem for the other cards: https://github.com/pop-os/nvidia-graphics-drivers-470/pull/10.

I avoided opening another issue due to the risk of creating a duplicate. However, I can create as suggested if still needed.

Thanks for helping! :)

**Comment by leviport** [comment]
I'm pretty sure this issue wasn't supposed to be specific to the 470 driver, even if that was the original root cause, and I was only trying to make sure we weren't hijacking this issue from the original reporter.

If you'd like to try out https://github.com/pop-os/nvidia-graphics-drivers-470/pull/10, you can do so with these commands:
```
apt-manage add popdev:740m
sudo apt update && sudo apt upgrade
```

Then once you're ready to remove that testing source:
```
apt-manage remove popdev-740m
```

**Comment by KairanD** [comment]
@leviport Thanks for showing me how to test the proposed update. Unfortunately, this didn't work. The request was also closed.

It seems to be an Nvidia issue. Maybe we will have to wait until Nvidia provides a fix?

I'm participating in a Pop!_OS brazilian group in Telegram and I just saw a complaint from a desktop user saying that his system is not booting up (since there are no integrated graphics) after updating to kernel 6.0 with Nvidia 470 drivers installed.

**Comment by leviport** [comment]
>Maybe we will have to wait until Nvidia provides a fix?

If it's a problem with the 470 driver itself, then yeah we'd probably have to wait until Nvidia has a fix.

**Comment by lmassach** [comment]
Sorry for the late response.

> Those outputs all look normal. Did you check whether the Nvidia driver was installed afterwards? If yes, is it 515 or 510?
I checked the installed packages: 515 is installed; 510 or 470 are no longer there.

Still, I think @leviport might be right about this problem being unrelated with @KairanD's: my GPU _is_ working with the live USB, which should have driver 515 only (or does the live USB also have other versions of the driver installed?).

**Comment by leviport** [comment]
The current ISO (and probably several versions back) should have 515. I don't think 510 has been on a live disk for at least the last several releases. The current ISO, number 16, will have the 6.0 kernel, as well as the 515 driver, so if that's working on your system, then there has to be something misconfigured. 

I'm still surprised that purging and reinstalling Nvidia didn't help. This happens on occasion, and that almost always seems to clear it up. It might be worth trying that again, then making sure the machine is set to Nvidia graphics mode? You can do that by running `system76-power graphics nvidia` and then rebooting.

**Comment by lmassach** [comment]
I booted the live USB again (number 16, as you mentioned), and confirmed it only has drivers 515 and kernel 6.0.2.

I can try to purge and reinstall the drivers again, but I already did it a couple of times, and set the graphics mode to nvidia or hybrid from the GUI both of the times.

**Comment by lmassach** [comment]
Just tried
```
sudo apt purge "~nnvidia"
sudo apt autoremove
audo apt clean
sudo apt install nvidia-driver-515
system76-power graphics nvidia
```
and rebooted. Now it works. Also tried hybrid mode and it works. I don't think I changed anything in the meanwhile, so I am not sure what made the difference. Anyway, thanks for your help.

**Comment by T100D** [comment]
Same problem here with nvidia-driver-470 and NVIDIA Corporation GK208M [GeForce GT 730M].

lspci tells me the card is there:
` 01:00.0 VGA compatible controller: NVIDIA Corporation GK208M [GeForce GT 730M] (rev a1)`

modinfo indicates no driver present:
```
modinfo /usr/lib/modules/$(uname -r)/kernel/drivers/video/nvidia.ko
modinfo: ERROR: Module /usr/lib/modules/6.0.6-76060006-generic/kernel/drivers/video/nvidia.ko not found.
```

ubuntu states it is more a kernel problem than a driver problem: [bugs.launchpad.net/ubuntu/ +bug/1994435](https://bugs.launchpad.net/ubuntu/+source/ubuntu-drivers-common/+bug/1994435)

newer drivers do not support this system and this casd for lspci not showing the card anymore with newer drivrers installed.

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

```

**Comment by kyoku37** [comment]
> 

Also got a 730M (Thinkpad T540p)

Kernel version 6.0.12-76060006-generic just dropped.
Still same issue. The "old kernel" option inside of the recovery menu uses ver. 6.0.6 now which also doesn't work.
Before this update the old version was: linux-headers-5.19.0-76051900 and 470.141.03 worked on it.

I wish 470.161.03 would drop cause it supposedly fixes the issue...

A temporary fix is to use 390 drivers, but from what I've seen some GPU technologies are not supported on those drivers.
Couple of patches are floating around the web, but I had no luck with using them.

**Comment by T100D** [comment]
Same hardware, 390 works, but fractional scaling seems to be off, luckily the performance is not bad with the default card.

**Comment by T100D** [comment]
Installed nvidia-driver-470 server and looks like 470.161.03 is up and running:
```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   52C    P0    N/A /  N/A |    280MiB /   983MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


```

**Comment by kyoku37** [comment]
> Installed nvidia-driver-470 server and looks like 470.161.03 is up and running:
> 
> ```
> $ nvidia-smi
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 N/A |                  N/A |
> | N/A   52C    P0    N/A /  N/A |    280MiB /   983MiB |     N/A      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```

Can confirm that this works.
I also managed to run Minecraft with these drivers and it's running on the GPU so all is good for now :)

**Comment by T100D** [comment]
Solverd, version is upped https://github.com/pop-os/nvidia-graphics-drivers-470/pull/12
