### ISSUE TITLE
Thinkpad X1 Carbon Gen 9 Hangs When Waking Up From Hibernation/Suspend

### ISSUE THREAD

**Issue by helios2k6** [pop-os/pop#2675]
**Distribution:**
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
[thinkpad-x1][/var/log] > 
```

*uname -a*
`Linux thinkpad-x1 6.0.3-76060003-generic #202210211149~1666452039~22.04~1891946 SMP PREEMPT_DYNAMIC Sat O x86_64 x86_64 x86_64 GNU/Linux`

**Issue/Bug Description:**
Display is black when laptop is attempting to resume from hibernation or suspend. Hibernation can be triggered by running `sudo systemctl hibernate` and suspend can be triggered by closing the lid.

**Steps to reproduce (if you know):**
1/ Run `sudo systemctl hibernate` or close the lid of the laptop
2/ Open the lid of the laptop
3/ Observe that the screen is still dark
4/ Hit any key or attempt to use the trackpad
5/ Continue to observe that the screen is dark and that the system is unresponsive

**Expected behavior:**
The system resumes from hibernation/suspend promptly.

**Other Notes:**
This laptop does not have any Nvidia drivers or GPUs. 

I've viewed several of the previous issues and none of them seem to actually have an answer to the problem.

The system does come back to life after about 2 minutes of constantly hitting the keyboard. Not sure if that matters.

[kern.log](https://github.com/pop-os/pop/files/9933665/kern.log)
[journalctl_logs.txt](https://github.com/pop-os/pop/files/9933667/journalctl_logs.txt)
[lspci.txt](https://github.com/pop-os/pop/files/9933674/lspci.txt)

**Comment by bovicbro** [comment]
I have experienced the same issue, booted with old kernel fixes it for me. 

Linux nl 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux

**Comment by helios2k6** [comment]
> I have experienced the same issue, booting with old kernel fixes it for me.
> 
> Lenovo thinkpad X1 Carbon gen 10
> 
> Linux nl 5.19.16-76051916-generic #202210150742~1666053244~22.04~cf07008 SMP PREEMPT_DYNAMIC Tue O x86_64 x86_64 x86_64 GNU/Linux

Nice! So I just booted using the previous kernel by holding down the Space key on boot and selecting the `Pop!_OS (Pop_OS-oldkern.conf)`

```
> uname -a
Linux thinkpad-x1 6.0.2-76060002-generic #202210150739~1666289067~22.04~fe0ce53 SMP PREEMPT_DYNAMIC Thu O x86_64 x86_64 x86_64 GNU/Linux
```
And suspend and hibernate are working as intended.

As an aside, to view the different kernel boot options:
```
> sudo bootctl list
        title: Pop!_OS (Pop_OS-current.conf) (default)
           id: Pop_OS-current.conf
       source: /boot/efi/loader/entries/Pop_OS-current.conf
        linux: /EFI/Pop_OS-5c8af9f8-89ea-4136-8cac-be39559a894e/vmlinuz.efi
       initrd: /EFI/Pop_OS-5c8af9f8-89ea-4136-8cac-be39559a894e/initrd.img
      options: root=UUID=5c8af9f8-89ea-4136-8cac-be39559a894e ro quiet loglevel=0 systemd.show_status=false splash i915.enable_psr=0

        title: Pop!_OS (Pop_OS-oldkern.conf)
           id: Pop_OS-oldkern.conf
       source: /boot/efi/loader/entries/Pop_OS-oldkern.conf
        linux: /EFI/Pop_OS-5c8af9f8-89ea-4136-8cac-be39559a894e/vmlinuz-previous.efi
       initrd: /EFI/Pop_OS-5c8af9f8-89ea-4136-8cac-be39559a894e/initrd.img-previous
      options: root=UUID=5c8af9f8-89ea-4136-8cac-be39559a894e ro quiet loglevel=0 systemd.show_status=false splash i915.enable_psr=0

        title: Pop!_OS recovery
           id: Recovery-8856-5501.conf
       source: /boot/efi/loader/entries/Recovery-8856-5501.conf
        linux: /EFI/Recovery-8856-5501/vmlinuz.efi
       initrd: /EFI/Recovery-8856-5501/initrd.gz
      options: boot=casper hostname=recovery userfullname=Recovery username=recovery live-media-path=/casper-8856-5501 live-media=/dev>

        title: Reboot Into Firmware Interface
           id: auto-reboot-to-firmware-setup
       source: /sys/firmware/efi/efivars/LoaderEntries-4a67b082-0a4c-41cf-b6c7-440b29bb8c4f
```

**Comment by helios2k6** [comment]
It appears that a kernel change between `6.0.2-76060002-generic`  and `6.0.3-76060003-generic` is causing issues when attempting to resume from a suspended state.

**Comment by helios2k6** [comment]
I just updated to the 6.0.6 Linux kernel and this issue appears to be resolved:
```
> uname -a
Linux thinkpad-x1 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux
```
