### ISSUE TITLE
Disabling HiDPI Daemon doesn't hide notifications

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#268]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
annoying HiDPI notification won't go away, even if I turned the HiDPI daemon off.

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
How did you turn the daemon off?

**Comment by cunctator00** [comment]
there is an option in Settings->Display.
If you set the screen resolution and then turn the daemon off it will keep the resolution set at the next reboot and make it persistent.

**Comment by djordan2** [comment]
Thanks for reporting this!  It's a known bug that disabling the hidpi daemon doesn't hide the notification, which we'll be addressing as soon as possible.

**Comment by cunctator00** [comment]
UPDATE: when using the laptop alone I don't get the notification, but when I connect an external HDMI monitor then I get the notification which won't go away.

**Comment by cunctator00** [comment]
...and then even if I disconnect the HDMI screen, the notification stays

**Comment by brs17** [comment]
Yes, so the notification only appears once a hidpi screen is detected. It sounds like your external monitor is but your internal monitor is not. 

It is a known issue that the notification should go away once the hidpi screen is disconnected.

**Comment by djordan2** [comment]
Fixed.

**Comment by mcandre** [comment]
@djordan2 Awesome, looking forward to this merging soon. Any idea when this becomes available for plain vanilla Ubuntu 18.10 users?

**Comment by jackpot51** [comment]
@mcandre This was already fixed and released, could you describe the issue you are seeing?
