### ISSUE TITLE
Gnome shell crash with segmentation fault

### ISSUE THREAD

**Issue by Derisis13** [pop-os/pop#2681]
**Distribution (run `cat /etc/os-release`):**
 ```
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 ```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
gnome-shell:
  Installed: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Candidate: 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8
  Version table:
     42.5-0ubuntu1 500 (phased 0%)
        500 http://hu.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages
 *** 42.3.1-2ubuntu1pop1~1660592271~22.04~ca01bf8 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     42.0-2ubuntu1 500
        500 http://hu.archive.ubuntu.com/ubuntu jammy/main amd64 Packages
```
**Issue/Bug Description:**

On random occasions Gnome just crashes. I don't know when it started, but it has been annoying me for a long time now. 

For a moment, I see the TTY, then I'm greeted with a login screen. Digging in dmesg and journalctl I found this: 

![Screenshot from 2022-11-04 11-19-53](https://user-images.githubusercontent.com/66648475/200091198-6f12263e-b9c3-464b-a873-21e0170ba42b.png)

The two gnome shell allocations of the highest possible unsigned value seem suspicious to me, but I don't know where to follow this lead.

**Steps to reproduce (if you know):**

unknown

**Expected behavior:**

Gnome shouldn't do anything that creates a segfault.

**Other Notes:**

I'm using wayland, haven't tried to reproduce on X11.

**Comment by HiraduNakamura** [comment]
I have the exact same issue

**Comment by Derisis13** [comment]
For me, it turned out that it was an extension, that caused the crashes - AWSM (another window session manager). The issue has been fixed since then, and I haven't seen a segfault for a while now. I suggest you to try turning off extensions to see if they cause the segfault
