### ISSUE TITLE
PC won't boot after power outage

### ISSUE THREAD

**Issue by ydhnwb** [pop-os/pop#2690]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When PC is power off caused by power outage, PC will not boot on next time power on. It only shows bootsplash (my case: "Asrock") forever, but when I press the keyboard, CLI does show but not GUI.

I tried to power it off again by holding power button, doesnt work.
For now, the only thing to fix this, is boot to my Windows partition (yes, I have dual boot), turn off my pc through windows, then power it on again.

**Steps to reproduce (if you know):**
turn off/plug out your power brick to recreate power outage when pc is turned on.

**Expected behavior:**
PC boot on next power on

**Other Notes:**
I am using nVidia GTX 1650 D6 and intel F series (Just in case this is needed).
Kernel version: 6.0.6-76060006-generic (also happens on some 5.1x  kernel)

**Comment by leviport** [comment]
>but when I press the keyboard, CLI does show but not GUI.

What do you see when the CLI shows? If there is text being displayed, it could be very important for understanding the situation.

**Comment by ydhnwb** [comment]
![Uploading 20221218_143248.jpg…]()

**Comment by ydhnwb** [comment]
![20221218_143248](https://user-images.githubusercontent.com/26734262/208286792-64aa6f92-c316-4cb4-8e3f-cc5d6eeee3b2.jpg)

**Comment by ydhnwb** [comment]
https://user-images.githubusercontent.com/26734262/208623657-3414bfff-6452-4191-a4bf-cdceb3c15fa6.mp4

This issue remain exists

**Comment by ydhnwb** [comment]
I found something, after I let my pc waiting on Asrock logo/bootsplash for ~7minutes, it shows me a log and boot up to DE. 

I think i'll close this issue.
