### ISSUE TITLE
No Audio output, despite showing audio devices.

### ISSUE THREAD

**Issue by NOOBLINUXUSER** [pop-os/pop#2693]
any solutions guys? this happened to just today, i switched to usb headphones, and when i tried to get back into my analog audio. this happened. it works well on my windows install.
This is the output on ``pw-top``
![image](https://user-images.githubusercontent.com/66922885/201480452-b88aedad-b42e-4a70-b001-2c0f588d091b.png)
And this is what ```● pipewire.service - PipeWire Multimedia Service
     Loaded: loaded (/usr/lib/systemd/user/pipewire.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2022-11-13 02:55:49 +06; 5h 47min left
TriggeredBy: ● pipewire.socket
   Main PID: 1360 (pipewire)
      Tasks: 2 (limit: 18985)
     Memory: 13.2M
        CPU: 1.489s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/pipewire.service
             └─1360 /usr/bin/pipewire

Nov 13 02:55:49 pop-os systemd[1344]: Started PipeWire Multimedia Service.
Nov 13 02:55:49 pop-os pipewire[1360]: mod.rt: Can't find xdg-portal: (null)
Nov 13 02:55:49 pop-os pipewire[1360]: mod.rt: found session bus but no portal```  
```systemctl --user status pipewire``` shows

_Originally posted by @NOOBLINUXUSER in https://github.com/pop-os/pop/issues/2487#issuecomment-1312502356_

**Comment by NOOBLINUXUSER** [comment]
I tested on a recovery partition, with a different kernel, referenced on that thread (that's what you call it right?)

**Comment by NOOBLINUXUSER** [comment]
solved via this https://bbs.archlinux.org/viewtopic.php?id=273805 
``` cat /etc/modprobe.d/audio-jack.conf
options snd_hda_intel model=headset-mode```
and a reboot

**Comment by jacobgkau** [comment]
> so i just use sudo vim cat /etc/modprobe.d/audio-jack.conf

I assume you mean `sudo vim /etc/modprobe.d/audio-jack.conf` (no `cat` in that command to create the file).

**Comment by NOOBLINUXUSER** [comment]
ye
