### ISSUE TITLE
Still can't get bluetooth working on Pop_OS 22.04

### ISSUE THREAD

**Issue by 0wx** [pop-os/pop#2697]
**(1) Issue/Bug Description:**
I had bluetooth 5.0 dongle not working on my PC

**(2) Steps to reproduce (if you know):**

**(3) Expected behavior:**
working bluetooth of course

**(4) Distribution (run `cat /etc/os-release`):**
 ```
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**(5) Gnome Shell version:**
42.5

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
pop-shell:
  Installed: 1.1.0~1667482449~22.04~30bf682
  Candidate: 1.1.0~1667482449~22.04~30bf682
  Version table:
 *** 1.1.0~1667482449~22.04~30bf682 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status

```

**(7) Where was Pop Shell installed from:**
Official website iso

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
2x1080p

What I've been trying:
- Install bluez, bluetooth manager
- installing driver from MPOW (rtk_btusb)

**Comment by ydhnwb** [comment]
What ia the type of your bluetooth dongle?
I was have this problem with Totolink dongle then i fixed it by installing the driver manually (you need to know the chipset)

**Comment by richardHangHimself** [comment]
I have the same issue. And I suspect the kernel version, however I did not troubleshoot it yet. 

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
> uname -a 

```
Linux glx 6.0.12-76060006-generic #202212290932~1671652965~22.04~452ea9d SMP PREEMPT_DYNAMIC Wed D x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jacobgkau** [comment]
What does "still" mean in the issue title? What previous information or report were you referring to?

**Comment by 0wx** [comment]
@jacobgkau still can't get it work after trying a lot of guide on the internet, I downgraded to Pop OS 20.04, and my bluetooth dongle working again
![Screenshot from 2022-12-30 13-28-20](https://user-images.githubusercontent.com/28288911/210041267-cbc4e3c6-bba9-401a-b889-e0ee08cf94e6.png)
![Screenshot from 2022-12-30 13-29-38](https://user-images.githubusercontent.com/28288911/210041329-65e80fe5-6098-4e33-a478-c82aefb04c05.png)

**Comment by mcd92** [comment]
Same issue here.

Tried quite a few tutorials, resetting bluetooth service, installing blueman, nothing worked. It is like this since the upgrade to 22.04. Running a VM on Unraid.

Thinking about downgrading back to 20.04.

If anyone finds a solution that does not involve downgrading, please share.

![image](https://github.com/pop-os/pop/assets/20120390/822cac59-a7ab-4623-a466-19284824c959)

**Comment by 0wx** [comment]
This is solved, I just reinstall the pop os itself with newest iso build, now everything works fine.

**Comment by mlp1802** [comment]
Wow the most userfriendly os cant get bluetooth working lol
