### ISSUE TITLE
Revert Button for OS side-by-side installation needed

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#27]
_From @brs17 on October 11, 2017 16:13_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
In the Ubiquity installer, when selecting to install Pop!_OS alongside another OS, a graphical tool is shown asking the user to customize how much space each OS should take up on the drive. In the advance partitioning tool, there is a revert button in case a change is made that the user did not want done. This does not exist in the simple setup. While the "back" button does undo all changes, a Revert button should be added to simplify and match with the more advance partitioning tool.  The page I am detailing is shown in the image below.

![screenshot from 2017-10-10 23-11-34](https://user-images.githubusercontent.com/7460774/31452594-9b3f508a-ae6c-11e7-85c0-57676561ac5c.png)

**Steps to reproduce (if you know)**
Run the installer with an OS already installed on the harddrive.

**Expected behaviour**

**Other Notes**

_Copied from original issue: pop-os/iso#138_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
