### ISSUE TITLE
lemp10 MicroSD card reader not working

### ISSUE THREAD

**Issue by phrogpilot73** [pop-os/pop#2707]
**Distribution (run `cat /etc/os-release`):** 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure which related package it may be.

**Issue/Bug Description:**
MicroSD card reader on Lemur Pro 10 is not recognizing that a MicroSD card is inserted. 

**Steps to reproduce (if you know):**
Insert MicroSD card.
Does not auto mount.
Does not show in Gnome Disks.

**Expected behavior:**
MicroSD card will mount, or at least be seen by Pop!_OS.

**Other Notes:**
Tried an external reader, and MicroSD card was recognized/read.
Tried built-in MicroSD card reader on Windows 10 partition - was recognized, so not hardware.
Tried multiple different MicroSD cards/file systems. Does not recognize any of them.
It was working on December 1st (3 days ago), because I flashed a Raspberry Pi bootloader. One of the updates between then and now may be the cause.

**Comment by jacobgkau** [comment]
I am not seeing this issue on a lab lemp10. After installing all updates today (including Linux 6.0.6~d94609a), a microSD card is still detected and auto-mounted. The SD card I'm using to test is a 16GB Class 10 MicroSDHC card that is Micro Center brand.

What SD card are you using? Does anything show up in `sudo dmesg --follow` when you insert the card (especially the first time after booting)?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by phrogpilot73** [comment]
I'm using SanDisk, MicroCenter, and a cheap Chinese one that came with my 3D printer. None of them are recognized. All sizes (from 8GB to 128GB), SDHC/SHXC, all UHS-1, Class 10.

dmesg --follow: absolutely no output when I insert a MicroSD card. 

However, when I boot into pop_os.oldkern.conf, it works. 

uname -r for pop_os.oldkern.conf: 6.0.3-76060003-generic (MicroSD works)

uname -re for pop_os.current.conf: 6.0.6-76060006-generic (MicroSD doesn't work)

**Comment by phrogpilot73** [comment]
Whatever kernel update happened today fixed the issue.

**Comment by jacobgkau** [comment]
> Whatever kernel update happened today fixed the issue.

There was no kernel update today/yesterday, the latest version is still d94609a: https://github.com/pop-os/linux/commits/master 

Glad to hear something else fixed it, though.

**Comment by phrogpilot73** [comment]
NGL - I wasn't REALLY paying attention when doing the updates from the CL, just saw the standard message pop up:

```
update-initramfs: Generating /boot/initrd.img-6.0.6-76060006-generic
cryptsetup: WARNING: Resume target cryptswap uses a key file
```

during the update, so assumed it was a kernel module being updated. I could dig into the logs and figure it out, but it's working - and I guess I might be the only one that had the "glitch"
