### ISSUE TITLE
touchpad scrolling inconsistent

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#271]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os or start a conversation in our chat https://chat.pop-os.org/ - as these are the proper forums for those types of posts.

 **Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 **Related Application and/or Package Version - apt policy $PACKAGE NAME**

**Issue/Bug Description**
working flawlessly in Pop_OS! 17.10, now inconsistent. Sometimes it doesn't work sometimes it scrolls not enough.

**Steps to reproduce (if you know)**

**Expected behavior**

**Other Notes**

**Comment by brs17** [comment]
@cunctator00 on what hardware are you having this issue?

**Comment by cunctator00** [comment]
this is so weird, now it seems to have stabilized...
anyway it's a Lenovo X1 Carbon

**Comment by brs17** [comment]
Hmmm, interesting. Not too familiar with the X1 and some of the Linux quirks that exist but definitely seems like you aren't the only one who hasn't had issues at somepoint with Ubuntu based systems: 

https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_5)#Bug:_Trackpoint.2FTrackpad_not_working)

Going to close this issue, but I'd love to hear if you end up finding a fix for the issue(if it happens again)

**Comment by bgSosh** [comment]
I've got the same issue with a 3rd gen Lenovo carbon x1.  Most of the time it's impossible to click-drag with the touch pad (sometimes works for no apparent reason).
