### ISSUE TITLE
Installer/LiveCD Not working in ASUS TUF Gaming notebook

### ISSUE THREAD

**Issue by oti4500** [pop-os/pop#2718]
**Distribution:**
 Latest version (22.04) w/ Nvidia driver
 
**Issue/Bug Description:**
error: /casper_popos_22.04_amd64_nvidia_debug_298/vmlinuz.efi has invalid signature. error: you need to load the kernel first. 
Press any key to continue...

**Steps to reproduce (if you know):**
Boot the bootable USB from UEFI (non-legacy BIOS)
Enter the "Try or Install Pop_OS"

**Other Notes:**
ASUS TUF GAMING A15 (2022) Ryzen 7 /w RTX 3070 and (factory) 16 GB Ram and 1TB Kingston M.2 SSD, Windows 11 Pro is included
Secure boot: ON (unable to disabling this one)
UEFI: On
Latest UEFI version: Yes

**Comment by leviport** [comment]
Secureboot definitely needs to be disabled. Secureboot support is something that'll come at a later time, but right now it is not supported.
