### ISSUE TITLE
failing to update system

### ISSUE THREAD

**Issue by 2legged4ox** [pop-os/pop#2719]
**Distribution (run `cat /etc/os-release`):**
Pop!_OS 22.04

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy

**Issue/Bug Description:**
<html>Package download failed:<br/><br/>E: http://apt.pop-os.org/ubuntu jammy-updates/main amd64 python3-problem-report all 2.20.11-0ubuntu82.3 is not (yet) available (Error writing to file - write (28: No space left on device) [IP: 99.86.114.6 80])
E: http://apt.pop-os.org/ubuntu jammy-updates/main amd64 python3-apport all 2.20.11-0ubuntu82.3 is not (yet) available (Error writing to file - write (28: No space left on device) [IP: 99.86.114.6 80])
E: http://apt.pop-os.org/ubuntu jammy-updates/main amd64 apport all 2.20.11-0ubuntu82.3 is not (yet) available (Error writing to file - write (28: No space left on device) [IP: 99.86.114.6 80])
</html>

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

my system memory is low as well

**Comment by leviport** [comment]
>No space left on device

looks like your disk is full

**Comment by 2legged4ox** [comment]
thanks, sorted
