### ISSUE TITLE
Release 21 of 18.04 Installer Crash

### ISSUE THREAD

**Issue by legendarykai** [pop-os/pop#272]
**Distribution - (run ```cat /etc/os-release```)**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 

**Issue/Bug Description**
18.04 Installer crashes on Meerkat.  
When I run the installer and select Customize Partitions, the installer will hang then crash. 

**Steps to reproduce (if you know)**
Run installer from USB, select Customize partitions.

**Expected behavior**
Some sort of screen to customize partitions.

**Other Notes**
in syslog:

May 10 03:47:35 pop-os io.elementary.installer.desktop[6026]: libdistinst: found existing LVM device on "/dev/sda2"
May 10 03:47:35 pop-os io.elementary.installer.desktop[6026]: File descriptor 12 (/dev/mapper/control) leaked on vgchange invocation. Parent PID 6026: /usr/bin/io.elementary.installe
May 10 03:47:40 pop-os io.elementary.installer.desktop[6026]: thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
May 10 03:47:40 pop-os io.elementary.installer.desktop[6026]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
May 10 03:47:40 pop-os io.elementary.installer.desktop[6026]: fatal runtime error: failed to initiate panic, error 5

**Comment by mmstick** [comment]
@legendarykai Are you able to give the output of `lsblk -f`? And if possible, kill the installer, then get the backtrace by re-running the installer with `sudo env RUST_BACKTRACE=1 io.elementary.installer`. That should tell me which line the panic happened on. If it happened on the custom partitioning view, it may be related to getting information about a specific partition.

**Comment by legendarykai** [comment]
@mmstick 

pop-os@pop-os:~$ lsblk -f
NAME                  FSTYPE      LABEL              UUID                                   MOUNTPOINT
loop0                 squashfs                                                              /rofs
sda                                                                                         
├─sda1                vfat                           D5BB-E422                              
└─sda2                LVM2_member                    9S2cIW-CbIY-gnE9-otyR-G4BG-DcfW-ZUPAJ1 
  ├─pop_os--vg-root   ext4                           50e62243-c68b-49a9-b61e-a3f79ef1dc67   
  └─pop_os--vg-swap_1 swap                           e4f875b0-259a-4fb0-99c6-9c1cb210d5eb   
sdb                   iso9660     Pop_OS 18.04 amd64 2018-05-03-18-45-02-00                 /cdrom
├─sdb1                iso9660     Pop_OS 18.04 amd64 2018-05-03-18-45-02-00                 
└─sdb2                vfat        Pop_OS 18.04 amd64 775E-D5E6                              
sdc                   ntfs        tux                04CF08D54C05504F                       /media/pop-os/tux

**Comment by legendarykai** [comment]
@mmstick Thanks for looking in to this!

pop-os@pop-os:/var/crash$ sudo env RUST_BACKTRACE=1 io.elementary.installer 
Gtk-Message: 00:50:42.330: GtkDialog mapped without a transient parent. This is discouraged.

** (io.elementary.installer:2726): WARNING **: 00:50:42.342: Inhibitor.vala:62: Could not inhibit screen: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.ScreenSaver was not provided by any .service files
libdistinst: found existing LVM device on "/dev/sda2"
File descriptor 11 (/dev/mapper/control) leaked on vgchange invocation. Parent PID 2726: io.elementary.installer
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: distinst_disks_initialize_volume_groups
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: g_object_new_valist
  17: g_object_new
  18: <unknown>
  19: g_closure_invoke
  20: <unknown>
  21: g_signal_emit_valist
  22: g_signal_emit
  23: <unknown>
  24: g_signal_emit_valist
  25: g_signal_emit
  26: <unknown>
  27: <unknown>
  28: g_closure_invoke
  29: <unknown>
  30: g_signal_emit_valist
  31: g_signal_emit
  32: <unknown>
  33: ffi_call_unix64
  34: ffi_call
  35: g_cclosure_marshal_generic_va
  36: <unknown>
  37: g_signal_emit_valist
  38: g_signal_emit
  39: <unknown>
  40: g_cclosure_marshal_VOID__BOXEDv
  41: <unknown>
  42: g_signal_emit_valist
  43: g_signal_emit
  44: <unknown>
  45: <unknown>
  46: <unknown>
  47: gtk_event_controller_handle_event
  48: <unknown>
  49: <unknown>
  50: <unknown>
  51: g_signal_emit_valist
  52: g_signal_emit
  53: <unknown>
  54: <unknown>
  55: gtk_main_do_event
  56: <unknown>
  57: <unknown>
  58: g_main_context_dispatch
  59: <unknown>
  60: g_main_context_iteration
  61: g_application_run
  62: _vala_main
  63: __libc_start_main
  64: _start
fatal runtime error: failed to initiate panic, error 5
Aborted

**Comment by mmstick** [comment]
@legendarykai I guess all the debugging symbols have been stripped from the package. The backtrace contains no additional information. I'm not sure what's causing the issue, but I'll try to replicate your layout on my end. I've recently pushed changes to distinst to give more detailed info for panics on optional values that have been unwrapped, so at least a newer ISO will feature more info.

**Comment by legendarykai** [comment]
@mmstick Cheers man.  No rush, appreciate the help.

**Comment by mmstick** [comment]
I tried with this layout, but was unable to replicate it:

```
sda                                                                                  
├─sda1         vfat                           2208-4681                              
├─sda2         ext4                           1343343e-9802-43da-9a17-0ac176416566   
├─sda3         ext4                           252f93ce-68cf-4ed8-8e6d-f148fea4a3ee   
├─sda4         ext4                           2429e718-3e1e-4118-a912-27408d4c44ca   
├─sda5         swap                           bceab69e-836f-4478-befd-39b4c9a88a5e   [SWAP]
└─sda6         ext4                           9db8b623-20a5-4ec5-860a-3b757331026e   
sdb            ntfs                           70D35A122D9D9EE9                       /media/pop-os/70D35A122D9D9EE9
sdc                                                                                  
├─sdc1         vfat                           731B-EB5E                              
└─sdc2         LVM2_member                    iPEpcf-RTHV-0c16-eZWV-LEEw-3TRZ-O6Qi9f 
  ├─data2-root ext4                           498b1f14-a6da-41d1-9ab3-450cfdf56000   
  └─data2-swap swap                           5d03eb37-b468-4dcc-b2ff-888905d2bfc9   
sdd            iso9660     Pop_OS 18.04 amd64 2018-05-03-18-45-02-00                 /cdrom
├─sdd1         iso9660     Pop_OS 18.04 amd64 2018-05-03-18-45-02-00                 
└─sdd2         vfat        Pop_OS 18.04 amd64 775E-D5E6  
```
I wonder if it's the naming of your LVM group / logical volumes that are confusing distinst. I'll check that next.
