### ISSUE TITLE
apt purge not removing thunderbird configuration files

### ISSUE THREAD

**Issue by pdqwq** [pop-os/pop#2721]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
This report is incomplete. You don't mention what you're trying to purge, and you didn't fill out the issue template. This issue can be reopened if you complete the report.
