### ISSUE TITLE
Keyboard Strokes Causing Unwanted Highlighting, and Deletion of Typed Text

### ISSUE THREAD

**Issue by pdqwq** [pop-os/pop#2722]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
This report is incomplete, but it sounds like you're using a laptop, and your palm is bumping the track pad as you type. There are some things that can be done to improve palm rejection, if that is the issue you're encountering. 

This issue can be reopened if you complete the report.
