### ISSUE TITLE
Unable  to install chmod

### ISSUE THREAD

**Issue by soma2000-lang** [pop-os/pop#2735]
Distribution (run cat /etc/os-release):

Related Application and/or Package Version (run apt policy $PACKAGE NAME):

system76-driverNAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

Issue/Bug Description:
I am unable to install chmod ,tried several ways but failed.Any pointers regarding this matter would be quiet helpfull

![image](https://user-images.githubusercontent.com/56045049/209523039-5a5ab6b3-1a21-4854-aad9-626180ffe361.png)

**Comment by soma2000-lang** [comment]
![image](https://user-images.githubusercontent.com/56045049/209523380-60ba4f5c-baa0-4a99-a6e3-8c5b4d5034b6.png)

**Comment by lolcosmo** [comment]
It is already installed and can run, but you haven't appended any parameters to the chmod command.
