### ISSUE TITLE
Can't remove DEV adware installed on Pop OS

### ISSUE THREAD

**Issue by aindriu80** [pop-os/pop#2737]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

![2022-12-29_16-21](https://user-images.githubusercontent.com/8885837/209981385-0b3d4a02-297f-4db5-b42c-65fe2db787ee.png)

**Issue/Bug Description:**

Can't get rid of annoying **DEV** adware

**Steps to reproduce (if you know):**
Type the word dev and adware comes up.  I never installed it on my machine but can't remove it, 

**Expected behavior:**

No **DEV** Adware

**Other Notes:**

It should be easily removed not baked into the OS

**Comment by n3m0-22** [comment]
There is nothing installed, and it is not adware. This is a shortcut built into the launcher to make it quick to search `https://dev.to`. There are many of these (e.g, ddg "duckduckgo search", gs "google search"). They are in the file `config.ron` located at `/usr/lib/pop-launcher/plugins/web/`. You can remove that one if it is bothering you. You can also add new ones that might be helpful to you, and submit a PR for review if you thing it would be useful to others as well. I think that resolves this issue so I will close it for now, but if you think there is more to address I can always reopen.
