### ISSUE TITLE
The repository does not have a Release file

### ISSUE THREAD

**Issue by Aayushpatil77** [pop-os/pop#2742]
![Screenshot from 2022-12-31 13-13-41](https://user-images.githubusercontent.com/65178660/210129542-db7923d7-82a5-4841-a8cc-93935fcf8472.png)

ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by mmstick** [comment]
Our repository is not hosted on Launchpad
