### ISSUE TITLE
Second monitor lagging after formatting

### ISSUE THREAD

**Issue by gabrielgrs** [pop-os/pop#2747]
**Distribution:**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

When I try to use the secondary monitor as the only one, the OS starts to be very slow
(My notebook has a broken screen, so I use a second monitor)!

I was already using POP OS in version 22.04, however, after a long time it seemed slow and I decided to format it, I downloaded the ISO in the NVIDIA version, as I had done before, I performed the installation and the problem started to happen out of nowhere

**Steps to reproduce:**

- Start OS
- Disable notebook image (closing or disabling notebook screen)
- Using external monitor as default

**Other Notes:**

I already tried to download the distro again and use another pendrive, it didn't work

**Comment by leviport** [comment]
This sounds like a duplicate of https://github.com/pop-os/nvidia-graphics-drivers/issues/61

You may have better behavior by switching to Nvidia graphics mode. If you're tied to an external display, I'm guessing you're probably also normally connected to a charger anyway, so I'm betting this will work well for your use-case.

**Comment by leviport** [comment]
Crashes sound like different behavior than "running very slow". I'd probably advise checking logs around the time of the crash, to start with. Also probably want to see if memory usage is reasonable. When a machine starts swapping to disk after filling RAM, it's usually not a very pleasant experience.

**Comment by gabrielgrs** [comment]
I was using a translator and ended up not checking the translation, it was in fact a lag, not a crash. :)

But ok, I found the solution here https://www.reddit.com/r/pop_os/comments/os2lhb/external_display_lag/, in my case, I needed to open "nvidia-settings" and change the PowerMizer Settings solution to "Prefer Maximum Performance" instead of "Auto"

**Comment by leviport** [comment]
Ah I see. Well I'm glad to hear you found a solution!
