### ISSUE TITLE
Disable fwupd/LVFS phoning home

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/pop#276]
[fwupd phones home](https://blogs.gnome.org/hughsie/2018/01/10/phoning-home-after-updating-firmware/) to LVFS with [a bunch of data](https://fwupd.org/privacy) when running. While we don't use GNOME Software (so I don't believe fwupd/lvfs stuff are automatically running), we should protect user data, especially when they've not opted to give any data to that third party.

According to the post, 
>You can disable the reporting functionality in all applications by editing /etc/fwupd/remotes.d/*.conf

We should do so in Pop!_OS.

**Comment by cunctator00** [comment]
agree

**Comment by jackpot51** [comment]
Let's discuss this in more depth.

**Comment by cunctator00** [comment]
nobody?

**Comment by cassidyjames** [comment]
It looks like you need to modify `/etc/fwupd/remotes.d/lvfs.conf `:

```
sudo nano /etc/fwupd/remotes.d/lvfs.conf 
```

Add a `#` to the `ReportURI` line to comment it out, i.e.:

```
#ReportURI=https://fwupd.org/lvfs/firmware/report
```

**Comment by cunctator00** [comment]
done! many thanks for that

**Comment by brs17** [comment]
This has been resolved when we started packaging our own fwupd for firmware-manager.
