### ISSUE TITLE
Remove daily.dev from Pop!_OS 

### ISSUE THREAD

**Issue by aindriu80** [pop-os/pop#2770]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Using the Pop!_OS  finder

**Issue/Bug Description:**

Daily.dev is built into Pop!_OS  and I can't get it removed.  Everytime I press the super key and type anything like 'dev' the daily.dev suggestion comes up in front of my applications like Firefox Developer Edition and I can't get it removed.  

**Steps to reproduce (if you know):**

1. Press the Super key
2. type anything like dev
3. Notice the daily.dev adware

![lbs0kyq5wgt81](https://user-images.githubusercontent.com/8885837/213264840-d9f76163-2536-4bb1-a9b8-9b1c306f2c62.jpg)

**Expected behavior:**

1. Press the super key
2. type dev
3. Notice software packages installed on the operating system like Firefox Developer Edition on top of the list

**Other Notes:**

I have removed the browser addon but it is still on the OS.  I also reinstalled Pop!_OS  recently just to keep the machine running smoothly and copied my home folder over and once I did that I get the Daily.Dev pop up.  It's really intrusive at this stage, I've done many searches and made a several posts but I can't get rid of this Adware.

**Comment by leviport** [comment]
Why did you open another issue? You already had https://github.com/pop-os/launcher/issues/151 which had a response. Just because an issue gets closed doesn't mean the discussion can't continue in that issue.

**Comment by aindriu80** [comment]
I removed the lines but it keeps coming back.  There is a script installed on my computer somewhere I can't find it.

`**nvim /usr/lib/pop-launcher/plugins/web/config.ron**    `


```

   (
            matches: ["dev"],
             queries: [(name: "DEV Community", query: "dev.to/search?q=")],
        ),

```


This is really annoying,
