### ISSUE TITLE
Restarts after trying to turn on from Suspend mode.

### ISSUE THREAD

**Issue by Addy420** [pop-os/pop#2773]
**Distribution:**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Issue/Bug Description:**
Computer doesnt turn on and work usual after prompted to get on normal run mode to get out of suspend mode.
acts as if it was shut down and restarts.

**Steps to reproduce:**

After suspend button is clicked,
click on power button and wait. (displays Manufacturer logo and restarts)

**Expected behavior:**

Should show normal screen and pre-opened applications as they were before suspending

**Other Notes:**
logs:

> Jan 20 16:04:34 pop-os systemd[1]: Stopped target Bluetooth Support.
Jan 20 16:04:34 pop-os bluetoothd[947]: Battery Provider Manager destroyed
Jan 20 16:04:34 pop-os bluetoothd[947]: Destroy Adv Monitor Manager
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/opus_05_duplex
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/opus_05_duplex
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/opus_05
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/opus_05
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/faststream_duplex
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/faststream
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_0
Jan 20 16:04:34 pop-os kernel: PM: suspend entry (deep)
Jan 20 16:04:34 pop-os systemd-sleep[7069]: Entering sleep state 'suspend'...
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx_ll_duplex_1
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx_ll_0
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx_ll_1
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/sbc_xq
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/sbc_xq
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/sbc
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/sbc
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aac
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/aac
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/aptx
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/aptx_hd
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSink/aptx_hd
Jan 20 16:04:34 pop-os bluetoothd[947]: Endpoint unregistered: sender=:1.141 path=/MediaEndpoint/A2DPSource/ldac
Jan 20 16:04:34 pop-os rfkill[7122]: block set for type bluetooth
Jan 20 16:04:34 pop-os kernel: Bluetooth: hci0: HCI reset during shutdown failed
Jan 20 16:04:34 pop-os systemd[1]: NetworkManager-dispatcher.service: Deactivated successfully.
Jan 20 16:04:26 pop-os kernel: Bluetooth: hci0: command 0x0c03 tx timeout
Jan 20 16:04:24 pop-os kernel: usb 1-8: USB disconnect, device number 3
Jan 20 16:04:24 pop-os gnome-shell[2592]: An active wireless connection, in infrastructure mode, involves no access point?
Jan 20 16:04:24 pop-os wpa_supplicant[976]: nl80211: deinit ifname=wlp1s0 disabled_11b_rates=0
Jan 20 16:04:24 pop-os wpa_supplicant[976]: wlp1s0: CTRL-EVENT-DSCP-POLICY clear_all
Jan 20 16:04:24 pop-os wpa_supplicant[976]: wlp1s0: CTRL-EVENT-DSCP-POLICY clear_all
Jan 20 16:04:24 pop-os systemd[1]: Starting System Suspend...
Jan 20 16:04:24 pop-os systemd[1]: Reached target Sleep.
Jan 20 16:04:24 pop-os wpa_supplicant[976]: nl80211: deinit ifname=p2p-dev-wlp1s0 disabled_11b_rates=0
Jan 20 16:04:24 pop-os wpa_supplicant[976]: p2p-dev-wlp1s0: CTRL-EVENT-DSCP-POLICY clear_all
Jan 20 16:04:24 pop-os wpa_supplicant[976]: p2p-dev-wlp1s0: CTRL-EVENT-DSCP-POLICY clear_all

Please let me know what other logs required, I will quickly make them available.
Thank you!

**Comment by leviport** [comment]
Can you describe the hardware this is happening on?

**Comment by Addy420** [comment]
> Can you describe the hardware this is happening on?

Dell Inc. Latitude E5470
Intel® Core™ i5-6200U CPU @ 2.30GHz × 4 
Mesa Intel® HD Graphics 520 (SKL GT2)
8 gb rab
(4gb swap memory if you are wondering)

**Comment by lhotari** [comment]
Same problem with Dell Precision 5550
Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
00:02.0 VGA compatible controller: Intel Corporation CometLake-H GT2 [UHD Graphics] (rev 05)
Using Kernel Mode Setting driver: i915, version 1.6.0 20201103
32GB RAM
Linux pop-os 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf SMP PREEMPT_DYNAMIC Thu J x86_64 x86_64 x86_64 GNU/Linux

This might be caused after 6.0.12 kernel upgrade.

**Comment by lhotari** [comment]
I'm confident that 6.0.12 kernel was causing the issues for me. I switched to use xanmod kernel in the meantime, until pop-os kernel is stable. ([my notes for installing / removing xanmod kernel](https://gist.github.com/lhotari/f5025d84758f755d42c7e0b455e4913b)) I need a recent kernel (>=6.0.7) [with the fix for the squashfs bug](https://lore.kernel.org/lkml/20221020223616.7571-1-phillip@squashfs.org.uk/).

**Comment by Addy420** [comment]
> I'm confident that 6.0.12 kernel was causing the issues for me. I switched to use xanmod kernel in the meantime, until pop-os kernel is stable. ([my notes for installing / removing xanmod kernel](https://gist.github.com/lhotari/f5025d84758f755d42c7e0b455e4913b)) I need a recent kernel (>=6.0.7) [with the fix for the squashfs bug](https://lore.kernel.org/lkml/20221020223616.7571-1-phillip@squashfs.org.uk/).

**Comment by Addy420** [comment]
@lhotari the problem seems to have gone now all of a sudden, i don't know what was the issue exactly, there wasn't any update.

(my current kernel is 6.0.12-76060006-generic)
By the way 
I think it was some random kernel issue and couldn't get rid of by itself, although one thing to note here is I had shut down my Laptop couple of times and i feel that was one thing i had noticed after which the problem never came back.

Also is the problem recent to you?

**Comment by lhotari** [comment]
> Also is the problem recent to you?

yes, it started after the 6.0.12 kernel update a few weeks ago. I have had zero issues after replacing 6.0.12 kernel with xanmod 6.1.10
