### ISSUE TITLE
firefox user app

### ISSUE THREAD

**Issue by 2leggeg4ox** [pop-os/pop#2776]
**Distribution (run `cat /etc/os-release`):**
 pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

userapp-firefox-OSPY9Y1.desktop

**Issue/Bug Description: The file or folder /home/pro4essor/Desktop/userapp-Firefox-OSP9Y1.desktop does not exist. 

**Steps to reproduce (if you know):**

i removed it from the task bar and placed it on the desktop then  tried deleting it but wouldn't let me do that

**Expected behavior:**

error notification

**Other Notes:**

how can i delete it

**Comment by jacobgkau** [comment]
What is the output of this command?

```
find ~/Desktop/ | grep -i firefox
find ~/.local/share/applications/ | grep -i firefox
```

If the filename shows up within the second command, then you can remove the file from there with `rm`.

If that doesn't solve the issue, can you clarify what steps you took when you added Firefox to the desktop?

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by 2leggeg4ox** [comment]
Thanks much appreciated
