### ISSUE TITLE
Connecting external HDMI monitor causes continuously recurring hiccups

### ISSUE THREAD

**Issue by wout** [pop-os/pop#278]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
hidpi-daemon:
  Installed: 18.04.2\~1525980324\~18.04\~40aed76
  Candidate: 18.04.2\~1525980324\~18.04\~40aed76
  Version table:
 *** 18.04.2\~1525980324\~18.04\~40aed76 776
        776 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        776 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
After installing Pop!_OS 18.04 (clean install; I'm coming from Pop!_OS 17.10) on my Dell XPS 15 9560 I noticed a recurring hiccup in UI rendering on external displays connected through HDMI. Every 3 seconds there is a stall of about 500ms. The hiccups also happens on the built-in display while the HDMI cable is connected. As soon as I unplug the external monitor, the hiccups are gone.

After some tests I noticed the hiccups disappear when I kill the hidpi-daemon. So I'm pretty sure the problem is in there somewhere. Disabling the HiDPI deamon from the settings doesn't do a thing. The process has to be killed manually.

I made a screen cast to illustrate the issue:

![hiccups-external-monitor](https://user-images.githubusercontent.com/107324/39936709-a1748c30-554d-11e8-9383-d504e76adc7a.gif)

**Steps to reproduce (if you know):**
Plug in a HDMI cable while the hidpi-daemon is running.

**Comment by djordan2** [comment]
I wonder if there are any errors being logged for the hidpi daemon while this happens.  Could you look in your system logs to see if anything relevant shows up?

**Comment by wout** [comment]
I can't really see anything specific there. A `tail -f /var/log/syslog` gives me:

```
May 11 22:47:39 slet gnome-shell[2937]: Did not find color property '-arrow-background-color'
May 11 22:47:44 slet gnome-shell[2937]: Ignoring excess values in shadow definition
May 11 22:47:44 slet gnome-shell[2937]: message repeated 3 times: [ Ignoring excess values in shadow definition]
May 11 22:47:46 slet gnome-shell[1580]: Ignoring excess values in shadow definition
May 11 22:47:47 slet kernel: [  826.458226] [UFW BLOCK] IN=wlp2s0 OUT= MAC=01:00:5e:00:00:01:38:43:7d:3e:ef:8b:08:00 SRC=192.168.0.1 DST=224.0.0.1 LEN=36 TOS=0x00 PREC=0xC0 TTL=1 ID=5973 PROTO=2 
May 11 22:47:46 slet gnome-shell[1580]: message repeated 5 times: [ Ignoring excess values in shadow definition]
May 11 22:47:54 slet gnome-shell[2937]: Did not find color property '-arrow-background-color'
May 11 22:47:54 slet gnome-shell[2937]: Ignoring excess values in shadow definition
May 11 22:47:57 slet gnome-shell[2937]: message repeated 11 times: [ Ignoring excess values in shadow definition]
May 11 22:47:59 slet gnome-shell[2937]: Did not find color property '-arrow-background-color'
May 11 22:48:15 slet gnome-shell[2937]: Ignoring excess values in shadow definition
May 11 22:48:15 slet gnome-shell[2937]: Ignoring excess values in shadow definition
May 11 22:48:44 slet gnome-shell[2937]: Did not find color property '-arrow-background-color'
May 11 22:48:53 slet gnome-shell[2937]: message repeated 2 times: [ Did not find color property '-arrow-background-color']
May 11 22:49:08 slet systemd[1]: Starting Cleanup of Temporary Directories...
May 11 22:49:08 slet systemd[1]: Started Cleanup of Temporary Directories.
May 11 22:49:08 slet gnome-shell[2937]: Did not find color property '-arrow-background-color'
```

But nothing is added while the hiccups are happening.
Than I kill the hidpi-daemon:

```
May 11 22:53:02 slet acpid: client 3153[1000:1000] has disconnected
```

**Comment by MakotoTheKnight** [comment]
I'm experiencing this as well; didn't notice anything in particular as to where the hidpi-daemon would be logging.  Could someone point us to a specific file that this would log to?  It'd be inconvenient to disable the hidpi-daemon in every session.

**Comment by wout** [comment]
I was wondering if there is any progress on this issue. In the meantime I reinstalled Pop!_OS 18.04 but the issue remains.

@MakotoTheKnight 
What kind of machine are you using?

**Comment by MakotoTheKnight** [comment]
@wout I'm currently using a Dell Precision 5520 which has an Optimus setup (Intel integrated, NVIDIA dedicated).  I'm running on the NVIDIA chip right now as I thought this was an issue specific to the integrated Intel chip.  Switching between the two doesn't accomplish much (and I'd *really* like to stay off of the Intel chip if I can).

**Comment by wout** [comment]
@MakotoTheKnight So maybe it's an issue with Dell hardware? The XPS 15 and the Precision seem like similar machines.

I also noticed switching between Intel and Nvidia doesn't make a difference.

**Comment by MakotoTheKnight** [comment]
I'm noticing this issue not occur with the latest update to the hidpi-daemon package.  Was it the case that there were some  issues with the daemon "working around" bugs in the NVIDIA 390+ driver?

**Comment by djordan2** [comment]
Yes, the workarounds were removed now that we're shipping NVIDIA 396.  Based on your description of the bug, it 's probable this fixed the issue.  Incidentally, Laptops with hybrid graphics should work considerably better with the new PRIME support.

**Comment by brs17** [comment]
Since it sounds like the issue was fixed with NVIDIA 396, I am going to close this issue. If issues persist feel free to comment and reopen the issue.

**Comment by wout** [comment]
@brs17 I'm sorry for not continuing my report. I haven't had any issues lately so all is well. :)

**Comment by DhruvaG2000** [comment]
I am facing this issue on Pop 20 LTS. Can someone help? I tried hybrid graphics and integrated graphics modes. Issue Occurs on both modes.
I suspected it was hdmi cable issue, so I checked on ubunth DDE that I had on dual boot, but ubuntu DDE works perfectly fine without any flicker or glitch.
