### ISSUE TITLE
pop-zram-config not loading during boot

### ISSUE THREAD

**Issue by imlinstress** [pop-os/pop#2783]
I tried to extend the swap memory from default 16GB to something higher using pop-zram-config file on the usr/bin Folder.

Although i just altered the memory size and leaving everything else untouched, the zram has just disappeared. Even after rebooting the system i just can't get it activated again.

Is there a way to go back to the default setting again?

running latest version pop-os!

Thanks!

**Comment by mmstick** [comment]
```
sudo apt install --reinstall pop-default-settings-zram
```

**Comment by imlinstress** [comment]
Thanks a lot mmstick for your quick reply!

After running the command i've got:
Unpacking pop-default-settings-zram (5.1.0~1674146824~22.04~999ad2c) over (5.1.0
~1674146824~22.04~999ad2c) ...
but unfortunately nothing happened.
Running following commands results in:
uname -r returns: 6.0.12-76060006-generic
zramctl --find  returns: /dev/zram0
and
swapon /dev/zram0 returns:  swapon: /dev/zram0: read swap header failed

**Comment by imlinstress** [comment]
Using the Refresh OS option from the settings did resolve the issue.
Not quite the elegant solution that one would hope for.
