### ISSUE TITLE
Overheating issue on MacBook Pro (Ubuntu 20.04 dual booted)

### ISSUE THREAD

**Issue by xhesi2003lutaj** [pop-os/pop#2786]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by leviport** [comment]
The Pop!\_OS github isn't the appropriate place to report Ubuntu bugs. Also, overheating is usually a symptom of something wrong with the hardware. I usually recommend cleaning all dust from the fan and heatsink, making sure the fan still works correctly, and refreshing the thermal paste on the CPU.
