### ISSUE TITLE
No Detection of Display via USB-C

### ISSUE THREAD

**Issue by stratigos** [pop-os/pop#279]
**Distribution (run `cat /etc/os-release`):** POP OS 18.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Displays

**Issue/Bug Description:**

When I plug any monitor in through a USB-C port, my laptop (Kudu) has no response. It cant detect the 2nd display / external monitor. There is no "detect displays" option in settings (should there be?). I have tried with two different brand monitors, and both work with other machines using the same USB-C cable. Basically, nothing happens.

Am I able to use a 2nd monitor through the USB-C port?

**Steps to reproduce (if you know):**

Plug 2nd monitor in via USB-C port. Nothing happens at all.

**Expected behavior:**

Plug 2nd monitor in via USB-C port. 2nd monitor displays, and system settings allow for configuration of screens/spaces.

**Other Notes:**

**Comment by brs17** [comment]
@stratigos The Kudu does not support displays through USB-C so what you are seeing is expected behavior.
