### ISSUE TITLE
Unable to make combined audio sink in Pipewire anymore

### ISSUE THREAD

**Issue by ChiefGyk3D** [pop-os/pop#2790]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
pipewire:
  Installed: 0.3.65~1675088007~22.04~5fd5a3a
  Candidate: 0.3.65~1675088007~22.04~5fd5a3a
  Version table:
 *** 0.3.65~1675088007~22.04~5fd5a3a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
pipewire-audio-client-libraries:
  Installed: 0.3.65~1675088007~22.04~5fd5a3a
  Candidate: 0.3.65~1675088007~22.04~5fd5a3a
  Version table:
 *** 0.3.65~1675088007~22.04~5fd5a3a 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages

**Issue/Bug Description:**
Unable to create combined sink all of a sudden been using this method for months since moving to 22.04. It's breaking my ability to properly stream my gaming to Twitch with a two pc setup as I have the audio piped to my mixer and an HDMI capture card on the second machine.

```
pactl load-module module-combine-sink
Failure: No such entity

```

**Steps to reproduce (if you know):**
pactl load-module module-combine-sink

**Expected behavior:**
Generates a combined sink with output audio devices available and is able to be selected in settings 

**Other Notes:**

**Comment by ChiefGyk3D** [comment]
It looks as if the module isn't even installed 

```
chiefgyk3d@Project-NOS:~$ pactl list short
1	libpipewire-module-rt	{
            nice.level    = -11
            #rt.prio      = 88
            #rt.time.soft = -1
            #rt.time.hard = -1
        }	
2	libpipewire-module-protocol-native		
3	libpipewire-module-profiler		
5	libpipewire-module-metadata		
7	libpipewire-module-spa-device-factory		
9	libpipewire-module-spa-node-factory		
11	libpipewire-module-client-node		
13	libpipewire-module-client-device		
15	libpipewire-module-portal		
16	libpipewire-module-access	{
            # access.allowed to list an array of paths of allowed
            # apps.
            #access.allowed = [
            #    /usr/bin/pipewire-media-session
            #]

            # An array of rejected paths.
            #access.rejected = [ ]

            # An array of paths with restricted access.
            #access.restricted = [ ]

            # Anything not in the above lists gets assigned the
            # access.force permission.
            #access.force = flatpak
        }	
17	libpipewire-module-adapter		
19	libpipewire-module-link-factory		
21	libpipewire-module-session-manager		
28	libpipewire-module-x11-bell	{
            #sink.name = ""
            #sample.name = "bell-window-system"
            #x11.display = null
            #x11.xauthority = null
        }	
536870912	module-always-sink		
50	alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2	PipeWire	s32le 2ch 48000Hz	SUSPENDED
51	alsa_output.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo	PipeWire	s24le 2ch 48000Hz	SUSPENDED
53	alsa_output.pci-0000_0c_00.4.iec958-stereo	PipeWire	s32le 2ch 48000Hz	SUSPENDED
50	alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2.monitor	PipeWire	s32le 2ch 48000Hz	SUSPENDED
51	alsa_output.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo.monitor	PipeWire	s24le 2ch 48000Hz	SUSPENDED
52	alsa_input.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo	PipeWire	s24le 2ch 48000Hz	SUSPENDED
53	alsa_output.pci-0000_0c_00.4.iec958-stereo.monitor	PipeWire	s32le 2ch 48000Hz	SUSPENDED
54	alsa_input.pci-0000_0c_00.4.analog-stereo	PipeWire	s32le 2ch 48000Hz	SUSPENDED
32	PipeWire	xdg-desktop-portal
33	PipeWire	pipewire
34	PipeWire	firefox-bin
36	PipeWire	wireplumber
37	PipeWire	wireplumber
73	PipeWire	gnome-shell
74	PipeWire	gsd-media-keys
124	PipeWire	gnome-shell
172	PipeWire	pactl
0	bell-window-system	s16le 2ch 44100Hz	1.000
43	alsa_card.pci-0000_0a_00.1	alsa
44	alsa_card.usb-R__DE_R__DECaster_Pro_II_GV0039166-00	alsa
45	alsa_card.pci-0000_0c_00.4	alsa
```

**Comment by ChiefGyk3D** [comment]
So apparently the module was changed with 0.3.65 but it's still not here apparently 

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.65
https://www.phoronix.com/news/PipeWire-0.3.65-Released

```
chiefgyk3d@Project-NOS:~$ pactl load-module module-combine-stream
Failure: No such entity
```

**Comment by ChiefGyk3D** [comment]
Looks as if there is an actual commit that this issue is known on Pipewire and it wasn't included on build apparently https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/fba7083f8ceb210c7c20aceafeb5c9a8767cf705

**Comment by ChiefGyk3D** [comment]
Resolved

**Comment by jacobgkau** [comment]
Fixed by https://github.com/pop-os/pipewire/pull/42.
