### ISSUE TITLE
Graphics switch does not work in kernel 6.0.12.

### ISSUE THREAD

**Issue by Diafwl** [pop-os/pop#2794]
**Distribution (run `cat /etc/os-release`):**
```
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os 
 
```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
system76-power:
  Installed: 1.1.24~1674505745~22.04~c504ff6
  Candidate: 1.1.24~1674505745~22.04~c504ff6
  Version table:
 *** 1.1.24~1674505745~22.04~c504ff6 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

in kernel '6.0.12-76060006-generic' gpu switching does not work(other than integrated graphics does not work), also some additional drivers also does not work properly 
(openrazer, tuxedo-io)

**Steps to reproduce (if you know):**
boot with 6.0.12-76060006-generic and try to switch gpu mode it states Requires restart but nothing happens after restart

**Expected behavior:**
Switch between gpu modes; nvidia, hybrid or compute

**Other Notes:**
using kernel 6.0.6-76060006-generic works perfectly.
Nvidia Driver Version: 525.85.05

**Comment by leviport** [comment]
I've seen this happen from time to time. You might just need to purge and reinstall Nvidia drivers to get it working again:
```
sudo apt purge ~nnvidia

**Comment by Diafwl** [comment]
unfortunately, that's does not work.
also i'm getting few errors like this in kernel 6.0.12
`[    6.410510] BPF: [124890] TYPEDEF a..percpu 
[    6.410515] BPF: type_id=3
[    6.410515] BPF:  
[    6.410516] BPF: Invalid name
[    6.410517] BPF: 
[    6.410519] failed to validate module [nvidia] BTF: -22
`

**Comment by leviport** [comment]
Did you reboot afterwards?

**Comment by Diafwl** [comment]
yeah i rebooted. 
after uninstalling nvidia driver i rebooted with integrated graphics and install nvidia driver after that i did tried to switch  nvidia or hybrid but does not work

**Comment by T100D** [comment]
What card are you using, recent or older. Mine is not supported so I and some others rely on nvidia 470-server icm kernel 6.x.

**Comment by Diafwl** [comment]
my dGPU is  GA106M [GeForce RTX 3060 Mobile / Max-Q]

**Comment by T100D** [comment]
Card should be supported, possibly a kernel/driver combination issue if the device is visible with lspci.

**Comment by Diafwl** [comment]
yeah as i can see nvidia 525, openrazer and tuxedo-io drivers does not work with 6.0.12

**Comment by Diafwl** [comment]
fixed after new clean installation of pop!_os
