### ISSUE TITLE
The repository 

### ISSUE THREAD

**Issue by 2leggeg4ox** [pop-os/pop#2801]
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Package files:

 100 /var/lib/dpkg/status
     release a=now
Pinned packages:

**Issue/Bug Description:**

The repository 'https://ppa.launchpadcontent.net/nilarimogard/webupd8/ubuntu jammy Release' does not have a Release file.

**Steps to reproduce (if you know):**
sudo apt update

**Expected behavior:**

i can't sudo update

**Other Notes:**

N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by leviport** [comment]
It's just as it says; that PPA doesn't have a release file. When you follow that link, you can see there is no "Jammy" in the "Dists" folder. 

The PPA needs to be disabled or removed. This can be done from Repoman. To open Repoman, open Pop Shop, then click "System software sources..." in the top right hamburger menu. Then go to the "Extra sources" tab, find the nilarimogard/webupd8 source, and turn it off in the Edit dialog (pencil button).

**Comment by 2leggeg4ox** [comment]
yes sure i did that but then again my Pc can connect to my Bose speaker and not the beats pro which I am guessing is due to removing the those particular PPA. thanks for the Repoman, i used software and updates from the system tray. cheers for helping

**Comment by leviport** [comment]
I thought webupd8 was for some kind of Java thing? Regardless, that PPA is very unlikely to have anything to do with bluetooth troubles.
