### ISSUE TITLE
Appearance -> Dark, do not change the color.

### ISSUE THREAD

**Issue by diegoalarc** [pop-os/pop#2807]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
It is not possible to completely change the color of the appearance of the operating system.

**Steps to reproduce (if you know):**
![Screenshot from 2023-02-23 18-54-48](https://user-images.githubusercontent.com/57131432/220989995-15b60cbb-a1b6-40ab-aa21-5ed019d1e975.png)

**Expected behavior:**
Put the appearance in black.

**Comment by leviport** [comment]
That looks like the Adwaita theme. Try installing gnome-tweaks and setting the "Appearance" settings back to these defaults:

![2023-02-23_11-15-12](https://user-images.githubusercontent.com/13512097/220995138-3bbd6403-83dd-4cf8-b5a2-36366a731b51.png)

**Comment by diegoalarc** [comment]
> That looks like the Adwaita theme. Try installing gnome-tweaks and setting the "Appearance" settings back to these defaults
I have done as requested and still this persists. Other ideas?

**Comment by leviport** [comment]
Did you restart the session? Either reboot the machine or restart Gnome with Alt+F2, type the letter `r`, and hit enter.

**Comment by diegoalarc** [comment]
> Did you restart the session? Either reboot the machine or restart Gnome with Alt+F2, type the letter r, and hit enter.

Yes, and it didn't work

**Comment by leviport** [comment]
Well it's definitely a theme problem. The theme selector doesn't work if you have Adwaita enabled.

**Comment by diegoalarc** [comment]
![Screenshot from 2023-02-23 20-26-33](https://user-images.githubusercontent.com/57131432/221010167-065b17a7-80de-4699-9135-a26fa9f270aa.png)

**Comment by jacobgkau** [comment]
The screenshot shows that the system is still using the Adwaita theme even though the theme is set to Pop. Whatever has the system stuck on Adwaita could be related to why it's stuck on the light theme as well.

Can you provide the output of `apt policy gnome-tweaks`? Do you have any GNOME Shell extensions installed? Does the issue still occur if you create a new user account in Settings -> Users for testing purposes, then log in as that user?

**Comment by diegoalarc** [comment]
`gnome-tweaks:
  Installed: 42~beta-1ubuntu2
  Candidate: 42~beta-1ubuntu2
  Version table:
 *** 42~beta-1ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe i386 Packages
        100 /var/lib/dpkg/status
     42~beta-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages
`

Yes, this still occur.

**Comment by diegoalarc** [comment]
At the end [this](https://www.reddit.com/r/pop_os/comments/swzagv/dark_theme_doesnt_work_in_some_areas_and_i_dont/) helped me.

`dconf reset -f /org/gnome/`

And then I did all the config again.

**Comment by leviport** [comment]
Glad to hear you found a fix! I'll close this issue since I think this was a one-off configuration problem, rather than a widespread bug. We can reopen it later if more users run into the same thing.
