### ISSUE TITLE
System hangs/screen goes dark and freezes when HP G5 USB-C dock is plugged in starting with kernel 6.*

### ISSUE THREAD

**Issue by Mouseskowitz** [pop-os/pop#2821]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
System/ video driver? kernel 6.*
dpkg -l xserver-xorg-video-amdgpu
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                      Version                                        Architecture Description
+++-=========================-==============================================-============-=======================================
ii  xserver-xorg-video-amdgpu 22.0.0-1ubuntu0.1pop1~1677198820~22.04~2e82f80 amd64        X.Org X server -- AMDGPU display driver

**Issue/Bug Description:**
When I plug my laptop in the HP G5 USB-C dock the laptop screen goes dark with only the outline of the mouse showing. The laptop screen is duplicated on one of the two attached monitors. If plugged in at boot, this happens after decrypting the drive. A hard reboot of the system is required to recover.

**Steps to reproduce (if you know):**
Plug in dock after boot or try to boot with it plugged in. 

**Expected behavior:**
Have the desktop extended across the monitors attached to the dock.

**Other Notes:**
This dock was working without issue prior to the upgrade to kernel 6.*. If logs or troubleshooting is needed, please let me know.

**Comment by leviport** [comment]
I think this might be the same as https://github.com/pop-os/linux/issues/226, so I'm going to close it as a duplicate. We can reopen if I'm mistaken, but it will be easier to track the bug in one place, if it is the same bug.
