### ISSUE TITLE
where did you install sddm files ? [close]

### ISSUE THREAD

**Issue by jerome-diver** [pop-os/pop#2830]
last pop_os update.
Did installed sddm from your repositories.

# But where did you choosed to put sddm sources files ? 

If you absolutely do not want to follow the manual page of sddm, please do update it the way your users can find them to config sddm.

So the man page of sddm installed from repo there indicate fake positions of sddm files (that is not there):

- no /etc/sddm.conf file present
- no /etc/sddm.conf.d directory present
- no /usr/lib/sddm directory present

Why are you practicing like this ? What is the idea ?

**Comment by leviport** [comment]
I'd like to note that `sddm` is an Ubuntu package from the Ubuntu repos, and not one that we maintain. However, I'm not very familiar with `sddm`, and I don't know where the config files are.

**Comment by jerome-diver** [comment]
ok, i did a sddm --example-config to get the config default file content and copy it in /etc/sddm.conf (where it should be).
My original problem was to get xmonad WM present in the session list (i ran with gdm3), but failed to egt it present in GDM3, so i did install SDDM (who is a bit slim also) to get something around xmonad from the /usr/share/xsession/xmonad.desktop i wrote to get it in the list. But nothing appears too.
Well... if you feel comfortable with xmonad, tell me, i think i should close or delete this post later beause it is unrelevant with Pop_OS if it is not package maintained from them.
Strange that the installation missed the ubuntu sddm man page request for files to be present at some places (because the man page of sddm: online is on ubuntu web site...).

**Comment by jacobgkau** [comment]
I'm closing this issue since you put `[close]` at the end of the title (which doesn't do anything), let me know if that wasn't your intention.
