### ISSUE TITLE
Unable to drag and drop files to share in slack

### ISSUE THREAD

**Issue by Abhishek-Stupa** [pop-os/pop#2832]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
slack:
  Installed: (none)
  Candidate: 1:0.15.2-9.1
  Version table:
     1:0.15.2-9.1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages

**Issue/Bug Description:**
Unable to share files using drag and drop when using slack in popOS
![image](https://user-images.githubusercontent.com/103176790/225200197-c3c9edc7-c130-45b5-8857-4db942c60c90.png)

**Steps to reproduce (if you know):**
Dragging and dropping any file type gives the above warning, however files can be uploaded when using the upload file dialog box inside slack.

**Expected behavior:**
Files should be uploaded in slack when dragging and dropping

**Other Notes:**

**Comment by leviport** [comment]
Sounds like you're using the Flatpak version of Slack. You need to use an application called Flatseal to grant Slack extra permissions in order for drag and drop to work. I believe the one you need is "All user files" under Filesystem.

**Comment by jaimeburnap** [comment]
> Sounds like you're using the Flatpak version of Slack. You need to use an application called Flatseal to grant Slack extra permissions in order for drag and drop to work. I believe the one you need is "All user files" under Filesystem.

This worked for me
