### ISSUE TITLE
Pop OS freezes when transfering big files

### ISSUE THREAD

**Issue by Parrawk** [pop-os/pop#2835]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
This started happening after installing a new nvme ssd on my system, nvme passes the tests I ran on it and SMART doesnt show any errors.
OS freezes when putting load on the nvme ssd(Crucial P3, Dramless), for example when tranfering big files (more than 10GB), on nautilus or terminal, it starts transfering for a couple of minutes and then I start losing control over the system, first it freezes nautilus, then the mouse stops responding and everything freezes but audio keeps playing, and I cant access the tty terminal with Ctrl + Alt + F5 either. 
I discovered by accident that it doesn't happen when I load into Pop while having secure boot on and NVIDIA drivers couldn't load (I think so because only one monitor works, and nvidia x server doesn't show config settings), but if I put the same load on the nvme ssd it completes the transfer normally.
It also happens that sometimes the system doesn't finish loading correctly after putting my encription password, it gets stuck after loading some services or displaying something about wifi or displaying something about /data-root/ clean.
I already did a fresh install on the nvme ssd itself and it keeps happening, and my previous installation on a sata ssd behaves the same.
I also tried tinkering with the nvme ssd efi settings like `nvme_core.default_ps_max_latency_us=0` and `pcie_aspm=off` and also settings like vm.dirty_bytes, dirty_background_bytes and other related options but nothing worked.

**Steps to reproduce (if you know):**
Initiate a big file transfer on the nvme ssd.

**Expected behavior:**
NVMe SSD completes file transfers 

**Other Notes:**
Using the latest nvidia driver 525.89.02

My specs:
Ryzen 9 5950X
GTX 1650 SUPER
MSI Tomahawk X570
Crucial MX500 1TB
Crucial P3 2TB

**Comment by deathxxx123** [comment]
Maybe you want to add full info about you'r system from there:
https://linux-hardware.org/?view=howto
I have SSD and 2x SSM and don't have this problems with multiple 3-4GB files transfer.
Do i need test with one big file?

**Comment by Parrawk** [comment]
This issue is gone after uninstalling anbox kernel modules, and the boot and shutdown issues are gone too, I don't know why, but I haven't had any issues for a day and doing big file transfers don't freeze my system anymore.
