### ISSUE TITLE
Buttons in the top right corners

### ISSUE THREAD

**Issue by 4r7hu3** [pop-os/pop#2840]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
In some apps, the system makes unavaliable to close/minimize the windows by clicking on the top right buttons because they simply don't exist. I already enabled 'Minimize & Maximize' buttons on Gnome-Tweaks, but the problem persists in several programs. To exit them, I have to SUPER + Q. Some of them in which this occurs: RStudio, Bitwarden, Transmission, Spotify, and also with some browser extensions, like Pushbullet.

**Steps to reproduce (if you know):**
Open one of those programs and try to minimize/maximize/close the window by clicking on the top right buttons.

**Expected behavior:**
To close/maximize/minimize windows.

**Other Notes:**

![Captura de tela de 2023-03-21 20-21-17](https://user-images.githubusercontent.com/83557508/226763627-c056e27f-3a22-4ab2-97e7-faa6c10741ad.png)
![Captura de tela de 2023-03-21 20-22-04](https://user-images.githubusercontent.com/83557508/226763638-f1370308-b827-438c-8d7a-1c74af19d680.png)

**Comment by leviport** [comment]
It looks like "Show Window Titles" is turned off in pop-shell settings:
![Screenshot from 2023-03-21 17-29-09](https://user-images.githubusercontent.com/13512097/226764599-fa889605-0b10-4d4a-9372-624a73a1cf07.png)

**Comment by 4r7hu3** [comment]
Thanks, it solved my problem! I was confused about this resource, thinking that it was linked with "Tile Windows" :')
