### ISSUE TITLE
Slack menu is weird

### ISSUE THREAD

**Issue by sarahpandabeara** [pop-os/pop#285]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Package files:
 100 /var/lib/dpkg/status
     release a=now
 776 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main i386 Packages
     release v=18.04,o=LP-PPA-system76-pop,a=bionic,n=bionic,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
 776 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
     release v=18.04,o=LP-PPA-system76-pop,a=bionic,n=bionic,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/system76-dev/stable/ubuntu bionic/main i386 Packages
     release v=18.04,o=LP-PPA-system76-dev-stable,a=bionic,n=bionic,l=System76 Stable PPA,c=main,b=i386
     origin ppa.launchpad.net
 500 http://ppa.launchpad.net/system76-dev/stable/ubuntu bionic/main amd64 Packages
     release v=18.04,o=LP-PPA-system76-dev-stable,a=bionic,n=bionic,l=System76 Stable PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 https://packagecloud.io/slacktechnologies/slack/debian jessie/main i386 Packages
     release v=1,o=packagecloud.io/slacktechnologies/slack,a=jessie,n=jessie,l=slack,c=main,b=i386
     origin packagecloud.io
 500 https://packagecloud.io/slacktechnologies/slack/debian jessie/main amd64 Packages
     release v=1,o=packagecloud.io/slacktechnologies/slack,a=jessie,n=jessie,l=slack,c=main,b=amd64
     origin packagecloud.io
 500 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages
     release v=1.0,o=Google, Inc.,a=stable,n=stable,l=Google,c=main,b=amd64
     origin dl.google.com
 500 http://security.ubuntu.com/ubuntu bionic-security/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=universe,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=main,b=i386
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-security,n=bionic,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic-updates,n=bionic,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/multiverse i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/universe i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/restricted i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/main i386 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
     release v=18.04,o=Ubuntu,a=bionic,n=bionic,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
Pinned packages:

**Issue/Bug Description:**
Theming? Slack used to have the menu bar hidden or it matched the rest of the top bar color/theme. Now it is all a different color than the top bar but it also is not matching the color of the text space... It looks ugly and should be fixed (maybe upstream)

**Steps to reproduce (if you know):**
Download Slack from Pop_Shop

**Expected behavior:**
Menu bar hides/blends in with the rest of the space

**Other Notes:**
This super low priority but has been bothering me. I thought it was just the flatpak version but it appears to be an issue with the packaged version for Pop!_OS 18.04 as well.

**Comment by mmstick** [comment]
Seems to be working now.

![screenshot from 2018-06-06 10-46-12](https://user-images.githubusercontent.com/4143535/41052731-dc69c64c-6976-11e8-97c7-38ba406d0d61.png)
