### ISSUE TITLE
Batter indicator in the top bar lags behind

### ISSUE THREAD

**Issue by aliasgar55** [pop-os/pop#2853]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
NO

**Issue/Bug Description:**
Battery indicator in the  status bar at the top takes a long to update after getting plugged in/out
The Icon dosen't reflect the current status charging status immediately

**Steps to reproduce (if you know):**

**Expected behavior:**
It should update as soon as the charger is plugged in

**Other Notes:**
I have battery percentage turned on

**Comment by ydhnwb** [comment]
It's been long time since 20.04 i think when i use pop. Took ~2 minutes to update from charging to uncharged
