### ISSUE TITLE
Desktop Contents Visible When Waking From Suspend

### ISSUE THREAD

**Issue by TwisX** [pop-os/pop#2854]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 22.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** Lock screen and suspend functionality

**Issue/Bug Description:** Sometimes after opening the lid and waking from suspend on my Dell Latitude 5430, the desktop and its contents are visible for about 5 seconds before the lock screen appears. During that time, I can move the mouse and try to click on things. For example, dock icons will be highlighted, but clicking on them doesn't do anything.

If I close the lid to where I can barely see the screen, I'm sometimes able to observe that the lock screen never engages and the system goes straight to suspend.

**Steps to reproduce (if you know):** Suspend and resume the computer. Doesn't happen every time, but maybe 20% - 50% of the time.

**Expected behavior:** On resume, only the lock screen should be displayed. It's a privacy and potential security risk for the desktop to be visible when the system is supposed to be locked.

**Other Notes:** I've tried adding a script to `/lib/systemd/system-sleep/` that runs `sleep 5`, `xdg-screensaver lock`, and `loginctl lock-sessions` with no success. I acknowledge that this is a duplicate of #134 and #1899, but it looks like those were closed without addressing the issue.

Issue #134 suggests that the HiDPI Daemon could be the cause, but I uninstalled that package and this issue still occurs.

I do see this line in journalctl upon resume, but everything else looks normal:
_/usr/lib/systemd/system-sleep/pop-default-settings_bluetooth-suspend failed with exit status 1._

If there are additional logs I could provide, I would be glad to do so.

**Comment by leviport** [comment]
>I acknowledge that this is a duplicate of https://github.com/pop-os/pop/issues/134 and https://github.com/pop-os/pop/issues/1899, but it looks like those were closed without addressing the issue.

#134 was not closed. Discussing issues in duplicate issue reports is counter-productive, which is why I try to close duplicates quickly. If different pieces of information are scattered across a handful of duplicate issues, it makes it much harder to piece together clues and get to an answer. 

I do agree about the HiDPI Daemon though. I've removed it on systems when I've seen the bug, and it also did not help. But let's take this to #134 so everyone following that report can participate.

Duplicate of #134
