### ISSUE TITLE
Chrome install does not appear in Pop Shop

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/pop#286]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Chrome Version 66.0.3359.181 (Official Build) (64-bit)
Via the download link on Goggle's site.

**Issue/Bug Description:**
When installed Chrome does not appear in the Pop Shop app.  Other apps installed outside of Pop Shop (via apt) do appear and can be managed or uninstalled using Pop Shop.

**Steps to reproduce (if you know):**
Go to https://www.google.ca/chrome/?
Click Download Chrome
Accept defaults (installs with Eddy)
When the install is complete open Pop Shop.
Chrome is not included as an installed application.

**Expected behavior:**
Chrome will be listed in Pop Shop

**Other Notes:**
Note: I was able to uninstall Chrome using:
sudo apt-get purge google-chrome-stable

**Comment by brs17** [comment]
This seems to be an issue with Chrome not having the proper appstream data. You'll need to get Chrome to include the right information. I know Chromium is in the Pop!_Shop and should appear as expected.
