### ISSUE TITLE
builtin speakers are not recognized after a recent pipewire update (11th gen tiger lake laptop)

### ISSUE THREAD

**Issue by klzsh** [pop-os/pop#2868]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

libpipewire-0.3-0:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

pipewire:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

pipewire-alsa:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status

pipewire-bin:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

pipewire-pulse:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages

pipewire:i386:
  Installed: 0.3.68~1681427438~22.04~29c62b5
  Candidate: 0.3.68~1681427438~22.04~29c62b5
  Version table:
 *** 0.3.68~1681427438~22.04~29c62b5 1001
       1001 http://apt.pop-os.org/release jammy/main i386 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main i386 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main i386 Packages

**Issue/Bug Description:**

After the recent pipewire/pipewire lib updates, I noticed that my inbuilt speakers were not playing any sound, and the device did not show up in audio devices 

**Steps to reproduce (if you know):**

update to the most recent version of pipewire on a 11th gen tiger lake processor

**Expected behavior:**
Builtin speakers should be recognized and play sound 

**Other Notes:**
NVIDIA sound card is detected, as well as the outputs for my external monitors, which are driven by the same card that drives my builtin speakers (Tiger Lake-H Audio Controller). 

The following dmesg snippets might help:

```

[   12.452087] input: sof-hda-dsp Mic as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card1/input38
[   12.452696] input: sof-hda-dsp Headphone as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card1/input39
[   12.453464] input: sof-hda-dsp HDMI/DP,pcm=3 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card1/input40
[   12.453808] input: sof-hda-dsp HDMI/DP,pcm=4 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card1/input41
[   12.453978] input: sof-hda-dsp HDMI/DP,pcm=5 as /devices/pci0000:00/0000:00:1f.3/skl_hda_dsp_generic/sound/card1/input42


[   15.310932] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[   15.310939] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[   15.310942]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[   15.310945]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[   15.310947]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
[   15.311003] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[   15.311006] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[   15.311008]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[   15.311010]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[   15.311012]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
[   15.357345] Bluetooth: RFCOMM TTY layer initialized
[   15.357353] Bluetooth: RFCOMM socket layer initialized
[   15.357355] Bluetooth: RFCOMM ver 1.11
[   16.975713] rfkill: input handler disabled
[   20.460298] logitech-hidpp-device 0003:046D:406D.000A: HID++ 4.5 device connected.
[   28.988192] rfkill: input handler enabled
[   29.415945] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[   29.415949] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[   29.415951]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[   29.415953]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[   29.415954]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
[   29.415982] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[   29.415984] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[   29.415985]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[   29.415985]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[   29.415986]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
```
The following messages are after waking from suspend
```
[ 3009.627762] PM: suspend exit
[ 3010.491394] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[ 3010.491398] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[ 3010.491400]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[ 3010.491401]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[ 3010.491402]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
[ 3010.491437] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[ 3010.491438] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[ 3010.491440]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[ 3010.491441]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[ 3010.491442]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22


[17079.406349] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[17079.406353] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[17079.406356]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[17079.406358]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[17079.406359]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22
[17079.406394] snd_hda_codec_realtek ehdaudio0D0: didn't find PCM for DAI Digital Codec DAI
[17079.406396] snd_hda_codec_realtek ehdaudio0D0: ASoC: error at snd_soc_dai_startup on Digital Codec DAI: -22
[17079.406397]  Digital Playback and Capture: ASoC: error at __soc_pcm_open on Digital Playback and Capture: -22
[17079.406398]  HDA Digital: ASoC: error at dpcm_be_dai_startup on HDA Digital: -22
[17079.406399]  HDA Digital: ASoC: error at dpcm_fe_dai_startup on HDA Digital: -22

```

**Comment by runboy93** [comment]
Have you tried with new Pipewire 0.3.69?

**Comment by PedroMTSilva** [comment]
Still nothing. Updated the system again, including Pop Shop updates. Also re-did the System76 audio troubleshooting steps in the website. Still nothing.

`alsa-info` still outputs the same information:

`cat: '/sys/module/snd_soc_skl_hda_dsp/parameters/*': No such file or directory
/usr/sbin/alsa-info: line 661: tree: command not found
/usr/sbin/alsa-info: line 661: tree: command not found
dmesg: read kernel buffer failed: Operation not permitted`
