### ISSUE TITLE
PopShop installs Flatpaks which lose user's saved files without warning.

### ISSUE THREAD

**Issue by jasonrohrer** [pop-os/pop#2877]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
 

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Flatpak: 
The Gnumeric Spreadsheet    org.gnumeric.Gnumeric    1.12.55     stable      user

**Issue/Bug Description:**

My wife has PopOS on her laptop.  She needed a spreasheet, so we searched for Gnumeric in the PopShop.  For whatever reason, the FlatPak version came up first, and I installed that without giving it much thought.

Then I set about helping her create a spreadsheet for her project, writing a bunch of macros, and having her enter some of the data.  We saved it, quit Gnumeric, and then I was going to show her how to find the file tomorrow to work on it again.  And the file was gone.  WTF?

So I thought I made a mistake... maybe I hit Cancel instead of Save?

So then I re-created the spreadsheet AGAIN, and this time, I made sure it was saved.  I closed it in Gnumeric and re-opened it.  YES, it worked this time!

But then today, we went to look for it in Gnumeric, and it's gone again.

Worse, it was apparently not saved anywhere.  Not in some temp directory.

So we have lost our work TWICE at this point.  Of course, I'm going to uninstall the FlatPak version now, and install the regular apt install one.

But for a program like Gnumeric, or Gimp, or Libre Office....  FlatPak seems totally useless, at least in the default configuration.  Who would ever want to use these programs and NOT save their work?

Since the normal way of using an Office program is to save your work.... any FlatPak version of such programs should warn the user repeatedly that files aren't really saved.  That this is a temporary session, etc.

I understand how FlatPak could be useful for a web browser or something else that doesn't save files.

But for software that usually saves files---and in the case of FlatPak, appears to save files but lies about it---the situation is ridiculous.

Looking at her system now, I see a bunch of things that were installed by PopShop as flatpaks.  GIMP is another example.  She used that to edit pictures last month, and guess what?  All that work is lost too!  She didn't even realize this was possible, and had no idea the files were lost until I just checked.

Since PopOS is supposed to be user-friendly for non-technical users (like my wife), the Flatpaks should be REMOVED from PopShop, if there's another option available.

This is a terrible trap for a new user---these applications appear to save your work, but don't actually save it, and there's no warning of any kind, not even on the PopShop listing for the app ("WARNING--THIS IS A FLATPAK---YOUR WORK WILL NOT BE SAVED IF YOU USE THIS")

This was a terrible trap for ME, an engineer with 25+ years of experience as a systems programmer and a linux user.  I lost my work twice with no warning.

And my wife now feels like she can't trust her PopOS Laptop, and wants to get rid of it...

**Steps to reproduce (if you know):**

Install Gnumeric with PopShop (flatpak version)

Open it and create a spreasheet.  Save it in the Documents folder.

Inside Gnumeric, go to Open, and verify that the file was saved correctly.

Quit Gnumeric.

Open Gnumeric again and try to find the file that you saved before.  It's gone.

**Expected behavior:**

Saved files should really be saved and available next time you run the app.

OR

A very obvious warning should be displayed whenever you run a flatpak app.

**Comment by mmstick** [comment]
You should make the issue here where the maintainers for the gnumeric flatpak are packaging this: https://github.com/flathub/org.gnumeric.Gnumeric
