### ISSUE TITLE
Pop! OS New user prompt is launched on startup or reboot

### ISSUE THREAD

**Issue by hungry-bogart** [pop-os/pop#2878]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Operating system issue.

**Issue/Bug Description:**
Every time I log out or reboot the system loads into installation mode even though I have no physical media for Pop! OS plugged into my device. I have to go through the prompts and create a new user and then delete the user after I login to my primary account.

**Steps to reproduce (if you know):**
The steps to reproduce if this bug is experienced by others is to log out and see if the new user prompts appear. Additionally, if you attempt a reboot and are faced with all of the new user menus, you have successfully reproduced this bug.

I will update my  system again, since I noticed there is an update. If it solves the problem, I will report back here.

**Expected behavior:**

Expected behavior is to have the system login prompt me to sign in as my regular user instead of asking me to create a new one each time I reboot or logout.

**Other Notes:**

I thought this was just a one time issue, maybe something that just happens sometimes, but it persisted and so now I'm sharing this issue with you. I don't have a fix for it unfortunately.

Updating did not resolve the issue.

I would like to add that this could be a security concern. I use full disk encryption, so that protects my files, but nonetheless, if anyone could create another user, that's not good.

**Comment by TemptingTaco12** [comment]
I had the same problem when I tried to refresh install my OS. Came across this Reddit post which solved the problem on my end: https://www.reddit.com/r/pop_os/comments/m33amm/recover_user_after_refresh_install/.

**Comment by hungry-bogart** [comment]
`[User]
Session=
Icon=/run/gnome-initial-setup//.face
SystemAccount=true

[InputSource0]
xkb=us
`
I see this in the file path suggested in the Reddit thread you referenced. Thanks for the tip. I'll make the edit and see if it helps.

**Comment by hungry-bogart** [comment]
Changing system account to false and rebooting fixed the problem. I still believe this to be strange behavior nonetheless. I'm closing this since it is a issue that can be resolved. I would be happy to debug or investigate this if necessary with Pop OS devs if needed. Closing unless reopened.
