### ISSUE TITLE
Chrome disrupts Suspend behaviour

### ISSUE THREAD

**Issue by Appalbarry** [pop-os/pop#288]
This bug report replaces a previous one.  
Random Behaviour with Laptop Wake on Opening Lid
https://github.com/pop-os/pop/issues/262

Distribution - (run cat /etc/os-release)
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

This bug references pop-os_18.04_amd64_intel_21.iso

Related Application and/or Package Version - apt policy $PACKAGE NAME
Chrome (download from Google) Version 66.0.3359.181 (Official Build) (64-bit)
google-chrome-stable:
  Installed: 66.0.3359.181-1
  Candidate: 66.0.3359.181-1
  Version table:
 *** 66.0.3359.181-1 500
        500 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
     66.0.3359.139-1 500
        500 http://apt.pop-os.org/proprietary bionic/main amd64 Packages

Issue/Bug Description

**Short Version:** if Chrome is left running while the laptop is unattended it will often not wake from suspend in the expected fashion.  Often any open applications will have been closed.  The exact sequence of events does vary from one instance to the other.  The previous bug report runs down the trial and error process that narrowed the problem down to Chrome.

**Long version:** At each instance I either closed the laptop lid or just left the laptop unattended, with Chrome and perhaps one other application open. The laptop remained plugged into AC power. In each case I came back after a period of time and either opened the laptop lid or pressed SPACE to wake the computer.

Laptop is idle for an extended period.
Laptop sometimes does not display the lock screen when opened.
Tap the space bar to "wake up" the computer.
A blank screen with a single flashing cursor sometimes appears, and is displayed for about 30 seconds.
A non-scrolling screen of terminal output sometimes appears, and is displayed for about 10 seconds.(see screen grabs below)
The log in box with my picture appears, I enter password.
A blank screen with an arrow pointer in the middle appears, and is displayed for about 8 seconds.
The desktop appears.
No applications are open, even though they were open when the lid was closed.

_It seems that if Chrome is left open the computer does a reboot if left unattended._

If Chrome is not running suspend works as expected.

![screen1](https://user-images.githubusercontent.com/1308152/40332930-d9aeeb8a-5d0a-11e8-9d23-95c21c08eb10.jpg)
![screen2](https://user-images.githubusercontent.com/1308152/40332931-d9c95100-5d0a-11e8-9d77-5272b30e9bb8.jpg)

**Comment by quantifish** [comment]
I am having the same issue with `pop-os_18.04_amd64_nvidia_36.iso` on a new Serval WS.

    $cat /etc/os-release
    NAME="Pop!_OS"
    VERSION="18.04 LTS"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Pop!_OS 18.04 LTS"
    VERSION_ID="18.04"
    HOME_URL="https://system76.com/pop"
    SUPPORT_URL="http://support.system76.com"
    BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
    PRIVACY_POLICY_URL="https://system76.com/privacy"
    VERSION_CODENAME=bionic
    UBUNTU_CODENAME=bionic

If Google chrome is open when I close the lid and I leave the laptop for more than about 30 minutes then I get a black screen when I open the lid.

**Comment by jackpot51** [comment]
We have released a firmware update that I hope addresses the issue.

**Comment by brs17** [comment]
Since no comments have been made since the firmware update, I am going to assume the issue was fixed. If it was not, feel free to comment and the issue will be reopened.

**Comment by tilsammans** [comment]
I have this issue. I am fully up-to-date running on a System76 aardvarck.

Good to know Chrome is involved. I can just quit chrome and things will be fine.

**Comment by ComputerCarl** [comment]
I have a similar issue on IBM ThinkServer, w/ POS 18.04 Nvidia.
When I leave the computer running idle for an indeterminate time, I can only cold boot to recover.
I do not have Chrome installed.

**Comment by TrentBrick** [comment]
I have a similar issue with my Alienware that I installed Pop-OS on but have not yet experimented with Chrome being the problem (if it is then is Chromium more likely to work?)

If I press the power button (putting the computer into suspend) most of the time when I come back to power it on, it will show me the login in screen but with the original Pop-OS robot guy as the background photo (I have replaced this with a different one so it should not appear) and then when I log in all of my applications have been closed and it is like I shutdown the computer. I am using Pop-OS 19.04 and update it regularly.

**Comment by vgjenks** [comment]
> I have a similar issue with my Alienware that I installed Pop-OS on but have not yet experimented with Chrome being the problem (if it is then is Chromium more likely to work?)
> 
> If I press the power button (putting the computer into suspend) most of the time when I come back to power it on, it will show me the login in screen but with the original Pop-OS robot guy as the background photo (I have replaced this with a different one so it should not appear) and then when I log in all of my applications have been closed and it is like I shutdown the computer. I am using Pop-OS 19.04 and update it regularly.

Awesome! Well, sort of - at least I'm not the only person having this problem. I get the same exact thing - the Gnome shell crashes and restarts, which obviously kills all GUI apps running in that context.

VERY disruptive. This is the only real issue (aside from some sound flakiness) that I have with Pop. I really, really hope someone figures out how to squash this bug.

**Comment by mmstick** [comment]
@vgjenks Are you using Wayland? GNOME Shell is able to crash and restore itself with X11.

**Comment by vgjenks** [comment]
@mmstick Honestly, don't know. I installed 19.10 and got right down to work - haven't toyed w/ the system at all. Have some quick instructions handy to switch? I'm willing to try anything. This is making me nuts.
