### ISSUE TITLE
Malformed terminal text 

### ISSUE THREAD

**Issue by Slagzz** [pop-os/pop#2882]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
The bug involves the tools cat and ls

**Issue/Bug Description:**
When cat'ing the file /usr/bin/ls all input and output from that terminal afterword's is malformed.
The commands written in the terminal will run but all text going in or out of the terminal will be malformed until the terminal is exited/closed.

**Steps to reproduce (if you know):**
run the command 'cat /usr/bin/ls'
everything after this command will show as malformed text until the terminal is closed. below is a screen shot of me running "ls" "whoami", "pwd" and cat /etc/os-release in that order.

![image](https://user-images.githubusercontent.com/74060997/236059153-e6da746f-6da1-4f2f-a1d7-04f55dd6a5fe.png)

**Expected behavior:**
The expected behavior is that the compiled code of the tool ls is read back into the terminal.

**Other Notes:**
This bug is present in both host machine POP OS and virtualized POP OS

**Comment by jacobgkau** [comment]
This is not an issue with Pop!_OS and will happen when `cat`ting out binaries on any distro. You are feeding text into the terminal that it is not meant to display; the terminal interprets some of the text as control symbols. You can run `reset` to get the terminal back to normal again after doing this.
