### ISSUE TITLE
Crimea peninsula is associated to incorrect timezone

### ISSUE THREAD

**Issue by scimonstr** [pop-os/pop#2886]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-control-center:   
  Installed: 1:41.4-1ubuntu12pop1~1653075611~22.04~64c84a2   
  Candidate: 1:41.4-1ubuntu12pop1~1653075611~22.04~64c84a2   
  Version table:   
     1:41.7-0ubuntu0.22.04.6 500     
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages   
     1:41.4-1ubuntu13.2 500   
        500 http://apt.pop-os.org/ubuntu jammy-security/main amd64 Packages   
 *** 1:41.4-1ubuntu12pop1~1653075611~22.04~64c84a2 1001   
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages     
        100 /var/lib/dpkg/status   
     1:41.4-1ubuntu12 500   
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

**Issue/Bug Description:**
While setting time zone using settings Crimea peninsula is associated to incorrect time zone.

**Steps to reproduce (if you know):**
1. Open settings
2. Switch to Date & Time
3. Click on Time Zone setting. Modal window will open displaying a map for time zone selection.
4. Click on Crimea peninsula
5. Observe that the selected time zone is "MSK UTC(+03)" with UTC(+03) time zone highlighted on the map. 

**Expected behavior:**
By International Law, Crimea is Ukraine and therefore upon clicking on Crimea peninsula on the map EEST UTC(+03) shall be selected, i.e. same as for other regions of Ukraine.

**Other Notes:**
Here are some screenshot of the behavior
![image](https://user-images.githubusercontent.com/10483688/236523145-6ba17f51-4264-4fed-ad20-f175b9348e91.png)
![image](https://user-images.githubusercontent.com/10483688/236523101-9d607c86-c37a-43d6-b65c-c26125388268.png)

**Comment by leviport** [comment]
This is not determined by the Pop!\_OS team. These timezones are defined by the upstream `tzdata` package, which I believe uses definitions from the [TZ Database](https://en.wikipedia.org/wiki/Tz_database). If that database changes, `tzdata` will change, and the timezone selector will also change in Pop!\_OS.

I'd also note that the specific labels are more a reference to a place in that timezone for which the time is the same year-round. For example, the label for U.S. Eastern time references New York City, despite the Eastern timezone encompassing many cities other than NYC. There is also "America/Denver" for all of U.S. Mountain time, and "America/Phoenix" for Arizona's time zone, which is basically Mountain time, sans any Daylight Savings changes.

**Comment by scimonstr** [comment]
@leviport thanks for information on TZ Database, I'll report the bug there.

And as to your note on labeling, it is irrelevant, Crimea has nothing to do with MSK (moscow) timezone, that is plain mistake. On the second screenshot you can see that Crimea is highlighted as part of EEST time zone.
And that is really important thing, that's how russians trying to legitimate presence in Crimea.
