### ISSUE TITLE
Installer crashes when exiting at "Keyboard layout" page.

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#29]
_From @brs17 on October 10, 2017 22:47_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**

![screenshot from 2017-10-10 22-34-08](https://user-images.githubusercontent.com/7460774/31414206-0d434dc8-adda-11e7-91ae-3af04b100fab.png)

**Steps to reproduce (if you know)**
In the installation:
1. Select a language
2. Select Quit when prompted for the Keyboard layout

**Expected behaviour**
Installer should exit peacefully

**Other Notes**

_Copied from original issue: pop-os/iso#135_

**Comment by isantop** [comment]
_From @brs17 on October 10, 2017 23:1_

A side-effect of this bug is that when the installer is run again (after crashing), the keyboard layout does not change to a newly selected language.

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
