### ISSUE TITLE
Install exfat-fuse by default

### ISSUE THREAD

**Issue by cdknight** [pop-os/pop#290]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**
When attempting to mount an exfat drive (in this case a micro-sd card) nautilus reports the drive has an unknown filesystem type.

**Steps to reproduce (if you know):**
Insert an exfat-formatted drive and attempt to access it.

**Expected behavior:**
The drive should mount and file contents should be displayed.

**Other Notes:**
Upon installing `exfat-fuse` everything works.

**Comment by jackpot51** [comment]
There are patent issues with exfat-fuse, meaning we do not want to distribute it
