### ISSUE TITLE
[pang12] How to update Mesa drivers?

### ISSUE THREAD

**Issue by juan-lunarg** [pop-os/pop#2918]
**Distribution**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Issue Description:**

I'm looking for documentation/instructions on how to update my drivers for my AMD GPU.

I'm using a pang12 System76 Laptop and would like to update my graphics drivers.

Currently I'm using Mesa `22.3.5`.

```sh
glxinfo | grep "OpenGL version"
OpenGL version string: 4.6 (Compatibility Profile) Mesa 22.3.5
```

However, I'd like to use newer Mesa graphics drivers. As of writing the current release is `23.1.2`.

It looks like there are mechanisms for updating my graphics drivers.
https://docs.mesa3d.org/precompiled.html

But I've been unsuccessful so far after following various online tutorials.

Any help is appreciated.

**Comment by jacobgkau** [comment]
Mesa is packaged as part of Pop!_OS. You will receive updates as part of normal system updates (through the Pop!_Shop or via `sudo apt update`/`sudo apt full-upgrade`) when they're tested and released by the Pop!_OS team.

You can see the source code for the Pop!_OS mesa package here: https://github.com/pop-os/mesa 

We QA our software on the pang12. Are you experiencing any issues causing you to want to update mesa faster?

If you really do want to update manually, building a newer branch of the upstream Debian package: https://salsa.debian.org/xorg-team/lib/mesa using `dpkg-buildpackage -b -uc -us` and then installing it would probably be the easiest way, as long as it doesn't have newer dependencies than Pop!_OS provides.

---

System76 customers can reach out to [support](https://support.system76.com/) for technical assistance. For non-System76 hardware, you can seek community support on [Reddit](https://reddit.com/r/pop_os/) or [Mattermost](https://chat.pop-os.org).

**Comment by juan-lunarg** [comment]
> Are you experiencing any issues causing you to want to update mesa faster?

1.) I am seeing a minor video issue and would like to see if updating and/or re-installing my graphics drivers fixes the issue.

2.) My work generally requires running against newer graphics drivers.

**Comment by juan-lunarg** [comment]
> If you really do want to update manually, building a newer branch of the upstream Debian package: https://salsa.debian.org/xorg-team/lib/mesa using dpkg-buildpackage -b -uc -us and then installing it would probably be the easiest way, as long as it doesn't have newer dependencies than Pop!_OS provides.

Ideally I'd just like to use a PPA pointing to newer versions of the mesa driver.

Like the kisak-mesa PPA:
- https://itsfoss.com/install-mesa-ubuntu/
- https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa

However, adding the kisak PPA didn't work for me.

**Comment by jacobgkau** [comment]
You'll need to be more specific than "didn't work for me." What error(s) are you seeing when you try to add the PPA and update from it?

**Comment by jacobgkau** [comment]
Can you provide the output of `apt policy mesa-vulkan-drivers`?

**Comment by juan-lunarg** [comment]
```
apt policy mesa-vulkan-drivers
mesa-vulkan-drivers:
  Installed: 22.3.5-1pop1~1677168864~22.04~8f20e98
  Candidate: 22.3.5-1pop1~1677168864~22.04~8f20e98
  Version table:
     23.1.2~kisak1~j 500
        500 https://ppa.launchpadcontent.net/kisak/kisak-mesa/ubuntu jammy/main amd64 Packages
 *** 22.3.5-1pop1~1677168864~22.04~8f20e98 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     22.2.5-0ubuntu0.1~22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     22.0.1-1ubuntu2 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Comment by jacobgkau** [comment]
You need to increase the pin priority for the kisak PPA so it's above the Pop!_OS repo's default `1001`. You can do that by creating a file in `/etc/apt/preferences.d/` (such as `/etc/apt/preferences.d/kisak`) containing this:

```
Package: *
Pin: release o=LP-PPA-kisak-kisak-mesa
Pin-Priority: 1002
```

(The format is `LP-PPA-<LP organization>-<LP repo>`.)

After that, a `sudo apt full-upgrade` (or just `sudo apt upgrade`) should pick it up-- `sudo apt update` shouldn't even be required. (You can confirm before installing by checking `apt policy` and seeing if the candidate version changed.)

**Comment by juan-lunarg** [comment]
That did the trick. Thank you very much for your time 💯 

```
juan@pop-os:~$ glxinfo | grep "OpenGL version"
OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.1.2 - kisak-mesa PPA
juan@pop-os:~$ cat /etc/apt/preferences.d/kisak 
Package: *
Pin: release o=LP-PPA-kisak-kisak-mesa
Pin-Priority: 1002
```
