### ISSUE TITLE
Odd behavior when renaming .desktop files

### ISSUE THREAD

**Issue by epistax** [pop-os/pop#293]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**
When renaming a .desktop file from Files or directly on the Desktop, an extension of .desktop will be added. So for example if the filename is "abc.desktop", and from the context menu you select rename and type "123", you'll actually get "123.desktop.desktop". If you go back to the context menu and select rename again but just hit enter, you'll get "123.desktop.desktop.desktop". 

**Steps to reproduce (if you know):**
See above

**Expected behavior:**
If the filename already ends in .desktop, no additional .desktop is provided.

**Other Notes:**

**Comment by mmstick** [comment]
Guess it couldn't hurt to check out File's source code.

**Comment by mmstick** [comment]
This bug is not present in the master branch of Nautilus. They must have already patched this upstream.

**Comment by mmstick** [comment]
After looking into it, this patch I've created seems to fix it:

```patch
--- src/nautilus-file.c	2018-05-29 20:32:35.000000000 -0600
+++ ../nautilus-file.c	2018-05-29 20:32:10.881176284 -0600
@@ -2199,7 +2199,8 @@
             g_error_free (error);
             return NULL;
         }
-        new_file_name = g_strdup_printf ("%s.desktop", new_name);
+
+        new_file_name = g_strdup (new_name);
         new_file_name = g_strdelimit (new_file_name, "/", '-');
 
         if (name_is (file, new_file_name))
```

**Comment by mmstick** [comment]
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1774094 We'll see what Ubuntu says about the patch.
