### ISSUE TITLE
Multiple monitors stuttering every ~5 seconds

### ISSUE THREAD

**Issue by JeffLabonte** [pop-os/pop#294]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

When on Gnome and using two screens, GUI stutters.

**Steps to reproduce (if you know):**
Have a fresh install of Pop!_OS. Use gnome with X11, Open any GUI app and move it as fast as possible, you will see the stutter.

**Expected behavior:**
No Stutters

**Comment by mmstick** [comment]
What's your hardware? Active graphics driver?

**Comment by JeffLabonte** [comment]
Dell XPS 15 9650 with a Nvidia GTX 1050. Drivers that comes with Pop!_OS on fresh install. Nvidia proprietary drivers. It also happen with Intel drivers. I have tried to go on MATE and i didn't have the issue. 

It seems that I am not the only one having this issue: https://www.reddit.com/r/pop_os/comments/8k2k1j/1804_nvidia_bad_interface_lag/

**Comment by JeffLabonte** [comment]
It seems that it has been fixed in a recent update! I will make some more testing and close the issue!
