### ISSUE TITLE
message: acpi int3400:00: unsupported event [0x86]

### ISSUE THREAD

**Issue by gil2gm** [pop-os/pop#295]
i have a problem, the message **acpi int3400:00: unsupported event [0x86]** is present went sent the laptop to hibernate or suspend

I have ASUS X510U i7 Nvidia 930Mx

**Comment by mmstick** [comment]
You'll have to ask ASUS to fix this for their hardware.

**Comment by ack0329** [comment]
‣ Grub
• add to grub's ... GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"...
• and another good idea ....Change GRUB_TIMEOUT=10 sec see Grub to GRUB_TIMEOUT=3. This will make the Grub load time to 2 seconds.
• sudo gedit /etc/default/grub
• sudo update-grub2
• sudo update-initramfs -u (Always a good idea)
• reboot
