### ISSUE TITLE
Battery percentage in lock screen not updating

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#296]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

The battery percentage dispalyed in the home screen does not reflect reality or better does not update. I had 58% in the lock screen and when I logged in it changed to 96%.

**Steps to reproduce (if you know):**

lock it and charge it

**Expected behavior:**

**Other Notes:**

**Comment by Clae224** [comment]
Duplicate of #249. Please comment there and also post the hardware you are using.
