### ISSUE TITLE
linux-image and linux-headers not installing

### ISSUE THREAD

**Issue by mikfra** [pop-os/pop#298]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
linux-headers-4.15.0-23-generic:
  Installed: 4.15.0-23.25
  Candidate: 4.15.0-23.25
  Version table:
 *** 4.15.0-23.25 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-proposed/main amd64 Packages
        100 /var/lib/dpkg/status
     4.15.0-23.25 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages

**Issue/Bug Description:**
Every Time I boot into pop_os I am greeted with the same updates that I recently installed before the reboot. The updates never fully install or become uninstalled after a reboot 
The updates are as follows:
9 components with updates:
 • linux-generic
	Complete Generic Linux kernel and headers
	Version: 4.15.0.23.25
 • linux-headers-4.15.0-23
	Header files related to Linux kernel version 4.15.0
	Version: 4.15.0-23.25
 • linux-headers-4.15.0-23-generic
	Linux kernel headers for version 4.15.0 on 64 bit x86 SMP
	Version: 4.15.0-23.25
 • linux-headers-generic
	Generic Linux kernel headers
	Version: 4.15.0.23.25
 • linux-image-4.15.0-23-generic
	Signed kernel image generic
	Version: 4.15.0-23.25
 • linux-image-generic
	Generic Linux kernel image
	Version: 4.15.0.23.25
 • linux-libc-dev
	Linux Kernel Headers for development
	Version: 4.15.0-23.25
 • linux-modules-extra-4.15.0-23-generic
	Linux kernel extra modules for version 4.15.0 on 64 bit x86 SMP
	Version: 4.15.0-23.25
 • linux-signed-generic
	Complete Signed Generic Linux kernel and headers (dummy transitional package)
	Version: 4.15.0.23.25

**Steps to reproduce (if you know):**
Troubleshooting:
sudo apt clean && Sudo apt autoremove
sudo apt update
dpkg --configure -a
sudo apt upgrade
sudo apt dist-upgrade

Attempted to install the linux-image and linux-headers manually

**Expected behaviour:**
Expected linux-headers and linux-image to be installed

**Other Notes:**
Whats the best way to get the nvidia gpu in razor blade to work more efficiently 

Any help would be greatly appreciated

**Comment by axelmeunier** [comment]
I have the same problem (though it started today only).

**Comment by mmstick** [comment]
They're installed. There's just a repo conflict where it wants to reinstall the same package.

**Comment by mmstick** [comment]
Seems that apt will always prefer the repo that is listed earlier in the `sources.list`, disregarding priority, whenever multiple repos have the same package.

**Comment by jackpot51** [comment]
Delete the linux-meta and linux-signed from the Pop PPA, if the Ubuntu one has been released and is up to date

**Comment by axelmeunier** [comment]
it's almost resolved for me, except for 1 package (linux-modules-4.15.0-23-generic) which keeps appearing.

**Comment by mikfra** [comment]
@mmstick Apt-Pinning for the Win!!!
Now to get these nvidia drivers working lol
