### ISSUE TITLE
Two languages not properly displaying in Installer

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#30]
_From @brs17 on October 10, 2017 22:30_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
Two languages are not viewing properly at all

![next](https://user-images.githubusercontent.com/7460774/31413225-82b0c7de-add5-11e7-812b-2ca04bd222ae.png)

**Steps to reproduce (if you know)**
Reproduces on every install

**Expected behaviour**
Language properly displays

**Other Notes**

_Copied from original issue: pop-os/iso#134_

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
