### ISSUE TITLE
Unable to boot with pop os

### ISSUE THREAD

**Issue by Freedomafia** [pop-os/pop#301]
**Distribution (run `cat /etc/os-release`):**

Pop os 18.04
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop os 18.04

**Issue/Bug Description:**

I wanted to boot my dell XPS 15 9570 with Pop os 18.04 (Nvidia version) and I disabled secure boot in my BIOS. I am able to get to the point where I am in the Pop os install environment. I select the drive 'Nvme Device' (which is the only one available) and it installs and restarts the computer. However as it restarts (to install Pop os) I get the following error message:

" [Failed] Failed unmounting cdrom.mount"

amongst all the other messages that are [okay]. Then when it switches back on a message on the screen says:

No boot device. Press any key to reboot the machine.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

As I disabled secure boot, I have lost Windows. This isn't a problem as I wanted to fully replace Windows with Pop os anyway.

**Comment by Freedomafia** [comment]
@jackpot51 Any suggestions please.

**Comment by Git76** [comment]
@Freedomafia I'm attempting the same thing on a Dell XPS 13. It has something to do with the boot loader. I can run Ubuntu or Fedora successfully. Like you, when I complete the install and reboot I get the message that no drives are found. I tried to install Grub before exiting the install but it didn't work - this is a stretch of my knowledge. I'm attempting to dual boot fedora and Pop right now. I'll let you know if it works

**Comment by mmstick** [comment]
@Freedomafia @Git76 Make sure you're BIOS is booting to the systemd boot loader installed by Pop!_OS.

**Comment by Git76** [comment]
@Freedomafia Turn off SecureBoot in the BIOS menu access by F12 AND switch your SATA operation to AHCI. I was able to get my install to work - runs great.

**Comment by SeptimusX75** [comment]
@Freedomafia I have the same XPS model and I can't even get the Live USB to boot. Did your Live USB have any issues prior to booting? I'm trying to narrow down the cause of my problem.

When I select the Pop!_OS USB from the boot menu all I get is a black screen with a white underscore in the top left corner of the screen. 

These are my system specs for anyone else that might be looking into this issue:

- 8th Generation Intel® Core™ i9-8950HK Processor (12M Cache, up to 4.8 GHz, 6 cores)
- NVIDIA GeForce GTX 1050Ti with 4GB GDDR5
- 32GB DDR4-2666MHz, 2x16GB
- 1TB M.2 2280 PCIe Solid State Drive

You can also see the specs [here].(https://www.dell.com/en-us/work/shop/cty/pdp/spd/xps-15-9570-laptop/cax15w10p1c1654p?cid=309255&st=&gclid=CjwKCAjw9qfZBRA5EiwAiq0AbQLiG2LRnIxGP7VRL1L8lRJ5jgOklviKxTvCn0hzhCXN8nfS0dejzBoC20oQAvD_BwE&lid=5844258&VEN1=sKEtgZ5BW,178681018987,901q5c14135,c,,CAX15W10P1C1654P&VEN2=,&dgc=st&dgseg=so&acd=12309152537501410&VEN3=114004453101429271)

I was also able to install Ubuntu 18.04 but have not been able to boot Pop!_OS so if anyone has any ideas, I'm happy to try them.

**Comment by mmstick** [comment]
@SeptimusX75 

> I can't even get the Live USB to boot

Which ISO did you use? If you chose the Intel ISO, the nouveau driver may be your issue.

**Comment by SeptimusX75** [comment]
@mmstick I've tried both pop-os_18.04_amd64_nvidia_23 and pop-os_18.04_amd64_nvidia_24 to no avail.

**Comment by Freedomafia** [comment]
Hi @SeptimusX75 @Git76 

I was unable to boot both Pop Os and Ubuntu. I was messing around with the BIOS settings attempting all sorts of configurations but I could not get it to install. I would get the demo running but it would never successfully install. In the end I had to return my dell xps 15 - shame as well because I really wanted to try out the intel i9

**Comment by SeptimusX75** [comment]
So... I got it to work. Turns out it was a BIOS issue. For anyone else experiencing the same issue, in the BIOS go to **Settings > General > Advanced Boot Options** then check the box next to _Enable Legacy Option ROMs_. After that Make sure _Secure Boot_ is disabled and that _SATA Operation_ is set to _AHCI_. I arrived at this solution from reading [this](http://xps-15.wikia.com/wiki/Cannot_boot_from_USB).

**Comment by yonilerner** [comment]
@SeptimusX75 Thanks! I too have the 8950HK model and had this exact issue, and enabling legacy option roms worked!

**Comment by optimuspaul** [comment]
I'd like to dual boot my system, this solution doesn't work for me
