### ISSUE TITLE
nagging update for kernel downgrade???

### ISSUE THREAD

**Issue by cunctator00** [pop-os/pop#302]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Booted up the laptop this morning and I had this OS update. I did it but it wont go away, every time I reboot it pops up again.
I tried doing it using the terminal and it says it is a DOWNGRADE. Even updating through the terminal it won't go away.

Below what the Terminal reads.

`reading state information... Done
Calculating upgrade... Done
The following packages will be DOWNGRADED:
  linux-generic linux-headers-4.15.0-23 linux-headers-4.15.0-23-generic
  linux-headers-generic linux-image-4.15.0-23-generic linux-image-generic
  linux-libc-dev linux-modules-extra-4.15.0-23-generic linux-signed-generic
  linux-tools-4.15.0-23 linux-tools-4.15.0-23-generic linux-tools-common
  linux-tools-virtual
0 upgraded, 0 newly installed, 13 downgraded, 0 to remove and 0 not upgraded.
Need to get 55.7 MB of archives.
`

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**
https://www.reddit.com/r/pop_os/comments/8qhucf/nagging_update_for_kernel_downgrade/

**Comment by tonymke** [comment]
Seems to come from a package in from the system76 launchpad source (```http://apt.pop-os.org/proprietary bionic main```). I think "PPA" is the ubuntu terminology for it.

If I were to guess, either a package from it that's installed by default has an upper bound on the kernel version, or there's some misbehaving pinning shenanigans.

**Comment by jackpot51** [comment]
This will be addressed shortly. We had released a newer kernel than Ubuntu to gain hardware support a week ago. Now that Ubuntu has released the same kernel version, our version has been removed and devices will start pulling in the Ubuntu version

**Comment by brs17** [comment]
This issue was fixed a while back. We will not avoid the issue entirely with the `linux-system76` package.
