### ISSUE TITLE
Chrome broken and Firefox won't save!!!!!

### ISSUE THREAD

**Issue by wdevore** [pop-os/pop#304]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
firefox:
  Installed: 60.0.2+build1-0ubuntu0.17.10.1
  Candidate: 60.0.2+build1-0ubuntu0.17.10.1
  Version table:
 *** 60.0.2+build1-0ubuntu0.17.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu artful-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu artful-security/main amd64 Packages
        100 /var/lib/dpkg/status
     56.0+build6-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages

**Issue/Bug Description:**
After the last update Chrome won't start and Firefox refuses to down to any folder! !@#$!#$%@#F!!!!!!

**Steps to reproduce (if you know):**
Just do an update and you are F$$$$$ed

**Expected behavior:**
I @#$! should be able to launch chrome without updates screwing me over. I mean seriously!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
I literally am locked out from downloading anything!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Other Notes:**

**Comment by wdevore** [comment]
I mean seriously!!! I can't even downgrade chrome because then it wants to upgrade. WTF!!!!!

**Comment by wdevore** [comment]
I was seriously thinking of purchasing a leopard box until this crap happened! I mean what do I do now!!!!! really! WHAT DO I DO NOW!!!

**Comment by wdevore** [comment]
What is this garbage!!!!!!!!!!!!!!!!!!!!11

google-chrome-stable 
[19868:19868:0619/201456.421385:ERROR:process_singleton_posix.cc(1036)] Failed to create socket directory.
[19868:19868:0619/201456.421527:ERROR:chrome_browser_main.cc(1686)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.

**Comment by wdevore** [comment]
@#$%@#$. Whatever you guys did must have done something to the gpu code framework. no matter what i do (unistall/install.... etc) i can't get chrome to launch because of some !@$@!#$ gpu problem!!!

google-chrome-stable 
[16601:16601:0619/203721.650435:ERROR:process_singleton_posix.cc(1025)] Failed to create socket directory.
[16601:16601:0619/203721.650538:ERROR:chrome_browser_main.cc(1496)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
[16601:16638:0619/203721.679718:ERROR:browser_gpu_channel_host_factory.cc(121)] Failed to launch GPU process.


--------------------------
WHAT DO I DO NOW! seriously, am i going to have to reimage the laptop somehow!!!

**Comment by wdevore** [comment]
Now i think i will be sick. My gazelle laptop won't recognize an SD card when I boot holding the F7 key. it doesn't see my sandisk card. What do i do now, I have a "brick" that I can't recover from.

i have no idea what i should do now....

**Comment by brs17** [comment]
@wdevore I believe the gazelle does not permit booting from an SD card. Please go ahead and create a support ticket with your System76 account on the website and I am positive the support team will be able to help you out and get everything back up and running again.

**Comment by wdevore** [comment]
I was able to re-image the laptop to the lastest pop os with one exception, I TURNED OF ENCRYPTION! It is my guess that the latest update borked some sort of encryption "somewhere" that effected several applications. Nonetheless, it works. ;-) I would suggest that you consider not installing/updating to the new os with encryption turned on but that is my personal opinion.
