### ISSUE TITLE
App icon doesn't appear in top right corner

### ISSUE THREAD

**Issue by MarkVaughn** [pop-os/pop#306]
**Distribution**
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description:**
After installing a VPN service successfully and its running in the background, I can not access the controls because the dropdown icon is missing.

**Steps to reproduce:**
Following installation instructions from https://www.privateinternetaccess.com/helpdesk/guides/desktop/linux/ubuntu-pia-app-setup

The app is now running, in the background, but I can not access the drop down icon that should be in the top right next to the wifi and volume.

**Expected behaviour:**

![image](https://user-images.githubusercontent.com/39970/41748327-a8ef81d6-756e-11e8-8b98-ccd5788578ce.png)

**Actual behaviour**
Icon is missing.
![screenshot from 2018-06-21 16-18-18](https://user-images.githubusercontent.com/39970/41748375-dcf17408-756e-11e8-898b-7c0df5483bf0.png)

**Comment by mmstick** [comment]
Try out https://extensions.gnome.org/extension/1031/topicons/

**Comment by MarkVaughn** [comment]
That worked, was this an issue with Pop OS or PIA?
