### ISSUE TITLE
Lack of radeon software support 

### ISSUE THREAD

**Issue by PeaceNira** [pop-os/pop#3065]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
 
 
amdgpu-install
Radeon™ Software for Linux® version 22.40.6 for Ubuntu 22.04.2
22.40.6

Attempting to install the driver (to gain access to radeon software, intially results in a unsupported OS. upon adding "pop"
to the OS it attempts to install but runs into: 
xserver-xorg-amdgpu-video-amdgpu : Depends: xorg-video-abi-24 but it is not installable

Download the latest amd radeon drivers for ubuntu at: (in my case, a 6700xt)
https://www.amd.com/en/support/graphics/amd-radeon-6000-series/amd-radeon-6700-series/amd-radeon-rx-6700-xt
add "pop" to the os list
run amdgpu-install

install the driver/radeon software

Having a proper panel for monitoring, configuring and troubleshooting is vital to a good user experience. i am unable
to make game profiles, edit fan speeds or clocks, monitor game FPS, ect.

**Comment by mmstick** [comment]
You have to report this to AMD, since we're not packaging this. But you won't get any of things from the package on their website, and I'd not recommend using it over AMD's open source driver in the kernel, which is a better driver.
