### ISSUE TITLE
S3 sleep broken, only modern standby works 

### ISSUE THREAD

**Issue by realKarthikNair** [pop-os/pop#3078]
**Distribution (run `cat /etc/os-release`):** 22.04

**Issue/Bug Description:** S3 sleep broken, only modern standby works 

System doesn't wake up from sleep (blank screen unresponsive keyboard)

- not using Nvidia dGPU (using iGPU)
- ryzen 5 4500u
- reproducible on both X11 and Wayland

**Comment by realKarthikNair** [comment]
Hibernation working perfectly. Only suspend is broken when BIOS is set to S3 standby.

**Comment by mmstick** [comment]
This is a hardware-related issue so you'll have to post your hardware specs and describe the issue in more detail.

**Comment by realKarthikNair** [comment]
Apologies for responding late.

- The last ever BIOS update this machine had was in 2022 and S3 sleep was working perfectly on Pop!_OS 22.0 until June 2023, so it's probably one of the July kernel updates from Pop!_OS

Motherboard and UEFI Info

```bash
karthik@cosmic:~$ sudo inxi -M
Machine:
  Type: Laptop System: ASUSTeK product: VivoBook_ASUSLaptop X421IAY_M413IA
    v: 1.0 serial: LAN0CX06K052439
  Mobo: ASUSTeK model: X421IAY v: 1.0 serial: L835NBCX00FA1RMB
    UEFI: American Megatrends v: X421IAY.314 date: 05/24/2022
```

Neofetch (Fastfetch)

```
karthik@cosmic:~$ neofetch
             /////////////                 karthik@cosmic
         /////////////////////             --------------
      ///////*767////////////////          OS: Pop!_OS 22.04 x86_64
    //////7676767676*//////////////        Host: VivoBook_ASUSLaptop X421IAY_M413IA 1.0
   /////76767//7676767//////////////       Kernel: 6.2.6-76060206-generic
  /////767676///*76767///////////////      Uptime: 4 mins
 ///////767676///76767.///7676*///////     Packages: 3308 (dpkg), 1 (flatpak)
/////////767676//76767///767676////////    Shell: bash 5.1.16
//////////76767676767////76767/////////    Resolution: 1920x1080 @ 60Hz
///////////76767676//////7676//////////    DE: GNOME 42.5
////////////,7676,///////767///////////    WM: Mutter (Wayland)
/////////////*7676///////76////////////    WM Theme: Pop-dark
///////////////7676////////////////////    Theme: Pop-dark [GTK2/3/4]
 ///////////////7676///767////////////     Icons: Numix-Circle [GTK2/3/4]
  //////////////////////'////////////      Font: Bahnschrift (11pt) [GTK2/3/4]
   //////.7676767676767676767,//////       Cursor: breeze (24px)
    /////767676767676767676767/////        Terminal: gnome-terminal-server
      ///////////////////////////          Terminal Font: JetBrains Mono (14pt)
         /////////////////////             CPU: AMD Ryzen 5 4500U (6) @ 4.011 GHz
             /////////////                 GPU: AMD Renoir
                                           Memory: 1.78 GiB / 7.18 GiB (24%)
                                           Disk (/): 88.36 GiB / 146 GiB (60%)
                                           Battery: 77% [Discharging]
                                           Locale: en_GB.UTF-8

                                           ████████████████████████
                                           ████████████████████████
karthik@cosmic:~$ 
```

As I added earlier, I am NOT using any dGPU, s2idle works file and hibernation too works.

**Comment by realKarthikNair** [comment]
Just an addendum: I faced a similar issue on the same machine back in 2021 when I booted Pop!_OS for the first time too, but both S3 sleep and s2idle (modern standby) was broken in that case and it got fixed in a few months.

**Comment by martyfuhry** [comment]
I've also suddenly started having this happen every day on my machine. I just had it happen right now (11 minutes ago, in fact...). I do not notice anything out of the ordinary in `journalctl`. I will share my hardware below as well:

<details>

<summary>My hardware</summary>

```
             /////////////                martyfuhry@pomerium 
         /////////////////////            ------------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Kernel: 6.2.6-76060206-gener 
   /////76767//7676767//////////////      Uptime: 11 mins 
  /////767676///*76767///////////////     Packages: 3404 (dpkg), 102 ( 
 ///////767676///76767.///7676*///////    Shell: bash 5.1.16 
/////////767676//76767///767676////////   Resolution: 1920x1080, 1920x 
//////////76767676767////76767/////////   DE: GNOME 42.5 
///////////76767676//////7676//////////   WM: Mutter 
////////////,7676,///////767///////////   WM Theme: Pop 
/////////////*7676///////76////////////   Theme: Pop-dark [GTK2/3] 
///////////////7676////////////////////   Icons: Pop [GTK2/3] 
 ///////////////7676///767////////////    Terminal: gnome-terminal 
  //////////////////////'////////////     CPU: AMD Ryzen 7 5800X (16)  
   //////.7676767676767676767,//////      GPU: NVIDIA GeForce RTX 3060 
    /////767676767676767676767/////       Memory: 9504MiB / 64219MiB 
      ///////////////////////////
         /////////////////////                                    
             /////////////                                        

```

</details>

**Comment by realKarthikNair** [comment]
Can you please share motherboard and UEFI information too?

```bash
sudo apt install inxi
```

```bash
sudo inxi -M
```

**Comment by martyfuhry** [comment]
```bash
martyfuhry@pomerium:~$ sudo inxi -M
Machine:
  Type: Desktop Mobo: ASRock model: X570 Phantom Gaming 4
    serial: M80-E4005300804 UEFI: American Megatrends v: P4.00
    date: 04/15/2021
```

**Comment by realKarthikNair** [comment]
- So we dont share the same motherboard
- But the kernel version is same
- Both are using AMD processors

Until some Intel user reports a similar issue, we can assume it's affecting AMD only

**Comment by realKarthikNair** [comment]
@martyfuhry For now you can use [this](https://github.com/DavidS95/Smokeless_UMAF) and turn on modern standby as a dirty fix (modern standby has its own pros and cons over S3 sleep). 

Just follow the below steps except step 8 and 9 

![image](https://github.com/pop-os/pop/assets/78267371/a2f24d0c-7339-4fd9-9596-2b31ad8c8dd5)


Please note that if you are on Windows-Linux dual boot and either of the OSes don't boot after the changes, just revert it to the defaults.

**Comment by martyfuhry** [comment]
Interesting. I don't know where else to start diagnosing, but it's good to see others having a similar issue. Maybe it will be easier to fix if we can coordinate.

What is "modern standby" and how is that working for you? Maybe it's a valid workaround for until this gets fixed. It's very frustrating to walk away from my desk and have to reboot.

**Comment by realKarthikNair** [comment]
> What is "modern standby" 
Google can explain the differences better than me 

> and how is that working for you? 
Modern standby isnt as dependant on low level firmware as S3 sleep since it doesnt put the CPU and other hardware in lowest possible power state (cons being extra power usage in sleep/suspend)
 
> Maybe it's a valid workaround for until this gets fixed. 
Yep. though the change breaks my windows dual boot. I am forced to reset the BIOS to S3 sleep every time before i boot to windows

> It's very frustrating to walk away from my desk and have to reboot.
Trust me it's frustrating to reboot even after being a laptop user

**Comment by realKarthikNair** [comment]
@mmstick sorry to dirturb, but is there any updates?

**Comment by mmstick** [comment]
Nope. Haven't seen any issues here

**Comment by realKarthikNair** [comment]
Thank you.

**Comment by irvj** [comment]
I, too, have been having this issue for the last few weeks. I'm using an HP Dev One, which is a collaboration between HP and System76. I've been looking for a firmware update from HP, but nothing has come up recently.

`cat /etc/os-release`
NAME="Pop!_OS"
VERSION="22.04 LTS"

HP System Firmware:
251985920

`sudo inxi -M`
Machine:
Type: Laptop System: HP product: Dev One Notebook PC v: N/A
serial: XXXXXXXXXX
Mobo: HP model: 8A78 v: KBC Version 01.03 serial: XXXXXXXXXXXXXXX
UEFI: Insyde v: F.05 date: 06/14/2022

**Comment by realKarthikNair** [comment]
```
dmesg | grep 'S3\|suspend'
``` 

after waking from suspend can tell if you're using S3 suspend or not.

**Comment by irvj** [comment]
@realKarthikNair @leviport 

I am using S3 suspend.

```
[603110.904293] PM: suspend entry (deep)
[603110.947004] printk: Suspending console(s) (use no_console_suspend to debug)
[603111.773139] ACPI: PM: Preparing to enter system sleep state S3
[603111.874404] ACPI: PM: Waking up from system sleep state S3
[603112.805413] PM: suspend exit
```

Just to clarify my issue, when I close the lid and put the machine to sleep, if I open it up soon after, it wakes fine. However, if I close the lid and wake it up hours later, very often the lock screen will appear but the time on the screen will be from earlier in the day when I initially put it to sleep. It's frozen and I must force a reboot. This has only been happening for the past few weeks. No changes have been made to the machine, no new software, apart from updates.

When I looked at the logs I didn't see anything helpful, but admittedly I haven't had time recently to really dig into this problem. For now, I've simply disabled suspend on close and I'm just working around it. But @leviport, if you have a Dev One and haven't had any issues, then it's probably a 'me' problem. I'll run some memory tests and maybe just do a fresh install and see if that helps.

**Comment by leviport** [comment]
I also don't spend a lot of time suspended on this machine, since I normally just shut it down all the way. I'll try leaving it suspended more often to see if I can reproduce the same behavior.

**Comment by irvj** [comment]
@leviport @realKarthikNair 

Just updating you both on this. I ran memtest86 (13 tests, 4 passes) and had no errors in my RAM (64GB Crucial CT32G4SFD832A.M16FF). After that, I did a Refresh OS to set up my machine from scratch but keep my user account. Sadly, I'm still getting freezes on lid close/suspend. Just now I opened up my laptop to find it frozen. Below is the syslog from yesterday when I suspended it. When I opened up my machine tonight, it had a black screen for some time, but after I hit a few keys the lock screen came up with yesterday's date at 7:02PM. It was frozen, I had to force a reboot. I guess my next step will be to completely wipe the machine, user account and all, and see what happens then. But again, nothing has really changed with this machine that would have caused this issue other than the standard system updates.

> Aug 18 19:02:23 pop-os ModemManager[1113]: <info>  [sleep-monitor-systemd] system is about to suspend
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.2641] manager: sleep: sleep requested (sleeping: no  enabled: yes)
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.2642] device (p2p-dev-wlo1): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.2645] manager: NetworkManager state is now ASLEEP
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.2646] device (wlo1): state change: activated -> deactivating (reason 'sleeping', sys-iface-state: 'managed')
> Aug 18 19:02:23 pop-os  systemd[1]: Starting Network Manager Script Dispatcher Service...
> Aug 18 19:02:23 pop-os  systemd[1]: Started Network Manager Script Dispatcher Service.
> Aug 18 19:02:23 pop-os  kernel: [32585.417178] wlo1: deauthenticating from 78:45:58:fb:ef:e8 by local choice (Reason: 3=DEAUTH_LEAVING)
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [popx11gestures@system76.com] Extension disabled
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [popx11gestures@system76.com] Building entry point for GNOME Shell 42.5
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [popx11gestures@system76.com] No tracker, skipping
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [VERTICAL-OVERVIEW] resetting overrides
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [VERTICAL-OVERVIEW] disabled
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [popx11gestures@system76.com] Connection with Touchégg daemon lost: null
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: [popx11gestures@system76.com] Connection manually closed, not reconnecting to the daemon
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: wlo1: CTRL-EVENT-DISCONNECTED bssid=78:45:58:fb:ef:e8 reason=3 locally_generated=1
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: wlo1: CTRL-EVENT-DSCP-POLICY clear_all
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.4898] device (wlo1): state change: deactivating -> disconnected (reason 'sleeping', sys-iface-state: 'managed')
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Withdrawing address record for fe80::c15d:165e:b844:da31 on wlo1.
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Leaving mDNS multicast group on interface wlo1.IPv6 with address fe80::c15d:165e:b844:da31.
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Interface wlo1.IPv6 no longer relevant for mDNS.
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.5138] dhcp4 (wlo1): canceled DHCP transaction
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.5138] dhcp4 (wlo1): activation: beginning transaction (timeout in 45 seconds)
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.5138] dhcp4 (wlo1): state changed no lease
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Withdrawing address record for 192.168.1.248 on wlo1.
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Leaving mDNS multicast group on interface wlo1.IPv4 with address 192.168.1.248.
> Aug 18 19:02:23 pop-os  avahi-daemon[1042]: Interface wlo1.IPv4 no longer relevant for mDNS.
> Aug 18 19:02:23 pop-os  systemd-resolved[984]: wlo1: Bus client set default route setting: no
> Aug 18 19:02:23 pop-os  gnome-shell[2440]: An active wireless connection, in infrastructure mode, involves no access point?
> Aug 18 19:02:23 pop-os  systemd-resolved[984]: wlo1: Bus client reset DNS server list.
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.5382] device (wlo1): supplicant interface state: completed -> disconnected
> Aug 18 19:02:23 pop-os  NetworkManager[1038]: <info>  [1692399743.5385] device (wlo1): state change: disconnected -> unmanaged (reason 'sleeping', sys-iface-state: 'managed')
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 52.10.183.132 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 91.189.94.4 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 165.140.142.118 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 45.83.234.123 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 185.125.190.56 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 18.228.202.30 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 91.189.91.157 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 198.137.202.32 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 3.220.42.39 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 15.237.97.214 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 185.125.190.58 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 137.190.2.4 offline
> Aug 18 19:02:23 pop-os  chronyd[1226]: Can't synchronise: no selectable sources
> Aug 18 19:02:23 pop-os  chronyd[1226]: Source 3.134.129.152 offline
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: p2p-dev-wlo1: CTRL-EVENT-DSCP-POLICY clear_all
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: p2p-dev-wlo1: CTRL-EVENT-DSCP-POLICY clear_all
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: nl80211: deinit ifname=p2p-dev-wlo1 disabled_11b_rates=0
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: wlo1: CTRL-EVENT-DSCP-POLICY clear_all
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: wlo1: CTRL-EVENT-DSCP-POLICY clear_all
> Aug 18 19:02:23 pop-os  wpa_supplicant[1085]: nl80211: deinit ifname=wlo1 disabled_11b_rates=0
> Aug 18 19:02:25 pop-os  systemd[1]: systemd-hostnamed.service: Deactivated successfully.
> Aug 18 19:02:27 pop-os  systemd[1]: Reached target Sleep.
> Aug 18 19:02:27 pop-os  systemd[1]: Starting NVIDIA system suspend actions...
> Aug 18 19:02:27 pop-os  suspend: nvidia-suspend.service
> Aug 18 19:02:27 pop-os  logger[78466]: <13>Aug 18 19:02:27 suspend: nvidia-suspend.service
> Aug 18 19:02:27 pop-os  systemd[1]: nvidia-suspend.service: Deactivated successfully.
> Aug 18 19:02:27 pop-os  systemd[1]: Finished NVIDIA system suspend actions.
> Aug 18 19:02:27 pop-os  systemd[1]: Starting System Suspend...
> Aug 18 19:02:28 pop-os  rfkill: block set for type bluetooth
> Aug 18 19:02:28 pop-os  systemd-sleep[78468]: Entering sleep state 'suspend'...
> Aug 18 19:02:28 pop-os  kernel: [32590.178303] PM: suspend entry (deep)
> Aug 18 19:02:28 pop-os  kernel: [32590.189800] Filesystems sync: 0.011 seconds

**Comment by bgrgv** [comment]
Try https://github.com/pop-os/pop/issues/1368#issuecomment-1743780588

**Comment by mikkorantalainen** [comment]
The "modern suspend" (technically called "s2idle" on Linux) is idling in S2 state without turning off the hardware similar to S3. It's much easier to implement for the manufacturers which is why they prefer it. It's totally inferior if you're interested in power usage or extra heat to the components.

A poorly implemented BIOS (that is, nearly every BIOS ever created) can still mess with either suspend. Typically the BIOS wakes up the system way too often from s2idle causing extra battery drain and heat and the S3 causes some of the hardware to be incorrectly restored (e.g. CPU MSR registers are more or less messed up after S3 sleep).

Either complain to BIOS manufacturer or start to write device specific workarounds such as this Intel authored workaround for one specific broken BIOS: https://patchwork.kernel.org/project/linux-pm/patch/6c37c06b6496431d6d82e6d59215eb04edfd9333.1447730578.git.yu.c.chen@intel.com/

**Comment by leviport** [comment]
Well summarized, thank you. I think this can be closed now.
