### ISSUE TITLE
User password entry during install does not follow keyboard map preference

### ISSUE THREAD

**Issue by ariadacapo** [pop-os/pop#308]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 18.04 LTS
 
**Issue/Bug Description:**
During the setup of the first user, the keyboard map selected during the installation process is ignored. Text entry for the user’s name, username, and password, are all done using en_US QUERTY keyboard map.

Once the setup is complete, the first login window asks for the chosen password; there, the entry is made following the user’s chosen a keymap.

**Steps to reproduce:**

Make a fresh install, select a French keyboard map (main difference is keys Q and A are inverted compared to US keyboard). 
Select full disk encryption (watch for issue #120). Reboot at end of installation.
Setup the first user. In the user name, username and password fields, you can observe that the text entry is en_US.

**Comment by mintymac** [comment]
I'm running into a similar issue but with dvorak.  

sudo dpkg-reconfigure keyboard-configuration

When I run this to set my default layout to dvorak, and reboot, password prompts and virual terminals respect it for a short amount of time before qwerty is back.

**Comment by brs17** [comment]
I believe this was recently fixed with https://github.com/pop-os/distinst/pull/120 so I am going to close this issue.
