### ISSUE TITLE
Cannot install Liquorix Zen Kernel

### ISSUE THREAD

**Issue by BarbzYHOOL** [pop-os/pop#3086]
**Distribution (run `cat /etc/os-release`):**
 
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Cannot install Liquorix Zen Kernel

```
The following packages have unmet dependencies:
 libelf-dev : Depends: libelf1 (= 0.186-1build1) but 0.188-1~bpo22.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I have no broken packages, but I encountered this kind of issue like 5 times already on POP OS while it never happened to me in 10 years of using ubuntu or debian, so it's most likely POP OS related

**Steps to reproduce (if you know):**

`curl -s 'https://liquorix.net/install-liquorix.sh' | sudo bash   `

**Expected behavior:**

Should install easily like on every other distribution

**Other Notes:**

**Comment by BarbzYHOOL** [comment]
can i safely revert the jammy-backports thing?

also note that I'm trying to install liquorix ONLY because of this https://github.com/pop-os/pop/issues/3087 ...........

**Comment by mmstick** [comment]
You can disable `jammy-backports` with `repoman`, listed as `Unsupported updates`. Though I'm not sure that will fix the dependency conflict you see here. Liquorix also won't help you with suspend issues.

If you haven't updated the system in a long time, then it might be difficult to narrow down a precise update. You can install older kernels from https://kernel.ubuntu.com/~kernel-ppa/mainline/, or get older linux-firmware packages from https://launchpad.net/ubuntu/jammy/+source/linux-firmware. You can see our changelogs at https://github.com/pop-os/repo-release/commits/master

**Comment by BarbzYHOOL** [comment]
some dudes on the net said so about liquorix fixing this issue

yeah i had not updated for a long time (because of fear of getting something not working anymore.................) i don't know how to switch a kernel and stuff yet, i have never done it, is it easy on POP OS??? i don't see anything when I boot up to switch the kernel
