### ISSUE TITLE
Installer advanced option fails

### ISSUE THREAD

**Issue by loxK** [pop-os/pop#309]
I am trying popos. I downloaded the 18.04 intel iso image.

The advanced installation mode fails when validating the partitions setup. 
It fails unmounting /cdrom

**Comment by brs17** [comment]
I believe there was an issue with unmounting that we have since patched. Can you try running `sudo apt update && sudo apt upgrade` and then relaunching the installer?

**Comment by brs17** [comment]
This issue should be fixed with the latest .iso.
