### ISSUE TITLE
`pop-desktop` update wants to remove `sddm`

### ISSUE THREAD

**Issue by mpartel** [pop-os/pop#3090]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

    pop-desktop:
      Installed: 1.6.0~1684785543~22.04~cadfc39
      Candidate: 2.0.0~1690385575~22.04~191b519
      Version table:
         2.0.0~1690385575~22.04~191b519 1001
           1001 http://apt.pop-os.org/release jammy/main amd64 Packages
     *** 1.6.0~1684785543~22.04~cadfc39 100
            100 /var/lib/dpkg/status

**Issue/Bug Description:**

IIRC I previously installed KDE as instructed [here](https://support.system76.com/articles/desktop-environment/), except I chose `sddm` and that has worked fine so far. The proposed update to `pop-desktop` seems to want to uninstall `sddm` i.e. KDE's login manager. That seems bad.

    $ apt-get dist-upgrade
    # ...
    The following packages will be REMOVED:
      desktop-base sddm sddm-theme-debian-maui
    The following NEW packages will be installed:
      pop-de-gnome
    The following packages will be upgraded:
      pop-desktop

**Steps to reproduce (if you know):**

Not sure how now that the update is out.

**Expected behavior:**

A non-major update should probably not affect the login manager, unless you've decided that sddm is explicitly unsupported.

**Comment by mmstick** [comment]
Fixed by https://github.com/pop-os/desktop/pull/120

**Comment by mpartel** [comment]
Thanks!
