### ISSUE TITLE
Realtek Ethernet Unstable After 6.4.6 Upgrade

### ISSUE THREAD

**Issue by PHY1643** [pop-os/pop#3097]
**Distribution:**
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version:**
Unknown

**Issue/Bug Description:**
Since upgrading to Kernel 6.4.6-76060406-generic, my ethernet connection will drop after a few minutes of uptime. Though the GNOME system settings indicates the link is active, there is no connectivity. (Cannot even contact the router.) Rebooting resolves the issue, but again, only for a few minutes. When connecting via Wi-Fi instead, the network connection is stable and functional. Other devices (e.g., Steam Deck), when connected to the same router via ethernet, do not exhibit this issue. Under the previous kernel version, 6.4.2, this issue did not occur.

**Steps to reproduce (if you know):**
Installed kernel 6.4.6-76060406-generic via apt; unexpected ethernet behavior began within minutes thereafter.

**Expected behavior:**
The network connection over ethernet should be stable.

**Other Notes:**
I did a bit of digging online and found [this](https://bugzilla.kernel.org/show_bug.cgi?id=217596), which may or may not be related.

**Comment by jacobgkau** [comment]
We had a user (`@jdmunoz`) in Mattermost discover a workaround for this issue (I have not personally tested this): https://chat.pop-os.org/pop-os/pl/a5p3h9wq7jd79q9nop85dmqkaa 

> I changed
> the kerne driver from r8169 to r8168 and that fixed the problem I would leave here the step by step, so any one could do it
> step by step via terminal 
> ```
> sudo apt-get autoremove
> sudo dpkg --configure -a
> sudo apt-get install -f
> sudo apt remove rtl8821ce-dkms
> git clone https://github.com/tomaspinho/rtl8821ce
> cd rtl8821ce
> chmod +x dkms-install.sh
> chmod +x dkms-remove.sh
> make
> sudo make install
> sudo ./dkms-install.sh
> ```
> then restart the pc 
> I found this fix in https://askubuntu.com/questions/1326359/im-getting-installed-rtl8821ce-dkms-package-post-installation-script-subproces

**Comment by SOLsensei** [comment]
I am pretty sure the above solution is not going to work in this case since the driver provided in the link is the wireless driver and we are experiencing issues with the ethernet driver.

**Comment by jacobgkau** [comment]
> I am pretty sure the above solution is not going to work in this case since the driver provided in the link is the wireless driver and we are experiencing issues with the ethernet driver.

Ah, you're correct about the link/commands being for the wrong NIC-- the rtl8821 in particular looks to be a wireless card. Like I said, I didn't test the solution (no System76 hardware models are having this issue, so I don't have any affected hardware to test it on), I was just passing it along from a Mattermost user who claimed that fixed his Ethernet on a Lenovo IdeaPad L340.

The `r8168-dkms` package in the Ubuntu repository may provide the r8168 driver that user claimed was working for him (DKMS packages don't always build on updated kernel versions, though.)

**Comment by PHY1643** [comment]
According to **[this bugzilla.org post](https://bugzilla.kernel.org/show_bug.cgi?id=217596#c55)**, the problem has been resolved as of kernel 6.4.8. I reckon I'll close this issue for now, since I figure the 6.4.8 version will eventually be in the Pop! repositories. Thanks!

**Comment by PHY1643** [comment]
Just an FYI to follow-up: With the kernel v 6.4.6 update that I downloaded this morning (Sept. 1, 2023), the above issue seems to have been resolved for me. Thanks again!

**Comment by PHY1643** [comment]
I updated to v6.5.4 earlier this morning (2023-OCT-07). Current uptime since that update is ~45 min; no issues so far. I'll report back if things go sour again.
