### ISSUE TITLE
Progress buttons do not (foreign language)translate properly during installation

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#31]
_From @brs17 on October 10, 2017 22:6_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
BUILD = 31 (noNVIDIA)

**Issue/Bug Description**
Certain Languages can be selected but the "Back" and "Quit" buttons do not translate. Such languages are highlighted in the screenshots attached.

![a-esperanto_done](https://user-images.githubusercontent.com/7460774/31412824-d85f3f6e-add3-11e7-9a4e-7f2029084856.png)

![euskara-nederlands_done](https://user-images.githubusercontent.com/7460774/31412822-d83a94e8-add3-11e7-9ae2-043abd41b186.png)

![norskbokmal-svenska_done](https://user-images.githubusercontent.com/7460774/31412821-d8249f08-add3-11e7-930f-37365866999b.png)

![tagalog-ykpaihcbka_done](https://user-images.githubusercontent.com/7460774/31412820-d813f23e-add3-11e7-86fe-769e8626849b.png)

![russian-sevenbelowhebrew_done](https://user-images.githubusercontent.com/7460774/31412819-d7ff6300-add3-11e7-9b98-26888a6a149d.png)

![next_done](https://user-images.githubusercontent.com/7460774/31412818-d7edfa2a-add3-11e7-83ac-9e7a87e7caf6.png)

![last_done](https://user-images.githubusercontent.com/7460774/31412817-d7d94bfc-add3-11e7-8db1-00339854bcff.png)

Screenshot of "Back" and "Quit" button that are not translated.

![full_example](https://user-images.githubusercontent.com/7460774/31412860-f5261fd2-add3-11e7-83f9-3831c07e6115.png)

**Steps to reproduce (if you know)**
Reproduces on every install

**Expected behaviour**
Specified language should be displayed on all buttons and headers.

**Other Notes**
Provided screenshots because I am unsure of all of the languages with issues.

_Copied from original issue: pop-os/iso#133_

**Comment by isantop** [comment]
_From @jackpot51 on October 10, 2017 22:28_

Making notes - the two missing language fonts - the ones that show hex escape codes - are `font-knda` and `font-telu`

**Comment by isantop** [comment]
_From @brs17 on October 10, 2017 22:42_

@jackpot51 is referring to to #134

**Comment by WatchMkr** [comment]
We're developing a new installer and won't be working on Ubiquity bug fixes. Please file this bug against Ubiquity here: https://bugs.launchpad.net/ubuntu/+source/ubiquity
