### ISSUE TITLE
Fresh install: not booting because of secure boot invalid signature

### ISSUE THREAD

**Issue by loxK** [pop-os/pop#310]
PopOS Intel 18.04
ASUS laptop

I tried a few fresh installs (erasing all drive). Each time the computer won't boot in secure boot mode because of invalid signature. 

The /boot/efi exists and contains systemd and popos related files.

**Comment by coolpolygons** [comment]
You will have to disable secure boot in your BIOS. It is annoying to dual boot windows with a linux distro at this point :P

**Comment by loxK** [comment]
Well I went for Ubuntu which handles it nicely.

**Comment by rohitghali** [comment]
So, I can't use pop os with Windows 10 now? I'm having the same problem. Latest iso. Secure boot failure. Ubuntu runs fine.

**Comment by Goddard** [comment]
Having this issue when trying to boot off usb to do a fresh install.
