### ISSUE TITLE
(initramfs) unable to find a live medium containing a live file system

### ISSUE THREAD

**Issue by NoskcajXela** [pop-os/pop#312]
**Distribution (run `cat /etc/os-release`):**
 latest (as of writing)
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
None (maybe BusyBox or initramfs)

**Issue/Bug Description:**
Cannot install PopOS:
Followed steps to create boot USB (multiple [Etcher.io and Rufus])
Boots to intialization, get stuck after loading keyboard, boots BusyBox and subsequently initramfs tells me "unable to find a live medium containing a live file system" (yes, I've tried switching to USB 2)

**Steps to reproduce (if you know):**
Unknown

**Expected behavior:**
Get to beautiful installation wizard and install

**Other Notes:**
Intel Core i-5 6600K
AMD Radeon R9 390
16GB RAM
MSI Gaming M-5 z-170
G Skill keyboard
Trying to install to bear hdd
Have Windows 10 and another 6 TB drive
Boot USB is USB 3.0
(Don't know if some of those matter but I'll include it anyways)

**Comment by brs17** [comment]
Are you using the intel iso? Are you able to boot off of this flashdrive from another machine (you don't need to install, just curious if it works anywhere)?

**Comment by NoskcajXela** [comment]
I never figured out what the problem was, however I tried another time in a
different situation and it worked. I guess that's all that matters. Thanks
for your help though!
