### ISSUE TITLE
Broken CH341 usb to serial module

### ISSUE THREAD

**Issue by david0rk** [pop-os/pop#3125]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
 
6.4.6-76060406-generic #202307241739~1690928105~22.04~d567a38 SMP PREEMPT_DYNAMIC Tue A x86_64 x86_64 x86_64 GNU/Linux

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Kernel-generic

**Issue/Bug Description:**
Was attempting to fire up chirp to program a radio, my usb to serial converter isn't showing up. 

device info 
Bus 001 Device 010: ID 1a86:7523 QinHeng Electronics CH340 serial converter

dmesg after plugging device in: 
[ 3058.444808] usb 1-2: new full-speed USB device number 11 using xhci_hcd
[ 3058.593723] usb 1-2: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.64
[ 3058.593752] usb 1-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 3058.593765] usb 1-2: Product: USB Serial
[ 3059.230799] BPF: 	 type_id=3 bitfield_size=0 bits_offset=256
[ 3059.230807] BPF:  
[ 3059.230810] BPF: Invalid name
[ 3059.230813] BPF: 
[ 3059.230816] failed to validate module [usbserial] BTF: -22

Attempting to manually  insmod the driver for the device: 

$ sudo insmod /usr/lib/modules/6.4.6-76060406-generic/kernel/drivers/usb/serial/ch341.ko
insmod: ERROR: could not insert module /usr/lib/modules/6.4.6-76060406-generic/kernel/drivers/usb/serial/ch341.ko: Unknown symbol in module

dmesg after failed insmod attempt
[ 3174.737277] usb 1-2: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[ 3174.737285] usb 1-2: Product: USB Serial
[ 3175.389774] BPF: 	 type_id=3 bitfield_size=0 bits_offset=256
[ 3175.389783] BPF:  
[ 3175.389786] BPF: Invalid name
[ 3175.389788] BPF: 
[ 3175.389792] failed to validate module [usbserial] BTF: -22
[ 3178.403528] ch341: Unknown symbol usb_serial_generic_open (err -2)
[ 3178.403567] ch341: Unknown symbol usb_serial_generic_close (err -2)
[ 3178.403602] ch341: Unknown symbol usb_serial_handle_dcd_change (err -2)
[ 3178.403637] ch341: Unknown symbol usb_serial_generic_resume (err -2)
[ 3178.403667] ch341: Unknown symbol usb_serial_deregister_drivers (err -2)
[ 3178.403703] ch341: Unknown symbol usb_serial_generic_tiocmiwait (err -2)
[ 3178.403738] ch341: Unknown symbol usb_serial_register_drivers (err -2)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jackpot51** [comment]
Have you tried rebooting?

**Comment by david0rk** [comment]
🙄 Yep, fixed it.   My bad!

**Comment by JaggedJax** [comment]
Thank you so much (from the future). I was checking my pins and measuring voltage and bashing my head before finding this post.
