### ISSUE TITLE
Unity-like layout (or Ubuntu MATE's Munity layout) for pop_os

### ISSUE THREAD

**Issue by coolpolygons** [pop-os/pop#313]
I think it would be great if pop os has a Unity-like layout for the desktop environment. 

- Top menu bar, that shows the menu bar of the current application, like in macOS
- Launcher for favorite apps
- Dash

Something like that. If someone can tell me the file in the pop_os source code that controls the UI, I will experiment with it myself.

Thank you :D

**Comment by brs17** [comment]
@coolpolygons You're welcome to try out/add whichever desktop environments and extensions that please you. 

Normally to install a desktop environment all that needs to be done is `sudo apt install <desktopenvironment>` and then select that desktop environment on the login page (there is a small gear that will let you select a desktop environment). You can find a list (although not a complete list) here: https://wiki.archlinux.org/index.php/Desktop_environment

If you stick with Gnome, there is a popular gnome extension, dash-to-dock: https://extensions.gnome.org/extension/307/dash-to-dock/
Installing the dock should be as easy as selecting `click here to install browser extension` and installing when prompted. Once that is done just toggle the off switch(to on) on the dash to dock page (or use these instructions: https://support.system76.com/articles/dash-to-dock/).

**Comment by purpleraven** [comment]
+1
pixel saver and some extension for status icons can be enabled by default
