### ISSUE TITLE
Evince (PDF Viewer) can't open a PDF file from a browser

### ISSUE THREAD

**Issue by zvirdaniel** [pop-os/pop#314]
Hi.

Recently, I've switched from elementaryOS to Pop!_OS, and so far the experience has been fantastic.

But, when I tried opening a PDF file from my browser, Evince gave me the following error:
![evince](https://user-images.githubusercontent.com/22638510/42168371-14185eec-7e11-11e8-8f36-53624e19cd1e.png)

Which can be translated as:
`Can't open the file *filename*. Failed to load backend for 'application/pdf': libnss3.so: mapping segment from the shared object has failed`

I'm running Pop!_OS 18.04 LTS on my Lenovo Yoga 500-14IHW. Evince version is 3.28.2-1, reinstalling it did not help. Libnss3 package is installed.

What should I do?

**EDIT:** This issue occurs only when opening the file directly from the browser (Firefox Developer Edition). Opening the file from the file manager works correctly

**Comment by brs17** [comment]
@zvirdaniel Have you tried opening any other pdfs? Can you try that and let us know if another file works?

**Comment by zvirdaniel** [comment]
I have tried opening a different pdf, same issue. Does not work when opening from a browser, does work when opening from files/terminal.

**Comment by brs17** [comment]
What do you mean exactly by opening a pdf from browser? Which browser are you using?

**Comment by zvirdaniel** [comment]
I'm using Firefox Developer Edition. I download a PDF file, and try to open it (Firefox is set to open all files in default pdf viewer). That gave me the error.
Do you think it's a browser issue?

**Comment by zvirdaniel** [comment]
It's related only to the Firefox Developer Edition. Chromium does not have this issue.

**Comment by brs17** [comment]
Perhaps try and give a different version of Firefox a shot?

**Comment by zvirdaniel** [comment]
I tried Firefox from the Pop!_OS shop, and it worked correctly. So this is specific to Firefox Developer Edition. 

Thank you, closing the issue.

**Comment by brs17** [comment]
@zvirdaniel Glad you were able to narrow the issue down. I would encourage you to file an issue with Mozilla so that this issue can be resolved!
