### ISSUE TITLE
Random freezes - i915 flip_done - kerenl 6.2.0 and newer

### ISSUE THREAD

**Issue by Guyv-dev** [pop-os/pop#3140]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**
My screen got random freezes, the cursor and the audio kept working for a couple of seconds, but I couldn't click on anything. That's happening with every kernel newer than 6.2.0. 
I should mention that I am using two screens (one of them connected with Thunderbolt 4).

On the time of the freezes i got from journalctl this errors: 

> i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out
> i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
> i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] commit wait timed out
> i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out

**Comment by leviport** [comment]
We believe we have found the culprit, and we will be pushing an update to resolve this soon.

**Comment by AMoonRabbit** [comment]
I am seeing this again on latest kernels. Same errors as above, difference is that this is only on shutdown, with a USB-C to HDMI adaptor (Framework hardware). 
```
i915 0000:00:02.0: [drm] *ERROR* [CRTC:80:pipe A] flip_done timed out
i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] flip_done timed out
i915 0000:00:02.0: [drm] *ERROR* flip_done timed out
i915 0000:00:02.0: [drm] *ERROR* [CRTC:80:pipe A] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [CRTC:131:pipe B] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [CONNECTOR:236:eDP-1] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [CONNECTOR:258:DP-2] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [PLANE:31:plane 1A] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [PLANE:82:plane 1B] commit wait timed out
i915 0000:00:02.0: [drm] *ERROR* [ENCODER:235:DDI A/PHY A] PPS 0 panel status timeout: PP_STATUS: 0x80000008 PP_CONTROL: 0x80000867
```
