### ISSUE TITLE
NVIDIA driver `nvidia-driver-525-server` won't load on kernel 6.5.4

### ISSUE THREAD

**Issue by JanPokorny** [pop-os/pop#3147]
**Distribution (run `cat /etc/os-release`):**

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
nvidia-driver-525-server:
  Installed: 525.125.06-0ubuntu0.22.04.1
  Candidate: 525.125.06-0ubuntu0.22.04.1
  Version table:
 *** 525.125.06-0ubuntu0.22.04.1 500
        500 http://apt.pop-os.org/ubuntu jammy-security/restricted amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy-updates/restricted amd64 Packages
        100 /var/lib/dpkg/status

linux-generic:
  Installed: 6.5.4.76060504.202309191142~1695998943~22.04~070916d
  Candidate: 6.5.4.76060504.202309191142~1695998943~22.04~070916d
  Version table:
 *** 6.5.4.76060504.202309191142~1695998943~22.04~070916d 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     5.15.0.86.83 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     5.15.0.84.81 500
        500 http://apt.pop-os.org/ubuntu jammy-security/main amd64 Packages
     5.15.0.25.27 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

> [!NOTE]  
> I had to downgrade the NVIDIA driver to version 525 due to this issue: https://github.com/pop-os/pop/issues/3088

`nvidia-smi` output for kernel `6.4.6`:

```
Wed Oct  4 11:02:31 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:26:00.0  On |                  N/A |
| 17%   41C    P5    35W / 175W |    584MiB /  8192MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1245      G   /usr/lib/xorg/Xorg                235MiB |
|    0   N/A  N/A      1558      G   /usr/bin/gnome-shell              183MiB |
|    0   N/A  N/A      4192      G   x-terminal-emulator                 9MiB |
|    0   N/A  N/A      7291      G   firefox                           144MiB |
|    0   N/A  N/A     12811      G   x-terminal-emulator                 8MiB |
+-----------------------------------------------------------------------------+
```

`nvidia-smi` output for kernel `6.5.4`:

```
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

**Issue/Bug Description:**

Yesterday, my kernel updated from `6.4.6.76060406.202307241739~1695312586~22.04~4d8f3e9` to `6.5.4.76060504.202309191142~1695998943~22.04~070916d`. After this, when booting with the new kernel, the screen resolution is stuck on `1024x768` and `nvidia-smi` outputs `NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.`.

I can boot by selecting the `oldkern` option in the bootloader and then everything works fine.

**Steps to reproduce (if you know):**

- GPU: NVIDIA RTX 2070
- Monitor: Samsung CRG9 (5120x1440)
- Driver: `nvidia-driver-525-server`
- Kernel: `6.5.4.76060504.202309191142~1695998943~22.04~070916d`

After booting, the resolution is stuck at 1024x768 with no other options in the picker. `nvidia-smi` says the driver did not load.

**Expected behavior:**

The driver should load.

**Other Notes:**

I would appreciate if anyone could help me with removing the offending new kernel and locking the kernel version until this is resolved -- I disabled automatic updates for now, so the old kernel stays with me, but I'd sleep better with a more permanent solution.

**Comment by mmstick** [comment]
We don't support this package. You must use one of the drivers that we package. The server packages are explicitly removed from the Pop Shop's drivers page for this reason.

**Comment by JanPokorny** [comment]
@mmstick Oh, it comes from `apt.pop-os.org`, does that not mean it is official? PopShop shows me only v470 and v535, do I understand correctly that there is no official way to stay on 525 and thus not suffer from #3088?

**Comment by mmstick** [comment]
All packages come from apt.pop-os.org, but there are multiple repositories on that server, and one of them is a mirror of the Ubuntu repositories. This package is packaged by Ubuntu for Ubuntu, and is not compatible with our kernels.
