### ISSUE TITLE
REALLY REALLY weird behavior of Git on PopOS...

### ISSUE THREAD

**Issue by liar666** [pop-os/pop#3155]
**(1) Issue/Bug Description:**

I'll try to summarize a REALLY REALLY weird behavior I got with Git on PopOS:

* Years ago, I had a repo with my linux config files on GitHub 
* At that time free repos@GH were public :(
* Thus, 4/5 years ago, I "transferred" this repo to GitLab and made it private
    * Transferred = [if I recall correctly] I changed the remote on my local copy and pushed it to a freshly created "empty" repo on GitLab
* On my personal machine (latest Linux Mint) and on my work machine (Ubuntu 22.04), when I clone the repo I see my latest files and a recent history (`git log`)  (2020 -> 2023).
    *  That's the history I see on the Web interface of GitLab
* On a third machine where I installed PopOS, when I clone the repo, I find myself with my files from the old GitHub repo, with the history (`git log`) of that time (2013->2019).
   * That's the history I see on GitHub's web interface.

More information:
* I have purged Git on PopOS and reinstalled it => same result
* `git branch -a` returns EXACTLY the same thing ON THE 3 MACHINES:
```
$ git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
```
* Git version returns EXACTLY the same thing on ALL 3 MACHINES:
```git version 2.34.1```
* I've searched for references to the string "github" inside the `repos/.git` and found nothing.
* I'm starting to think I'm crazy, so I asked a friend for help: we tried to `git clone` the same repo on his machine (a 4th machine, running Ubuntu) through `https://` and I got the correct (latest/GitLab) content.

So it seems only PopOS manages to get the old content, when cloning the new repo and using the same Git version...

**(2) Steps to reproduce (if you know):**

For sure, it works with my repo. I'm not sure if it is possible to reproduce on another repo... But the steps would be those explained above :
* @Ubuntu/Mint create a repo on GH
* create some history there
* switch the remote on your local machine
* push to fresh new GitLab repo
* create some history there.
* @PopOS Clone the repo and see the old history?

The repo is quite private, but I can eventually provide access to it to those that would like to have an eye on this very strange problem.

**(3) Expected behavior:**

Git clone on Ubuntu/Mint/PopOs, particularly with the exact same version number, should have the exact same behavior, even with a repo with a strange history.

**(4) Distribution (run `cat /etc/os-release`):**
 
PopOS 22.04

**Comment by mmstick** [comment]
We do not make any changes to git. It is the same package directly mirrored from the Ubuntu repositoriy.

**Comment by ids1024** [comment]
What about `git remote show origin`? Any difference in the output of that?

**Comment by leorochael** [comment]
Or perhaps check `git remote get-url origin` in all machines.

This is to double check you're actually pulling the commits from the right repository.

**Comment by jacobgkau** [comment]
@liar666 Any additional information regarding this issue?

**Comment by jacobgkau** [comment]
Since we haven't heard back and we're not doing anything out of the ordinary with git, I'm closing this issue. Please feel free to comment again if you have more information to provide.
