### ISSUE TITLE
Display corruption on AMD gpu notebook for lower than maximum resolution

### ISSUE THREAD

**Issue by leorochael** [pop-os/pop#3157]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
linux-image-6.5.4-76060504-generic:
  Installed: 6.5.4-76060504.202309191142~1695998943~22.04~070916d
  Candidate: 6.5.4-76060504.202309191142~1695998943~22.04~070916d
  Version table:
 *** 6.5.4-76060504.202309191142~1695998943~22.04~070916d 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

On a notebook with this hardware:

```
CPU: AMD Ryzen 7 PRO 5850U with Radeon Graphics
GPU: [AMD/ATI] Cezanne [1002:1638] (rev d1)
```

As well as on other amdgpu driven systems, selecting a lower than maximum resolutions on eDP panels causes severe screen corruption, as specified in this amd kernel driver repository issue:

https://gitlab.freedesktop.org/drm/amd/-/issues/2693

The issue has been solved on kernel version 6.5.6 and above (i.e. 6.5.7 as well at the time of this posting).

**Steps to reproduce (if you know):**

* Open the `Display` in the Settings app
* Select a lower than maximum resolution for the internal display
* watch the fireworks (see screenshots in the linked amd issue above).

**Expected behavior:**

* Lower resolutions can be selected without issues.

**Other Notes:**

As mentioned, issue is fixed on linux kernel 6.5.6 and above.

**Comment by leorochael** [comment]
This issue is particularly problematic when connecting multiple screens if the eDP screen cannot be dialed down to a lower resolution, since using scaling to reduce the resolution of only the eDP screen and not the other displays requires using fractional scaling, which causes issues with multiple monitors, like:

* mouse pointer flickering
* reduced performance
* difference in mouse speed when crossing between displays with different scaling settings.

**Comment by leviport** [comment]
Sounds like a duplicate of https://github.com/pop-os/linux/issues/286

**Comment by leorochael** [comment]
@leviport indeed! Closing this one for that other.
