### ISSUE TITLE
Any app don't working on pop_os! 22.04 LTS, because of python?

### ISSUE THREAD

**Issue by Veras-D** [pop-os/pop#3159]
**Distribution:**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

### Variety
variety:
  Instalado: 0.8.5-2
  Candidato: 0.8.5-2
  Tabela de versão:
 *** 0.8.5-2 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages
        100 /var/lib/dpkg/status

### Ice:
ice:
  Instalado: 5.3.0
  Candidato: 5.3.0
  Tabela de versão:
 *** 5.3.0 100
        100 /var/lib/dpkg/status

### Web manager:
webapp-manager:
  Instalado: 1.1.5
  Candidato: 1.1.5
  Tabela de versão:
 *** 1.1.5 100
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

### Variety
Traceback (most recent call last):
  File "/usr/bin/variety", line 64, in <module>
    import variety  # isort:skip
  File "/usr/lib/python3/dist-packages/variety/__init__.py", line 62, in <module>
    from variety import VarietyWindow, ThumbsManager, ThumbsWindow
  File "/usr/lib/python3/dist-packages/variety/VarietyWindow.py", line 34, in <module>
    from variety import indicator
  File "/usr/lib/python3/dist-packages/variety/indicator.py", line 24, in <module>
    from variety.Util import Util, _
  File "/usr/lib/python3/dist-packages/variety/Util.py", line 37, in <module>
    import requests
  File "/home/veras/.local/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/response.py", line 5, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### Ice
Traceback (most recent call last):
  File "/usr/bin/ice", line 18, in <module>
    import requests
  File "/home/veras/.local/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/response.py", line 5, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### webapp-manager
Traceback (most recent call last):
  File "/usr/lib/webapp-manager/webapp-manager.py", line 10, in <module>
    import tldextract
  File "/usr/lib/python3/dist-packages/tldextract/__init__.py", line 3, in <module>
    from .tldextract import extract, TLDExtract
  File "/usr/lib/python3/dist-packages/tldextract/tldextract.py", line 61, in <module>
    from .suffix_list import get_suffix_lists
  File "/usr/lib/python3/dist-packages/tldextract/suffix_list.py", line 7, in <module>
    import requests
  File "/home/veras/.local/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/response.py", line 5, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/veras/.local/lib/python3.10/site-packages/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Steps to reproduce (if you know):**

Just try opening the program or calling in the terminal

**Expected behavior:**
Open

**Other Notes:**
Obs: I gathered them all here because they all give a problem related to Python

## Python version
Python 3.10.12

## pip list
| Package                  | Version    |
|--------------------------|------------|
| aiohttp                  | 3.8.4      |
| aiosignal                | 1.3.1      |
| appdirs                  | 1.4.4      |
| argcomplete              | 3.1.1      |
| async-timeout            | 4.0.2      |
| attrs                    | 21.2.0     |
| autokey                  | 0.95.10    |
| backcall                 | 0.2.0      |
| bcc                      | 0.18.0     |
| beautifulsoup4           | 4.10.0     |
| beniget                  | 0.4.1      |
| blinker                  | 1.4        |
| Brlapi                   | 0.8.3      |
| Brotli                   | 1.0.9      |
| bs4                      | 0.0.1      |
| build                    | 1.0.3      |
| cachetools               | 5.3.1      |
| cefpython3               | 66.0       |
| certifi                  | 2023.7.22  |
| chardet                  | 4.0.0      |
| charset-normalizer       | 3.2.0      |
| chrome-gnome-shell       | 0.0.0      |
| click                    | 8.0.3      |
| colorama                 | 0.4.4      |
| command-not-found        | 0.3        |
| commonmark               | 0.9.1      |
| configobj                | 5.0.6      |
| contourpy                | 1.1.0      |
| cryptography             | 3.4.8      |
| cupshelpers              | 1.0        |
| cvxpy                    | 1.3.2      |
| cycler                   | 0.11.0     |
| dbus-python              | 1.2.18     |
| decorator                | 4.4.2      |
| defer                    | 1.0.6      |
| deprecation              | 2.1.0      |
| discovery                | 0.0.4      |
| distro                   | 1.7.0      |
| ecos                     | 2.0.12     |
| entrypoints              | 0.4        |
| filelock                 | 3.6.0      |
| fonttools                | 4.40.0     |
| frozenlist               | 1.3.3      |
| fs                       | 2.4.12     |
| gast                     | 0.5.2      |
| google-api-core          | 2.11.1     |
| google-api-python-client | 2.99.0     |
| google-auth              | 2.23.0     |
| google-auth-httplib2     | 0.1.1      |
| googleapis-common-protos | 1.60.0     |
| gyp                      | 0.1        |
| hidpidaemon              | 18.4.6     |
| html5lib                 | 1.1        |
| httplib2                 | 0.22.0     |
| idna                     | 3.4        |
| importlib-metadata       | 4.6.4      |
| install                  | 1.3.5      |
| ipykernel                | 6.7.0      |
| ipython                  | 7.31.1     |
| ipython_genutils         | 0.2.0      |
| jedi                     | 0.18.0     |
| jeepney                  | 0.7.1      |
| jupyter-client           | 7.1.2      |
| jupyter-core             | 4.9.1      |
| kernelstub               | 3.1.4      |
| keyring                  | 23.5.0     |
| kiwisolver               | 1.4.4      |
| language-selector        | 0.1        |
| launchpadlib             | 1.10.16    |
| lazr.restfulclient       | 0.14.4     |
| lazr.uri                 | 1.0.6      |
| louis                    | 3.20.0     |
| lxml                     | 4.8.0      |
| lz4                      | 3.1.3+dfsg |
| macaroonbakery           | 1.3.1      |
| mapping                  | 0.1.6      |
| matplotlib               | 3.7.1      |
| matplotlib-inline        | 0.1.3      |
| mock                     | 4.0.3      |
| more-itertools           | 8.10.0     |
| mpmath                   | 0.0.0      |
| multidict                | 6.0.4      |
| mutagen                  | 1.45.1     |
| nest-asyncio             | 1.5.4      |
| netaddr                  | 0.8.0      |
| netifaces                | 0.11.0     |
| nidaqmx                  | 0.8.0      |
| numpy                    | 1.26.0     |
| oauthlib                 | 3.2.0      |
| olefile                  | 0.46       |
| openai                   | 0.27.8     |
| osqp                     | 0.6.3      |
| packaging                | 23.1       |
| pandas                   | 2.0.3      |
| parso                    | 0.8.1      |
| pbr                      | 5.8.0      |
| pexpect                  | 4.8.0      |
| pickleshare              | 0.7.5      |
| Pillow                   | 10.0.1     |
| pip                      | 22.0.2     |
| pipx                     | 1.2.0      |
| ply                      | 3.11       |
| pop-transition           | 1.1.2      |
| powerline-status         | 2.8.2      |
| prompt-toolkit           | 3.0.28     |
| protobuf                 | 4.24.3     |
| psutil                   | 5.9.0      |
| ptyprocess               | 0.7.0      |
| py                       | 1.10.0     |
| pyasn1                   | 0.5.0      |
| pyasn1-modules           | 0.3.0      |
| pycairo                  | 1.20.1     |
| pycryptodomex            | 3.11.0     |
| pycups                   | 2.0.1      |
| pydbus                   | 0.6.0      |
| pygame                   | 2.5.2      |
| Pygments                 | 2.11.2     |
| PyGObject                | 3.42.1     |
| pyinotify                | 0.9.6      |
| PyJWT                    | 2.3.0      |
| pymacaroons              | 0.13.0     |
| PyMuPDF                  | 1.23.0     |
| PyMuPDFb                 | 1.23.0     |
| PyNaCl                   | 1.5.0      |
| pyparsing                | 3.1.1      |
| pyperclip                | 1.8.2      |
| pyproject_hooks          | 1.0.0      |
| PyQt5                    | 5.15.6     |
| PyQt5-sip                | 12.9.1     |
| PyQtWebEngine            | 5.15.5     |
| pyRFC3339                | 1.1        |
| PySimpleGUI              | 4.60.5     |
| python-apt               | 2.4.0+ubuntu2 |
| python-dateutil          | 2.8.2      |
| python-debian            | 0.1.43+ubuntu1.1 |
| python-gnupg             | 0.4.8      |
| python-xlib              | 0.29       |
| pythran                  | 0.10.0     |
| pytz                     | 2023.3     |
| pyxattr                  | 0.7.2      |
| pyxdg                    | 0.27       |
| PyYAML                   | 5.4.1      |
| pyzmq                    | 22.3.0     |
| qdldl                    | 0.1.7.post0 |
| qtconsole                | 5.2.2      |
| QtPy                     | 2.0.0      |
| repolib                  | 2.2.1      |
| repoman                  | 1.4.0      |
| requests                 | 2.31.0     |
| requests-file            | 1.5.1      |
| rich                     | 12.6.0     |
| rsa                      | 4.9        |
| scipy                    | 1.8.0      |
| screen-resolution-extra  | 0.0.0      |
| scs                      | 3.2.3      |
| SecretStorage            | 3.3.1      |
| sessioninstaller         | 0.0.0      |
| setproctitle             | 1.2.2      |
| setuptools               | 68.2.2     |
| shell-genie              | 0.2.10     |
| shellingham              | 1.5.0.post1 |
| six                      | 1.16.0     |
| soupsieve                | 2.3.1      |
| sympy                    | 1.9        |
| systemd-python           | 234        |
| tldextract               | 3.1.2      |
| tomli                    | 2.0.1      |
| tornado                  | 6.1        |
| tqdm                     | 4.65.0     |
| traitlets                | 5.1.1      |
| typer                    | 0.7.0      |
| tzdata                   | 2023.3     |
| ubuntu-advantage-tools   | 8001       |
| ubuntu-drivers-common    | 0.0.0      |
| ufoLib2                  | 0.13.1     |
| ufw                      | 0.36.1     |
| unicodedata2             | 14.0.0     |
| uritemplate              | 4.1.1      |
| urllib3                  | 1.26.16    |
| userpath                 | 1.8.0      |
| variety                  | 0.8.5      |
| wadllib                  | 1.3.6      |
| wcwidth                  | 0.2.5      |
| webencodings             | 0.5.1      |
| websockets               | 9.1        |
| wheel                    | 0.37.1     |
| xdg                      | 5          |
| xkit                     | 0.0.0      |
| yarl                     | 1.9.2      |
| youtube-dl               | 2021.12.17 |
| youtube-dlc              | 2020.11.11.post3 |
| yt-dlp                   | 2022.4.8   |
| zipp                     | 1.0.0      |

**Comment by leorochael** [comment]
From this section of the traceback:

```
File "/usr/lib/python3/dist-packages/variety/Util.py", line 37, in
import requests
File "/home/veras/.local/lib/python3.10/site-packages/requests/init.py", line 147, in
from . import packages, utils
```

It looks like you installed (an old version of) `requests` in your user home, what is called an [`user site` install by pip](https://packaging.python.org/en/latest/tutorials/installing-packages/#installing-to-the-user-site), with something like `pip install --user requests`. Or perhaps just by running `pip install requests` as a non-root user, and [outside of any virtual environment](https://docs.python.org/3/tutorial/venv.html).

That user-locally installed `requests`, in `/home/veras/.local/lib/python3.10/site-packages/requests/__init__.py`, is being used by system apps, like `variety` in `/usr/lib/python3/dist-packages/variety/Util.py` in this case.

Now, system applications should have their own virtual environments, so as not to be affected by user installs, but you can't influence that, other by filing bugs against those packages (e.g. filing a bug against `variety` for not using a virtualenv).

What you _can_ do is uninstall your user-site packages.  For example, for `requests` do:

* `pip uninstall requests`

as your own user (warning: **not as root**).

To see which other local packages you have installed, do `pip list --user`, and run `pip uninstall <package>`.

If `requests` was installed as a dependency of another Python package that you installed as `user site` so that you can run it as a command, like `poetry` or `tox`, I suggest using [pipx](https://github.com/pypa/pipx/blob/main/docs/installation.md) to manage them instead.

In any case, this doesn't seem like a pop-os bug to me.

**Comment by jacobgkau** [comment]
Hello @Veras-D, did the solution suggested by @leorochael work for you?

**Comment by jacobgkau** [comment]
Thanks for the update. I'm going to close this issue for now, but feel free to comment if you feel any further discussion is warranted.
