### ISSUE TITLE
[Feature Request] Integrating IPinfo's API for automatic timezone setup

### ISSUE THREAD

**Issue by abdullahdevrel** [pop-os/pop#3163]
I came across a [handful of issues](https://github.com/search?q=org%3Apop-os+timezone&type=issues) where users were raising concerns regarding automatic time zone settings in the OS. In a [discussion](https://www.reddit.com/r/pop_os/comments/170dwj7/time_zone_reset_daily_to_wrong_location/) like that, IPinfo.io was mentioned as a solution for automatic timezone setup through our [IP geolocation API services](https://ipinfo.io/products/ip-geolocation-api).

We would absolutely love to be a part of the Pop OS environment.

IPinfo.io provides one of the most accurate IP geolocation API services out there. We support tokenless free access API requests (1,000 requests/day) via HTTPS. 

Please let me know what you think.

### API response example:

```bash
curl https://ipinfo.io/json
```

Response: 

```
{
  "ip": "131.108.204.XXX",
  "city": "Osasco",
  "region": "São Paulo",
  "country": "BR",
  "loc": "-23.5325,-46.7917",
  "org": "AS61692 Mundo 7 Soluções em informática LTDA - ME",
  "postal": "06000-000",
  "timezone": "America/Sao_Paulo",
  "readme": "https://ipinfo.io/missingauth"
}
```

Timezone format example: `"America/Sao_Paulo"`

Please let me know what you think. If there is any I can assist that will be my pleasure.

**Comment by leviport** [comment]
No, thank you.

**Comment by abdullahdevrel** [comment]
Thank you for reviewing the request. Appreciate it.
