### ISSUE TITLE
Radeon VII only boots nomodeset. Kernel bug?

### ISSUE THREAD

**Issue by icytux** [pop-os/pop#3173]
**Distribution
Pop!_OS
22.04 LTS
jammy

**Issue/Bug Description:**
Radeon VII black screen in boot unless with nomodeset, happens with any distro or kernel.

Pop OS 22.04 does not work
Pop OS 18.04 works

Linux Mint 21.2 does not work
Linux Mint 19.2 works

Ubuntu 18.04 works
Ubuntu 20.04 does not work

Nobara does not work
Kubuntu does not work

Windows works.

**Steps to reproduce (if you know):**
Install Pop Os on a system with an AMD Radeon VII

**Expected behavior:**
Boot up.

**Other Notes:**
I've tried everything I can think of, changing kernel to newer, blacklist Radeon etc but it only works with nomodeset, all of them.

Someone suggested this might be just a bug in the kernel after 4.15 but I don't know enough to test or confirm so I'm hoping this helps a dev figure it out.

SPECS:
GPU: Radeon VII
CPU: Ryzen 3600
MB: Asrock B550M Steel Legend
RAM: 32GB

**Comment by jacobgkau** [comment]
From Mattermost:

> Radeon VII on an Asrock B550M Steel Legend

**Comment by jacobgkau** [comment]
Logs from the system (especially from a failed boot) may be helpful to see if a kernel crash is occurring.

**Comment by icytux** [comment]
I updated the BIOS and now it works....
