### ISSUE TITLE
Broken link on community page

### ISSUE THREAD

**Issue by railmeat** [pop-os/pop#319]
On the community page (https://system76.com/pop/community) there is a link with anchor text: "Check our bitesize bugs" which goes to a github page in the pop-os/iso section with no bite sized issues. 

I think this URL might be the one you want: https://github.com/pop-os/pop/issues?q=is%3Aissue+is%3Aopen+label%3Abite-sized It has open bite sized issues for Pop_OS

**Comment by brs17** [comment]
Thanks for filing this issue @railmeat .

A patch has been applied, the update should go live on the website on Monday!
