### ISSUE TITLE
Screen bottom flickering/distortion

### ISSUE THREAD

**Issue by eyallior** [pop-os/pop#3198]
OS: Pop!_OS 22.04 LTS
Laptop: Asus ROG Strix G513QR_G513QR

A few lines of pixels at the bottom of the screen (about 1mm) are distorted/flickering.

This begins to appear when there's something showing there. 
i.e. when I open a browser in maximize window, and start scrolling down a webpage.

This started in the recent 2 weeks or so.

Video:
https://github.com/pop-os/pop/assets/7419178/156cd702-0754-49c8-8d35-5f792530f970

Img:
https://github.com/pop-os/pop/assets/7419178/e6c2235e-2190-4fe6-9dbc-3591a1fea039

**Comment by eyallior** [comment]
I just noticed that if I take a screenshot of the bottom part, in the screenshot I can see lower than what's visible on the screen. Attached a photo from my phone showing the screen, and a screenshot taken of that part.
![size](https://github.com/pop-os/pop/assets/7419178/aeb99938-89c7-4fb8-8e0c-298b457783bd)

**Comment by eyallior** [comment]
Update: over time the bottom distorted part grows to ~1cm
![grow](https://github.com/pop-os/pop/assets/7419178/e30cb271-22ad-4e6f-a0a4-44e7b7ae4f2e)

**Comment by leviport** [comment]
Does this also appear on an external display? If you change the angle of the lid, does the distorted part change? I've seen similar behavior when a laptop's LCD cable develops a kink.

**Comment by eyallior** [comment]
Now the problem gets worse, and now the problem is visible also when restarting, so it's  hardware probably, closing. Thank you!
