### ISSUE TITLE
System76 Driver installed when System76 hardware is detected

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#32]
_From @sarahpandabeara on October 10, 2017 16:47_

_Copied from original issue: pop-os/iso#132_

**Comment by isantop** [comment]
Was it determined that the Driver should be instalable from the repo? If so, that's a pretty trivial update.

**Comment by isantop** [comment]
_From @sarahpandabeara on October 12, 2017 16:14_

Is it the driver that should be put in the Pop!_OS repo? Or is it the system76 repo that should be added to Pop!_OS?

**Comment by isantop** [comment]
_From @sarahpandabeara on October 13, 2017 16:53_

@isantop @jackpot51 ^ Either of you have an answer regarding the above question?

**Comment by isantop** [comment]
_From @jackpot51 on October 13, 2017 20:14_

I would prefer the latter, adding the System76 repo to Pop!_OS during install

**Comment by isantop** [comment]
_From @jackpot51 on October 16, 2017 15:27_

I believe this is the most logical way to manage things. A script will run during install. This script will add the system76-dev/stable PPA and install the driver when the correct hardware is detected.

**Comment by jlacroix82** [comment]
I'll take a look at this bug tonight.
