### ISSUE TITLE
Discover fails to install any updates.

### ISSUE THREAD

**Issue by a-hausmann** [pop-os/pop#3203]
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
 
 
Discover today lists dozens of updates, many completely unrelated and one (Brave browser) always a stand-alone update. Clicking Update All or selecting just one (Brave), or any other combination, pops up an error window, "Update Issue. There was an issue installing this update. Please try again later".

Clicking "See technical details" reveals the below in another window:
Package failed to install:
Error while installing package: dependency problems - leaving unconfigured

This happens each time I attempt any updates.

I expect the update(s) to succeed.
[Discover-error.txt](https://github.com/pop-os/pop/files/13848058/Discover-error.txt)

I've attached a file with /var/log/syslog output seen during the attempt.

**Comment by leviport** [comment]
That output doesn't provide much info. Please provide the output produced after running this command in your terminal:

```
sudo apt update && sudo apt upgrade
```

**Comment by a-hausmann** [comment]
Results in attached file.
[apt-diagnosis--20240108.txt](https://github.com/pop-os/pop/files/13869608/apt-diagnosis--20240108.txt)

**Comment by a-hausmann** [comment]
arnold@pop-os:~$ systemctl --version
systemd 249 (249.11-0ubuntu3.9pop0~1704316205~22.04~29371bb)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified

**Comment by a-hausmann** [comment]
Finally got the version info to not change tildes to strike-through. But at least that part is correct.

**Comment by leviport** [comment]
I believe this article might help: https://support.system76.com/articles/package-manager-pop

There is some very strange output in that file though. All of those "source configured multiple times" warning messages are not typical. Manually inspecting your apt sources might be a good idea.

**Comment by a-hausmann** [comment]
Thank you!  Problem solved. The "source configured multiple times" is what did it.

I've seen brief messages in Discover stating something like that for a while now, but never did that stop Discover from updating. Finding out the apt sources are in the /etc/apt/sources.list.d directory, and with the error messages you mentioned, once I renamed "archive_uri-http_apt_pop-os_org_ubuntu-jammy.list" to append a date string, Discover installed the updates just fine.

I suspect it's possible that over 200 updates overwhelmed Discover with the duplication of jammy sources, as it never seemed to matter before.  Whatever.  Cased Closed, and I hope these comments help someone else in the future.  Thanks again, have a great 2024!
