### ISSUE TITLE
Mouse pointer moving when switching Workspace

### ISSUE THREAD

**Issue by Milziade** [pop-os/pop#3206]
**Distribution (run `cat /etc/os-release`):**
 22.04 LTS
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
If I have two workspace with different open windows in them, when I switch from the first workspace to the second one, the pointer moves to the upper-left corner of the window on focus on the second workspace, no matter where the pointer was in the first workspace.
Same **does not** apply if I switch from the second workspace to the first (pointer stays in place)

**Steps to reproduce (if you know):**

**Expected behavior:**
Pointer doesn't change its position switching between workspaces

**Other Notes:**

**Comment by leviport** [comment]
Try changing "Mouse Cursor Follows Active Window" in the Extensions application > Pop Shell > Settings
![2024-01-08_07-33-16](https://github.com/pop-os/pop/assets/13512097/15bb4256-fef4-4ac6-ade6-ccfb930677bf)
