### ISSUE TITLE
PopShop perma hangs AdderWS3

### ISSUE THREAD

**Issue by Etrinque** [pop-os/pop#3208]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop_OS Pop Shop

**Issue/Bug Description:**
Pop shop update tab causes major hang issue with my Effectivly Brand new AdderWS3. Since nearly day one I have had issues with this Freezing and causing massive issues needing manual power downs. Completely unresponsive.

**Steps to reproduce (if you know):**
Open Pop Shop
allow to load fully
click update/installed tab
fans spin to 100% and system complete Freeze

must power down manually with power button.
No other way to kill or remedy.

**Expected behavior:**

Remain in control of system.

**Other Notes:**
I do understand updates from terminal and do it fairly frequently however that doesnt mean it should be the only way. 

I do fear the risk of data corruption and hardware failure from hard shutdowns and would like to avoid them at all possible. Considering the costs involved with this system it should be addressed.

**Comment by mmstick** [comment]
Did you create a support ticket?

**Comment by Etrinque** [comment]
> Did you create a support ticket?

I have not yet but will do as soon as avail.

**Comment by jacobgkau** [comment]
If you're experiencing full system hangs and you can't even switch to a TTY with Ctrl-Alt-F5 when that occurs, then it sounds like you may have a defective RAM stick or other hardware issue. The support team should be able to help diagnose and address this.

**Comment by jacobgkau** [comment]
Are you still in need of assistance regarding this issue? Did you end up creating a support ticket?

**Comment by Etrinque** [comment]
I contacted support and was told that it is being rewritten in rust etc. so we will see. Might as well close it out for now as its a mute point.

**Comment by mmstick** [comment]
@Etrinque You can install `cosmic-store` with `cosmic-icons` if you want to try it out, and then you can remove `pop-shop` if it works for you.

**Comment by Etrinque** [comment]
@mmstick Thank you for the info, I appreciate it.
