### ISSUE TITLE
Terminal starts with "Command 'ng' not found, but can be installed with: sudo apt install ng-common"

### ISSUE THREAD

**Issue by SziluChannel** [pop-os/pop#3216]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
nautilus-extension-gnome-terminal:
  Installed: 3.44.0-1ubuntu1pop0~1650921985~22.04~c2346f6
  Candidate: 3.44.0-1ubuntu1pop0~1650921985~22.04~c2346f6
  Version table:
 *** 3.44.0-1ubuntu1pop0~1650921985~22.04~c2346f6 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     3.44.0-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**
Upon opening the terminal, before the prompt appears, an error shows up, saying "Command 'ng' not found, but can be installed with: sudo apt install ng-common".
![image](https://github.com/pop-os/pop/assets/97226944/4f910bd1-1cae-4b41-a5cb-c8218b705f83)

**Steps to reproduce (if you know):**
I have recently refreshed my OS in the settings with the reset OS button. After that I ran a full system upgrade upgrading the kernel to 6.6.10-76060610.

**Expected behavior:**
The application starts up and the prompt appears without any text before it.

**Other Notes:**
So far no functionality was harmed, it is just a minor inconvenience that it takes up screen space unnecessarily.
When I installed the ng-common package in hope that the error disappears I would get an empty terminal with no prompt and no typing functionality.

**Comment by leviport** [comment]
Were you making modifications to your .bashrc?

**Comment by SziluChannel** [comment]
No, I did not touch that recently.

**Comment by mmstick** [comment]
A system refresh retains your home folder, so you have a configuration in your profile that's calling this.

**Comment by SziluChannel** [comment]
Oh thank you all for the quick fix!
You are totally correct, I had angular installed before, and now it is gone, but the config was still in the .bashrc file!
Thank you!
