### ISSUE TITLE
cannot open application from links

### ISSUE THREAD

**Issue by KasAgg21** [pop-os/pop#3230]
**Distribution (run `cat /etc/os-release`):**
 
 Version 22.04 lts

 

**Issue/Bug Description:**
When an link in chrome some website try to open a app from link it doesnt open and gives response 500

**Steps to reproduce (if you know):**
Try to signin using google account through zoom 

**Expected behavior:**
Open zoom or other app but it doesnt 

**Other Notes:**

**Comment by leviport** [comment]
Is this the flatpak or the .deb version of Chrome? If it's the flatpak, you might just need to grant it more permissions with Flatseal.
