### ISSUE TITLE
Upgrade package conflicts (system76-power vs power-profiles-daemon)

### ISSUE THREAD

**Issue by samuelznewton** [pop-os/pop#3234]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
system76-power:
  Installed: 1.1.25~1696869511~22.04~c802cea
  Candidate: 1.1.25~1696869511~22.04~c802cea
  Version table:
 *** 1.1.25~1696869511~22.04~c802cea 100
        100 /var/lib/dpkg/status
```

```
power-profiles-daemon:
  Installed: (none)
  Candidate: 0.10.1-3
  Version table:
     0.10.1-3 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
```

**Issue/Bug Description:**

Running `sudo apt update` then `sudo apt upgrade` results in the following error message:

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 system76-power : Conflicts: power-profiles-daemon but 0.10.1-3 is to be installed
E: Broken packages
```

I'm rather unfamiliar with the intricacies of package management, but I've found a few tidbits of information that might help:

- According to `apt show system76-power`, that package (`system76-power`) does conflict with `power-profiles-daemon`.
- ...and yet, according to `apt-cache rdepends power-profiles-daemon`, `system76-power` *depends on* `power-profiles-daemon`.  (Have I misinterpreted something?)
- Neither `system76-power` nor `power-profiles-daemon` are in the list of packages given by `apt list --upgradable`, and the latter package isn't installed in the first place.
- `gnome-shell`, which depends on `power-profiles-daemon`, is in the list of packages to upgrade (from `42.5-0ubuntu1pop1~1675984688~22.04~f574f54` to `42.9-0ubuntu2`, which somehow doesn't look like it's supposed to happen).

**Steps to reproduce (if you know):**

Well, I simply ran `sudo apt update` followed by `sudo apt upgrade`.  But, given the lack of identical reports, I assume that's not all there is to it.  Could the fact that I use XFCE be relevant?

**Expected behavior:**

The update should work, and not try to install conflicting packages.

**Other Notes:**

I've found the Pop!_Shop to be unstable in the past, so I tend to avoid it.  (Though, I believe it's been improved over time.)  Still, I went ahead and tried using it to update after apt failed, and got a somewhat different error message.  Intriguing...

```
Failed to update “Operating System Updates”

This may have been caused by sideloaded or manually compiled software, a third-party software source, or a package manager error. Manually refreshing updates may resolve the issue.

Details

The following packages have unmet dependencies:
  systemd-timesyncd: Conflicts: time-daemon
  chrony: Conflicts: time-daemon
          Conflicts: time-daemon
  steam-installer: Depends: steam-libs-i386 (= 1:1.0.0.78~ds-3~1702068998~22.04~9dee6ed)
```

(Manually refreshing updates does not resolve the issue.)

**Comment by samuelznewton** [comment]
Based on what I found with `gnome-control-center` and `gnome-shell`, I tried on a whim to hold back all gnome packages.

```
sudo apt-mark hold gnome*
sudo apt update
sudo apt upgrade
```

The update succeeded.  However, cancelling the hold and trying again, as expected, still fails.  So, as of now, it appears impossible to upgrade some set of gnome packages, which may or may not be all gnome packages.

**Comment by mmstick** [comment]
It looks like you no longer have the apt.pop-os.org sources in your apt configuration. Note that the version of `system76-power` claims its source as `/var/lib/dpkg/status` instead of `apt.pop-os.org`.

**Comment by samuelznewton** [comment]
@mmstick Thanks for the info.  Unfortunately, I'm operating past the edge of my understanding, so I'll poke you for a bit more info, if that's alright :sweat_smile: 

If the apt.pop-os.org sources are missing from my apt configuration, how would I add them back?

Are the files `/etc/apt/sources.list.d/pop-os-apps.sources` and `/etc/apt/sources.list.d/pop-os-release.sources` relevant?  They both exist, and, by my understanding, are enabled.  Here's their content:

```
samuel@sling-shot:/etc/apt/sources.list.d$ cat pop-os-apps.sources 
X-Repolib-Name: Pop_OS Applications
Enabled: yes
Types: deb
URIs: http://apt.pop-os.org/proprietary
Suites: jammy
Components: main
samuel@sling-shot:/etc/apt/sources.list.d$ cat pop-os-release.sources 
X-Repolib-Name: Pop_OS Release Sources
Enabled: yes
Types: deb deb-src
URIs: http://apt.pop-os.org/release
Suites: jammy
Components: main
```

**Comment by samuelznewton** [comment]
The issue has inexplicably disappeared.  If you guys did something behind the scenes to fix it, then thank you.  Otherwise... ehhhhh?

**Comment by mmstick** [comment]
We haven't done anything, no.

**Comment by fuog** [comment]
> Based on what I found with `gnome-control-center` and `gnome-shell`, I tried on a whim to hold back all gnome packages.
> 
> ```
> sudo apt-mark hold gnome*
> sudo apt update
> sudo apt upgrade
> ```
> 
> The update succeeded. However, cancelling the hold and trying again, as expected, still fails. So, as of now, it appears impossible to upgrade some set of gnome packages, which may or may not be all gnome packages.

i have the exact same problem.  :(

**Comment by alextenev** [comment]
same issue here:
```
The following packages have unmet dependencies:

  systemd-timesyncd: Conflicts: time-daemon
  chrony: Conflicts: time-daemon
          Conflicts: time-daemon
