### ISSUE TITLE
ROCm breaks the system after recent update.

### ISSUE THREAD

**Issue by loafylemon** [pop-os/pop#3235]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Hardware information:**
```
AMD Ryzen 7 7800X3D 8-Core Processor
AMD Radeon 7900 XTX
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
After the recent update, I've encountered an issue where the system wouldn't go past the 'Something went wrong :(' GNOME screen. Since then, I have reinstalled Pop_!OS in order to find the point of failure, and after trying to install ROCm and rebooting, the issue reoccurred. I must emphasise, the problem did not occur before the recent update.

Logs:
[dump.log](https://github.com/pop-os/pop/files/14437669/dump.log)

**Steps to reproduce (if you know):**
1. Download and install amdgpu-install.
```
sudo apt update
wget https://repo.radeon.com/amdgpu-install/6.0.2/ubuntu/jammy/amdgpu-install_6.0.60002-1_all.deb
sudo apt install ./amdgpu-install_6.0.60002-1_all.deb
```
2. Add Pop_!OS to the supported list.
```
sudo nano /usr/bin/amdgpu-install
```
```
case "$ID" in
ubuntu|linuxmint|debian|pop)
                         ^
```
3. Install ROCm.
```
sudo amdgpu-install --usecase=rocm --no-dkms
```
4. Reboot.

**Expected behavior:**

**Other Notes:**
I am able to log-in through TTYL by pressing CTRL+ALT+F4.

Things I have tried to make it work:
* Install another DE, WM.
* Reconfiguring dpkg.
* Installing older version of ROCm (5.7).
* Disabling hybrid graphics/iGPU.
* Rolling back to the previous version of Pop_!OS <- This allows ROCm to work, but is not ideal.

**EDIT:** (3 MAR 2024)
Still broken on the new kernel.
`Linux pop-os 6.6.10-76060610-generic #202401051437~1709085277~22.04~31d73d8 SMP PREEMPT_DYNAMIC Wed F x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Hunterrules0-0** [comment]
Can comfirm that this still is a problem has gotten worse. Dual monitors no longer work, going to the settings crahses the session and sends you back to the menu and worst of all it seems the drivers arent even loaded in. Uninstalling amdgpu dose not appear to do anything and im having to move over 1tb of data of files and videos because i have to reinstall the entire os. 

If your lucky you can try spamming tab on your pcs startup. then wait for the bootloader to show you the option to boot from the old kernel, current kernel, or recovery. Select old kernel and see if that fixes it. If it does DO NOT update until pop os figures out there shit.

**Comment by Hunterrules0-0** [comment]
> > until pop os figures out there shit.
> 
> Please keep in mind that we have a [code of conduct](https://github.com/pop-os/code-of-conduct).
> 
> It's been mentioned multiple times that this isn't Pop's fault. AMD's DKMS modules are often incompatible with the kernels we ship, and there's nothing we can do about it. Since System76 hardware is very bleeding-edge, we often need to ship newer kernels for hardware enablement.
> 
> At this time, we're recommending ROCm/AMDGPU-PRO users implement a containerized workflow, rather than trying to install these drivers directly on your OS.

Yeah I am sorry about that comment. Im just mad That I have to reinstall everything. I have a 2tb nvme drive that im moving the things to. it acts as a secondary storage device for my pc. IM moving all my important files to there temporarily. until I reinstall from the built in recovery mode. then after that ill move the files back to there respected places and delete the files from the secondary drive. It just makes me really mad that im having to format and reinstall everything. But I am sorry for that comment

**Comment by Hunterrules0-0** [comment]
> I managed to get ROCm 6.02 working on Pop!_OS 22.04 LTS with the latest Linux kernel (6.8.0) and a RX 7900 GRE.
> 
>     1. First, make some kind of backup of your system (there's no guarantee these steps will work for you).
> 
>     2. Install the AMD driver using:
> 
> 
> ```
> amdgpu-install --no-dkms
> ```
> 
>     3. Restart the system and ensure everything is working properly.
> 
>     4. Install ROCm:
> 
> 
> ```
> amdgpu-install --usecase=rocm --no-dkms
> ```
> 
>     5. Add yourself for rendering and video permissions:
> 
> 
> ```
> sudo usermod -aG video $USER
> sudo usermod -aG render $USER
> ```
> 
>     6. Restart again and verify that ROCm is functioning properly:
> 
> 
> ```
> rocminfo
> rocm-smi
> ```
> 
> Keep in mind that this might entail a regression in some aspects. For instance, MESA shifts from version 24 to 23.3 according to the command `glxinfo -B`.
> 
> Good luck!

can you show a picture of cpu-x to show that the drivers are loaded in and your kernel version. I dont think im going to install rocm again after it destroyed my installation. also who knows whats going to happen next update. it could break it more

**Comment by Hunterrules0-0** [comment]
Thank you. seems the drivers have loaded. Does rocm/amdgpupro offer better performance than the standard drivers included in pop os

**Comment by Hunterrules0-0** [comment]
thanks

**Comment by jacobgkau** [comment]
We have a WIP article that will explain how to install ROCm in an easier way, now that AMD provides an Ubuntu repository for it and offers a ROCm package that doesn't do anything DKMS-related: https://github.com/system76/docs/pull/1231/files 

Can anyone confirm if following the instructions in that draft article gets you what you need?

**Comment by loafylemon** [comment]
I did a fresh reinstall of Pop!_OS and followed the steps outlined in the aforementioned article, and can confirm that ROCm seems to work just fine. Thank you!
