### ISSUE TITLE
immutability?

### ISSUE THREAD

**Issue by Thatoo** [pop-os/pop#3236]
What do you think of adopting the agnostic distribution work done by VanillaOS to help distribution to be immutable, [ABroot](https://github.com/Vanilla-OS/ABRoot/) ?

**Comment by leviport** [comment]
We have discussed immutability in Pop quite a bit, but our current focus is on COSMIC DE, so it is a topic we will have to revisit at a later time. The specifics about which technology we'll use to implement it will be decided then.
