### ISSUE TITLE
No return from suspend

### ISSUE THREAD

**Issue by Haimaroch** [pop-os/pop#3243]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
No return from suspend.

**Steps to reproduce (if you know):**

suspend comp. press space bar twice 

**Expected behavior:**
computer only partly wakes up. no screen. 

**Other Notes:**

Cold shut off and restart as a remedy..

**Comment by leviport** [comment]
Please share hardware details.

**Comment by Haimaroch** [comment]
i tried to show the support file made by "settings" but i can not move it from my home directory.
