### ISSUE TITLE
Tracker high cpu usage

### ISSUE THREAD

**Issue by nietsj0** [pop-os/pop#3244]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
 
![image](https://github.com/pop-os/pop/assets/109591611/6bc8c271-cb94-4544-b499-40c2ba12a037)

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
tracker:
  Installed: 3.3.0-1
  Candidate: 3.3.0-1
  Version table:
 *** 3.3.0-1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
keeps +100% cpu, kill necessary 

**Steps to reproduce (if you know):**
on this system, every reboot

**Expected behavior:**
low cpu usage

**Other Notes:**

**Comment by nietsj0** [comment]
Anyone wanna have a look, need extra info or?

**Comment by nietsj0** [comment]
such helpfulness...

**Comment by leviport** [comment]
We use Github issues for tracking bugs and new features, not as a support forum. For support, please visit Pop!\_OS chat: https://chat.pop-os.org

[Tracker](https://tracker.gnome.org/overview/) is a file indexer. When it's running, it frequently uses a lot of CPU. Once it has a good index built, it should settle back down.

**Comment by nietsj0** [comment]
Congrats, it seems like an issue on this system and OS combo.
I disabled tracker because it never settles down, seemed I made that clear, maybe not... 

Anyways, very nice you decide to answer went its no longer relevant.
