### ISSUE TITLE
System update with Pop!_Shop stuck (freeze) on 90%. UPDATED

### ISSUE THREAD

**Issue by amadin** [pop-os/pop#328]
**Distribution**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version**
```
 l@pop-os:~$ dpkg --version
 Debian 'dpkg' package management program version 1.19.0.5 (amd64).
 This is free software; see the GNU General Public License version 2 or
 later for copying conditions. There is NO warranty.
 l@pop-os:~$ apt-get --version
 apt 1.6.3 (amd64)
 l@pop-os:~$ io.elementary.appcenter --help
 [INFO 12:08:35.580908] Application.vala:154: Pop!_Shop version: 0.2.9
 [INFO 12:08:35.580954] Application.vala:156: Kernel version: 4.15.0-23-generic
```
 

**Issue/Bug Description:**
After pressing the emerging message at the top of the screen (where date and time) about 1 update available and pressing button "Update All", process stuck (freeze) on ~ 90% and nothing happen. Also system can't load after reboot, black screen.

**Steps to reproduce (if you know):**
Disable UEFI in bios settings (maybe not necessary). Pop!_OS install on clear hard drive with  default installer settings ("Clear Install") without disk encryption. After reboot finish all wizard steps then press the emerging message at the top of the screen (where date and time) about 1 update available and press button "Update All". I reproduced this 3 times.
![screenshot from 2018-07-28 15-18-30](https://user-images.githubusercontent.com/13412191/43356895-ae00eb44-9281-11e8-9b59-6f669412e03a.png)

**Expected behavior:**
Update process stuck (freeze) on ~ 90% and nothing happen even if wait 15 minutes, hard drive don't produce any sounds. After manual compulsory reboot system not load (black screen after BIOS load).

**Other Notes:**
After manually end processes: io.elementary.appcenter and dpkg:
```
$ sudo dpkg --configure -a
[sudo] password for l: 
**Setting up grub-pc (2.02-2ubuntu8.2) ...**
debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
dpkg: error processing package grub-pc (--configure):
 installed grub-pc package post-installation script subprocess returned error exit status 1
Processing triggers for initramfs-tools (0.130ubuntu3.2pop3) ...
update-initramfs: Generating /boot/initrd.img-4.15.0-23-generic
Processing triggers for linux-image-4.15.0-29-generic (4.15.0-29.31) ...
/etc/kernel/postinst.d/initramfs-tools:
update-initramfs: Generating /boot/initrd.img-4.15.0-29-generic
/etc/kernel/postinst.d/zz-update-grub:
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-4.15.0-29-generic
Found initrd image: /boot/initrd.img-4.15.0-29-generic
Found linux image: /boot/vmlinuz-4.15.0-23-generic
Found initrd image: /boot/initrd.img-4.15.0-23-generic
done
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up linux-generic (4.15.0.29.31) ...
Setting up linux-signed-generic (4.15.0.29.31) ...
Setting up language-pack-ja (1:18.04+20180712) ...
Setting up language-pack-es (1:18.04+20180712) ...
Setting up language-pack-fr (1:18.04+20180712) ...
Setting up python3-update-manager (1:18.04.11.4) ...
Setting up language-pack-ja-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-zh-hans (1:18.04+20180712) ...
Setting up language-pack-gnome-ja (1:18.04+20180712) ...
Setting up language-pack-pt (1:18.04+20180712) ...
Setting up language-pack-gnome-ja-base (1:18.04+20180712) ...
Setting up language-pack-es-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-zh-hant (1:18.04+20180712) ...
Setting up language-pack-ar (1:18.04+20180712) ...
Setting up language-pack-en (1:18.04+20180712) ...
Setting up language-pack-it (1:18.04+20180712) ...
Setting up language-pack-zh-hant-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-zh-hans-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-fr-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-ar (1:18.04+20180712) ...
Setting up python3-distupgrade (1:18.04.21) ...
Setting up language-pack-de (1:18.04+20180712) ...
Setting up language-pack-it-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-zh-hans (1:18.04+20180712) ...
Setting up language-pack-pt-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-en-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-fr (1:18.04+20180712) ...
Setting up language-pack-ru (1:18.04+20180712) ...
Setting up language-pack-gnome-de (1:18.04+20180712) ...
Setting up language-pack-ru-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-es (1:18.04+20180712) ...
Setting up language-pack-gnome-es-base (1:18.04+20180712) ...
Setting up language-pack-gnome-en (1:18.04+20180712) ...
Setting up language-pack-gnome-ar-base (1:18.04+20180712) ...
Setting up language-pack-gnome-pt (1:18.04+20180712) ...
Setting up ubuntu-release-upgrader-core (1:18.04.21) ...
Setting up language-pack-gnome-zh-hans-base (1:18.04+20180712) ...
Setting up language-pack-gnome-zh-hant (1:18.04+20180712) ...
Setting up language-pack-gnome-it (1:18.04+20180712) ...
Setting up language-pack-ar-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-pt-base (1:18.04+20180712) ...
Setting up language-pack-gnome-en-base (1:18.04+20180712) ...
Setting up language-pack-gnome-de-base (1:18.04+20180712) ...
Setting up language-pack-de-base (1:18.04+20180712) ...
Generating locales (this might take a while)...
Generation complete.
Setting up language-pack-gnome-ru (1:18.04+20180712) ...
Setting up language-pack-gnome-ru-base (1:18.04+20180712) ...
Setting up language-pack-gnome-it-base (1:18.04+20180712) ...
Setting up language-pack-gnome-zh-hant-base (1:18.04+20180712) ...
Setting up language-pack-gnome-fr-base (1:18.04+20180712) ...
Setting up update-manager-core (1:18.04.11.4) ...
Errors were encountered while processing:
 grub-pc
```

Until reboot after x server down i see terminal message (1 second) "**GRUB install devices:**".
If in GRUB menu i select newest kernel i can saw this:
`Kernel Panic: VFS: Unable to mount root fs on unknown-block(0,0)`

I reinstall OS and do:
```
l@pop-os:~$ sudo apt-get update
l@pop-os:~$ sudo apt-get upgrade
```
And got this:
![screenshot from 2018-08-03 11-57-46](https://user-images.githubusercontent.com/13412191/43635120-d1ebad70-9716-11e8-93cf-91fa61d54b74.png)
![screenshot from 2018-08-03 11-59-20](https://user-images.githubusercontent.com/13412191/43635121-d67fb02a-9716-11e8-833f-f3646a138537.png)

So if do upgrade from console then upgrade can be successful.
Full logs are here https://pastebin.com/X5i8ahY3
Disc structure here (created by Pop_OS! automatically):
![screenshot from 2018-08-03 12-58-23](https://user-images.githubusercontent.com/13412191/43637421-ade38e96-971d-11e8-81a0-49268f0927bc.png)

I think Pop!_Shop don't have GUI menu for GRUB tune like Ubuntu "Sofware Centre" (see picture):
![j3hh8](https://user-images.githubusercontent.com/13412191/43358103-f9e09c2c-9294-11e8-9e63-c149d5192a3c.png)

Notebook "Lenovo G580", model 20150
Memory DDR3 - 1600Mhz 1x4GB
SATA II (SATA III compatible)] HDD storage - 500GB

**Comment by adityanb** [comment]
Had the same issue. Ended up doing a update-initramfs from an older kernel to fix this.

**Comment by amadin** [comment]
adityanb, can you write in more detail what needs to be done?

**Comment by mmstick** [comment]
@chris977 You should never disable UEFI. The other option is a legacy mode with a lot of restrictions.

If anyone is having issue installing updates, I can only recommend performing the updates through the terminal to fix them. `sudo apt update && sudo apt upgrade`. It will prompt you if needs to, and if there's an issue it will point out the cause. If it's a lockfile, you may need to `sudo rm path/to/lockfile` to get things working again.

**Comment by amadin** [comment]
@chris977 Turn on the computer and click (or often press) the down arrow button, you should see the Grub bootloader window, select the old kernel and the system will boot successfully. This is advice in case you can't load the system after the update.

**Comment by Bandito11** [comment]
Hi

Had a similar problem (mine was stuck at 8 percent) and I tried using `sudo apt update && sudo apt upgrade` but the terminal said something dpkg was interrupted and to run it manually:

`sudo dpkg --configure -a`

and then everything worked

**Comment by chris977** [comment]
@Bandito11 I think this solves the problem. I reinstalled Pop and I had to do `sudo dpkg --configure -a` at the first update after reboot. I wasn't sure what was it for, but I suppose this is it.

**Comment by Bandito11** [comment]
@chris977 I don't know what that line do either I just know it works 😂

**Comment by python-force** [comment]
@Bandito11 It solves the problem for me as well, what I did is:
1. sudo rm /var/lib/dpkg/lock
2. sudo dpkg --configure -a
3. sudo apt update && sudo apt upgrade
4. reboot - all up to date - all working

Thank you

**Comment by somersbmatthews** [comment]
my update stopped at 7%, followed the above steps and then it wouldn't boot. held down button during boot. selected pop os recovery. ran pop shop and am downloading os updates now through it.
