### ISSUE TITLE
This issue is not resolved, I'm still facing it with my laptop (Samsung Galaxy Book2 running Pop!_OS 22.04 LTS).

### ISSUE THREAD

**Issue by arthurto** [pop-os/pop#3301]
This issue is not resolved, I'm still facing it with my laptop (Samsung Galaxy Book2 running Pop!_OS 22.04 LTS). 
This thing comes and goes and I'm not sure why, looks random.
My battery is at 25% and not charging.
I need to turn it off to charge it, but somedays this problem simply does not exist.

_Originally posted by @arthurto in https://github.com/pop-os/pop/issues/1205#issuecomment-2133691021_

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/pop/issues/1205

Please don't open duplicate issues instead of requesting that the old issue be re-opened.
