### ISSUE TITLE
Pop!_OS crashes after reboot (not longer than 10 mins) after running upgrade

### ISSUE THREAD

**Issue by Yummy-Yums** [pop-os/pop#3302]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Issue/Bug Description:**

Pop OS crashes after reboot. It began with login issues . Failure to login after locking for a period of time and i upgraded . it can barely stay on for an hour after start . i run `kill -15 -1` as suggested by pop-os support articles

![image](https://github.com/pop-os/pop/assets/77977520/c0caf943-2fa5-4bd0-a192-b317c9541b87)

Most of my gnome-extensions have been turned off as well

![image](https://github.com/pop-os/pop/assets/77977520/dece12b0-b8d2-4b21-bb7e-34ac8dd53bff)

**Steps to reproduce (if you know):**
Run upgrade to see if same issue is experienced

**Expected behavior:**
Works as expected

**Other Notes:**
Please help

**Comment by vbordalo** [comment]
Same here:

Distribution (run cat /etc/os-release):
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com/"
SUPPORT_URL="https://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

After several library upgrades using the Pop!_OS standard upgrade tool POP-OS CRASHES AFTER REBOOT. Maybe we have to repair the Bootloader, but how?

In my case, I have an encrypted disk so I still can access the screen to unlock disk cryptdata after that the system goes to EMERGENCY MODE.

I was wondering if it is going to work as suggested in https://support.system76.com/articles/bootloader/:

```shell
for i in dev dev/pts proc sys run; do sudo mount -B /$i /mnt/$i; done
sudo chroot /mnt
apt install --reinstall linux-image-generic linux-headers-generic
update-initramfs -c -k all
exit
sudo bootctl --path=/mnt/boot/efi install
```
![IMG_2704](https://github.com/pop-os/pop/assets/36831295/860127c3-82bc-4cd3-85b5-308e087b6667)
![IMG_2696](https://github.com/pop-os/pop/assets/36831295/94e78e65-e58e-4e88-bb5e-9deec230b608)
![IMG_2703](https://github.com/pop-os/pop/assets/36831295/f08cda38-c383-4edf-ac54-b8438c7d6048)
![IMG_2702](https://github.com/pop-os/pop/assets/36831295/4dba2fb8-113a-4eb5-a3cc-3967930d4a7a)

**Comment by Yummy-Yums** [comment]
Regarding my case, I found out it's a Linux kernel issue... I downgraded to
a 5.16 generic kernel and gnome extensions stopped working.. I'd wait out
on the next kernel upgrade from Pop-OS

**Comment by Yummy-Yums** [comment]
There's an issue with the current kernel

**Comment by jacobgkau** [comment]
Please provide information about your hardware if it seems to be a kernel issue.

**Comment by Yummy-Yums** [comment]
@jacobgkau i found out it's recurring problem with others as well. below is my hardware info, 

![image](https://github.com/pop-os/pop/assets/77977520/ad2e189a-dfb8-42aa-a759-b6f7f68dfda4)

linked issue...the kernel listed below given this problem so i downgraded the kernel to 5.13 but i can't downgrade to 6.13 for some reason and can't upgrade back to 6.8.0-76

**Comment by vbordalo** [comment]
In my case, for some reason it seems that a given kernel update made changes in my Bootloader and damaged my sda1 EFI partition (!!), so I need to:

1. Boot from a Live USB,
2. Unlock the encrypted partition,
3. Manually mount the root and other necessary filesystems into /mnt
4. Chroot into /mnt,
5. Reinstall GRUB with the appropriate target for UEFI systems (by editing GRUB configuration file to enable cryptodisk, GRUB_ENABLE_CRYPTODISK=y)
reboot
Solved!!

**Comment by Yummy-Yums** [comment]
What's your kernel version and hardware ?

**Comment by Yummy-Yums** [comment]
@jacobgkau @vbordalo can you guys help me here?... I mistakenly deleted my /lib/modules files and reinstalled a kernel(6.5.0) but pop os still boots from 5.17.. My wifi and module stopped working 

![IMG_20240531_153318](https://github.com/pop-os/pop/assets/77977520/d70f97d2-2edd-4636-a311-d8612d528e18)

**Comment by Yummy-Yums** [comment]
![IMG_20240531_153318](https://github.com/pop-os/pop/assets/77977520/af2d6247-514e-41d3-bf7b-af45051ad01f)

**Comment by Yummy-Yums** [comment]
It can't find the /boot/efi error when I run sudo mount -a

**Comment by Leebre** [comment]
I have Pop! OS installed on a workstation PC and I've had a boot problem since yesterday. It seems the ext4 /home partition cannot mount, due to issues with user quotas. I opened a Stack Exchange issue [here](https://unix.stackexchange.com/questions/777563/ext4-home-filesystem-wont-mount-possible-to-recover?noredirect=1#comment1487160_777563) and a helpful person there pointed me to this issue. Perhaps this problem is related to the same kernel issue?

**Comment by Leebre** [comment]
My system is a desktop PC workstation:

CPU: Intel Core i9 13900K
Motherboard: MSI PRO Z790-A
SSD in question:  Samsung 960 PRO 512GB NVME SSD
Kernel version:  Linux pop-os 6.8.0-76060800daily20240311-generic #202403110203~1710198088~22.04~1a3dbc7 SMP PREEMPT_DYNAMIC Mon M x86_64 x86_64 x86_64 GNU/Linux

**Comment by Yummy-Yums** [comment]
@Leebre download Mainline Kernel and use it to switch to another kernel... 6.7.0-060700 is more stable.. That's what I switched to

**Comment by leviport** [comment]
If anyone's feeling adventurous, you could take the proposed 6.9.3 kernel we are testing for a spin: https://github.com/pop-os/linux/pull/324. I've been running it on my oryp9 and my custom built gaming desktop (all AMD) and I haven't run into any issues yet.

To install it, first add the staging branch:
```
apt-manage add popdev:linux-6.9.3
```
and then install updates and restart. 

Just be mindful that doing so will remove the `oldkern` entry and replace it with the second newest kernel, which is likely 6.8.0 for most. If you're booting oldkern to avoid 6.8.0, you should be aware of that.
