### ISSUE TITLE
Kernel 6.8.0 update 22.04~aba43ee fails to detect AMD graphics, and it falls back to llvmpipe

### ISSUE THREAD

**Issue by dxps** [pop-os/pop#3303]
## Distribution

The content of `/etc/os-release`:
 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

<br/>

## Issue/Bug Description

On my Lenovo Yoga 7 14APH8, having an AMD Radeon 780M, with the latest update to kernel 6.8.0 (see `uname -a` below), the graphics that is selected is llvmpipe. And I discovered this issue while trying to figure it out why the external monitor is not detected.

### With kernel 6.8.0

```shell
~ ❯ uname -a
Linux dxps 6.8.0-76060800daily20240311-generic #202403110203~1715181801~22.04~aba43ee SMP PREEMPT_DYNAMIC Wed M x86_64 x86_64 x86_64 GNU/Linux
~ ❯
```

<img src="https://github.com/pop-os/pop/assets/14140226/05402f55-210c-4ba3-9d5d-6ed1da08e282" width="400">

### With kernel 6.5.6

Specifically:
```shell
~ ❯ uname -a
Linux dxps 6.5.6-76060506-generic #202310061235~1697396945~22.04~9283e32 SMP PREEMPT_DYNAMIC Sun O x86_64 x86_64 x86_64 GNU/Linux
~ ❯
```

<img src="https://github.com/pop-os/pop/assets/14140226/f6713c98-4598-4bdd-a059-6a84acd55702" width="400">

<br/>
<br/>

Any hints, please?
Thanks in advance!

**Comment by APainInTheAss** [comment]
I experience the same issue with 6.8.0 kernel and a AMD Radeon 6700 gpu. I also noticed it when my second monitor didn't get detected.
My current work around is booting into the old kernel config which is using the 6.6.10 kernel.
I first had this issue yesterday (thu 30 may) after I updated my system the day before (wed 29 may).

**Comment by dxps** [comment]
And today, with the new kernel update - `6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67` - which I hoped to solve the problem, it actually didn't, but made it worse as the old kernel became `6.8.0` (details above), so now I cannot use the second monitor as I don't yet have any workaround. :disappointed:

**Comment by dxps** [comment]
And today, with the new kernel update - `6.9.3-76060903-generic #202405300957~1718348209~22.04~7817b67` - which I hoped to solve the problem, it actually didn't, but made it worse as the old kernel became `6.8.0` (details above), so now I cannot use the second monitor as I don't yet have any workaround. :disappointed:

**Comment by dxps** [comment]
Problem solved!

I found that `amdgpu` module was blacklisted:
```
❯ cat /etc/modprobe.d/blacklist-amdgpu.conf
blacklist amdgpu
❯ 
```
So I "commented" it by `mv blacklist-amdgpu.conf blacklist-amdgpu.conf_orig` and system restart.

So now I'm all good again, running on the recent `6.9.3` kernel.
