### ISSUE TITLE
Visual horiznotal lines glitches while using Pop OS with AMD GPU Radeon RX 7800XT

### ISSUE THREAD

**Issue by IkutiDev** [pop-os/pop#3311]
**Distribution (run `cat /etc/os-release`):** 
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

---

**Issue/Bug Description:**

While using Pop OS and using any apps (Firefox web browser, discord, gaming using Proton and Steam, game developing with Godot 4.2) I keep getting a horizontal lines that appear on my display for a half a second. Here's a video of when it got real bad:

https://github.com/pop-os/pop/assets/40697587/2aaebc41-7d4c-4161-a88c-0718a670843c

**Steps to reproduce (if you know):**
Sadly it currently feels very random. Sometimes for hours there are no problems, other times a glitch appears each time I alt-tab or move a mouse cursor.

**Expected behavior:**

No visual glitches appearing on my display.

**Other Notes:**

My PC setup that is running Pop OS:
Motherboard: MSI PRO X670-P WIFI
CPU: AMD Ryzen 9 7900X
GPU:Gigabyte Radeon RX 7800 XT Gaming OC 16GB GDDR6
RAM: Lexar 32GB (2x16GB) 6400MHz CL32 Ares Gaming RGB (twice, so together it's 64 GB) 
Currently running 2 monitors. They are as follow: LG 27UL600-W 4K HDR and LG 27UL850-W 4K HDR. Both are 60 Hz.

Here's the list of stuff I tried to fix it:
Disabling hardware acceleration for both firefox and discord.
Running just firefox and watching amazon prime on it (all other apps disabled).
Switching from Wayland to X11 display server (same issue on both).
Changing old monitor cable with new high quality one.
Making sure my temps aren't too high for this type of GPU.
Disconnecting my camera that seemed to keep connecting and disconnecting.
Running "sudo kernelstub -a "i915.enable_psr=0" "

I didn't try to reinstall or change amd gpu drivers, as everyone says to not do this (if it's what I'm supposed to do I ask for a help/guide how to do it safely and correctly).

Also as I run dual boot, this issue isn't happening on Win11 (which I sit on for 8+ hours on each workday) so I don't believe this is a hardware issue.

**Comment by SpunkyMcGoo** [comment]
+1 to this, I've tested the RAM, VRAM, done stress tests, all turned up negative, AND I just had it start happening and i was able to trigger it by spamming alt+tab. it would do nothing, then i'd spam alt+tab or the super key and it would freak out, then go back to doing nothing when i idled.

**Comment by IkutiDev** [comment]
GPU drivers version:
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 7800 XT (radeonsi, navi32, LLVM 15.0.7, DRM 3.57, 6.7.9-060709-generic)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.0.3-1pop1~1711635559~22.04~7a9f319
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

Current Linux Kernel version is 6.7.9, since I read the bug report and downgraded the kernel via Mainline Kernels GUI App.

Before it happened on earlier 6.8.0 version, current Pop OS 6.8.0, and as well as 6.8.10.
According to that bug tracker it's still happening on 6.9.2 as well.

If the glitch doesn't happen today as well as tomorrow on kernel 6.7.9, I believe this was the issue and I will close this with comment for anyone having similiar problem in the future. And than just hope that on kernel 6.10.0 the issue is fixed :D

**Comment by IkutiDev** [comment]
After 5 hours of usage of Pop OS with kernel 6.7.9 the issue didn't appear again. So I'm guessing it was the kernel that was the issue, will be checking out fresh version of 6.9.x and 6.10.x and see if the future kernels finally fix it. Thanks for the help troubleshooting this!
