### ISSUE TITLE
Repackaging VS Code

### ISSUE THREAD

**Issue by mmstick** [pop-os/pop#333]
Microsoft is now providing a `postinst` script in their debian package, which adds their repository to the system's apt sources list. This causes a conflict due to apt wanting to get the same package from both our and Microsoft's repositories. We'll need to either A) implement repackaging within debrep to replace the postinst script, or B) build VS code from source. A will be the solution for now.

**Comment by luispabon** [comment]
It's a different discussion, but all the IDEs including vscode are already available as snaps, not sure why you guys are complicating your lives so much reinventing the wheel here. First thing I do after installing Pop is to install snapd.

**Comment by luispabon** [comment]
Building electron apps is harder than it looks. Many of the apps are very reliant on which exact version of electron (and by extension chromium) they need to link to, hence why they usually come statically linked. vscode in particular has been very conservative in this regard, and only recently upgraded to latest electron, which in turn only recently upgraded to latest chromium, which is good as it gave it the ability to rescale itself on the fly as needed (you need this if you're using hidpi daemon).

**Comment by mmstick** [comment]
@luispabon That may be state of Electron today, but it is not likely to always be the case in the future.

**Comment by mmstick** [comment]
The code package is now repackaged to exclude Microsoft's repo, and will be in the repos soon. You will want to remove the vscode repo (`sudo rm /etc/apt/sources.list.d/vscode.list`) now, so that you'll only receive the package from us.

**Comment by exanup** [comment]
Hi @mmstick, thanks for the update. However I'm still facing an issue. I have removed the vscode repo but I still get false upgrade notice.

When I run  `apt list upgradable -a` I get two entries as follows:
```
code/bionic 1.27.2-1536736588 amd64 [upgradable from: 1.27.2-1536736588]
code/now 1.27.2-1536736588 amd64 [installed,upgradable to: 1.27.2-1536736588]
```

And the output of `apt show code -a` is as follows:
```
Package: code
Version: 1.27.2-1536736588
Priority: optional
Section: devel
Origin: system76
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Installed-Size: 205 MB
Provides: visual-studio-code
Depends: libnotify4, libnss3 (>= 2:3.26), gnupg, apt, libxkbfile1, libgconf-2-4, libsecret-1-0, libgtk-3-0 (>= 3.10.0)
Conflicts: visual-studio-code
Homepage: https://code.visualstudio.com/
Download-Size: 45.4 MB
APT-Sources: http://apt.pop-os.org/proprietary bionic/main amd64 Packages
Description: Code editing. Redefined.
 Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. See https://code.visualstudio.com/docs/setup/linux for installation instructions and FAQ.

Package: code
Version: 1.27.2-1536736588
Status: install ok installed
Priority: optional
Section: devel
Maintainer: Microsoft Corporation <vscode-linux@microsoft.com>
Installed-Size: 205 MB
Provides: visual-studio-code
Depends: libnotify4, libnss3 (>= 2:3.26), gnupg, apt, libxkbfile1, libgconf-2-4, libsecret-1-0, libgtk-3-0 (>= 3.10.0)
Conflicts: visual-studio-code
Replaces: visual-studio-code
Homepage: https://code.visualstudio.com/
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: Code editing. Redefined.
 Visual Studio Code is a new choice of tool that combines the simplicity of a code editor with what developers need for the core edit-build-debug cycle. See https://code.visualstudio.com/docs/setup/linux for installation instructions and FAQ.
```

**Comment by exanup** [comment]
@mmstick May be I didn't quite understand you, but enabling MS repo after disabling Pop's proprietary  repo solved false "upgrade available" message for me. What I did is:
* Disabled Pop's proprietary repo
* Enabled only Microsoft's repo
* `sudo apt update && sudo apt install code`

Now, `sudo apt update` didn't produce the "upgrade available" message anymore.
But the moment I enable Pop's proprietary repo (after disabling MS one), the issues resurfaces.

**Comment by mmstick** [comment]
It could be that `dpkg` or `apt` in 18.04 has issues with Debian packages that contain a `control.tar.xz`. The version of `dpkg-deb` in 18.04 defaults to uniformly compressing both the data and control archives with `xz`. I'll try passing `--no-uniform-compression` and see if the next update fixes it.

**Comment by mmstick** [comment]
Doesn't seem to be the issue. The deb file is fine.

**Comment by newcoderlife** [comment]
I just reinstall pop-os today and find this 'update problem'. Seems it haven't been fixed yet.
