### ISSUE TITLE
start menu offered Deluge and Orion bittorrent clients, but cannot be found them in repos

### ISSUE THREAD

**Issue by jeanrajotte** [pop-os/pop#3332]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

start menu offered Deluge and Orion bittorrent client, but cannot be found in repos

**Steps to reproduce (if you know):**

type "torrent" in start menu

**Expected behavior:**

Discover should find it since it offered it but it reports

**Other Notes:**

**Comment by jeanrajotte** [comment]
hmmmm... Type "torrent" IN DISCOVER and it finds and can install Deluge. Oh well. You decide whether it's a valid bug. Thanks.

**Comment by leviport** [comment]
Are you talking about the "available to install" options at the bottom of the App Library? If so, it's probably also showing you Flatpak results that are available to install, which is expected. 

Since it sounds like this isn't a bug, I'm closing. If I'm mistaken, we can reopen it.
