### ISSUE TITLE
Missing support information

### ISSUE THREAD

**Issue by buhtz** [pop-os/pop#3338]
Hello,
I am not a PopOS user and don't have an instance installed. I am just an upstream maintainer dealing with one of your users.

Looking to your website I was not able to find information about the different versions of PopOS and how long they are supported and what "support" really means.

Would be nice if you could at that to your page.

**Comment by mmstick** [comment]
It's the same as Ubuntu. LTS + whatever we provide to download.

**Comment by daveTheOldCoder** [comment]
This Wikipedia page _seems_ to be accurate:
https://en.wikipedia.org/wiki/Pop!_OS

I'm only a Pop!_OS user, so I don't know if the information there is "official".
