### ISSUE TITLE
Online searchable package repository

### ISSUE THREAD

**Issue by buhtz** [pop-os/pop#3339]
Hello,
I am not a PopOS user and don't have an instance installed. I am just an upstream maintainer dealing with one of your users.

I was not able to find a way to search your package repository. I don't know which packages you offer, which version and where are they from (e.g. your own repo or copied from canoncial, or copied from ubuntu community "universe", or or).

Do you have a web based package search for non-popos users like me?

**Comment by buhtz** [comment]
Related to https://github.com/pop-os/website/issues/19

**Comment by mmstick** [comment]
You're looking at it. GitHub is our repository.  Packages are published to our apt repository here: https://apt.pop-os.org/release/

**Comment by buhtz** [comment]
> You're looking at it. GitHub is our repository. Packages are published to our apt repository here: https://apt.pop-os.org/release/

Hello Michael,
thank you for the quick reply.
I meant deb-file packages. The link you provided is not searchable. The directory names are not self explaining. I see no version numbers. It doesn't help if you are not an PopOS user.

**Comment by mmstick** [comment]
The deb  files are in there, and those are built from repositories here on GitHub. Search either.

**Comment by mmstick** [comment]
Use https://packages.ubuntu.com/ for packages not in our repositories.
