### ISSUE TITLE
Pop!_OS 24.04 LTS alpha COSMIC Epoch 1 (alpha 1) Fails to Boot to Installer

### ISSUE THREAD

**Issue by crftbt** [pop-os/pop#3348]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 24.04 LTS alpha COSMIC Epoch 1 (alpha 1)
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:** Fails to boot to installer and stuck at  ```[OK] Finished casper-md5check.service -...md5check Verify Live ISO Checksum.e```
![Screenshot_popos24 04alpha-cosmic_2024-08-08_11:33:59](https://github.com/user-attachments/assets/244c97a4-033c-4e46-9255-09da93f3b949)

**Steps to reproduce (if you know):** Download the AMD iso and confirm it's `sha256sum`. Setup a virt-manager/libvirt vm and boot the iso.
```
$ sha256sum ~/Downloads/pop-os_24.04_amd64_intel_9.iso 
894bc15abcad05839b226655121a113ad16cfbc4ada98e93e3ffb74a853fdcd4 
```

**Expected behavior:** Expected to boot into installer.

**Other Notes:** This was tested with 1vCPU and 8GB RAM (same behavior with 4GB RAM).

**Comment by crftbt** [comment]
Solved this by using the virt-manager ubuntu 24.04 template instead of the popos template.

**Comment by ElBrigos** [comment]
Hey, I have the same problem on Vmware workstation 17.5.2 build-23775571

The problem is probably Vmware and not POP OS 24.04 LTS Cosmetic Epoch 1

But if anybody have solution, share it ;)

**Comment by crftbt** [comment]
> Hey, I have the same problem on Vmware workstation 17.5.2 build-23775571
> 
> The problem is probably Vmware and not POP OS 24.04 LTS Cosmetic Epoch 1
> 
> But if anybody have solution, share it ;)

Sounds like something to contact vmware support about, particularly since they're closed source.

**Comment by mmstick** [comment]
@ElBrigos Similar to virt-manager, make sure to enable GPU acceleration in your VM.

**Comment by ElBrigos** [comment]
Hi @mmstick ! Thx you, it work's !

**Comment by crftbt** [comment]
Just came back to leave another message that the popos 20.10 template also fails to work with virt-manager for the Epoch Alpha 2 release of Pop_OS! 24.04 alpha. The ubuntu 24.04 template still works.
