### ISSUE TITLE
Password shows up in plain text after couple of logouts under Wayland!

### ISSUE THREAD

**Issue by MTomic2003** [pop-os/pop#336]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure about which package causes a bug.

**Issue/Bug Description:**
There is a critical security flaw where after couple of logouts under Wayland causes the password to show up in plain text on the screen. It "prints" out in a terminal-like form.

**Steps to reproduce (if you know):**
1) On login screen, select your account and click on the gear icon.
2) Select 'Pop on Wayland'.
3) Log in, log out. Log in, log out, etc.
After few logouts you might see your password in plain text shown on a terminal-like screen.

**Expected behavior:**
The terminal-like screen should at least be empty.

**Other Notes:**
This problem may not be the problem with Pop!_OS directly, but since I'm not sure where it comes from, I needed to post it somewhere.
For me, it showed up for a split second. Not sure if lack of performance makes it show up for longer time.

**Comment by brs17** [comment]
@MTomic2003 I am going to close this issue as it is a duplicate of https://github.com/pop-os/pop/issues/292. Feel free to provide any additional information that was not provided there.
