### ISSUE TITLE
Add open source apps to the pop repo:

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#34]
_From @sarahpandabeara on October 9, 2017 15:27_

Atom: popular, fitting our customers, and should be installable from the included repos
Mattermost: the tool used for our community communications
Telegram: There's an active system76 community

_Copied from original issue: pop-os/iso#127_

**Comment by isantop** [comment]
_From @kylerchin on October 9, 2017 20:32_

+1 for Atom and Brave Browser...

**Comment by isantop** [comment]
_From @jackpot51 on October 12, 2017 18:33_

Due to the amount of time required to do this, I am moving it to Post-Release

**Comment by brs17** [comment]
The apps mentioned were added to the Pop!_Shop in the Pop!_Picks. Does that mean this issue can be closed? If not what action items would still be desired?
