### ISSUE TITLE
<html>Cannot obtain lock:<br/><br/>E: dpkg was interrupted, you must manually run &apos;dpkg --configure -a&apos; to correct the problem.  </html>

### ISSUE THREAD

**Issue by Ishmael78** [pop-os/pop#3416]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by TheGroundZero** [comment]
Had the same this morning.
I believe it's related to an update of VSCode where Microsoft wants to add their own apt source.

Run `dpkg --configure -a` to fix the issue.

**Comment by leviport** [comment]
This article should help: https://support.system76.com/articles/package-manager-pop
