### ISSUE TITLE
Icon of installed application dont show up at teh dock

### ISSUE THREAD

**Issue by lorensiusdoni** [pop-os/pop#3418]
**Distribution (run `cat /etc/os-release`):**
 Pop!OS 24.04 Alpha 4
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Goggle Chrome, Docker Desktop

**Issue/Bug Description:**
Icon is not show at the docker after running the application

**Steps to reproduce (if you know):**

**Expected behavior:**
Show the application icon

**Other Notes:**
![screenshot-2024-12-12-01-32-40](https://github.com/user-attachments/assets/4586278e-cd02-4eac-8ad3-a1cb0f175e71)

**Comment by leviport** [comment]
Duplicate of https://github.com/pop-os/cosmic-applets/issues/667
