### ISSUE TITLE
Invisible upgradable package

### ISSUE THREAD

**Issue by TheGroundZero** [pop-os/pop#3419]
**Distribution (run `cat /etc/os-release`):**
 
 22.04 LTS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Shop

**Issue/Bug Description:**

Pop!_Shop always displays 1 upgradable package in the notification, but no package name is shown.

Pressing the `Upgrade all` button also doesn't seem to initiate any updates.

**Steps to reproduce (if you know):**

![image](https://github.com/user-attachments/assets/94b5ce6e-5c97-42cc-a878-6fc7f01a2a04)
![image](https://github.com/user-attachments/assets/cd53afe5-f3a2-4a2f-82a8-01bb77e8c3fd)

**Expected behavior:**

Show which package can be updated or do not display notification at all

**Other Notes:**

```sh
apt list --upgradable
Listing... Done
```

**Comment by leviport** [comment]
How about `flatpak update` ?

**Comment by TheGroundZero** [comment]
Ah, I did have a flatpak update available.
It involved a repo change, so required some manual verifications. Perhaps that's why Pop!_Shop didn't/couldn't finish the installation.
I'll monitor whether I see this notification pop up again
