### ISSUE TITLE
Packagekit update not working

### ISSUE THREAD

**Issue by KindledFlame** [pop-os/pop#3421]
**Distribution (run `cat /etc/os-release`):**

> NAME="Pop!_OS"
> VERSION="22.04 LTS"
> ID=pop
> ID_LIKE="ubuntu debian"
> PRETTY_NAME="Pop!_OS 22.04 LTS"
> VERSION_ID="22.04"
> HOME_URL="https://pop.system76.com"
> SUPPORT_URL="https://support.system76.com"
> BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
> PRIVACY_POLICY_URL="https://system76.com/privacy"
> VERSION_CODENAME=jammy
> UBUNTU_CODENAME=jammy
> LOGO=distributor-logo-pop-os
> 

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Package files:
 

> 100 /var/lib/dpkg/status
>      release a=now
>  100 http://apt.pop-os.org/ubuntu jammy-backports/universe i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-backports,n=jammy,l=Ubuntu,c=universe,b=i386
>      origin apt.pop-os.org
>  100 http://apt.pop-os.org/ubuntu jammy-backports/universe amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-backports,n=jammy,l=Ubuntu,c=universe,b=amd64
>      origin apt.pop-os.org
>  100 http://apt.pop-os.org/ubuntu jammy-backports/main i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-backports,n=jammy,l=Ubuntu,c=main,b=i386
>      origin apt.pop-os.org
>  100 http://apt.pop-os.org/ubuntu jammy-backports/main amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-backports,n=jammy,l=Ubuntu,c=main,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/multiverse i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=multiverse,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/multiverse amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=multiverse,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/universe i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=universe,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=universe,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/restricted i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=restricted,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/restricted amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=restricted,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/main i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=main,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-updates,n=jammy,l=Ubuntu,c=main,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/multiverse i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=multiverse,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/multiverse amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=multiverse,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/universe i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=universe,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=universe,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/restricted i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=restricted,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/restricted amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=restricted,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/main i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=main,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy-security/main amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy-security,n=jammy,l=Ubuntu,c=main,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/multiverse i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=multiverse,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/multiverse amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=multiverse,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/universe i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=universe,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=universe,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/restricted i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=restricted,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/restricted amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=restricted,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/main i386 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=main,b=i386
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
>      release v=22.04,o=Ubuntu,a=jammy,n=jammy,l=Ubuntu,c=main,b=amd64
>      origin apt.pop-os.org
>  500 https://repo.protonvpn.com/debian stable/main all Packages
>      release o=proton-gitlab,n=stable,c=main,b=all
>      origin repo.protonvpn.com
>  500 https://repo.protonvpn.com/debian stable/main amd64 Packages
>      release o=proton-gitlab,n=stable,c=main,b=amd64
>      origin repo.protonvpn.com
> 1001 http://apt.pop-os.org/release jammy/main i386 Packages
>      release v=22.04,o=pop-os-release,a=jammy,n=jammy,l=Pop!_OS Release,c=main,b=i386
>      origin apt.pop-os.org
> 1001 http://apt.pop-os.org/release jammy/main amd64 Packages
>      release v=22.04,o=pop-os-release,a=jammy,n=jammy,l=Pop!_OS Release,c=main,b=amd64
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/proprietary jammy/main all Packages
>      release v=22.04,o=system76,a=jammy,n=jammy,l=System76,c=main,b=all
>      origin apt.pop-os.org
>  500 http://apt.pop-os.org/proprietary jammy/main amd64 Packages
>      release v=22.04,o=system76,a=jammy,n=jammy,l=System76,c=main,b=amd64
>      origin apt.pop-os.org

**Issue/Bug Description:**

packagekit update 1.2.5-2ubuntu3 will not update, returns the following message: 

Cannot obtain lock:
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem. 

Doing so and then trying again returns the following message:

The PackageKit daemon has crashed:

The PackageKit daemon has crashed

And trying again returns it to the first error messaage

**Expected behavior:**

The update completes with no errors or issues

**Other Notes:**

Running KDE as my desktop environment and mainly trying to use the Discover Software Center for this update, also tried updating with the COSMIC Store instead of Discover only to get the same error messages

**Comment by mmstick** [comment]
Did you follow the instructions in the message?

```
E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.
```

**Comment by KindledFlame** [comment]
I did to my knowledge, I used the command in the console (or konsole since this is on KDE) with sudo privileges. Nothing happens immediately so I then try updating packagekit from Discover again which gives the other message.

> The PackageKit daemon has crashed:
> 
> The PackageKit daemon has crashed

**Comment by roveda** [comment]
For me worked:
```
sudo dpkg --configure -a
sudo apt update
sudo apt upgrade
```

But I had to use these commands two times.

**Comment by KindledFlame** [comment]
Thank you very much! It has worked for me.

**Comment by Jojo3d** [comment]
Thanks, work form me too.

**Comment by vladotoka** [comment]
@roveda Thanks, worked for me too. I also had to use these commands two times.

**Comment by JeNeSuisPasDave** [comment]
@roveda That also worked for me. Thank you!
