### ISSUE TITLE
Don't reboot after close and open the lid of laptop

### ISSUE THREAD

**Issue by jrph** [pop-os/pop#343]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Lid hardware

**Issue/Bug Description:**
after close and open the lid of laptop the display only stay in black and don't restart the session

**Steps to reproduce (if you know):**
Close the lid
open the lid
vuala, black screen

**Expected behavior:**
login screen

**Other Notes:**
laptop asus x556ur

**Comment by jackpot51** [comment]
Does your laptop have an NVIDIA card and is the `nvidia-graphics-driver-390` package installed?
