### ISSUE TITLE
Unable to change screen brightness on Oryx Pro 4 with Dvorak keyboard layout

### ISSUE THREAD

**Issue by Spoons** [pop-os/pop#344]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**
When the Dvorak  keyboard layout has been added to the  available keyboard inputs, the system will no longer respond to changes with the brightness controls after a system sleep. Sometimes the system needs to sleep twice before the display brightness becomes unresponsive. When the display becomes unresponsive, neither the hardware keys, F7 or F8, or the software brightness slider can adjust it. Upon pressing either hardware keys, an error is logged in dmesg.

**Steps to reproduce (if you know):**

Install PopOS
Add Dvorak to the list of layouts.
Reboot
Log in
Sleep the computer x2
Attempt to adjust display brightness.

I have found this to be reproduceable.

**Expected behavior:**

Display brightness will be adjustable after sleep.

**Other Notes:**
After a reboot, the display brightness adjustment will work again until slept.
If the Dvorak layout is removed, leaving only qwerty, and the system rebooted. Display adjustment will continue to work fine after sleep. The problem only occurs when the Dvorak layout has been added.

When the Dvorak layout is initially added to the Pop! system, the keyboard will not change to it properly. The gnome indicator will indicate the layout has been changed but the system will continue to use Qwerty. It will not change to Dvorak until after a reboot.

Additionally,  I have found this causes problems with xdotool. 

[dmesg.txt](https://github.com/pop-os/pop/files/2320043/dmesg.txt)

**Comment by m160** [comment]
This appears to be the same issue as I'm having. One of the first things I did when I got my Oryx Pro was to add a Norwegian keyboard to the available inputs and I've had this problem from the very begininng.

System does not necessarily have to sleep in my case. It happens after the display goes blank as a result of the power settings, after closing the lid and opening it again, when changing resolution or refresh rate, whenever the display turns off and on again even for just a brief second the screen brightness gets stuck at full brightness.

It's not 100% consistent though. I'd say it gets stuck about 90% of the time.

A reboot fixes it, but also logging out makes the screen brightness snap back to where it's supposed to be. When logging in it works as long as the display is on.

**Comment by brs17** [comment]
Are these issues on the 15" or 17" model of the Oryx Pro 4?

**Comment by Spoons** [comment]
I have the 17" as well.

**Comment by brs17** [comment]
This issue sounds to me a lot like https://github.com/pop-os/system76-driver/issues/59 (which happens regardless of keyboard layout). Using the steps to reproduce that I mention in that issue, can you recreate the issue on a different keyboard layout?

**Comment by Spoons** [comment]
I agree. It sounds like the same issue.

My experience has been that the issue only happens when I have the Dvorak layout added to the layout list. The issue did not occur when Qwerty was the only layout added to the "Input Sources" menu. This could be coincidence but I was unable to replicate it with only the Qwerty layout added to input sources. As soon as I add Dvorak to the list, the display brightness stops responding shortly after.

**Comment by brs17** [comment]
Awesome, if you don't mind then, I would like to then consolidate the two conversations into one so I am going to close this issue.
