### ISSUE TITLE
When you enable "battery percentage" in the gnome tweak tool, the accurate battery icon goes away and is replaced with the three dot indicator.

### ISSUE THREAD

**Issue by ghost** [pop-os/pop#351]
![screenshot from 2018-09-04 20-03-30](https://user-images.githubusercontent.com/24643378/45063771-c8bc8a00-b07d-11e8-8261-e407723f3296.png)

**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-tweak-tool:
  Installed: (none)
  Candidate: 3.28.1-1
  Version table:
     3.28.1-1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu bionic/universe i386 Packages

**Issue/Bug Description:**

When you enable "battery percentage" in the gnome tweak tool, the accurate battery icon goes away and is replaced with the three dot indicator.

**Steps to reproduce (if you know):**

enable battery percentage in gnome tweak tool

**Expected behavior:**

a clean battery indicator next to a percent number

**Other Notes:**

when you first turn it on, it works as expected. About a day later I noticed that it was the ugly gnome 3 bar indicator. when you hover over the menu, it returns to normal. when you battery percentage off and on again, it fixes the bug for a short while.

**Comment by bflanagin** [comment]
Good news! Things are working as expect in 20.10 
Closing ticket due to age, if your issue reappears in 20.04 or 20.10 reopen this ticket and we'll have a look.
