### ISSUE TITLE
Ctrl/Control key stops working on remote connections with remmina and Chrome Remote Desktop

### ISSUE THREAD

**Issue by ximinez** [pop-os/pop#352]
**Distribution (run `cat /etc/os-release`):**
 
 ```
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
$ apt policy remmina
remmina:
  Installed: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Candidate: 1.2.0-rcgit.29+dfsg-1ubuntu1
  Version table:
 *** 1.2.0-rcgit.29+dfsg-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

$ apt policy google-chrome-stable 
google-chrome-stable:
  Installed: 69.0.3497.81-1
  Candidate: 69.0.3497.81-1
  Version table:
 *** 69.0.3497.81-1 500
        500 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
(I'm not sure that `google-chrome-stable` is the right package, but Chrome Remote Desktop is a Chrome app available from https://chrome.google.com/webstore/detail/chrome-remote-desktop/gbchcmhmhahfdphkhkmpfmihenigjmpp?utm_source=chrome-app-launcher-info-dialog. In fact, I'm not even sure `remmina` should be implicated, as described below.)

**Issue/Bug Description:**

When connecting to a remote desktop using either VNC (to a linux server) or RDP (to a Windows server) protocol in `remmina` or whatever protocol Chrome Remote Desktop (CRD) uses, the ctrl key eventually stops responding on the remote desktop. For example, I type a command on the command line, and press `Ctrl+u` to wipe the line, and I just get a `u`. I start a long running command, and press `Ctrl+c` to stop it, and see a `c` on the terminal, and the program keeps running. It's as if the `Ctrl` key is not functioning (or more likely, is not being passed to the remote host). The problem is intermittent in that on a fresh connection, `Ctrl` will sometimes work for a while, and on rare occasions after stopping, it'll start working again. This is anything but predictable or reliable.

I have narrowed the problem (as best as I can) down to Pop OS and/or the keyboard driver.

1) For a while, I only used `remmina` to connect to the linux host to do occasional remote admin functions, so I was able to work around the issue.
2) This week, I added a new Windows box to my network for development work. I intend to run it mostly-headless. At first, things were fine, so I assumed the problem was a fluke. However, by the end of the day, I had lost `Ctrl`, and couldn't get it back.
3) Thinking now that the problem was `remmina`, I installed CRD. Same problem cropped up almost immediately.
4) Now thinking the problem was hardware related (external keyboard, KVM, etc.), I recreated the connection on another model of Pop OS machine. Same issue. I also disconnected any potentially problematic hardware and the problem persisted.
5) Finally, I recreated the connection on a stock Ubuntu 18.04 box (older System76 hardware), and haven't had a problem, despite having the connection up all day. I plugged in the same keyboard hardware to that box just in case and had no problems.

**Steps to reproduce (if you know):**

I've sort of described this above, but to summarize:
1) Use `remmina` or CRD to connect to a remote desktop.
2) Use the connection to do some typing.
3) After some time (but usually very little), the `Ctrl` key will no longer function on the remote desktop.

**Expected behavior:**

The `Ctrl` key should function for the entire duration of the remote desktop session.

**Other Notes:**

`remmina` defines the right `Ctrl` key as a sort of meta key for the app, so normally only the left key is relevant. I didn't make that mistake. And even I had, I wouldn't have seen the symptoms I did. Nor would it have been an issue in CRD.

**Comment by ximinez** [comment]
@brs17 

> Is this machine you are having issues with a System76 machine?
Yes. All three of the machines I described are from System76. The primary is a Galago Pro, the one where I reproduced the problem is a Lemur, and the one running base Ubuntu that didn't have the problem is a 5 year old Galago UltraPro. 

> From the sounds of it, you never have an issue with the Ctrl key doing things locally, only when remoting in to a different machine, correct?

That is correct.

**Comment by brs17** [comment]
That is definitely odd that you have only had the issue on Pop!_OS, I think I will close this issue for now as there is a pretty straight forward solution to the problem.

**Comment by maxio-co** [comment]
Hi All
Having the same issue on elementary OS 5.1 on remote desktop connecitons.
Same in VM or physical hardware.

""Cheers
Gerardo

**Comment by maxio-co** [comment]
Quick FYI just found the solution - i noticed that when pressing CTRL repeatedly the mouse courser would blink, found that in settings > mouse > pointing > "Reveal Pointer" was turned on.

It may be a default setting as i cant remember turning this on.

Once it was turned off CRTL started working in the remote session again.

you don't notice how much you need that key until you are trying to perform a short cut for search in remote sessions or need to kill a command.

Hope this helps anyone out there with a similar issue.

""Cheers
Gerardo

**Comment by puvi7722** [comment]
@maxio-co Thank you. I have been looking for this fix on my elementary.

**Comment by grasflocke** [comment]
@maxio-co thanks a lot! Deactivating the option "Keyboard & Mouse" > "Pointer Location" in gnome-tweaks solves the ctrl-c problem for Chrome Remote Desktop on Ubuntu 20.04 LTS.

Just leaving this comment here for all the other lost Ubuntu users who didn't think that this option could interfere with ctrl key bindings in Chrome Remote Desktop.

Cheers

**Comment by CaglayanDokme** [comment]
> @maxio-co thanks a lot! Deactivating the option "Keyboard & Mouse" > "Pointer Location" in gnome-tweaks solves the ctrl-c problem for Chrome Remote Desktop on Ubuntu 20.04 LTS.
> 
> Just leaving this comment here for all the other lost Ubuntu users who didn't think that this option could interfere with ctrl key bindings in Chrome Remote Desktop.
> 
> Cheers
Worked for me too, thanks a lot.

**Comment by abdelkareemkobo** [comment]
After 6 years, i have the same issue. 
I am using popos and installed the RPM version and the keyboard is not working. 
when i toggle the use client keyboard mapping, the nomral numbers are working but super keys liek CTRL and backspace are not. 
when i toggle it again and choose the the keyboar layout no thing happend.
I toggled also the grab all keyboard events.
