### ISSUE TITLE
"Do Not Disturb" shows error on Gnome's Installed Extensions page

### ISSUE THREAD

**Issue by colans** [pop-os/pop#354]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

colan@leopard[Thu 13 9:38]% apt policy gnome-shell-extension-do-not-disturb                                                                
gnome-shell-extension-do-not-disturb:
  Installed: 0.1.0~1525996283~18.04~e924d6c
  Candidate: 0.1.0~1525996283~18.04~e924d6c
  Version table:
 *** 0.1.0~1525996283~18.04~e924d6c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

The "Do Not Disturb" Gnome extension shows ERROR on Gnome's Installed Extensions page.  instead of the on/off switch, just says ERROR, and no other info.  (It is still configurable, however.)

**Steps to reproduce (if you know):**

Nothing; it's always shown an error to my knowledge.

**Expected behavior:**

The extension should not show an error.

**Other Notes:**

I couldn't find any other issues about this here, or in [the upstream issue queue](https://github.com/kylecorry31/gnome-shell-extension-do-not-disturb/issues).

Here's some more info:

```sh
% sudo journalctl /usr/bin/gnome-shell -f
[...]
Aug 01 17:42:49 leopard gnome-shell[1772]: st_widget_get_theme_node called on the widget [0x560a6f487450 StBoxLayout ("Do not disturb")] which is not in the stage.
Aug 01 17:42:49 leopard gnome-shell[1772]: st_widget_get_theme_node called on the widget [0x560a6f4b7630 StBoxLayout.popup-menu-item do-not-disturb:last-child first-child ("Do not disturb")] which is not in the stage.
[...]
```

These have no effect:

```sh
sudo apt install --reinstall gnome-shell-extension-do-not-disturb
sudo dpkg-reconfigure gnome-shell-extension-do-not-disturb
```

**Comment by colans** [comment]
Thanks!

The only non-system extensions I have enabled are:

- https://extensions.gnome.org/extension/36/lock-keys/
- https://extensions.gnome.org/extension/120/system-monitor/
- https://extensions.gnome.org/extension/495/topicons/

**Comment by kylecorry31** [comment]
Thanks, I will look into this.

**Comment by kylecorry31** [comment]
Hello, just a follow up on this. Have you changed any of the settings for the Do Not Disturb extension?

**Comment by colans** [comment]
I don't remember what the defaults are, but I have:

* Enabled Icon: On
* Mute Sounds: On
* Hide Notification Dot: Off

**Comment by kylecorry31** [comment]
This should be fixed, do you still experience any issues?

**Comment by colans** [comment]
Still getting the same error after rebooting.  Would providing the same log data again be useful?

**Comment by kylecorry31** [comment]
Try installing the extension from the GNOME extension store, maybe Pop! isn't using the latest version yet.

https://extensions.gnome.org/extension/1480/do-not-disturb/ 

Let me know if that clears up the issues (you may have to restart your shell: `Alt-F2` then `r`), if not please provide the log again (use `journalctl -b 0 | grep kylecorry` to get errors specific to the extension)

**Comment by jackpot51** [comment]
I will make sure we have released the latest version

**Comment by colans** [comment]
Thanks.  Seems like the error went away after I removed the old version and installed the new one.  I then had two switches, but the old one went away after restarting the shell.
