### ISSUE TITLE
Consider adding Yaru icons

### ISSUE THREAD

**Issue by jbicha** [pop-os/pop#360]
Ubuntu 18.10 has switched its theme to Yaru. Please consider offering icons in this style for the Yaru theme. You could either install them yourself or submit a pull request to https://github.com/ubuntu/yaru to have them shipped by the Yaru theme directly. Note that the Yaru icons are licensed as CC-BY-SA-4.0.

See the [Suru icon guidelines](https://snwh.org/suru/guidelines). (Yaru is basically Suru.)

Here's a screenshot. As you can tell, I have other apps installed that have missing icons. The Suru style is rounded rectangles. At this time, I expect Firefox and Thunderbird to keep their upstream app icons.

![ubuntu-18-10-suru](https://user-images.githubusercontent.com/876259/46259363-6ac96980-c4a6-11e8-947b-51d47a5c40fd.png)

**Comment by alosarjos** [comment]
This can be closed since the icons are offered by Ubuntu repos as `yaru-theme-icon`
