### ISSUE TITLE
Pop!_OS 18.10 About page incorrectly labels OS

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#363]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 18.10 debug 8
 
**Issue/Bug Description:**
OS is listed as `Pop!_OS 18.10 LTS`.

Should probably just be `Pop!_OS 18.10`.

**Comment by brs17** [comment]
Screenshot:

![bug363](https://user-images.githubusercontent.com/7460774/46561350-840e5380-c8b4-11e8-820d-4e901493c933.png)

**Comment by jackpot51** [comment]
@brs17 this should be fixed now

**Comment by jackpot51** [comment]
Check in the `master` staging repo

**Comment by brs17** [comment]
Fixed!
