### ISSUE TITLE
Icons are in color when they should be monochromatic

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#365]
**Distribution (run `cat /etc/os-release`):**
 18.10 debug 8
 
**Issue/Bug Description:**
Color icons exist in the System Menu when they should be monochromatic.

![bug365](https://user-images.githubusercontent.com/7460774/46562168-1cf29e00-c8b8-11e8-84bf-3dc58da6d7e0.png)

**Comment by jackpot51** [comment]
This looks like an intentional decision in gnome-shell. I see these icons are specified as color variants. I will update our suspend button extension to change all the icons

**Comment by brs17** [comment]
Fixed here: https://github.com/pop-os/gnome-shell-theme/pull/56
