### ISSUE TITLE
Certain applications are not in the correct folders

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#366]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 18.10 debug 8
 
**Issue/Bug Description:**
In the Activities list of all of the programs, certain programs should be in a folder but are not. Those programs are:

Archive Manager should be in Utilities Folder
Document Viewer should be in Utilities Folder
Videos should be in the Utilities Folder

**Comment by jackpot51** [comment]
This is an issue in https://github.com/pop-os/default-settings. I will put the fixes into `master_cosmic`, as I have done with other cosmic-related bugs

**Comment by jackpot51** [comment]
This should be fixed by https://github.com/pop-os/default-settings/commit/cc9d7df30c8346c4e93f453a64d9a429c395e152
