### ISSUE TITLE
NVIDIA iso returns ACPI errors, does not boot successfully into live image

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#373]
**Distribution (run `cat /etc/os-release`):**
 18.10 debug 14

**Issue/Bug Description:**
When attempting to boot the live image of 18.10 NVIDIA debug 14, the error: `ACPI Error: No handler or method for GPE XX, disabling event (xxxxxxxx/evgpe-xxx)` prints out constantly. The system does not boot into the live image. 

![img_20181016_085307](https://user-images.githubusercontent.com/7460774/47026099-ea4f6d80-d121-11e8-97dd-ba737e5843e5.jpg)

**Comment by jackpot51** [comment]
What system?

**Comment by brs17** [comment]
oryp4-b

**Comment by brs17** [comment]
Per @mmstick's suggestion I am going to try the Nvidia iso on other NVIDIA machines.

**Comment by brs17** [comment]
Well I just tried again (on a reflashed flash drive) and I am not having any issues :tada:
