### ISSUE TITLE
Unable to boot into Pop! OS, hangs on black screen permanently.

### ISSUE THREAD

**Issue by KorabU** [pop-os/pop#374]
**Distribution (run `cat /etc/os-release`):**

Pop! os 18.04
 
 **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop! os 18.04 Intel/AMD ISO

**Issue/Bug Description:**

i have gotten to the Pop! OS installer, gone through the process of replacing my windows install, but, when i hit the restart button the laptop shows the Dell logo, but boots into a permanently black screen until i force a restart
i have disabled secure boot, set SATA operations to AHCI and enabled legacy option ROMS in the bios and still no luck 

the laptop is a Dell inspiron 3552

intel celeron N3060
4GB of DDR3 RAM
500GB

**Steps to reproduce (if you know):**
**Expected behavior:**

actually booting into the OS lol

**Other Notes:**

i completely want to replace windows 10 with Pop! OS so anything shouldn't be an issue.

**Comment by mmstick** [comment]
You might want to try downloading the ISO / imaging the ISO again / installing it again, just to rule out any issues there. If you haven't already. Logs are created during install and stored to `/tmp/installer.log`, so you may want to attach that here if it continues to happen.

**Comment by KorabU** [comment]
@mmstick i've actually been trying to install the OS for the past 6 hours or so, and here is the Log created during each install https://anotepad.com/notes/4hwrj8

i can't figure out WHAT the issue is

**Comment by mmstick** [comment]
There's your issue:

```
WARN: Installing for i386-pc platform. WARN: grub-install: warning: this GPT partition label contains no BIOS Boot Partition; embedding won't be possible. WARN: grub-install: warning: Embedding is not possible. GRUB can only be installed in this setup by using blocklists. However, blocklists are UNRELIABLE and their use is discouraged..
```

You're not allowed to do a MBR install on a GPT disk layout.

**Comment by KorabU** [comment]
how do i fix it? sorry im quite new to all of this, if you could link a tutorial or something that would be greatly appreciated :)

**Comment by mmstick** [comment]
You need to ensure that the device you're booting from is booting into EFI mode. In your motherboard BIOS, you may have it configured to allow booting either EFI or Legacy MBR mode. If you get to the BIOS boot device selection screen, they'll usually also list two options for a device that can be booted into either mode.

**Comment by KorabU** [comment]
@mmstick would this work? https://www.disk-partition.com/articles/how-to-convert-gpt-to-mbr-without-operating-system-4125.html

**Comment by mmstick** [comment]
@KorabU No, you just want to boot the USB device in EFI mode.
