### ISSUE TITLE
Pop os with touchscreen  (Surface)

### ISSUE THREAD

**Issue by divtodiv** [pop-os/pop#375]
If you guys wanna try it out,
Its 1-week I'm running a different kernel for touchscreen and the UI is GREAT!
Check it out
https://github.com/jakeday/linux-surface

Still work in progress with some littlegs bugs

**Comment by brs17** [comment]
@divtodiv this issue you filed does not seem to be a problem with Pop!_OS but an interesting project that members of the Pop!_OS community may find interesting. Feel free to share things like this in the Pop!_Chat here: [chat.pop-os.org](https://chat.pop-os.org)
