### ISSUE TITLE
VPN DNS Not working

### ISSUE THREAD

**Issue by mabasic** [pop-os/pop#376]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 18.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
network-manager-openvpn-gnome/cosmic,now 1.8.6-1ubuntu1 amd64 [installed]
network-manager-openvpn/cosmic,now 1.8.6-1ubuntu1 amd64 [installed]
openvpn/cosmic,now 2.4.6-1ubuntu2 amd64 [installed]

**Issue/Bug Description:**
When I connect to the VPN I cannot resolve any host using nslookup.

I have asked on two different places on reddit:
https://www.reddit.com/r/Ubuntu/comments/9qjy1i/vpn_dns_not_working/
https://www.reddit.com/r/pop_os/comments/9qnzm0/vpn_dns_not_working/

I think that the OS does not use/detect the VPN DNS.

If I use specifically the DNS of the VPN as the DNS to query like so `nslookup nas-1 172.16.0.1` then I get the desired response.

**Steps to reproduce (if you know):**
Connect to any VPN and try to use nslookup to query for a host on the VPN network.

eg. `nslookup nas-1` or `nslookup nas-1.local`

**Expected behavior:**
I expect to normally use `nslookup` or any other network tool protocol with hostnames instead of IPs.

**Other Notes:**
I have tried doing the same thing with manjaro live and it works out of the box as expected. I have booted Pop!_OS 18.10 live and tried it on a fresh machine and the same issue happens.

**Comment by fadsm** [comment]
Same issue here. I can connect over terminal directly with sudo openvpn <filename>.ovpn
My packages are the same as yours. (1.8.6-1ubuntu1)

May you please let us know manjaro's versions?

**Comment by mabasic** [comment]
Manjaro Gnome Edition. Can't remember what version was it at that moment.
