### ISSUE TITLE
Multimonitor mixed DPI work

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#38]
_From @sarahpandabeara on October 5, 2017 22:32_

_Copied from original issue: pop-os/iso#121_

**Comment by isantop** [comment]
_From @cassidyjames on October 10, 2017 16:37_

I've noticed the System76 HiDPI driver thing works well here, except for losing the monitor layout.

**Comment by isantop** [comment]
_From @jackpot51 on October 10, 2017 17:10_

Losing the layout does not mean it works well

**Comment by isantop** [comment]
_From @cassidyjames on October 20, 2017 1:19_

Hence
> except for

**Comment by isantop** [comment]
_From @sarahpandabeara on October 20, 2017 16:24_

Is this issue related to the one that Sam and I are having with multiple monitors in workspaces? At least one display (not the main) has flickering from time to time when not in use.

**Comment by oksoft-ondra** [comment]
In /etc/gdm/Custom.conf comment Waylandsomething=false and after reboot select session Pop (no Pop(XORG)) and It will work!

**Comment by WatchMkr** [comment]
A new version of the hdmi daemon has been released that should fix this bug.

**Comment by cassidyjames** [comment]
Re-opening because losing the monitor layout is still a bug that needs to be fixed (per @WatchMkr).

**Comment by brs17** [comment]
With the latest release of the hidpi daemon monitor positioning is remembered when set in the Gnome display settings. 

Closing this issue, if problems remain, please reopen the issue and provide any available details.
