### ISSUE TITLE
Pop!_OS install seems to boot to stock Ubuntu

### ISSUE THREAD

**Issue by quietlychris** [pop-os/pop#380]
**Distribution:**
 Pop!_OS 18.04/18.10
 
**Issue/Bug Description:**
Hi there! I'm currently having a strange issue with the installation of Pop!_OS. I have written the .iso image to a bootable USB drive using Etcher, but when I attempt to boot from the drive, I don't proceed through the standard installation flow. The current flow starts with the Pop!_OS logo and a prompt indicating that the boot will begin (with a countdown, which can either run through or will be accepted by pressing 'ENTER'). In both cases, upon proceeding, I see various screens w/boot messages, and end up with what looks like a stock version of Ubuntu (classic Ubuntu stock background, UI, included programs), except the system information displays the computer name as "pop-os." At no point does the live boot/install prompt appear, nor does the Pop!_OS stock background/GNOME UI. I think this is a live image, since I try booting without the installation media included, I can't reproduce any of these features. 

The computer being flashed originally had Ubuntu 16.04 installed, although that is not the same actual image I'm seeing (no file crossover, different system details, etc.). The BIOS setting are UEFI with secure boot disabled, on a new Dell w/Xeon processor and NVIDIA graphics card. 

I've tried this installation with both NVIDIA and Intel drivers for 18.04/.10, as well as having built the .iso from source based on the GitHub repo's instructions. Furthermore, I have repeated this process with various other distros, including Debian, ParrotSec, and Ubuntu 18.04, all of which act as expected. The host computer I'm using to flash the bootable USB drive is running Pop!_OS 17.10. 

**Steps to reproduce (if you know):**
Standard Pop!_OS installation process (download .iso, use Etcher to create flash image to bootable USB drive, insert drive into computer to be flashed, choose desired boot location).

**Expected behavior:**
Pop!_OS installation prompts

**Other Notes:**
Please let me know if there is any add'l information I can offer that might be helpful, or if this issue should be moved somewhere else. Thanks!

**Comment by jackpot51** [comment]
What machine do you have? Does it have a dell recovery partition? It might be booting to that

**Comment by quietlychris** [comment]
The machine is a Dell Precision 5820 Tower, with a Intel Xeon W-2123 and NVIDIA Quadro P400, 512GB SSD. 

Dell says it doesn't [ship](https://www.dell.com/support/article/us/en/04/sln265982/how-system-recovery-and-backup-works-with-ubuntu-linux-on-your-dell-pc?lang=en) with a recovery partition included, and I don't believe that I made one at any point. I haven't been able to find anything that looks like a recovery on the drive, but if there's something specific I should look for, I'd be happy to check again.

I'm doing a sanity check and running through the process one more time with a fresh .iso download for 18.04, and will keep updated with details of how it goes.

**Comment by quietlychris** [comment]
Okay, update:

I'm still seeing the same behaviour. Here are the steps and some observations along the way:

- Downloaded fresh Pop!_OS 18.04 from System76 site
- Flashed drive using Etcher. This looked like sort of a two-step process compared with some of the other ones; a "flashing" step and then a "validating" step. I don't believe I've seen the validating step for other distros. The USB drive is now called "Pop_OS 19.04 amd64"
- Pulled USB drive from first computer, inserted into powered-down Dell 5820. 
- Powered on Dell. During power on, hit F12 key to enter Boot menu
    - The boot menu looks like this:

`

    Boot mode is set to: UEFI, Secure Boot: OFF
    LEGACY BOOT:

        USB Storage Device

    UEFI:

        UEFI: LITEON CVA-C1512-11 SATA 512 GB    <- selecting this option sends me to the current 16.04 install

        UEFI: Samsung Flash Drive FIT 1100

        UEFI: Samsung Flash Drive FIT 1100    <- this isn't a typo; there's actually two of these options
`
- From there, I see a screen with the (P_!) logo and a '[ (P_!) Try or Install Pop!_OS ]' button with a counter below it. I press `ENTER`
- Various boot screens flash, and I end up directly in what looks like a standard Ubuntu 16.04 desktop
    - Along the left side menu, we have: Chromium browser, various LibreOffice, Amazon
    - Also have: a disk icon called "UBUNTU" and a usb icon called "Pop_OS 18.04 amd64"
        - "UBUNTU" disk has the users & and info from my existing 16.04 install; when I create a folder on the desktop, it appears in ~/Desktop for pop-os@pop-os, not in the "UBUNTU" drive directory

After examining it in the disk utility, I see the USB drive I'm using to boot has two partitions in it, both labeled Pop!_OS 18.04, although the first is marked bootable, and the other is not. The first partition is the right size (2.0 GB ISO9660), while the other is a 2.9 MB FAT-12/EFI. Not sure if that's supposed to happen or not, but figured I'd remark on it. Other than that, the system information shows that the OS is Ubuntu 16.04, although the device name is "pop-os".  

That being said, it is possible there is a recovery drive somewhere, although I'm not certain how or why I'd be booting to it through this process (I've re-formatted the USB drive a couple times; there shouldn't be anything left on there). Any advice would be greatly appreciated, as I've really enjoyed using Pop!_OS. Thanks!

**Comment by mmstick** [comment]
@quietlychris Sounds like the USB device is not being loaded, but an EFI option on `LITEON CVA-C1512-11 SATA 512 GB` is getting loaded instead.

**Comment by quietlychris** [comment]
@mmstick @jackpot51 I agree, although I'm not exactly sure what to do about this. Unfortunately, it looks like I'm going to need to put this off for the time being (the workstation needs to be up and running shortly), although I'll continue to try booting from the USB when I have some time down the line. Thank you both for your time, and I'm happy to either close this issue or keep it open and update when I have any news

**Comment by jackpot51** [comment]
It appears as though the Pop ISO is booting into the Dell recovery partition. I believe this can be fixed with a new ISO, or by removing the recovery partition from the disk.

I will update this issue if we address the problem in Pop

**Comment by jmcalabrese** [comment]
I have the same issue on a 2016 Dell Precision 5510 with factory installed Ubuntu (14.04) and a recovery partition.

**Comment by m44te** [comment]
Same issue here on a 2018 Dell G5 5587 shipped with Ubuntu 16.04. Did anybody managed to install Pop? I tried the 18.04 and 18.10 Nvidia Pop ISO, none of them worked. Thank you in advance!

**Comment by m44te** [comment]
i removed the dell recovery partition with gparted and everything works fine now.

**Comment by agervasoni** [comment]
I have the same issue on a Dell Inspiron 3467. The strange thing is that, according to Dell, my PC doesn't have a recovery partition and I've been unable to locate one with either gparted or Disks. So where is this whole system coming from? Where is it stored? Also, once booted on this recovery mode (or whatever it is), if I open Disks and choose my Ubuntu partition, it says "Mounted at /media/pop-os/UBUNTU". I've tried everything, including updating the BIOS but I don't think it's a problem of my machine because I've been able to boot other systems from flash drives before.

**Comment by mmstick** [comment]
Yes, for whatever reason the firmware will decide to load the Ubuntu partition with Pop's parameters (setting the username / hostname to pop-os). Unsure why this happens, exactly.

**Comment by agervasoni** [comment]
@mmstick Yes, but the strange thing is that it loads the 16.04 version that came with the laptop, which I upgraded to 18.04 several months ago. How can this be? I don't have a recovery partition. @jackpot51 suggests that the recovery partition be removed… but there's no such partition in my HDD. In fact, gparted shows the following partitions:
Partition | Name | File System | Mount Point | Label | Size| Flags
/dev/sda1 | EFI system partition | fat32 | /boot/efi | ESP | 750 MiB | boot, esp
/dev/sda2 | Basic data partition | fat32 | --- | OS | 5.00 GiB | msftdata
/dev/sda3 | --- | ext4 | / | UBUNTU | 918.04 GiB |
/dev/sda4 | --- | linux-swap | --- | --- | 7.74 GiB |
I'm no expert on HDD partitions but my guess is that this 16.04 is stored on sda2. It can't be on sda3 (because that's where 18.04 is) or sda4, for obvious reasons, and it's too big for sda1. besides, Dell says there are no recovery files on my laptop. Does anyone have a clue?

**Comment by mmstick** [comment]
`/dev/sda2` does contain the recovery environment. We do this similarly with clean installs.

**Comment by agervasoni** [comment]
I knew it! Thanks! Do you know what would happen if I nuke that partition? Is it safe?

**Comment by mmstick** [comment]
Deleting it means you will no longer have the original recovery partition to boot to.
