### ISSUE TITLE
Unable to locate package ntfs-config

### ISSUE THREAD

**Issue by smkamranqadri** [pop-os/pop#381]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N: Unable to locate package ntfs-config

**Issue/Bug Description:**
Not able to install ntfs-config package, it's from ubuntu universe repo.

**Steps to reproduce (if you know):**
sudo apt install ntfs-config

**Expected behavior:**
Should have installed and I may be able to use/ mount auto USB drive with ntfs file system.

**Other Notes:**

**Comment by jackpot51** [comment]
ntfs-config was not published by Ubuntu for 18.10:

https://launchpad.net/ubuntu/+source/ntfs-config

You may be able to download the 18.04 package from that page
