### ISSUE TITLE
After Updating Not Able to Login with Nvidia Graphics; Freezes at Login

### ISSUE THREAD

**Issue by HymanZHAN** [pop-os/pop#385]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gdm3:
  Installed: 3.28.3-0ubuntu18.04.3pop0
  Candidate: 3.28.3-0ubuntu18.04.3pop0
  Version table:
 *** 3.28.3-0ubuntu18.04.3pop0 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     3.28.3-0ubuntu18.04.3 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
     3.28.2-0ubuntu1.4 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     3.28.0-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

pop-session:
  Installed: 2.0.5\~1527106467\~18.04\~c1e7b63
  Candidate: 2.0.5\~1527106467\~18.04\~c1e7b63
  Version table:
 *** 2.0.5\~1527106467\~18.04\~c1e7b63 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Just after a `sudo apt-get update && apt-get upgrade` today, my laptop started to slow down and became quite laggy. So after half an hour endurance, I rebooted the device. Then I am not able to log in with Nvidia Graphics. It would just freeze. If I try to log in with Intel / into Wayland session I am able to do so. However, performance is way poorer. Words on screen lagging behind my typing now.

**Steps to reproduce (if you know):**

Reboot with Nvidia Graphics on and try to log in to `Pop`, not `Pop Wayland`, which are my only two options for my login session.

**Expected behavior:**

Being able to login with Nvidia without any issue.

**Other Notes:**

None at the moment.

**Comment by jackpot51** [comment]
What machine are you running on?

**Comment by HymanZHAN** [comment]
@jackpot51 Asus UX501VW 
CPU: Intel I7 6700HQ
Graphics: GTX960M / Intel HD530

**Comment by HymanZHAN** [comment]
BTW I don't have the original system installed already. This is my daily machine for work and I need to have it running for today's work so I just wiped the machine and installed Pop_Os! 18.10 last night. It seems to work fine for now.

**Comment by jackpot51** [comment]
Oh, ok. Reopen the issue if it happens again.
