### ISSUE TITLE
OS freezes when openning libreoffice [nvidia version]

### ISSUE THREAD

**Issue by devlwkyan** [pop-os/pop#388]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

 

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

libreoffice

**Issue/Bug Description:**

Alrays when I try openning libreoffice, the system freezes (completely) and I need to reboot the computer.

**Steps to reproduce (if you know):**

Open libreoffice.

**Expected behavior:**

Open libreoffice.

**Other Notes:**

Also happens when I try to use any colour picker, but when It's with the colour picker besides freezing also the screen goes blank , and sometimes goes back to login screens and I need to reboot.

**Comment by devlwkyan** [comment]
Libreoffice 6.1.3

**Comment by brs17** [comment]
So I believe that that version is not yet in the Pop/Ubuntu repositories, so you're adding it yourself? How did you go about doing that?

**Comment by devlwkyan** [comment]
Well, first I had the one that came with popOS, as it had this issue, I've uninstalled it and reinstalled using the debian package from the site ( https://www.libreoffice.org/download/download/ ).

**Comment by brs17** [comment]
Interesting, I was unable to recreate the issue with the version of libreoffice that comes with a fresh install.

Could you post the output of `journalctl -b 0` after trying to launch libreoffice? I would like to see if there are any logs relating to this issue. If you cannot provide logs because of the system freeze `journalctl -b -1` should provide the logs of the previous boot.

**Comment by devlwkyan** [comment]
Well, I had to reinstall the popos on ym root directory, I believe some the issues could be some corruption on my kernel (I'm noy sure), but after reinstalling my on my root directory, I can open normally libreoffice, thank you anyway @brs17
