### ISSUE TITLE
Pop!_OS won't start because vboxadd-service.service failed to start.

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#39]
_From @Justin00015 on October 5, 2017 13:59_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```lsb_release -a```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**
When starting Pop on a VM, I see that it says "FAILED" for "Starting vboxadd-service.service." The VM then will just not do anything for an unlimited amount of time and forces me to force-shut-down the VM.

**Steps to reproduce (if you know)**
I turn on my VM and I get this message.

**Expected behaviour**
The VM should be able to start the service and boot properly.

**Other Notes**
The VM has EFI disabled. Here is a picture of what happens on the screen: [Picture](https://imgur.com/a/LlKr9)

_Copied from original issue: pop-os/iso#118_

**Comment by isantop** [comment]
@Justin00015 Are you still getting this issue with the latest build of Pop? Also, what VM Hypervisor are you using?

**Comment by WatchMkr** [comment]
Please re-open if this bug is still present.
