### ISSUE TITLE
"Switching Graphics" extension not visible

### ISSUE THREAD

**Issue by louistsaitszho** [pop-os/pop#390]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
gnome-shell-extension-system76-power:
  Installed: 1.0.0~1536965741~18.10~0cc2661
  Candidate: 1.0.0~1536965741~18.10~0cc2661
  Version table:
 *** 1.0.0~1536965741~18.10~0cc2661 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
The ["Switching Graphics" menu](https://support.system76.com/articles/graphics-switch-pop/) disappear. I just installed Pop!_OS 2 days ago, and at the beginning it shows up, and yesterday it just disappear. 

On the bright side, it still works with the `system76-power` command, and I seem to be able to switch between the 2. It's just that the menu is gone. 

**Steps to reproduce (if you know):**
No idea

**Expected behavior:**
See the switching graphics menu since
A) it was there 2 days ago
B) it still works through terminal

**Other Notes:**
I am not sure if this is a Pop!_OS issue or a `gnome-shell-extension-system76-power` issue.

**Comment by jackpot51** [comment]
Check what extensions are enabled in `gnome-shell-extension-prefs`

**Comment by louistsaitszho** [comment]
@jackpot51 yup it was disabled! that explains a lot! thanks!
