### ISSUE TITLE
Driverless printers don't always work automatically

### ISSUE THREAD

**Issue by valerie-makes** [pop-os/pop#391]
**Distribution (run `cat /etc/os-release`):**
 
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

cups-browsed

**Issue/Bug Description:**

Driverless printers don't work out-of-the-box - notifications are shown to indicate that they have been added, but when pressing "Print" in most applications, they do not show up in the list of printers.

**Steps to reproduce (if you know):**

1. Connect to a network with a driverless printer
2. Add the printer in settings / wait for it to be automatically added
3. Try to print something (e.g. a text file from gedit)

**Expected behavior:**

The printer shows up and works

**Proposed fix:**

Uncommenting `CreateIPPPrinterQueues All` in `/etc/cups/cups-browsed.conf` (and running `sudo systemctl restart cups-browsed`) fixes the problem - I think this should be the default configuration, so that these types of printers work out-of-the-box.

**Comment by mmstick** [comment]
Any consequences to enabling by default?

**Comment by davidbailey00** [comment]
@mmstick Not as far as I'm aware - the current behaviour seems much more confusing, given that a notification is still shown to say that the printer is added, but it's unusable.

**Comment by mmstick** [comment]
I'll submit a patched version of `cups-filters` to our proposed PPA soon, which should default to that setting. It would be great if you're willing to test it.

**Comment by davidbailey00** [comment]
> Looking at the source code, IPP_DRIVERLESS should be the default setting already.

Yeah, I think that must be the case, given it works briefly regardless of the config. Also, when it stops working, the printer still appears under Printers in Settings, but its options are blank - screenshots:

regardless of whether working or not working
![image](https://user-images.githubusercontent.com/4248177/49043217-5530a180-f1c2-11e8-9cab-25fc9ceb56d4.png)

only when working, i.e. just after running `sudo systemctl restart cups-browsed`
![image](https://user-images.githubusercontent.com/4248177/49043276-77c2ba80-f1c2-11e8-81de-53665b012522.png)

only when not working, i.e. a few minutes after restarting the service
![image](https://user-images.githubusercontent.com/4248177/49043182-3af6c380-f1c2-11e8-8b84-71b7629a78c8.png)

**Comment by mmstick** [comment]
If you haven't already, you might want to also report the issue to Launchpad against the `cups-filters` package / check if anyone has reported a similar issue.

**Comment by davidbailey00** [comment]
Hmm, after a while the printer seems to disappear from the settings panel - re-adding it manually seems to work now. So, now I'm not really sure if this is a consistent problem or just some kind of temporary glitch. Worth noting that when restarting the service (and having the printer re-added automatically), the following warnings are logged in `/var/log/cups/errror_log` (but not when re-adding it manually):

```
W [26/Nov/2018:21:29:57 +0000] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id \'Brother_DCP_9020CDW-Gray..\' already exists
W [26/Nov/2018:21:29:57 +0000] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id \'Brother_DCP_9020CDW-DeviceN..\' already exists
```

I don't know if this is what was causing it to fail though - not sure if it's worth keeping this issue open given that my problem is now fixed?
