### ISSUE TITLE
GIMP not available trough Pop!_Shop

### ISSUE THREAD

**Issue by forteller** [pop-os/pop#396]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pop-shop:
  Installed: 0.2.9~1543260272~18.10~ded150c
  Candidate: 0.2.9~1543260272~18.10~ded150c
  Version table:
 *** 0.2.9~1543260272~18.10~ded150c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu cosmic/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Searching for GIMP only gives the result shown in the screenshot. But I can still find and install it trough Synaptic.

![screenshot from 2018-12-11 15-53-36](https://user-images.githubusercontent.com/343561/49816004-4672ee80-fd6d-11e8-83e8-ab026881e10a.png)

**Steps to reproduce (if you know):**
- Open Pop!_Shop (or just the Gnome Dash)
- Search for GIMP

**Expected behavior:**

GIMP should be available trough the Pop!_Shop

**Other Notes:**

Thank you for you hard work making Linux better and available to more people!

**Comment by mmstick** [comment]
I wonder if it appears in GNOME Software. If not, the GIMP package in the repos may not be carrying appstream data.

**Comment by forteller** [comment]
I'd like to try, but installing it seems a bit… "not so fun"?
![Uploading Screenshot from 2018-12-11 17-55-38.png…]()

**Comment by mmstick** [comment]
Yes, GNOME Software's packaging is incompatible with ours.

**Comment by Dzeg** [comment]
I faced the same situtation looks like is not fixed yet.... had to install via terminal instead.

**Comment by im7FFY** [comment]
No problem nowadays on 19.04 to find it! (issue solved?)

**Comment by DanielPower** [comment]
Gimp is not available in the app store on 19.10, so I'm thinking this is still not solved.

**Comment by jacobgkau** [comment]
GIMP is available in the Pop!_Shop as both a Flatpak and a deb package, on both 20.04 LTS and 21.04.

![image](https://user-images.githubusercontent.com/7199422/122998814-c0d34f00-d36a-11eb-97e5-8a33a3c8deb6.png)
