### ISSUE TITLE
No icon thumbnails on Pops_OS 18.04

### ISSUE THREAD

**Issue by dfstorm** [pop-os/pop#398]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**
No icons thumbnails in gnome file manager (Nautilus) for every files and in any Apps that need a thumbnail. 

**Steps to reproduce (if you know):**
Install Pops_OS 18.04, open a file manager and go to a directory with images; no thumbnail. Open this image with EyeOfGnome (The default Gome image viewer) and display the "gallery"; no thumbnails. Upgrade the system; no change.

**Expected behavior:**
Icons with thumbnails.

![capture du 2018-12-12 00-16-19](https://user-images.githubusercontent.com/5215808/49836617-a2586a00-fda3-11e8-827d-77f3e381709e.png)
![capture du 2018-12-12 00-15-27](https://user-images.githubusercontent.com/5215808/49836606-9b315c00-fda3-11e8-94c7-6978454943d8.png)

**Comment by linhusp** [comment]
I have the same issue on my pops_os 18.04 LTS. Besides, this issue was gone when i upgraded my system to 18.10

**Comment by mmstick** [comment]
issue is caused by the package not installing `bubblewrap` as a dependency. An updated package with the dependency listed as a requirement will be uploaded soon.

**Comment by mmstick** [comment]
Issue has been fixed, and packages are now going live.

After updating, you can delete your thumbnail cache and restart nautilus (runs in background even if not opened):

```sh
rm ~/.cache/thumbnails
nautilus -q
```
