### ISSUE TITLE
Online account login still remembered when account is removed

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#4]
_From @brs17 on October 24, 2017 16:26_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
After selecting to remove an account that was connected in GNOME, reselecting on the same service does not require the user to resupply login information.

**Steps to reproduce (if you know)**
Connect media account to "Online Accounts". 
Select connected account
Click "Remove Account"
Reselect same service
Note that login information is not required to log back in.

**Expected behaviour**
User should be required to provide both username and password to reconnect.

**Other Notes**
I initially found this issue with Google. Similar issue happens with Facebook, although with manual interaction, it is possible to require the password to be supplied again.

This may be an issue with cookies not expiring when they should.

_Copied from original issue: pop-os/iso#187_

**Comment by bflanagin** [comment]
The particular issue is resolved in newer versions of gnome-online-accounts. For future reference here is a link to the gitlab issues page. 

https://gitlab.gnome.org/GNOME/gnome-online-accounts/-/issues
