### ISSUE TITLE
Cannot boot on MSI GE63VR-7RE Raider without `nomodeset`

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#40]
_From @Shamash2014 on October 1, 2017 18:20_

**Reporter info**

```
msi GE63VR 7RE

GTX1060 + i7-7700HQ+120hz screen
```

**Issue/Bug Description**

Cannot boot without nomodeset. With nomodeset can install, but on boot of installed system blank screen. 

**Steps to reproduce (if you know)**

**Expected behaviour**

Possible to boot and have at list non 1024X768 resolution and run system without recovery mode

**Other Notes**

_Copied from original issue: pop-os/iso#111_

**Comment by isantop** [comment]
_From @jackpot51 on October 1, 2017 19:59_

Did you try the NVIDIA ISO?

**Comment by isantop** [comment]
_From @Shamash2014 on October 2, 2017 22:9_

Everything the same

**Comment by isantop** [comment]
_From @Shamash2014 on October 2, 2017 22:9_

Laprop screen turns off

**Comment by isantop** [comment]
_From @WatchMkr on October 2, 2017 22:31_

Does your laptop have nvidia optimus?

Please try to use the Intel/AMD iso and remove "splash" from the kernel line.

**Comment by isantop** [comment]
_From @Shamash2014 on October 3, 2017 18:35_

yeah, it has optimus, I even can boot to tty console and mangle with `prime-select` on installed system. Prime-select nvidia shows loop with black X server on boot. 

Prime-select intel results in just the whole screen turned off / blank. 

Setting `i915.nomodeset=0` helps to boot, but without hardware acceleration. 

Platform: KabyLake (i7-7700HQ) & GTX 1060

**Comment by isantop** [comment]
_From @RicardoEPRodrigues on October 19, 2017 22:17_

I have a similar issue.

If I install the Nvidia ISO it runs smoothly, yet only on the dedicated card. If I try to `prime-select intel` it shows the loading screen and as soon has it disables the dedicated card it freezes.

For the Intel builds I have the same issue with extra steps, where I have to start with `nouveau.modeset=0` install nvidia proprietary drivers and reboot. Then first problem arises.

**Comment by WatchMkr** [comment]
This is the expected behavior at this time because nvidia optimus isn't well supported in Linux.

**Comment by RicardoEPRodrigues** [comment]
Even using the NVIDIA prime?

**Comment by WatchMkr** [comment]
Yes, we've tested optimus in Linux for 7 years. Each product iteration we hope it's improved to production quality but it still hasn't yet.

**Comment by RicardoEPRodrigues** [comment]
Wow. Yet, I had prime working on previous versions of Ubuntu. Do I need to rollback or is a fix being made?
