### ISSUE TITLE
Pop Shop Disappeared from System

### ISSUE THREAD

**Issue by stratigos** [pop-os/pop#400]
**Distribution (run `cat /etc/os-release`):**
 
```sh
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

The package is Pop Shop, but I believe it is not on my system, so I dont know what the package name is.

**Issue/Bug Description:**

Recently, the Pop Shop seems to have gone missing from my system. I cant find it by searching.

**Steps to reproduce (if you know):**

Press system key. Type "shop" into search. Observe the Pop Shop is not listed. 

**Expected behavior:**

I would expect to find the Pop Shop and update my packages. 

**Other Notes:**

I can `sudo apt-get update` fine. When I `sudo apt-get upgrade`, some packages are always "held back," such as kernel updates. I can then `sudo apt-get --with-new-pkgs upgrade` to upgrade them. For some reason, I get the feeling this has to do with a conflict with Pop Shop.

I went looking for Pop Shop when I encountered this, as I suspect it was preventing those packages from upgrading. My intention was to delete it off my system if possible (and perhaps remove Pop OS altogether and just use GNOME). Then I discovered I couldnt find the package or the application. I believe its hiding in my system somewhere, I just dont know where.

**Comment by mmstick** [comment]
The name of the package is `pop-shop`:

```
# apt-cache policy pop-shop
pop-shop:
  Installed: 0.2.9~1543260272~18.10~ded150c
  Candidate: 0.2.9~1543260272~19.04~ded150c
  Version table:
     0.2.9~1543260272~19.04~ded150c 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/proposed/ubuntu disco/main amd64 Packages
 *** 0.2.9~1543260272~18.10~ded150c 100
        100 /var/lib/dpkg/status
```

However, I don't think the pop-shop would be causing any packages to be held back.

**Comment by stratigos** [comment]
Thanks, I have since reinstalled the `pop-shop` package. The _only_ time I experience packages "held back" is when I am doing a `sudo apt-get upgrade` and `pop-shop` _also_ is trying to upgrade to a new linux kernel or something similar. This led me to believe that the shop is related. 

I had never removed `pop-shop` to my knowledge, and still dont know how it disappeared from my system.  :man_shrugging:

**Comment by akashshil447** [comment]
Have you uninstalled python2 from your system?
pop shop requires python2 so if you remove python 2 then pop shop will get removed too.

**Comment by CSForever07** [comment]
I got an update error from the Pop shop and the terminal so I used the install command to update every package individually, but this just removed the pop-shop and it even said it removed the pop-desktop despite me still being able to use the desktop.

**Comment by kpgtox** [comment]
> Thanks, I have since reinstalled the `pop-shop` package. The _only_ time I experience packages "held back" is when I am doing a `sudo apt-get upgrade` and `pop-shop` _also_ is trying to upgrade to a new linux kernel or something similar. This led me to believe that the shop is related.
> 
> I had never removed `pop-shop` to my knowledge, and still dont know how it disappeared from my system. man_shrugging

how do you reinstall pop shop?

**Comment by Himel-Sarker1** [comment]
ones i uninstall some of files like pop shop related. after this i didn't find my pop shop store!
how do you reinstall pop shop again?

**Comment by algaly** [comment]
sudo apt-get upgrade
