### ISSUE TITLE
Gnome crash

### ISSUE THREAD

**Issue by TylerJWhit** [pop-os/pop#417]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

When using application/file search, gnome crashes.
**Steps to reproduce (if you know):**

When bringing up the gnome search, I try to open up the screenshot application. I type 'scr' in search and it crashes. It seems to only work with this key combination. Potentially a corrupted search index.

**Expected behavior:**

Searching anything shouldn't cause gnome to crash.

**Other Notes:**

**Comment by TylerJWhit** [comment]
I'd upload the file but the file zipped is 67.3 MB

**Comment by mmstick** [comment]
Not able to replicate. You may want to submit your bug report upstream to GNOME. [Tracker](https://gitlab.gnome.org/GNOME/tracker) is the project which handles search for GNOME.

**Comment by TylerJWhit** [comment]
Will do, Thanks!
