### ISSUE TITLE
Rx 590 not working

### ISSUE THREAD

**Issue by EduardoSevilla** [pop-os/pop#418]
Drivers compatibility bug

**Distribution :** 
Pop!_OS 18.04, Pop!_OS 18.10
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop!_OS 18.04, Pop!_OS 18.10

**Issue/Bug Description:**
Recently installed an AMD RX 590 on my Desktop computer. 
I had installed Pop!_OS 18.04, but when I try to start the system it turns a black screen and doesn't works anything... The graphic card turns on the fans to top power for a second, and i cant start the system.
I tried installing 18.10 release but the same thing happens.
I think that this graphic card drivers are not working on Linux beacouse i have the same problem with Ubuntu or Fedora.

**Steps to reproduce (if you know):**
Install an AMD RX 590 on a Pop!_OS system

**Expected behavior:**
System works correctly

**Other Notes:**
-The live CD doesn´t work neither
-Same problem with other Linux distros like Ubuntu or Fedora
-Sorry for my low level of English

**Comment by leviport** [comment]
I believe the RX590 is currently working in 20.04. Let me know if I'm mistaken and I will reopen this issue.
