### ISSUE TITLE
Audio Disabled on Install

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#42]
_From @Appalbarry on September 29, 2017 23:35_

barryrueger@pop-os:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

**Issue/Bug Description**

After a fresh install to my Dell Latitude E6400 laptop audio is disabled until the Pop/Gnome audio level is lowered from maximum.  There after audio works as expected.

**Steps to reproduce (if you know)**

(I have gone through this twice)

1. Fresh install of Pop_OS accepting all default settings except for choosing to "Erase Disc and install Pop_OS"

2. After install, configure WIFI and password.

3. Open Firefox (or Chrome) and visit Youtube. Click to play video.

4. There is no sound.  the audio control in the browser is at the default level.

5. Opening the audio level slider from the top right hand speaker icon (see before.png) shows that audio level is set to maximum.
![image](https://user-images.githubusercontent.com/1308152/31039609-d6adb270-a533-11e7-9a27-36d5cb466736.png)

6. Lowering the audio level to something less than maximum makes sound work. (see after.png)
![image](https://user-images.githubusercontent.com/1308152/31039626-e9eb9bae-a533-11e7-8fc6-79f697cda219.png)

7. Thereafter audio work as expected, even if the slider is set back to maximum volume.

**Expected behaviour**

Audio works properly after a fresh install.

_Copied from original issue: pop-os/iso#105_

**Comment by isantop** [comment]
_From @WatchMkr on September 30, 2017 0:6_

Does audio work as expected after a reboot?

**Comment by isantop** [comment]
_From @Appalbarry on September 30, 2017 0:20_

1) I rebooted form USB and the audio was disabled in the Live Boot instance.

2) I did another fresh install.
3) Opened Firefox and tried Youtube. Audio did not work.
4)BEFORE CHANGING ANY SETTINGS rebooted the computer.
5) Audio still did not work.
6) Changed audio level as before, audio works.
7) Rebooted again, audio still works.

If it helps:

barryrueger@pop-os:~$ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: Intel [HDA Intel], device 0: 92HD71B7X Analog [92HD71B7X Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
barryrueger@pop-os:~$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Intel [HDA Intel], device 0: 92HD71B7X Analog [92HD71B7X Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by isantop** [comment]
_From @Appalbarry on October 20, 2017 2:8_

Problem remains with 17.10.

**Comment by isantop** [comment]
@jackpot51 Could this be related to the over 100% volume issue?

**Comment by brs17** [comment]
Following up with this bug, @Appalbarry are you still able to recreate this issue with Pop!_OS? I have not heard of others with this problem.

**Comment by Appalbarry** [comment]
Hi Ben, actually I just did a fresh install this week.  I remember some
kind of audio issue, but don't remember just what.

If I have time this weekend I'll do another install and see what's up.

Barry

**Comment by Appalbarry** [comment]
Downloaded the latest Intel ISO. Fresh install to the same Dell. Volume was initially minimized after install, and worked as expected.

**Comment by brs17** [comment]
So it sounds (pun unintended) like things are working now. Going to close the bug, feel free to reopen if the issue persists.
