### ISSUE TITLE
How to make the right favorites bar to show on mouse hover ??

### ISSUE THREAD

**Issue by cata0309** [pop-os/pop#425]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by sikrob** [comment]
There is a gnome extension you can install: https://support.system76.com/articles/dash-to-dock/
