### ISSUE TITLE
Multiple Mouse Cursors on Login

### ISSUE THREAD

**Issue by pravinba9495** [pop-os/pop#429]
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

GPU: Using nVidia GTX 1050 Ti 4GB

**Issue/Bug Description:**
User is shown multiple cursors upon login, one cursor per attached display.

**Expected behavior:**
Show only one cursor only on the primary display

**Comment by brs17** [comment]
@pravinba9495 could the displays be set to mirror by default? Do you have the same content on both screens?

**Comment by pravinba9495** [comment]
No. They are in extend mode (not mirroring). The duplicate mouse cursor disappears after moving the primary mouse pointer to that screen. I have a triple monitor setup.

**Comment by pravinba9495** [comment]
The issue seems to be fixed. I have tried installing the latest 18.04 build on two of my PCs. The issue is  resolved now. Cannot pin point which build exactly that has the fix implemented.
