### ISSUE TITLE
"Try or Install" is booting to Dell recovery partition

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#43]
_From @aronbohl on September 29, 2017 19:57_

I just downloaded pop-os_amd64_27.iso and burnt it to a USB drive with the latest version of Etcher. When I booted from the drive it loaded the Unity 7 desktop. I'm using a Dell Precision 5510 laptop.

Trying to view the what got written to the thumb drive results in the following error. Please let me know if there's anymore information that would be useful.

![screenshot from 2017-09-29 13 22 09](https://user-images.githubusercontent.com/2165875/31033580-e0b03c86-a51d-11e7-9cab-ae81769e7dae.png)

_Copied from original issue: pop-os/iso#104_

**Comment by isantop** [comment]
_From @aronbohl on September 29, 2017 21:5_

After a little more digging, I discovered that it's actually booting my recovery partition that my laptop shipped with (came from Dell with Ubuntu 14.04 LTS). The really weird thing is that I get the “Try or Install Pop_OS” screen but when I hit enter it just proceeds to boot the Ubuntu live session.

**Comment by isantop** [comment]
_From @cassidyjames on September 29, 2017 21:12_

Ah, that sounds a little more plausible :joy:

Still not a fun bug. We'll keep this open while we investigate it.

**Comment by isantop** [comment]
Closing since ISO issues are mostly fixed.

**Comment by patped** [comment]
Can confirm that this bug is still going. I'm on a Dell XPS 13 (9350) Is there some kinda workaround?
