### ISSUE TITLE
The sound is low even when maxed in settings

### ISSUE THREAD

**Issue by cata0309** [pop-os/pop#431]
**Distribution (run `cat /etc/os-release`):**
 18.04 latest
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
The maximum sound is low.

**Steps to reproduce (if you know):**
Enter chrome/firefox/etc. Anything that plays sounds.

**Expected behavior:**
Sound louder when maxing the volume
**Behavior:**
Sounds low comparatively to windows
**Other Notes:**
I used alsamixer, puvacontrol and anything, but sound still is low

**Comment by brs17** [comment]
@cata0309 what hardware are you having this sound issue? Can you confirm that the volume is not a problem on a different operating system?

**Comment by cata0309** [comment]
Yes it is, I searched on google for solutions and a lot of users have this problem, but no solution.
I am using an Hp Pavillion 15 series laptop

**Comment by mlncn** [comment]
Same problem, and i'm on an Oryx Pro.

The ability to 'overclock' the volume and go to 150% or 200% i think would solve it for me, i think.

**Comment by mmstick** [comment]
@mlncn You could use alsamixer or qasmixer to check if the sound card's volume is turned up.

**Comment by mlncn** [comment]
Result from alsamixer:

![oryx-alsamixer](https://user-images.githubusercontent.com/27131/59947166-86144480-943a-11e9-80cc-ecd89efa5c57.png)
