### ISSUE TITLE
Geary unable to connect accounts.

### ISSUE THREAD

**Issue by fadsm** [pop-os/pop#447]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Geary 0.13.0-1~bionic1 

**Issue/Bug Description:**

Guys, I'm very new at this community and this might help someone. I updated the system and my geary stopped to connect in my Gmail account. The following error appeared:

Account provider: GEARY_SERVICE_PROVIDER_OTHER
Service type: GEARY_PROTOCOL_IMAP
Service host: mail.tecnico.ulisboa.pt
Error type: GIOError 38
Message: Could not connect to mail.tecnico.ulisboa.pt: Network is unreachable

**Steps to reproduce (if you know):**

1.Update Geary in Pop!_Shop.

2.Try connect in Gmail account

**Expected behavior:**

Account connected

**Other Notes:**

I found the solution from the Developers website:
https://gitlab.gnome.org/GNOME/geary/issues/217

I suggest to update the repository as soon as they release the new version. 

For users that want to resolve as soon as possible, please clone and install from this branch:
https://gitlab.gnome.org/GNOME/geary/merge_requests/112

**Comment by mmstick** [comment]
The repos will be updated as soon as a new release is available. I actually have the Geary repository in my RSS feed reader, to notify me on new tagged releases.

**Comment by mmstick** [comment]
Geary 0.13.1 was released. Does this still occur?

**Comment by fadsm** [comment]
No, problem solved. Thanks for support.
