### ISSUE TITLE
Needs Nvidia driver 418 support

### ISSUE THREAD

**Issue by yelcat** [pop-os/pop#454]
My Alienware laptop's  graphics card is Nvidia RTX 2070 MQ, It need Nvidia driver 418 support

**Comment by mmstick** [comment]
We will be updating the NVIDIA driver soon.

**Comment by jackpot51** [comment]
We will have this out very soon. Earlier than any other distribution, as far as I know.

**Comment by yelcat** [comment]
> We will have this out very soon. Earlier than most other distributions

I am very happy to hear this, thank you for your work.

**Comment by brs17** [comment]
NVIDIA 418.43 was released yesterday and should be available via an upgrade. (`sudo apt update && sudo apt upgrade`)
