### ISSUE TITLE
Feature request: bring back zoom and minimize buttons

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#459]
**Distribution (run `cat /etc/os-release`):**
 
 All
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

(Window rendering)

**Issue/Bug Description:**

I know this has been discussed before, and it's technically redundant, but it sure is awkward to be navigating around with the mouse and suddenly need to switch to the keyboard just to zoom or minimize a window. OK, so it's not the most pressing issue, but virtually every other desktop OS has these buttons somewhere on the top of each window.

**Steps to reproduce (if you know):**

N/A

**Expected behavior:**

Click the zoom button to go full-screen. Click the minimize button to shrink the window off of the desktop.

**Other Notes:**

**Comment by mmstick** [comment]
A keyboard isn't required. You can double click the title bar to toggle maximizing the window. You can right click the title bar to select either Minimize or a number of other useful window management options.

**Comment by KloudKoder** [comment]
Ah ha! Thanks again, you win. Granted, it's not really intuitive.

**Comment by spectrapulse** [comment]
This can be enabled in gnome-tweak-tool as far I know?
![image](https://user-images.githubusercontent.com/20131658/54581342-8bfa2400-4a0c-11e9-8181-db51a9170aef.png)

Just install gnome-tweak-tool and go to Window Titlebars tab and enable maximize and minimize.
![image](https://user-images.githubusercontent.com/20131658/54581396-d11e5600-4a0c-11e9-90dd-c307f80b394d.png)

**Comment by KloudKoder** [comment]
@spectrapulse Thanks! You also solved this mystery: https://github.com/pop-os/pop/issues/438

**Comment by spectrapulse** [comment]
No problem! 

I think this issue can be closed now.
