### ISSUE TITLE
high ram memory consumption with kernel 4.10.x?

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#46]
_From @filipeGamaBR on September 20, 2017 5:3_

Hello good night, I am using pop or a few days, with kernel 4.10.35 I noticed a high ram memory consumption around 2.3GB and with few open applications and I realize the system is slow, little fluid and this makes it very difficult to perform the tasks. boot starts around 1,3GB ram I use a lot of virtualbox or boxes too. I have not found any bug and I am loving this system !, has what it takes for day to day, has the quality look well built, beautiful wallpapers has beautiful balance of colors and combinations! Many thanks to all the team for taking initiative to create the POP OS, I am looking forward to new upgrades !.
obs: I had to change the kernel and it looks better.
hardware:
Notbook-Dell i14-5458
intel corei3 5 generation
ram: 4GB ddr3 1.600mhz
Intel HD Graphics 5500

_Copied from original issue: pop-os/iso#85_

**Comment by isantop** [comment]
_From @kylerchin on October 9, 2017 20:33_

for me it's high CPU and slightly high RAM on my Galago Pro.

**Comment by isantop** [comment]
@filipeGamaBR @kylerchin Either of you guys still having this issue?

**Comment by filipeGamaBR** [comment]
no is perfect anow thanks for the suport , i love the suport  POP Os thanks very mutch

**Comment by isantop** [comment]
Thanks!

**Comment by kylerchin** [comment]
Still having problems. I can't have 4 tabs open on Brave without my Galago about to take off from the jet engine like sound of the stupid fan.

**Comment by isantop** [comment]
Does that same thing happen with Firefox? I wonder if that's just an issue with Brave.

**Comment by kylerchin** [comment]
Firefox as well. Chrome is the Worst... Eats up memory like hell.

**Comment by isantop** [comment]
Chrome takes the crown for the most memory of any secondary OS ever. If only they didn't try to build their own OS shell into Chrome.... :)

What kind of memory usage are you seeing before opening Firefox, and what kind after? Also, does this change depending on what sites you go to? Additionally, do you have the most up-to-date firmware installed on your Galago? That can make a big difference with the fan noise.

**Comment by kylerchin** [comment]
Yes, I 
```
apt update && apt upgrade
```
Weekly. I have a 32GB model, and using  2 GB across Brave, Atom, and Tilix, and that usually doesn't hurt that much until I have a lot of stuff with ssh or more than 3 tabs open. The second I open Discord, my fan will try to take off.

**Comment by isantop** [comment]
`apt` will not install firmware updates.

It does sound like you may have an older BIOS. @cassidyjames Next to me also has a 32GB Galago and it doesn't have fan issues in Pop_OS. Go ahead and open a support ticket and we should be able to get you instructions for updating the BIOS to solve the fan problem (it shouldn't require sending the computer in for anything)

**Comment by cassidyjames** [comment]
To be fair, my fan does spin up loudly now and then when I'm opening something heavy, eg. an Electron app or Chrome. But yeah, I'd agree this is not a Pop!_OS issue as it's the same for me across OSes.
