### ISSUE TITLE
Fonts with border only in Gnome desktop

### ISSUE THREAD

**Issue by raulsanchezmv** [pop-os/pop#464]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

N/A

**Issue/Bug Description:**

On new installs and even updated installs, the fonts in the desktop have a border around the font, making them difficult to read.

**Steps to reproduce (if you know):**

New installations.

**Expected behavior:**

No border, same font looking as in Nautilus.

**Other Notes:**

![image](https://user-images.githubusercontent.com/30627030/53917737-8b08e000-4065-11e9-80e2-720a6eaee1b3.png)

**Comment by jackpot51** [comment]
We actually added the border for readability reasons. Without it, it can be extremely difficult to read the text on light backgrounds. We are not going to change it.
