### ISSUE TITLE
Feature request: microphone control in sound control dropdown

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#465]
**Distribution (run `cat /etc/os-release`):**
 
All 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

(Whatever code runs when I click the speaker icon on the taskbar.)

**Issue/Bug Description:**

Even a shortcut to the mic settings would help, but a direct mic control would be best. I like to keep my mic disabled at all times unless I need it on, for obvious security reasons. I'm sure I'm not the only person to have ever considered this. But of course this isn't totally straightforward, as there are multiple mic sources and they seem to have different enables (creepy, huh?). Frankly just a master disable for all mics would be highly appreciated.

**Steps to reproduce (if you know):**

N/A

**Expected behavior:**

Let's not have to go search for settings, then sound, then input, etc. just to toggle the mic.

**Other Notes:**

**Comment by jackpot51** [comment]
You can try an extension like this:

https://extensions.gnome.org/extension/906/sound-output-device-chooser/
