### ISSUE TITLE
Boot volume selection and GRUB commandline modification are mutually exclusive

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#469]
**Distribution (run `cat /etc/os-release`):**
 
 All
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

GRUB

**Issue/Bug Description:**

When the OS is booting, you can bring up a menu of boot volumes (stardard, old, recovery, etc.) by pressing F8. (You have to press it rapidly in succession, or hold it down, during system boot, but not too early an not too late. It's more art than science.) Likewise, you can bring up the GRUB commandline, which you can modify, by doing the same routine with the "e" key. But in this case, you can't do both, i.e. choose a volume to boot and also modify its commandline.

**Steps to reproduce (if you know):**

As above.

**Expected behavior:**

Please provide some way to allow us to modify both. But don't get me wrong. I'm not suggesting that we increase the already-ample boot latency by displaying a message like "Press any key in the next 10 seconds to activate the boot menu." How this would work in a text UI is up to you.

**Other Notes:**

**Comment by jackpot51** [comment]
The boot volume selection comes from the firmware, not from the OS. If you select an from the firmware boot menu item, you should be able to press escape immediately after to have the GRUB menu show up.
