### ISSUE TITLE
Cancel upon screen unlock fails to reenter idle (S1)

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#472]
**Distribution (run `cat /etc/os-release`):**
 
All 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Lock screen

**Issue/Bug Description:**

Clicking "Cancel" just makes the clock sit there doing nothing. 

**Steps to reproduce (if you know):**

Lock the screen (Super+L). Wait til the machine is in idle. Wake it up. Swipe up to get the password prompt. Click "Cancel".

**Expected behavior:**

Go back to the previous sleep state, whatever it happened to be (S1 in this case).

**Other Notes:**

**Comment by jackpot51** [comment]
This is the GNOME lockscreen design. Cancel just closes the authentication dialog. If you want it to do something different, you can open an issue here:
https://gitlab.gnome.org/GNOME/gdm/
