### ISSUE TITLE
Can't right-click with touchpad

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#473]
**Distribution (run `cat /etc/os-release`):**
 
All 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

(Touchpad configuration)

**Issue/Bug Description:**

If you click on the right side of the touchpad, it still gets interpreted as a left-click.

**Steps to reproduce (if you know):**

(As above.)

**Expected behavior:**

Bring up the right-click menu.

**Other Notes:**

Based on gnome-tweaks, it appears as though Pop defaults to the "fingers" mode instead of the "area" mode. In the former case, 1 finger is left-click, 2 fingers is right-click, and 3 is middle-click.(unintuitive and not really discoverable). The default should be "area" mode, in which the left side is left-click and right side is right-click (obvious and immediately discoverable).

More generally, I never understood why gnome-tweaks hasn't even been absorbed into Settings. It's not as though we want certain settings to hide from us by remaining only in this obscure app that few people have. This is especially important when the default is obscure behavior, as in this case; in which the natural response would be to look at touchpad settings. (Granted the best solution here is to simply change the default behavior.)

A really easy fix for the general case would be to install gnome-tweaks as part of the OS install process, then put a link to it in the Settings menu. (The last thing I want to do is invite more bloat, but in this case it seems justifiable.)

**Comment by mmstick** [comment]
This sounds hardware specific. Right clicking works on all of our touchpads.

**Comment by KloudKoder** [comment]
For some reason it works fine out of the box on other Linux flavors. I'm stumped.

**Comment by CosmanAgraz** [comment]
I have this issue as well.  Right-click worked fine on Windows 7, Ubuntu, Mint, and xubuntu, but not on pop_OS.

Running pop_OS on an Asus x401a

**Comment by DevDof** [comment]
Hi,
Go to the store, download gnome tweaks, go to mouse and keyboard, then mouse click emulation and finally choose Area to have the ability to use right-click as a right-click.

**Comment by gnumanx** [comment]
> I have this issue as well. Right-click worked fine on Windows 7, Ubuntu, Mint, and xubuntu, but not on pop_OS.
> 
> Running pop_OS on an Asus x401a
> 
> Edit: Upon testing, it seems that both touch-pad buttons are mapped as primary button. Any suggestions on coming up with a fix?

I have the same issue on a Asus laptop, and gnome-tweaks doesn't help

**Comment by richardanaya** [comment]
I was able to solve this by enabling this trackpad area emulation in gnome tweaks:

![image](https://user-images.githubusercontent.com/294042/103319954-8060cd00-49e8-11eb-8780-756229f21f34.png)

**Comment by KloudKoder** [comment]
Thanks, it worked!

**Comment by nitheeshmavila** [comment]
> Hi,
> Go to the store, download gnome tweaks, go to mouse and keyboard, then mouse click emulation and finally choose Area to have the ability to use right-click as a right-click.

Worked for me

**Comment by jeorgy** [comment]
Thanks, it worked for me.

**Comment by OpenSourceIronman** [comment]
On bad ASUS trackpads I would use the two finger tap for right click, but "sudo apt install gnome-tweaks"  works great if you want to click on the lower right side of the trackpad.

**Comment by StubbsPKS** [comment]
> Hi, Go to the store, download gnome tweaks, go to mouse and keyboard, then mouse click emulation and finally choose Area to have the ability to use right-click as a right-click.

Thank you for this. I was going insane trying to add a new application to my pop OS dock because "right click" would just open the application!

**Comment by acme64** [comment]
sometimes right click doesn't work after changing to area. if i right click multiple times fast nothing happens, if i take my time maybe every 2 or 3 clicks will result in a menu

**Comment by K4rBie** [comment]
So was that fixed or is this just a workaround? How a new user should know that it has to install third-party application to enable right-clicking?

**Comment by SirRFI** [comment]
> So was that fixed or is this just a workaround? How a new user should know that it has to install third-party application to enable right-clicking?

Fresh install of PopOS 21.10 few days ago. This is not "fixed".

**Comment by jacobgkau** [comment]
There is nothing "broken," at this point you're making a feature request to change the default right-click style from multi-touch to area emulation or provide a more prominent setting to do so.

**Comment by m-moraes** [comment]
> thank you!

**Comment by AntonyOnScript** [comment]
> I was able to solve this by enabling this trackpad area emulation in gnome tweaks:
> 
> ![image](https://user-images.githubusercontent.com/294042/103319954-8060cd00-49e8-11eb-8780-756229f21f34.png)

tks

**Comment by FernandoHaeser** [comment]
**Hi everyone! I solve this in 2025 with this:**

1. Identify your touchpad device ID:
```bash
xinput list
```
2.  Switch the click method to Clickfinger:
```bash
xinput set-prop <device-id> "libinput Click Method Enabled" 1 0
```
3. Add permanent
```bash
nano ~/.xsessionrc
xinput set-prop <device-id> "libinput Click Method Enabled" 1 0
```

**Comment by rsabarinath7c-droid** [comment]
> **Distribution (run `cat /etc/os-release`):**
> 
> All
> 
> **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
> 
> (Touchpad configuration)
> 
> **Issue/Bug Description:**
> 
> If you click on the right side of the touchpad, it still gets interpreted as a left-click.
> 
> **Steps to reproduce (if you know):**
> 
> (As above.)
> 
> **Expected behavior:**
> 
> Bring up the right-click menu.
> 
> **Other Notes:**
> 
> Based on gnome-tweaks, it appears as though Pop defaults to the "fingers" mode instead of the "area" mode. In the former case, 1 finger is left-click, 2 fingers is right-click, and 3 is middle-click.(unintuitive and not really discoverable). The default should be "area" mode, in which the left side is left-click and right side is right-click (obvious and immediately discoverable).
> 
> More generally, I never understood why gnome-tweaks hasn't even been absorbed into Settings. It's not as though we want certain settings to hide from us by remaining only in this obscure app that few people have. This is especially important when the default is obscure behavior, as in this case; in which the natural response would be to look at touchpad settings. (Granted the best solution here is to simply change the default behavior.)
> 
> A really easy fix for the general case would be to install gnome-tweaks as part of the OS install process, then put a link to it in the Settings menu. (The last thing I want to do is invite more bloat, but in this case it seems justifiable.)



> **Distribution (run `cat /etc/os-release`):**
> 
> All
> 
> **Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
> 
> (Touchpad configuration)
> 
> **Issue/Bug Description:**
> 
> If you click on the right side of the touchpad, it still gets interpreted as a left-click.
> 
> **Steps to reproduce (if you know):**
> 
> (As above.)
> 
> **Expected behavior:**
> 
> Bring up the right-click menu.
> 
> **Other Notes:**
> 
> Based on gnome-tweaks, it appears as though Pop defaults to the "fingers" mode instead of the "area" mode. In the former case, 1 finger is left-click, 2 fingers is right-click, and 3 is middle-click.(unintuitive and not really discoverable). The default should be "area" mode, in which the left side is left-click and right side is right-click (obvious and immediately discoverable).
> 
> More generally, I never understood why gnome-tweaks hasn't even been absorbed into Settings. It's not as though we want certain settings to hide from us by remaining only in this obscure app that few people have. This is especially important when the default is obscure behavior, as in this case; in which the natural response would be to look at touchpad settings. (Granted the best solution here is to simply change the default behavior.)
> 
> A really easy fix for the general case would be to install gnome-tweaks as part of the OS install process, then put a link to it in the Settings menu. (The last thing I want to do is invite more bloat, but in this case it seems justifiable.)

its just stupid bro they shouls say it atleast two fingers right click

**Comment by FernandoHaeser** [comment]
Instead of changing the default, why not expose the click method directly in Settings like Ubuntu does? Users could then choose between two-finger right-click and right-side click without needing GNOME Tweaks.

The biggest issue isn't the default itself, it's that the option is hidden and most users don't know it exists.
