### ISSUE TITLE
Dublin Timezone is incorrect

### ISSUE THREAD

**Issue by lmanalas** [pop-os/pop#474]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

https://twitter.com/ruigalaxys4/status/1107588683014787072

**Comment by brs17** [comment]
I believe @ruigalaxys4 is incorrect because Dublin is still in UTC 0 during the winter months, and their daylight savings time is not until March 31st this year. https://en.wikipedia.org/wiki/Time_in_the_Republic_of_Ireland

**Comment by brs17** [comment]
Turned out, the actual issue here is one in the map used in gnome-initial-setup. The actual issue was not that the timezone was incorrect but rather that Dublin is not highlighted when selecting it (and getting the correct timezone). This is an upstream issue but I am not sure where.

**Comment by lmanalas** [comment]
Ah. Okay, thanks Shpurk. I'll get back to him and let him know. I'll dig around and see if I can find more answers or file a bug. Thanks

**Comment by brs17** [comment]
@lmanalas I was just posting here the results of the twitter conversation. 

Next step would be to find where this map is drawn (upstream) and file an issue there.
