### ISSUE TITLE
Screen flashes on restart and resume

### ISSUE THREAD

**Issue by nomtat** [pop-os/pop#482]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

**Issue/Bug Description:**
When my laptop turns on after restarting, it shows the cryptsetup disk encryption screen. After I type in my password, it flashes that screen a few times, then goes to black, flashes red, then flashes the cryptsetup: cryptdata screen a few more times, then finally the lock screen shows. Furthermore, upon suspending the laptop by closing the lid, when opening it again, the screen also flashes red for a split second.

**Steps to reproduce (if you know):**
If the disk is encrypted, restart the computer, decrypt the disk, and it will happen.

**Expected behavior:**
It should show the decrypt screen, then not flash, and go to the login page. 

**Other Notes:**
The laptop is the Lenovo ThinkPad X1 Extreme, BiOS version 1.19.

**Comment by brs17** [comment]
@nomtat, this is a known issue that originates from the NVIDIA driver.

@jackpot51, as we strengthen our communication with NVIDIA, let's add this to the list of bugs we have seen.

**Comment by nomtat** [comment]
Would you recommend switching to hybrid graphics in the meantime?

**Comment by nomtat** [comment]
Update: I was able to resolve this issue by turning on 'Hybrid Graphics' in the BiOS, but setting Pop OS to 'NVIDIA Graphics' in the quick settings menu. This fixes the screen flashing issue and retains all of the benefits of the discrete graphics card.
