### ISSUE TITLE
geary does not highlight which mailbox is currently active

### ISSUE THREAD

**Issue by bekips** [pop-os/pop#484]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

geary:
  Installed: 0.13.3-1~bionic1
  Candidate: 0.13.3-1~bionic1

**Issue/Bug Description:**
geary doesn't indicate which mailbox is currently active in the sidebar

**Steps to reproduce (if you know):**
run geary
click sidebar to change mailboxes

Expected behavior:**
geary should clearly indicate at all times which mailbox is active in the sidebar 

**Other Notes:**

this might be a bug in the pop theme

**Comment by brs17** [comment]
@bekips , would you say this issue is the same as https://github.com/pop-os/gtk-theme/issues/283 ? Sounds to me like the highlight selection in Geary is being improperly handled by the gtk-theme.

**Comment by bekips** [comment]
> @bekips , would you say this issue is the same as [pop-os/gtk-theme#283](https://github.com/pop-os/gtk-theme/issues/283) ? Sounds to me like the highlight selection in Geary is being improperly handled by the gtk-theme.

yes.

**Comment by brs17** [comment]
Cool, then let's follow progress on the issue there.
