### ISSUE TITLE
POP OS ISOs not signed

### ISSUE THREAD

**Issue by SaltyCybernaut** [pop-os/pop#485]
**Issue/Bug Description:**
ISOs from system76.com only include a hash of the ISO which is not enough to verify the ISO has not been maliciously tampered with. A signature of the ISO or a signature of the hash is needed for POP OS to have parity with other Linux distributions.

**Comment by jackpot51** [comment]
The hash is provided over HTTPS, so it can be verified.

**Comment by jackpot51** [comment]
In addition, we have a shasum file found in the same folder the ISO is served. For example, for build 17 of 18.10, we have this:

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/18.10/amd64/intel/17/SHA256SUMS

And a GPG signature:

https://pop-iso.sfo2.cdn.digitaloceanspaces.com/18.10/amd64/intel/17/SHA256SUMS.gpg

**Comment by SaltyCybernaut** [comment]
@jackpot51, ah this is exactly what I was looking for. Is there any way to inform visitors of the website that the signatures exists and where they can find them? I went looking for these signatures and was not able to find them.

**Comment by jackpot51** [comment]
On the website, we rely on the verification done by HTTPS, which I believe is sufficient
