### ISSUE TITLE
Firefox missing on favorites bar

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#492]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.04 iso19

**Issue/Bug Description:**
Firefox icon is missing on the favorites bar.

![Screenshot from 2019-04-09 09-44-36](https://user-images.githubusercontent.com/7460774/55816409-6f9f5380-5aaf-11e9-82a1-19d8b4135f77.png)

Note that if Firefox is removed from the pinned items and added later (or the application is run), then the icon does show up on the bar.

**Comment by brs17** [comment]
Upstream bugs can be tracked: 
Ubuntu: https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1822846
Gnome: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1053

**Comment by jackpot51** [comment]
Fixed by pulling the one missing commit from GNOME into the Ubuntu version of gnome-shell: https://github.com/pop-os/gnome-shell/compare/ubuntu/master...master_disco
