### ISSUE TITLE
Unplugging ethernet while in standby fails

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#5]
_From @brs17 on October 23, 2017 21:13_

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
Pop!_OS 17.10

**Issue/Bug Description**
On OryxPro3 and 2, when Ethernet is disconnected when the computer is in a standby state, the machine fails to disconnect from Ethernet and regain WI-fi connection upon system resume.

On Kudu4, the Ethernet connection properly disconnects upon resume but takes >1minute to reconnect to a wired connection if Ethernet cable is plugged in again.

**Steps to reproduce (if you know)**
Connect machine to both wired ethernet connection as well as to a Wifi connection. Put the machine in standby. Unplug ethernet connection. Resume system. 

**Expected behaviour**
Ethernet connection should disconnect and Wifi should reconnect after system resumes. 

**Other Notes**
Ethernet connected icon is still visible in the system menu upon resume. Internet connection unavailable.

![screenshot from 2017-10-23 13-32-02](https://user-images.githubusercontent.com/7460774/31913491-7802fd28-b804-11e7-9c21-dbca04bb2e94.png)

_Copied from original issue: pop-os/iso#186_

**Comment by isantop** [comment]
Oryx issue also happens on oryp1

**Comment by zhangandyx** [comment]
I am also having this issue when my lid is closed when I reboot.

**Comment by brs17** [comment]
This is also being reported now on the oryp4

**Comment by bflanagin** [comment]
We now have tests for this in the QA department to mitigate issues like these. 

For good measure, I've attempted to replicate this issue with our newer hardware on current versions of Pop!_OS without success.

Closing ticket.

**Comment by frock81** [comment]
I'm experiencing this issue on my System76 Pangolin with Pop!_OS 22.04. I tried reloading the module based on [this](https://askubuntu.com/questions/1029250/ubuntu-18-04-ethernet-disconnected-after-suspend), which I thought could be related, but had no success.

**Comment by frock81** [comment]
I'm experiencing this issue on my System76 Pangolin with Pop!_OS 22.04. I tried reloading the module based on [this](https://askubuntu.com/questions/1029250/ubuntu-18-04-ethernet-disconnected-after-suspend), which I thought could be related but had no success. I also tried restarting Network Manager with no effect. What works is restarting the operating system.
