### ISSUE TITLE
System locks up when adjusting the display brightness in the Live boot (ThinkPad T420 4178-6VU)

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#50]
_From @nick1297 on August 23, 2017 14:24_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 17.04
Release: 17.04
Codename: zesty
 * Related Application and/or Package Version - Gallium
```

**Issue/Bug Description**
On my ThinkPad T420 4178-6VU with the Intel IGP disabled (along with Optimus), the system locks up if you attempt to adjust the volume with the Intel IGP hidden and nVidia Optimus disabled. This does NOT happen when nVidia Optimus is enabled nor does it happen when the Intel IGP is visible but the nVidia GPU is hidden.
Note: The correct Distro reference is Pop!_OS 17.04. The distro is not reporting itself correctly.

**Steps to reproduce (if you know)**
* On a ThinkPad T420 4178-6VU (or any T420 with the NVS 4200M dGPU) disable nVidia Optimus and force the nVidia graphics on all the time by setting up the system accordingly: Graphics Device: Discrete Graphics/OS Detection for NVIDIA Optimus: Disabled
* Boot Pop!_OS off of a USB drive (Specific USB drive used: SanDisk Cruzer Micro 4GB/SDCZ6-4096RB)
* Let the system boot
* Adjust the display brightness (Note: The test machine has the Fn/Ctrl key swap setting enabled. This likely doesn't matter, but I am mentioning it for completeness.)

**Expected behaviour**
The LCD brightness should adjust without a total system lockup.

**Other Notes**
Terminal output:
pop_os@pop_os:~$ apt policy $Gallium
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://ppa.launchpad.net/system76/pop/ubuntu zesty/main amd64 Packages
     release v=17.04,o=LP-PPA-system76-pop,a=zesty,n=zesty,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://archive.ubuntu.com/ubuntu zesty-updates/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty-updates/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty-updates/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-updates,n=zesty,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu zesty-security/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty-security,n=zesty,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin archive.ubuntu.com
 500 http://archive.ubuntu.com/ubuntu zesty/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=main,b=amd64
     origin archive.ubuntu.com
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/universe amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=universe,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/restricted amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=restricted,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/multiverse amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=multiverse,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
 500 cdrom://Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104) zesty/main amd64 Packages
     release v=17.04,o=Ubuntu,a=zesty,n=zesty,l=Ubuntu,c=main,b=amd64
     origin Pop_OS 17.04 _Zesty Zapus_ - Release amd64 (20170104)
Pinned packages:

_Copied from original issue: pop-os/iso#61_

**Comment by isantop** [comment]
_From @nick1297 on August 23, 2017 15:48_

This issue also happens on a SanDisk SDZ60-016G (Cruzer Glide 16GB), which was recently purchased in a 3 pack. It does not matter which USB drive is used.

**Comment by isantop** [comment]
As a testing procedure, can you try testing from an Ubuntu GNOME live disk and see if you get the same issues there? That will help us locate the problem and file appropriate upstream bugs (if necessary).

**Comment by isantop** [comment]
_From @nick1297 on August 24, 2017 0:41_

This issue still happens on Ubuntu GNOME. It happens on both my Cruzer Micro and my Cruzer Glide drives.

It may also be a hardware issue, since I have had issues with thermals being higher then I'd like it to be for a Sandy Bridge i5 machine (the system uses an i5 2520M). It's not likely since the thermals aren't completely gone to the point that it heats up instantly (it usually ramps up to the point the thermals become an issue) but I am mentioning it in case the possibility of a hardware issue comes up. It may be a good idea to have someone test machine with a similar GPU configuration and get a second opinion, to isolate the possibility that my machine's thermal issues (which I am working on chasing down and fixing if it makes sense) aren't the cause.

**Comment by nick1297** [comment]
Did you find anyone with a NVS 4200M T420 that's far more trustworthy then the one I have issues with yet?

**Comment by WatchMkr** [comment]
We haven't seen any other reports of hotkeys locking Pop! This is likely a firmware bug or hardware failure.
