### ISSUE TITLE
lsb_release shows incorrect description

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#505]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.04
 
 
**Issue/Bug Description:**
Output of `lsb_release -a` on a Pop!_OS 19.04 system is:
```
Distributor ID: Ubuntu
Descripion: Ubuntu 19.04
Release: 19.04
Codename: disco
```

in 18.10 it is:

```
Distributor ID: Ubuntu
Descripion: Pop!_OS 18.10
Release: 18.10
Codename: cosmic

```

**Comment by mmstick** [comment]
https://github.com/pop-os/default-settings/pull/56 seems to fix this as well

**Comment by brs17** [comment]
Fixed by https://github.com/pop-os/default-settings/pull/56
