### ISSUE TITLE
Pop!_OS 19.04 NVIDIA download link not working

### ISSUE THREAD

**Issue by gabrielivascu** [pop-os/pop#508]
The link https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/nvidia/3/pop-os_19.04_amd64_nvidia_3.iso from the official download page is not working. In browser, it outputs:

```
<Error>
    <Code>NoSuchKey</Code>
    <BucketName>pop-iso</BucketName>
    <RequestId>tx00000000000009e2aeab3-005cb88b49-795c7-sfo2a</RequestId>
    <HostId>795c7-sfo2a-sfo</HostId>
</Error>
```

Happens on both Chrome and Firefox. Also, `wget`-ing it returns 404.

The link for the Intel flavor is OK.

**Comment by brs17** [comment]
Seems to be an issue the CDN is having in your part of the world. Hopefully they get it back up soon. We'll keep an eye out if more people are having this issue.

You can always install the intel iso and add `system76-driver-nvidia` to get up and running on an nvidia-system

**Comment by brs17** [comment]
Looks like there might be an outage causing this issue: https://status.digitalocean.com/incidents/1w60w7p89hng

**Comment by brs17** [comment]
This issue looks like it has now been resolved. Please let us know if you still can not reach it.

**Comment by currymj** [comment]
I'm having the same problem -- unable to download, I get an XML document with a "NoSuchKey" error. It seems like there was a DO Spaces outage yesterday so that could be the reason.

(I have tried downloading the AMD/Intel version but it doesn't work on my machine (boots, flashes the installer for a second, then sticks me back at the login screen).)

**Comment by brs17** [comment]
@currymj As the isos are distributed via CDN, in what part of the world do you reside?

**Comment by currymj** [comment]
Washington, D.C.

**Comment by Boshimanu** [comment]
Same Issue - Romania

**Comment by Boshimanu** [comment]
Confirmed the CDN problem.... I've download it from Italy and it works!

**Comment by Nicklas2751** [comment]
I have the same problem in germany. 

```xml
<Error>
<Code>NoSuchKey</Code>
<BucketName>pop-iso</BucketName>
<RequestId>tx0000000000001f00c267b-005dba9f49-23fcca-sfo2a</RequestId>
<HostId>23fcca-sfo2a-sfo</HostId>
</Error>
```

**Comment by lukeyeh** [comment]
getting the same issue in Massachusetts

**Comment by tobiasbaehr** [comment]
Now the same with 20.04 :D

**Comment by brs17** [comment]
> Now the same with 20.04 :D

CDN cache has been cleared and should be working again.
