### ISSUE TITLE
Icons are not Pop Theme after update to 19.04

### ISSUE THREAD

**Issue by insanerwayner** [pop-os/pop#509]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Pop Icons are no longer there. I tried changing them to something else and then back but it is something else. I think it is Adwaita.

**Issue/Bug Description:**
After update to 19.04 from 18.10 the icons 

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by insanerwayner** [comment]
Okay. My mistake. I did not realize that the icon theme had changed so drastically and I thought something was broken on my system. I'll see if I can figure out a way to switch to the old theme, I thought they were prettier, but that is just taste. I will close this.

**Comment by mmstick** [comment]
Pop Planet is hosting the old icon theme: https://pop-planet.info/forums/threads/new-icon-theme-got-you-down.138/

**Comment by insanerwayner** [comment]
Thank you, sir!

**Comment by insanerwayner** [comment]
> Pop Planet is hosting the old icon theme: https://pop-planet.info/forums/threads/new-icon-theme-got-you-down.138/

Thank you, sir!
