### ISSUE TITLE
Launchpad System76 Pop Cosmic InRelease Doesn't Support Architecture '1386' update and upgrade 

### ISSUE THREAD

**Issue by TLable** [pop-os/pop#514]
-->

Running the lastest Pop!_OS 18.10 but was an error found in 18.0
 $ cat /etc/os-release
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I was installing when it first came up Lutris, League of Legends, then Origin, I was asking to install with architecture i1386 and now because I added in a new architecure '1386' the update and applications dependant on i386 dependancies now return an error asking for dependancies that meet both architecture  i386 and 1386. Any help on locating these files woulld Be great. 

**Issue/Bug Description:**
I'm new but I'll try to explain here. I intall lutris and ask it to install latest version of Origin and get hung on architecture dependant error. 

$ sudo apt-get update
[sudo] password for logan: 
Hit:1 https://dl.winehq.org/wine-builds/ubuntu cosmic InRelease
Hit:2 https://dl.winehq.org/wine-builds/ubuntu xenial InRelease                
Hit:3 http://apt.pop-os.org/proprietary cosmic InRelease                       
Hit:4 http://us.archive.ubuntu.com/ubuntu cosmic InRelease                     
Hit:5 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu cosmic InRelease    
Ign:6 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ InRelease
Hit:7 http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease             
Hit:8 http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease            
Hit:9 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_18.04 ./ Release
Hit:10 http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease    
Hit:11 http://ppa.launchpad.net/lutris-team/lutris/ubuntu cosmic InRelease
Hit:13 http://ppa.launchpad.net/system76/pop/ubuntu cosmic InRelease           
Reading package lists... Done                      
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'https://dl.winehq.org/wine-builds/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'https://dl.winehq.org/wine-builds/ubuntu xenial InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://apt.pop-os.org/proprietary cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'restricted/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'universe/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'multiverse/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'restricted/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'universe/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'multiverse/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'restricted/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'universe/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'multiverse/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'restricted/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'universe/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'multiverse/binary-1386/Packages' as repository 'http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://ppa.launchpad.net/lutris-team/lutris/ubuntu cosmic InRelease' doesn't support architecture '1386'
N: Skipping acquire of configured file 'main/binary-1386/Packages' as repository 'http://ppa.launchpad.net/system76/pop/ubuntu cosmic InRelease' doesn't support architecture '1386'

**Steps to reproduce (if you know):**
I can remove wine then dl lutris. Try to dl Origin and I get the error to close wine because the system won't support windows 7 architecture. I am unable to run wine with 64 bit support and when updating to the newest version of wine the error becomes the architecture  both 'i386' '1386' then fails installing some of the packages.

**Expected behavior:**
I've had Origin running Anthem the first time installed without too many issues, I had BFV and Apex running although Apex would not pass software based anti cheat ppackage registration. and ask me to install cross and other package management software.

**Other Notes:**

**Comment by mmstick** [comment]
There is no such thing as `1386`. That would be a typo for `i386`, if anything.

**Comment by TLable** [comment]
The terminal has a print out that says 1386 as a type os system,
architecture.
And I realize it was a typo. but now the system believes it is an
architecture to rely on for counting application dependencies.

**Comment by TLable** [comment]
it must be a txt file somewhere that has a duplicate line of code.
