### ISSUE TITLE
Failed to fetch updates on Pop! OS 19.04

### ISSUE THREAD

**Issue by victorrattis** [pop-os/pop#516]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
NA

**Issue/Bug Description:**
I have installed the new version of Pop! OS 19.04 and after of few usage hours the following issue happens:

Sometimes when I am not using my computer, I saw that had a program using the processor much time (I think a task on loop). This program is the PackageKit and so I opened the Pop! Shop and it was thrown a dialog "Failed to fetch updates", look in this picture:
![Screenshot from 2019-04-22 19-50-23](https://user-images.githubusercontent.com/1884044/56538237-f127c480-6538-11e9-9529-46f767da7c33.png)
It has the following error text:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://apt.pop-os.org/proprietary disco InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 204DD8AEC33A7AFF
E: http://apt.pop-os.org/proprietary disco InRelease is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 204DD8AEC33A7AFF)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6494C6D6997C215E
E: http://dl.google.com/linux/chrome/deb stable Release.gpg is not (yet) available (The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6494C6D6997C215E)
```

**Steps to reproduce (if you know):**
I have installed the new Pop!_OS version, installed a few programs on my computer and after of few usage hours this issue happened here.

**Expected behavior:**
NA

**Other Notes:**
Let me know if you need more information about this issue.

**Comment by victorrattis** [comment]
I think the following logs may be related to this issue (`/var/log/syslog`):

> Apr 22 19:46:11 trojan gnome-shell[1775]: Received error from DBus search provider io.elementary.appcenter.desktop: Gio.DBusError: GDBus.Err      or:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files
> Apr 22 19:46:11 trojan gnome-shell[1775]: g_environ_setenv: assertion 'value != NULL' failed
> Apr 22 19:46:26 trojan gnome-shell[1775]: Received error from DBus search provider io.elementary.appcenter.desktop: Gio.DBusError: GDBus.Err      or:org.freedesktop.DBus.Error.ServiceUnknown: The name io.elementary.appcenter was not provided by any .service files

**Comment by dannyk81** [comment]
It looks like the repo keys on your system are outdated.

the pop_os key can be updated with:
```
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 63C46DF0140D738961429F4E204DD8AEC33A7AFF
```

Source: http://apt.pop-os.org

The google key, should be fetched from Google, see if [this](https://askubuntu.com/questions/599112/google-chrome-ppa-upgrade-invalid-signature) helps.

don't forget to run `sudo apt update` afterwards.

**Comment by victorrattis** [comment]
Thank you very much for your help, my issue has been fixed successfully. 

obs.:
![Screenshot from 2019-04-22 21-40-58](https://user-images.githubusercontent.com/1884044/56702214-4bf82200-66d9-11e9-8995-e5c3a7c97bdc.png)

This picture is when this issue happens and it is a processor overhead. When it happens, no error dialog is shown to the user and this overhead worries me because the user can not see it.

**Comment by dannyk81** [comment]
@victorrattis not sure what are you trying to describe with this graph...

**Comment by victorrattis** [comment]
This is the CPU history during the issue, I added to describe the overhead caused by it. I think there is a service/program in loop due to this issue/error trying to fetch updates without stopping (a retry logic).

**Comment by dannyk81** [comment]
didn't you say that the issue was fixed by updating the keys as I suggested?

**Comment by victorrattis** [comment]
Yes, the issue has been fixed successfully. Thanks for that.
Sorry so much, I have not been clear, I would like to say there is a retry logic that is overheating the processor when it cannot fetch the updates. Highlighting this issue and it could happen at another time here or in other users and they could not see it.

I am closing this issue as completed because my issue was fixed.
Thank you for your support. =)

**Comment by dannyk81** [comment]
Pop_shop may be trying to update the repos while it's running, but your graph just showed the per cpu usage, how do you know it's pop_shop that is consuming the cpu??

anyway, this should be sorted now.

**Comment by nadyrbek97** [comment]
@dannyk81 Please sir help me, I have the same problem , after updating pop os 19.04 to 19.10 , my sound dissapeared, and I have this message in pop shop "The repository 'http://ppa.launchpad.net/ubuntu-audio-dev/ppa/ubuntu eoan Release' does not have a Release file.

**Comment by leviport** [comment]
@nadyrbek97 You probably just need to disable that PPA. Open Pop!_Shop, click the cog on the top right, go to "Extra Sources", find that PPA and disable it. Then you should be able to install updates properly.

**Comment by re-mc** [comment]
> It looks like the repo keys on your system are outdated.
> 
> the pop_os key can be updated with:
> 
> ```
> $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 63C46DF0140D738961429F4E204DD8AEC33A7AFF
> ```
> 
> Source: http://apt.pop-os.org
> 
> The google key, should be fetched from Google, see if [this](https://askubuntu.com/questions/599112/google-chrome-ppa-upgrade-invalid-signature) helps.
> 
> don't forget to run `sudo apt update` afterwards.

Thanks soooooo much!!!!
