### ISSUE TITLE
Screen freezes when using mouse macros and keyboard keys simultaneously

### ISSUE THREAD

**Issue by remissio** [pop-os/pop#523]
**Distribution (run `cat /etc/os-release`):**

POP!_OS, Ubuntu and Arch were tested with gnome 3.30 and 3.32
  
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome

**Issue/Bug Description:**

* When using the macro keys on each of the used mice (while a keyboard key is pressed) the whole screen freezes for roughly a second.
* The freeze persists for way longer when clicking the mouse button multiple times.

**Steps to reproduce (if you know):**

* Tested mice: "Logitech G700", "Logitech G700s" and "Corsair Scimitar pro RGB"
* Distributions used: "Arch", "Ubuntu" and "POP!_OS"
* Tried it on my desktop pc and 2 laptops
* This only happens for special keys, not the default mouse keys

**Other Notes:**

* Cinnamon, as a Gnome fork, does not have this issue
* On Arch the X11 session was chosen under LightDM
* On Gnome and POP!_OS the default sessions were used
* I've had this issue in Gnome 3.30 and 3.32

**Comment by mmstick** [comment]
You're saying that GNOME causes this behavior on Arch and Pop!_OS?

**Comment by remissio** [comment]
Atleast i have had this issue only under gnome when desktop hopping under Arch.
Then later i've found this issue again under Ubuntu and POP!_OS.

**Comment by remissio** [comment]
** Update **

I've just switched to LightDM on my POP!_OS machine and selected the Wayland session.
It is not a problem under Wayland.

**Comment by mmstick** [comment]
Yes, I've long suspected that there are X11 issues in GNOME that cause the screen to freeze. You may want to report this to GNOME's Gitlab though, as they'd be in a better position to diagnose the cause and fix it.
