### ISSUE TITLE
Quit button missing from GNOME dash icons

### ISSUE THREAD

**Issue by davidbailey00** [pop-os/pop#528]
**Distribution (run `cat /etc/os-release`):**
 
 ```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
gnome-shell:
  Installed: 3.32.0+git20190410-1ubuntu1pop0~1555607389~19.04~56282e6
  Candidate: 3.32.0+git20190410-1ubuntu1pop0~1555607389~19.04~56282e6
  Version table:
 *** 3.32.0+git20190410-1ubuntu1pop0~1555607389~19.04~56282e6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
        100 /var/lib/dpkg/status
     3.32.0+git20190410-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
```

**Issue/Bug Description:**

Quit button missing from GNOME dash:
![image](https://user-images.githubusercontent.com/4248177/56900872-ca184800-6a8e-11e9-977e-6908cd206a6c.png)

**Steps to reproduce (if you know):**

1. Open an application
2. Press Activities
3. Right-click the open application

**Expected behavior:**

A quit button is visible.

**Other Notes:**

**Comment by davidbailey00** [comment]
Upstream: https://gitlab.gnome.org/GNOME/gnome-shell/issues/1226

**Comment by davidbailey00** [comment]
Apparently there was never a quit button (at least in upstream GNOME since 3.0) - maybe I imagined one being there ¯\\\_(ツ)_/¯

I'll leave this open for the Pop developers to decide whether it would be worth adding one, or in case one of the built-in Pop!_OS extensions was meant to add this button.

**Comment by dvisztempacct** [comment]
Requesting `kill -15` and `kill -9` menu options

**Comment by jacobgkau** [comment]
21.04's dock adds a quit button in the dash/dock.

![Screenshot from 2021-06-22 15-03-49](https://user-images.githubusercontent.com/7199422/122999179-2cb5b780-d36b-11eb-8c2d-f6b630991b57.png)

For 20.04 LTS, the quit button is located in the top-left app menu (this menu has been removed in 21.04, which is why the option moved to the dock.)

![Screenshot from 2021-06-22 15-05-19](https://user-images.githubusercontent.com/7199422/122999306-553db180-d36b-11eb-8adf-a94f6836e9ed.png)
