### ISSUE TITLE
System hard lock

### ISSUE THREAD

**Issue by tgelter** [pop-os/pop#532]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Here are a couple of traces from when the hard lock occurs:
https://pastebin.com/Assn9mw7
https://pastebin.com/JtyrAd8j

**Steps to reproduce (if you know):**
Unknown (it's occurred a few times during "normal operation" of the laptop)

**Expected behavior:**
Don't hard lock. :-)

**Other Notes:**
Thank you!

**Comment by mmstick** [comment]
> LENOVO 20MF000MUS/20MF000MUS, BIOS N2EET37W (1.19 ) 01/31/2019

You will want to look for any firmware updates available for your system, and if none, ask Lenovo if they know what's causing the general protection fault in Ubuntu 19.04 (5.0.0-13-generic).

**Comment by alphastrata** [comment]
I'm also experiencing this.. tried a clean install - nothing.
```
Ryzen 1800x
GTX1080ti
32GB ram
Asus mobo (taichi)
```

Tried updating firmware etc on all above to no avail... I'm outta ideas.

**Comment by tgelter** [comment]
The really odd thing about this issue is that it has plagued me 3 times since about 6 months ago, leaving for a month or two at a time, then recurring. I've consistently applied OS & firmware upgrades and haven't found any commonality between any particular upgrade and the frequency of the hard lock.

**Comment by alphastrata** [comment]
@tgelter What kind of processor were/are you running? A recent bios update disabling `C6` power saving features on Ryzen chips has resolved all my freezes.

**Comment by tgelter** [comment]
@alphastrata, thanks for the heads up, unfortunately I've got a **Intel(R) Core(TM) i7-8850H CPU**.

**Comment by tgelter** [comment]
I no longer use PopOS, closing this old issue.
