### ISSUE TITLE
Stuck at grey screen after login

### ISSUE THREAD

**Issue by Bearbobs** [pop-os/pop#533]
Using pop os 19.04 intel/amd version
After password input , the screen goes grey and desktop never shows up

**Comment by mmstick** [comment]
When did this start happening (what happened to the system the last time it was logged in)?

**Comment by Bearbobs** [comment]
I installed pop yesterday from the iso, jst put on some code editor customized theme and icon from gnome desktop environment.
Yesterday also it happened but after reboot it got fixed.
Today again the same issue.

**Comment by mmstick** [comment]
If you can log in from a different TTY, the usual steps to resolve issues are to

1. Reinstall pop-desktop

```
sudo apt install --reinstall pop-desktop
```

2. Check if a local config is messing things up

```
mv ~/.config ~/.config.bak
```

3. Reinstall the NVIDIA driver (if applicable)

```
sudo apt install --reinstall nvidia-dkms-418
```

**Comment by Bearbobs** [comment]
Showing unmet dependencies in reinstalling pop dektop

**Comment by Bearbobs** [comment]
Update: my mouse cursor is also stuck on that grey screen

**Comment by mmstick** [comment]
You'll have to find out what's causing the conflicts with `pop-desktop`, and remove it.

**Comment by Bearbobs** [comment]
Fixed it by moving config thx for the help

**Comment by javiaurea** [comment]
Hello @Bearbobs @mmstick Can you describe how you solved the problem? The detailed steps I should follow. The same thing is happening to me with System76 and Apple Studio Display.

**Comment by Bearbobs** [comment]
Hey mate, unfortunately i don't use that setup anymore
As far as i remember it was an issue with .profile file, if you are still using 19.04 i will suggest updating to new release
