### ISSUE TITLE
GUI not working anymore after trying to install nvidia-prime

### ISSUE THREAD

**Issue by EmielSchmeink** [pop-os/pop#534]
**Distribution (run `cat /etc/os-release`):**
 
 Pop os 19.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Tty1 is a grey screen with a blinking cursor.

**Steps to reproduce (if you know):**

**Expected behavior:**

The normal login shows up.

**Other Notes:**

As the title tells, I tried to install nvidia prima on my laptop, but that failed horribly, and now the nvidia-drivers are completely messed up. The gui doesn't show up and instead I get an entire grey screen with a blinking cursor. The gui does work without the nvidia drivers, but that's not an option. Any ideas?

**Comment by EmielSchmeink** [comment]
I fixed it by manually restarting the X server

**Comment by mmstick** [comment]
There is no need to install `nvidia-prime`. We have graphics switching provided already by `system76-power`. It is incompatible with our driver packaging, so it may have removed the nvidia driver.
