### ISSUE TITLE
Removing gedit breaks multiple things

### ISSUE THREAD

**Issue by mvelinder** [pop-os/pop#543]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gedit:
  Installed: 3.32.0-3
  Candidate: 3.32.0-3
  Version table:
 *** 3.32.0-3 500
        500 http://us.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     3.32.0-2 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages

**Issue/Bug Description:**
Removing gedit via `sudo apt purge gedit` prevents gnome-control-center "Settings" from opening and prevents the VPN icon from correctly showing in top menu bar. There may be other things removing gedit breaks as well, but these were the two I noted. It also didn't break "Settings" right away, but a hard reset may have triggered it?

**Steps to reproduce (if you know):**
Remove gedit via `sudo apt purge gedit`
Update, clean via `sudo apt update ; sudo apt upgrade; sudo apt autoclean; sudo apt autoremove`
wait for "Settings" to break
Reinstall gedit via `sudo apt install gedit`
Update, clean via `sudo apt update ; sudo apt upgrade; sudo apt autoclean; sudo apt autoremove`
"Settings" should launch now

**Expected behavior:**
That removing the default GUI text editor does **not** break the ability to open "Settings"

**Other Notes:**
`/var/log/syslog` gives this error when trying to launch gnome-control-center "Settings" when gedit is not installed
```
May  7 13:07:55 galago gnome-shell[1544]: g_environ_setenv: assertion 'value != NULL' failed
May  7 13:07:55 galago /usr/lib/gdm3/gdm-x-session[1390]: (II) modeset(0): EDID vendor "AUO", prod id 16445
May  7 13:07:55 galago /usr/lib/gdm3/gdm-x-session[1390]: (II) modeset(0): Printing DDC gathered Modelines:
May  7 13:07:55 galago /usr/lib/gdm3/gdm-x-session[1390]: (II) modeset(0): Modeline "1920x1080"x0.0  141.00  1920 1936 1952 2104  1080 1083 1097 1116 -hsync -vsync (67.0 kHz eP)
May  7 13:07:55 galago gnome-control-c[3843]: Settings schema 'org.gnome.gedit.preferences.editor' is not installed
May  7 13:07:55 galago kernel: [  140.956211] traps: gnome-control-c[3843] trap int3 ip:7f07ce122955 sp:7ffc5e949ec0 error:0 in libglib-2.0.so.0.6000.0[7f07ce0e9000+80000]
```

**Comment by mmstick** [comment]
Please don't remove gedit. As you can see, removing desktop-critical packages breaks the desktop, and makes it difficult to support you. :cry:

**Comment by AgnishRoy** [comment]
I'm on pop 18.04. Removing Gnome breaks the installation completely.
