### ISSUE TITLE
Fractional scaling zooms rather than scales on Nvidia GFX (works on intel) [X1 Extreme]

### ISSUE THREAD

**Issue by point-source** [pop-os/pop#546]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"

Lenovo X1 Extreme
i7- 8750H
32GB RAM
2x 256GB SSD
Nvidia 1050 Ti
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome / display manager / xorg

**Issue/Bug Description:**
When running on nvidia graphics, selecting a scaling factor of anthing between 100% and 200% results in the screen contents appearing "zoomed" and anchored at the upper left corner rather than scaling down and fitting the screen. Clipping occurs on the right and bottom edges. Scaling works properly when using intel graphics.

**Steps to reproduce (if you know):**
Switch to nvidia graphics, set scaling factor to something between 100% and 200%

**Expected behavior:**
UI elements should scale in size but not become hidden

**Comment by point-source** [comment]
This appears to have been fixed in the latest round of updates. Going to close for now until it pops up again

**Comment by igavrysh** [comment]
I experience the same issue with Thinkpad X1 Extreme, Nvidia 450.66 driver version, ubuntu 20.04.1
