### ISSUE TITLE
Pop!_Shop is not responding!

### ISSUE THREAD

**Issue by yahkun** [pop-os/pop#550]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

The appcenter Pop!_OS is stuck and not responding every time after a few seconds I opened it, and the CPU utilized percent is unusually high before the appcenter is stuck. Have to force quit it.

**Steps to reproduce (if you know):**

Open the Pop!_OS, wait for a few seconds, it reproduces 100% on my PC.

**Expected behavior:**

**Other Notes:**

![image1](https://coding-net-production-pp-ci.codehub.cn/8582cdb2-8b8d-47ad-a331-c95803148250.png)
When open Pop!_Shop, CPU utilited percent go unusually high. Then the app get stuck, and CPU utilited percent become normal.

![image2](https://coding-net-production-pp-ci.codehub.cn/34501670-541b-45cc-892c-ae1e4cc1f653.png)
"Pop!_Shop" is not responding. Have to force quit.

**Comment by BootlegPhil** [comment]
Maybe try a fresh install. It's been a while since this issue was opened, so this could have been fixed.

**Comment by Jasonwi** [comment]
@BootlegPhil on my version 20.04(on Vmware) equally issue also happened

**Comment by SZP1206** [comment]
Same...
Anyone knows how to fix it?

**Comment by SnapeFung** [comment]
The same...

**Comment by leviport** [comment]
This looks like a duplicate of https://github.com/pop-os/shop/issues/119
