### ISSUE TITLE
Add encryption for custom install

### ISSUE THREAD

**Issue by aunetx** [pop-os/pop#551]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
The installer and cryptosetup ?

**Issue/Bug Description:**
During the installation process, there is no way to choose to customize the install (option 'Custom Install') and encrypt partitions that are selected.
I believe that this is more an Elementary OS issue, since we're using their installer, but I don't know if encryption is from their installer thought. Of course I can choose to use 'Default Installation' but I would like to keep some space on my ssd and hdd for later.

**Steps to reproduce (if you know):**
- Begin the installation
- Choose 'Custom Install'
- Can't encrypt any partition

**Expected behavior:**
Maybe add an encryption for some given partitions if needed ? Or maybe there is a way but not  enough visible at all.

**Other Notes:**
I am sorry for multiple mistakes, you have internationals users hehe

**Comment by aunetx** [comment]
(well I just saw that the answer was already given : [no way](https://github.com/pop-os/installer/issues/144))
But is there really no way or workaround ? As he said :

> not in the graphical installer

means maybe install from cli ? Well sorry for the duplicate

**Comment by mmstick** [comment]
You can use graphical tools like GNOME Disks to set up encryption in advance. The installer isn't meant to be a partitioner.

**Comment by aunetx** [comment]
Oh well I didn't know that setting encryption before installation worked, but that's logical after all.
Thanks ^^
