### ISSUE TITLE
Laptop's keyboard prints wrong characters

### ISSUE THREAD

**Issue by topaz-akeneo** [pop-os/pop#553]
I've just installed a fresh version of pop os and whenever I click on 'p' it prints '*' and when I click on '/' (the one near the right shift button I get +.

In the "Region & Language" section of the settings when I look at the keyboard layout it thinks my laptop has a numeric keypad on the right and the button 'p' translates as a click on the '*' of the numeric keypad the same goes for '/' that translates to a '+' of the numeric keypad.

My laptop is Asus ux550v.

Thanks for any help with this

**NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
**

**Comment by mmstick** [comment]
You'll have to ask ASUS about the quirks specific to their laptop.

**Comment by topaz-akeneo** [comment]
I figured the solution.
The computer thinks the num lock is pushed although I don't really have have a num lock key, because my laptop has no side number pad. I pressed fn+insert to toggle my virtual num lock.

**Comment by brs17** [comment]
> I figured the solution.
> The computer thinks the num lock is pushed although I don't really have have a num lock key, because my laptop has no side number pad. I pressed fn+insert to toggle my virtual num lock.

Many laptops have numlock even if they do not have a separate numpad (for those who want/need to input numbers with a layout similar to the numpad. In my experience, numlock state seems to be remembered between boots. Which usually means you should only see issues like that if you are sometimes booting with an external keyboard (and enablling numlock there) and other times booting without (so numlock may still be enabled from having the external keyboard plugged in).
