### ISSUE TITLE
Virtual Box, cant find other hdd directories, in popOS only

### ISSUE THREAD

**Issue by rrvillareal2011** [pop-os/pop#554]
**Distribution (run `cat /etc/os-release`):**
 
 Pop OS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

VirtualBox

**Issue/Bug Description:**

After installing virtual box, when I try to add my IOS to install windows 7, For some reason it cant locate the directory for my internal hdd, It can only see the hdd where the popOS is installed on,

But when using ubuntu I dont get that issue, 

**Steps to reproduce (if you know):**

Install popOS, install Virtualbox, then when try crating a virtualmachine to add IOS or to change the default directory when adding new virtualmachine. 

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
Have you tried this with `virt-manager`? In general it's often better to use the native QEMU/KVM support than to use VirtualBox on Linux.

**Comment by mmstick** [comment]
You can install and use virt-manager by running the following:

```
sudo apt install ovmf virt-manager
sudo adduser ${USER} kvm
sudo adduser ${USER} kvm
```

Log out, log back in, and you can launch the "Virtual Machine Manager" which will step you through the creation of a new VM. At the end, it will ask if you want to do some additional configuration before launching the VM, and this is were you can change the firmware to the OVMF EFI firmware.

**Comment by rrvillareal2011** [comment]
Yes, it like the other drive is not mounted, but if I go to my files and
otgers, it shows up and I can open the drive,

**Comment by rrvillareal2011** [comment]
Sorry I didnt try that, ill give it a try, is there a way I can send a
short video to show the issue?

**Comment by mmstick** [comment]
There's a tool that you can install from the repos, named `peek`. It provides the ability to capture a portion of the screen or window as either a GIF, APNG, MP4, or WebM.

**Comment by rrvillareal2011** [comment]
I meant i can capture it on my mobile then upload it in google drive and
share the link instead. Can I do it that way?

**Comment by rrvillareal2011** [comment]
Hi Michael,

I'm getting this error in virtual manager
[image: image.png]

Also, this is the original issue I have with virtualbox

[image: image.png]

When I brows for my ISO when creating a virtual machine, It doesnt show my
2nd internal HDD
[image: image.png]

But as you can see, its in there, the BACKUP_01
[image: image.png]

And its mounted

**Comment by rrvillareal2011** [comment]
Hi Michael,

I'm getting this error in virtual manager
https://drive.google.com/file/d/1fYVgKsQoMyHuQybdNY9GaYNSB2yQoxVw/view?usp=sharing

Also, this is the original issue I have with virtualbox
https://drive.google.com/file/d/1FooI2HPDXPmjeB7mw4UTi_lPsRahVu_I/view?usp=sharing


When I brows for my ISO when creating a virtual machine, It doesnt show my 2nd internal HDD
https://drive.google.com/file/d/1mYJokKx40_Z4_-y3Yq48Ao4PkpJiWE5Z/view?usp=sharing


But as you can see, its in there, the BACKUP_01
https://drive.google.com/file/d/1fs6vshHdgjGSt0hzC7hiakyzpKs96FST/view?usp=sharing


And its mounted

**Comment by mmstick** [comment]
I see the misunderstanding. Linux does not mount tertiary drives by default. The only drives which are mounted out of the box are the partitions defined in the `/etc/fstab` file. Nautilus displays mount-able partitions in its UI and uses gvfs (GNOME Virtual FIlesystem) to temporarily mount them in user space. Removable drives are automounted to `/media/${USER}/${PARTUUID}`.

You need to set up a more permanent mount by adding your backup partition as an entry in `/etc/fstab`. You may also need to change the permissions of the partition to allow read/write access by your user account. By default, it shall be owned by root.

**Comment by rrvillareal2011** [comment]
I added that entry it just deleted my 2nd drive, but also, it is mounted and i can access it if i go to files, I just cant access it.on virtualbox,.its as if.the virtual box dont have permission to access the 2nd drive
