### ISSUE TITLE
Update NVIDIA driver to 430.14

### ISSUE THREAD

**Issue by kassindornelles** [pop-os/pop#561]
Can you guys upgrade the NVIDIA drivers to 430.14 on Pop!_OS 18.04?
That includes some vulkan performance improvements and vulkan extensions that DXVK/Steam Play needs to perform better.

**Comment by brs17** [comment]
We are currently working on it here: https://github.com/pop-os/nvidia-graphics-drivers/pull/7 but running into some issues upgrading to all of the OSes we need to update. 

If you really want to get it today on Pop!_OS 18.04, you can add the proposed repo and upgrade:
```
sudo add-apt-repository ppa:system76/proposed # press enter when prompted
sudo apt update
sudo apt upgrade
```
