### ISSUE TITLE
Yubikey 5C not recognised in USB C port.

### ISSUE THREAD

**Issue by brierjon** [pop-os/pop#571]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
yubikey-manager:
  Installed: 2.1.0~ppa1~disco1
  Candidate: 2.1.0~ppa1~disco1

**Issue/Bug Description:**
A brand new Yubkikey 5c is not recognised when inserted to the Serval WS USB C port.

**Steps to reproduce (if you know):**
Start Yubikey Manager
Insert Yubikey 5C
Yubikey Manager does not acknowledge Yubikey 5C was inserted (touched or without touch)

Second reproduction - pairing with Google Account via Chrome.
Start Chrome
visit accounts.google.com
select 2 factor configuration, proceed to add new key
Insert key when prompted and touch the sides
Adding fails as no key is recognised.

**Expected behavior:**
Startup Yubikey Manager (or other program where the key has been associated)
Insert Yubikey 5C 
Yubikey Manager reports it sees a Yubikey 5C and some details

**Other Notes:**
This key is recognised and functions as expected on a Chromebook and Android Phone, only on Pop!_OS on this hardware is the key not recognised. Other Yubikeys on USB B ports work just fine and appear in the Yubikey-manager. My guess is this is software recognition of the key and not so much the USB C port hardware.

**Comment by isantop** [comment]
I can't seem to replicate this issue with a Yubikey 4C, and @ahoneybun has a Yubikey 5 that also works fine. From the OS perspective, there isn't actually a difference between the 5 and the 5C, so I'm skeptical that this is a software issue in Pop.

**Comment by brierjon** [comment]
Yeah, I was able to test the 5C on another System76 laptop today and tested a USB A to USB C drive... it was hardware. Sorry for the spam, closing.
