### ISSUE TITLE
Screenshot Area Selection Faulty

### ISSUE THREAD

**Issue by meatnordrink** [pop-os/pop#577]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_OS 19.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Screenshot Utility

**Issue/Bug Description:**

The screenshot utility doesn't produce any visible "square" when you select a region of the screen. It works, but it's a little janky just guessing where the edge of the square you're making is. 

**Steps to reproduce (if you know):**

Open "screenshot," choose "select area to grab," and try to take a screenshot.

**Expected behavior:**

Most screenshot utilities use a semi-opaque window to show you the area you're capturing. 

**Other Notes:**

I'm on a brand-new System76 Meerkat running only Pop!_OS, so it shouldn't be any kind of compatibility or driver issue.

**Comment by mmstick** [comment]
Also noticing the same on my end.

**Comment by isantop** [comment]
I can not reproduce the issue using the Adwaita shell theme, so this appears to be another case where they made breaking CSS changes in a patch release.
