### ISSUE TITLE
pop-os installer not booting

### ISSUE THREAD

**Issue by kearfy** [pop-os/pop#578]
**Distribution**
 
 Both 18.04 LTS and 19.04

**Issue/Bug Description:**

Pop-os installer only shows a non blinking _ on the screen when trying to boot into the installer.
This issue only seems to happen on my "Teclast F5" laptop, on my desktop it boots just fine.
i've tried to use both 18.04 and 19.04, nvidia and non-nvidea, with and without secure boot, usb3.0 and usb2.0, but it does the same thing over and over again.

**Steps to reproduce:**

Just boot the pop-os installer on a teclast F5 laptop

**Expected behavior:**

the screen only showing a non-blinking "_", endlessly

**Other Notes:**

Please tell me if i'm missing anything.

**Comment by royfall** [comment]
I have the same issue on my ASUS Zenbook UX333FA (Intel Core i5-8265U, Video: Intel UHD 620, 8GB DDR3L). BIOS revision: 306. I have disabled secure boot and fast startup in BIOS settings. Ubuntu 19.04 boots fine.

**Comment by kearfy** [comment]
Ah, well for me none of both 18 and 19 seem to work, but there is a big chance we have the same issue i guess

**Comment by royfall** [comment]
Sorry, I meant Pop _OS! 18.04 and 19.04 dont boot but ubuntu 19.04 does boot.

**Comment by kearfy** [comment]
Ah, m2

**Comment by featherspeed** [comment]
For me the problem was the installer didn't set my flags on my hhd to boot

**Comment by kearfy** [comment]
Well, in our case the installer doesnt even boot, while it boots fine on my pc

**Comment by featherspeed** [comment]
Mabe you can boot to the efi file ore disable secure boot that was recommended by most of the posts i saw

**Comment by kearfy** [comment]
Tried all of it

**Comment by featherspeed** [comment]
On my machine i had a support legacy boot 
And also under my security settings i had options that blocked me from making changes to certain settings like the boot options so it always changed back to the default value

**Comment by featherspeed** [comment]
Can you get a Ubuntu or a Windows startup disk to load

**Comment by kearfy** [comment]
I can indeed, i will look into it soon

**Comment by ShadowAUS** [comment]
I also have this same issue with an Asus Zenbook UX433FN-A5037T (i7 8565U, MX150). Both the current and LTS images. Confirmed working on separate machine.
Everyone that I've seen that has had this issue and solved it has done it by enabling CSM/Legacy Boot in the BIOS so if you're having this issues make sure you check for that in your BIOS.
Unfortunately Legacy Boot is unsupported on Coffee Lake and newer CPU's and thus ASUS has removed the option to enable Launch CSM in the BIOS of the laptops featuring these CPUs. I haven't found a workaround at this stage though if anyone has any information on possible solutions I would love to hear it.

**Comment by featherspeed** [comment]
You can browse for your boot file by going into the boot menu selecting boot from file and navigating to the selected install drive also make sure the drive is bootable set in its partitions

**Comment by ShadowAUS** [comment]
The drive is flagged as boot. Booting from file does the same thing, black screen with an _ that blinks once and then hangs.

**Comment by featherspeed** [comment]
Did you reinstall after you modified the bios that was also a problem i encountered as i moved my bios over to legacy 

I can only assume that the same applies if it goes from a legacy to a sucure boot

**Comment by ShadowAUS** [comment]
Yes, I've reinstalled since bios modifications. Still no luck sadly.

**Comment by PeppaPigHS** [comment]
I face the same problem too. It happens on my Zenbook UX433FN (the nvidia version). BIOS revision : 307. Seem like the problem hasn't been fixed yet even with the latest BIOS update.

**Comment by szabolaszlo** [comment]
Hi, Same problem here. I have UX433FN. I update BIOS to 308.
Only a blank screen on boot. I tried to disable secure boot, touchpad, all usb, disable everything but no matter. Only a blank screen. But ubuntu works fine, only the pop os not booting, unfortunetly but previous notebook I love this OS, much better than ubuntu so I hope finally the 20.04 version solve this problem ;)

**Comment by Sohib** [comment]
i just bought UX333FA-AB77 Zenbook 13,I can confirm this issue happened to me, Ubuntu booted without any problems but pop os didn't.  Secure Boot has been disabled for the machine.

**Comment by kevhemingway88** [comment]
still no solution
see this:
https://www.reddit.com/r/pop_os/comments/dkgqd4/6_months_later_still_cant_boot_with_any_version/

**Comment by szabolaszlo** [comment]
Yeeeha!
It seems to be working!
https://www.reddit.com/r/pop_os/comments/c9rsv7/any_experience_installing_pop_os_on_asus_zenbook/f7o6kqg/?utm_source=share&utm_medium=web2x

> I have a ux533fd, and it has a similar issue. the problem seems to be with the grub bootloader inside the iso.
> i have managed to overcome this and install pop os 19.10 on my machine using the following workaround.
> boot into a running grub (another live cd, current Linux install)
> Press Esc key in order to get into grub CLI.
> using the ls command detect the correct path for pop os install disk, mine was (hd0), at this stage also note and write the label of the pop os device.
> then type:
> search --set=root --label "<pop os device label>"
> configfile /boot/grub/grub.cfg
> after those lines are typed, grub will change into pop os grub loader (if it won't, press Esc key)
> now you can go forward with the installer just as you would on a regular Linux installer.

I try it, boot on exist ubuntu, push esc on booting, I am in grub cli. type commands below and boot up POP OS! and the live installer is strat. 
I don't want to install yet becouse I have to make a lot of backup, but I will try is soon.
I already use POP, when I change my notebook, I have to change to ubuntu. But after few month I think pop os much better than ubuntu, so I will try to install it as soon as possible.

**Comment by kearfy** [comment]
> Yeeeha!
> It seems to be working!
> https://www.reddit.com/r/pop_os/comments/c9rsv7/any_experience_installing_pop_os_on_asus_zenbook/f7o6kqg/?utm_source=share&utm_medium=web2x
> 
> > I have a ux533fd, and it has a similar issue. the problem seems to be with the grub bootloader inside the iso.
> > i have managed to overcome this and install pop os 19.10 on my machine using the following workaround.
> > boot into a running grub (another live cd, current Linux install)
> > Press Esc key in order to get into grub CLI.
> > using the ls command detect the correct path for pop os install disk, mine was (hd0), at this stage also note and write the label of the pop os device.
> > then type:
> > search --set=root --label ""
> > configfile /boot/grub/grub.cfg
> > after those lines are typed, grub will change into pop os grub loader (if it won't, press Esc key)
> > now you can go forward with the installer just as you would on a regular Linux installer.
> 
> I try it, boot on exist ubuntu, push esc on booting, I am in grub cli. type commands below and boot up POP OS! and the live installer is strat.
> I don't want to install yet becouse I have to make a lot of backup, but I will try is soon.
> I already use POP, when I change my notebook, I have to change to ubuntu. But after few month I think pop os much better than ubuntu, so I will try to install it as soon as possible.

Is there any way i can complete that process without grub cli, cuz i don't have one available atm. Or maybe you could try to send me a clone of your usb drive?

**Comment by szabolaszlo** [comment]
> > Yeeeha!
> > It seems to be working!
> > https://www.reddit.com/r/pop_os/comments/c9rsv7/any_experience_installing_pop_os_on_asus_zenbook/f7o6kqg/?utm_source=share&utm_medium=web2x
> > > I have a ux533fd, and it has a similar issue. the problem seems to be with the grub bootloader inside the iso.
> > > i have managed to overcome this and install pop os 19.10 on my machine using the following workaround.
> > > boot into a running grub (another live cd, current Linux install)
> > > Press Esc key in order to get into grub CLI.
> > > using the ls command detect the correct path for pop os install disk, mine was (hd0), at this stage also note and write the label of the pop os device.
> > > then type:
> > > search --set=root --label ""
> > > configfile /boot/grub/grub.cfg
> > > after those lines are typed, grub will change into pop os grub loader (if it won't, press Esc key)
> > > now you can go forward with the installer just as you would on a regular Linux installer.
> > 
> > 
> > I try it, boot on exist ubuntu, push esc on booting, I am in grub cli. type commands below and boot up POP OS! and the live installer is strat.
> > I don't want to install yet becouse I have to make a lot of backup, but I will try is soon.
> > I already use POP, when I change my notebook, I have to change to ubuntu. But after few month I think pop os much better than ubuntu, so I will try to install it as soon as possible.
> 
> Is there any way i can complete that process without grub cli, cuz i don't have one available atm. Or maybe you could try to send me a clone of your usb drive?

Hi,
So this is not the most confortable thing in the world but not impossible, so 
- you have to take two usb flash drive (let it A and B)
- The A drive have to contains an ubuntu or any linux distro what is able to boot on your device
- The B drive have to contains the PopOS installer
- Plug in both to your machine
- Boot from A drive and when you see the grub boot menu (try ubuntu, install ubuntu, etc) push ESC and you into grub cli.
- Then type two commands below the previous comment (label is your flash drive label not hd0 or sda)
- At this time the grub use B drive to boot so your pop installer is booting.

I hope this will help you

**Comment by kearfy** [comment]
I can now happily confirm this method is working, i'm having a few other issues, but since they are not related to this thread, i will now close it.

**Comment by kearfy** [comment]
An addition to the already working fix: it seems like they have fixed the issue (at least in my case) since release 19.10! So no need to any tricky actions anymore.
