### ISSUE TITLE
Theme parsing error: gtk.css

### ISSUE THREAD

**Issue by tekblupace** [pop-os/pop#582]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
In sysylog there is a Gtk-WARNING"
`Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name`

This relates to the following applications:-
Web Content
evolution-alarm
firefox
firefox.desktop
gedit
gnome-calculato
gnome-calendar
gnome-control-c
gnome-shell
gnome-terminal-
gnome-tweaks
gsd-clipboard
gsd-color
gsd-keyboard
gsd-media-keys
gsd-power
gsd-wacom
gsd-xsettings
io.elementary.a
nautilus
nvidia-settings
org.gnome.Terminal.desktop
seahorse

**Steps to reproduce (if you know):**
cat /var/log/syslog | grep 'Theme parsing error'

**Expected behavior:**
No warning found

**Other Notes:**

**Comment by jackpot51** [comment]
Fix was done in pop-gtk-theme repository

**Comment by tekblupace** [comment]
Is this in the standard repository's included with pop, or do i need to install it?

**Comment by mmstick** [comment]
You'll need to wait for the package to be updated in the stable repositories.

**Comment by tekblupace** [comment]
Thanks guys...
