### ISSUE TITLE
Forced reset of "appfolders" settings

### ISSUE THREAD

**Issue by maoschanz** [pop-os/pop#583]
It's a bug but i report it as a developer who doesn't use Pop OS so the template is empty.

**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

gnome-shell, i guess

**Issue/Bug Description:**

https://github.com/maoschanz/appfolders-manager-gnome-extension/issues/55

**Steps to reproduce (if you know):**

**Expected behavior:**

As in all other existing distros, the default settings should not prevent the user from setting his own

**Other Notes:**

**Comment by ayoungethan** [comment]
$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Comment by jackpot51** [comment]
@maoschanz this is the program that sets up the app folders for Pop!_OS. Do you see anything that would touch the settings for your extension?

```
$ cat /usr/bin/pop-app-folders 
#!/bin/sh

APP_FOLDER="org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Pop"

gsettings reset-recursively "${APP_FOLDER}-Office/"
gsettings set "${APP_FOLDER}-Office/" name "Office.directory"
gsettings set "${APP_FOLDER}-Office/" translate true
gsettings set "${APP_FOLDER}-Office/" apps "[
'libreoffice-calc.desktop',
'libreoffice-draw.desktop',
'libreoffice-impress.desktop',
'libreoffice-math.desktop',
'libreoffice-startcenter.desktop',
'libreoffice-writer.desktop'
]"

gsettings reset-recursively "${APP_FOLDER}-System/"
gsettings set "${APP_FOLDER}-System/" name "System.directory"
gsettings set "${APP_FOLDER}-System/" translate true
gsettings set "${APP_FOLDER}-System/" apps "[
'gnome-language-selector.desktop',
'gnome-session-properties.desktop',
'gnome-system-monitor.desktop',
'im-config.desktop',
'nm-connection-editor.desktop',
'nvidia-settings.desktop',
'org.gnome.baobab.desktop',
'org.gnome.DiskUtility.desktop',
'org.gnome.PowerStats.desktop',
'org.gnome.seahorse.Application.desktop',
'software-properties-gnome.desktop',
'system76-driver.desktop',
'system76-firmware.desktop'
]"

gsettings reset-recursively "${APP_FOLDER}-Utility/"
gsettings set "${APP_FOLDER}-Utility/" name "X-GNOME-Utilities.directory"
gsettings set "${APP_FOLDER}-Utility/" translate true
gsettings set "${APP_FOLDER}-Utility/" apps "[
'com.github.donadigo.eddy.desktop',
'eog.desktop',
'gucharmap.desktop',
'org.gnome.Evince.desktop',
'org.gnome.FileRoller.desktop',
'org.gnome.font-viewer.desktop',
'org.gnome.Screenshot.desktop',
'org.gnome.Totem.desktop',
'popsicle.desktop',
'simple-scan.desktop',
'yelp.desktop'
]"
```

**Comment by maoschanz** [comment]
My extension just edits the appfolder settings, so as long as the folders defined here are reset recursively, it undoes all apps modifications to these folders

It's coherent with the observations of @ayoungethan who, if i understand correctly, "fixed" the issue on his system because the new folders he created have different ids so they are not reset (and the script doesn't modify the "folder-chidren" key so the reset folders are not shown on his system)

**Comment by jackpot51** [comment]
@maoschanz we will have a fix for this shortly: https://github.com/pop-os/default-settings/pull/59

**Comment by maoschanz** [comment]
Nice, thank you very much!
