### ISSUE TITLE
Skype notifications issue

### ISSUE THREAD

**Issue by kronikpillow** [pop-os/pop#592]
**Distribution :**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
skypeforlinux:
  Installed: 8.47.0.59
  Candidate: 8.47.0.59
  Version table:
 *** 8.47.0.59 500
        500 https://repo.skype.com/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
     8.46.0.60 500
        500 https://repo.skype.com/deb stable/main amd64 Packages
     8.45.0.41 500
        500 https://repo.skype.com/deb stable/main amd64 Packages
     8.44.0.40 500
        500 https://repo.skype.com/deb stable/main amd64 Packages
     8.34.0.78 500
        500 https://repo.skype.com/deb stable/main amd64 Packages

**Issue/Bug Description:**
While I have the Skype Window Opened, and receive a message, GNOME Notifications shows me a "Skype is ready" notification, and after it's gone it displays the message content, I have tried setting the Show message content in Popups, rebooted, same issue persists, while if Skype is minimized to tray (skype window closed but running in background) and I receive a message, GNOME Notifications displays the Skype notification properly without the "Skype is ready notification" 
Screenshot: http://0x0.st/z2f2.png

**Steps to reproduce (if you know):**
Install Skype from the official skype repositories, run it, leave it open (don't send it to the tray by closing it) receive a message and see what happens

**Other Notes:**
This is not present in the LTS version

**Comment by samim23** [comment]
I have the same issue. On each message, the "Skype is ready" notification pops up > stays for 5s > then instantly a new notification pops up with the actually message content. It's rather annoying.

**Comment by mmstick** [comment]
This would be an issue to report to the Skype developers.

**Comment by kronikpillow** [comment]
I solved this by installing the gnome extension Notofication is ready remover ... seems that this is a GNOME thing
