### ISSUE TITLE
Nautilus closes immediately when opened by Peek

### ISSUE THREAD

**Issue by meatnordrink** [pop-os/pop#597]
**Distribution (run `cat /etc/os-release`):**
 
 Latest Pop OS, on 2-month old System76 Meerkat
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Nautilus, Peek Screen Recorder

**Issue/Bug Description:**

After making a screen recording with Peek, Nautilus opens to allow you to save the file, but immediately closes again before you can actually save it. 

**Steps to reproduce (if you know):**

1. Open Peek. 
2. Position it over what you want to record. (In this case, a browser page.)
3. Record. 
4. Stop recording. 
The Nautilus window will pop up, then immediately close again, without saving the file. 

**Expected behavior:**
The window to stay open long enough for you to save the file. 

**Other Notes:**

**Comment by brs17** [comment]
With what kind of file format are you seeing this issue happen? I am noticing that I do not have an issue with a file format such as .mp4 but peek does crash for me when trying to save a .gif

This issue looks to have been already posted upstream numerous times: https://github.com/phw/peek/issues?utf8=%E2%9C%93&q=is%3Aissue+gif+crash

**Comment by meatnordrink** [comment]
@brs17 , it looks like you're right; I am able to save as .mp4. 

Also, I looked through those upstream reports, and it looks like the issue may have been fixed: 

https://github.com/phw/peek/issues/476

However, updating doesn't seem to do it; you must have to uninstall and reinstall? 

.mp4 format works for me, so I haven't explored further.

**Comment by brs17** [comment]
The latest version I see in the repositories (at least for 19.04) is 1.3.1-5. Looking at the github page for Peek: https://github.com/phw/peek the PPA they recommend adding as well as their daily PPA does not seem to have anything more recent than 1.3.1-5 either. Building from source may be the way to go.
