### ISSUE TITLE
Text not rendering correctly after resume from suspend 

### ISSUE THREAD

**Issue by tkanik** [pop-os/pop#602]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Issue/Bug Description:**

Since 19.04, I've been experiencing frequent difficulties resuming from suspend, causing text not to be displayed at all, or wrong characters to be displayed. Please see the attached screenshots.

I don't know what part of the system this lies in. It seems to affect all gtk apps at least. Firefox and Chromium renders just fine when this happens, other than the titlebar.

**Steps to reproduce (if you know):**
Close the laptop lid to suspend OS, then open the lid and log-in. You will see that even on login page some letter on screen are change to rectangle. Same happen with texts on system dialogs windows.

**Expected behavior:**
Text displays as readable group of characters.

**Other Notes:**
I use following settings to have different scaling on different displays
gsettings set org.gnome.mutter experimental-features "['scale-monitor-framebuffer']"
but above-mentioned bug is happen also when I use laptop without displays.

**Comment by tkanik** [comment]
[bug.zip](https://github.com/pop-os/pop/files/3365091/bug.zip)

**Comment by dani763f** [comment]
+1 for same issue

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Comment by ArdusJax** [comment]
+1 This is also happening for me. Same steps as what is listed in the issue.

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Comment by matheus-roma** [comment]
+1 This also happening for me. Even with the 20.04 LTS

NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

**Comment by leviport** [comment]
This bug is being tracked here: https://github.com/pop-os/nvidia-graphics-drivers/issues/133

In summary, it's a long-standing and annoying bug related to Nvidia, but it's fairly easy to work around it by restarting Gnome Shell when it happens (alt+F2, `r`, enter).
