### ISSUE TITLE
whole Intel NUC system unresponsive when in Devices page under Settings app

### ISSUE THREAD

**Issue by jupiterbox** [pop-os/pop#604]
-- Pop!_OS 19.04
--  Fresh install with ISO file...   pop-os_19.04_amd64_intel_6.iso
-- System...  Intel NUC Kit NUC8i7BEH   (BIOS version:  0071)

-- Whole system becomes unresponsive except mouse cursor every time I arrive at Devices / Displays page under Settings app.  I have to turn off/on the NUC to keep the system running without touching Devices / Displays page.  I need modify some display settings (resolution, refresh rate, etc). After several recent updates, this issue persists.

**Comment by mmstick** [comment]
Sounds like a conflict with the hidpi-daemon. Try to `sudo apt remove hidpi-daemon` and then visit the Display panel.

**Comment by jupiterbox** [comment]
Solved!   This also solves my random issue when display goes black for 1 or 2 seconds right after full boot-up and then come up with unresponsive system except mouse cursor.   Thank you!
