### ISSUE TITLE
System stuck for minutes on shutdown

### ISSUE THREAD

**Issue by tsebastiani** [pop-os/pop#61]
When I shut down the laptop, the system get stuck in a range between 2 to 6 minutes waiting for network interfaces.

![img_6925](https://user-images.githubusercontent.com/15978528/32318000-12efbac0-bfb6-11e7-8714-a0e6b17dd5f8.jpg)
![img_6926](https://user-images.githubusercontent.com/15978528/32318006-16003cbc-bfb6-11e7-8a37-c1cefecddf11.jpg)
![img_6927](https://user-images.githubusercontent.com/15978528/32318011-1aee7ba8-bfb6-11e7-8f75-d1f62e8b41c2.jpg)

**Comment by WatchMkr** [comment]
This appears to be a systemd bug. Please report there: https://github.com/systemd/systemd/issues
