### ISSUE TITLE
20-nvidia.conf no longer being loaded from /etc/X11/xorg.conf.d after 430.34 driver update

### ISSUE THREAD

**Issue by takatakatakatak** [pop-os/pop#613]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Nvidia driver 430.34

**Issue/Bug Description:**
After recent update to 430.34, 20-nvidia.conf is no longer being loaded from /etc/X11/xorg.conf.d/
This is necessary to set coolbits "12" and allow manipulation of fan and power controls by external applications such as greenwithenvy and the nvidia-settings app.

**Steps to reproduce (if you know):**
Update from 418 to 430.34

**Expected behavior:**
Respect settings contained within 20-nvidia.conf

**Other Notes:**
Have attempted to create a new 20-nvidia.conf via running 
sudo  nvidia-xconfig --cool-bits=12
And renaming xorg.conf and moving to correct directory. Something has changed. Any help appreciated.

**Comment by PrzemekSkw** [comment]
Maybe that's the reason why my driver don't work after upgrade. I have to downgrade driver to work correctly.
