### ISSUE TITLE
Microsoft Pro IntelliMouse - Can't scroll

### ISSUE THREAD

**Issue by SomKen** [pop-os/pop#614]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Issue/Bug Description:**
Unable to scroll using Microsoft Pro IntelliMouse.

https://www.microsoft.com/en-us/p/microsoft-pro-intellimouse/8rs0hww7dhnk

**Steps to reproduce (if you know):**
1. Have mouse
2. Attempt to scroll.
3. Scrolling doesn't happen.  

This can also be seen if attempting to scroll in xev.

**Expected behavior:**
When scrolling, such as on a webpage, it should scroll.

**Other Notes:**
Center mouse button does work.  Reviewing https://www.reddit.com/r/linuxquestions/comments/bxa4bd/microsoft_pro_intellimouse_anyone_got_scrolling/, it appears that this does work on 16.04, but my Thinkpad T495 isn't fully supported so I can't use that.  In the linked reddit thread, I have attempted to edit my grub config to fix, but no help.

**Comment by SomKen** [comment]
Follow up:  I attmepted Pop 18.04 last night and the installer did not respond to mouse scrolling.

**Comment by SomKen** [comment]
Another update from me, when I boot into the installer for Ubuntu 18.04 I am able to scroll.

**Comment by mmstick** [comment]
We use the same libinput driver and kernel as Ubuntu, so there shouldn't be difference.

**Comment by SomKen** [comment]
@mmstick is there anything I can grab to help?

**Comment by SomKen** [comment]
Resolved in 19.10.  Closing.
