### ISSUE TITLE
GNOME Desktop Trash Icon not working, removing other icons

### ISSUE THREAD

**Issue by DToka** [pop-os/pop#619]
*Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

**Issue/Bug Description:**
In Gnome tweaks under Extensions, Desktop Icons when you click on the gear and then enable the personal folder in the desktop and then click to show the trash icon. On desktop now the personal folder is missing and there is no trash icon

**Steps to reproduce (if you know):**
-Fresh Install on Acer Swift 3(SF315-51G) with Nvidia drivers
-Update system
-Install Gnome Tweaks
-Enable trash icon in the desktop

**Expected behavior:**
-Keeps the personal folder icon and the shows the trash icon on the desktop

**Comment by KarkanAlzwayed** [comment]
I confirm that. First, I thought it was a bad install or something. Reinstalled fresh and it is still there.

**Comment by MrArca9** [comment]
Confirmed, installed the extension via https://extensions.gnome.org/extension/1465/desktop-icons/ which had it enabled by default. Googled and came across this, unchecked the trash icon and everything showed up. 

Running 19.04 latest updates, possibly an issue with the extension breaking in gnome 3.32.2 as it was designed for 3.30.0

**Comment by KarkanAlzwayed** [comment]
> Confirmed, installed the extension via https://extensions.gnome.org/extension/1465/desktop-icons/ which had it enabled by default. Googled and came across this, unchecked the trash icon and everything showed up.
> 
> Running 19.04 latest updates, possibly an issue with the extension breaking in gnome 3.32.2 as it was designed for 3.30.0

I don't think it is an issue with gnome (I could definitely be wrong). It is working just fine for me on Fedora 30 with gnome DE.

**Comment by svenoaks** [comment]
Is this a temporary fix for it? https://www.reddit.com/r/pop_os/comments/cj79t7/having_problems_with_your_desktop_icons/?utm_medium=android_app&utm_source=share

**Comment by juhani-korhonen** [comment]
Affects me as well. Running Pop!_OS 19.04 Disco Dingo, and gnome-shell 3.32.2. Just like @MrArca9 I installed the extension through https://extensions.gnome.org/extension/1465/desktop-icons/

**Comment by DToka** [comment]
Updated the gnome extensions through the browser and this issue has gone away as of March 14, 2019
