### ISSUE TITLE
Mistakenly uninstall system applications

### ISSUE THREAD

**Issue by CookieLau** [pop-os/pop#627]
My system version is Pop!Os 18.04 LTS

**Distribution (run `cat /etc/os-release`):**
 run 'sudo apt-get install aptitude'
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
When installing aptitude, it uninstalled my several system default applications (like pop!shop and system setting), how can i reinstall it back? 
I searched that problem in ubuntu and it can be solved with installing ubuntu-desktop, is there any command to deal with pop!os? 

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**
Looking forward to ur reply.
Thank you in advance.

**Comment by jackpot51** [comment]
In Pop!_OS you can run the following:

```
sudo apt-get install pop-desktop
```

**Comment by CookieLau** [comment]
Thank you sincerely!!!!!!!!!!!!!!!!!!!!!!!!!!!
I know ubuntu-desktop but donot realize it is the same case in pop!os
Looking forward to your wonderful development!
Pop!Os is awesome! I strongly recommend to all my friend! :)
