### ISSUE TITLE
Dash glitches out when 14 applications are open and you close one.

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#63]
_From @ahoneybun on November 2, 2017 20:21_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

Please only use this for reporting issues with _generating the ISO images for Pop!\_OS_. If your issue is a Pop!\_OS bug, please open your issue against the [pop-os/pop](https://github.com/pop-os/pop/issues/new) repository

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```
athoneycutt@pop-os:~/Downloads$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

**Issue/Bug Description**

The Dash on the left will freak out when you have 14 applications open and close one (13 is the bad number)

**Steps to reproduce (if you know)**

Open 14 applications and close one then watch the Dash flip out

**Expected behaviour**

Dash evens out and does not jump like it does.

**Other Notes**

_Copied from original issue: pop-os/iso#193_

**Comment by cassidyjames** [comment]
@ahoneybun I can't reproduce this. Can you still after applying the latest updates?

**Comment by isantop** [comment]
I just tried to reproduce this, and can confirm that it doesn't seem to happen anymore with either D-t-D or the standard dashboard. However, I did notice that going from 14 to 13 applications causes the icons to resize, and that might be what's causing the skip-jump referred to in the original report.

**Comment by ahoneybun** [comment]
I can't reproduce this with the latest updates either. It was from the resizing I believe.
