### ISSUE TITLE
How to re-install POP!_OS keeping previous home folder

### ISSUE THREAD

**Issue by ahbon123** [pop-os/pop#632]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Issue/Bug Description:**

I want to re-install POP!_OS and I want save a large amount of data in `home` folder of the previous system, but I don't know either how to browser into it, or how to re-install system while keeping previous `home` folder at same time? Someone could help? Thanks a lot.

**Comment by mmstick** [comment]
You can use the recovery partition's "Refresh OS" option. It will move all but the `/home` directory from the root partition, and then installs the new system around it. On success, it deletes the backed up install. On failure, it restores it.
