### ISSUE TITLE
Blender 2.8.0 update unavailable on the pop_shop

### ISSUE THREAD

**Issue by afro-madness-ke** [pop-os/pop#638]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**There is no blender 2.8.0 update for pop in pop shop just 2.7.9**

**Steps to reproduce (if you know):**

**Blender update available soon**

**Other Notes:**

**Comment by mmstick** [comment]
This is expected, because Pop!_OS is based on Ubuntu, which uses a point release model. Software is only updated to new versions in the next point release, which occurs every 6 months. The next point release is 19.10, and it's likely that Ubuntu will update the Blender package in the 19.10 release.
