### ISSUE TITLE
How do you add minimize button to the window?

### ISSUE THREAD

**Issue by wisdomlight** [pop-os/pop#64]
in other os - even linux there is a way to have three buttons at the top left or right of a window allowing you to close/minimize/or maximize

my pop_os seem to have only 'x' on the top right side of the windows. 

which settings do i need to use in order to add those other functions?

cheers

**Comment by brs17** [comment]
@wisdomlight Go ahead and install gnome-tweak-tool. Once you've done that, if you go to the "Windows" tab, you'll see a toggle to turn on minimize and maximize. (You can also choose which side of the window the buttons are on)

Hope this answers your question! If this doesn't feel free to reopen the issue and supply additional information.

**Comment by amyers88** [comment]
"duplicated functionality" is no excuse... this is actually an accessibility issue as well. that's like saying you should remove "double click" because you can single click and press enter...... come on.

**Comment by brs17** [comment]
@amyers88 removing the minimize button was a design choice made by GNOME developers for GNOME 3.x as it does not fit in well with the GNOME 3 workflow.

**Comment by radiantone** [comment]
That was a terrible design choice that breaks a long enduring and obvious function. Minimizing windows is probably the most commonly performed desktop function and now we have to jump through hoops to get it back. How else is one to keep their desktop uncluttered yet easily move between apps?

**Comment by darkoverlordofdata** [comment]
Now I remember why I don't like Gnome. What about My workflow? They apparently don't care - "I've heard it both ways. There's the right way and then your way..."

**Comment by mmstick** [comment]
Super + H is used to minimize a window. You can also right click a window and select the Minimize option. If you install Tweak Tool, you can enable the minimize button, but it's not the default behavior.

**Comment by darkoverlordofdata** [comment]
Superkey? What is that? I google and find the definition that I am familiar with, but it makes no sense in the context of your reply (https://en.wikipedia.org/wiki/Superkey). 

In any case, either using a keyboard shortcut while I am using a mouse, or remembering to right click when I am used to clicking is disruptive to the workflow that I've been using for 30 years. My point is that Gnome is starting to tell us what we want, not asking us what we want, and it does anger me. 

I started using Linux when Vista released. At that time was better than the Windows desktop environment. But comparing modern Gnome to Win10, I no longer believe that, and find myself back using Windows more & more.

**Comment by arthurbernierjr** [comment]
The super Key is the Key that has the windows logo on it if you are using a traditional windows keyboard from Dell or Acer or something like that.

**Comment by 1beb** [comment]
This is only based on my own experience. But as soon as you push Super (Windows Key on most keyboards), you get a spread of windows. If every window you are actually working on is maximized (double click on title bar) or pushed to either side (Ctrl + Super + Left/Right/Up/Down), then you never have to minimize when switching. I don't know if that's the intent but working that way has been really useful and the minimize key becomes redundant in all but edge case scenarios.

**Comment by kejodion** [comment]
For the love of god make maximize and minimize buttons standard with the distro. Expecting people to using keyboard shortcuts or install the tweak tool for such a fundamental thing is only going to turn people away.

**Comment by ahbon123** [comment]
I try to install `gnome-tweak-tool`

```
x@pop-os:~$ sudo apt install gnome-tweak-tool
[sudo] x password:
Reading list of packages... done
Analyzing the dependency tree of the package
Reading status information... done
There are some packages that cannot be installed. If you are using an unstable distribution, this might be
Because the system is unable to reach the state you requested. There may be some software you need in this release.
The packages have not been created or they have been moved out of the Incoming directory.
The following information may be helpful in resolving the issue:

The following packages have unmet dependencies:
  Gnome-tweak-tool : Dependency: gnome-shell-common (>= 3.4) But it won't be installed
E: I can't fix the error because you want some packages to stay current, that is, they break the dependencies between the packages.
```
But when I install gnome-shell-common, it indicates the  latest version has been installed, anyone know how to fix this? Thanks.

```
x@pop-os:~$ sudo apt install gnome-shell-common
Reading list of packages... done
Analyzing the dependency tree of the package
Reading status information... done
Gnome-shell-common is the latest version (3.28.4-0ubuntu18.04.2).
Gnome-shell-common has been set up for manual installation.
0 packages have been upgraded, 0 packages have been newly installed, 0 packages have been uninstalled, and 22 packages have not been upgraded.
```

**Comment by sprakashdash** [comment]
@ahbon123 Try uninstalling gnome-shell-common using `sudo apt remove` then try reinstalling gnome-tweak-tools.

**Comment by jim7fl** [comment]
> @bprashanth It's because it is duplicated functionality in GNOME. Super + H minimizes the active window, without the need for clicking a button. If you right click the title bar, "Minimize" is also the first action in the context menu that pops up.

This is all fine for folks who have "Super" or "Windows" keyboards, but what about those of us who still use the Northgate Omnikey 102 without any of those?  I see no need to introduce an additional right click before I can do what I have been doing for 30 years, which is simply click the minimize button or double click the title bar to maximize.

**Comment by leviport** [comment]
@jim7fl Awesome keyboard! If you don't use Caps Lock very much, you can remap it to Super with gnome-tweaks. You can perform more complex remappings with xmodmap, but that's a bit more work. In Gnome, and especially with pop-shell, you're missing out on a lot by not having a Super key.

**Comment by farazfazli** [comment]
Please have minimize and maximize buttons as standard. These are sane defaults for anyone coming from a non-Linux background, and give that PopOS is largely used as a first distro by many, I can see it positively impacting user adoption. It's little things like this that are much appreciated.

**Comment by deathxxx123** [comment]
> Please have minimize and maximize buttons as standard. These are sane defaults for anyone coming from a non-Linux background, and give that PopOS is largely used as a first distro by many, I can see it positively impacting user adoption. It's little things like this that are much appreciated.

This is why i do not want to use PopOS. Why the hell i need install something to get minimize and maximize buttons back?
For that: Ubuntu Budgie is a great choice!

**Comment by abevac** [comment]
I'm on 20.04 and it seems Super+H is actually the Vim shortcut for switching focus to the left window, not minimizing. In Settings > Keyboard Shortcuts however, you can set the "Hide window" shortcut (disabled by default) to Super+H, and confirm that you want to override the switch-to-left-window functionality. (And even though you can't see it in the settings, Super+←↓↑→ and Super+HJKL are BOTH mapped to the shift window focus shortcuts.)

The functionality is not duplicated since nobody is going to right click to minimize, so I agree with the others that this is a bad default, and the graphical minimize button should certainly be included without needing to install an additional "tweak".

**Comment by KaziBora** [comment]
Am no 20.04 and I have install the gnome-tweak-tool but I can't locate the windows settings to enable this

**Comment by mmstick** [comment]
![Screenshot from 2020-09-05 23-21-53](https://user-images.githubusercontent.com/4143535/92318797-99271c00-efce-11ea-9351-abf3bb78cae0.png)

**Comment by jroque3011** [comment]
I still can't find the "Windows" settings to enable the minimize option. Is it in "Settings"

**Comment by LimpingNinja** [comment]
Adding in here that even on the current version of 20.10 this is **not duplicated functionality** as SUPER+H is mapped to switching windows directionally (H being left). So the argument to close this does not make any sense whatsoever. I want bother reopening, but it is an odd usability choice.

**Comment by PhilParisot** [comment]
Just so it's known, I've slowly been converting friends and family to Linux, and I've been recommending Ubuntu over Pop_OS to them specifically for this reason.

I can't expect my parents and grand-parents to figure out shortcuts, they need the visible buttons. I'd also like to see this be added by default in the OS so that I can start recommending Pop to regular every day users.

**Comment by Zebirdman** [comment]
this is what happens when programmers make design decisions 'duplicated functionality' meh.....

**Comment by leviport** [comment]
Since this closed issue remains popular, I'd like to reiterate that this design decision came from Gnome, and we simply don't want to part with Gnome's well researched design decisions unless we have a very good reason to. If Gnome brings back minimize and maximize, then they will also be in Pop. Since we are leaving the decision up to them, further discussion would be more fruitful if it happened upstream.

**Comment by rdgh8** [comment]
So is there no way to minimize a window using the keyboard without overriding the default focus switching (Super + H)?

**Comment by leviport** [comment]
There's no need to overwrite `Super`+`H`. There are many key combinations that can be bound to window minimizing. I personally use `Super`+`,` but I also don't use QWERTY, so it might not be as comfortable for other users.

**Comment by JesusJimenezG** [comment]
To everyone that "Window" tab doesn't show you the option to add the buttons, just use the console:

- add the values at the left side of `:` for buttons on the left side

 `close,minimize,maximize:`

        gsettings set org.gnome.desktop.wm.preferences button-layout "close,minimize,maximize:"

 ![enter image description here][1]

- add the values at the right side of `:` for buttons on the right side

 `:minimize,maximize,close`

        gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"

 ![enter image description here][2]

- or mix them

 `close:minimize,maximize`

        gsettings set org.gnome.desktop.wm.preferences button-layout "close:minimize,maximize"

source: https://askubuntu.com/a/651349

**Comment by beetlejuice1005** [comment]
Manjaro Gnome 21.0.7 has got what people have been talking about in this post.
https://manjaro.org/downloads/official/gnome/
Has got tweaks preinstalled, got the minimise and maximise buttons activated.
Right click on the 9 dots and can click dock settings.  Can move the dock to different locations.
The dock stays on the screen when nothing is open, and only hides when a window goes over the top.
Can just over the mouse over where the dock is, and the dock appears automatically.
When using it on the live usb, a menu appears before it boots into manjaro.  There are 2 screen driver types to choose from. If one doesn't work, try the other one for the screen drivers. When I first loaded it on the usb, was wondering why I got a blank screen.
Note that the timeout lock is short.  Not sure how long.  If the screen does lock, the password to unlock is "manjaro", same as the user name.

**Comment by leviport** [comment]
@beetlejuice1005 Have you taken Pop!\_OS 21.04 for a spin yet?

Also, this isn't a good place to discuss other feature requests. The minimize button thing was settled long ago, and discussion about docks doesn't belong in this issue. Feel free to open a fresh one for a new feature request though.

**Comment by katzda** [comment]
I clicked the "Tile" icon and there is a settings to show "Titles". I turned it on and now I can finally minimize a window thanks God :-D.
