### ISSUE TITLE
Darter Pro wakes up from suspend immediately

### ISSUE THREAD

**Issue by ahoneybun** [pop-os/pop#646]
**Distribution (run `cat /etc/os-release`):**
 
 Pop 19.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

I'm unable to put my 2019 Darter Pro to sleep. Both using fn+F12 and closing the lid cause the suspend process to start, but as soon as it powers down it begins the process of waking back up.

These steps fix the issue as it seems tied to the USB 3 port:

$ head -n 3 /proc/acpi/wakeup
Device S-state Status Sysfs node
XHC S3 *enabled ...
XDCI S4 *disabled ...
HDAS S4 *disabled ...

$ sudo su

$ echo XHC > /proc/acpi/wakeup

$ head -n 3 /proc/acpi/wakeup
XHC S3 *disabled ...
XDCI S4 *disabled ...
HDAS S4 *disabled ...

**Steps to reproduce (if you know):**

Suspend the laptop with the current kernel and watch it come back from suspend right away

**Expected behavior:**

Laptop suspends and stays suspended. 

**Other Notes:**
https://system76.com/admin/support/view/39074

**Comment by leviport** [comment]
Issues for QA to investigate should be posted in the system76/testing repo. Closing this and moving it there.
