### ISSUE TITLE
All system updates fail with 18.10

### ISSUE THREAD

**Issue by KloudKoder** [pop-os/pop#651]
**Distribution (run `cat /etc/os-release`):**
 
18.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

All updates with all apps, including Pop!_OS itself.

**Issue/Bug Description:**

Can't update anything. This happens on every machine thus far tested. Reinstall of lots of machines is not fun, but maybe that's the only way out of this if the solution can't be manually implemented in some config file.

**Steps to reproduce (if you know):**

Pop!_Shop no longer works for updates. So if you try this: 

sudo apt-get update

you get:

The repository 'http://apt.pop-os.org/proprietary cosmic Release' no longer has a Release file. Updating from such a repository can't be done securely, and is therefore disabled by default.

**Expected behavior:**

Just do the update, over HTTPS.

**Other Notes:**

While we're at it, I've noticed that the update process on some Linux flavors have been using SHA1 way past its freshness date. I'm not sure if that's the case here, but FYI it's well deprecated. Ditto for MD5SUM. For that matter, I hope that an attacker would need to do a lot more than just change a hash to falsely authenticate his man-in-the-middle modifications to executables, before the receiving end would be willing to accept them. Likewise for the sake of convincing the update server to stay stuck on a vulnerable old version of a given binary, for the sake of leaving vulnerabilities unpatched, despite the appearance of updates having been done.

**Comment by brs17** [comment]
Pop!_OS 18.10 (and Ubuntu 18.10) reached end of life In mid-July and therefore is no longer supported and the repositories no longer receive updates. Non-LTS releases have 9 month release cycles and it is recommended to upgrade to the next version (19.04 currently) as soon after the release of 19.04 (release was in April of 2019) as possible. Installing Pop!_OS 19.04 (or 18.04) will solve your problem.
