### ISSUE TITLE
Manual changes to printers fail

### ISSUE THREAD

**Issue by thomas-zimmerman** [pop-os/pop#655]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
cups:
  Installed: 2.2.10-4ubuntu2.1
  Candidate: 2.2.10-4ubuntu2.1
  Version table:
 *** 2.2.10-4ubuntu2.1 500
        500 http://us.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu disco-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.2.10-4 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
**Issue/Bug Description:**
Unable to make manual changes to printers until you add lpadmin to your group membership.

**Steps to reproduce (if you know):**
Try and make any changes in https:/localhost:631 to a installed printer
Admin user and password do not work

**Expected behavior:**
sudo usermod -aG lpadmin USERNAME
Changes to printers works.

**Other Notes:**
I think the fix will be to change the default group membership done in user-setup to include "lpadmin"

**Comment by jacobgkau** [comment]
Admin users (including the default user) will now be added to `lpadmin` by default: https://github.com/pop-os/accountsservice/pull/2
