### ISSUE TITLE
System Freezes on Logout

### ISSUE THREAD

**Issue by iamjameswalters** [pop-os/pop#657]
**Distribution (run `cat /etc/os-release`):** Pop!_OS 18.04 LTS
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** GDM (?) 

**Issue/Bug Description:** When I logout from the User Menu (in the upper right corner of the shell panel), the screen goes black, and the computer becomes silent. The power light remains lit, and does not blink as if it were sleeping. The power button remains unresponsive, and the computer requires a hard reset.

**Steps to reproduce (if you know):** Click menu in upper right of shell. Click user name, click "Log out."

**Expected behavior:** Session logs out and returns to the login screen.

**Comment by jks15satoshi** [comment]
I got the similar issue with yours, but it happens when I attempt to re-login, instead of just log out.

**Comment by NightFuryG** [comment]
Have this exact same problem after clean install 19.10.

**Comment by jh0l** [comment]
yeah I still have this problem in 20.04LTS. Funny thing is logout from the ctrl+alt+del menu works completely fine. If what ever the system menu's logout procedure was replaced with the ctrl+alt+del menu's logout perhaps this issue would be fixed?

**Comment by iamjameswalters** [comment]
It's been three and a half years since I opened this, I don't think it's relevant anymore.
