### ISSUE TITLE
Can't play Youtube Videos 

### ISSUE THREAD

**Issue by caiodelgadonew** [pop-os/pop#658]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
google-chrome-stable:
  Installed: 77.0.3865.75-1
  Candidate: 77.0.3865.75-1
  Version table:
 *** 77.0.3865.75-1 500
        500 http://apt.pop-os.org/proprietary disco/main amd64 Packages
        500 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status

firefox:
  Installed: 69.0+build2-0ubuntu0.19.04.1
  Candidate: 69.0+build2-0ubuntu0.19.04.1
  Version table:
 *** 69.0+build2-0ubuntu0.19.04.1 500
        500 http://us.archive.ubuntu.com/ubuntu disco-security/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
        100 /var/lib/dpkg/status
     66.0.3+build1-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages

**Issue/Bug Description:**

Youtube videos keep loading and doesn't playback.

**Steps to reproduce (if you know):**

Fresh install of PopOS! 19.04.

**Expected behavior:**

Playback with no problems.

**Other Notes:**

Tested with three different notebooks:
* Acer Aspire A515-51G
* Acer Aspire Nitro 5
* Dell Inspiron G3 3579

**Comment by caiodelgadonew** [comment]
When an application like Virtualbox takes control over the Sound Card, youtube cant play anything.

**Comment by spencer1573** [comment]
I had sony bluetooth headphones connected and an aux hooked up to my darp5. the second i disconnected the bluetooth ... then the song began playing (from the start). before the song on youtube music was just spinning and not even playing... it was messing with the google chrome certs i think.
