### ISSUE TITLE
Screen Touch Always Activates Soft Keyboard

### ISSUE THREAD

**Issue by MisterRager** [pop-os/pop#66]
**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)
```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

 * Related Application and/or Package Version - apt policy $PACKAGE NAME
I'm not sure - sorry

Also, this is on my HP Spectre x360 15t (late 2017).

```

**Issue/Bug Description**

Touching the screen invokes the on-screen soft keyboard every time I touch the screen, whether or not there is a focused text box. On top of that, it'd be nice to have some way to change or disable the soft keyboard.

**Steps to reproduce (if you know)**

On a computer that has a touch screen, touch the screen.

**Expected behaviour**

Soft keyboard only comes up when a text field is explicitly focused.

**Other Notes**

What is the software that actually handles this? Is it a gnome component I can configure?

**Comment by cassidyjames** [comment]
Thanks for the issue report, @MisterRager! This sounds like it might be an upstream Ubuntu or GNOME Shell issue, as I don't believe we've changed anything that relates to touch or the soft keyboard.

@sarahpandabeara we should probably have QA test on a Sable Touch and/or Darter UltraTouch to see if we can reproduce on Pop!_OS, and then test if we can reproduce on Ubuntu.

**Comment by WatchMkr** [comment]
I've seen this behavior on a touch screen laptop. Please file a bug with GNOME upstream if one doesn't already exist.

https://bugzilla.gnome.org/

**Comment by MisterRager** [comment]
To leave a recorded solution, here's what I ended up using:
https://extensions.gnome.org/extension/1326/block-caribou/
