### ISSUE TITLE
Unlock disc cryptdata failure

### ISSUE THREAD

**Issue by poruchik-bi** [pop-os/pop#664]
**Distribution:**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-control-center:
  Installed: 1:3.28.2-0ubuntu0.18.04.5~1558109272~18.04~56507d7
  Candidate: 1:3.28.2-0ubuntu0.18.04.5pop1~1565997431~18.04~7b797dc
  Version table:
     1:3.28.2-0ubuntu0.18.04.5pop1~1565997431~18.04~7b797dc 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu bionic/main amd64 Packages
     1:3.28.2-0ubuntu0.18.04.5 500
        500 http://us.archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
 *** 1:3.28.2-0ubuntu0.18.04.5~1558109272~18.04~56507d7 100
        100 /var/lib/dpkg/status
     1:3.28.1-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 Packages

**Issue/Bug Description:**
Pop OS was installed with disc data encription.
After suspend I often can't open system setting window / wired settings window/ wi-fi settings window. This generally happen when I connect\disconnect second monitor after suspend.

I tried make an upgrade and reinstall gnome-control-center. After reboot I had no access to my disc because of encryption key verification  failure. I had to reinstall OS and lost all my data.

**Steps to reproduce (if you know):**
sudo apt update
sudo apt upgrade
sudo apt remove --purge gnome-control-center
sudo apt autoremove
sudo apt install gnome-control-center

**Expected behavior:**
master password that I set up on Pop OS for data encryption do not working any more and I can't load OS.  

**Other Notes:**
If exclude commands 
sudo apt update
sudo apt upgrade
from this procedure everything working fine after  gnome-control-center re-installation. Encryption disc access do not failure.

**Comment by mmstick** [comment]
GNOME Control Center is installed by default, so it sounds like you removed the `pop-desktop`, which may have removed disk encryption support with it.
