### ISSUE TITLE
19.10: Gnome Calendar often fails to launch

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#668]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-calendar

**Issue/Bug Description:**
About half of the time, gnome-calendar fails to launch when being executed from the Activities menu. The error I see (repeated multiple times) is: `gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

**Comment by mmstick** [comment]
It's possibly related to https://gitlab.gnome.org/GNOME/gnome-calendar/issues/439

The issue being this particular segfault:

```
gnome-calendar[8014]: segfault at 4 ip 00007f31d3ad2c7d sp 00007ffe0f28b4a0 error 4 in libglib-2.0.so.0.6200.0[7f31d3a7f000+83000]
```

We should file an issue on Launchpad

**Comment by mmstick** [comment]
Reported bug at https://bugs.launchpad.net/ubuntu/+source/gnome-calendar/+bug/1846541

**Comment by mmstick** [comment]
I think this has been fixed. I'm not able to replicate it anymore.
