### ISSUE TITLE
Activities search results are transparent

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#673]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10 debug iso 2
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
[installed_packages.log](https://github.com/pop-os/pop/files/3672551/installed_packages.log)

**Issue/Bug Description:**
When searching for a program/setting/file in the Activities menu, the search results are completely transparent. The only way I was able to tell that the search was actually happening is by pressing <kbd>Enter</kbd> and seeing the application launch.

This is not an issue on a fresh install using debug iso 2, but only happens after running updates. The packages updated are listed above under `Releated Application`. At the time of this issue being created, the new pop-gtk-theme is not released for eoan so this is not related to the theme.

**Comment by mmstick** [comment]
Does this also occur in current ISOs of Ubuntu 19.10? We're using the upstream packaging of GNOME Shell in 19.10 now.

**Comment by brs17** [comment]
> Does this also occur in current ISOs of Ubuntu 19.10? We're using the upstream packaging of GNOME Shell in 19.10 now.

It does not.

**Comment by mmstick** [comment]
I wonder which package is causing this behavior. We could try installing the Pop shell theme on Ubuntu to see if that introduces the issue.

**Comment by brs17** [comment]
Issue has been resolved.
