### ISSUE TITLE
Chrome window flickering

### ISSUE THREAD

**Issue by jliles** [pop-os/pop#68]
**Reporter info**

```
 * Distribution - Pop!_OS 17.10 (Artful Aardvark)
 * Related Application and/or Package Version - google-chrome-stable 62.0.3202.89-1, nvidia-384 384.90-0ubuntu3

```

**Issue/Bug Description**
Rectangular portions of the maximized Chrome window seem to flicker with the contents of different areas of other screens while window focus is away from the Chrome window.

**Steps to reproduce (if you know)**
* Use NVIDIA
* Add two external monitors to the system
* open Chrome and maximize the window on one external monitor.
* Open Tilix or another application in the other external monitor and maximize the window.
* Work as normal in the other application

The issue is very inconsistent and not reliably reproduced even using these steps.

**Expected behaviour**
Portions of the Chrome window shouldn't flicker

**Other Notes**
This occurs when no video or other 'graphics' application is running.  Firefox, Google Chrome, Atom, Slack, Mattermost, VirtualBox, PyCharm, Nautilus, and Tilix are the only windows open when the issue occurs for me.

**Comment by jliles** [comment]
This issue occurred on a Bonobo with SLI video cards.  Back on my Oryx with a single GPU, I have not seen the issue recur.  This could be SLI-related.

**Comment by dgoerlich** [comment]
I've encountered a similar issue.  I'm running on a Galago Pro, driving a single external monitor via HDMI.  If I maximize a Chrome window on the built-in display I'll get the flicker.  Also the native Slack app does the same, though it's effectively just a wrapper around a Chrome-based web view anyway.  I've noticed this issue more after I converted to a 34" ultra-wide external monitor (3440x1440)

**Comment by jliles** [comment]
![image](https://user-images.githubusercontent.com/2293367/33087497-c7788894-ceb8-11e7-8309-4deb325deea8.png)

I finally managed to capture a screenshot of this while it was happening, the chrome window in the foreground is actually maximized, and the bottom and right sides are flickering in and out revealing the Tilix window behind it.  Focusing another application made it remain in this condition.  If I focus the chrome window again, it appears normally.

**Comment by jliles** [comment]
This appears to be resolved using nvidia-387; at least since updating, it hasn't occurred again.

**Comment by WatchMkr** [comment]
That's great. Please re-open if the problem reemerges.
