### ISSUE TITLE
Kernel Upgrade Causes Kernel Options to Disappear

### ISSUE THREAD

**Issue by JWhitleyAStuff** [pop-os/pop#680]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os
```
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
EFI Bootloader

**Issue/Bug Description:**
If kernel options are added to `/boot/efi/loader/entries/Pop_OS-current.conf` and a kernel update is performed, those options disappear and are also not available in `/boot/efi/loader/entries/Pop_OS-oldkern.conf`.

**Steps to reproduce (if you know):**
I have to use software-based IOMMU controller so this is my particular issue:
1. As root, enter `/boot/efi/loader/entries` and edit `Pop_OS-current.conf`.
2. Add the kernel option `iommu=soft` at the end of the line beginning with `options`.
3. Update the kernel.
4. Reboot.

**Expected behavior:**
The kernel options applied will be maintained either in `Pop_OS-current.conf` or `Pop_OS-oldkern.conf`.

**Comment by mmstick** [comment]
This is expected behavior, because the boot loader entries are automatically generated by kernelstub. If you want boot options to persist, you need to define them with kernelstub, like so:

```
# Add a new option
sudo kernelstub -a iommu=soft

# Remove an option
sudo kernelstub -d iommu=soft
```

**Comment by JWhitleyAStuff** [comment]
Thank you! I had been looking for this solution for a while but couldn't find it.
