### ISSUE TITLE
19.10: Appearance>Background menu scales strangely on HiDPI screens

### ISSUE THREAD

**Issue by leviport** [pop-os/pop#684]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
gnome-control-center:
  Installed: 1:3.34.0.1-1ubuntu2pop1~1570212276~19.10~4861d64
  Candidate: 1:3.34.0.1-1ubuntu2pop1~1570212276~19.10~4861d64
  Version table:
 *** 1:3.34.0.1-1ubuntu2pop1~1570212276~19.10~4861d64 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.34.0.1-1ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
```

**Issue/Bug Description:**
The wallpaper chooser seems to scale strangely on my 4K Oryx display. I did not see this on 1080p displays. HiDPI daemon is turned off and my scaling is set to 200%. 

![Screenshot from 2019-10-07 10-05-45](https://user-images.githubusercontent.com/13512097/66328848-ac2afb00-e8ea-11e9-86c7-d4b43d5e067b.png)
![Screenshot from 2019-10-07 09-33-20](https://user-images.githubusercontent.com/13512097/66328855-adf4be80-e8ea-11e9-93b6-02fb8d679ff3.png)

**Comment by mmstick** [comment]
Seems the GtkImage widgets are abnormally large at 100%.

**Comment by mmstick** [comment]
Upstream issue: https://gitlab.gnome.org/GNOME/gnome-control-center/issues/704

**Comment by brs17** [comment]
Sounds like they are kinda stuck at coming up with a solution :cry:
