### ISSUE TITLE
"Record your encryption passphrase" not launching after initial setup

### ISSUE THREAD

**Issue by ross-miller** [pop-os/pop#69]
**Reporter info**

Ross Miller - ross.leonmiller@gmail.com

```
 * Distribution - (run ```cat /etc/os-release```)

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - apt policy $PACKAGE NAME

-  apt policy ecryptfs-utils
ecryptfs-utils:
  Installed: 111-0ubuntu5
  Candidate: 111-0ubuntu5
  Version table:
 *** 111-0ubuntu5 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status

- apt policy cryptsetup
cryptsetup:
  Installed: 2:1.7.3-4ubuntu1
  Candidate: 2:1.7.3-4ubuntu1
  Version table:
 *** 2:1.7.3-4ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu artful/main amd64 Packages
        100 /var/lib/dpkg/status

- apt policy xubuntu-desktop
xubuntu-desktop:
  Installed: 2.218
  Candidate: 2.218
  Version table:
 *** 2.218 500
        500 http://us.archive.ubuntu.com/ubuntu artful/universe amd64 Packages
        100 /var/lib/dpkg/status

```
**Issue/Bug Description**

I've installed Pop!_OS a few times now (on a galago pro galp2 and on my recently built pc) and each time I was never greeted with the "Record encryption passphrase" prompt window after everything was set up, even on the second boot. I installed Pop!_OS on my new pc after trying Ubuntu 17.10 again on it. I forewent full disk encryption, and I added xubuntu-desktop because I use it for chrome remote desktop sessions. 

I installed xubuntu-desktop first without installing google chrome or chrome remote desktop. I logged out of the pop session and almost immediately after logging into the xubuntu session, I was greeted by the "Record encryption passphrase" prompt. I haven't repeated it yet because I have everything working so I'll let others reproduce it for now.

**Steps to reproduce (if you know)**

Install Pop!_OS, don't set up full disk encryption (you can if you want to test that), but select home folder encryption and  go through the initial set-up of your user after the reboot. Update Pop!_OS after you've started a normal pop session, then install xubuntu-desktop. Log out of the pop session and log into a xubuntu session. You should be greeted by the prompt after a few seconds. 

**Expected behaviour**

Be greeted by the prompt once the user has been created and initialized, i.e. upon first user session similar to the first user session in Ubuntu after first system reboot after installation and user creation.  

**Other Notes**

This is the prompt as seen in Ubuntu 16.04/17.04 with unity. I expect the same prompt with the pop-theme. I didn't take a picture of the prompt because I was so glad to have it come up.

![general-ubuntu-prompt-home-encryption](https://user-images.githubusercontent.com/26983278/32696537-d6f3ced6-c72f-11e7-9466-502e70670d56.png)

**Comment by ross-miller** [comment]
I just installed xubuntu-desktop on my galp2 which has had Pop!_OS on it for a few weeks. I logged out, but it didn't show an xubuntu session option. I logged back into my pop (xorg) session and it brought up the prompt as well as told me not all of my changes would go through without restarting my laptop. I was given an xubuntu session option after restarting my laptop.

**Comment by WatchMkr** [comment]
This behavior is expected. The user password is used and it's not required to prompt for it. Something the xubuntu-desktop package pulls in must be launching this prompt.

**Comment by ross-miller** [comment]
You're saying the user password is the home folder encryption password? Seems more "user friendly", but is it inherently insecure.... I guess you're assuming people wouldn't use best practices with regard to passwords?
