### ISSUE TITLE
19.10: Nvidia driver stops working after installing updates 

### ISSUE THREAD

**Issue by leviport** [pop-os/pop#690]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
nvidia-driver-435:
  Installed: 435.21-1pop1~1567200870~19.10~c01044a
  Candidate: 435.21-1pop1~1567200870~19.10~c01044a
  Version table:
 *** 435.21-1pop1~1567200870~19.10~c01044a 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     435.21-0ubuntu2 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/restricted amd64 Packages
```

**Issue/Bug Description:**
After installing system updates, some DKMS stuff gets rebuilt. After a reboot, my external monitor cannot be enabled and `nvidia-smi` reports that the nvidia driver is not running. In my logs during the reboot, I see these messages:
```
Oct 14 07:35:56 pop-os nvidia-settings-autostart.desktop[2905]: ERROR: NVIDIA driver is not loaded
Oct 14 07:35:56 pop-os nvidia-settings-autostart.desktop[2905]: ERROR: Unable to load info from any available system
```

**Steps to reproduce (if you know):**
Not sure exactly, but I saw it happen twice when installing system updates which included DKMS stuff and required a reboot.

**Expected behavior:**

**Other Notes:**
I solved it both times with 
`sudo apt purge *nvidia* && sudo apt install system76-driver-nvidia`

I collected and saved logs which I can share if they are useful.

**Comment by mmstick** [comment]
So, `update-initramfs -c -k all` didn't fix it? Knowing which packages were updated might be useful.

**Comment by leviport** [comment]
I didn't try `update-initramfs -c -k all`, but I will if I see it happen again. I'll also have a look through my logs to see if I can find the packages that updated.

**Comment by mmstick** [comment]
If it happens again, we could try reinstalling the `nvidia-dkms-435` package.

**Comment by leviport** [comment]
I've not seen this since. Will reopen if I notice it again.
