### ISSUE TITLE
19.10: Chromium has no desktop file

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#692]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
chromium-browser

**Issue/Bug Description:**
After installing Chromium from the Pop!_Shop (it is listed as a Pop!_Pick), there is no desktop file from which to launch Chromium. It appears the only way to launch it is by selecting "Open" in the Pop!_Shop or from the command line with `snap`.

**Comment by jackpot51** [comment]
Does the chromium package in proposed have the same problem?
