### ISSUE TITLE
Laptop uses 4 times more energy after resuming after closing the lid.

### ISSUE THREAD

**Issue by FelixKimmerle** [pop-os/pop#697]
English is not my first language so i'm sorry for mistakes.

**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"                                      
PRIVACY_POLICY_URL="https://system76.com/privacy"                                          
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
I use powertop to get the current battery discharge rate in Watts.

powertop:
  Installed: 2.9-0ubuntu2
  Candidate: 2.9-0ubuntu2
  Version table:
 *** 2.9-0ubuntu2 500
        500 http://mirror.23media.com/ubuntu disco/main amd64 Packages                     
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
If I'm on the integrated GPU the laptop has a discharge rate of around 5W but if I close my laptop lid and open it again it has a discharge rate of around 20W. After a reboot its back to 5W.
If im on the Nvidia GPU the discharge rate does not change after closing and opening the lid (around 10W).

I tried it many times and it does always happens. 

**Steps to reproduce (if you know):**
- Close all Applications
- Start powertop and note the discharge rate.
- Close the laptop lid
- Wait for 1 minute
- Open the lid
- Wait until powertop refreshes for a few times and note the discharge rate 

**Expected behavior:**
I expect that the discharge rate is the same before and after

**Other Notes:**
I'm sure that the discharge rate that powertop is reporting is correct because the battery drains 4 times faster after closing and opening the lid than usual.
I use an IdeaPad l340 Gaming
All tests are done without the AC plugged in and in a range of 30% to 90% so its not dependent on the current charge.
It's happening on a completely new installation of pop os.

`uname -a`:
Linux pop-os 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

If you need more information I'm happy to give them to you.

I hope this is somehow possible to fix. If pop os is not responsible im happy to post it again on the right Forum.

**Comment by FelixKimmerle** [comment]
I tried it on a laptop without a dedicated GPU and it did not happen. Maybe this information can help.

It was a ThinkPad T520 (i5 2520m)

NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os

uname -a:
Linux pop-os 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by FelixKimmerle** [comment]
The built in app called: "Power statistics" reports the same as powertop.

**Comment by retromuz** [comment]
@FelixKimmerle did you try booting into old kernel and see if problem persists?
You can do this by keeping SPACE depressed while booting. Then a menu will appear to select latest or oldkern.

Cheers!

**Comment by FelixKimmerle** [comment]
I can't boot into the old kernel and have a graphical user interface. I always end up in root console. with the message that im in emergency mode. I cant start the graphical user interface with startx.

**Comment by FelixKimmerle** [comment]
`dpkg --list | grep linux-image`:
rc  linux-image-5.0.0-21-generic                     5.0.0-21.22+system76                                             amd64        Signed kernel image generic                               
ii  linux-image-5.0.0-31-generic                     5.0.0-31.33                                                      amd64        Signed kernel image generic                               
ii  linux-image-5.0.0-32-generic                     5.0.0-32.34                                                      amd64        Signed kernel image generic                               
ii  linux-image-generic

**Comment by FelixKimmerle** [comment]
I tried it today with the new version 19.10 and the problem still exists.

**Comment by mmstick** [comment]
Create a new issue if this still occurs on 20.04
