### ISSUE TITLE
failed to upgrade OS to 19.10 (exit code 100)

### ISSUE THREAD

**Issue by currymj** [pop-os/pop#699]
**Distribution (run `cat /etc/os-release`):**
 ```
NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Trying to upgrade using `pop-upgrade` results in the following error:

```
Event: updating package lists for the current release
Event: fetching updated packages for the current release
Event: upgrading packages for the current release
Release upgrade status: release upgrade aborted: status for `apt-get install -f` failed: command failed with exit status: exit code: 100
pop-upgrade: dbus client error: calling ReleaseUpgradeFinalize method failed
```

A similar error message appears when using the GUI option in the Settings menu.

**Steps to reproduce (if you know):**

**Expected behavior:**

Sucessful upgrade to the wonderful new 19.10 release!

**Other Notes:**

**Comment by mmstick** [comment]
You must have installed the pre-release version of `pop-upgrade`. Upgrade the system and then restart the `pop-upgrade` service to use the release version.

**Comment by uvinduperera** [comment]
This may cause if you haven't installed pop-desktop
Try installing

    sudo apt install pop-desktop
