### ISSUE TITLE
No headphone sound.

### ISSUE THREAD

**Issue by isantop** [pop-os/pop#7]
_From @ryanpcmcquen on October 21, 2017 16:11_

If this is a bug, please use the template below. If this is a feature request, question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description**

No headphone sound. Sound works out of internal speakers.

**Steps to reproduce (if you know)**

Install Pop!_OS.

**Expected behaviour**

There would be sound out of the headphones.

**Other Notes**

Let me know what other diagnostic data would be helpful. I would _love_ to get this working. Pop!_OS is amazing!

_Copied from original issue: pop-os/iso#180_

**Comment by isantop** [comment]
_From @jackpot51 on October 21, 2017 16:19_

What machine are you running Pop!_OS on?

**Comment by isantop** [comment]
_From @ryanpcmcquen on October 21, 2017 16:25_

A Sager NP7338.

**Comment by isantop** [comment]
_From @jackpot51 on October 21, 2017 17:22_

Is there a line out jack you can try?

**Comment by isantop** [comment]
_From @ryanpcmcquen on October 21, 2017 17:23_

No, the only audio ports are headphone and microphone (both 3.5mm).

**Comment by isantop** [comment]
_From @vincenttaglia on October 21, 2017 17:39_

I'm having the same issue on my Kudu Pro with the headphone port, except the built in speakers and the built in microphone both do not work as well. I also installed the System76 drivers and restarted but that didn't help.

This is what my dashboard looks like for sound:

![broken_sound](https://user-images.githubusercontent.com/15239196/31854400-f4c99de2-b65d-11e7-90b0-e3a679d328a2.png)

and in the actual settings there are no input or output devices.

**Comment by isantop** [comment]
_From @ryanpcmcquen on October 21, 2017 19:8_

I've tried everything here:

http://support.system76.com/articles/audio/

```
$ lspci -v | grep -A6 Audio
00:03.0 Audio device: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller (rev 06)
	Subsystem: CLEVO/KAPOK Computer Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at f7a14000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel

--
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
	Subsystem: CLEVO/KAPOK Computer 8 Series/C220 Series Chipset High Definition Audio Controller
	Flags: bus master, fast devsel, latency 0, IRQ 33
	Memory at f7a10000 (64-bit, non-prefetchable) [size=16K]
	Capabilities: <access denied>
	Kernel driver in use: snd_hda_intel
	Kernel modules: snd_hda_intel
```
```
$ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA Intel HDMI], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 8: HDMI 2 [HDMI 2]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: HDMI [HDA Intel HDMI], device 10: HDMI 4 [HDMI 4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 0: VT1802 Analog [VT1802 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: PCH [HDA Intel PCH], device 2: VT1802 Alt Analog [VT1802 Alt Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
I also have the `system76-driver` installed (sound did not work before it). I think my system is similar to some older System76 laptops even though it is not a System76 machine.

**Comment by isantop** [comment]
_From @vincenttaglia on October 22, 2017 1:13_

I just installed pulse audio, deleted the config files from pulse, and that ended up fixing the problem somehow. I did have pulse audio config files there from a restored backup, so that may or may not have something to do with it.

Also, ryanpcmcquen, I don't think you are supposed to install system76 drivers unless you have a system76 machine, but I may be wrong.

**Comment by isantop** [comment]
_From @ryanpcmcquen on October 22, 2017 1:21_

@vincenttaglia I'm pretty sure my machine is close to one of the older System76 machines.

**Comment by isantop** [comment]
@ryanpcmcquen Unless it's actually a System76-Branded computer, the Driver will not work on it, and it's designed not to. All System76 computers have certain BIOS modifications to implement things in more linux-friendly ways. The driver expects this, but that may cause issues even with systems similar to System76 machines.

**Comment by isantop** [comment]
_From @ryanpcmcquen on October 23, 2017 16:17_

@isantop, noted. It still had no headphone sound without the driver though.

**Comment by isantop** [comment]
Closing for now. Feel free to reopen if this continues to be an issue.

**Comment by ryanpcmcquen** [comment]
Why is this being closed? This is 100% still an issue ...

**Comment by ryanpcmcquen** [comment]
See: https://github.com/pop-os/pop/issues/7#issuecomment-340803382

**Comment by jackpot51** [comment]
Sorry, we will keep this open @ryanpcmcquen

**Comment by ryanpcmcquen** [comment]
Thank you @jackpot51.

**Comment by WatchMkr** [comment]
We won't be able to fix this one. If audio isn't working on system76 hardware please contact support. If it's not working on other hardware, please file a bug against the alsa project: http://alsa-project.org/main/index.php/Bug_Tracking

**Comment by ryanpcmcquen** [comment]
It is a config issue. Adding this:

https://github.com/ryanpcmcquen/linuxTweaks/blob/master/alsa-base.conf

To `/etc/modprobe.d/`, and doing a full shut down/power cycle fixes it.

**Comment by WatchMkr** [comment]
Using a quirk in alsa-base.conf means the hardware isn't recognized correctly.

**Comment by WatchMkr** [comment]
Yes, probably in the Realtek driver.

**Comment by BHunter2889** [comment]
@WatchMkr Did this ever get fully resolved or are we still to rely on the alsa config? Is there a driver repository somewhere?

**Comment by faedy2** [comment]
I am also having an issue with my headphones not playing audio
I'm on 20.10

**Comment by stragos13** [comment]
i was trying all the different things in the internet and no one did the trick.
The solution for me was  manually change the output audio from audio setting, it appear like "not connected" but i just clicked and the it work

**Comment by gabriel-fsantos** [comment]
I had the same problem, I managed to solve it by deleting the PulseAudio settings.

**Comment by gabriel-fsantos** [comment]
I had the same problem, I managed to solve it by deleting the PulseAudio settings.

**Comment by gabriel-fsantos** [comment]
I had the same problem, I managed to solve it by deleting the PulseAudio settings. 

`systemctl --user restart pulseaudio`
`rm -r ~/.config/pulse`
`pulseaudio -k`

https://support.system76.com/articles/audio/

**Comment by PascalMasny** [comment]
I had the same Bug. Worked Like a charm. :) Thank you.
my System: ```Pop!_OS 21.04```
