### ISSUE TITLE
Apply button not working in 19.10 (network settings)

### ISSUE THREAD

**Issue by evil-arri** [pop-os/pop#704]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 19.10
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
Apply button not working when trying to change network settings, whatever setting I try to change, apply button is grey and cannot be clicked.

![set](https://user-images.githubusercontent.com/56842169/67230203-360eb400-f413-11e9-941a-9c6594c6523b.jpeg)

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
The fix will be published to our repos soon.
