### ISSUE TITLE
Unable to give Static IP on ethernet connection

### ISSUE THREAD

**Issue by RenouxMarais** [pop-os/pop#707]
Hi guys.

Not sure if this has been an issue before but when trying to apply a static IP through the GUI.

I can edit the details but then the 'Apply' button stays greyed out.

P.S I have not tried using Terminal to configure but I'm sure I'll be able to change like that.

Does anyone have an answer to this? I use this feature quite frequently when on-site at new clients.

Google obviously has no answers. (That worked in my case)

**Comment by 1r0n-ZA** [comment]
Hi Guys.

I have the same problem at the moment.

IP addr works in terminal though.

**Comment by brs17** [comment]
This issue will be fixed with this: https://github.com/pop-os/gnome-control-center/pull/62 which will be released shortly.
