### ISSUE TITLE
Cannot power off/restart laptop using menu on login screen after boot

### ISSUE THREAD

**Issue by ChaotiX66** [pop-os/pop#708]
**Distribution (run `cat /etc/os-release`):**
cat /etc/issue generates:
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

I am  running:
Pop!_OS 19.10, with Linux Kernel 5.3.0-19-generic
on a ThinkPad X1 Extreme (gen 1) with 32 GB RAM, 1TB SSD, Intel i7-8750H with Nvidia GTX 1050 Ti Max-Q.
Installation is a fresh default install of the Pop!_OS 19.10 ISO installed on a wiped SSD. I am dual-booting Windows 19.03 as a secondary OS on a secondary internal 1TB SSD.
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Laptop doesn't power off nor restart through the menu in the top-right corner of the login screen after booting. The Power off/restart dialogue _does_ show up but clicking either Power-off or Restart leads to nothing. I tried waiting a couple of minutes but the dialogue won't disappear and laptop remains powered- on. If I login first, then try the menu in the top-right corner, everything works fine. Shutting down or restarting doesn't help and I have nothing installed except for Steam (with CS:GO) and InkScape.

**Steps to reproduce (if you know):**
1. Boot up computer
2. Decrypt disk by inputting password
3. Click on top-right drop-down menu
4. Choose Power-off or Restart

**Expected behavior:**
Laptop powers off/restarts

**Other Notes:**
This worked on Pop!_OS 19.04 without issues.

**Comment by brs17** [comment]
I can confirm this is a regression with GNOME 3.34. I plan to file an issue upstream soon and link it here.

**Comment by brs17** [comment]
Filed the issue here: https://gitlab.gnome.org/GNOME/gdm/issues/528

**Comment by brs17** [comment]
Looks to be an authentication issue per logs I found in journald. :thinking:

**Comment by jamespotz** [comment]
I can confirm. This also happens on my end restart and shutdown does not work on GDM

**Comment by brs17** [comment]
This issue has been resolved upstream: https://github.com/systemd/systemd/commit/a2dcb1d78737d3daa301ee63fbdd02837acb71a8. As noted here: https://gitlab.gnome.org/GNOME/gdm/issues/528 the issue has reached Ubuntu 19.10 and is being released to Pop!_OS 19.10 today.
