### ISSUE TITLE
Intel WiFi module update broke reliability and I can't connect to my home network anymore

### ISSUE THREAD

**Issue by MaCroX95** [pop-os/pop#709]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not entirely sure, it was dkms module that got upgraded upon doing apt upgrade...

**Issue/Bug Description:**
After today's update of Intel's Wifi driver I cannot connect to my home wifi network anymore and connecting on other networks is extremely unreliable.

**Steps to reproduce (if you know):**
100% of the time for my home network, and let's say 50% of time for my mobile hotspot.

**Expected behavior:**
Wifi connects as it was before the update, without issues

**Other Notes:**
Maybe revert the update so more users aren't affected by this?

**Comment by mmstick** [comment]
The package is from Canonical's HWE team. It wasn't installing before, so it sounds like you don't need. You're free to uninstall that package. It's not required.

**Comment by MaCroX95** [comment]
> The package is from Canonical's HWE team. It wasn't installing before, so it sounds like you don't need it. You're free to uninstall that package. It's not required.

Remove it? As far as I've understood the apt, it just got updated? how do I remove it if you can please tell me? :)

**Comment by mmstick** [comment]
The package isn't installed by default, so it shouldn't be installed unless you opted into it. The name of the package is `backport-iwlwifi-dkms`, so you can remove it by running `sudo apt remove backport-iwlwifi-dkms`.

**Comment by MaCroX95** [comment]
> The package isn't installed by default, so it shouldn't be installed unless you opted into it. The name of the package is `backport-iwlwifi-dkms`, so you can remove it by running `sudo apt remove backport-iwlwifi-dkms`.

Excellent thank you!
Works great now, sorry for bothering you, this thread can be closed now since I apparently pressed the install button in software store when updating through GUI. :grin:
