### ISSUE TITLE
Snap Store and Remmina snap not using dark theme?

### ISSUE THREAD

**Issue by RenouxMarais** [pop-os/pop#715]
Hi All.

Went through all settings and tried to get both mentioned in dark mode but it wont.
Worth noting that both of these are snaps, older version downloaded from POP store was dark themed as per system.

Not sure if I am missing something?

**Comment by bekips** [comment]
snaps don't do themes properly, on any distro. never have.

**Comment by RenouxMarais** [comment]
Ah. Thanks. Still getting used to Linux and how it works.
