### ISSUE TITLE
Light and dark mode switch appears to be missing from the intel iso

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#717]
I installed once from the intel ISO and once from tribble on an intel graphics laptop. Both times I don't recall seeing the GNOME Initial Setup light/dark mode option.

**Comment by brs17** [comment]
Theme switcher was removed from GIS prior to 19.10 launch due to the switcher not making the appropriate changes for the new user. This issue is all detailed here: https://github.com/pop-os/gnome-initial-setup/issues/48 . Once a solution is found, the switcher will be added to GNOME Initial Setup.
