### ISSUE TITLE
Screen going blank after few seconds of inactivity

### ISSUE THREAD

**Issue by sudhirj** [pop-os/pop#72]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
```

**Issue/Bug Description**

After a few seconds of inactivity, the screen goes blank. Have disabled all related Power settings: Blank Screen is set to "Never", and Automatic Suspend is off, but the problem still remains. Not a cable problem or a hardware issue, either, have tried both DisplayPort and HDMI, exactly the same issue in both cases. Does not happen with my other computer / laptop.

This a full signal stoppage - the monitor shows the built in "No Signal" screen. 

Recovery is easy - if I can just move the mouse or type and the screen comes back.

**Steps to reproduce (if you know)**
Stop moving the mouse or typing and just wait for a few seconds. 

**Expected behaviour**
One would expect the screen not to switch itself off :-P

**Other Notes**

**Comment by sarahpandabeara** [comment]
@sudhirj Can you share what type of machine (including CPU & GPU) you are running? That will make it easier for us to re-create the issue here in our lab.

**Comment by sudhirj** [comment]
@sarahpandabeara Sure, I have this NUC https://www.intel.in/content/www/in/en/nuc/nuc-kit-nuc6i7kyk-features-configurations.html

It's been outfitted with 32GB RAM and a 256GB Samsung 960 EVO m2 SSD if that makes a difference. No external GPU, I'm plugged into a 4K monitor running at 200% scaling. 

The problem happens both when plugged in via HDMI and DisplayPort. Haven't checked if it happens at a lower resolution than 4K.

**Comment by sudhirj** [comment]
Is there a log file I can post? I can post the last ~1000 lines off whichever log you think will help debug immediately after this happens.

**Comment by WatchMkr** [comment]
This appears to be a hardware specific driver bug. Modifying display power settings works on hardware here - including a different NUC model on a 4k display. I suggest filing a bug here: https://bugs.freedesktop.org

**Comment by colans** [comment]
@sudhirj Kindly post a link to the other bug you created?  Thanks.

**Comment by sudhirj** [comment]
Been a few years, don't remember creating one, sorry. Is it still happening for you?

**Comment by colans** [comment]
Yeah, all of a sudden, this laptop started blanking after 30 seconds even though the settings say not to; it never did this before.  I also did everything mentioned at [Screen turning off when idle even with power settings disabled](https://askubuntu.com/questions/1001198/screen-turning-off-when-idle-even-with-power-settings-disabled), and actually that stuff was already done.

**Comment by colans** [comment]
Okay, turns out it's fixed by `xset -dpms` as per [r/pop_os: Screen going black after 30 seconds](https://www.reddit.com/r/pop_os/comments/eln8bp/screen_going_black_after_30_seconds/).

If this is still happening, isn't it a bug we can deal with here?  Can we reopen this for that purpose?

**Comment by colans** [comment]
Just in case anyone else lands here for the same thing I did, open ticket is https://github.com/pop-os/pop/issues/2104.
