### ISSUE TITLE
Drag & Drop to/from desktop

### ISSUE THREAD

**Issue by konsumer** [pop-os/pop#723]
**Distribution:**
 ```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version:**

I think it's `pop-desktop` but really not sure:

```
pop-desktop:
  Installed: 1.2.12~1571158898~19.10~1b39ca8
  Candidate: 1.2.12~1571158898~19.10~1b39ca8
  Version table:
 *** 1.2.12~1571158898~19.10~1b39ca8 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**

With other desktop systems (unity, cinnamon, nautilus on gnome, kde, etc), I can drag & drop files from the desktop. This doesn't work on pop. An example is that I can drag & drop to add an image to this issue while I'm editing it. It works fine if I open a file-manager and navigate to ~/Desktop and drag from there, or use another desktop-system (tested with cinnamon.)

**Steps to reproduce (if you know):**

try to drag an image onto a chrome window. It's not just chrome though, it seems to happen with any program that otherwise works with D&D, including file-manager. It happens dragging things to & from desktop.

**Expected behavior:**

it should open the image, if it's working correctly.

**Other Notes:**

Here is the behavior from desktop & from filemanager:

![no](https://user-images.githubusercontent.com/83857/67626611-5d45f680-f802-11e9-847f-94cd7bac795c.gif)

![yes](https://user-images.githubusercontent.com/83857/67626612-5fa85080-f802-11e9-86d3-4cda7f95b088.gif)

To get the screencap in the issue,  I had to open the file-manager, browse to ~/Desktop, then drag it from there.

**Comment by mmstick** [comment]
GNOME dropped support for desktop icons in Nautilus in the 3.32 release which was featured in 19.04. Desktop icons have been provided by a GNOME Shell extension ever since, which has never supported this feature. Until GNOME decides to reintegrate desktop icons into the desktop at some point, or the extension becomes capable of better integration with desktop applications, this is what we're stuck with today.

**Comment by konsumer** [comment]
Looks like cinammon uses nemo, which is very similar, but supports desktop icons (running `nemo-desktop`.)  Maybe we should switch.

**Comment by konsumer** [comment]
I may be missing features, but I did `sudo apt remove nautilus` and it got rid of double "Files" entry in meta-search.

![Screenshot from 2019-10-26 15-35-58](https://user-images.githubusercontent.com/83857/67626865-6769f400-f806-11e9-9e1c-1843c16014a8.png)

**Comment by konsumer** [comment]
Hmm, on reboot, after this, Pop desktop was no longer available. I think I'll just stick with cinnamon for a while. Having functional D&D makes my life easier (a common task in my regular workflow is dragging images into issues, for example, or dragging images from the web to my desktop while I am working on stuff.)

**Comment by mmstick** [comment]
You can still do that with nautilus, of course. Just not with the desktop background.

**Comment by danielskapunk** [comment]
It would be nice to show a message to inform the user about the limitation or alternatives.
I thought it was something I messed up with the configuration.

**Comment by jacobgkau** [comment]
This limitation was eliminated with https://github.com/pop-os/session/pull/26 / https://github.com/pop-os/session/pull/27. Drag/drop from the desktop to apps such as Chromium/Chome works now.
