### ISSUE TITLE
5.3.0-20 kernel won't connect to Wi-Fi range extender w/ Galago Pro

### ISSUE THREAD

**Issue by dido** [pop-os/pop#738]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

linux-generic:
  Installed: 5.3.0-20.21+system76~1572304854~19.10~8caa3e6
  Candidate: 5.3.0-20.21+system76~1572304854~19.10~8caa3e6
  Version table:
     5.3.0.19.22 500
        500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu eoan-security/main amd64 Packages
     5.3.0.18.21 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
 *** 5.3.0-20.21+system76~1572304854~19.10~8caa3e6 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

My home network basically consists of a TP Link Archer C7 as the main router, and a TP-Link RE450 range extender since the Wi-Fi signal won't reach all the parts of my house without it. I've not had any issues with this set up for a very long time, at least until the update to kernel 5.3.0.

Now, after the 5.3.0 update, my laptop now refuses to talk to the range extender, insisting on connecting to the main router, even though its signal is very weak. Booting into kernel 5.0.0-32 fixes the issue, and I no longer have problems connecting to the SSIDs associated with the range extender.

**Steps to reproduce (if you know):**

With the 5.3.0-20 kernel, try to connect to a Wi-Fi range extender.

**Expected behavior:**

The system should not have any problem connecting to the Wi-Fi.

**Other Notes:**

I have no idea if this is limited to the Intel wireless drivers that are used by the Galago Pro. I don't have anything else to test this against.

**Comment by jwackito** [comment]
Same issue here with a Gazelle gaze14. Problem seems to be the package backport-iwlwifi-dkms=8042-0ubuntu1. Network-manager complains that "Credentials were not provided" or something like that. Journalfs sais
 
> WPA: Failed to set GTK to the driver (alg=2 keylen=32 keyidx=1)
>  RSN: Failed to configure GTK
> deauthenticating from xx:xx:xx:xx:xx by local choice (Reason: 1=UNSPECIFIED)

Workaround for this, downgrade to previos version...
Check available versions...
> yo@popos:~$ sudo apt-cache madison backport-iwlwifi-dkms
> backport-iwlwifi-dkms | 8042-0ubuntu1 | http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
> backport-iwlwifi-dkms | 8042-0ubuntu1 | http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
> backport-iwlwifi-dkms | 7906-0ubuntu1 | http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
> backport-iwlwifi-dkms | 7906-0ubuntu1 | http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages
> backport-iwlwifi-dkms | 7906-0ubuntu1 | http://us.archive.ubuntu.com/ubuntu eoan/universe Sources
> backport-iwlwifi-dkms | 8042-0ubuntu1 | http://ppa.launchpad.net/system76/pop/ubuntu eoan/main Sources

Then downgrade to previous one:

> yo@popos:~$ sudo apt install backport-iwlwifi-dkms=7906-0ubuntu1

You can pin the 8042 version so it skip software upgrades adding a file in /etc/apt/preferences.d/blacklist-iwlwifi-8042 with the following content

> Package: backport-iwlwifi-dkms
> Pin: version 8042-0ubuntu1 
> Pin-Priority: -1

It's a nasty bug, took like a lot to find the answer cause wifi was working at the office but I spend like 4 days without wifi at home (office, no auth, mac filtered, home with wpa2.)
Hope it get fixed soon. In any case, you are welcome ;)

**Comment by nitinsareen** [comment]
Hey, facing the same issue here with same OS and router. While implementing your solution to downgrade the wifi driver, having this error - 

Building for 5.3.0-20-generic
Building initial module for 5.3.0-20-generic
ERROR (dkms apport): kernel package linux-headers-5.3.0-20-generic is not supported
Error! Bad return status for module build on kernel: 5.3.0-20-generic (x86_64)
Consult /var/lib/dkms/backport-iwlwifi/7906/build/make.log for more information.
dpkg: error processing package backport-iwlwifi-dkms (--configure):
 installed backport-iwlwifi-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 backport-iwlwifi-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

Any suggestions please?

**Comment by nitinsareen** [comment]
Pls refer - https://github.com/pop-os/pop/issues/689#issuecomment-553304570

**Comment by dido** [comment]
Unfortunately, the above workaround just makes things worse. I managed to find a dpkg for the 7906 version that builds under 5.3.0 here:

https://launchpad.net/~vicamo/+archive/ubuntu/ppa-1848922.2/+packages

However, the downgraded kernel module has even worse behaviour than the 8042 version, refusing to connect to any of my WiFi networks at all, and I just get an authentication error. I am of course using WPA2(AES)-PSK on the router, have been since the beginning. What's worse is that the latest update removed the 5.0.0 kernel I was using previously and now I'm stuck with slow Wi-Fi until this is fixed, or I can figure out how to go back to 5.0.0.

**Comment by mmstick** [comment]
The previous kernel still exists (`linux-generic`), but you'll need to add and maintain loader entries for it.

**Comment by dido** [comment]
So now I managed to boot into the old 5.0.0-32 kernel, but the 8042 iwlwifi is still installed and still insists on connecting only to the main router. I installed the 7906 iwlwifi dpkg from the link I posted up there and created some EFI loader entries for the 5.0.0-32 kernel, and now I'm able to connect to WiFi extender as I always used to before this nasty bug showed up. I've created a blacklist for the broken 8042 module so the system won't try to install it again:

$ cat blacklist-iwlwifi-8042 
Package: backport-iwlwifi-dkms
Pin: version 8042*
Pin-Priority: -1

Then maybe someday if there's a new version of iwlwifi that fixes this hopefully I can start using the newer kernels again.

I'm running this on actual System76 hardware and I imagine that the Intel Wi-Fi chipset its using isn't exactly rare. This is a really convoluted workaround and hopefully there won't be an "upgrade" that removes my 5.0.0-32 kernel before everything is fixed.

**Comment by brs17** [comment]
> So now I managed to boot into the old 5.0.0-32 kernel, but the 8042 iwlwifi is still installed and still insists on connecting only to the main router. I installed the 7906 iwlwifi dpkg from the link I posted up there and created some EFI loader entries for the 5.0.0-32 kernel, and now I'm able to connect to WiFi extender as I always used to before this nasty bug showed up. I've created a blacklist for the broken 8042 module so the system won't try to install it again:
> 
> $ cat blacklist-iwlwifi-8042
> Package: backport-iwlwifi-dkms
> Pin: version 8042*
> Pin-Priority: -1
> 
> Then maybe someday if there's a new version of iwlwifi that fixes this hopefully I can start using the newer kernels again.
> 
> I'm running this on actual System76 hardware and I imagine that the Intel Wi-Fi chipset its using isn't exactly rare. This is a really convoluted workaround and hopefully there won't be an "upgrade" that removes my 5.0.0-32 kernel before everything is fixed.

I recommend reaching out to System76 support for a system76 product as they have dealt with removing/avoiding the backport-iwlwifi driver while also using 5.3* kernel.

**Comment by dido** [comment]
Well, I just done and uninstalled the backport-iwlwifi-dkms package at the advice of System76 support and now it seems that the bizarre Wi-Fi connectivity issues I've been experiencing suddenly went away with the latest kernel. They mentioned that the package was unnecessary.
