### ISSUE TITLE
video camera stops working after a suspend

### ISSUE THREAD

**Issue by laubster** [pop-os/pop#76]
**Reporter info**

 * Distribution - Pop!_OS 17.10

**Issue/Bug Description**

The video camera on my System76 Oryx Pro (orxp1) stops working once I suspend the machine; a full power down/up (not just straight reboot) is needed to reset it.

**Steps to reproduce**

Starting with the camera working after a power down/up:
- notice that "lsusb" reports something like "Bus 001 Device 004: ID 5986:066d Acer, Inc" (lsusb -v" indicates it's related to video)
- verify the camera is working by starting a video call in Riot
- suspend the machine, then resume
- notice that "lsusb" no longer reports the Acer entry
- Riot now just blinks when a video call is attempted

**Expected behavior**

The video camera should function after a suspension as well as before.

**Other Notes**

What's below is an excerpt from "dmesg"; compared to when the camera is working/malfunctioning, the output is the same, except that the last ("disconnect") line is present only when it's malfunctioning:

[    2.164034] usb 1-9: new high-speed USB device number 4 using xhci_hcd
[    2.352606] usb 1-9: New USB device found, idVendor=5986, idProduct=066d
[    2.352607] usb 1-9: New USB device strings: Mfr=3, Product=1, SerialNumber=2
[    2.352608] usb 1-9: Product: BisonCam, NB Pro
[    2.352608] usb 1-9: Manufacturer: Generic
[    2.352609] usb 1-9: SerialNumber: 200901010001
[    4.285689] uvcvideo 1-9:1.0: Entity type for entity Extension 4 was not initialized!
[    4.285690] uvcvideo 1-9:1.0: Entity type for entity Processing 2 was not initialized!
[    4.285691] uvcvideo 1-9:1.0: Entity type for entity Camera 1 was not initialized!
[    4.285805] input: BisonCam, NB Pro: BisonCam, NB  as /devices/pci0000:00/0000:00:14.0/usb1/1-9/1-9:1.0/input/input21
[  190.392236] usb 1-9: USB disconnect, device number 4

**Comment by sramkrishna** [comment]
I ran this through with technical support and they believe that this is a hardware issue.  Since you have a System76 computer, please call technical support and open a ticket.  Thanks!

**Comment by laubster** [comment]
Wrap-up... James@system76support steered me to a solution: use one of the Fn keys to explicitly re-enable the camera (in my case, it's Fn+F10).  Once I do that, lsusb does confirm the camera is reinstated (as Device 5 instead of 4). From that point on I've also noticed the camera is automatically re-enabled after subsequent suspends, without the need for additional Fn+F10 presses (at least until the next cold reboot).
