### ISSUE TITLE
Screenshot of selected region using ctrl+shift+prtsc not saving image

### ISSUE THREAD

**Issue by jackpot51** [pop-os/pop#761]
@maria-komarova discovered that taking a screenshot of a region using ctrl+shift+prtsc does not save images under ~/Pictures

Other keyboard shortcuts (alt+prtsc and prtsc) do save the image.

**Comment by Amizaday** [comment]
Olá, ao invés de ctrl+shift+prtsc use shift+prtsc, ;)

**Comment by jacobgkau** [comment]
Yes, Shift + PrtSc is for saving a region to ~/Pictures. Ctrl + Shift + PrtSc is for copying a region to clipboard.

This is documented on GNOME's website here: https://help.gnome.org/users/gnome-help/stable/screen-shot-record.html.en 

Confirmed both of these are working on 21.04 and 21.10.
