### ISSUE TITLE
VirtualBox 6.0.6 not working on Kernel 5.3.0-20-generic

### ISSUE THREAD

**Issue by Latelesley** [pop-os/pop#762]
**Distribution (run `cat /etc/os-release`):**
 
 NAME="Pop!_OS"
VERSION="19.04"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.04"
VERSION_ID="19.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://download.virtualbox.org/virtualbox/debian disco/contrib amd64 Packages
     release o=Oracle Corporation,n=disco,l=Oracle Corporation,c=contrib,b=amd64
     origin download.virtualbox.org
1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main i386 Packages
     release v=19.04,o=LP-PPA-system76-pop,a=disco,n=disco,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu disco/main amd64 Packages
     release v=19.04,o=LP-PPA-system76-pop,a=disco,n=disco,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 http://apt.pop-os.org/proprietary disco/main all Packages
     release v=19.04,o=system76,a=disco,n=disco,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary disco/main amd64 Packages
     release v=19.04,o=system76,a=disco,n=disco,l=System76,c=main,b=amd64
     origin apt.pop-os.org
 100 http://us.archive.ubuntu.com/ubuntu disco-backports/universe i386 Packages
     release v=19.04,o=Ubuntu,a=disco-backports,n=disco,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu disco-backports/universe amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-backports,n=disco,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu disco-backports/main i386 Packages
     release v=19.04,o=Ubuntu,a=disco-backports,n=disco,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu disco-backports/main amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-backports,n=disco,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/multiverse i386 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/multiverse amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/universe i386 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/universe amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/restricted amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/main i386 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-updates/main amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-updates,n=disco,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/multiverse i386 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/multiverse amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/universe i386 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/universe amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/restricted amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/main i386 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco-security/main amd64 Packages
     release v=19.04,o=Ubuntu,a=disco-security,n=disco,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/multiverse i386 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/multiverse amd64 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/universe i386 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/universe amd64 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/restricted i386 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/restricted amd64 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/main i386 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu disco/main amd64 Packages
     release v=19.04,o=Ubuntu,a=disco,n=disco,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
Pinned packages:

**Issue/Bug Description:**

When trying to run a virtual machine in Virtualbox I get the error :

```
The virtual machine 'Android 9 x86 64' has terminated unexpectedly during startup with exit code 1 (0x1).

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | MachineWrap
Interface: | IMachine {5047460a-265d-4538-b23e-ddba5fb84976}

```
and 

`Kernel driver not installed (rc=-1908)

The VirtualBox Linux kernel driver is either not loaded or not set up correctly. Please reinstall virtualbox-dkms package and load the kernel module by executing

'modprobe vboxdrv'

as root.

If your system has EFI Secure Boot enabled you may also need to sign the kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load them. Please see your Linux system's documentation for more information.

where: suplibOsInit what: 3 VERR_VM_DRIVER_NOT_INSTALLED (-1908) - The support driver is not installed. On linux, open returned ENOENT. `

**Steps to reproduce (if you know):**

Tried running a virtual machine. 

**Expected behavior:**

Virtual machine should start

**Other Notes:**

A bit of googling showed that the issue is with the newer kernel 5.3.0 onwards. VirtualBox needs to be version 6.0.14 to work with the new kernel, current version in Pop! OS is 6.0.6. Can we please get version 6.0.14? :-) 

https://askubuntu.com/questions/1175840/unable-to-start-virtualbox-vm-on-ubuntu-kernel-driver-not-installed

I did try the other fix recommended, which was to run "sudo apt install virtualbox-dkms", but it says it is already the latest version. 
`sudo apt install virtualbox-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
virtualbox-dkms is already the newest version (6.0.6-dfsg-1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
`

**Comment by mmstick** [comment]
You need to install it from https://download.virtualbox.org/virtualbox/6.0.14/virtualbox-6.0_6.0.14-133895~Ubuntu~bionic_amd64.deb

**Comment by Latelesley** [comment]
:( I just tried that, and got an error. 

I tried sudo apt remove virtualbox, to remove the installed version, then tried installing. 

Now the package installer says 
"Same version is available in a software channel.
You are recommended to install the software from the channel instead"

It's actively stopping me from installing it. I click install package, and the package installer just disappears. 

Thanks for the link though.

**Comment by mmstick** [comment]
What's the output from installing it with `dpkg -i`?

**Comment by Latelesley** [comment]
```
sudo dpkg -i virtualbox-6.0_6.0.14-133895_Ubuntu_bionic_amd64.deb 
[sudo] password for lesley: 
Selecting previously unselected package virtualbox-6.0.
(Reading database ... 269646 files and directories currently installed.)
Preparing to unpack virtualbox-6.0_6.0.14-133895_Ubuntu_bionic_amd64.deb ...
Unpacking virtualbox-6.0 (6.0.14-133895~Ubuntu~bionic) ...
Setting up virtualbox-6.0 (6.0.14-133895~Ubuntu~bionic) ...
addgroup: The group `vboxusers' already exists as a system group. Exiting.
```

hmm. Looks like the Group is stopping install. (First I panicked, cos I've never used the dpkg command. I'm clueless. :-D ) 

Ok, so I went into sytem settings, users and groups, and deleted vboxusers. Tried again.

```
sudo dpkg -i virtualbox-6.0_6.0.14-133895_Ubuntu_bionic_amd64.deb 
(Reading database ... 270471 files and directories currently installed.)
Preparing to unpack virtualbox-6.0_6.0.14-133895_Ubuntu_bionic_amd64.deb ...
Unpacking virtualbox-6.0 (6.0.14-133895~Ubuntu~bionic) over (6.0.14-133895~Ubuntu~bionic) ...
Setting up virtualbox-6.0 (6.0.14-133895~Ubuntu~bionic) ...
Adding group `vboxusers' (GID 129) ...
Done.
Processing triggers for systemd (240-6ubuntu5.2pop1) ...
Processing triggers for gnome-menus (3.32.0-1ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-4ubuntu1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for shared-mime-info (1.10-1) ...
```

I fired up VirtualBox, 6.0.14 is installed, and tried the virtual machine, and it now loads, no error. :-)

You cracked it, mmstick. Thank you so much for all your help. I was lost otherwise. 

But, Pop! OS still need to upgrade the version in the repository. :-)

**Comment by jacobgkau** [comment]
Our VirtualBox packaging has been updated since this issue was opened.
