### ISSUE TITLE
Contributing to upsteam repositories and fork policy

### ISSUE THREAD

**Issue by PanderMusubi** [pop-os/pop#763]
**Distribution (run `cat /etc/os-release`):** Pop!_OS
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):** n/a

**Issue/Bug Description:** From the 133 repositories at https://github.com/pop-os at least 14 are forked form GitHub repositories (such as https://github.com/pop-os/linux ) and at least 16 are forked from repositories outside of GitHub, such as Launchpad (such as https://github.com/pop-os/linux-firmware ).

Before me and my colleagues purchase hardware from System76, we need to know how well Ubuntu runs on it out of the box, because we need to be able to run it with good hardware support. In order to be able to reproduce certain software behavior, we are bound to those operating systems.

Pop!_OS has a lot of forks and does development on those, but we do not have a clear view of how this development is being contributed upstream via pull requests, patches or merge requests. We have had look at a lot of the forked repositories here, but haven't been able to see contributions upstream. Even though this is all open source, we wonder how dependent a user of a System76 hardware is on Pop!_OS. We hope users are not locked into using only Pop!_OS for being able to have full hardware support and/or upstream repositories start deviating too much that merging (either way) becomes an issue in itself.

**Steps to reproduce (if you know):** n/a

**Expected behavior:** Regular contributions to upstream and info regarding this so that hardware support for System76 is up to date in also Ubuntu and users are well-informed on the policy and impact of the forks.

**Other Notes:** I have read https://support.system76.com/articles/install-ubuntu/

**Comment by jackpot51** [comment]
The majority of the purpose for these forks is to provide earlier access to upstream code. For example, deploying the 19.10 Ubuntu kernel on 18.04 to ensure Comet Lake CPUs are functional. We also deliver the same support to our Ubuntu customers using the system76-dev/stable PPA.
