### ISSUE TITLE
After the installation is locked in the configurations(setup)

### ISSUE THREAD

**Issue by filipeGamaBR** [pop-os/pop#77]
After installing pop and configuring the setup, nothing appears like the side menu, I tried to reboot the system, and when I reboot it asks to confirm the setup again and it is only there.

ps: I downloaded Pop twice the iso .47 and nvidia .36 both with the same problem, and checked the integrity of the isos and the correct ones.

specs:

Dell inspiron i14-5458 laptop

intel core i3 5 generation 2.0ghz
gpu: Intel HD graphics 5500
ram: 4GB DDR3-1600mhz

Thanks for the suport ,and all equip and sorry for my bad english.

**Comment by ahoneybun** [comment]
What username did you use during the setup?

**Comment by filipeGamaBR** [comment]
I used the same from my gmail account.

**Comment by ahoneybun** [comment]
What is your gmail? Not sure what that is.

**Comment by filipeGamaBR** [comment]
Well, when I set up the pop after installation I chose to log in and use the gmail account as my computer account so I only chose a password.

**Comment by WatchMkr** [comment]
Hi, thanks for your report. Try to use a short username and see if that solves the problem for you. We've seen this before with initial setup. Please re-open this bug if that doesn't work.
