### ISSUE TITLE
Korean Language Input

### ISSUE THREAD

**Issue by hanyangii** [pop-os/pop#784]
Hello,

I have a question about language input. 

I am currently using a Korean keyboard layout but still can't type in Korean, although I've installed ibus-hangul.

I've also installed Korean language for input source on 'Regional and Language' tab in Settings.

Do you know how to get other language input?

Thanks.

**Comment by crawfxrd** [comment]
안녕! It was a PITA for me to get Hangul working when I set it up.

I just tried it on a different machine, and it look like this is the problem:
```
Generating locales (this might take a while)...
  ko_KR.UTF-8...hash collision (1701936715) ko_KR.utf8, es_CO.utf8
 done
```

What I did was:
```
apt purge language-pack-es-base langauge-package-gnome-es-base
apt install --reinstall language-pack-ko-base
```
This allowed me to add "Korean (Hangul)" as an input source.

**Comment by BootlegPhil** [comment]
I selected the Korean (Hangul) option, which is the only option that shows up with a gear next to it. Using this option, Korean input works perfectly on my setup.

**Comment by crawfxrd** [comment]
Going to close this. The locale issue appears to have been fixed (don't see it anymore on new installs), so once the Korean language pack is installed it should be available for input and display language.
