### ISSUE TITLE
I keep getting this whenever I open pop shop

### ISSUE THREAD

**Issue by A-Random-Lantern** [pop-os/pop#787]
Distribution is Pop!_OS 19.10
 
I keep getting this whenever open pop shop, only way to remove it is to press ignore

I get this error

E: The repository 'http://ppa.launchpad.net/embrosyn/cinnamon/ubuntu eoan Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/webupd8team/java/ubuntu eoan Release' does not have a Release file.
W: Updating from such a repository can't be done securely, and is therefore disabled by default.
W: See apt-secure(8) manpage for repository creation and user configuration details

**Comment by crawfxrd** [comment]
You are using PPAs.

WebUpd8/java is [discontinued](https://launchpad.net/~webupd8team/+archive/ubuntu/java). You should remove the PPA. If you want to use Oracle JDK, you should [download it from the Oracle site](https://www.oracle.com/technetwork/java/javase/downloads/index.html).

@embrosyn does not have Cinnamon packages for 19.10.
