### ISSUE TITLE
GDM user leaks too much ram while the computer is used

### ISSUE THREAD

**Issue by AkechiShiro** [pop-os/pop#789]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

```
gnome-shell:
  Installed: 3.34.1-1ubuntu1pop0~1573148724~19.10~f65f9b1
  Candidate: 3.34.1-1ubuntu1pop0~1573148724~19.10~f65f9b1
  Version table:
     3.34.1+git20191024-1ubuntu1~19.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
 *** 3.34.1-1ubuntu1pop0~1573148724~19.10~f65f9b1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     3.34.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages

```

**Issue/Bug Description:**
GDM consumes lots of ram (about 1.4GB sometimes more or less than that inconsistent, the maximum I have seen was 4GB of consumption) after the computer has been up for about more than 24 hours non-stop.
![GDMramConsumption](https://user-images.githubusercontent.com/14914796/70866222-6aac7100-1f67-11ea-9393-9401f85e7b95.png)

**Steps to reproduce (if you know):**
Just use the computer normally

**Expected behavior:**
GDM consumption of ram should be lower.

**Other Notes:**

I contacted [Gnome devs](https://gitlab.gnome.org/GNOME/gnome-shell/issues/829#note_631221) about a month ago to ask them about any memory leak they pointed out to me that I should open an issue here and since it has been a few weeks without any changes or solutions, I've taken their suggestion.
I'm not sure if the issue comes from PopOS or from Gnome 3 or maybe both, but I think that further investigation for both is needed.

**Comment by mmstick** [comment]
Software should never leak memory, so it's definitely an upstream issue. They would have the best idea of how to fix this. We're just packaging their software straight from Ubuntu's packaging.

**Comment by AkechiShiro** [comment]
So this comment on the Gnome devs page of an issue about ram leaks, is completely useless and mistaking about the fact that the issue is could be PopOS-specific?? 

> @AkechiShiro, Note your 4GB gnome-shell process is running as user gdm. That means it is the login screen GUI and not your actual shell! 🙂
> In regular Ubuntu and upstream gnome-shell that process running as gdm should get killed and not exist while you are logged in. Then it gets recreated whenever the login screen is needed again. Maybe it's a PopOS-specific issue then.

**Comment by mmstick** [comment]
We're using the same packaging as Ubuntu here, so there should no difference in behavior.

**Comment by AkechiShiro** [comment]
Oh okay so there is either an issue within Ubuntu 19.10 or an issue with Gnome 3 (it's most likely an issue with Gnome 3), I'll close this issue thanks for the information.
