### ISSUE TITLE
External monitor not detected after waking from locked workstation. (MiniDP)

### ISSUE THREAD

**Issue by dgoerlich** [pop-os/pop#79]
**Issue/Bug Description**

My external monitor is no longer detected on resume from a locked workstation.  System acts as though no monitor is plugged in when driving via MiniDP.  This did not occur when driving the same monitor via HDMI.

**Steps to reproduce (if you know)**

1) Plug external monitor in via MiniDP
2) Lock the workstation, allowing screen to blank
3) Hit key / move mouse to wake system
4) System will not detect the external monitor unless you unplug / reconnect the monitor.

**Expected behavior**

When waking from a locked state, monitor should be detected, and previous display settings retained

**Other Notes**

I originally was driving this monitor via HDMI, and things worked correctly with the monitor detected on waking.

**Comment by cassidyjames** [comment]
@dgoerlich interesting, I've not experienced this on my laptop + miniDP display. What sort of graphics does your system have?

**Comment by dgoerlich** [comment]
@cassidyjames, it's a brand new Galago Pro with the Intel HD Graphics 620.

**Comment by dgoerlich** [comment]
Mine is a galp3 (and wow, what a great piece of hardware) - but I'm not sure what differences might be in the details between the two.  I'll give it a try with a different monitor on the miniDP port and see if I get the same result.

**Comment by dgoerlich** [comment]
I did a bit more testing, and discovered that everything works as expected as long as the monitor has not gone into "power save" mode after the signal loss with the blanking of the screens.  I can lock the workstation, and immediately attempt to log back in, and the external monitor is still enabled with all proper settings.  However, if the monitor has gone to sleep, waking the notebook does not seem to turn the signal back on through the miniDP.  (It did work as expected on HTMI to the same monitor).

@cassidyjames I'm a bit out of my depth here to know where that line falls between "specific hardware issue" and "OS issue", so I'm happy to take your recommendation to reach out to the amazing support team at System76 if you think that's more likely to be where the root cause would be found.  Thanks!

**Comment by cassidyjames** [comment]
@dgoerlich I think support is your best bet. Thanks for your report, though!

**Comment by dgoerlich** [comment]
Will do!  Thanks!
