### ISSUE TITLE
Breeze conflicts with pop-os-branding after install.

### ISSUE THREAD

**Issue by sysdrum** [pop-os/pop#80]
**Reporter info**

sysdrum

```
 * Distribution

NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS Artful Aardvark"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/system76/pop-distro/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful
 * Related Application and/or Package Version - apt policy $PACKAGE NAME
```

**Issue/Bug Description**

Breeze conflicts with pop-os-branding after install. 

Most cases will be due to the ERROR of not having Breeze installed after installing Kdenlive.

You will see that the POP_OS! Logo is no longer in place under details in Settings ( Gnome-control-center )

POP_OS Pop index.theme shows this:
`Inherits=pop-os-branding,breeze,ubuntu-mono-dark,Mint-X,elementary,gnome,hicolor`

**Steps to reproduce (if you know)**
Install Breeze icons
Open Settings ( Gnome-control-center )
Go to Details
You will see that the POP_OS! Logo is no longer in place under details.
An Ubuntu logo is in place.

**Expected behavior**

POP_OS! Logo in place under details.

**Comment by brs17** [comment]
Closed and reopened here: https://github.com/pop-os/gtk-theme/issues/91
