### ISSUE TITLE
irqbalance installed by default

### ISSUE THREAD

**Issue by flyinprogrammer** [pop-os/pop#81]
https://github.com/konkor/cpufreq/issues/48#issuecomment-345753362

**I have 0 interest in starting or fighting a religious battle**, however, ya'll might simply consider removing the `irqbalance` package from the default installation.

While I have no scientific proof, it would seem my galp2 is much happier post- removal, i.e. I'm running in pstate performance mode (cores clocked to around 3.4+GHz with turbo enabled) and the laptop fan is coming on less than it ever has. I can try and put together some non-scientific battery stats too over the next week or so.

**Comment by WatchMkr** [comment]
Thanks for the suggestion. Pulling together battery stats would be helpful. I think we should consider this in the context of another project we're considering - enabling performance profiles through the system menu.

I'm going to add the roadmap tag to help track this.

**Comment by brs17** [comment]
We have included new power management functionality in Pop!_OS 18.04, @flyinprogrammer, go ahead and take a look at that and let us know what you think!
