### ISSUE TITLE
Couldn't install printer shared over network

### ISSUE THREAD

**Issue by pollaloca** [pop-os/pop#811]
**Distribution (run `cat /etc/os-release`):**
 AME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
cups:
  Installed: 2.2.12-2ubuntu1
  Candidate: 2.2.12-2ubuntu1
  Version table:
 *** 2.2.12-2ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
1.- Couldn't install a printer from a Windows PC shared over the network because the user was not added automatically to the `lpadmin` group. I had to added it manually. 
2.- Then the printer won't print because authentication failure but won't ask for credentials. I had to edit `/etc/cups/printers.conf` and change the line that says `AuthInfoRequired none` to `AuthInfoRequired username,password`

I think this should be done automatically.

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by jacobgkau** [comment]
Administrator users (including the default user) will now be added to `lpadmin` by default: https://github.com/pop-os/accountsservice/pull/2
