### ISSUE TITLE
Japanese (Mozc) Preferences

### ISSUE THREAD

**Issue by ghost** [pop-os/pop#815]
**Distribution (run `cat /etc/os-release`):**
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Mozc 2.23.2815.102

Output of `apt policy $PACKAGE NAME`:

Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_19.10 ./ Packages
     release o=obs://build.opensuse.org/Emulators:Wine:Debian/xUbuntu_19.10,n=xUbuntu_19.10,l=Emulators:Wine:Debian,c=
     origin download.opensuse.org
 500 https://repo.windscribe.com/ubuntu bionic/main i386 Packages
     release o=. bionic,a=bionic,n=bionic,l=. bionic,c=main,b=i386
     origin repo.windscribe.com
 500 https://repo.windscribe.com/ubuntu bionic/main amd64 Packages
     release o=. bionic,a=bionic,n=bionic,l=. bionic,c=main,b=amd64
     origin repo.windscribe.com
1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
     release v=19.10,o=LP-PPA-system76-pop,a=eoan,n=eoan,l=Pop!_OS PPA,c=main,b=i386
     origin ppa.launchpad.net
1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
     release v=19.10,o=LP-PPA-system76-pop,a=eoan,n=eoan,l=Pop!_OS PPA,c=main,b=amd64
     origin ppa.launchpad.net
 500 https://brave-browser-apt-release.s3.brave.com eoan/main amd64 Packages
     release o=. eoan,a=eoan,n=eoan,l=. eoan,c=main,b=amd64
     origin brave-browser-apt-release.s3.brave.com
 500 https://brave-browser-apt-release.s3.brave.com disco/main amd64 Packages
     release o=. disco,a=disco,n=disco,l=. disco,c=main,b=amd64
     origin brave-browser-apt-release.s3.brave.com
 500 http://apt.pop-os.org/proprietary eoan/main all Packages
     release v=19.10,o=system76,a=eoan,n=eoan,l=System76,c=main,b=all
     origin apt.pop-os.org
 500 http://apt.pop-os.org/proprietary eoan/main amd64 Packages
     release v=19.10,o=system76,a=eoan,n=eoan,l=System76,c=main,b=amd64
     origin apt.pop-os.org
 100 http://us.archive.ubuntu.com/ubuntu eoan-backports/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-backports,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 100 http://us.archive.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-backports,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-updates,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan-security/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan-security,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/multiverse i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=multiverse,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/multiverse amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=multiverse,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/universe i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=universe,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=universe,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/restricted i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=restricted,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/restricted amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=restricted,b=amd64
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/main i386 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=main,b=i386
     origin us.archive.ubuntu.com
 500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
     release v=19.10,o=Ubuntu,a=eoan,n=eoan,l=Ubuntu,c=main,b=amd64
     origin us.archive.ubuntu.com
Pinned packages:

**Issue/Bug Description:**
When clicking the gear next to the Japanese (Mozc) option in Settings, the preferences won't pop up the way they do with other language options, such as Chinese (Intelligent Pinyin) and Korean (Hangul).

**Steps to reproduce (if you know):**
Go to Settings and click on the gear next to Japanese (Mozc).

**Expected behavior:**
For the Mozc preferences to appear when I press the gear.

**Comment by SirAlienTheGreat** [comment]
I know this is pretty old, but for anyone still wondering, you can fix this by running:
``` sudo apt install mozc-utils-gui```
