### ISSUE TITLE
packagekitd frequent activation, CPU usage, battery drainage

### ISSUE THREAD

**Issue by Iiari** [pop-os/pop#83]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```) Pop OS based on Ubuntu 17.10
 * Related Application and/or Package Version - apt policy $PACKAGE NAME  packagekitd
```

**Issue/Bug Description**
I was noting with the new version of Pop OS a drop in battery life from 5.5 hrs, to 3.5 hrs with frequent fan activation every few seconds and CPU spikes to 100% briefly when that happened with system slugishness.  For comparison, I installed Ubuntu 17.10. Battery life was great, 6.2 hrs, better than before.
I went back to Pop OS 17.04, and battery life again was 5.5 hrs without the frequent fan.  I installed the new Pop OS version on a different laptop, with the same results.  I knew the problem was 17.10 Pop OS, so I installed htop and it looked like the offending task was packagekitd.  When I killed that, the problem was GONE. Battery life jumped back up to 5 hrs 20 minutes (still not as good as before, but 1 hr 45 min better) and the laptop was silent without fan activation.

Talked on the Pop OS chat and in reply to a suggestion typed journalctl -u packagekit and it gave me over a 1000 lines back.  Amongst normal outpt, the abnormal one was: 
Nov 15 13:04:50 pop-os PackageKit[1319]: refresh-cache transaction /84534_eabaecac from uid 1000 finished with failed after 3372ms

Normal outpt lines were happening every 2-4 seconds, the failed ones every 6 seconds...

In my Googling, I found that similar packagekitd CPU spike bugs were seen with Elementary Loki, which is related to the Pop OS store, correct?  .

So, just my guess, I'm wondering if the Pop OS store or Eddy has a packagekitd bug? Might be worth looking into. I'm just into the first hour of this, but the resource utilization differences are night and day.

**Steps to reproduce (if you know)**
Every time I boot.

**Expected behavior**
As above

**Other Notes**
All as above.  Thanks!

**Comment by Iiari** [comment]
Uninstalling packagekit seems to work well.  I no longer have the problem on booting.  Is it necessary to have in the distro at all?

**Comment by WatchMkr** [comment]
Thanks for report. This isn't occurring on my machine. Do you have a way to replicate the bug? Does it occur when you're not connected to the internet? I'm wondering if the cache refresh are attempts to update repos.

**Comment by tompatulpan** [comment]
Have been running pop_os for a week and have monitoring CPU activity all the time. Yesterday I noticed high usage from packagekit and reboot or updates via terminal didn't help.
There are updates in pop_shop and I got error message when trying to run "Too few items to process" - maybe related??

**Comment by Iiari** [comment]
Maybe.  It's been on every install of Pop_OS I've done but I think I'm the only one who's complaIned about it, they hadn't been able to replicate it.  I'm just glad I'm not crazy!  You can uninstall packagekit and the problem is gone, but that breaks the Pop Shop and means you have to do updates and .deb installs manually via the command line.

**Comment by dragonbite** [comment]
By "manual" you mean "sudo apt update"?  If so, that isn't so bad.

**Comment by Iiari** [comment]
Exactly, and sudo apt upgrade, and I use gdebi to install .deb files.  I've never been a big app store person anyway.   To get double the battery life in return makes it worth it.  I'm not sure why seemingly only me tompatulpan seem cursed by this issue, but I installed Pop_OS on three machines and had the same problem with each...

**Comment by Iiari** [comment]
Think I finally fixed the packagekitd going nuts problem.  I think there was a broken PPA, and as a result, the elementary app store kept trying to reload the PPA, like, several times per second, ongoing, in the background without end.  That's why it was taking up so much CPU and draining so much battery.  So, it appears, the elementary app store needs to recognize when something is broken and behave differently.  I'll need to test it again, but unselecting the PPA from the additional software app and rebooting seems to have fixed the problem.  Packagekitd isn't running anymore and battery consumption is normal....  The PPA is  "http://ppa.launchpad.net/webup8team/nemo/ubuntu artful".

**Comment by jigarzon** [comment]
Hi guys I have also this currently happening on my Thinkpad X1 Extreme. Available for testing if you want. I just came to this issue after seeing a 50% reduction on battery consumption after killing packagekit...

**Comment by Iiari** [comment]
@jigarzon While no longer on Pop OS (I've finally settled on Manjaro KDE as my distro/DE of choice), when I was on Pop, I found a broken PPA was causing my issue (PPA frustration is one reason I'm no longer on Ubuntu/Debian based distros).  If a broken PPA isn't responsible for you, you can do what I did before I found that as the issue by adding a kill command for packagekit to your startup routine.

**Comment by mmstick** [comment]
In general, it's best to avoid PPAs unless absolutely necessary. We do package a lot of third party applications, so what you're looking for may already be in Pop. Lutris and GameHub, for example, were recently added.

**Comment by youngpm** [comment]
I encountered the same problem on a System 76 Thelio; fan was pulsing all the time.  Same deal, a bad PPA (had one in there for cosmo instead of disco).  Once removed, no more CPU usage.

**Comment by schwab** [comment]
Thanks for the tip on removing packagekit and finding bad PPAs. Removing that service really helped me too.  During development of a stack of Docker services, I really need the machine focused on the tasks I'm asking it too, not constantly checking ppa for broken updates. Cycling fans usually means something unexpected is happening and has negative effects on development.

**Comment by tuxutku** [comment]
I have the same problem:
```
utku3@pop-os:/home/utku3$ sudo systemctl status packagekit|cat
● packagekit.service - PackageKit Daemon
   Loaded: loaded (/lib/systemd/system/packagekit.service; static; vendor preset: enabled)
   Active: failed (Result: signal) since Fri 2019-11-01 17:30:18 +03; 4min 43s ago
  Process: 3464 ExecStart=/usr/lib/packagekit/packagekitd (code=killed, signal=KILL)
 Main PID: 3464 (code=killed, signal=KILL)

Nov 01 17:29:57 pop-os PackageKit[3464]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Nov 01 17:29:57 pop-os PackageKit[3464]: uid 1000 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Nov 01 17:30:05 pop-os PackageKit[3464]: refresh-cache transaction /9943_ebebceca from uid 1000 finished with need-untrusted after 7764ms
Nov 01 17:30:05 pop-os PackageKit[3464]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Nov 01 17:30:05 pop-os PackageKit[3464]: uid 1000 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Nov 01 17:30:13 pop-os PackageKit[3464]: refresh-cache transaction /9944_ecacbdbd from uid 1000 finished with need-untrusted after 8009ms
Nov 01 17:30:15 pop-os PackageKit[3464]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
Nov 01 17:30:15 pop-os PackageKit[3464]: uid 1000 obtained auth for org.freedesktop.packagekit.system-sources-refresh
Nov 01 17:30:18 pop-os systemd[1]: packagekit.service: Main process exited, code=killed, status=9/KILL
Nov 01 17:30:18 pop-os systemd[1]: packagekit.service: Failed with result 'signal'.
```
It was complaining about broken ppa, i have disabled the service for now.

**Comment by drscotthawley** [comment]
Just noticed my packaged is through the roof and I'm not doing anything.  
So...apart from deleting it, are there any instructions for fixing it? 
 "Don't use PPAs" just doesn't seem feasible in the modern world.  PopOS distros don't (yet) include all packages we may need.

**Comment by nprasovict** [comment]
I know this issue is closed, just wanted to confirm that I had the same issue and resolved it by removing a bad PPA. I had to install Google Chrome to be able to run E2E tests on my work project (NOT Chromium from official repo, it's older version than what I needed) and ended up with 2 google*.list files which contained references to the same Google repo (thanks Google developers for broken scripts!). After removing one of these files and running manual apt update && upgrade things went to normal. Had to kill -9 packagekitd first.
