### ISSUE TITLE
multiarch-support 

### ISSUE THREAD

**Issue by advaithm** [pop-os/pop#833]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

multiarch support is not installable on pop os but it is on ubuntu I have not been able to fix this issue and it is not from ubuntu 

**Expected behavior:**
it should be pre installed but it is not

**Other Notes:**
forcing a dist-upgrade doesn't fix the problem

**Comment by karx1** [comment]
Go to https://ubuntu.pkgs.org/19.04/ubuntu-main-amd64/multiarch-support_2.29-0ubuntu2_amd64.deb.html, scroll down to 'Binary Release', and click the file link

**Comment by jackpot51** [comment]
Could you provide more information about the issue? I have multiarch-support 2.29-0ubuntu3 installed on Pop!_OS 19.10
