### ISSUE TITLE
Pop Incompatible with New Navi Cards (5600 XT)

### ISSUE THREAD

**Issue by gardotd426** [pop-os/pop#842]
Running Pop-OS 19.10 (amd/intel iso)
After having to use `nomodeset` to get the live usb to boot without freezing, I went ahead and tried to install it, as I was told Pop OS works with Navi and it backports essential parts of more up-to-date kernels. I've been having some issues with Arch and Manjaro and wanted to replace Manjaro with Pop to test it out. Well, it doesn't work. At all. After installation, it's just a grey screen. I am unable to do anything, and it won't even let me into a tty. I chrooted into it from Arch, hoping that like in Linux Mint, maybe you all have a 5.4 or 5.5 kernel available in the repos, but no such luck. I updated everything from within Arch, and still, nothing (although I do get a message about "possibly missing firmware /lib/modules/amdgpu/navi10_mes.bin for module amdgpu). I'm attempting now to clone the git package for the updated firmware and hopefully that will work, but either way, it should be made clear that this distro is completely incompatible with newer Navi GPUs, at least not without massive tweaking. Preferably, this would actually be fixed and these things backported into the kernel and linux-firmware package. 
 
Steps to reproduce:
1. Have a Navi10 RX 5600 XT GPU (or a 5500 XT as well, most likely)
2. Install Pop OS 19.10
3. Attempt to reboot into new system.

**Comment by brs17** [comment]
RX 5700 XT and RX 5700 currently work in Pop!_OS 19.10. RX 5600 XT requires Linux 5.5 and Mesa >=19.3 and therefore is currently not supported in Pop!_OS. For the time being, expect this GPU to be supported in 20.04 although support may be provided sooner.
