### ISSUE TITLE
Contacts not syncing in GNOME Contacts

### ISSUE THREAD

**Issue by danielskapunk** [pop-os/pop#843]
**Distribution:** Pop OS 19.10
**Related Application and/or Package Version:**
GNOME Contacts 3.34

**Issue/Bug Description:**
GNOME Contacts not syncing with Google Account

**Steps to reproduce**
I just added my Google Account in Online Account under System Preferences.
In the Online Account preferences, everything is ON
When I open GNOME Contacts, select
Options Menu --> Change Address Book --> Select Google
Nothing happens

**Expected behavior:**
Address book would have changed and show synced contacts.

**Other Notes:**
- I'm also having other issues related to Online Accounts
For example, I can view the calendars from Google in Calendar App, but events doesn't show up in when searching with Activities Search

### Edit
The problem was that one of the contacts in my Google Contacts had the field Birthday with a wrong format, and Gnome Online Accounts couldn't sync the database without throwing any error messages in the GUI.
I downloaded Gnome Evolution 3.34 and when trying to sync it gave a useful error message that helped me to know what the problem was. 
Hope it helps to someone with a similar problem.
Also it would be nice to show an error message if Google contacts aren't fully synced.

**Comment by mrandreastoth** [comment]
Same issue and same fault-finding methodology identifying date format to be the issue. However, which contact is causing the issue is anyone's guess, and who knows how many of my contacts have this issue. Mo, this should not cause sync issues but must be handled correctly instead of throwing and error and refusing to sync.

**Comment by stickr** [comment]
Running in terminal after just linking my Google account into the Linux Online Accounts provides the following warning:

`(gnome-contacts:7691): gnome-contacts-WARNING **: 14:26:11.883: contacts-esd-setup.vala:80: Failed to authenticate for source "Contacts": Invalid request URI or header, or unsupported nonstandard parameter: Contacts API is being deprecated. Migrate to People API to retain programmatic access to Google Contacts. See https://developers.google.com/people/contacts-api-migration.`

**Comment by jacobgkau** [comment]
@stickr The issue you are referring to is not the same issue as this two-year-old issue, and is being tracked upstream here: https://gitlab.gnome.org/GNOME/gnome-contacts/-/issues/221
