### ISSUE TITLE
system76-cudnn-10.1 not available? 

### ISSUE THREAD

**Issue by mikkokotila** [pop-os/pop#844]
Unlike the information in https://support.system76.com/articles/cuda/ suggests, 10.1 is not available. 

```
mikko@pop-os:~/dev$ sudo apt install system76-cudnn-10.1
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package system76-cudnn-10.1
E: Couldn't find any package by glob 'system76-cudnn-10.1'
E: Couldn't find any package by regex 'system76-cudnn-10.1'
```
This also means that Tensorflow 2.1 can't be used. I think a lot of TensorFlow users want to use this version, particularly now that Keras is becoming depreciated. Given that you make a big deal about cuda/tensorflow on your website, I think this should actually work.

**Comment by mikkokotila** [comment]
By running `apt-cache search system76` it becomes clear that just 10.0 and 10.2 are available. No version of TensorFlow supports 10.2 and TensorFlow 2.0 which supports 10.0 really should not be used as it's pretty much just a beta of the new generation. 

```
system76-cuda - NVIDIA CUDA Compiler / Libraries / Toolkit Metapackage
system76-cuda-10.0 - NVIDIA CUDA 10 Compiler / Libraries / Toolkit
system76-cuda-10.2 - NVIDIA CUDA 10 Compiler / Libraries / Toolkit
system76-cudnn-10.0 - NVIDIA CUDA Deep Neural Network library (cuDNN) for CUDA 10.0
system76-cudnn-10.2 - NVIDIA CUDA Deep Neural Network library (cuDNN) for CUDA 10.2
system76-nccl-10.0 - Optimized primitives for collective multi-GPU communication.
system76-nccl-10.2 - Optimized primitives for collective multi-GPU communication.
system76-cuda-latest - Metapackage for the latest version of the CUDA Toolkit
gnome-shell-extension-system76-power - Gnome-shell extension for System76 Power Management
libs76-hidpi-widget - System76 HiDPI daemon widget library
libs76-hidpi-widget-dev - Pop theme switcher widget library header
linux-system76 - System76 recommended Linux kernel
network-manager-config-connectivity-pop - NetworkManager configuration to enable connectivity checking
system76-acpi-dkms - System76 ACPI Driver (DKMS)
system76-dkms - System76 DKMS driver
system76-driver - Universal driver for System76 computers
system76-driver-nvidia - Latest nvidia driver for System76 computers
system76-firmware - System76 Firmware CLI
system76-firmware-daemon - System76 Firmware Daemon
system76-io-dkms - System76 Io DKMS driver
system76-oled - Control brightness on OLED displays
system76-power - System76 Power Management
system76-r8125-dkms - System76 Realtek 8125 DKMS driver
system76-wallpapers - System76 Wallpapers

```

**Comment by Impeekay** [comment]
http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cudnn-10.1/

@mikkokotila  Found this, check if this deb can be used

**Comment by alextremes** [comment]
> http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cudnn-10.1/
> 
> @mikkokotila Found this, check if this deb can be used

Thanks @Impeekay, working flawlessly. @mikkokotila Remember installing the deb package at http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cuda-10.1/

**Comment by joshuacwnewton** [comment]
> Remember installing the deb package at http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cuda-10.1/

Thanks for the reminder, @alextremes. Very helpful.

I made the dumb error of not noticing the difference between the cuda and cudnn links (they're different!). For anyone else who missed it like I did, install [**cuda**-10.1](http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cuda-10.1/) first, then [**cudnn**-10.1](http://apt.pop-os.org/proprietary/pool/bionic/main/binary-amd64/s/system76-cudnn-10.1/) second.

**Comment by johndpope** [comment]
For clarity - if you have cuda10.1 you're looking for cuDNN at around 7.X (maybe 8 for 10.2)
https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html

**Comment by mmstick** [comment]
Closing this because it is available
