### ISSUE TITLE
Application Menu extensions do not work in Pop OS top bar for me

### ISSUE THREAD

**Issue by Iiari** [pop-os/pop#85]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
 * Distribution - (run ```cat /etc/os-release```)  Pop OS 17.10
 * Related Application and/or Package Version - apt policy $PACKAGE NAME  Application Menu Extensions
```

**Issue/Bug Description**
Trying to install most extensions that replace the Activities button in the top bar with a traditional Applications menu don't work in Pop OS and give errors.  Similar extensions do work in Ubuntu 17.10 and also in Pop OS 17.04.  

**Steps to reproduce (if you know)**
Trying to install, say, Applications Menu

**Expected behavior**
As above.  

**Other Notes**
Thanks!

**Comment by yousuc** [comment]
It is because gnome-shell-extensions is not installed. To fix:
`
sudo apt install gnome-shell-extensions`

**Comment by Iiari** [comment]
Installing gnome-shell-extensions sadly made no difference in that situation for me...

**Comment by Iiari** [comment]
Installing gnome-shell-extensions sadly made no difference in this situation for me.

**Comment by yousuc** [comment]
Interesting as installing that and restarting my session got it working for myself. But I personally use Arc Menu (which also requires gnome-shell-extensions to install a required lib... gir1.2-gmenu-3.0).

**Comment by sramkrishna** [comment]
installing gnome-shell-extensions only installs the extensions that come with GNOME.  It doesn't activate extensions per say.  If you're trying debug errors, type: 'alt-f2' and then type 'lg' - go to extensions and look for the extension you installed and then click on errors.  Feel free to post that here.

**Comment by sramkrishna** [comment]
It's been awhile since we've seen any activity on this bug.  If you this bug is still persistent, please re-open.

**Comment by fawkesmask** [comment]
sudo apt install gnome-shell-extensions

worked for me, with arc menu.

**Comment by UnixExt** [comment]
sudo apt install gnome-shell-extensions
Works Flawlessly with Pop OS 18.04, I tested it with Arc Menu

**Comment by Xinetizen** [comment]
I tried this :
`sudo apt install gnome-shell-extensions`

And it worked for me, with arc menu.
