### ISSUE TITLE
Issue after last update. With intel/AMD graphics. 

### ISSUE THREAD

**Issue by N3rdB01** [pop-os/pop#854]
**Distribution (run `cat /etc/os-release`):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by brs17** [comment]
Without any details about the system or information on how the problem happens, this report does not give us a clear starting point to figure out the issue.
