### ISSUE TITLE
20.04: GNOME Calender desktop icon is missing

### ISSUE THREAD

**Issue by brs17** [pop-os/pop#859]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-calendar

**Issue/Bug Description:**
When searching for gnome-calendar in the GNOME Activities search, the desktop icon is not the calendar icon but a generic program icon. When right clicking and selecting "Show Details" I see that the name of the program is `org.gnome.Calendar..desktop` which may be the cause of this issue.

**Comment by isantop** [comment]
It appears that the application name and expected Icon have been changed to `org.gnome.Calendar.` with the final dot. This is almost certainly a bug

**Comment by crawfxrd** [comment]
I don't see this (I have the correct icon). Can someone confirm if this is still the case?

**Comment by leviport** [comment]
I also now have the correct icon
