### ISSUE TITLE
Suspending the system is broken (at least on XPS 7590s running NVIDIA ISOs)

### ISSUE THREAD

**Issue by melkadze** [pop-os/pop#862]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
The issue is with the kernel's boot parameters; I've attatched kernelstub's apt policy in case it's relevant
```
kernelstub:
  Installed: 3.1.2~1578423034~19.10~9086739
  Candidate: 3.1.2~1578423034~19.10~9086739
  Version table:
 *** 3.1.2~1578423034~19.10~9086739 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Issue/Bug Description:**
On my laptop (the Dell XPS 15 7590), while using the NVIDIA-specific ISO for Pop!_OS, closing the laptop lid or otherwise suspending the system renders it inoperable once opening the lid, and waking the system back up.

It either displays a blank screen, a single underscore, or a message saying the GPU has fallen off the bus.

**Steps to reproduce (if you know):**
Close the laptop lid, wait for it to suspend, and wake the system back up by raising the lid.

**Expected behavior:**
The system should wake from its suspended state as normal.

**Other Notes:**
This issue can be **completely resolved** by setting the following kernel parameters with kernelstub:
`systemd.show_status=false`
`mem_sleep_default=deep`

Additionally, replacing the proprietary NVIDIA drivers with the Nouveau drivers seems to resolve the issue as well, but this is an undesirable solution.

I would attempt to submit a pull request to resolve this, but I am unaware of the consequences that setting these boot parameters may bring.

There is a [similar GitHub issue](https://github.com/pop-os/pop/issues/349) about this topic already, however it is marked as closed with a solution that doesn't work -- at least on my machine.

**Comment by RafalSkolasinski** [comment]
Is not the case on 21.04 and 21.10 now. 

BTW, deep sleep is broken on this laptop in general, one probably need to settle on s2idle... :(

**Comment by jacobgkau** [comment]
Thank you for confirming. As we don't have Dell XPS machines to test with and it sounds like this issue is no longer occurring on recent Pop!_OS/Linux kernel/NVIDIA driver versions, I'll close this for now.

**Comment by RafalSkolasinski** [comment]
For someone finding this issue later on: the system is with NVIDIA GPU but I run it in this mode that dedicated card is only used for compute (don't remember its exact name in the menu).
