### ISSUE TITLE
20.04: darp6 and galp4 do not have wifi

### ISSUE THREAD

**Issue by leviport** [pop-os/pop#869]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04

**Issue/Bug Description:**
Wifi does not work in 20.04 on darp6 and galp4.  The behavior is identical to when we first received the machines and began testing them on 19.10. The same fix may work on 20.04.

**Comment by willdarton** [comment]
"The same fix may work on 20.04." - can you point me at this fix?

**Comment by leviport** [comment]
I don't remember where it went, sorry. I believe it was a kernel update from upstream, and it was specifically related to 10th gen Intel CPU's and Intel CNVi wifi cards. It's fairly high on our list though, so we'll have it fixed pretty soon.

It could be related to [this bug](https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/1867026) though, in case you want to investigate that.

**Comment by willdarton** [comment]
> It could be related to [this bug](https://bugs.launchpad.net/ubuntu/+source/linux-firmware/+bug/1867026) though, in case you want to investigate that.

That fix did the trick on 19.10 as well.  Will keep an eye out for an official update. Thanks for the quick reply!

**Comment by brs17** [comment]
This seems to be resolved with the kernel currently in proposed: `5.4.0-7618.22~1584134448~20.04~82a44c0`. It will be released shortly.
