### ISSUE TITLE
Long disk encryption password escapes input box

### ISSUE THREAD

**Issue by 4e410a** [pop-os/pop#87]
**Reporter info**

Pop!_OS  on Thinkpad T440

**Issue/Bug Description**
When unlocking the system disk, longer passwords escape the input box.

Similar to this:
```
[***********]
[***********]********
```

**Steps to reproduce (if you know)**
1. Install Pop!_OS with full-disk encryption and a long password.
2. Restart
3. Try to enter the password.

**Expected behavior**

Long passwords should cause the input form to scroll left / right.
If not scroll, at least the text overflow should be hidden.

**Other Notes**
Making the input field larger could also help.

**Comment by isantop** [comment]
It kind of doesn't matter, because long passwords can always run out of the input box. Making the dots smaller might be a better soloution.

Not personally using FDE, can someone tell me how many dots fit into the box currently?

**Comment by AtomicCons** [comment]
Fits 19 characters. upon 20 and above, only 1 character is escaped. 
![screenshot from 2018-01-15 11-13-46](https://user-images.githubusercontent.com/22971111/34956167-331f969e-f9e5-11e7-9e06-85123927acd5.png)

**Comment by isantop** [comment]
So if I'm understanding correctly, if you have 21 characters, there's still only one dot that's overrun the box?

**Comment by AtomicCons** [comment]
From what i am seeing on a virtual and physical machine, that is correct.
Only 1 character run out of bounds.
