### ISSUE TITLE
Can't apt update, upgrade or distribution upgrade 

### ISSUE THREAD

**Issue by dbuscombe-usgs** [pop-os/pop#870]
Can't apt update or upgrade  
 
```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```
 
Output from ```sudo apt update``` 

```
Hit:1 http://storage.googleapis.com/bazel-apt stable InRelease
Ign:2 http://dl.google.com/linux/earth/deb stable InRelease                                                                         
Ign:3 http://us.archive.ubuntu.com/ubuntu cosmic InRelease                                                                          
Ign:4 http://apt.pop-os.org/proprietary cosmic InRelease                                                                            
Get:5 http://dl.google.com/linux/earth/deb stable Release [933 B]                                                                   
Hit:6 https://repo.skype.com/deb stable InRelease                                                                                   
Err:7 http://apt.pop-os.org/proprietary cosmic Release                                                                              
  404  Not Found [IP: 52.38.47.2 80]
Ign:8 http://us.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                                                  
Get:9 http://dl.google.com/linux/earth/deb stable Release.gpg [819 B]                                                               
Hit:10 http://ppa.launchpad.net/system76/pop/ubuntu cosmic InRelease                                                                
Ign:9 http://dl.google.com/linux/earth/deb stable Release.gpg                                                                       
Ign:11 http://us.archive.ubuntu.com/ubuntu cosmic-security InRelease                            
Hit:12 https://packages.cloud.google.com/apt cloud-sdk InRelease                                
Hit:13 https://packages.microsoft.com/repos/vscode stable InRelease                             
Ign:14 http://us.archive.ubuntu.com/ubuntu cosmic-backports InRelease     
Err:15 http://us.archive.ubuntu.com/ubuntu cosmic Release
  404  Not Found [IP: 91.189.91.14 80]
Err:16 http://us.archive.ubuntu.com/ubuntu cosmic-updates Release
  404  Not Found [IP: 91.189.91.14 80]
Err:17 http://us.archive.ubuntu.com/ubuntu cosmic-security Release
  404  Not Found [IP: 91.189.91.14 80]
Err:18 http://us.archive.ubuntu.com/ubuntu cosmic-backports Release
  404  Not Found [IP: 91.189.91.14 80]
Reading package lists... Done
E: The repository 'http://apt.pop-os.org/proprietary cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: http://dl.google.com/linux/earth/deb stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'http://dl.google.com/linux/earth/deb stable Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://us.archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://us.archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://us.archive.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://us.archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Contents of ```/etc/apt/sources.list```

```
# deb cdrom:[Pop_OS 18.10 _Cosmic_ - Release amd64 (20181217)]/ cosmic main restricted
# deb cdrom:[Pop_OS 18.10 _Cosmic_ - Release amd64 (20181217)]/ stable main restricted
# deb cdrom:[Pop_OS 18.10 _Cosmic_ - Release amd64 (20181217)]/ unstable main restricted
deb http://us.archive.ubuntu.com/ubuntu/ cosmic main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ cosmic main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ cosmic-updates main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ cosmic-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ cosmic-security main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ cosmic-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ cosmic-backports main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ cosmic-backports main restricted universe multiverse
deb http://apt.pop-os.org/proprietary cosmic main
# deb-src http://apt.pop-os.org/proprietary cosmic main
```

My preference would not be to upgrade distribution at this time, just update my packages. However, I can upgrade distribution if that is the only fix. Any advice would be gratefully appreciated

Thanks,
Dan

**Comment by MARDAScience** [comment]
It's been 12 days since I posted this. This affects BOTH my first-gen Thelio and my first-gen Thelio Massive. I am COMPLETELY SHUT DOWN by this! Anyone have any advice, beyond reinstalling the OS from scratch?

**Comment by leviport** [comment]
Sorry to be the bearer of bad news, but you're pretty much down to reinstalling the OS. 18.10 is not an LTS and is over a year old, so upgrades will not be possible. It is important to either use the LTS version or keep the OS updated. The new pop-upgrade utility will make keeping your OS release up-to-date much more convenient in the future, so it should be easier to avoid this situation.

Since you have System76 hardware, if you need any help backing up files and getting back up and running, our excellent support team will be happy to help: https://support.system76.com/

**Comment by MARDAScience** [comment]
Thank you!!! That's what I suspected but wanted to avoid the pain of file backups. I will install 19.10 from USB

**Comment by MARDAScience** [comment]
So, I flashed 19.10 onto a USB stick using `dd`, changed the boot order in BIOS. I get the message 'install pop!OS', I hit enter, then after a few seconds the screen goes off. The computer stays on indefinitely. As far as I can tell, the installation process never starts. Jeez this is such a pain!

**Comment by MARDAScience** [comment]
BTW, this only occurs on my Thelio Massive. I was able to install the OS on my smaller Thelio no problem.

**Comment by MARDAScience** [comment]
Update: I made and tried a different disk. No difference. I tried booting using F8 then selecting the disk. Hangs indefinitely. I tried booting by going into BIOS then changing the boot order. That allows me to at least see the pop!OS installation splash screen before hanging indefinitely. The computer stays on but the monitor goes blank. I can still boot into my OS but because it is 18.10 I cannot update, upgrade or install anything.

I have quite a bit of experience installing linux operating systems from USB so I don't think I'm doing anything wrong. As I say, the same process worked for me on my other Thelio. I'm stuck - please help

**Comment by MARDAScience** [comment]
Using the f8 popup menu approach, with either disk, when I get the pop!OS boot screen, after the countdown, the screen glitches before going blank. Might be relevant info.

I also made a third disk, this time using the Disks > restore disk image option. Same result. Makes me think I have a hardware problem? Or something wrong with bootloader?

**Comment by mmstick** [comment]
If you're using the NVIDIA ISO, did you try the Intel ISO?

**Comment by MARDAScience** [comment]
Thanks for the advice. I just got round to this (need to visit my computer physically!). No, that didn't work either. Any other suggestions? I'm at a loss

**Comment by leviport** [comment]
I highly recommend contacting System76 support with this. Since you have System76 hardware, support is included. We have a lot on our plate right now, and they will be able to help you much more quickly. We prefer not to use github issues for support-related matters. The support team is fantastic and they'll certainly be able to help you out. https://support.system76.com/

**Comment by MARDAScience** [comment]
Ok. I'll solve the problem out of public view then. I'm sure I won't be the only person with this problem ...
