### ISSUE TITLE
No Access To Settings Menu

### ISSUE THREAD

**Issue by transtrike** [pop-os/pop#871]
**Distribution (run `cat /etc/os-release`):**
 
 Pop!_Os 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Pop!_Os' Settings Menu 

**Issue/Bug Description:**

After putting the computer to sleep mode for the night, turning it on again i found these issues:
1. It's 11:24 AM and night mode was still active. It didn't turn off automatically
2. After that I decided to turn it off, so I clicked in the upper right corner and clicked on the settings button. After that the loading icon on the mouse appeared, but nothing happend. 10 minutes later, it didn't open the settings menu(But everything else was working just fine). So i decided to restart the OS. After doing so, the settings button on the same place disappeared. Even trying to get to the Settings from "Account settings" or from "Wired settings" isn't working

**Steps to reproduce (if you know):**

1. Put the PC to sleep mode(From the menu on the top right)
2. Turn it on after some time(Mine was around 6-7 hours, but same issue apperas after even 10 seconds in sleep mode)
3. Try to click on the settings button from the upper right corner's menu

**Expected behavior:**
1. Night mode(the one which makes your screen warmer at night) isn't turning off at the proper time
2. Cannot open settings menu from anywhere(haven't tried with commands, if there is a way)

**Other Notes:**

1. Night mode isn't turning off sometimes(no matter the time of the day) at proper time and also from the "Turn off" button
2. Sleep mode is sometimes shutting down the computer, insted of putting it to sleep

**Comment by transtrike** [comment]
Edit: Even after several restarts, the settings menu still isn't appearing. Currently reltaing to commands only for any kind of settings change, even minor
![Screenshot from 2020-03-14 11-27-47](https://user-images.githubusercontent.com/57849063/76681715-9f7ba300-65fe-11ea-9a7e-9a14aa64c325.png)

**Comment by mmstick** [comment]
Ensure that `pop-desktop` is installed. There may be a missing dependency.

**Comment by anegg0** [comment]
@mmstick Thank you much, `sudo apt install pop-desktop` did the trick for me, I had the exact same problem as @transtrike
