### ISSUE TITLE
Administrator password is requested in GUI sudo but it was never set during installation

### ISSUE THREAD

**Issue by poolpog** [pop-os/pop#88]
If this is a bug, please use the template below. If this is a question, or a general discussion topic - please post on our subreddit https://reddit.com/r/pop_os - as that is the proper forum for those types of posts.

**Reporter info**

```
NAME="Pop!_OS"
VERSION="17.10 (Artful Aardvark)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 17.10 (Artful Aardvark)"
VERSION_ID="17.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com/"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=artful
UBUNTU_CODENAME=artful

 * Related Application and/or Package Version - na
```

**Issue/Bug Description**

When performing tasks that require GUI sudo, (such as installing a .deb using Eddy) the end user is asked for the **Administrator** password

However, the Administrator password was never set. Also, typical scenarios like this -- that I've experienced in Ubuntu, LinuxMint, macOS, and Windows -- require the **user's** password. And the assumption is that the primary user has admin sudo privs.

**Steps to reproduce (if you know)**

Double-click a .deb file to open and install it in Eddy

Get popup dialog requesting Administrator password

Enter user's password; FAIL

Workaround: Set root password like so

Terminal
```
sudo passwd root
```

**Expected behavior**

GUI popup requests **logged in user's password** and that user, if the primary user, has sudo admin rights

**Other Notes**

**Comment by sramkrishna** [comment]
I was not able to reproduce this problem following your steps.  There must be something else happening here.

**Comment by poolpog** [comment]
Is there a newer release of PopOS? I am using the version I downloaded on Oct 19, 2017

**Comment by jackpot51** [comment]
Are you sure your user password doesn't work in that dialog?

**Comment by jsilverman-blispay** [comment]
I'm working on trying to reproduce this problem on a fresh install; I should be able to get a screenshot this evening.

I'm 100% positive that *my* password doesn't work, and only "root" password does. I've tried both, numerous times, and the first time, I had to actually go into a terminal and give root a  password since he didn't get one during installation.

This doesn't just affect Eddy -- it affects all calls to the GUI Sudo. So, any action that requires sudo and asks for it in the GUI

**Comment by poolpog** [comment]
Ok, so, I tried this using the same Oct 2017 .ISO (v45, I believe) in a Virtualbox VM

The problem is not reproducible. i.e. When I use Eddy or the Pop!_Shop I am asked for **my** password, not "Administrator"

Any ideas how my current desktop install got switched and/or why it is asking for Administrator?

Thanks

**Comment by poolpog** [comment]
![popos_administrator_bug](https://user-images.githubusercontent.com/1319389/34188095-81ddd6da-e502-11e7-8ba3-e933a3f5de76.png)

Screenshot with "Administrator"

**Comment by poolpog** [comment]
I'm working on trying to reproduce this problem on a fresh install; I should be able to get a screenshot this evening.

I'm 100% positive that my password doesn't work, and only "root" password does. I've tried both, numerous times, and the first time, I had to actually go into a terminal and give root a password since he didn't get one during installation.

This doesn't just affect Eddy -- it affects all calls to the GUI Sudo. So, any action that requires sudo and asks for it in the GUI

**Comment by sramkrishna** [comment]
Thanks for putting the effort in, anything helps.  We would definitely like to fix this problem!

**Comment by brs17** [comment]
With this issue having been inactive for a few months I am going to close it.

@poolpog If this issue is still causing issues for you (or if anyone else is having an issue) please provide additional information as we have been unable to reproduce this issue on our end.

**Comment by Dirk-c-Walter** [comment]
I have a user with the same problem, fresh system 76 laptop just arrived today. Not a good first impression.

**Comment by mmstick** [comment]
@Dirk-c-Walter The user account created during setup is the administrator account, so you only need to enter your password.

**Comment by bgiesbrecht** [comment]
For anyone facing the same issue, make sure that your user account is in the sudo group. I did some 'maintenance' and removed myself and had the same behaviour as the OP.
