### ISSUE TITLE
Upgrade from 18.04 to 19.10 disabled user-theme-extension and crashes to log-in screen when trying to re-enable it.

### ISSUE THREAD

**Issue by tre-x** [pop-os/pop#881]
**Distribution:**
`NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
`

**Related Application and/or Package Version:**
`gnome-shell:
  Installed: 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17
  Candidate: 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17
  Version table:
 *** 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     3.34.3-1ubuntu1~19.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
     3.34.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages
`

**Issue/Bug Description:**
I recently installed Pop_OS 18.04 over a Linux Mint installation on my dual-booted Windows 10 machine. Today I upgraded to 19.10 via _Settings>Details>About>OS Upgrade_. Upon successful installation and reboot, I logged in and was met with what seems to be a [gnome shell crash dialog](https://imgur.com/a/HmIMozu).

> Oh no! Something has gone wrong. A problem has occurred and the system can't recover. Please log out and try again.

I was able to login to my Desktop following another login attempt afterwards. But I noticed that all of my gnome shell themes were missing, and that `user-theme-extension` was disabled, after I had enabled it previously on my Pop 18.04 desktop, GNOME 3.23. 

I went onto the [Gnome Shell Extensions](https://extensions.gnome.org/) website to see if they were still installed, and they were, in fact all of them were enabled except for User Themes. I tried re-enabling User Themes, but nothing happened, and after a page refresh it was set back to disabled.

I then tried re-enabling `user-theme-extension` through `gnome-tweaks` under _Extensions>User themes_, and I was met with the crash dialog once again. 

**Notes:**
My previous Pop installation was Pop_OS 18.04 LTS **NVIDIA** 
I am using a laptop with Intel integrated graphics + NVIDIA Geforce GTX 1050ti.

**Comment by Daggerpov** [comment]
why is this closed? I have the same problem.
