### ISSUE TITLE
20.04 Change default background

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#884]
/usr/share/backgrounds/pop/kate-hazen-pop-retro1.png

**Comment by leviport** [comment]
If https://github.com/pop-os/pop/issues/885 is the direction we're going, shouldn't we pick a darker wallpaper? I know most people change it themselves, but those who don't probably don't want to put on sunglasses every time they switch to an empty workspace. Especially on the Adder. The thing makes me feel like Nosferatu opening the drapes at high noon when it's at full brightness.

**Comment by WatchMkr** [comment]
I tested this for installation and setup. It has nice color and contrast. I also tested dark wallpapers. There's then little contrast and it's gloomy.

We're still going for Pop. The two don't conflict.
