### ISSUE TITLE
20.04 Set dark mode by default

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#885]

**Comment by jackpot51** [comment]
Browser support is really, really poor for dark mode right now. Website support is even worse. Installing dark reader makes it better, but breaks a lot of sites. I wonder - what we can do to keep the user from being blinded every time they launch Firefox?

**Comment by mmstick** [comment]
What about an option to alternate between light and dark based on time of day? The light theme works best during the day, and dark theme works best at night (provided you avoid a web viewer).

I think the general population will want a light theme by default, though. Less risk of certain applications looking off if they're using custom styling.
