### ISSUE TITLE
Graphics switching option has dissapeared.

### ISSUE THREAD

**Issue by jesseregier** [pop-os/pop#893]
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

apt policy gnome-shell

gnome-shell:
  Installed: 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17
  Candidate: 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17
  Version table:
 *** 3.34.3-1ubuntu1~19.10.1pop1~1580755358~19.10~c75fa17 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main amd64 Packages
        100 /var/lib/dpkg/status
     3.34.3-1ubuntu1~19.10.1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages
     3.34.1-1ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu eoan/main amd64 Packages

**Issue/Bug Description:**

The graphic switching options has disappeared at some point. It seems like the issue is with GNOME shell. The GNOME shell extensions I had installed stopped working as well. I have reinstalled gnome-shell to no effect.

**Steps to reproduce (if you know):**

The option is not present.

**Expected behavior:**

**Other Notes:**

**Comment by crawfxrd** [comment]
The system76-power extension is probably disabled. You can enable it using GNOME Tweak Tool.

**Comment by jesseregier** [comment]
Yep, that was it. 
Thank you for your time Tim, much appreciated! Great distro BTW!
