### ISSUE TITLE
Valve Steam fail to start after upgrading nvidia driver to 440.64

### ISSUE THREAD

**Issue by ccll** [pop-os/pop#895]
**Distribution (run `cat /etc/os-release`):**
```
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
```
$ sudo apt policy steam
steam:i386:
  Installed: 1:1.0.0.59-4pop1~1553119860~19.10~0992314
  Candidate: 1:1.0.0.59-4pop1~1553119860~19.10~0992314
  Version table:
 *** 1:1.0.0.59-4pop1~1553119860~19.10~0992314 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
     1:1.0.0.54+repack-5ubuntu1 500
        500 http://mirrors.tuna.tsinghua.edu.cn/ubuntu eoan/multiverse i386 Package
```

**Issue/Bug Description:**
Steam used to work, but fail to start after recent nvidia driver update.

**Steps to reproduce (if you know):**

```
$ steam
Running Steam on ubuntu 19.10 64-bit
STEAM_RUNTIME is enabled automatically
Pins up-to-date!
/home/cailei/.steam/debian-installation/ubuntu12_32/steam -nominidumps -nobreakpad
[2020-04-04 17:18:38] Startup - updater built Feb 11 2020 19:26:28
SteamUpdateUI: An X Error occurred
X Error of failed request:  BadValue (integer parameter out of range for operation)
```

`glxinfo` also report error.
```
$ glxinfo
name of display: :1
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  96
  Current serial number in output stream:  97
```

Check for `libnvidia-gl-440:i386`:
```
$ sudo apt policy libnvidia-gl-440:i386
libnvidia-gl-440:i386:
  Installed: 440.64-1pop1~1585833700~19.10~ddf0d07
  Candidate: 440.64-1pop1~1585833700~19.10~ddf0d07
  Version table:
 *** 440.64-1pop1~1585833700~19.10~ddf0d07 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu eoan/main i386 Packages
        100 /var/lib/dpkg/status
```

**Expected behavior:**
Steam and glxinfo should run like before.

**Other Notes:**
Similar issues are found on Steam github issue board:
- https://github.com/ValveSoftware/steam-for-linux/issues/6789
- https://github.com/ValveSoftware/steam-for-linux/issues/6969
But none of the solutions worked for me.

**Comment by leviport** [comment]
I can't seem to reproduce this. I did a clean install of Pop!_OS 19.10 on the Adder WS and installed Steam. It opens as expected, and `glxinfo` does not report any errors.

**Comment by thorn-ale** [comment]
Hello,

I upgraded the nvidia driver this morning and had the same issue with all my OpenGL dependant applications. After restarting my computer the issue was solved.

**Comment by mmstick** [comment]
It's because your driver isn't being loaded. Make sure the kernel has loaded the same driver version as what's installed on the system.

**Comment by ccll** [comment]
The issue is gone for unknown reason, thanks for the help guys!
Closing.
