### ISSUE TITLE
Nvidia Optimus  - HDMI is not working

### ISSUE THREAD

**Issue by ijaure299** [pop-os/pop#906]
**Distribution (run `cat /etc/os-release`):**
 
 Pop OS 19.10
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

None

**Issue/Bug Description:**
When plugging an HDMI cable to my laptop (which running nvidia Optimus) and using intel+nvidia, the hdmi will only work when choosing Nvidia and not intel which requires me to reboot my laptop, on my Windows its automatically switches to Nvidia (I'm assuming that the port itself connected to the nvidia chip inside), is there a way to make it automatic? Thanks!

**Steps to reproduce (if you know):**
Running Lenovo Legion Y530, just plug an hdmi cable on a model with similar specs and see.

**Expected behavior:**
Automatically switch to the card which the HDMI port is connected to and make it work without too much hussle

**Other Notes:**
Thank you for your hard work Your distro is the only one I liked so far

**Comment by crawfxrd** [comment]
This is expected behavior. You cannot use displays connected to the dGPU when in Intel mode.

**Comment by ijaure299** [comment]
well I consider it as a bug because on I except my HDMI port to work out of the box without all the hassle, maybe Pop OS team can make it detect when I'm plugging my HDMI to switch to the Nvidia Chip automatically

**Comment by crawfxrd** [comment]
You _have_ to switch to NVIDIA mode and restart to use the ports connected to the dGPU.

On supported laptop models (ours) we have hotplug detection to prompt users to switch to NVIDIA mode if they plug in a display connected to the dGPU while in Intel or Hybrid mode.

But there's no getting around requiring a restart right now.

**Comment by ijaure299** [comment]
> You _have_ to switch to NVIDIA mode and restart to use the ports connected to the dGPU.
> 
> On supported laptop models (ours) we have hotplug detection to prompt users to switch to NVIDIA mode if they plug in a display connected to the dGPU while in Intel or Hybrid mode.
> 
> But there's no getting around requiring a restart right now.

:) well too bad..
