### ISSUE TITLE
Invalid signature for kernel

### ISSUE THREAD

**Issue by Vignesh-Nswamy** [pop-os/pop#908]
I am trying to dual boot Pop OS with Windows 10 and I have secure boot enabled. When I try to boot from a live USB i get the following error when I press "Try or Install Pop OS"
**error: /casper_pop-os_19.10_amd_intel_debug_191/vmlinuz.efi has invalid signature
error: you need to load the kernel first**

What am I doing wrong?

**Comment by bb4L** [comment]
I have the same issue

I followed this: https://medium.com/@mattzab_49257/how-to-make-a-pop-os-persistent-live-usb-f96e776dccc

But i didn't have to do the changes in the end... it already was like that

and when booting and selecting any of the options i get the same error as @Vignesh-Nswamy

**Comment by Vignesh-Nswamy** [comment]
@bb4L Apparently secure boot should be turned off before booting Pop OS. Consequence of Secure Boot is that, it does not allow any bootloader not signed by Microsoft to run.

**Comment by bb4L** [comment]
@Vignesh-Nswamy  this means you got it running?

will try it out soon thanks for the hint!

**Comment by Vignesh-Nswamy** [comment]
I don’t wanna turn off secure boot. So I didn’t try. But there’s a way to sign the kernel so the boot loader can run without secure boot being turned off. Haven’t tried yet.

**Comment by bb4L** [comment]
i tried with the LTS iso, same outcome...

how could you manually sign the kernel?

**Comment by daniellim051000** [comment]
Secure Boot is recommended to be turn off. Actually, secure boot was developed for Window. In order to stay away problem and trouble, just close it.

**Comment by mmstick** [comment]
Secure boot is not supported

**Comment by Faq** [comment]
just leaving it here for ref. https://pop-planet.info/forums/threads/any-way-of-signing-for-secure-boot.300/

**Comment by eguiajosue** [comment]
> @Vignesh-Nswamy  this means you got it running?
> 
> will try it out soon thanks for the hint!

It worked

**Comment by chadidi02** [comment]
https://www.reddit.com/r/pop_os/comments/gbkh4z/invalid_signature_and_kernel_error_messages_at/
