### ISSUE TITLE
Cannot fully disable automatic update checking

### ISSUE THREAD

**Issue by joey04** [pop-os/pop#91]
Using a VM install of 17.10 from a few days ago, I cannot disable the automatic update checks that occur during Pop startup. Using Wireshark on the host Windows, I can see that Pop checks the launchpad.net repos then open a TLS connection to developer.elementary.io. I'll then get a Gnome notice box if there are updates available.

I already disabled automatic checking via Synaptic's Settings->Repositories. Pop should honor that preference for startup as well.

edit: I did a Reload in Synaptic and as expected it only connected to the launchpad repos. That's how I want to manage updates going forward without any other update checks.

**Comment by sramkrishna** [comment]
What's the reason behind disabling it?  Is it slowing down the boot process or some other issue?

**Comment by joey04** [comment]
No issues, just a personal preference to manage updates manually.

I should note that the automatic update checking is an Ubuntu default. I hadn't noticed that before, but I've seen it there too.

**Comment by WatchMkr** [comment]
@joey04 Does setting "Automatically check for updates:" to "Never" in Software and Updates fix this issue for you?

**Comment by WatchMkr** [comment]
Scratch that. It appears that AppCenter and thus Pop!_Shop do not adhere to Software and Updates settings. We'll add this to the Pop!_shop repo and link here.

**Comment by WatchMkr** [comment]
Filed against Pop!_Shop here https://github.com/pop-os/shop/issues/38
