### ISSUE TITLE
"Always show workspaces" Extension shown error loading sign.

### ISSUE THREAD

**Issue by anick76** [pop-os/pop#916]
PopOS 20.04 Beta installed in my "HP - Spectre Folio 13 / i7 / 8GB" Everything seem to work just fine, except the "Always show workspaces" Extension can not turn on. It just said "Error loading extension" no matter what I do.

**Comment by brs17** [comment]
Thank you for filing this issue. This issue with the" Always show workspaces" extension is known, and currently tracked here: https://github.com/pop-os/gnome-shell-extension-always-show-workspaces/issues/5
