### ISSUE TITLE
Yellow text says "you may wish to update installer" when installing to a VM (iso 49)

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/pop#92]
via voodoof101 on Pop!_Chat

I always mess around with various os's in VM's in vmware and virtualbox. i was creating one yesterday and today, to test and tweak settings.. using iso 49 for intel. there is a brief yellow text on the intial Install Pop_OS 17.10 screen, that says.. you may wish to update installer.  (Bold area is yellow text) then disappears quickly

**Comment by brs17** [comment]
![install](https://user-images.githubusercontent.com/7460774/34050159-21983a38-e177-11e7-9e35-17666b641de8.jpg)

**Comment by sramkrishna** [comment]
This is a known issue, and we are working on a new installer.  See our blog for updates on this work.
