### ISSUE TITLE
Window Title Bar/Firefox

### ISSUE THREAD

**Issue by Comet-D-Monkey** [pop-os/pop#923]
**Distribution (run `cat /etc/os-release`):**
 Pop!_OS 20.04
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Extensions/Gnome Extensions/Firefox Installed: 75.0+build3-0ubuntu1

**Issue/Bug Description:**
Under the Pop Shell settings in the new Extensions feature added to GNOME the "Show Window Titles" option over-rides my option to disable the title bar in Firefox. I love Pop but am not a fan of tiling window managers, I would like to keep the title bars on and be able to move my windows around freely (float) and still have the option to disable the title bar in Firefox as normal.  

**Steps to reproduce (if you know):**
Open Extensions, open the settings for Pop Shell and turn on Show Window Titles.  Open Firefox and click Customize from the hamburger menu, uncheck Title Bar at the bottom.

**Expected behavior:**
The Extension feature over-rides the Firefox option and the Title Bar will remain even when disabled in Firefox.

**Other Notes:**
Thank you

**Comment by leviport** [comment]
Thank you for the report! This issue is being tracked here: https://github.com/pop-os/beta/issues/2
