### ISSUE TITLE
Applications installed not being found by IntelliJ (pop os 20.04 updated today)

### ISSUE THREAD

**Issue by mariobittencourt** [pop-os/pop#924]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04"
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

pycharm 2020.1 installed by pop.shop

**Issue/Bug Description:**

It says it cannot find node installed. When I open the dialog and go into /usr/bin it does not locate node executable.  If I go in the regular gnome terminal I can find and run the commend.

**Steps to reproduce (if you know):**

Open pycharm, open the terminal located on the lower bar. Type node.

$node --version
bash: node: command not found

**Expected behavior:**

v10.19.0

**Other Notes:**

If I use the version downloaded directly from jetbrains it works as expected.

**Comment by LLNet** [comment]
![image](https://user-images.githubusercontent.com/7931918/80416075-d1f20e80-88d3-11ea-8075-8124aba557ed.png)

if you use pop-shop you will installing flatpak version of "pycharm".

maybe some help/info here:
https://unix.stackexchange.com/questions/412869/how-to-allow-gui-application-in-flatpak-to-run-cli-tool

**Comment by mariobittencourt** [comment]
thank you. I wish this was somewhat easier or more evident.  I guess whoever knows the flatpak default behavior can spot this.
