### ISSUE TITLE
Pop related software tied to Python 2

### ISSUE THREAD

**Issue by btegs** [pop-os/pop#928]
When running apt in Pop_OS 20.03, I keep getting this warning:

`The following packages have been kept back: libpython2-stdlib python python2 python2-minimal`

Why are there Pop related packages still tied to Python 2? Can you update those to use Python 3 instead?

This is causing broken packages
```The following packages were automatically installed and are no longer required:
  python-certifi python-chardet python-idna python-pkg-resources
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libpython2-stdlib python
The following packages will be REMOVED:
  libpython-stdlib python-minimal
The following packages will be upgraded:
  libpython2-stdlib python
2 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
1 not fully installed or removed.
```
then
```
Unpacking python (2.7.17-2pop1~1580508288~20.04~6895a24) over (2.7.17-1) ...
dpkg: error processing archive /var/cache/apt/archives/python_2.7.17-2pop1~1580508288~20.04~6895a24_all.deb (--unpack):
 trying to overwrite '/usr/bin/python', which is also in package python-minimal 2.7.17-1
Errors were encountered while processing:
 /var/cache/apt/archives/python_2.7.17-2pop1~1580508288~20
```

I found out that I had to disable the Pop_OS PPAs and then removing the `python` related packages to get a stable system. I still had to have `python2` installed since there are other things dependent on it. Since Python 2 is not going to be supported anymore, the less reliance the better!

**Comment by leviport** [comment]
Thank you for the report! This appears to be the same issue as this one https://github.com/pop-os/beta/issues/74  so we'll be tracking it there.
