### ISSUE TITLE
Live Media doesn’t boot on Lemur (lemu6)

### ISSUE THREAD

**Issue by jlacroix82** [pop-os/pop#93]
**Issue/Bug Description**

PopOS live USB doesn’t start on the lemu6. Instead, the following error appears:

Can not mount /dev/loop0 (/cdrom/casper/filesystem.squashfs) on //filesystem.squashfs 

I tried reflashing the live usb several times, with both dd and etcher, same issue. I also tried the same USB on my Galago, and it does boot normally on that machine. The problem seems limited to the Lemur.

**Steps to reproduce (if you know)**

Press F7 to boot from USB
It won’t boot

**Expected behavior**

It should start the live media

**Other Notes**

**Comment by jlacroix82** [comment]
User error, closing. Sorry.

**Comment by clyver** [comment]
I'm currently trying to get past this issue on a Lenovo ThinkPad. I'm seeing exactly what you've described. Interestingly, I'm able to successfully live-boot Ubuntu 18. @jlacroix82, any chance you can shed some light on what worked for you? Thanks.

**Comment by jlacroix82** [comment]
For me, the issue was that I accidentally dd'd the ISO image to my hard drive. I removed the partition table from the disk, which solved it.

**Comment by clyver** [comment]
Thanks, @jlacroix82. I was able to resolve my issue by disabling `secure boot` in the UEFI.
