### ISSUE TITLE
Can't set monitors to portrait mode

### ISSUE THREAD

**Issue by kasbruh** [pop-os/pop#932]
**Distribution (run `cat /etc/os-release`):**
 20.04 LTS
 

**Issue/Bug Description:**
Cannot set monitors to portrait mode. When i apply settings it asks to keep or revert changes, but no changes happen.

**Steps to reproduce (if you know):**
Change monitor orientation in Display Settings

**Expected behavior:**
Monitor to be set to portrait mode.

**Other Notes:**
one 27" 1440p@144hz and one 24" 1080p@240hz.
solid work, people <3

**Comment by brs17** [comment]
Thank you for filing this issue, we are going to follow progress on this issue here: https://github.com/pop-os/pop/issues/933 (moved over from the beta repository)
