### ISSUE TITLE
chromium hardware accelerated video decode not working by default

### ISSUE THREAD

**Issue by shadywack** [pop-os/pop#943]
**Distribution (run `cat /etc/os-release`):**
  NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
chromium:
  Installed: 80.0.3987.149-1pop1
  Candidate: 80.0.3987.149-1pop1
  Version table:
 *** 80.0.3987.149-1pop1 1001
       1001 http://ppa.launchpad.net/system76/pop/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Hardware accelerated video decode not enabled by default. Have to run chromium --ignore-gpu-blacklist --enable-gpu-rasterization --enable-native-gpu-memory-buffers --enable-zero-copy from the command line to get it working.

This is on a Vega64 with the default Mesa drivers, not using a PPA.

**Steps to reproduce (if you know):**
Install Chromium, go to chrome://gpu, "Video Decode: Unavailable"
When using the command line parameters, "Video Decode: Available" is present, and hw accelerated VP9/h264 decoding functions.

**Expected behavior:**
Would like to see a way to get the flags into a config file that can stay persistent. On Arch, they make use of a chromium-flags.conf file that stays in the user's .local folder. When I try using a file like that, this build doesn't pick up those flags.

**Other Notes:**
Thank you for the awesome release of Pop_OS! If you can fix, great, much appreciated. Regardless, thanks for your time.

**Comment by mmstick** [comment]
It does require the full set of GPU acceleration features to be enabled, and Chrome blacklists graphics drivers that are known to have issues. So for now, we have to be happy with toggling some features to get it working on unsupported hardware.
