### ISSUE TITLE
Mouse Accelaration is on by default Pop OS 20.04

### ISSUE THREAD

**Issue by Oymate** [pop-os/pop#945]
Distribution NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

Related Application and/or Package Version (run apt policy $PACKAGE NAME):

Issue/Bug Description:
Mouse Accelaration is on by default
Giphy https://giphy.com/gifs/fSpC99mtw0WRxWj0J1

**Steps to reproduce (if you know):

    Upgrading from 19.04 to 20.04 Pop OS**

Expected behavior:
Mouse Accelaration should off be default

**Other Notes:
I was able to resolve the issue by following this guide.
http://www.webupd8.org/2016/08/how-to-completely-disable-mouse.html

>     To completely disable mouse acceleration, create a file called "50-mouse-acceleration.conf" in xorg.conf.d. The path to xorg.conf.d can vary depending on the Linux distribution you use. For instance, in Ubuntu, Linux Mint, and derivatives, it's /usr/share/X11/xorg.conf.d/. On Arch Linux, it's /etc/X11/xorg.conf.d/.
> 
>     To open an empty 50-mouse-acceleration.conf file in /usr/share/X11/xorg.conf.d/ with Nano (command line text editor; should be installed by default in most Linux distributions), use the following command:
> 
>     sudo nano /usr/share/X11/xorg.conf.d/50-mouse-acceleration.conf
> 
>     And in this file, paste the following:
> 
>     Section "InputClass"
>     Identifier "My Mouse"
>     MatchIsPointer "yes"
>     Option "AccelerationProfile" "-1"
>     Option "AccelerationScheme" "none"
>     Option "AccelSpeed" "-1"
>     EndSection
> 
>     Then save the file (to save the file in Nano, use Ctrl + o, then press Enter; to exit, use Ctrl + x). Note that the section just needs an identifier, but the actual name doesn't matter, so you don't have to replace "My Mouse" with anything.
> 
>     Once you're done, restart the session (logout/login). That's it!
> 
>     Using this, the Touchpad acceleration is left unchanged.

I also opened [an issue](https://github.com/pop-os/default-settings/issues/85) in the default setting part of the project as I was unsure where to post this. Thank you for such a great OS again :)

**

**Comment by leviport** [comment]
Thanks for the report. The first issue is sufficient, so I'll close this one.

**Comment by Oymate** [comment]
Thanks!
