### ISSUE TITLE
systemctl isolate multi-user.target fails to funciton

### ISSUE THREAD

**Issue by BTBlueSkies** [pop-os/pop#947]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**
sudo systemctl isolate multi-user.target fails to switch out of GUI to terminal

**Steps to reproduce (if you know):**
sudo systemctl isolate multi-user.target from gui term

**Expected behavior:**
drop out of graphical mode into terminal

**Other Notes:**

ryzen 3900x with dual nvidia rtx 2080 TI's

**Comment by sawyermade** [comment]
I am having the same exact problem and have basically the same setup you have. I fucking hate Pop!_OS

**Comment by JOT85** [comment]
This has been fixed by https://github.com/pop-os/upgrade/pull/121

> I am having the same exact problem and have basically the same setup you have. Then if you try to remove gdm3 it gives you a bunch of crap. I fucking hate Pop!_OS.

@sawyermade there was no need for that last sentance.

**Comment by BTBlueSkies** [comment]
I was able to test this successfully. One note, setting the console font was unclear. I had to edit the /etc/default/console-setup file and change the font size there to get a readable font on my system as the default 16x32 was way too big.

thanks for the fix!
