### ISSUE TITLE
 battery: extension failed to load:ASUS Battery Extension

### ISSUE THREAD

**Issue by emretuna** [pop-os/pop#960]
6.342679 battery: extension failed to load:ASUS Battery Extension

After clean install Pop Os 20.04 receiving this error while system boots.Model: Asus GL503VS

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Comment by leviport** [comment]
If you're talking about a gnome-shell extension, it probably just hasn't been updated to Gnome 3.36 yet by the extension maintainers. Many extensions lag behind Gnome releases for a time.

**Comment by emretuna** [comment]
> If you're talking about a gnome-shell extension, it probably just hasn't been updated to Gnome 3.36 yet by the extension maintainers. Many extensions lag behind Gnome releases for a time.

It gives error at boot, not in gnome logs.I don't think it's related with gnome extension maybe about kernel.

**Comment by leviport** [comment]
When you see this error, what is the behavior? Does it prevent your machine from booting?

**Comment by emretuna** [comment]
> When you see this error, what is the behavior? Does it prevent your machine from booting?

No it doesn't effect anything on the system (as I observed) booting normally, but maybe an unobserved problem may occur.I have no idea about it,maybe related with new Asus support coming with kernel 5.4.
[Here](https://www.reddit.com/r/pop_os/comments/gbh22n/not_a_big_error_but_receiving_this_after_clean/) you can see the image of error from the post I opened on reddit.

**Comment by emretuna** [comment]
UPDATE:
PC not booting on battery, if not plugged in stuck on boot with a text Job running Hold...

**Comment by faedy2** [comment]
> UPDATE:
> PC not booting on battery, if not plugged in stuck on boot with a text Job running Hold...

What I am assuming is going on is that you are booting to a gray screen when you aren't plugged in, correct?
Here is what I do. I am also on an ASUS machine (GL703VM), and sometimes my system will do this even if I am plugged in, but almost 100% of the time if I am unplugged.

Workaround:
1. Hit '3' on numpad
2. Hit 'CTRL+ALT+F4'
3. Hit 'CTRL+ALT+F1'
3. You should now be on the login screen for PopOS
