### ISSUE TITLE
Lock Screen background image issue

### ISSUE THREAD

**Issue by KTran-Tech** [pop-os/pop#962]
![Screenshot from 2020-05-02 10-45-32](https://user-images.githubusercontent.com/48570648/80868744-1843c680-8c62-11ea-8724-dc987a3cef14.png)

**Distribution (run `cat /etc/os-release`):**
 
 Pop_Os 20.04
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Background in Appearance settings no longer support change lock screen background images only desktop images. Previous os version had this feature.

**Steps to reproduce (if you know):**

**Expected behavior:**

When left clicking on the provided Pop_Os provided images it should display a menu to ask whether or not you want it to change the background wallpaper for both lockscreen and and desktop images, or for one of either.

**Other Notes:**

If by any chance there is a way to change the lock screen wallpaper, its a very bad idea to do that as it is harder for anyone to find it themselves. By putting that feature on demand in Appearance ---> Background, it makes it easier for people to change the lock screen without having to waste time.

**Comment by WatchMkr** [comment]
Thanks for your issue report. This was removed in GNOME due to the new lockscreen in GNOME 3.36 now matching a blurred version of the desktop wallpaper.

**Comment by donniehanna** [comment]
This is a new gnome 3.36 feature, it doesn't allow to set both background and lock screen image separately, it set the same image for both and blurs the lock screen image.
https://itsfoss.com/gnome-3-36-release/
