### ISSUE TITLE
remove python and always freezout the screen using the gnome

### ISSUE THREAD

**Issue by crisywini** [pop-os/pop#970]
**Distribution (pop!_os 20.04):**
 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

**Steps to reproduce (if you know):**

**Expected behavior:**

**Other Notes:**

**Comment by mmstick** [comment]
Issue unclear. Can you describe the issue?

**Comment by crisywini** [comment]
sorry I am new in this, I upgrade the O.S but my ides and the gnome was like freezing, but I have to refresh the installation so everything is working now, the only problem is that I lost some important data.
