### ISSUE TITLE
Missing Pop! OS logo everywhere

### ISSUE THREAD

**Issue by defecador** [pop-os/pop#975]
**Distribution (run `cat /etc/os-release`):**
 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**Issue/Bug Description:**

Pop! OS logo is missing.

**Steps to reproduce (if you know):**

execute screenfetch, or go to "About" under "Settings" or go to installed Updates

**Expected behavior:**

See the right Pop! OS logo.

**Other Notes:**

![Screenshot from 2020-05-04 13-26-16](https://user-images.githubusercontent.com/57116457/80961332-05b8c100-8e0b-11ea-8725-90bfb7ffd36f.png)
![Screenshot from 2020-05-04 13-28-04](https://user-images.githubusercontent.com/57116457/80961366-19642780-8e0b-11ea-8c5c-2a30f9241237.png)
![Screenshot from 2020-05-04 13-28-45](https://user-images.githubusercontent.com/57116457/80961397-313bab80-8e0b-11ea-960a-1d920f60b6eb.png)

**Comment by mmstick** [comment]
Set your icon theme to the Pop icon theme, and the logo will come back.
