### ISSUE TITLE
Keyboard and mouse not working after upgrade to 20.04 from 19.04 and enabling tiling

### ISSUE THREAD

**Issue by mirkojotic** [pop-os/pop#977]
**Distribution (run `cat /etc/os-release`):**
 Pop-OS 20.04 (I just upgraded, but I'm unable to run the actual command due to this issue)
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
Upgraded to 20.04 from 19.04. After enabling tiling my keyboard and mouse do not work. If I drop into bios and boot loader I can use the keyboard. But after booting up I cannot unlock the computer because the keyboard won't work.

**Steps to reproduce (if you know):**
Oh I'm sure it's a me problem but there's no reasources out there on how to handle it and I'm kinda stuck without a computer atm. 

**Expected behavior:**
I'd expect to be able use my keyboard and/or mouse even if tiling mode is enabled. If I cannot I'd gladly revert back but I'm unable to log on :)

**Other Notes:**
Nothing else.

**Comment by mmstick** [comment]
This is the first I've heard of this issue. Does it happen in a live ISO of 20.04? Perhaps an extension gone wrong somewhere?

**Comment by mirkojotic** [comment]
Yeah, I wouldn't be surprised if it's very specific to me. I haven't tried anything else as after I started experiencing the issue... well I couldn't do anything else. I'm going to have to reinstall pop-OS unfortunatelly.

I wasn't able to find anyone else that experienced the same issue so feel free to close the issue. I was just raising awareness just in case.

Sorry for the trouble.
