### ISSUE TITLE
Unable to disable icons on the desktop

### ISSUE THREAD

**Issue by LL83** [pop-os/pop#978]
**Distribution:**

 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

**Related Application and/or Package Version:**

https://extensions.gnome.org/extension/1465/desktop-icons/

**Issue/Bug Description:**

After upgrading from Pop!_OS 18.04 to 20.04, icons are shown on the desktop. There now seems to be an extension installed that appears to be a 'System Extension', which cannot be removed (except by removing pop-desktop also). This extension has a permanent update-icon next to it on the extension-website: updating or disabling it doesn't seem to have any effect.

![Screenshot from 2020-05-05 00-28-43](https://user-images.githubusercontent.com/41305461/81019687-72fa3f80-8e67-11ea-91bd-44228cdebd1d.png)

**Steps to reproduce:**

Try disabling desktop icons by turning off the switch on the extensions-website, or try updating this extension.

**Expected behavior:**

Updating the extension should result in an actual update, and, actually, I'd expect to be able to disable this extension altogether in order to prevent icons from showing on the desktop.

**Comment by crawfxrd** [comment]
Use GNOME Extensions to manage extensions in 20.04. Disable Desktop Icons from there.

**Comment by LL83** [comment]
Crawfxrd's solution seems to be working now. Closing the issue.

**Comment by aryehw** [comment]
I have this problem, running 20.04.  Disabling the desktop icons in Gnome Extensions has no effect. 
In addition, I cannot auto-arrange the icons. I have to drag them individually.

It is a recent problem, apparently caused by a recent upgrade, but I cannot say what exactly caused it.

**Comment by LL83** [comment]
> I have this problem, running 20.04. Disabling the desktop icons in Gnome Extensions has no effect.
> In addition, I cannot auto-arrange the icons. I have to drag them individually.
> 
> It is a recent problem, apparently caused by a recent upgrade, but I cannot say what exactly caused it.

In a recent update, I think the developers pushed  a system extension called _Desktop Icons NG (DING)_. Is it possible that you checked another extension? For the added extension you have to scroll down and look under _Built In_ in the extensions application in your system. Disbling that by unchecking the extension will probably fix the issue (again) - I also ran into this problem this week.

**Comment by aryehw** [comment]
Thank you for your quick response.
The extension is in fact called Desktop icons ng (ding)
Changing its state has no effect.
I tried uninstalling it -- icons remain. Tried re-installing , tried uninstalling and installing a different desktop icon extension -- no change.
What is really aggravating is that there is nothing in the setting to auto-arrange the icons, so they are spread over two displays with no special order.
What I will probably do as a workaround is move everything out of the Desktop folder.

**Comment by LL83** [comment]
> Thank you for your quick response.
> The extension is in fact called Desktop icons ng (ding).
> Did not find anything called biult-in.
> Changing its state has no effect.
> I tried uninstalling it -- icons remain. Tried re-installing , tried uninstalling and installing a different desktop icon extension -- no change.
> What is really aggravating is that there is nothing in the setting to auto-arrange the icons, so they are spread over two displays with no special order.
> What I will probably do as a workaround is move everything out of the Desktop folder.

![Screenshot from 2021-01-28 10-35-11](https://user-images.githubusercontent.com/41305461/106118681-aba81a80-6154-11eb-8c44-15365e599ae2.png)
How did you try uninstalling it? It might be that you have to scoll down in the extensions-app tot see the _Buiklt In_ section. Also, changing it via the webrowser doesn' t work - in case that' s what you're trying.

**Comment by aryehw** [comment]
I was using the browser. 
I do not see the built in section - I am using gnome-tweaks. Should I be using something else?
![image](https://user-images.githubusercontent.com/9643344/106121306-1b6fd280-6160-11eb-9492-91ac40af1beb.png)

**Comment by aryehw** [comment]
Ok - I found the Extensions  app that appears to be what you showed.
I removed the extension.
The icons are still there - maybe they will disappear after a reboot.

**Comment by LL83** [comment]
> Ok - I found the Extensions app that appears to be what you showed.
> I removed the extension.
> 
> After logging out and logging in the icons are gone.
> Removing the extension using Extensions worked.
> Thank you for your assistance

You're more than welcome. By removing, I assume you meant disabling it.

**Comment by aryehw** [comment]
Actually, I removed it. Simply turning it off did not help, but that may be because I did not log out and log in, so maybe it would have worked if I had done that.
For most extensions, I an used to seeing the result immediately, so I did not think to log out and in until I saw that even removing it did not work.

**Comment by LL83** [comment]
> Actually, I removed it. Simply turning it off did not help, but that may be because I did not log out and log in, so maybe it would have worked if I had done that.
> For most extensions, I an used to seeing the result immediately, so I did not think to log out and in until I saw that even removing it did not work.

How did you remove the extension? Because it is not possible (as far as I know) to remove the extensions listed under _Built-In_, in the GUI showed on the screenshot I posted earlier. Also, disabling it should take effect immediately.

**Comment by aryehw** [comment]
It appeared in the Manually installed section, and for there I removed it. 
At that point it was removed, but nothing had changed. Then I logged out and logged in, and the icons were gone.
Now it has reappeared in the Built In section, and there it does behave as expected.
I suspect that I had a second version that somehow covered the Built In version, and by removing that it got back to normal.

**Comment by LL83** [comment]
> It appeared in the Manually installed section, and for there I removed it.
> At that point it was removed, but nothing had changed. Then I logged out and logged in, and the icons were gone.
> Now it has reappeared in the Built In section, and there it does behave as expected.
> I suspect that I had a second version that somehow covered the Built In version, and by removing that it got back to normal.

Ah, that's strange. But nice that you're having a clean desktop again:)
