### ISSUE TITLE
Gnome-Tweaks: Desktop icons toggle switch not working

### ISSUE THREAD

**Issue by oodsway** [pop-os/pop#979]
**Distribution (run `cat /etc/os-release`):**
### 
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
gnome-tweaks:
  Installed: 3.34.0-2ubuntu1
  Candidate: 3.34.0-2ubuntu1
  Version table:
 *** 3.34.0-2ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu focal/universe i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Desktop icons should appear or disappear depending on state of toggle in Gnome-tweaks > Extensions > Desktop icons

**Steps to reproduce (if you know):**
~$ sudo apt install gnome-tweaks
Create a file and a directory on Desktop
Open Gnome-Tweaks > Extensions
Toggle Desktop icons switch

**Expected behavior:**
Desktop Icons appear | disappear depending on toggle position

**Other Notes:**
Desktop icons gear settings that show | hide home, recycle bin, and change icon size work. 
Hide | view Desktop icons does not work.

I confirmed that hide | view Desktop icons works in pop_OS 19.10. 

I've tested this from clean install of 20.04, and upgrade from 19.10.

**Comment by crawfxrd** [comment]
Use GNOME Extensions in 20.04 to manage extensions.  Extension support will be removed from Tweaks in the future ([GNOME/gnome-tweaks!50](https://gitlab.gnome.org/GNOME/gnome-tweaks/-/merge_requests/50)).

**Comment by oodsway** [comment]
Thank you!
Works perfectly with Extensions (built in). 
Closing.
