### ISSUE TITLE
Firefox again with double buttons in title bar only in SPANISH

### ISSUE THREAD

**Issue by evil-arri** [pop-os/pop#981]
**Distribution (run `cat /etc/os-release`):**
 NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
firefox:
  Instalados: 75.0+build3-0ubuntu1
  Candidato:  75.0+build3-0ubuntu1
  Tabla de versión:
 *** 75.0+build3-0ubuntu1 500
        500 http://us.archive.ubuntu.com/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**
Same old bug since 20.04. When removing the title bar I get a double bar but on "SPANISH".
I already checked it out with the language set to english and the bug is simply not there, but since I use the system set to spanish I still have the bug.
![Captura de pantalla de 2020-05-05 00-54-42](https://user-images.githubusercontent.com/56842169/81036014-67a91300-8e6b-11ea-9976-dbbae12bf9f0.png)

**Steps to reproduce (if you know):**
Just set Firefox in customization without title bar and double bars get activated

**Expected behavior:**
It should remove the title bar.

**Other Notes:**
Maybe not too many reports about this since I don't think there is a lot of people using Pop_OS! in Spanish...

**Comment by mdirksen** [comment]
Same issue in French.

**Comment by isamu1024** [comment]
Same issue with French too.
Only issue is to disable pop shell.

**Comment by jackpot51** [comment]
@mmstick we should use wm_class for the titlebar fix instead of title

**Comment by evil-arri** [comment]
Finally fixed in today's update.
