### ISSUE TITLE
Keyboard shortcuts freezing and secondary input sources lose shortcuts

### ISSUE THREAD

**Issue by allentje** [pop-os/pop#982]
**Distribution (run `cat /etc/os-release`):**
Upgrade

NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
N/A

**Issue/Bug Description:**
There are two issues I have been facing since upgrading.

Issue 1
I have two different keyboard layouts/input sources
English (US)
German

When I switch to second input source all the standard shortcuts keys stop working.
I can't copy, paste, open a new tab, super key. Nothing.
I have seem that the super key button detects a press but it doesn't run the regular behavior. 

If I reorder e.g German as the first input source then I can get the shortcuts working but then I lose them for the English source due to it set to the second position.

Issue 2
The first input source has no problem with 2 key shortcut presses but as soon as I try to run 3 key shortcuts the system doesn't detect them half of the time.
If I press them a few times then the system will sometimes detect them.
This makes copying from and pasting into terminal windows near impossible as well as selecting text.

- ctrl+shift+c
- ctrl+shift+v
- ctrl+shift+t
- ctrl+shift+(left/right)
- ctrl+shift+o (Jetbrains IDE)

**Steps to reproduce (if you know):**
Upgrade from 19.10

**Expected behavior:**
To have the second input source shortcut keys work
To have a consistent behaviour with 3 key shortcut commands.

**Other Notes:**
- I tried removing gnome tweaks to see if it would have an impact and it didn't.
- Clean install isn't really a preferable option due to it being my business laptop

**Comment by fkastner** [comment]
I face the same issue with secondary input sources (issue 1). Ctrl-based shortcuts don't work unless the first input source is selected. Also <Super> alone doesn't show the overview.
I too upgraded from 19.10.

**Comment by haspok** [comment]
Here is the relevant Gnome Mutter bug:
https://gitlab.gnome.org/GNOME/mutter/-/issues/1144
Fixed in 3.36.2, Pop-OS should upgrade or backport and the issue will be resolved.

**Comment by fkastner** [comment]
I think this can be closed now.
@allentje can you confirm that you don't see this behaviour anymore?

**Comment by allentje** [comment]
@fkastner I actually had this issue up until I switched my OS which was around May of last year (2021).
This also means I can no longer confirm or deny if this is still an issue.
