### ISSUE TITLE
The new launcher's shortcut doesn't work in Italian keyboard

### ISSUE THREAD

**Issue by PyGera** [pop-os/pop#984]
**Distribution (run `cat /etc/os-release`):**

NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os

 
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

Nothing

**Issue/Bug Description:**

I can't use the new version's launcher because the shortcut `Super + /` is impossible to do with my Italian Keyboard. I've tried to use `Super + \` but it does the same thing as `Alt + Tab`

**Steps to reproduce (if you know):**

1) Use an Italian keyboard
2) Try `Super + /` or `Super + \`

**Expected behavior:**

I want to use the new launcher

**Other Notes:**

Nothing

**Comment by crawfxrd** [comment]
Tracked in pop-os/shell#196.
