### ISSUE TITLE
Hotkeys for resizing a tiled window act backwards and also do not make sense

### ISSUE THREAD

**Issue by julianlam** [pop-os/pop#986]
**Distribution (run `cat /etc/os-release`):**

``` 
NAME="Pop!_OS"
VERSION="20.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04"
VERSION_ID="20.04"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Issue/Bug Description:**

The hotkeys mention (under "Move, resize and swap windows") that `Shift-right` and `Shift-down` increase a window size, and `Shift-left` and `Shift-up` decrease a window size.

1. The keys act backwards. If your window is top-right, shift-left and shift-down make your window smaller, and the opposite make your window bigger.
2. The hotkey combinations are position-dependent, so "left" and "down" don't always mean "decrease window size", i.e. if your window is at the top-right quadrant.

![image](https://user-images.githubusercontent.com/923011/81071920-63a0e380-8eb3-11ea-8f66-868cd05c867d.png)

Also I just noticed, but the hints are showing both "down" for increase and decrease.

**Comment by WatchMkr** [comment]
Thanks for the issue report. A fix for the inconsistent resizing behavior is in QA. The shortcut typo is fixed. Running updates will pull in the latest for that one.
